Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-04, with the labels that each got.

#290 Added a maintainers file
  MAINTAINERS.md
Labels: docs

#288 [Tests] ciGroup1 func test fixes
  src/plugins/timeline/public/directives/timeline_help/timeline_help.html
  test/functional/apps/timeline/_expression_typeahead.js
Labels: >Fork, test:functional

#291 [Tests] ciGroup2 functional test fixes
  src/plugins/saved_objects_management/public/lib/resolve_saved_objects.test.ts
  src/plugins/saved_objects_management/public/lib/resolve_saved_objects.ts
  test/functional/apps/dashboard/create_and_add_embeddables.js
  test/functional/apps/dashboard/dashboard_back_button.ts
  test/functional/apps/dashboard/dashboard_error_handling.ts
  test/functional/apps/dashboard/dashboard_filter_bar.js
  test/functional/apps/dashboard/dashboard_filtering.js
  test/functional/apps/dashboard/dashboard_grid.js
  test/functional/apps/dashboard/dashboard_options.js
  test/functional/apps/dashboard/dashboard_query_bar.js
  test/functional/apps/dashboard/dashboard_saved_query.js
  test/functional/apps/dashboard/dashboard_snapshots.js
  test/functional/apps/dashboard/data_shared_attributes.js
  test/functional/apps/dashboard/edit_embeddable_redirects.js
  test/functional/apps/dashboard/edit_visualizations.js
  test/functional/apps/dashboard/embed_mode.js
  test/functional/apps/dashboard/embeddable_rendering.js
  test/functional/apps/dashboard/empty_dashboard.js
  test/functional/apps/dashboard/full_screen_mode.js
  test/functional/apps/dashboard/legacy_urls.ts
  test/functional/apps/dashboard/panel_expand_toggle.js
  test/functional/apps/dashboard/time_zones.js
  test/functional/apps/dashboard/url_field_formatter.ts
  test/functional/apps/dashboard/view_edit.js
Labels: >Fork, test:functional

#292 Change Version to 1.0.0
  package.json
Labels: Build, Versioning

#305 Added link to MAINTAINERS.md from the Contributing guide
  CONTRIBUTING.md
Labels: docs

#308 [BUILD] Maps service config
  src/plugins/maps_legacy/config.ts
  src/plugins/maps_legacy/public/map/base_maps_visualization.js
  src/plugins/maps_legacy/public/map/service_settings.js
  src/plugins/maps_legacy/public/map/service_settings.test.js
  src/plugins/maps_legacy/server/index.ts
Labels: >Fork, bug, rename

#310 Change x86_64 to x64 and aarch64 to arm64 following industry conventions
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
  packages/osd-opensearch/src/custom_snapshots.js
  src/dev/build/lib/build.test.ts
  src/dev/build/lib/platform.test.ts
  src/dev/build/lib/platform.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
  src/dev/build/tasks/os_packages/create_os_package_tasks.ts
  src/dev/build/tasks/os_packages/docker_generator/run.ts
  src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
  src/plugins/home/server/tutorials/instructions/auditbeat_instructions.ts
  src/plugins/home/server/tutorials/instructions/filebeat_instructions.ts
  src/plugins/home/server/tutorials/instructions/functionbeat_instructions.ts
  src/plugins/home/server/tutorials/instructions/heartbeat_instructions.ts
  src/plugins/home/server/tutorials/instructions/metricbeat_instructions.ts
  src/plugins/vis_type_vislib/public/fixtures/mock_data/filters/_columns.js
  src/plugins/vis_type_vislib/public/fixtures/mock_data/range/_rows.js
  tasks/config/run.js
Labels: rename

#312 [Bug]Fix version conflict for plugins
  packages/osd-plugin-helpers/src/cli.ts
Labels: Build, Plugins, bug

#316 [RENAME] Fix typo in renamed filename in dev script
  src/dev/build/tasks/bin/scripts/opensearch-dashboards-plugin
Labels: bug, rename

#302 Rename files on disk needed for systemd and service start.
  src/dev/build/tasks/os_packages/run_fpm.ts
  src/dev/build/tasks/os_packages/service_templates/systemd/etc/systemd/system/opensearch-dashboards.service
  src/dev/build/tasks/os_packages/service_templates/systemd/usr/lib/tmpfiles.d/opensearch-dashboards.conf
  src/dev/build/tasks/os_packages/service_templates/sysv/etc/default/opensearch-dashboards
  src/dev/build/tasks/os_packages/service_templates/sysv/etc/init.d/opensearch-dashboards
Labels: Build, bug, rename

#313 Fix functional tests
  test/common/config.js
  test/functional/apps/management/_test_huge_fields.js
  test/functional/fixtures/opensearch_archiver/large_fields/data.json.gz
  test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights/data.json.gz
  test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights/mappings.json
  test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights_index_pattern/data.json.gz
Labels: rename, test:functional

#318 [Tests] Fix integration test due to code change in osd-plugin-helper
  packages/osd-plugin-helpers/src/integration_tests/build.test.ts
Labels: bug, test:integration

#323 Update map client
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
  src/legacy/server/config/schema.js
  src/plugins/maps_legacy/config.ts
  src/plugins/maps_legacy/public/__tests__/map/ems_mocks/sample_files.json
  src/plugins/maps_legacy/public/common/opensearch_maps_client.js
  src/plugins/maps_legacy/public/map/map_messages.js
  src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
  src/plugins/maps_legacy/public/map/service_settings.js
  src/plugins/maps_legacy/public/map/service_settings.test.js
  src/plugins/maps_legacy/server/index.ts
  src/plugins/region_map/public/choropleth_layer.js
  src/plugins/region_map/public/components/region_map_options.tsx
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/visualize/_region_map.js
  test/functional/apps/visualize/_tile_map.js
Labels: bug
