Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-05, with the labels that each got.

#337 [Bug] Replace EuiLoadingElastic to EuiLoadingSpinner
  src/plugins/newsfeed/public/components/__snapshots__/loading_news.test.tsx.snap
  src/plugins/newsfeed/public/components/loading_news.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: bug

#350 [BUILD] Update notice generator
  src/dev/build/tasks/notice_file_task.ts
  src/dev/notice/generate_notice_from_source.ts
Labels: rename

#341 [Rename] remove remaining references
  src/core/server/saved_objects/status.test.ts
  src/core/server/saved_objects/status.ts
  src/legacy/server/config/schema.js
  src/plugins/maps_legacy/config.ts
  test/api_integration/fixtures/import.ndjson
Labels: >Fork, rename

#355 Auto-focus on the Field input when clicking Add filter
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
Labels: Beta, bug

#369 Update favicons with new OpenSearch branding
  src/core/server/core_app/assets/favicons/android-chrome-192x192.png
  src/core/server/core_app/assets/favicons/android-chrome-512x512.png
  src/core/server/core_app/assets/favicons/android-chrome-heatmap-192x192.png
  src/core/server/core_app/assets/favicons/android-chrome-heatmap-256x256.png
  src/core/server/core_app/assets/favicons/apple-touch-icon-heatmap.png
  src/core/server/core_app/assets/favicons/apple-touch-icon.png
  src/core/server/core_app/assets/favicons/browserconfig.xml
  src/core/server/core_app/assets/favicons/favicon-16x16.png
  src/core/server/core_app/assets/favicons/favicon-32x32.png
  src/core/server/core_app/assets/favicons/favicon-heatmap-16x16.png
  src/core/server/core_app/assets/favicons/favicon-heatmap-32x32.png
  src/core/server/core_app/assets/favicons/favicon-heatmap.ico
  src/core/server/core_app/assets/favicons/favicon.ico
  src/core/server/core_app/assets/favicons/manifest.json
  src/core/server/core_app/assets/favicons/mstile-144x144.png
  src/core/server/core_app/assets/favicons/mstile-150x150.png
  src/core/server/core_app/assets/favicons/mstile-310x150.png
  src/core/server/core_app/assets/favicons/mstile-310x310.png
  src/core/server/core_app/assets/favicons/mstile-70x70.png
  src/core/server/core_app/assets/favicons/mstile-heatmap-150x150.png
  src/core/server/core_app/assets/favicons/safari-pinned-tab-heatmap.svg
  src/core/server/core_app/assets/favicons/safari-pinned-tab.svg
  src/core/server/core_app/integration_tests/static_assets.test.ts
  src/core/server/rendering/views/template.tsx
  src/dev/precommit_hook/casing_check_config.js
  src/plugins/index_pattern_management/public/components/field_editor/components/field_format_editor/editors/url/__snapshots__/url_template_flyout.test.tsx.snap
  src/plugins/index_pattern_management/public/components/field_editor/components/field_format_editor/editors/url/url_template_flyout.tsx
Labels: branding

#376 Update logos site-wide with new OpenSearch branding
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_logo_darkmode.tsx
  src/core/public/chrome/ui/header/header_logo.tsx
  src/core/public/core_app/styles/_mixins.scss
  src/core/server/rendering/views/template.tsx
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/home/public/application/components/__snapshots__/welcome.test.tsx.snap
  src/plugins/home/public/application/components/welcome.tsx
  src/plugins/home/public/assets/logos/opensearch_mark_centered.svg
  src/plugins/home/public/assets/logos/opensearch_mark_darkmode.svg
  src/plugins/home/public/assets/logos/opensearch_mark_default.svg
  src/plugins/home/server/index.ts
  src/plugins/home/server/tutorials/opensearch_logs/index.ts
  src/plugins/home/server/tutorials/opensearch_metrics/index.ts
  src/plugins/management/public/plugin.ts
  src/plugins/opensearch_dashboards_react/public/exit_full_screen_button/__snapshots__/exit_full_screen_button.test.tsx.snap
  src/plugins/opensearch_dashboards_react/public/exit_full_screen_button/exit_full_screen_button.tsx
Labels: branding

#382 Fix beta doc links, truncated help menu label
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/doc_links/doc_links_service.test.ts
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
Labels: bug
