Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-06, with the labels that each got.

#391 [Purify] remove upsells and branding from pre-fork
  src/core/server/rendering/views/styles.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/home/server/services/sample_data/data_sets/logs/logs.json.gz
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/empty_state.tsx
  src/plugins/maps_legacy/public/components/legacy_map_deprecation_message.tsx
  src/plugins/maps_legacy/public/index.ts
  src/plugins/maps_legacy/public/map/map_messages.js
  src/plugins/region_map/public/get_deprecation_message.tsx
  src/plugins/region_map/public/region_map_type.js
  src/plugins/tile_map/public/get_deprecation_message.tsx
  src/plugins/tile_map/public/tile_map_type.js
  src/plugins/tile_map/public/tile_map_visualization.js
Labels: >Fork, branding

#387 Add SVG logo spinner
  src/core/server/rendering/views/template.tsx
  src/plugins/home/public/application/components/_solutions_section.scss
Labels: branding

#441 [Build] fix icons in stack management
  src/plugins/data/public/ui/typeahead/__snapshots__/suggestion_component.test.tsx.snap
  src/plugins/data/public/ui/typeahead/suggestion_component.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
Labels: Build, branding

#442 [Build] fix overview and default app titles
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: Build, branding

#443 [Build] fix overview default route
  src/core/server/core_app/core_app.ts
  src/core/server/core_app/integration_tests/default_route_provider_config.test.ts
Labels: Build, backwards-compatibility

#392 [Patch] Graphite SSRF patch
  config/opensearch_dashboards.yml
  package.json
  src/plugins/vis_type_timeline/config.ts
  src/plugins/vis_type_timeline/server/index.ts
  src/plugins/vis_type_timeline/server/lib/config_manager.ts
  src/plugins/vis_type_timeline/server/plugin.ts
  src/plugins/vis_type_timeline/server/routes/run.ts
  src/plugins/vis_type_timeline/server/series_functions/fixtures/tl_config.js
  src/plugins/vis_type_timeline/server/series_functions/graphite.js
  src/plugins/vis_type_timeline/server/series_functions/graphite.test.js
  src/plugins/vis_type_timeline/server/series_functions/helpers/graphite_helper.js
  src/plugins/vis_type_timeline/server/series_functions/helpers/graphite_helper.test.js
  yarn.lock
Labels: patch

#445 [Build] Reduce yarn bootstrap warnings
  package.json
  yarn.lock
Labels: Build

#449 Remove unused dependencies left over from x-pack
  package.json
  yarn.lock
Labels: dependencies, xpack-cleanup

#463 Implement optimized healthcheck for Dashboards
  config/opensearch_dashboards.yml
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/core/server/opensearch/opensearch_service.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: Migration, bug

#464 Temporarily remove Tutorials from "Add Data" page
  src/plugins/home/public/application/components/add_data/__snapshots__/add_data.test.tsx.snap
  src/plugins/home/public/application/components/add_data/add_data.test.tsx
  src/plugins/home/public/application/components/add_data/add_data.tsx
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/home/public/plugin.ts
  src/plugins/opensearch_dashboards_overview/public/components/add_data/__snapshots__/add_data.test.tsx.snap
  src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.test.tsx
  src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx
  test/functional/apps/home/_add_data.js
Labels: enhancement, v1.0.0

#466 [Tests] updated artifact script
  packages/osd-opensearch-archiver/src/lib/docs/__tests__/generate_doc_records_stream.ts
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
  src/core/server/ui_settings/create_or_upgrade_saved_config/integration_tests/create_or_upgrade.test.ts
  src/core/server/ui_settings/integration_tests/index.test.ts
Labels: >test:unit, test:functional, test:integration, v1.0.0

#468 [Bug]Change JetBeats --> BeatsWest to avoid trademark violation
  src/plugins/home/public/assets/sample_data_resources/flights/dashboard.png
  src/plugins/home/public/assets/sample_data_resources/flights/dashboard_dark.png
  src/plugins/home/server/services/sample_data/data_sets/flights/flights.json.gz
  src/plugins/home/server/services/sample_data/data_sets/flights/saved_objects.ts
  test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights/data.json.gz
  test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights_index_pattern/data.json.gz
Labels: bug, v1.0.0

#456 Add proper dependency resolution for dns-packet
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#457 Add proper dependency resolution for ssri
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#458 Add proper dependency resolution for url-parse
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#460 Add proper dependency resolution for locutus
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#461 Add proper dependency resolution for immer
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#484 [Build] restore visTypeVega
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
  src/plugins/vis_type_vega/public/components/experimental_map_vis_info.tsx
  src/plugins/vis_type_vega/public/data_model/types.ts
  src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
  src/plugins/vis_type_vega/public/test_utils/vega_graph.json
  src/plugins/vis_type_vega/public/test_utils/vega_map_test.json
  src/plugins/vis_type_vega/public/test_utils/vegalite_graph.json
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
  src/plugins/vis_type_vega/server/types.ts
  src/plugins/vis_type_vega/server/usage_collector/get_usage_collector.test.ts
  src/plugins/vis_type_vega/server/usage_collector/get_usage_collector.ts
  test/functional/apps/visualize/_vega_chart.ts
  test/functional/fixtures/opensearch_archiver/dashboard/current/opensearch_dashboards/data.json.gz
Labels: Build, backwards-compatibility, v1.0.0

#485 [Build] use saved config from valid kbn version
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts
Labels: Build, backwards-compatibility, v1.0.0

#476 Bump axios related dependencies
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#488 [Test] Enable schema_error.test.ts
  packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
  packages/osd-config-schema/src/errors/schema_error.test.ts
Labels: >test:unit, v1.0.0

#493 [Build] deprecate renamed configurations
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/core/server/opensearch_dashboards_config.test.ts
  src/core/server/opensearch_dashboards_config.ts
  src/plugins/home/server/index.ts
  src/plugins/maps_legacy/server/index.ts
  src/plugins/opensearch_dashboards_legacy/server/index.ts
  src/plugins/region_map/server/index.ts
  src/plugins/vis_type_timeline/server/index.ts
  src/plugins/vis_type_vega/server/index.ts
Labels: Build, backwards-compatibility

#497 [Test] Enable unit test suite: loading_news.test.tsx
  src/plugins/newsfeed/public/components/loading_news.test.tsx
Labels: >test:unit, v1.0.0

#496 [Test] Enable unit test suite: empty_news.test.tsx
  src/plugins/newsfeed/public/components/__snapshots__/empty_news.test.tsx.snap
  src/plugins/newsfeed/public/components/empty_news.test.tsx
Labels: >test:unit, v1.0.0

#495 [Test] Enable unit test suite: api.test.ts
  src/plugins/newsfeed/public/lib/api.test.ts
Labels: >test:unit, v1.0.0

#501 Bump node-sass to address LibSass vulnerabilities
  packages/osd-optimizer/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v1.0.0

#531 [Test] Enable unit test suite: get_telemetry_saved_object.test.ts
  src/plugins/telemetry/server/telemetry_repository/get_telemetry_saved_object.test.ts
Labels: >test:unit, v1.0.0

#530 [Test] Enable unit test suite: get_data_telemetry.test.ts
  src/plugins/telemetry/server/telemetry_collection/get_data_telemetry/get_data_telemetry.test.ts
Labels: >test:unit, v1.0.0

#529 [Test] Enable unit test suite: get_nodes_usage.test.ts
  src/plugins/telemetry/server/telemetry_collection/get_nodes_usage.test.ts
Labels: >test:unit, v1.0.0

#525 [Test] Enable unit test suite: get_cluster_stats.test.ts
  src/plugins/telemetry/server/telemetry_collection/get_cluster_stats.test.ts
Labels: >test:unit, v1.0.0

#524 [Test] Enable unit test suite: get_cluster_info.test.ts
  src/plugins/telemetry/server/telemetry_collection/get_cluster_info.test.ts
Labels: >test:unit, v1.0.0

#523 [Test] Enable unit test suite: fetcher.test.ts
  src/plugins/telemetry/server/fetcher.test.ts
Labels: >test:unit, v1.0.0

#522 [Test] Enable unit test suite:telemetry_notifications
  src/plugins/telemetry/public/services/telemetry_notifications/telemetry_notifications.test.ts
Labels: >test:unit, v1.0.0

#506 [Test]Enable unit test suite: render_opted_in_notice_banner.test.ts
  src/plugins/telemetry/public/services/telemetry_notifications/render_opted_in_notice_banner.test.ts
Labels: >test:unit, v1.0.0

#505 [Test] Enable unit test suite: render_opt_in_banner.test.ts
  src/plugins/telemetry/public/services/telemetry_notifications/render_opt_in_banner.test.ts
Labels: >test:unit, v1.0.0

#489 [Test] Enable help.test.ts
  packages/osd-dev-utils/src/run/help.test.ts
Labels: >test:unit, v1.0.0

#539 Bump webpack-dev-server from 3.8.2 to 3.11.0
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v1.0.0

#545 Add RELEASING.md
  RELEASING.md
Labels: docs, v1.0.0

#532 [Test] Enable unit test suites in telemetry/public/components
  src/plugins/telemetry/public/components/__snapshots__/opt_in_banner.test.tsx.snap
  src/plugins/telemetry/public/components/__snapshots__/opt_in_message.test.tsx.snap
  src/plugins/telemetry/public/components/__snapshots__/opted_in_notice_banner.test.tsx.snap
  src/plugins/telemetry/public/components/opt_in_banner.test.tsx
  src/plugins/telemetry/public/components/opt_in_message.test.tsx
  src/plugins/telemetry/public/components/opted_in_notice_banner.test.tsx
Labels: >test:unit, v1.0.0

#541 Bump path-parse from 1.0.6 to 1.0.7
  yarn.lock
Labels: dependencies, v1.0.0

#534 [Test] Enable unit test suites in telemetry_management_section
  src/plugins/telemetry_management_section/public/components/__snapshots__/opt_in_security_example_flyout.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/opt_in_example_flyout.test.tsx
  src/plugins/telemetry_management_section/public/components/opt_in_security_example_flyout.test.tsx
  src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx
Labels: >test:unit, v1.0.0

#528 [Test] Enable unit test suite: get_local_stats.test.ts
  src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts
Labels: >test:unit, v1.0.0

#502 [Test] Enable unit test suite: telemetry_service.test.ts
  src/plugins/telemetry/public/services/telemetry_service.test.ts
Labels: >test:unit, v1.0.0

#500 [Test] Enable unit test suite: telemetry_sender.test.ts
  src/plugins/telemetry/public/services/telemetry_sender.test.ts
Labels: >test:unit, v1.0.0

#547 Require kind-of v6.0.3
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#553 [DOCS] Replace edit_index_pattern link
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
Labels: docs

#552 Upgrade normalize-url related dependencies
  package.json
  packages/opensearch-safer-lodash-set/package.json
  packages/osd-apm-config-loader/package.json
  packages/osd-config-schema/package.json
  packages/osd-config/package.json
  packages/osd-optimizer/src/worker/webpack_helpers.ts
  packages/osd-std/package.json
  packages/osd-storybook/package.json
  packages/osd-ui-shared-deps/package.json
  packages/osd-utility-types/package.json
  yarn.lock
Labels: dependencies, v1.0.0

#560 Require `ejs` v3.1.6
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#558 Upgrade merge from 1.2.1 to 2.1.1
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#548 Upgrade glob-parent related dependencies
  package.json
  packages/osd-analytics/package.json
  packages/osd-babel-preset/package.json
  packages/osd-i18n/package.json
  packages/osd-interpreter/package.json
  packages/osd-opensearch/package.json
  packages/osd-optimizer/package.json
  packages/osd-pm/package.json
  packages/osd-spec-to-console/package.json
  packages/osd-storybook/package.json
  packages/osd-test/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v1.0.0

#540 [Test] Remove unit test case in zip.test.js
  src/cli_plugin/install/zip.test.js
Labels: >test:unit, v1.0.0

#537 Bump yeoman-generator from 1.1.1 to 4.13.0
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v1.0.0

#549 Require lodash v4.17.21
  package.json
  packages/osd-config-schema/package.json
  packages/osd-pm/package.json
  packages/osd-telemetry-tools/package.json
  packages/osd-test/package.json
  yarn.lock
Labels: dependencies, v1.0.0

#566 Upgrade chromedriver, match version in Dockerfile
  Dockerfile
  package.json
  yarn.lock
Labels: Build, test:functional

#544 Bump Node.js from 10.23.1 to 10.24.1
  .github/workflows/pr_check_workflow.yml
  .node-version
  .nvmrc
  Dockerfile
  README.md
  package.json
Labels: Build, dependencies, v1.0.0

#559 Require front-matter v4.0.2, fix resolutions
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#568 Require `trim-newlines` v3.0.1
  package.json
  yarn.lock
Labels: dependencies, v1.0.0

#565 [DOCS] Replace settings and help menu links
  src/core/public/doc_links/doc_links_service.ts
  src/core/server/ui_settings/settings/date_formats.ts
  src/plugins/console/server/lib/spec_definitions/json/generated/msearch.json
  src/plugins/console/server/lib/spec_definitions/json/generated/msearch_template.json
  src/plugins/dashboard/public/application/help_menu/help_menu_util.ts
  src/plugins/data/server/ui_settings.ts
  src/plugins/discover/public/application/angular/context/api/utils/get_opensearch_query_sort.ts
  src/plugins/discover/public/application/components/help_menu/help_menu_util.js
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
  src/plugins/maps_legacy/server/ui_settings.ts
  src/plugins/vis_type_vega/public/components/vega_help_menu.tsx
Labels: docs, v1.0.0
