Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-07, with the labels that each got.

#578 Revert "Default to converting folder name for cli plugin to kebab-case (#347)"
  src/cli_plugin/install/install.js
  src/cli_plugin/install/opensearch_dashboards.js
Labels: rename

#583 Revert "Default to converting folder name for cli plugin to kebab-case (#357)"
  src/cli_plugin/install/install.js
  src/cli_plugin/install/opensearch_dashboards.js
Labels: backport, v1.0.0

#584 Revert "Default to converting folder name for cli plugin to kebab-case (#357)"
  src/cli_plugin/install/install.js
  src/cli_plugin/install/opensearch_dashboards.js
Labels: backport, v1.0.0

#587 Add Release note for 1.0.0
  release-notes/opensearch-dashboards.release-notes-1.0.0.md
Labels: v1.0.0

#588 [1.0] Add Release note for 1.0.0
  release-notes/opensearch-dashboards.release-notes-1.0.0.md
Labels: backport, v1.0.0

#589 [1.x] Add Release note for 1.0.0
  release-notes/opensearch-dashboards.release-notes-1.0.0.md
Labels: backport, v1.0.0

#579 Update readme for dashboards 1.0.0
  README.md
Labels: v1.0.0

#582 [1.x] Update Readme for dashboards 1.0.0
  README.md
Labels: backport, v1.0.0

#581 [1.0] Update Readme for dashboards 1.0.0
  README.md
Labels: backport, v1.0.0

#599 [Bug] replace words in PRINCIPLES.md
  src/core/PRINCIPLES.md
Labels: bug, v1.0.0

#614 [1.x][Bug] replace words in PRINCIPLES.md
  src/core/PRINCIPLES.md
Labels: backport, bug, v1.0.0

#613 [1.0][Bug] replace words in PRINCIPLES.md
  src/core/PRINCIPLES.md
Labels: backport, bug, v1.0.0

#597 [Bug] remove incorrect reference in testing.md
  src/core/TESTING.md
Labels: bug, v1.0.0

#603 [Bug] Remove appKey in github-checks-reporter
  github_checks_reporter.json
Labels: bug, v1.0.0

#604 [Bug] Fix broken link in package.json
  package.json
Labels: bug, v1.0.0

#605 [Bug] Fix broken links in package.json in opensearch-eslint-config-opensearch-dashboards
  packages/opensearch-eslint-config-opensearch-dashboards/README.md
  packages/opensearch-eslint-config-opensearch-dashboards/package.json
Labels: bug, v1.0.0

#606 [Bug] Replace words in /packages/opensearch-datemath/readme.md
  packages/opensearch-datemath/readme.md
Labels: bug, v1.0.0

#609 [Bug] Clean concepts in packages/osd-plugin-generator/README.md
  packages/osd-plugin-generator/README.md
Labels: bug, v1.0.0

#610 [Bug] Clean concepts in packages/osd-plugin-helpers/README.md
  packages/osd-plugin-helpers/README.md
Labels: bug, v1.0.0

#611 [Bug] Clean elastic-eslint-config-kibana in packages/osd-pm/README.md
  packages/osd-pm/README.md
  packages/osd-pm/src/README.md
Labels: bug, v1.0.0

#607 [Bug] Fix broken links in packages/opensearch-safter-lodash-set
  packages/opensearch-safer-lodash-set/LICENSE
  packages/opensearch-safer-lodash-set/package.json
Labels: bug, v1.0.0

#602 [Bug] Remove license concepts in packages/osd-opensearch
  packages/osd-opensearch/README.md
Labels: bug, v1.0.0

#616 [PURIFY] Remove certs and PKCS12 files temporarily
  packages/osd-dev-utils/certs/ca.crt
  packages/osd-dev-utils/certs/opensearch.p12
  packages/osd-dev-utils/certs/opensearch_dashboards.p12
  packages/osd-dev-utils/certs/opensearch_emptypassword.p12
  packages/osd-dev-utils/certs/opensearch_nopassword.p12
  packages/osd-opensearch/src/integration_tests/cluster.test.js
  src/core/server/utils/crypto/__fixtures__/README.md
  src/core/server/utils/crypto/pkcs12.test.ts
Labels: rename, v1.0.0

#622 [PURIFY] Remove certs and PKCS12 files temporarily (#616)
  packages/osd-dev-utils/certs/ca.crt
  packages/osd-dev-utils/certs/opensearch.p12
  packages/osd-dev-utils/certs/opensearch_dashboards.p12
  packages/osd-dev-utils/certs/opensearch_emptypassword.p12
  packages/osd-dev-utils/certs/opensearch_nopassword.p12
  packages/osd-opensearch/src/integration_tests/cluster.test.js
  src/core/server/utils/crypto/__fixtures__/README.md
  src/core/server/utils/crypto/pkcs12.test.ts
Labels: backport, v1.0.0

#624 [1.x][Bug] Fix broken link in package.json
  package.json
Labels: backport, bug, v1.0.0

#623 [1.0][Bug] Fix broken link in package.json
  package.json
Labels: backport, bug, v1.0.0

#621 [1.x][Bug] Remove appKey in github-checks-reporter
  github_checks_reporter.json
Labels: backport, bug, v1.0.0

#639 [1.x][Bug] Remove license concepts in packages/osd-opensearch
  packages/osd-opensearch/README.md
Labels: backport, bug, v1.0.0

#638 [1.0][Bug] Remove license concepts in packages/osd-opensearch
  packages/osd-opensearch/README.md
Labels: backport, bug, v1.0.0

#637 [1.x][Bug] Fix links in packages/opensearch-safter-lodash-set
  packages/opensearch-safer-lodash-set/LICENSE
  packages/opensearch-safer-lodash-set/package.json
Labels: backport, bug, v1.0.0

#636 [1.0][Bug] Fix links in packages/opensearch-safter-lodash-set
  packages/opensearch-safer-lodash-set/LICENSE
  packages/opensearch-safer-lodash-set/package.json
Labels: backport, bug, v1.0.0

#635 [1.0][Bug] Clean concepts in packages/osd-pm/README.md
  packages/osd-pm/README.md
  packages/osd-pm/src/README.md
Labels: backport, bug, v1.0.0

#634 [1.x][Bug] Clean concepts in packages/osd-pm/README.md
  packages/osd-pm/README.md
  packages/osd-pm/src/README.md
Labels: backport, bug, v1.0.0

#633 [1.x][Bug] Clean concepts in packages/osd-plugin-helpers
  packages/osd-plugin-helpers/README.md
Labels: backport, bug, v1.0.0

#632 [1.0][Bug] Clean concepts in packages/osd-plugin-helpers
  packages/osd-plugin-helpers/README.md
Labels: backport, bug, v1.0.0

#631 [1.x][Bug] Clean concepts in packages/osd-plugin-generator
  packages/osd-plugin-generator/README.md
Labels: backport, bug, v1.0.0

#630 [1.0][Bug] Clean concepts in packages/osd-plugin-generator
  packages/osd-plugin-generator/README.md
Labels: backport, bug, v1.0.0

#629 [1.x][Bug] Replace words in /packages/opensearch-datemath
  packages/opensearch-datemath/readme.md
Labels: backport, bug, v1.0.0

#628 [1.0][Bug] Replace words in /packages/opensearch-datemath
  packages/opensearch-datemath/readme.md
Labels: backport, bug, v1.0.0

#627 [1.x][Bug] Fix links in opensearch-eslint-config-opensearch-dashboards
  packages/opensearch-eslint-config-opensearch-dashboards/README.md
  packages/opensearch-eslint-config-opensearch-dashboards/package.json
Labels: backport, bug, v1.0.0

#626 [1.0][Bug] Fix links in opensearch-eslint-config-opensearch-dashboards
  packages/opensearch-eslint-config-opensearch-dashboards/README.md
  packages/opensearch-eslint-config-opensearch-dashboards/package.json
Labels: backport, bug, v1.0.0

#625 [1.x][PURIFY] Remove certs and PKCS12 files temporarily
  packages/osd-dev-utils/certs/ca.crt
  packages/osd-dev-utils/certs/opensearch.p12
  packages/osd-dev-utils/certs/opensearch_dashboards.p12
  packages/osd-dev-utils/certs/opensearch_emptypassword.p12
  packages/osd-dev-utils/certs/opensearch_nopassword.p12
  packages/osd-opensearch/src/integration_tests/cluster.test.js
  src/core/server/utils/crypto/__fixtures__/README.md
  src/core/server/utils/crypto/pkcs12.test.ts
Labels: backport, v1.0.0

#620 [1.0][Bug] Remove appKey in github-checks-reporter
  github_checks_reporter.json
Labels: backport, bug, v1.0.0

#618 [1.x][Bug] remove incorrect reference in testing.md
  src/core/TESTING.md
Labels: backport, bug, v1.0.0

#617 [1.0][Bug] remove incorrect reference in testing.md
  src/core/TESTING.md
Labels: backport, bug, v1.0.0

#608 [Bug] Remove kibana issue from /packages/osd-optimizer/README.md
  packages/osd-optimizer/README.md
Labels: bug

#643 [1.0][Bug] Replace issue in /packages/osd-optimizer/README.md
  packages/osd-optimizer/README.md
Labels: backport, bug, v1.1.0

#642 [1.x][Bug] Replace issue in /packages/osd-optimizer/README.md
  packages/osd-optimizer/README.md
Labels: backport, bug, v1.1.0

#641 [Tests] ARM64 artifacts for testing
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
Labels: >test:unit, test:functional, test:integration

#644 [Purify] update general info in run_fpm
  src/dev/build/tasks/os_packages/run_fpm.ts
Labels: rename

#352 Increase filters popover size and use full width in form components
  src/plugins/data/public/ui/filter_bar/_index.scss
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/_filter_editor.scss
  src/plugins/data/public/ui/filter_bar/filter_editor/_index.scss
  src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/phrase_value_input.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/phrases_values_input.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/range_value_input.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx
  src/plugins/data/public/ui/filter_bar/filter_item.tsx
Labels: enhancement, v1.1.0

#654 [Test] Wrap FunComponent in unit test with IntlProvider
  src/core/public/application/ui/app_container.test.tsx
  src/core/public/core_app/status/components/server_status.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/__snapshots__/warning_call_out.test.tsx.snap
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/warning_call_out.test.tsx
  src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx
  src/plugins/vis_default_editor/public/components/controls/percentiles.test.tsx
  src/test_utils/public/enzyme_helpers.tsx
Labels: >test:unit, v1.1.0

#661 [1.x][Test] Wrap FunComponent in unit test with IntlProvider
  src/core/public/application/ui/app_container.test.tsx
  src/core/public/core_app/status/components/server_status.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/__snapshots__/warning_call_out.test.tsx.snap
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/warning_call_out.test.tsx
  src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx
  src/plugins/vis_default_editor/public/components/controls/percentiles.test.tsx
  src/test_utils/public/enzyme_helpers.tsx
Labels: >test:unit, backport, v1.1.0

#596 Adding updated content to README.md and remove superfluous sections
  README.md
Labels: v1.1.0

#598 Removing incorrect CONTRIBUTING.md language and adding updated links
  CONTRIBUTING.md
Labels: v1.1.0

#600 Updating MAINTAINERS.md with correct links
  MAINTAINERS.md
Labels: v1.1.0

#659 [Bug] fix timeline icon in Visualize list
  src/plugins/vis_type_timeline/public/timeline_vis_type.tsx
Labels: bug

#595 [Test] Fix console error in search_service.test.ts 
  src/plugins/data/server/search/search_service.ts
Labels: >test:unit, v1.1.0

#671 [1.x][Test] Fix console error in search_service.test.ts 
  src/plugins/data/server/search/search_service.ts
Labels: >test:unit, backport, v1.1.0

#664 [1.x] Update MAINTAINERS.md (#600)
  MAINTAINERS.md
Labels: backport

#663 [1.x] Update CONTRIBUTING.md (#598)
  CONTRIBUTING.md
Labels: backport

#662 [1.x] Clean up README.md (#596)
  README.md
Labels: backport

#668 [1.x][Tests] ARM64 artifacts for testing
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
Labels: backport, test:functional, test:integration, v1.1.0

#669 [1.x][Purify] update general info in run_fpm
  src/dev/build/tasks/os_packages/run_fpm.ts
Labels: backport, rename, v1.1.0

#670 [1.x][Bug] fix timeline icon in Visualize list
  src/plugins/vis_type_timeline/public/timeline_vis_type.tsx
Labels: backport, bug, v1.1.0

#672 [1.x] Increase filters popover size and use full width in form components
  src/plugins/data/public/ui/filter_bar/_index.scss
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/_filter_editor.scss
  src/plugins/data/public/ui/filter_bar/filter_editor/_index.scss
  src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/phrase_value_input.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/phrases_values_input.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/range_value_input.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx
  src/plugins/data/public/ui/filter_bar/filter_item.tsx
Labels: backport, enhancement, v1.1.0

#674 [Test] Fix console warning in field_editor.test.tsx
  src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx
Labels: >test:unit, v1.1.0

#677 Add CODE_OF_CONDUCT markdown file to fix broken link in README
  CODE_OF_CONDUCT.md
Labels: docs, v1.1.0

#682 [1.x][Test] Fix console warning in field_editor.test.tsx
  src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx
Labels: >test:unit, backport, v1.1.0
