Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-09, with the labels that each got.

#753 [1.0][Build] use saved legacy config for 1.x
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts
Labels: Build, backport

#738 Make welcome page logo and title configurable
  config/opensearch_dashboards.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/branding/__snapshots__/opensearch_dashboards_custom_logo.test.tsx.snap
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.test.tsx
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_logo.tsx
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/injected_metadata/injected_metadata_service.test.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/public/mocks.ts
  src/core/public/plugins/plugin_context.ts
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/legacy/server/config/schema.js
  src/plugins/home/public/application/components/__snapshots__/home.test.js.snap
  src/plugins/home/public/application/components/__snapshots__/welcome.test.tsx.snap
  src/plugins/home/public/application/components/_welcome.scss
  src/plugins/home/public/application/components/home.js
  src/plugins/home/public/application/components/home.test.js
  src/plugins/home/public/application/components/welcome.test.tsx
  src/plugins/home/public/application/components/welcome.tsx
  src/plugins/home/public/application/opensearch_dashboards_services.ts
  src/plugins/home/public/plugin.ts
  test/common/config.js
  test/functional/apps/visualize/_custom_branding.js
  test/functional/page_objects/common_page.ts
Labels: branding

#704 Upgrade `tar` from 4.4.13/6.0.2 to 6.1.6
  package.json
  yarn.lock
Labels: dependencies, v1.1.0

#756 [1.x] Upgrade `tar` from 4.4.13/6.0.2 to 6.1.6 (#704)
  package.json
  yarn.lock
Labels: v1.1.0, backport

#757 [1.x] docs(docker): add .dockerignore, add build instructions (#299)
  .dockerignore
  DEVELOPER_GUIDE.md
Labels: v1.1.0, backport

#758 [1.x] Bump url-parse from 1.5.1 to 1.5.3 (#727)
  yarn.lock
Labels: v1.1.0, backport

#759 [1.x] Bump jszip from 3.3.0 to 3.7.1 (#728)
  yarn.lock
Labels: v1.1.0, backport

#762 Bump `tar` from 6.1.6 to 6.1.11
  package.json
  yarn.lock
Labels: dependencies, v1.1.0

#764 [1.x] Bump `tar` from 6.1.6 to 6.1.11 (#762)
  package.json
  yarn.lock
Labels: v1.1.0, backport

#712 Correct copyright notices to reflect Copyright OpenSearch Contributors
  README.md
Labels: docs, v1.1.0

#767 Correct copyright notices in README (#712)
  README.md
Labels: v1.1.0, backport

#746 Make loading page logo and title configurable
  config/opensearch_dashboards.yml
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/styles.tsx
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/legacy/server/config/schema.js
Labels: branding

#776 [Backport] [1.x] Update TESTING.md (#770)
  TESTING.md
Labels: v1.1.0, backport

#775 [Backport][1.1] Update TESTING.md (#770)
  TESTING.md
Labels: v1.1.0, backport

#780 Upgrade `immer` from 8.0.1 to 9.0.6
  package.json
  yarn.lock
Labels: dependencies, v1.1.0

#779 Bump `axios` from 0.21.1 to 0.21.4
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-release-notes/package.json
  yarn.lock
Labels: dependencies, v1.1.0

#783 [1.0] Bump `axios` from 0.21.1 to 0.21.4
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-release-notes/package.json
  yarn.lock
Labels: dependencies, v1.1.0, backport

#784 [1.x] Bump `axios` from 0.21.1 to 0.21.4
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-release-notes/package.json
  yarn.lock
Labels: dependencies, v1.1.0, backport

#785 [1.0] Upgrade `immer` from 8.0.1 to 9.0.6
  package.json
  yarn.lock
Labels: dependencies, v1.1.0, backport

#786 [1.x] Upgrade `immer` from 8.0.1 to 9.0.6
  package.json
  yarn.lock
Labels: dependencies, v1.1.0, backport

#788 [1.1] Upgrade `immer` from 8.0.1 to 9.0.6
  package.json
  yarn.lock
Labels: dependencies, v1.1.0, backport

#789 [1.1] Bump `axios` from 0.21.1 to 0.21.4
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-release-notes/package.json
  yarn.lock
Labels: dependencies, v1.1.0, backport

#790 Add release note for 1.1.0
  release-notes/opensearch-dashboards.release-notes-1.1.0.md
Labels: docs, v1.1.0

#791 [1.1] Add release note for 1.1.0
  release-notes/opensearch-dashboards.release-notes-1.1.0.md
Labels: docs, v1.1.0, backport

#793 Branding config structure change and renaming
  config/opensearch_dashboards.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/branding/__snapshots__/opensearch_dashboards_custom_logo.test.tsx.snap
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.test.tsx
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_logo.scss
  src/core/public/index.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/legacy/server/config/schema.js
  src/plugins/home/public/application/components/welcome.test.tsx
  src/plugins/home/public/application/components/welcome.tsx
  src/plugins/home/public/application/opensearch_dashboards_services.ts
  test/common/config.js
Labels: branding

#797 Dark mode configurations for header logo, welcome logo and loading logo
  config/opensearch_dashboards.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/branding/__snapshots__/opensearch_dashboards_custom_logo.test.tsx.snap
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.test.tsx
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/index.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/plugins/home/public/application/components/__snapshots__/welcome.test.tsx.snap
  src/plugins/home/public/application/components/welcome.test.tsx
  src/plugins/home/public/application/components/welcome.tsx
  test/common/config.js
  test/functional/apps/visualize/_custom_branding.js
Labels: branding

#792 Correct the mime-type of exported CSVs
  src/plugins/inspector/public/views/data/lib/export_csv.ts
  src/plugins/vis_type_table/public/agg_table/agg_table.js
  src/plugins/vis_type_table/public/agg_table/agg_table.test.js
Labels: bug, v1.2.0

#802 [Version] Increment to 1.2
  package.json
Labels: Build, Versioning, v1.2.0

#803 [1.x][Version] Increment to 1.2
  package.json
Labels: Build, Versioning, backport, v1.2.0

#801 Add favicon configuration
  config/opensearch_dashboards.yml
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/legacy/server/config/schema.js
Labels: branding

#808 [1.x] De-Couple Dashboards linux building process
  DEVELOPER_GUIDE.md
  package.json
  src/dev/build/args.test.ts
  src/dev/build/args.ts
  src/dev/build/build_distributables.ts
  src/dev/build/cli.ts
  src/dev/build/lib/build.test.ts
  src/dev/build/lib/config.test.ts
  src/dev/build/lib/config.ts
  src/dev/build/lib/platform.ts
  src/dev/build/tasks/clean_tasks.ts
  src/dev/build/tasks/create_archives_task.ts
  src/dev/build/tasks/nodejs/clean_node_builds_task.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
  src/dev/build/tasks/notice_file_task.ts
Labels: Build, backport, v1.2.0

#811 [1.x] Correct the mime-type of exported CSVs (#792)
  src/plugins/inspector/public/views/data/lib/export_csv.ts
  src/plugins/vis_type_table/public/agg_table/agg_table.js
  src/plugins/vis_type_table/public/agg_table/agg_table.test.js
Labels: backport, v1.2.0

#815 Revert "[1.0] Upgrade `immer` from 8.0.1 to 9.0.6 (#785)"
  package.json
  yarn.lock
Labels: dependencies

#813 Revert "[1.1] Upgrade `immer` from 8.0.1 to 9.0.6"
  package.json
  yarn.lock
Labels: dependencies, v1.1.0

#814 Revert "[1.x] Upgrade `immer` from 8.0.1 to 9.0.6"
  package.json
  yarn.lock
Labels: dependencies

#819 [1.1] Bump tmpl from 1.0.4 to 1.0.5 (#807)
  yarn.lock
Labels: v1.1.0, backport

#818 [1.x] Bump tmpl from 1.0.4 to 1.0.5 (#807)
  yarn.lock
Labels: v1.1.0, backport

#816 [1.x] Bump prismjs from 1.24.0 to 1.25.0 (#805)
  yarn.lock
Labels: v1.1.0, backport

#817 [1.1] Bump prismjs from 1.24.0 to 1.25.0 (#805)
  yarn.lock
Labels: v1.1.0, backport

#821 Update release note OSD 1.1
  release-notes/opensearch-dashboards.release-notes-1.1.0.md
Labels: docs, v1.1.0

#822 [1.1] Update release note OSD 1.1
  release-notes/opensearch-dashboards.release-notes-1.1.0.md
Labels: docs, v1.1.0, backport

#825 [Bug] Restore timeline legacy functions and filters
  src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/opensearch.test.js
  test/functional/apps/timeline/_expression_typeahead.js
Labels: bug, backwards-compatibility

#827 [1.x][Bug] Restore timeline legacy functions and filters
  src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/opensearch.test.js
  test/functional/apps/timeline/_expression_typeahead.js
Labels: bug, backport

#828 [1.1][Bug] Restore timeline legacy functions and filters
  release-notes/opensearch-dashboards.release-notes-1.1.0.md
  src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/opensearch.test.js
  test/functional/apps/timeline/_expression_typeahead.js
Labels: bug, v1.1.0, backport
