Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-11, with the labels that each got.

#893 Update dashboard maps end point
  src/legacy/server/config/schema.js
  src/plugins/maps_legacy/config.ts
Labels: Maps

#899 1.x Update the dashboard maps end point (#893)
  src/legacy/server/config/schema.js
  src/plugins/maps_legacy/config.ts
Labels: Maps, backlog

#912 fix Node selection when using built in node
  src/dev/build/tasks/bin/scripts/opensearch-dashboards
Labels: bug, Build, v1.2.0

#916 [1.x] Fix Node selection when using built in node (#912)
  src/dev/build/tasks/bin/scripts/opensearch-dashboards
Labels: bug, backport

#917 [1.2] Fix Node selection when using built in node (#912)
  src/dev/build/tasks/bin/scripts/opensearch-dashboards
Labels: bug, backport

#922 [Release] add axios dependency to UI package
  packages/osd-ui-shared-deps/package.json
Labels: branding, v1.2.0

#924 [1.x][Release] add axios dependency to UI package
  packages/osd-ui-shared-deps/package.json
Labels: branding, backport

#925 [1.2][Release] add axios dependency to UI package
  packages/osd-ui-shared-deps/package.json
Labels: branding, backport, v1.2.0

#936 [LIC] Allows the simplified header for new files
  .eslintrc.js
  packages/osd-eslint-plugin-eslint/rules/__tests__/require_license_header.js
  packages/osd-eslint-plugin-eslint/rules/require_license_header.js
Labels: v1.3.0

#937 [Git] update PR template
  .github/pull_request_template.md
Labels: CI

#944 Add release notes for Dashboards 1.2.0
  release-notes/opensearch-dashboards.release-notes-1.2.0.md
Labels: v1.2.0

#964 Add release notes for Dashboards 1.2.0 (#944)
  release-notes/opensearch-dashboards.release-notes-1.2.0.md
Labels: backport, v1.2.0

#965 Add release notes for Dashboards 1.2.0 (#944)
  release-notes/opensearch-dashboards.release-notes-1.2.0.md
Labels: backport, v1.2.0

#905 Add versioned doc support
  DEVELOPER_GUIDE.md
  src/core/public/chrome/chrome_service.tsx
  src/core/public/doc_links/doc_links_service.test.ts
  src/core/public/doc_links/doc_links_service.ts
  src/core/public/public.api.md
  src/core/server/ui_settings/settings/date_formats.ts
  src/plugins/advanced_settings/public/management_app/components/field/field.tsx
  src/plugins/console/server/lib/spec_definitions/json/generated/msearch.json
  src/plugins/console/server/lib/spec_definitions/json/generated/msearch_template.json
  src/plugins/dashboard/public/application/help_menu/help_menu_util.ts
  src/plugins/data/common/opensearch_query/kuery/node_types/wildcard.ts
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/server/autocomplete/value_suggestions_route.ts
  src/plugins/data/server/ui_settings.ts
  src/plugins/discover/public/application/angular/context/api/utils/get_opensearch_query_sort.ts
  src/plugins/discover/public/application/angular/directives/no_results.js
  src/plugins/discover/public/application/angular/directives/no_results.test.js
  src/plugins/discover/public/application/components/doc/use_opensearch_doc_search.ts
  src/plugins/discover/public/application/components/help_menu/help_menu_util.js
  src/plugins/home/public/application/components/tutorial/replace_template_strings.js
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/tabs/tabs.tsx
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/warning_call_out.tsx
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/scripting_syntax.tsx
  src/plugins/index_pattern_management/public/components/field_editor/field_editor.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/empty_state.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
  src/plugins/index_pattern_management/public/mocks.ts
  src/plugins/input_control_vis/public/control/list_control_factory.ts
  src/plugins/maps_legacy/public/map/map_messages.js
  src/plugins/maps_legacy/server/ui_settings.ts
  src/plugins/timeline/public/components/timeline_deprecation.tsx
  src/plugins/vis_default_editor/public/components/agg_select.tsx
  src/plugins/vis_default_editor/public/components/controls/date_ranges.tsx
  src/plugins/vis_type_vega/public/components/vega_help_menu.tsx
  src/plugins/visualize/public/application/utils/utils.ts
Labels: docs, enhancement, rename-docs, v1.3.0

#941 [Branding] prevent logging when config not set
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
Labels: branding, v1.3.0

#973 [Version] Increment to 2.0
  package.json
Labels: Versioning, v2.0.0

#946 Initial Drag and Drop plugin code
  src/plugins/wizard/.i18nrc.json
  src/plugins/wizard/README.md
  src/plugins/wizard/common/index.ts
  src/plugins/wizard/common/wizard_saved_object_attributes.ts
  src/plugins/wizard/opensearch_dashboards.json
  src/plugins/wizard/public/application/_variables.scss
  src/plugins/wizard/public/application/app.scss
  src/plugins/wizard/public/application/app.tsx
  src/plugins/wizard/public/application/components/_util.scss
  src/plugins/wizard/public/application/components/data_tab/config_panel.scss
  src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/config_section.scss
  src/plugins/wizard/public/application/components/data_tab/config_section.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
  src/plugins/wizard/public/application/components/data_tab/index.scss
  src/plugins/wizard/public/application/components/data_tab/index.tsx
  src/plugins/wizard/public/application/components/side_nav.scss
  src/plugins/wizard/public/application/components/side_nav.tsx
  src/plugins/wizard/public/application/components/style_tab.tsx
  src/plugins/wizard/public/application/components/top_nav.scss
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/application/index.tsx
  src/plugins/wizard/public/application/utils/async_search/index.ts
  src/plugins/wizard/public/application/utils/drag_drop/drag_drop_context.tsx
  src/plugins/wizard/public/application/utils/drag_drop/index.ts
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/index.ts
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/types.ts
  src/plugins/wizard/public/visualizations/xy_chart.tsx
  src/plugins/wizard/server/index.ts
  src/plugins/wizard/server/plugin.ts
  src/plugins/wizard/server/routes/index.ts
  src/plugins/wizard/server/saved_objects/index.ts
  src/plugins/wizard/server/saved_objects/wizard_app.ts
  src/plugins/wizard/server/types.ts
Labels: d-and-d

#977 [1.x][Version] Bump to 1.3.0
  package.json
Labels: Versioning, v1.3.0
