Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-08, with the labels that each got.

#685 Add Getting Started section to the Developer Guide
  DEVELOPER_GUIDE.md
  README.md
Labels: docs, v1.1.0

#692 [1.x] Add Getting Started section to the Developer Guide (#685)
  DEVELOPER_GUIDE.md
  README.md
Labels: backport, v1.1.0

#696 [1.x] [BUG] fix CODE_OF_CONDUCT link in README.md (#677)
  CODE_OF_CONDUCT.md
Labels: backport, v1.1.0

#691 Update FieldEditor test snapshots
  src/plugins/index_pattern_management/public/components/field_editor/__snapshots__/field_editor.test.tsx.snap
Labels: >test:unit, v1.1.0

#698 Bump `postcss` from 7.0.32 to 7.0.36
  yarn.lock
Labels: dependencies, v1.1.0

#699 Bump `ws` from 7.3.1 to 7.5.3
  yarn.lock
Labels: dependencies, v1.1.0

#675 [Bug] remove tutorials from router temporarily
  src/plugins/home/server/services/tutorials/tutorials_registry.ts
Labels: bug, v1.1.0

#700 [1.x][Bug] remove tutorials from router temporarily
  src/plugins/home/server/services/tutorials/tutorials_registry.ts
Labels: bug, backport

#703 [1.x] Update FieldEditor test snapshots (#691)
  src/plugins/index_pattern_management/public/components/field_editor/__snapshots__/field_editor.test.tsx.snap
Labels: v1.1.0, backport

#702 [1.x] Bump `postcss` from 7.0.32 to 7.0.36 (#698)
  yarn.lock
Labels: v1.1.0, backport

#713 [Docs] Added TESTING.md
  TESTING.md
Labels: bug, docs, v1.1.0

#717 [1.x][Docs] Added TESTING.md (#713)
  TESTING.md
Labels: docs, backport

#715 [Docs] Added SECURITY.md
  SECURITY.md
Labels: bug, docs, v1.1.0

#722 [Build] Version bump for 1.1 release
  package.json
  packages/osd-opensearch/src/artifact.js
Labels: CI, Build, v1.1.0

#701 [1.x] Bump `ws` from 7.3.1 to 7.5.3 (#699)
  yarn.lock
Labels: v1.1.0, backport

#726 [1.x][Docs] Added SECURITY.md
  SECURITY.md
Labels: docs, backport

#729 [1.x][Docs] Improve the getting started section of the developer guide
  DEVELOPER_GUIDE.md
Labels: docs, backport

#730 [1.x][Build] Version bump for 1.1 release
  package.json
  packages/osd-opensearch/src/artifact.js
Labels: CI, Build, backport

#299 docker: add .dockerignore, add build instructions
  .dockerignore
  DEVELOPER_GUIDE.md
Labels: docs, v1.1.0

#724 [Build] Dashboards working with legacy engines 7.10.2
  src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.test.ts
  src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.ts
Labels: Build

#742 [1.x][Docs] Update doc refs from beta to prod
  src/core/public/doc_links/doc_links_service.test.ts
  src/core/public/doc_links/doc_links_service.ts
  src/core/server/ui_settings/settings/date_formats.ts
  src/plugins/console/server/lib/spec_definitions/json/generated/msearch.json
  src/plugins/console/server/lib/spec_definitions/json/generated/msearch_template.json
  src/plugins/data/server/ui_settings.ts
  src/plugins/discover/public/application/angular/context/api/utils/get_opensearch_query_sort.ts
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
  src/plugins/maps_legacy/public/map/map_messages.js
  src/plugins/maps_legacy/server/ui_settings.ts
  src/plugins/vis_type_vega/public/components/vega_help_menu.tsx
Labels: docs, v1.1.0, backport

#734 [Build] build:types and uiFramework run successfully
  packages/osd-ui-framework/doc_site/src/components/guide_nav/_guide_nav.scss
  packages/osd-ui-framework/doc_site/src/components/guide_nav/guide_nav.js
  packages/osd-ui-framework/doc_site/webpack.config.js
  src/plugins/data/common/field_formats/field_formats_registry.ts
Labels: Build, v1.1.0

#735 [Purify] Remove deprecation message in batchSearches settings
  src/plugins/data/server/ui_settings.ts
Labels: rename, v1.1.0

#748 [1.x][Build] build:types and uiFramework run successfully
  packages/osd-ui-framework/doc_site/src/components/guide_nav/_guide_nav.scss
  packages/osd-ui-framework/doc_site/src/components/guide_nav/guide_nav.js
  packages/osd-ui-framework/doc_site/webpack.config.js
  src/plugins/data/common/field_formats/field_formats_registry.ts
Labels: Build, v1.1.0, backport

#749 [1.x][Purify] Remove deprecation message in batchSearches settings
  src/plugins/data/server/ui_settings.ts
Labels: rename, v1.1.0, backport

#743 [Build] use saved legacy config for 1.x
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts
Labels: Build, v1.1.0

#751 [1.x][Build] use saved legacy config for 1.x
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts
Labels: Build, v1.1.0, backport
