Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2021-12, with the labels that each got.

#1012 [Node 14 upgrade] Fix unit test failures
  src/dev/jest/config.js
Labels: >test:unit, build, >upgrade

#986 [CI] Add tests to github workflow
  .github/workflows/pr_check_workflow.yml
  packages/osd-pm/src/run.test.ts
  src/dev/jest/config.js
  src/plugins/embeddable/public/lib/embeddables/error_embeddable.test.tsx
  src/plugins/vis_type_markdown/public/markdown_vis_controller.test.tsx
  src/plugins/vis_type_tagcloud/public/components/tag_cloud_visualization.test.js
  src/plugins/visualize/public/application/utils/use/use_visualize_app_state.test.ts
Labels: ci

#1016 Moves Drag and Drop to create visualization menu
  src/plugins/visualizations/public/wizard/__snapshots__/new_vis_modal.test.tsx.snap
  src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx
  src/plugins/wizard/opensearch_dashboards.json
  src/plugins/wizard/public/index.ts
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/types.ts
Labels: drag & drop

#871 [Backwards Compatibility][OSD bundle]check advanced_settings, default page and filter&query
  cypress/integration/osd-bundle/check_advanced_settings.js
  cypress/integration/osd-bundle/check_default_page.js
  cypress/integration/osd-bundle/check_filter_and_query.js
  scripts/bwctest-osd.sh
Labels: v1.3.0, test:bwc

#900 [Backwards Compatibility][OSD] check advanced_settings, default page, loaded sample date, timeline and filter&query
  cypress/integration/osd/check_advanced_settings.js
  cypress/integration/osd/check_default_page.js
  cypress/integration/osd/check_filter_and_query.js
  cypress/integration/osd/check_loaded_data.js
  cypress/integration/osd/check_timeline.js
Labels: v1.3.0, test:bwc

#901 [Backwards Compatibility][OSD bundle] add timeline and sample data check
  cypress/integration/osd-bundle/check_loaded_data.js
  cypress/integration/osd-bundle/check_timeline.js
Labels: v1.3.0, test:bwc

#1021 [Backwards Compatibility] restore URL forwarding from legacy app
  src/plugins/data/common/field_formats/converters/url.test.ts
  src/plugins/opensearch_dashboards_utils/public/state_management/url/format.test.ts
  src/plugins/opensearch_dashboards_utils/public/state_management/url/hash_unhash_url.test.ts
  src/plugins/opensearch_dashboards_utils/public/state_management/url/osd_url_storage.test.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
  src/plugins/share/public/lib/url_shortener.test.ts
  src/plugins/url_forwarding/public/forward_app/forward_app.ts
  src/plugins/url_forwarding/public/plugin.ts
Labels: bug, backwards-compatibility
