Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-02, with the labels that each got.

#1170 [1.x][BUG] fix disableWelcomeScreen config (#1143)
  src/plugins/home/server/index.ts
Labels: bug, backport, v1.3.0

#1207 [Tests] configurable skip checksum verification
  .github/workflows/pr_check_workflow.yml
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
Labels: test:functional, test:integration

#1185 Don't terminate the server on NodeDeprecationWarning
  src/setup_node_env/exit_on_warning.js
Labels: v1.3.0, backport pending

#1105 Removes KUI Generator and related dependencies
  .eslintignore
  .eslintrc.js
  package.json
  packages/osd-ui-framework/README.md
  packages/osd-ui-framework/generator-kui/app/component.js
  packages/osd-ui-framework/generator-kui/app/documentation.js
  packages/osd-ui-framework/generator-kui/component/index.js
  packages/osd-ui-framework/generator-kui/component/templates/_component.scss
  packages/osd-ui-framework/generator-kui/component/templates/_index.scss
  packages/osd-ui-framework/generator-kui/component/templates/component.js
  packages/osd-ui-framework/generator-kui/component/templates/index.js
  packages/osd-ui-framework/generator-kui/component/templates/stateless_function.js
  packages/osd-ui-framework/generator-kui/component/templates/test.js
  packages/osd-ui-framework/generator-kui/documentation/index.js
  packages/osd-ui-framework/generator-kui/documentation/templates/documentation_page.js
  packages/osd-ui-framework/generator-kui/documentation/templates/documentation_page_demo.js
  packages/osd-ui-framework/generator-kui/documentation/templates/documentation_sandbox.html
  packages/osd-ui-framework/generator-kui/documentation/templates/documentation_sandbox.js
  packages/osd-ui-framework/generator-kui/utils.js
  packages/osd-ui-framework/package.json
  src/dev/i18n/tasks/extract_untracked_translations.ts
  src/dev/jest/config.js
  src/dev/precommit_hook/casing_check_config.js
  yarn.lock
Labels: dependencies, v2.0.0, ux / ui, security fix, ui library

#1213 Fix createStateContainerReactHelpers documentation (closes #1197)
  src/plugins/opensearch_dashboards_utils/docs/state_containers/react/connect.md
Labels: docs

#1169 Bumps `node-fetch` from v2.6.1 to v2.6.7
  package.json
  packages/osd-opensearch/package.json
  yarn.lock
Labels: dependencies, v1.3.0, security fix

#1113 Removes deprecated `request` and `@percy/agent`
  package.json
  packages/osd-test/src/functional_tests/lib/auth.js
  packages/osd-test/src/functional_tests/lib/run_opensearch.js
  packages/osd-test/src/index.ts
  src/core/server/http/cookie_session_storage.test.ts
  src/core/server/http/integration_tests/lifecycle.test.ts
  src/core/test_helpers/osd_server.ts
  test/visual_regression/services/visual_testing/take_percy_snapshot.js
  test/visual_regression/services/visual_testing/visual_testing.ts
  yarn.lock
Labels: dependencies, v2.0.0, security fix

#1192 [Bug] fix incorrect import for opensearch aggs
  src/plugins/data/common/search/expressions/opensearchaggs.ts
  src/plugins/data/config.ts
  test/interpreter_functional/test_suites/run_pipeline/opensearchaggs.ts
Labels: bug

#1221 [Backport 1.x] Bumps `node-fetch` from v2.6.1 to v2.6.7 (#1169)
  package.json
  packages/osd-opensearch/package.json
  yarn.lock
Labels: backport, v1.3.0

#1172 Removes storybook package and related code
  .eslintrc.js
  package.json
  packages/osd-storybook/README.md
  packages/osd-storybook/index.ts
  packages/osd-storybook/lib/constants.ts
  packages/osd-storybook/lib/default_config.ts
  packages/osd-storybook/lib/register.ts
  packages/osd-storybook/lib/run_storybook_cli.ts
  packages/osd-storybook/lib/templates/index.ejs
  packages/osd-storybook/package.json
  packages/osd-storybook/preset.js
  packages/osd-storybook/tsconfig.json
  packages/osd-storybook/typings.d.ts
  packages/osd-storybook/webpack.config.ts
  packages/osd-storybook/yarn.lock
  scripts/storybook.js
  src/dev/precommit_hook/casing_check_config.js
  src/dev/storybook/aliases.ts
  src/dev/storybook/commands/clean.ts
  src/dev/storybook/run_storybook_cli.ts
  src/plugins/embeddable/.storybook/main.js
  src/plugins/embeddable/public/components/panel_options_menu/__examples__/panel_options_menu.stories.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/.storybook/main.js
  src/plugins/opensearch_dashboards_react/public/code_editor/README.md
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.stories.tsx
  tsconfig.base.json
  yarn.lock
Labels: v1.3.0

#1227 [1.x][Bug] fix incorrect import for opensearch aggs (#1192)
  src/plugins/data/common/search/expressions/opensearchaggs.ts
  src/plugins/data/config.ts
  test/interpreter_functional/test_suites/run_pipeline/opensearchaggs.ts
Labels: bug, backport, v1.3.0

#1222 Run build and test workflow on all branches
  .github/workflows/pr_check_workflow.yml
Labels: ci

#1229 Upgrades `webpack-dev-server` and `webpack-cli`
  packages/osd-interpreter/package.json
  packages/osd-monaco/package.json
  packages/osd-monaco/scripts/build.js
  packages/osd-pm/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v2.0.0

#1233 [CI] Add backport action for automated backports
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  CONTRIBUTING.md
Labels: ci

#1194 [nodejs client] fix hookup issues in src/core/server/opensearch
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/client/configure_client.ts
  src/core/server/opensearch/client/mocks.test.ts
  src/core/server/opensearch/client/mocks.ts
  src/core/server/opensearch/client/retry_call_cluster.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: v2.0.0, nodejs :lollipop:

#1261 [Tests] unit test for config was failing
  src/core/server/opensearch/opensearch_config.test.ts
  yarn.lock
Labels: >test:unit

#1239 Upgrades `node-forge` from v0.10.0 to v1.2.1
  package.json
  yarn.lock
Labels: dependencies, v2.0.0

#1271 [Backport 1.x] Run build and test workflow on all branches (#1222)
  .github/workflows/pr_check_workflow.yml
Labels: backport

#1196 Add option to configure available bucket agg types + jest tests
  src/plugins/data/common/search/aggs/agg_types_registry.test.ts
  src/plugins/data/common/search/aggs/agg_types_registry.ts
  src/plugins/data/common/search/aggs/aggs_service.test.ts
  src/plugins/data/common/search/aggs/aggs_service.ts
  src/plugins/data/common/search/aggs/test_helpers/mock_agg_types_registry.ts
  src/plugins/data/public/search/aggs/aggs_service.ts
  src/plugins/data/server/search/aggs/aggs_service.ts
  src/plugins/visualizations/common/constants.ts
  src/plugins/visualizations/server/index.ts
  src/plugins/visualizations/server/plugin.ts
Labels: backport 1.x

#1288 Fix cache.ts for Resource temporarily unavailable
  packages/osd-optimizer/src/node/cache.ts
Labels: bug, test:functional, v1.3.0, backport 1.x

#1265 docs(Dev Guide): Updates how to run OpenSearch
  DEVELOPER_GUIDE.md
Labels: docs
