Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-07, with the labels that each got.

#1837 [Bug] Fix new issue link
  src/plugins/vis_type_timeseries/server/routes/vis.ts
Labels: bug, backport 2.x

#1844 chore: updates D&D icon
  src/plugins/wizard/public/assets/wizard_icon.svg
  src/plugins/wizard/public/plugin.ts
Labels: drag & drop

#1843 Chore/remove contributions
  src/plugins/wizard/public/application/components/data_source_select.tsx
  src/plugins/wizard/public/application/components/data_tab/config_panel.scss
  src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/dropbox.scss
  src/plugins/wizard/public/application/components/data_tab/dropbox.tsx
  src/plugins/wizard/public/application/components/data_tab/field_search.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
  src/plugins/wizard/public/application/components/data_tab/index.scss
  src/plugins/wizard/public/application/components/data_tab/index.tsx
  src/plugins/wizard/public/application/components/data_tab/schema_to_dropbox.tsx
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/title.tsx
  src/plugins/wizard/public/application/components/data_tab/use/index.ts
  src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/wizard/public/application/components/searchable_dropdown.scss
  src/plugins/wizard/public/application/components/searchable_dropdown.tsx
  src/plugins/wizard/public/application/components/side_nav.tsx
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/application/contributions/constants.ts
  src/plugins/wizard/public/application/contributions/containers/common/items/index.tsx
  src/plugins/wizard/public/application/contributions/containers/common/items/select.tsx
  src/plugins/wizard/public/application/contributions/containers/common/items/text_input.tsx
  src/plugins/wizard/public/application/contributions/containers/common/items/types.ts
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/form_field.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/index.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/types.ts
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/use/index.ts
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/use/use_form_field.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/utils/item_to_panel.tsx
  src/plugins/wizard/public/application/contributions/containers/index.ts
  src/plugins/wizard/public/application/contributions/containers/style_tab/index.tsx
  src/plugins/wizard/public/application/utils/async_search/index.ts
  src/plugins/wizard/public/application/utils/state_management/visualization_slice.ts
  src/plugins/wizard/public/application/utils/validate_schema_state.ts
  src/plugins/wizard/public/services/type_service/type_service.test.ts
  src/plugins/wizard/public/services/type_service/types.ts
  src/plugins/wizard/public/services/type_service/visualization_type.test.tsx
  src/plugins/wizard/public/services/type_service/visualization_type.tsx
  src/plugins/wizard/public/visualizations/bar_chart/index.ts
  src/plugins/wizard/public/visualizations/index.ts
  src/plugins/wizard/public/visualizations/metric/to_expression.ts
  src/plugins/wizard/public/visualizations/pie_chart/index.ts
Labels: drag & drop

#1809 Adds v2.1.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.1.0.md
Labels: docs, v2.1.0, backport 2.x, backport 2.1

#1848 Remove banner when editing maps visualization
  src/plugins/vis_type_vega/public/components/experimental_map_vis_info.tsx
  src/plugins/vis_type_vega/public/vega_type.ts
Labels: backport 2.x, v2.2.0

#1855 fix(D&D): fixes reloading app
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/visualizations/index.ts
Labels: drag & drop

#1811 [CI] Bump chromedriver to 102
  .github/workflows/pr_check_workflow.yml
Labels: ci, backport 1.3, v1.3.4

#1863 [D&D] Dropbox style and animations
  src/plugins/wizard/public/application/components/data_tab/dropbox.scss
  src/plugins/wizard/public/application/components/data_tab/dropbox.tsx
  src/plugins/wizard/public/application/components/data_tab/use/use_prefers_reduced_motion.ts
  src/plugins/wizard/public/application/components/workspace.tsx
Labels: drag & drop

#1200 Add DocView links pluggable injection capability
  .i18nrc.json
  src/plugins/discover/public/application/angular/doc_table/components/row_headers.test.js
  src/plugins/discover/public/application/angular/doc_table/components/table_row/details.html
  src/plugins/discover/public/application/angular/doc_viewer_links.tsx
  src/plugins/discover/public/application/components/doc/doc.test.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.test.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
  src/plugins/discover/public/application/doc_views_links/doc_views_links_registry.ts
  src/plugins/discover/public/application/doc_views_links/doc_views_links_types.ts
  src/plugins/discover/public/get_inner_angular.ts
  src/plugins/discover/public/mocks.ts
  src/plugins/discover/public/opensearch_dashboards_services.ts
  src/plugins/discover/public/plugin.ts
  test/plugin_functional/config.ts
  test/plugin_functional/plugins/doc_views_links_plugin/opensearch_dashboards.json
  test/plugin_functional/plugins/doc_views_links_plugin/package.json
  test/plugin_functional/plugins/doc_views_links_plugin/public/index.ts
  test/plugin_functional/plugins/doc_views_links_plugin/public/plugin.tsx
  test/plugin_functional/plugins/doc_views_links_plugin/tsconfig.json
  test/plugin_functional/test_suites/doc_views_links/doc_views_links.ts
  test/plugin_functional/test_suites/doc_views_links/index.ts
Labels: backport 2.x, needs-documentation, v2.2.0

#1894 [D&D] Adds a few readme's
  src/plugins/navigation/README.md
  src/plugins/wizard/README.md
Labels: drag & drop

#1896 Fixes issue on saving custom vector map options as part of visualization
  src/plugins/maps_legacy/public/common/types/region_map_types.ts
  src/plugins/region_map/public/region_map_type.js
  src/plugins/region_map/public/region_map_visualization.js
Labels: backport 2.x, v2.2.0

#1900 [D&D] Empty-workspace polish
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/assets/fields_bg.svg
  src/plugins/wizard/public/assets/hand_field.svg
Labels: drag & drop

#1916 fix(Workspace): Fixes illustration and copy
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/assets/fields_bg.svg
  src/plugins/wizard/public/assets/index_pattern.svg
Labels: drag & drop

#1924 [D&D] Misc fixes
  src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/utils/use/index.ts
  src/plugins/wizard/public/application/utils/use/use_index_pattern.tsx
  src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
  src/plugins/wizard/public/plugin.test.ts
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/services/type_service/utils/index.ts
  src/plugins/wizard/public/services/type_service/utils/merge_array.test.ts
  src/plugins/wizard/public/services/type_service/utils/merge_arrays.ts
  src/plugins/wizard/public/visualizations/metric/to_expression.test.ts
  src/plugins/wizard/public/visualizations/metric/to_expression.ts
  src/plugins/wizard/server/routes/index.ts
Labels: drag & drop

#1927 [D&D] Fix scss lint and available fields
  src/plugins/wizard/public/application/_util.scss
  src/plugins/wizard/public/application/_variables.scss
  src/plugins/wizard/public/application/app.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/components/data_tab/utils/get_available_fields.ts
  src/plugins/wizard/public/application/components/data_tab/utils/index.ts
  src/plugins/wizard/public/application/components/side_nav.scss
  src/plugins/wizard/public/application/components/top_nav.scss
Labels: drag & drop

#1934 [D&D] Feature/experimental
  src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx
  src/plugins/wizard/public/application/components/experimental_info.tsx
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/embeddable/disabled_embeddable.tsx
  src/plugins/wizard/public/embeddable/disabled_visualization.scss
  src/plugins/wizard/public/embeddable/disabled_visualization.tsx
  src/plugins/wizard/public/embeddable/wizard_embeddable_factory.tsx
  src/plugins/wizard/public/plugin.ts
Labels: drag & drop

#1860 [Version] Increment to 2.2
  package.json
Labels: versioning, v2.2.0

#1953 [D&D] Adds autosave while editing aggregation
  src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/application/utils/state_management/metadata_slice.ts
  src/plugins/wizard/public/application/utils/state_management/preload.ts
  src/plugins/wizard/public/application/utils/state_management/store.ts
  src/plugins/wizard/public/application/utils/state_management/visualization_slice.ts
Labels: drag & drop

#1875 [Docs] Add developer documentation for using/modifying the chrome service
  src/core/public/chrome/README.md
Labels: docs

#1948 [CI] Clean up for BWC tests & run only on PRs for backports
  .github/workflows/build_and_test_workflow.yml
  cypress/integration/with-security/check_filter_and_query.js
  cypress/integration/without-security/check_filter_and_query.js
Labels: test:bwc, backport 2.x, v2.2.0

#1955 [Backport 2.x] [CI] Clean up for BWC tests & run only on PRs for backports
  .github/workflows/pr_check_workflow.yml
  cypress/integration/with-security/check_filter_and_query.js
  cypress/integration/without-security/check_filter_and_query.js
Labels: v2.2.0

#1946 [BUG] Fixing some of the broken links in core plugin API documentations
  src/core/README.md
Labels: docs, backport 2.x, backport 2.0, v2.2.0, backport 2.1

#1931 Bump moment from 2.29.2 to 2.29.4
  yarn.lock
Labels: dependencies, cve, backport 2.x, v2.2.0

#1965 [D&D] Fixes autosave with debounce
  src/plugins/wizard/public/application/_variables.scss
  src/plugins/wizard/public/application/app.scss
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/application/utils/state_management/metadata_slice.ts
Labels: drag & drop

#1996 [MD] Instantiate credential management plugin code structure
  src/plugins/credential_management/.eslintrc.js
  src/plugins/credential_management/.i18nrc.json
  src/plugins/credential_management/README.md
  src/plugins/credential_management/common/index.ts
  src/plugins/credential_management/opensearch_dashboards.json
  src/plugins/credential_management/public/application.tsx
  src/plugins/credential_management/public/components/app.tsx
  src/plugins/credential_management/public/index.scss
  src/plugins/credential_management/public/index.ts
  src/plugins/credential_management/public/plugin.ts
  src/plugins/credential_management/public/types.ts
  src/plugins/credential_management/server/index.ts
  src/plugins/credential_management/server/plugin.ts
  src/plugins/credential_management/server/routes/index.ts
  src/plugins/credential_management/server/types.ts
Labels: multiple datasource

#1964 [Docs] Updates Code of Conduct
  CODE_OF_CONDUCT.md
Labels: v2.2.0

#1932 [CVE] Handle invalid query, index and date in vega charts filter handlers
  packages/osd-std/src/__snapshots__/validate_object.test.ts.snap
  packages/osd-std/src/index.ts
  packages/osd-std/src/validate_object.test.ts
  packages/osd-std/src/validate_object.ts
  src/plugins/vis_type_vega/public/data_model/utils.test.js
  src/plugins/vis_type_vega/public/data_model/utils.ts
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
Labels: medium severity, cve, backport 1.x, backport 2.x, v2.2.0

#1954 [UX] Restyle global breadcrumbs
  src/core/public/_variables.scss
  src/core/public/chrome/public/assets/round_filter.svg
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header_breadcrumbs.scss
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: backport 2.x, v2.2.0

#1901 Version increment to 1.3.5
  package.json
Labels: versioning, v1.3.5
