Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-05, with the labels that each got.

#1534 Adds 1.3.2 release notes
  release-notes/opensearch-dashboards.release-notes-1.3.2.md
Labels: docs, backport 1.x, backport 1.3, v1.3.2

#1537 Removes GitHub DCO Action
  .github/workflows/dco.yml
  README.md
Labels: ci, backport 1.x, backport 1.3, backport 2.x, backport 2.0

#1541 [Backport 2.x] Removes GitHub DCO Action
  .github/workflows/dco.yml
Labels: ci, backport

#1539 [Backport 1.x] Removes GitHub DCO Action
  .github/workflows/dco.yml
Labels: ci, backport

#1543 [Docs] update doc reference to point to 2.0 docs
  package.json
Labels: docs, v2.0.0

#1540 [Backport 1.3] Removes GitHub DCO Action
  .github/workflows/dco.yml
Labels: ci, backport

#1551 Bump version to 1.3.3
  package.json
Labels: versioning, v1.3.3

#1552 [CVE] Bumps Chromedriver to v100 and axios to v0.27.2
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: v2.0.0, security vulnerability, high severity, cve, backport 2.x, backport 2.0

#1545 [Bug] fix missing discover context icon
  src/plugins/discover/public/get_inner_angular.ts
Labels: bug, v2.0.0, backport 1.x, backport 1.3, backport 2.x, backport 2.0, v1.3.3

#1567 Adds v2.0.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.0.0.md
Labels: docs, v2.0.0, backport 2.x, backport 2.0

#1575 Updates 2.0 release notes with latest commits
  release-notes/opensearch-dashboards.release-notes-2.0.0.md
Labels: docs, v2.0.0, backport 2.x, backport 2.0

#1580 [CVE] Resolves grunt to 1.5.3
  release-notes/opensearch-dashboards.release-notes-2.0.0.md
  yarn.lock
Labels: v2.0.0, cve, backport 2.x, backport 2.0

#1559 Enforces equal or increasing code coverage in PRs
  .github/.codecov.yml
Labels: test:unit, ci, v2.0.0, backport 1.x, backport 1.3, backport 2.x, backport 2.0

#1592 Fixes omissions/errors in v2.0.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.0.0.md
Labels: docs, v2.0.0, backport 2.x, backport 2.0

#1598 [Purify] hide option for theme version in settings
  release-notes/opensearch-dashboards.release-notes-2.0.0.md
  src/core/server/ui_settings/settings/theme.ts
Labels: v2.0.0, backport 2.x, backport 2.0

#1599 Removes irrelevant upsell in the timeout message
  .lycheeexclude
  release-notes/opensearch-dashboards.release-notes-2.0.0.md
  src/plugins/data/public/index.ts
  src/plugins/data/public/public.api.md
  src/plugins/data/public/search/errors/timeout_error.test.tsx
  src/plugins/data/public/search/errors/timeout_error.tsx
  src/plugins/data/public/search/search_interceptor.ts
Labels: v2.0.0, backport 1.x, backport 1.3, backport 2.x, backport 2.0, v1.3.3

#1607 [Build][Tests] handle painless scripts update
  src/plugins/home/server/services/sample_data/data_sets/flights/saved_objects.ts
  test/functional/apps/management/_scripted_fields.js
  test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights_index_pattern/data.json.gz
Labels: test:functional, v3.0.0

#1626 [Tests] Update Dockerfile chrome version to match
  Dockerfile
Labels: ci
