Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-08, with the labels that each got.

#2010 Enable CI for multi datasource feature branch
  .github/workflows/build_and_test_workflow.yml
Labels: multiple datasource

#2052 Add empty data source plugin
  src/plugins/data_source/README.md
  src/plugins/data_source/common/index.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/data_source/server/index.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
Labels: dashboards anywhere

#2043 [BUG] Telemetry plugin cluster info rename error
  src/plugins/telemetry/server/telemetry_collection/get_cluster_info.ts
Labels: bug, rename, backport 2.x, v2.2.0

#2042 [BUG] show region blocked warning config not respected
  src/plugins/maps_legacy/public/map/base_maps_visualization.js
  src/plugins/maps_legacy/public/map/service_settings.js
  src/plugins/vis_type_vega/public/services.ts
  src/plugins/vis_type_vega/public/vega_view/vega_map_view.js
Labels: bug, maps, backport 2.x, v2.2.0

#2040 [MD] Add initial credential management CRUD pages
  src/plugins/credential_management/.eslintrc.js
  src/plugins/credential_management/common/index.ts
  src/plugins/credential_management/opensearch_dashboards.json
  src/plugins/credential_management/public/application.tsx
  src/plugins/credential_management/public/components/app.tsx
  src/plugins/credential_management/public/components/breadcrumbs.ts
  src/plugins/credential_management/public/components/create_button/create_button.tsx
  src/plugins/credential_management/public/components/create_button/index.tsx
  src/plugins/credential_management/public/components/create_credential_wizard/components/header/header.tsx
  src/plugins/credential_management/public/components/create_credential_wizard/components/header/index.tsx
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/create_credential_wizard/index.tsx
  src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
  src/plugins/credential_management/public/components/credential_table/index.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential_page.tsx
  src/plugins/credential_management/public/components/edit_credential/index.tsx
  src/plugins/credential_management/public/components/index.tsx
  src/plugins/credential_management/public/components/types.ts
  src/plugins/credential_management/public/components/utils.ts
  src/plugins/credential_management/public/index.ts
  src/plugins/credential_management/public/management_app/index.tsx
  src/plugins/credential_management/public/management_app/mount_management_section.tsx
  src/plugins/credential_management/public/plugin.ts
  src/plugins/credential_management/public/types.ts
  src/plugins/credential_management/server/plugin.ts
  src/plugins/credential_management/server/routes/index.ts
  src/plugins/credential_management/server/saved_objects/credential_saved_objects_type.ts
  src/plugins/credential_management/server/saved_objects/index.ts
Labels: multiple datasource

#1862 [Version] Increment to 2.1.1
  package.json
Labels: docs, v2.1.1

#2071 [D&D] Final fixes
  config/opensearch_dashboards.yml
  src/plugins/saved_objects_management/README.md
  src/plugins/wizard/.i18nrc.json
  src/plugins/wizard/README.md
  src/plugins/wizard/common/wizard_saved_object_attributes.ts
  src/plugins/wizard/config.ts
  src/plugins/wizard/public/application/_util.scss
  src/plugins/wizard/public/application/_variables.scss
  src/plugins/wizard/public/application/app.scss
  src/plugins/wizard/public/application/app.tsx
  src/plugins/wizard/public/application/components/data_tab/config_panel.scss
  src/plugins/wizard/public/application/components/data_tab/dropbox.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
  src/plugins/wizard/public/application/components/data_tab/index.scss
  src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/wizard/public/application/components/searchable_dropdown.scss
  src/plugins/wizard/public/application/components/side_nav.scss
  src/plugins/wizard/public/application/components/top_nav.scss
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/embeddable/disabled_visualization.scss
  src/plugins/wizard/public/services/type_service/types.ts
  src/plugins/wizard/public/services/type_service/visualization_type.tsx
  src/plugins/wizard/server/plugin.ts
  src/plugins/wizard/server/routes/index.ts
  src/plugins/wizard/server/types.ts
Labels: drag & drop

#2066 breadcrumbfix for datasource management
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/types.ts
Labels: multiple datasource

#2070 [D&D] Initial functional tests
  .github/workflows/build_and_test_workflow.yml
  Jenkinsfile
  TESTING.md
  src/plugins/wizard/public/application/components/data_tab/dropbox.tsx
  src/plugins/wizard/public/application/components/data_tab/title.tsx
  src/plugins/wizard/public/application/components/searchable_dropdown.scss
  src/plugins/wizard/public/application/components/searchable_dropdown.tsx
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/visualizations/metric/to_expression.test.ts
  test/common/config.js
  test/examples/embeddables/dashboard.ts
  test/functional/apps/wizard/_base.ts
  test/functional/apps/wizard/_experimental_vis.ts
  test/functional/apps/wizard/index.ts
  test/functional/config.js
  test/functional/page_objects/index.ts
  test/functional/page_objects/wizard_page.ts
  test/mocha_decorations.d.ts
  test/plugin_functional/test_suites/panel_actions/index.js
Labels: drag & drop

#1808 [Deprecation] Deprecate the Blacklist / Whitelist nomenclature
  config/opensearch_dashboards.yml
  packages/opensearch-safer-lodash-set/scripts/update.sh
  packages/osd-pm/dist/index.js
  src/core/server/http/http_server.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/core/server/saved_objects/mappings/lib/get_root_properties_objects.test.ts
  src/dev/license_checker/config.ts
  src/dev/license_checker/index.ts
  src/dev/license_checker/run_check_licenses_cli.ts
  src/legacy/server/config/schema.js
  src/plugins/home/public/application/components/tutorial/__snapshots__/content.test.js.snap
  src/plugins/home/public/application/components/tutorial/content.js
  src/plugins/home/server/tutorials/santa_logs/index.ts
  src/plugins/maps_legacy/config.ts
  src/plugins/maps_legacy/public/map/base_maps_visualization.js
  src/plugins/maps_legacy/public/map/map_messages.js
  src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
  src/plugins/maps_legacy/public/map/service_settings.js
  src/plugins/maps_legacy/server/index.ts
  src/plugins/opensearch_dashboards_react/public/markdown/__snapshots__/markdown.test.tsx.snap
  src/plugins/opensearch_dashboards_react/public/markdown/markdown.test.tsx
  src/plugins/opensearch_dashboards_react/public/markdown/markdown.tsx
  src/plugins/vis_type_timeline/server/index.ts
  src/plugins/vis_type_timeline/server/lib/config_manager.ts
  src/plugins/vis_type_timeline/server/series_functions/fixtures/tl_config.js
  src/plugins/vis_type_timeline/server/series_functions/graphite.test.js
  src/plugins/vis_type_timeline/server/series_functions/helpers/graphite_helper.js
  src/plugins/vis_type_timeline/server/series_functions/helpers/graphite_helper.test.js
  src/plugins/vis_type_timeseries/common/ui_restrictions.ts
  src/plugins/vis_type_timeseries/public/application/lib/check_ui_restrictions.js
  src/plugins/vis_type_timeseries/server/lib/search_strategies/default_search_capabilities.js
  src/plugins/vis_type_timeseries/server/lib/search_strategies/default_search_capabilities.test.js
  src/plugins/vis_type_vega/public/services.ts
  src/plugins/vis_type_vega/public/vega_view/vega_map_view.js
  test/api_integration/apis/core/index.js
Labels: backport 2.x, deprecation, non-inclusive language, v2.2.0

#2069 [MD] Fix breadcrumb on listing page and update credential saved object mapping
  src/plugins/credential_management/public/components/breadcrumbs.ts
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential_page.tsx
  src/plugins/credential_management/public/components/types.ts
  src/plugins/credential_management/public/components/utils.ts
  src/plugins/credential_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts
Labels: ux / ui, multiple datasource

#2080 Alias OUI onto EUI
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
Labels: backport 2.x, v2.2.0

#2085 [Bug] Fix Global Breadcrumb Styling in dark mode
  src/core/public/_variables.scss
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.scss
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: bug, backport 2.x, v2.2.0, backport 2.2

#2084 changes js code to ts in region_map
  src/plugins/region_map/server/plugin.js
  src/plugins/region_map/server/plugin.ts
  src/plugins/region_map/server/routes/index.ts
  src/plugins/region_map/server/routes/opensearch.ts
  src/plugins/region_map/server/services/index.js
  src/plugins/region_map/server/services/opensearch_service.js
Labels: maps, refactor, backport 2.x, v2.2.0, backport 2.2

#2079 [Bug] fix TSVB y-axis
  src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js
Labels: bug, backport 2.x, v2.2.0, backport 2.2

#2101 Bump node version to 14.20.0
  .node-version
  .nvmrc
  Dockerfile
  TESTING.md
  package.json
  src/setup_node_env/node_version_validator.test.js
  yarn.lock
Labels: cve, backport 2.x, v2.2.0, backport 2.2

#2022 [Release] Adds v2.2.0 release note
  release-notes/opensearch-dashboards.release-notes-2.2.0.md
Labels: docs, backport 2.x, v2.2.0, backport 2.2

#2067 [MD] Add delete an existing credential page button
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
  src/plugins/credential_management/public/components/text_content/text_content.ts
Labels: ux / ui, multiple datasource

#2118 [MD][IP]Link datasource to index pattern
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
  src/plugins/data/common/index_patterns/types.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
Labels: multiple datasource

#2054 [CVE-2022-25758] Use dart-sass instead of node-sass
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/integration_tests/__snapshots__/basic_optimization.test.ts.snap
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-ui-framework/Gruntfile.js
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, v3.0.0

#1915 Fixes maps wms zoom limitation
  src/plugins/maps_legacy/public/map/base_maps_visualization.js
Labels: bug, maps, backport 2.x, v2.3.0

#2120 [MD] Add encrypt/decrypt module on data source plugin
  package.json
  src/dev/jest/config.js
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
  src/plugins/credential_management/public/components/text_content/index.ts
  src/plugins/credential_management/public/components/utils.ts
  src/plugins/data_source/common/credentials/index.ts
  src/plugins/data_source/common/credentials/types.ts
  src/plugins/data_source/common/index.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/cryptography/cryptography_client.test.ts
  src/plugins/data_source/server/cryptography/cryptography_client.ts
  src/plugins/data_source/server/cryptography/index.ts
  src/plugins/data_source/server/index.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/credential_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts
  src/plugins/data_source/server/saved_objects/index.ts
Labels: multiple datasource

#2096 increment from 2.2 to 2.3
  package.json
Labels: versioning, v2.3.0

#2146 [MD][IP] Integrate index pattern with new data client
  src/plugins/data/common/index_patterns/index_patterns/__snapshots__/index_patterns.test.ts.snap
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
  src/plugins/data/common/index_patterns/types.ts
  src/plugins/data/public/index_patterns/index_patterns/index_patterns_api_client.ts
  src/plugins/data/server/index_patterns/fetcher/index_patterns_fetcher.ts
  src/plugins/data/server/index_patterns/fetcher/lib/field_capabilities/field_capabilities.ts
  src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
  src/plugins/data/server/index_patterns/fetcher/lib/resolve_time_pattern.ts
  src/plugins/data/server/index_patterns/routes.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/step_time_field.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
  src/plugins/index_pattern_management/server/routes/resolve_index.ts
Labels: multiple datasource

#2154 Add noAuth to dataSource attributes
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/saved_objects/data_source.ts
Labels: multiple datasource

#2128 [MD] Datasource Management - creation & listing - UI only
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_button/index.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/components/credentials_combox_box/credentials_combo_box.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/components/credentials_combox_box/index.ts
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/components/header/index.ts
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/create_edit_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/index.ts
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/edit_data_source/index.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/types.ts
  src/plugins/home/server/tutorials/haproxy_metrics/index.ts
Labels: multiple datasource

#2150 [MD]Apply dataSource plugin as dependent for cm and dsm plugins
  src/plugins/credential_management/opensearch_dashboards.json
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
  src/plugins/credential_management/public/plugin.ts
  src/plugins/credential_management/public/types.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/data_source/public/index.ts
  src/plugins/data_source/public/plugin.ts
  src/plugins/data_source/public/types.ts
  src/plugins/data_source_management/opensearch_dashboards.json
Labels: multiple datasource

#2121 [MD] Register data source plugin interface to route handler context
  src/plugins/data_source/common/index.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/client/client_config.test.ts
  src/plugins/data_source/server/client/client_config.ts
  src/plugins/data_source/server/client/client_pool.test.ts
  src/plugins/data_source/server/client/client_pool.ts
  src/plugins/data_source/server/client/configure_client.test.mocks.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/index.ts
  src/plugins/data_source/server/data_source_service.test.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
Labels: multiple datasource

#2164 [MD][IP]Make step info in index pattern creation dynamic
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/step_time_field.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/creation_flow.test.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/creation_flow.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
Labels: multiple datasource

#2142 [MD][CM]credential listing page
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
  src/plugins/credential_management/public/components/utils.ts
Labels: ux / ui, multiple datasource

#2167 [MD][IP] Integration sequel - replace data client placeholders
  src/plugins/data/opensearch_dashboards.json
  src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
  src/plugins/data/server/index_patterns/routes.ts
  src/plugins/index_pattern_management/server/routes/resolve_index.ts
Labels: multiple datasource

#2170 integrate with crypto module to decrypt password
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/plugin.ts
Labels: multiple datasource

#2165 [MD] noAuth integration, credential & endpoint validation
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/components/credentials_combox_box/credentials_combo_box.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/create_edit_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/home/server/tutorials/haproxy_metrics/index.ts
Labels: multiple datasource

#2171 [MD] Refactor search strategy to conditionally user datasource client
  src/plugins/data/common/search/opensearch_search/types.ts
  src/plugins/data/common/search/search_source/search_source.test.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/opensearch_dashboards.json
  src/plugins/data/server/search/opensearch_search/decide_client.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.test.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
Labels: multiple datasource

#2175 adding relation between credential selection and no auth checkbox
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/create_edit_data_source_wizard.tsx
Labels: multiple datasource

#2176 [MD][IP] Update getIndicesViaSearch with datasource
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.test.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts
Labels: multiple datasource

#2181 Fix CVE-2022-0686, add resolution for url-parse
  package.json
  yarn.lock
Labels: cve, backport 1.3

#2186 Bump chrome driver version in PR check workflow
  .github/workflows/pr_check_workflow.yml
Labels: backport 1.x, backport 1.3

#2188 Add null auth header to child client spawn
  src/plugins/data_source/server/client/configure_client.ts
Labels: multiple datasource

#2129 Bump 2.2 branch version to be 2.2.1
  package.json
Labels: release

#2195 [MD][IP]Update button position & Add UT & Add skip option
  src/fixtures/stubbed_saved_object_index_pattern.ts
  src/plugins/data/common/index_patterns/index_patterns/__snapshots__/index_pattern.test.ts.snap
  src/plugins/data/common/index_patterns/index_patterns/__snapshots__/index_patterns.test.ts.snap
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.test.ts
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.test.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
Labels: multiple datasource

#2202 [MD]Refactor layout and validate input fields for listing and create pages
  src/plugins/credential_management/public/components/breadcrumbs.ts
  src/plugins/credential_management/public/components/common/components/create_credential_form/create_credential_form.tsx
  src/plugins/credential_management/public/components/common/components/create_credential_form/index.tsx
  src/plugins/credential_management/public/components/common/components/header/header.tsx
  src/plugins/credential_management/public/components/common/components/header/index.tsx
  src/plugins/credential_management/public/components/common/components/index.tsx
  src/plugins/credential_management/public/components/common/index.tsx
  src/plugins/credential_management/public/components/common/text_content/index.ts
  src/plugins/credential_management/public/components/common/text_content/text_content.ts
  src/plugins/credential_management/public/components/create_button/create_button.tsx
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
  src/plugins/credential_management/public/components/edit_credential/edit_credential_page.tsx
  src/plugins/credential_management/public/components/edit_credential_wizard/components/edit_credential.tsx
  src/plugins/credential_management/public/components/edit_credential_wizard/components/index.tsx
  src/plugins/credential_management/public/components/edit_credential_wizard/edit_credential_wizard.tsx
  src/plugins/credential_management/public/components/edit_credential_wizard/index.tsx
  src/plugins/credential_management/public/components/index.tsx
  src/plugins/credential_management/public/components/types.ts
  src/plugins/credential_management/public/components/utils.ts
  src/plugins/credential_management/public/types.ts
  src/plugins/data_source/common/credentials/index.ts
  src/plugins/data_source/common/index.ts
  src/plugins/data_source/public/index.ts
  src/plugins/data_source/server/saved_objects/credential_saved_objects_client_wrapper.ts
Labels: ux / ui, multiple datasource

#2138 [DeAngular][visualization][vislib] remove angular from vislib
  src/plugins/vis_type_vislib/public/vislib/lib/binder.ts
Labels: visualizations, technical debt, v2.3.0, de-angular

#2193 [D&D] metadata slice 1879
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/application/utils/state_management/metadata_slice.ts
  src/plugins/wizard/public/application/utils/state_management/store.ts
  src/plugins/wizard/public/application/utils/use/use_can_save.ts
  src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
  yarn.lock
Labels: drag & drop, v2.3.0

#2235 [MD][IP] Update configure data source per UX input
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.scss
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
Labels: multiple datasource

#2222 [MD] Refactor of credential editing page layout & refactor backend field validation method
  src/plugins/credential_management/public/components/common/components/create_credential_form/create_credential_form.tsx
  src/plugins/credential_management/public/components/common/components/header/header.tsx
  src/plugins/credential_management/public/components/common/text_content/text_content.ts
  src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
  src/plugins/credential_management/public/components/edit_credential_wizard/components/edit_credential.tsx
  src/plugins/data_source/server/saved_objects/credential_saved_objects_client_wrapper.ts
Labels: ux / ui, multiple datasource

#2231 [D&D] Adds count field to field picker
  src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
  src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/wizard/public/application/utils/drag_drop/types.ts
Labels: drag & drop, backport 2.x, v2.3.0

#2238 [MD][IP]Tweak fetch data back to original
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
Labels: multiple datasource

#2232 Custom healthcheck with filters
  config/opensearch_dashboards.yml
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/core/server/opensearch/opensearch_service.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: backport 1.x, backport 1.3, backport 1.2, backport 2.x, backport 2.0, backport 2.1, v2.3.0, backport 2.2

#2217 [D&D] Adds visualization type switcher for Wizard
  src/plugins/wizard/public/application/app.scss
  src/plugins/wizard/public/application/app.tsx
  src/plugins/wizard/public/application/components/data_source_select.tsx
  src/plugins/wizard/public/application/components/data_tab/config_panel.scss
  src/plugins/wizard/public/application/components/left_nav.tsx
  src/plugins/wizard/public/application/components/option.scss
  src/plugins/wizard/public/application/components/option.tsx
  src/plugins/wizard/public/application/components/right_nav.tsx
  src/plugins/wizard/public/application/components/side_nav.scss
  src/plugins/wizard/public/application/components/side_nav.tsx
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/application/utils/state_management/index.ts
  src/plugins/wizard/public/application/utils/state_management/shared_actions.ts
  src/plugins/wizard/public/application/utils/state_management/style_slice.ts
  src/plugins/wizard/public/application/utils/state_management/visualization_slice.ts
  src/plugins/wizard/public/visualizations/metric/components/metric_viz_options.tsx
Labels: drag & drop, backport 2.x, v2.3.0
