Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-01, with the labels that each got.

#995 Field Search in Data panel
  src/plugins/wizard/public/application/components/data_tab/field_search.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/utils/state_management/datasource_slice.ts
Labels: drag & drop

#1028 [Node 14] Upgrades Node version to 14.18.2
  .github/workflows/pr_check_workflow.yml
  .node-version
  .nvmrc
  Dockerfile
  TESTING.md
  package.json
  packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
  packages/osd-config-schema/src/types/stream_type.test.ts
  packages/osd-dev-utils/src/proc_runner/proc.ts
  packages/osd-dev-utils/src/tooling_log/__snapshots__/tooling_log_text_writer.test.ts.snap
  packages/osd-i18n/package.json
  packages/osd-i18n/src/__snapshots__/loader.test.ts.snap
  packages/osd-interpreter/package.json
  packages/osd-opensearch-archiver/src/lib/streams/concat_stream_providers.test.js
  packages/osd-opensearch-archiver/src/lib/streams/reduce_stream.test.js
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/node/cache.ts
  packages/osd-optimizer/src/node/node_auto_tranpilation.ts
  packages/osd-optimizer/src/optimizer/get_mtimes.ts
  packages/osd-optimizer/src/optimizer/observe_worker.ts
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-storybook/package.json
  packages/osd-storybook/webpack.config.ts
  packages/osd-test/src/functional_test_runner/lib/docker_servers/container_logs.ts
  packages/osd-test/src/functional_test_runner/lib/lifecycle_phase.test.ts
  packages/osd-test/src/osd/osd_test_config.ts
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/cli/cluster/cluster.mock.ts
  src/cli/repl/__snapshots__/repl.test.js.snap
  src/core/public/utils/crypto/sha256.ts
  src/core/server/core_usage_data/core_usage_data_service.test.ts
  src/core/server/http/__snapshots__/http_config.test.ts.snap
  src/core/server/http/http_server.test.ts
  src/core/server/http/http_tools.test.ts
  src/core/server/http/router/validator/validator.test.ts
  src/core/server/logging/appenders/file/file_appender.test.ts
  src/core/server/logging/appenders/file/file_appender.ts
  src/core/server/metrics/collectors/process.test.ts
  src/core/server/metrics/integration_tests/server_collector.test.ts
  src/core/server/metrics/metrics_service.test.ts
  src/core/server/opensearch/client/configure_client.test.ts
  src/core/server/plugins/discovery/plugins_discovery.ts
  src/core/server/utils/streams/concat_stream_providers.test.ts
  src/core/server/utils/streams/reduce_stream.test.ts
  src/dev/jest/config.js
  src/legacy/server/logging/index.js
  src/plugins/console/public/application/models/sense_editor/__tests__/integration.test.js
  src/plugins/inspector/public/views/data/components/__snapshots__/data_view.test.tsx.snap
  src/plugins/opensearch_dashboards_utils/public/core/create_start_service_getter.test.ts
  src/plugins/opensearch_dashboards_utils/public/state_management/url/format.ts
  src/plugins/opensearch_dashboards_utils/public/state_management/url/osd_url_storage.ts
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: build, dependencies, v2.0.0, >upgrade

#931 [Backwards Compatibility] add a script to use one command to run all bwc tests
  package.json
  scripts/bwctest-osd.sh
Labels: v1.3.0, test:bwc

#1110 [Docs] remove invalid reference in CONVENTIONS.md
  src/core/CONVENTIONS.md
Labels: docs

#1104 Upgrades `babel`, `storybook`, and `postcss`
  package.json
  packages/opensearch-eslint-config-opensearch-dashboards/package.json
  packages/osd-analytics/package.json
  packages/osd-babel-preset/package.json
  packages/osd-dev-utils/package.json
  packages/osd-i18n/package.json
  packages/osd-interpreter/package.json
  packages/osd-monaco/package.json
  packages/osd-opensearch/package.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/integration_tests/__snapshots__/basic_optimization.test.ts.snap
  packages/osd-optimizer/src/integration_tests/basic_optimization.test.ts
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-plugin-helpers/src/integration_tests/build.test.ts
  packages/osd-pm/package.json
  packages/osd-storybook/lib/default_config.ts
  packages/osd-storybook/package.json
  packages/osd-storybook/webpack.config.ts
  packages/osd-test/package.json
  packages/osd-ui-framework/doc_site/webpack.config.js
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/dev/i18n/extractors/__snapshots__/html.test.js.snap
  yarn.lock
Labels: dependencies, v2.0.0, security fix

#1106 Bumps `@microsoft/api-documenter` and `@microsoft/api-extractor`
  package.json
  yarn.lock
Labels: dependencies, v2.0.0, security fix

#1030 [Backwards Compatibility] update instructions in TESTING.md
  TESTING.md
Labels: v1.3.0, test:bwc

#1149 Disable WhiteSource check fails on commits/PRs
  .whitesource
  whitesource.config
Labels: configuration error

#1143 [BUG] fix disableWelcomeScreen config
  src/plugins/home/server/index.ts
Labels: bug
