Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-11, with the labels that each got.

#2706 [Backport 2.x]Bump loader-utils to 2.0.3 to fix CVE-2022-37601
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: security vulnerability, cve, v2.4.0

#2707 [Backport 1.x] Bump loader-utils to 2.0.3 to fix CVE-2022-37601
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: security vulnerability, cve, v1.3.7

#2703 Adds @osd/cross-platform
  CHANGELOG.md
  package.json
  packages/osd-config-schema/package.json
  packages/osd-config-schema/src/errors/schema_error.test.ts
  packages/osd-cross-platform/README.md
  packages/osd-cross-platform/package.json
  packages/osd-cross-platform/src/__snapshots__/path.test.ts.snap
  packages/osd-cross-platform/src/index.ts
  packages/osd-cross-platform/src/path.test.ts
  packages/osd-cross-platform/src/path.ts
  packages/osd-cross-platform/src/process.ts
  packages/osd-cross-platform/src/repo_root.ts
  packages/osd-cross-platform/tsconfig.json
  packages/osd-dev-utils/src/serializers/absolute_path_serializer.ts
  packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.js
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/node/cache.ts
  packages/osd-optimizer/src/node/node_auto_tranpilation.ts
  packages/osd-optimizer/src/optimizer/cache_keys.test.ts
  packages/osd-optimizer/src/optimizer/cache_keys.ts
  packages/osd-optimizer/src/optimizer/get_changes.test.ts
  packages/osd-plugin-generator/package.json
  packages/osd-plugin-generator/src/cli.ts
  packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts
  packages/osd-plugin-helpers/package.json
  packages/osd-plugin-helpers/src/cli.ts
  packages/osd-plugin-helpers/src/integration_tests/build.test.ts
  packages/osd-plugin-helpers/src/tasks/create_archive.ts
  packages/osd-pm/package.json
  packages/osd-pm/src/utils/projects.test.ts
  packages/osd-pm/src/utils/projects_tree.ts
  packages/osd-utils/package.json
  packages/osd-utils/src/index.ts
  packages/osd-utils/src/package_json/index.ts
  packages/osd-utils/src/path/index.ts
  src/cli_plugin/install/download.test.js
  src/cli_plugin/install/opensearch_dashboards.test.js
  src/cli_plugin/install/pack.test.js
  src/cli_plugin/list/list.test.js
  src/cli_plugin/remove/remove.test.js
  src/core/server/plugins/discovery/plugins_discovery.test.ts
  src/core/server/plugins/plugins_service.test.ts
  src/dev/build/lib/config.test.ts
  src/dev/build/lib/integration_tests/fs.test.ts
  src/dev/build/lib/integration_tests/scan_copy.test.ts
  src/dev/build/lib/scan_delete.test.ts
  src/dev/file.ts
  src/dev/i18n/integrate_locale_files.test.ts
  src/dev/i18n/utils/utils.js
  src/dev/jest/config.js
  src/dev/jest/integration_tests/junit_reporter.test.js
Labels: v2.4.0

#2709 [CVE-2022-33987][2.x]Re-upgrade geckodriver to 3.0.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport, cve, v2.4.0, backport 2.4

#2693 [MD]Update MD data source documentation link
  CHANGELOG.md
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
Labels: docs, backport 2.x, multiple datasource, v2.4.0

#2726 Add `Skip-Changelog` label to skip changelog verification on certain PRs
  .github/workflows/changelog_verifier.yml
Labels: Skip-Changelog

#2725 Enable visbuilder by default
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/vis_builder/config.ts
  src/plugins/vis_builder/server/index.ts
  test/common/config.js
  test/functional/config.js
Labels: vis builder, backport 2.x, v2.4.0, backport 2.4

#2729 Update backport workflow to ignore changelog conflicts
  .github/workflows/backport.yml
Labels: backport 2.x, backport 2.4, Skip-Changelog

#2713 [Backport 2.x] Removed Leftover X Pack references
  CHANGELOG.md
  packages/osd-pm/src/utils/validate_dependencies.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/opensearch_index.ts
  src/dev/notice/cli.js
  src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
  src/plugins/data/README.md
Labels: backport 2.0, backport 2.1, v2.4.0, backport 2.2, backport 2.3, backport 2.4

#2724 [MD] Tweak multiple data source design doc
  CHANGELOG.md
  docs/multi-datasource/client_management_design.md
Labels: docs, v2.4.0

#2723 Removes Add Integration button
  CHANGELOG.md
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/empty_state.tsx
Labels: v2.4.0

#2746 Prevent backport workflow from running on umerged PRs
  .github/workflows/backport.yml
Labels: Skip-Changelog

#2728 [Vis Builder] Enable VisBuilder cypress tests
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: vis builder, backport 2.x, v2.4.0, backport 2.4

#2766 [CI] update backport custom branch name
  .github/workflows/backport.yml
  CHANGELOG.md
Labels: ci, backport 1.x, backport 2.x, backport 2.4

#2767 [Backport 2.x] [Vis Builder] Remaining vis builder rename backport
  config/opensearch_dashboards.yml
  src/plugins/saved_objects/README.md
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/saved_objects_management/public/register_services.ts
  src/plugins/vis_builder/README.md
  src/plugins/vis_builder/common/index.ts
  src/plugins/vis_builder/common/vis_builder_saved_object_attributes.ts
  src/plugins/vis_builder/opensearch_dashboards.json
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/assets/vis_builder_icon.svg
  src/plugins/vis_builder/public/assets/vis_builder_icon_secondary_fill.svg
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/server/capabilities_provider.ts
  src/plugins/vis_builder/server/plugin.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_app.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_migration.test.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_migration.ts
  src/plugins/visualize/public/application/components/visualize_listing.scss
  src/plugins/visualize/public/application/utils/get_table_columns.tsx
  test/common/config.js
  test/functional/apps/vis_builder/_base.ts
  test/functional/apps/vis_builder/_experimental_vis.ts
  test/functional/apps/vis_builder/index.ts
  test/functional/apps/visualize/_chart_types.ts
  test/functional/config.js
  test/functional/page_objects/index.ts
  test/functional/page_objects/vis_builder_page.ts
Labels: autocut

#2776 [Backport 2.4] Adding @zengyan-amazon as a Dashboards co-maintainer
  CHANGELOG.md
  MAINTAINERS.md
Labels: autocut

#2775 [Backport 2.x] Adding @zengyan-amazon as a Dashboards co-maintainer
  CHANGELOG.md
  MAINTAINERS.md
Labels: autocut

#2540 [Legacy Maps Plugin] Prevent reverse-tabnabbing
  CHANGELOG.md
  src/plugins/maps_legacy/public/map/map_messages.js
Labels: backport 2.x

#2774 [Backport 2.4][Vis Builder] Bug fixes for datasource picker and auto time interval
  src/core/public/saved_objects/simple_saved_object.ts
  src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/vis_builder/public/application/components/option.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
  src/plugins/vis_builder/public/application/utils/use/index.ts
  src/plugins/vis_builder/public/application/utils/use/use_aggs.ts
  src/plugins/vis_builder/public/application/utils/validate_schema_state.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/services/type_service/types.ts
  src/plugins/vis_builder/public/services/type_service/visualization_type.tsx
  src/plugins/vis_builder/public/visualizations/metric/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/area/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/common/create_vis.ts
  src/plugins/vis_builder/public/visualizations/vislib/common/types.ts
  src/plugins/vis_builder/public/visualizations/vislib/histogram/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/line/to_expression.ts
Labels: autocut

#2716 [Backport 1.x] Removed Leftover X Pack references
  CHANGELOG.md
  packages/osd-pm/src/utils/validate_dependencies.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/opensearch_index.ts
  src/dev/notice/cli.js
  src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
  src/plugins/data/README.md
Labels: backport 1.3, backport 1.2, backport 1.1, backport 1.0

#2772 change geckodriver version to make consistency
  CHANGELOG.md
  package.json
  yarn.lock
Labels: v2.4.0

#2705 [Vis Builder] Add an experimental table visualization in vis builder
  CHANGELOG.md
  src/plugins/vis_builder/README.md
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/visualizations/common/expression_helpers.ts
  src/plugins/vis_builder/public/visualizations/index.ts
  src/plugins/vis_builder/public/visualizations/table/components/table_viz_options.tsx
  src/plugins/vis_builder/public/visualizations/table/index.ts
  src/plugins/vis_builder/public/visualizations/table/table_viz_type.ts
  src/plugins/vis_builder/public/visualizations/table/to_expression.ts
  src/plugins/vis_type_table_new/README.md
  src/plugins/vis_type_table_new/opensearch_dashboards.json
  src/plugins/vis_type_table_new/public/components/table_vis_app.scss
  src/plugins/vis_type_table_new/public/components/table_vis_app.tsx
  src/plugins/vis_type_table_new/public/components/table_vis_component.tsx
  src/plugins/vis_type_table_new/public/components/table_vis_component_group.tsx
  src/plugins/vis_type_table_new/public/components/table_vis_control.tsx
  src/plugins/vis_type_table_new/public/components/table_vis_grid_columns.tsx
  src/plugins/vis_type_table_new/public/index.ts
  src/plugins/vis_type_table_new/public/plugin.ts
  src/plugins/vis_type_table_new/public/services.ts
  src/plugins/vis_type_table_new/public/table_vis_fn.ts
  src/plugins/vis_type_table_new/public/table_vis_renderer.tsx
  src/plugins/vis_type_table_new/public/table_vis_response_handler.ts
  src/plugins/vis_type_table_new/public/types.ts
  src/plugins/vis_type_table_new/public/utils/convert_to_csv_data.ts
  src/plugins/vis_type_table_new/public/utils/convert_to_formatted_data.ts
  src/plugins/vis_type_table_new/public/utils/index.ts
  src/plugins/vis_type_table_new/public/utils/use_pagination.ts
Labels: vis builder, backport 2.x, v2.4.0, tableVis, backport 2.4

#2777 [Backport 2.x][Chore] Refactor and improve Discover field summaries
  CHANGELOG.md
  src/core/public/mocks.ts
  src/plugins/discover/public/application/components/sidebar/discover_field.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_bucket.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_details.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_details.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/sidebar/lib/field_calculator.js
  src/plugins/discover/public/application/components/sidebar/lib/field_calculator.test.ts
  src/plugins/discover/public/application/components/sidebar/lib/field_calculator.ts
  src/plugins/discover/public/application/components/sidebar/lib/get_details.ts
  src/plugins/discover/public/application/components/sidebar/types.ts
  test/functional/apps/management/_scripted_fields.js
Labels: autocut

#2778 [Backport 2.4][Chore] Refactor and improve Discover field summaries
  CHANGELOG.md
  src/core/public/mocks.ts
  src/plugins/discover/public/application/components/sidebar/discover_field.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_bucket.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_details.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_details.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/sidebar/lib/field_calculator.js
  src/plugins/discover/public/application/components/sidebar/lib/field_calculator.test.ts
  src/plugins/discover/public/application/components/sidebar/lib/field_calculator.ts
  src/plugins/discover/public/application/components/sidebar/lib/get_details.ts
  src/plugins/discover/public/application/components/sidebar/types.ts
  test/functional/apps/management/_scripted_fields.js
Labels: autocut

#2674 Security-CVEs fixes guidelines
  SECURITY.md
Labels: docs

#2784 [Backport 2.x] [CI] update backport custom branch name (#2766)
  .github/workflows/backport.yml
  CHANGELOG.md
Labels: backport 2.4

#2793 [MD] Update default audit log path
  CHANGELOG.md
  src/plugins/data_source/README.md
  src/plugins/data_source/audit_config.ts
  src/plugins/data_source/config.ts
Labels: backport 2.x, multiple datasource, v2.4.0, backport 2.4

#2789 [Backport 2.x]Change geckodriver version to make consistency
  package.json
  yarn.lock
Labels: autocut

#2790 [Backport 2.4]Change geckodriver version to make consistency
  package.json
  yarn.lock
Labels: autocut

#2682 [Vis Builder] Add field summary popovers
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/data_tab/field.scss
  src/plugins/vis_builder/public/application/components/data_tab/field.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_bucket.scss
  src/plugins/vis_builder/public/application/components/data_tab/field_bucket.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_details.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_details.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_selector.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_selector.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_selector_field.tsx
  src/plugins/vis_builder/public/application/components/data_tab/types.ts
  src/plugins/vis_builder/public/application/components/data_tab/utils/field_calculator.test.ts
  src/plugins/vis_builder/public/application/components/data_tab/utils/field_calculator.ts
  src/plugins/vis_builder/public/application/components/data_tab/utils/get_field_details.ts
  src/plugins/vis_builder/public/application/components/data_tab/utils/index.ts
  src/plugins/vis_builder/public/application/utils/drag_drop/drag_drop_context.tsx
  src/plugins/vis_builder/public/application/utils/drag_drop/index.ts
  src/plugins/vis_builder/public/application/utils/use/index.ts
  src/plugins/vis_builder/public/application/utils/use/use_on_add_filter.ts
  src/plugins/vis_builder/public/application/utils/use/use_sample_hits.ts
Labels: vis builder, backport 2.x, v2.4.0, backport 2.4

#2773 [Backport 2.4] Enable visbuilder by default (#2725)
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/vis_builder/config.ts
  src/plugins/vis_builder/server/index.ts
  test/functional/config.js
Labels: autocut

#2801 Bump makelogs to remove dependency on got
  CHANGELOG.md
  yarn.lock
Labels: cve, backport 2.x, v2.4.0, backport 2.4

#2802 [Backport 2.x][CVE-2022-33987]Bump makelogs to remove dependency on got (#2801)
  yarn.lock
Labels: cve, autocut, backport 2.4

#2803 [Backport 2.4][CVE-2022-33987]Bump makelogs to remove dependency on got
  yarn.lock
Labels: cve, autocut

#2804 [VisBuilder] Change VisBuilder flag for docker config
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
Labels: vis builder, backport 2.x, backport 2.4, Skip-Changelog

#2809 Adds CHANGELOG.md and Release Notes for 2.4.0
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.4.0.md
Labels: docs, v2.4.0

#2818 [MD] Add explicit no spellcheck on password fields
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/__snapshots__/edit_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/__snapshots__/edit_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/__snapshots__/update_password_modal.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
Labels: security feature, backport 2.x, multiple datasource, v2.4.0, backport 2.4

#2828 [Bug][Table Visualization] Fix first column sort issue
  CHANGELOG.md
  src/plugins/vis_type_table_new/public/components/table_vis_component.tsx
Labels: bug, backport 2.x, v2.4.0, tableVis, backport 2.4

#2838 [2.4] Update release note for fixing table vis bug
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.4.0.md
Labels: docs, v2.4.0

#2842 Temporarily prevents `task-kill` exceptions on Windows when it is passed a `pid` for a process that is already dead
  CHANGELOG.md
  packages/osd-opensearch/src/cluster.js
Labels: backport 2.x, v2.4.0, windows, backport 2.4

#2846 Update release note and CHANGELOG for 2842
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.4.0.md
Labels: docs, v2.4.0

#2533 Add the release runbook to RELEASING.md
  CHANGELOG.md
  RELEASING.md
Labels: docs

#2853 [VisBuilder] [BUG] fix empty workspace animation does not work in firefox
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/workspace.scss
  src/plugins/vis_builder/public/application/components/workspace.tsx
Labels: backport 2.x

#2867 [Vis Builder] Removed Hard Coded Strings and Used i18n to translate
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/data_tab/dropbox.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
Labels: backport 2.x, v2.5.0

#2883 Bump version to 2.4.1
  package.json
Labels: versioning, v2.4.1

#2884 Bump version on 2.x branch to 2.5.0
  package.json
Labels: versioning, v2.5.0

#2695 [Doc] Document `charts` plugin
  CHANGELOG.md
  docs/charts/current_usage.md
  src/plugins/charts/README.md
Labels: docs, backport 2.x, v2.5.0

#2711 [WS-2021-0638][Security] bump mocha to 10.1.0
  CHANGELOG.md
  package.json
  packages/osd-test/src/functional_test_runner/integration/failure_hooks.test.js
  packages/osd-test/src/functional_test_runner/lib/mocha/filter_suites_by_tags.test.js
  yarn.lock
Labels: security fix, v3.0.0

#2873 OSD-2847 bump del version to fix race condition
  CHANGELOG.md
  package.json
  packages/osd-i18n/package.json
  packages/osd-interpreter/package.json
  packages/osd-monaco/package.json
  packages/osd-opensearch/package.json
  packages/osd-optimizer/package.json
  packages/osd-plugin-helpers/package.json
  packages/osd-pm/package.json
  packages/osd-test/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: backport 1.x, backport 2.x, v2.5.0

#2817 [i18n] Register `ru`, `ru-RU` locale
  CHANGELOG.md
  packages/osd-i18n/src/core/locales.js
Labels: i18n, backport 1.x, backport 2.x, v2.5.0

#2881 Add 2.4.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.4.0.md
Labels: backport 2.x, Skip-Changelog

#2908 Reenable CI tests for feature branches
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: ci

#2950 [Backport 1.3 - Manual] [Backport 1.x] [Legacy Maps Plugin] Prevent reverse-tabnabbing (#2934) (#2540)
  CHANGELOG.md
  src/plugins/maps_legacy/public/map/map_messages.js
Labels: v1.3.7

#2954 [Backport 1.x][CI] update backport custom branch name (#2766)
  .github/workflows/backport.yml
  CHANGELOG.md
Labels: backport 1.3, v1.3.7

#2946 [Manual] [Backport 1.x] Bump minimatch to 3.0.5 and [IBM X-Force ID: 220063] unset-value to 2.0.1
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3, v1.3.7

#2951 [Backport - Manual] [CVE] Remove storybook package to fix CVE-2021-42740 and CVE-2021-24033 (#2660)
  .eslintrc.js
  CHANGELOG.md
  package.json
  packages/osd-storybook/README.md
  packages/osd-storybook/index.ts
  packages/osd-storybook/lib/constants.ts
  packages/osd-storybook/lib/default_config.ts
  packages/osd-storybook/lib/register.ts
  packages/osd-storybook/lib/run_storybook_cli.ts
  packages/osd-storybook/lib/templates/index.ejs
  packages/osd-storybook/package.json
  packages/osd-storybook/preset.js
  packages/osd-storybook/tsconfig.json
  packages/osd-storybook/typings.d.ts
  packages/osd-storybook/webpack.config.ts
  packages/osd-storybook/yarn.lock
  scripts/storybook.js
  src/dev/precommit_hook/casing_check_config.js
  src/dev/storybook/aliases.ts
  src/dev/storybook/commands/clean.ts
  src/dev/storybook/run_storybook_cli.ts
  src/plugins/embeddable/.storybook/main.js
  src/plugins/embeddable/public/components/panel_options_menu/__examples__/panel_options_menu.stories.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/.storybook/main.js
  src/plugins/opensearch_dashboards_react/public/code_editor/README.md
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.stories.tsx
  tsconfig.base.json
  yarn.lock
Labels: v1.3.7

#2964 [Build] Update folder timestamps after copying files into them using `scanCopy`
  CHANGELOG.md
  src/dev/build/lib/scan_copy.ts
Labels: bug, build, backport 1.x, backport 1.3, backport 2.x, v1.3.7

#2952 [Backport - Manual] Bump prismjs to 1.29.0 to fix CVE-2022-23647 (#2668)
  CHANGELOG.md
  yarn.lock
Labels: v1.3.7
