Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-03, with the labels that each got.

#1300 Removes unnecessary manual `resolutions`
  package.json
  packages/osd-plugin-generator/package.json
  yarn.lock
Labels: dependencies, v2.0.0

#1285 [Build] Build ARM64 for deb and rpm
  DEVELOPER_GUIDE.md
  src/dev/build/args.test.ts
  src/dev/build/args.ts
  src/dev/build/build_distributables.ts
  src/dev/build/lib/runner.test.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
  src/dev/build/tasks/os_packages/create_os_package_tasks.test.ts
  src/dev/build/tasks/os_packages/create_os_package_tasks.ts
  src/dev/build/tasks/os_packages/package_scripts/pre_install.sh
  src/dev/build/tasks/os_packages/package_scripts/pre_remove.sh
  src/dev/build/tasks/os_packages/run_fpm.ts
Labels: build, v1.3.0, backport 1.x

#1307 remove native realm from code base
  packages/osd-opensearch/src/cli_commands/archive.js
  packages/osd-opensearch/src/cli_commands/snapshot.js
  packages/osd-opensearch/src/cli_commands/source.js
  packages/osd-opensearch/src/cluster.js
  packages/osd-opensearch/src/utils/index.js
  packages/osd-opensearch/src/utils/native_realm.js
  packages/osd-opensearch/src/utils/native_realm.test.js
Labels: bug, xpack-cleanup

#1301 Upgrades `jest` to v27
  .eslintrc.js
  package.json
  packages/opensearch-eslint-config-opensearch-dashboards/package.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/optimizer/cache_keys.test.ts
  packages/osd-optimizer/src/optimizer/cache_keys.ts
  packages/osd-optimizer/src/optimizer/optimizer_config.test.ts
  packages/osd-spec-to-console/package.json
  packages/osd-ui-shared-deps/package.json
  src/core/TESTING.md
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/http/integration_tests/request.test.ts
  src/core/server/legacy/merge_vars.test.ts
  src/core/server/legacy/merge_vars.ts
  src/core/server/metrics/integration_tests/server_collector.test.ts
  src/core/server/metrics/metrics_service.test.ts
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/opensearch_service.test.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/ui_settings/integration_tests/index.test.ts
  src/dev/jest/babel_transform.js
  src/dev/jest/config.js
  src/legacy/server/logging/rotate/log_rotator.test.ts
  src/plugins/dashboard/public/application/embeddable/dashboard_container.test.tsx
  src/plugins/dashboard/public/application/embeddable/grid/dashboard_grid.test.tsx
  src/plugins/dashboard/public/application/embeddable/viewport/dashboard_viewport.test.tsx
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.test.ts
  src/plugins/data/common/search/search_source/legacy/fetch_soon.test.ts
  src/plugins/data/common/utils/abort_utils.test.ts
  src/plugins/data/common/utils/abort_utils.ts
  src/plugins/data/public/query/filter_manager/lib/generate_mapping_chain.test.ts
  src/plugins/data/public/query/filter_manager/lib/map_filter.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_exists.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_geo_bounding_box.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_geo_polygon.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_match_all.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_missing.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_phrase.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_query_string.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_range.test.ts
  src/plugins/data/public/query/filter_manager/lib/mappers/map_spatial_filter.test.ts
  src/plugins/data/public/search/search_interceptor.test.ts
  src/plugins/data/public/search/search_interceptor.ts
  src/plugins/embeddable/public/lib/embeddables/embeddable.test.tsx
  src/plugins/embeddable/public/lib/embeddables/embeddable_renderer.test.tsx
  src/plugins/embeddable/public/lib/embeddables/error_embeddable.test.tsx
  src/plugins/embeddable/public/lib/panel/embeddable_panel.test.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/customize_title/customize_panel_action.test.ts
  src/plugins/embeddable/public/tests/container.test.ts
  src/plugins/embeddable/public/tests/explicit_input.test.ts
  src/plugins/expressions/common/execution/execution.ts
  src/plugins/expressions/common/execution/execution_contract.test.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/ensure_minimum_time.test.ts
  src/plugins/opensearch_dashboards_usage_collection/server/collectors/application_usage/telemetry_application_usage_collector.test.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_summary.test.tsx
  src/plugins/vis_type_markdown/public/markdown_vis_controller.test.tsx
  yarn.lock
Labels: >test:unit, test:integration, dependencies, v2.0.0

#1306 Runs GitHub workflow unit tests in band
  .github/workflows/pr_check_workflow.yml
  package.json
  packages/osd-pm/src/run.test.ts
  src/plugins/embeddable/public/lib/embeddables/error_embeddable.test.tsx
  src/plugins/vis_type_markdown/public/markdown_vis_controller.test.tsx
  src/plugins/vis_type_tagcloud/public/components/tag_cloud_visualization.test.js
  src/plugins/visualize/public/application/utils/use/use_visualize_app_state.test.ts
Labels: >test:unit, v2.0.0

#1302 [BUG] fix median.ts to work for scripted field
  src/plugins/data/common/search/aggs/metrics/__snapshots__/median.test.ts.snap
  src/plugins/data/common/search/aggs/metrics/median.test.ts
  src/plugins/data/common/search/aggs/metrics/median.ts
Labels: bug, v1.3.0, backport 1.x

#1323 [Bug] Solve saved query bug
  src/plugins/data/public/query/saved_query/saved_query_service.test.ts
  src/plugins/data/public/query/saved_query/saved_query_service.ts
Labels: bug, v1.3.0, backport 1.x

#1316 [Plugins] update default url for installing plugins
  packages/osd-opensearch/src/artifact.test.js
  src/cli_plugin/install/settings.js
  src/cli_plugin/install/settings.test.js
Labels: v1.3.0, backport 1.x

#1329 [Branding] assets folder and SSL support
  assets/.gitignore
  src/core/server/core_app/core_app.ts
  src/core/server/rendering/rendering_service.tsx
  src/dev/build/tasks/clean_tasks.ts
  src/dev/build/tasks/create_empty_dirs_and_files_task.ts
  src/dev/build/tasks/os_packages/run_fpm.ts
  test/server_integration/http/ssl/index.js
Labels: branding, v1.3.0, backport 1.x

#1327 [CVE] Decode anchor ID in Discover
  src/plugins/discover/public/application/angular/context.js
  test/functional/apps/discover/_indexpattern_with_encoded_id.ts
  test/functional/apps/discover/index.js
  test/functional/fixtures/opensearch_archiver/index_pattern_with_encoded_id/data.json
  test/functional/fixtures/opensearch_archiver/index_pattern_with_encoded_id/mappings.json
Labels: v1.3.0, cve, backport 1.x

#1333 [Docs] update branch version to 1.3
  package.json
Labels: docs, v1.3.0

#1334 [Tests] remove include_type_name from OpenSearch Archiver
  packages/osd-opensearch-archiver/src/lib/indices/__tests__/create_index_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.ts
Labels: test:functional

#1338 [Tests] fix JUnit Reporter test
  src/dev/jest/integration_tests/__fixtures__/test.js
Labels: test:integration

#1320 Resolves `ansi-regex` to v5.0.1
  package.json
  yarn.lock
Labels: dependencies, v2.0.0

#1348 Add release notes for Dashboards 1.3.0
  release-notes/opensearch-dashboards.release-notes-1.3.0.md
Labels: docs, backport 1.3, backport main

#1356 Runs functional test jobs in parallel w/ build job
  .github/workflows/pr_check_workflow.yml
Labels: test:functional, ci

#1346 Fixes inconsistent plugin installation tests
  src/cli_plugin/install/settings.test.js
Labels: test:unit, backport 1.x

#1369 Bumps `node-forge` from v1.2.1 to v1.3.0
  package.json
  yarn.lock
Labels: dependencies, v2.0.0, cve

#1371 [CI][Build] Use BUILD_NUMBER for building bundles
  src/dev/build/lib/get_build_number.test.ts
  src/dev/build/lib/get_build_number.ts
Labels: ci, backport 1.x

#1380 Resolves all `qs` dependencies to v6.10.3
  package.json
  yarn.lock
Labels: dependencies, v2.0.0, cve

#1385 Bumps `json-schema` from 0.2.3 to 0.4.0
  package.json
  yarn.lock
Labels: dependencies, cve, backport 1.x, v1.4.0

#1362 Bump the version to 1.3.1
  package.json
Labels: v1.3.1

#1386 [Improvement] node healthcheck optimization
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: backport 1.x, backport 1.3

#1396 [Backport 1.x] [Improvement] node healthcheck optimization (#1386)
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: v1.4.0

#1397 [Backport 1.3] [Improvement] node healthcheck optimization (#1386)
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: v1.3.1
