Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-09, with the labels that each got.

#2239 [MD] Revamped UX for data source management
  src/plugins/credential_management/public/components/common/components/create_credential_form/create_credential_form.tsx
  src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
  src/plugins/credential_management/public/index.ts
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/index.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/index.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/create_edit_data_source_wizard/create_edit_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/credentials_combox_box/credentials_combo_box.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/index.ts
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/loading_mask/index.ts
  src/plugins/data_source_management/public/components/loading_mask/loading_mask.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/types.ts
Labels: multiple datasource

#2255 add release note for 1.3.5
  release-notes/opensearch-dashboards.release-notes-1.3.5.md
Labels: docs, backport 1.3, v1.3.5

#2256 add release note for 2.2.1
  release-notes/opensearch-dashboards.release-notes-2.2.1.md
Labels: docs, backport 2.x, backport 2.2

#2253 [MD] Credentials security redesign
  src/plugins/data_source/common/credentials/index.ts
  src/plugins/data_source/common/credentials/types.ts
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/common/index.ts
  src/plugins/data_source/public/index.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/credential_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/saved_objects/index.ts
Labels: multiple datasource

#2264 [MD]Add step data source UI test
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/__snapshots__/step_data_source.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
Labels: test:unit, multiple datasource

#2218 [D&D] Save index pattern using proper saved object structure
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
  src/plugins/wizard/public/saved_visualizations/_saved_vis.ts
  src/plugins/wizard/public/saved_visualizations/saved_visualization_references.ts
  src/plugins/wizard/server/saved_objects/wizard_app.ts
  src/plugins/wizard/server/saved_objects/wizard_migration.test.ts
  src/plugins/wizard/server/saved_objects/wizard_migration.ts
Labels: drag & drop

#2162 [UX] Change timeline icon
  src/plugins/vis_type_timeline/public/timeline_vis_type.tsx
  src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx
Labels: ux / ui

#2192 [Visualizations] Adds visConfig.title and uiState to build pipeline function
  src/plugins/visualizations/public/legacy/build_pipeline.ts
Labels: backport 2.x

#2236 [MD] Wrap datasource errors for route handlers to understand
  src/core/server/http/router/router.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/lib/error.test.ts
  src/plugins/data_source/server/lib/error.ts
  src/plugins/data_source/server/plugin.ts
Labels: multiple datasource

#2227 [D&D] Persists index field on agg type change if possible
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
Labels: drag & drop, backport 2.x, v2.3.0

#2277 [BUG] fix healthcheck logic to expect object and return ids
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: backport 2.x, v2.3.0

#2247 [Backport 1.x] Custom healthcheck with filters (#2232)
  config/opensearch_dashboards.yml
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/core/server/opensearch/opensearch_service.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: backport 1.3, backport 1.2, backport 1.1, backport 1.0

#2282 [MD] Datasource management new API change integrations
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/credentials_combox_box/credentials_combo_box.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/index.ts
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/text_content/index.ts
  src/plugins/data_source_management/public/components/text_content/text_content.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/components/validation/index.ts
  src/plugins/data_source_management/public/types.ts
Labels: multiple datasource

#2300 [Backport 1.x] [BUG] fix healthcheck logic to expect object and return ids
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: backport 1.3, backport 1.2, backport 1.1, backport 1.0

#2295 Increment from 2.3 to 2.4
  package.json
Labels: versioning, v2.4.0

#2309 [D&D] Fixes time series for new chart types
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/application/utils/use/use_can_save.ts
  src/plugins/wizard/public/visualizations/vislib/area/to_expression.ts
  src/plugins/wizard/public/visualizations/vislib/common/get_pipeline_params.ts
  src/plugins/wizard/public/visualizations/vislib/common/index.ts
  src/plugins/wizard/public/visualizations/vislib/histogram/to_expression.ts
  src/plugins/wizard/public/visualizations/vislib/line/to_expression.ts
Labels: drag & drop, backport 2.x

#2322 Update caniuse to fix failed integration tests
  package.json
  yarn.lock
Labels: backport 1.x, backport 2.x, backport 2.0, backport 2.1, v2.4.0, backport 2.2, backport 2.3

#2318 Add v2.3.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.3.0.md
Labels: docs, backport 2.x, v2.3.0, backport 2.3

#2352 Use a forced CSP-compliant interpreter with Vega visualizations
  package.json
  src/plugins/vis_type_vega/public/lib/vega.js
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
  src/plugins/vis_type_vega/public/vega_view/vega_map_view.js
  src/plugins/vis_type_vega/public/vega_view/vega_view.js
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 1.2, backport 1.1, backport 1.0, backport 2.x, v2.4.0, backport 2.3

#2341 [MD] Datasource Management - Create data source - Unit tests
  src/plugins/data_source_management/public/components/breadcrumbs.test.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/loading_mask/__snapshots__/loading_mask.test.tsx.snap
  src/plugins/data_source_management/public/components/loading_mask/loading_mask.test.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.test.ts
  src/plugins/data_source_management/public/mocks.ts
Labels: multiple datasource

#2361 Bump moment-timezone from 0.5.34 to 0.5.37
  yarn.lock
Labels: cve, backport 1.x, backport 1.3, backport 1.2, backport 1.1, backport 1.0, backport 2.x, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#2364 [MD] Fix update data source & block update endpoint
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/types.ts
Labels: multiple datasource

#2350 [MD] datasource management-datasource table-UTs
  src/plugins/data_source_management/public/components/create_button/__snapshots__/create_button.test.tsx.snap
  src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
Labels: multiple datasource

#2375 reafctor based on PR 2334 comments to merge to main
  src/plugins/data_source_management/README.md
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: multiple datasource

#2376 removing invalid urls as CI fails on link checker for inavlid urls in git
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/mocks.ts
Labels: multiple datasource

#2344 Fixes management app breadcrumb error
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_index_pattern_prompt/empty_index_pattern_prompt.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
  src/plugins/management/public/components/landing/landing.tsx
Labels: backport 2.x

#2279 [Table Visualization] remove legacy table and add table visualization
  src/plugins/vis_type_table/README.md
  src/plugins/vis_type_table/opensearch_dashboards.json
  src/plugins/vis_type_table/public/__snapshots__/table_vis_fn.test.ts.snap
  src/plugins/vis_type_table/public/_table_vis.scss
  src/plugins/vis_type_table/public/agg_table/_agg_table.scss
  src/plugins/vis_type_table/public/agg_table/_index.scss
  src/plugins/vis_type_table/public/agg_table/agg_table.html
  src/plugins/vis_type_table/public/agg_table/agg_table.js
  src/plugins/vis_type_table/public/agg_table/agg_table.test.js
  src/plugins/vis_type_table/public/agg_table/agg_table_group.html
  src/plugins/vis_type_table/public/agg_table/agg_table_group.js
  src/plugins/vis_type_table/public/agg_table/agg_table_group.test.js
  src/plugins/vis_type_table/public/agg_table/tabified_data.js
  src/plugins/vis_type_table/public/get_inner_angular.ts
  src/plugins/vis_type_table/public/index.scss
  src/plugins/vis_type_table/public/index.ts
  src/plugins/vis_type_table/public/paginated_table/_index.scss
  src/plugins/vis_type_table/public/paginated_table/_table_cell_filter.scss
  src/plugins/vis_type_table/public/paginated_table/paginated_table.html
  src/plugins/vis_type_table/public/paginated_table/paginated_table.js
  src/plugins/vis_type_table/public/paginated_table/paginated_table.test.ts
  src/plugins/vis_type_table/public/paginated_table/rows.js
  src/plugins/vis_type_table/public/paginated_table/table_cell_filter.html
  src/plugins/vis_type_table/public/plugin.ts
  src/plugins/vis_type_table/public/services.ts
  src/plugins/vis_type_table/public/table_vis.html
  src/plugins/vis_type_table/public/table_vis_controller.js
  src/plugins/vis_type_table/public/table_vis_controller.test.ts
  src/plugins/vis_type_table/public/table_vis_fn.test.ts
  src/plugins/vis_type_table/public/table_vis_fn.ts
  src/plugins/vis_type_table/public/table_vis_legacy_module.ts
  src/plugins/vis_type_table/public/table_vis_renderer.tsx
  src/plugins/vis_type_table/public/table_vis_response_handler.ts
  src/plugins/vis_type_table/public/table_vis_type.ts
  src/plugins/vis_type_table/public/to_ast.ts
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/vis_controller.ts
  src/plugins/vis_type_table/server/index.ts
  src/plugins/visualizations/public/legacy/__snapshots__/build_pipeline.test.ts.snap
  src/plugins/visualizations/public/legacy/build_pipeline.test.ts
  src/plugins/visualizations/public/legacy/build_pipeline.ts
Labels: tableVis

#2166 Upgrade geckodriver to 3.0.2 to partially fix CVE-2022-33987
  yarn.lock
Labels: cve, backport 2.x

#2403 fix 2402 | remove extra typo from readme.
  README.md
Labels: bug, docs, backport 2.x

#2397 [Backport 2.x] Upgrade geckodriver to 3.0.2 to partially fix CVE-2022-33987 (#2166)
  yarn.lock
Labels: backport 2.3

#2390 [Table Visualization] add a plain datagrid component
  src/plugins/vis_type_table/opensearch_dashboards.json
  src/plugins/vis_type_table/public/components/table_vis_app.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/plugin.ts
  src/plugins/vis_type_table/public/table_vis_renderer.tsx
  yarn.lock
Labels: tableVis

#2408 Updating WS scans to ignore BWC artifacts in `cypress`
  whitesource.config
Labels: backport 2.x, backport 2.3

#2419 Adding @zengyan-amazon as a Dashboards co-maintainer
  CHANGELOG.md
  MAINTAINERS.md
Labels: docs

#2421 Version increment to 2.3.1
  package.json
Labels: v2.3.1

#2420 Version Increment to 1.3.6
  package.json
Labels: versioning, v1.3.6

#2423 Updating @tmarkley to Emeritus status
  CHANGELOG.md
  MAINTAINERS.md
Labels: docs

#2401 [Vis Builder] Misc Bar chart fixes
  CHANGELOG.md
  src/plugins/wizard/opensearch_dashboards.json
  src/plugins/wizard/public/application/components/data_tab/config_panel.scss
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/application/utils/use/use_index_pattern.tsx
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/plugin_services.ts
  src/plugins/wizard/public/saved_visualizations/transforms.test.ts
  src/plugins/wizard/public/saved_visualizations/transforms.ts
  src/plugins/wizard/public/visualizations/common/expression_helpers.ts
  src/plugins/wizard/public/visualizations/vislib/area/to_expression.ts
  src/plugins/wizard/public/visualizations/vislib/common/create_vis.ts
  src/plugins/wizard/public/visualizations/vislib/histogram/histogram_vis_type.ts
  src/plugins/wizard/public/visualizations/vislib/histogram/to_expression.ts
  src/plugins/wizard/public/visualizations/vislib/line/to_expression.ts
  test/functional/apps/wizard/_base.ts
Labels: vis builder, backport 2.x, backport 2.3

#2351 [Viz Builder] State validation before dispatching and loading
  CHANGELOG.md
  package.json
  src/plugins/wizard/public/application/utils/schema.json
  src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
  src/plugins/wizard/public/application/utils/wizard_state_validation.test.ts
  src/plugins/wizard/public/application/utils/wizard_state_validation.ts
  yarn.lock
Labels: backport 2.x, v2.4.0

#2204 Support legacy client for data source
  CHANGELOG.md
  src/core/server/http/router/router.ts
  src/plugins/data/server/index_patterns/fetcher/index_patterns_fetcher.ts
  src/plugins/data/server/index_patterns/fetcher/lib/field_capabilities/field_capabilities.ts
  src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
  src/plugins/data/server/index_patterns/fetcher/lib/resolve_time_pattern.ts
  src/plugins/data/server/index_patterns/routes.ts
  src/plugins/data_source/server/client/client_pool.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/index.ts
  src/plugins/data_source/server/data_source_service.test.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/legacy/client_config.test.ts
  src/plugins/data_source/server/legacy/client_config.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/legacy/index.ts
  src/plugins/data_source/server/lib/error.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
  src/plugins/index_pattern_management/server/routes/resolve_index.ts
Labels: multiple datasource

#2415 Bumps `percy-agent` to use non-beta version
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.3

#2425 [backport 1.x] Resolves ansi-regex to v5.0.1
  package.json
  yarn.lock
Labels: dependencies, cve, backport 1.3, v1.3.6

#2454 fix d3-color and potential security issue
  CHANGELOG.md
  package.json
  src/dev/jest/config.js
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 2.x, v2.4.0, v1.3.6, backport 2.3

#2398 Extends plugin-helpers to be used for automating version changes
  CHANGELOG.md
  packages/osd-plugin-helpers/README.md
  packages/osd-plugin-helpers/src/cli.ts
  packages/osd-plugin-helpers/src/contexts.ts
  packages/osd-plugin-helpers/src/tasks/clean.ts
  packages/osd-plugin-helpers/src/tasks/create_archive.ts
  packages/osd-plugin-helpers/src/tasks/index.ts
  packages/osd-plugin-helpers/src/tasks/optimize.ts
  packages/osd-plugin-helpers/src/tasks/update_versions.ts
  packages/osd-plugin-helpers/src/tasks/write_public_assets.ts
  packages/osd-plugin-helpers/src/tasks/write_server_files.ts
  packages/osd-plugin-helpers/src/tasks/yarn_install.ts
Labels: build, backport 1.x, backport 1.3, backport 2.x, v1.3.6, backport 2.3

#2469 [Backport 2.x][Plugin Helpers] Facilitate version changes (#2398)
  CHANGELOG.md
  packages/osd-plugin-helpers/README.md
  packages/osd-plugin-helpers/src/cli.ts
  packages/osd-plugin-helpers/src/contexts.ts
  packages/osd-plugin-helpers/src/tasks/clean.ts
  packages/osd-plugin-helpers/src/tasks/create_archive.ts
  packages/osd-plugin-helpers/src/tasks/index.ts
  packages/osd-plugin-helpers/src/tasks/optimize.ts
  packages/osd-plugin-helpers/src/tasks/update_versions.ts
  packages/osd-plugin-helpers/src/tasks/write_public_assets.ts
  packages/osd-plugin-helpers/src/tasks/write_server_files.ts
  packages/osd-plugin-helpers/src/tasks/yarn_install.ts
Labels: backport 2.3

#2468 [Backport 1.x] Add CHANGELOG.md and related workflows (#2414)
  .github/pull_request_template.md
  .github/workflows/changelog_verifier.yml
  CHANGELOG.md
Labels: backport 1.3
