Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-04, with the labels that each got.

#1414 [Branding] allow for SSL setup failures
  src/core/server/rendering/rendering_service.tsx
Labels: branding, backport 1.x, backport 1.3, v1.3.1

#1409 Fixes interfaced errors across Dashboards
  package.json
  packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
  packages/osd-optimizer/src/integration_tests/__snapshots__/basic_optimization.test.ts.snap
  packages/osd-optimizer/src/limits.ts
  packages/osd-ui-framework/package.json
  src/core/public/apm_system.test.ts
  src/core/public/application/scoped_history.ts
  src/core/server/opensearch/opensearch_config.test.mocks.ts
  src/core/server/rendering/rendering_service.test.ts
  src/plugins/dashboard/public/application/embeddable/viewport/dashboard_viewport.test.tsx
  src/plugins/vis_default_editor/public/components/controls/has_extended_bounds.tsx
  yarn.lock
Labels: v2.0.0, refactor

#1419 Reverts re2 back to 1.15.4 from 1.17.4 to fix build issues
  yarn.lock
Labels: v2.0.0

#1383 [Backport 1.x] Bump minimist from 1.2.5 to 1.2.6 (#1377)
  yarn.lock
Labels: cve, v1.4.0

#1389 [Backport 1.x] Bumps `json-schema` from 0.2.3 to 0.4.0 (#1385)
  package.json
  yarn.lock
Labels: cve, v1.4.0

#1426 [Admin] add current maintainers as of 04/2022
  MAINTAINERS.md
Labels: docs

#1427 Fixes search usage telemetry
  config/opensearch_dashboards.yml
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
  src/plugins/data/config.ts
  src/plugins/data/server/search/collectors/usage.test.ts
  src/plugins/data/server/search/collectors/usage.ts
  src/plugins/data/server/search/search_service.ts
Labels: v2.0.0

#1347 [Circuit-Breaker] Add memory circuit breaker configuration
  config/opensearch_dashboards.yml
  package.json
  packages/osd-opensearch/package.json
  src/core/server/opensearch/client/client_config.ts
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
  yarn.lock
Labels: v2.0.0

#1324 fix(Tooltip): Fixes tooltip when split series charts are used
  src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js
  src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.test.js
Labels: bug, v2.0.0

#1428 [2.x] support legacy config
  src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.test.ts
  src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts
Labels: v2.0.0

#1455 Revert "Bump moment from 2.29.1 to 2.29.2 (#1439)"
  package.json
  packages/osd-config/package.json
  packages/osd-dev-utils/package.json
  packages/osd-telemetry-tools/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: v2.0.0

#1434 [Build] Bumps version from 1.3.1 to 1.3.2
  package.json
Labels: build, versioning, v1.3.2

#1463 Cleans up changes from memory circuit breaker PR
  src/core/server/opensearch/client/client_config.ts
  src/core/server/opensearch/opensearch_config.ts
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
Labels: v2.0.0, refactor

#1453 update re2 for linux, darwin, and windows
  src/dev/build/tasks/patch_native_modules_task.ts
Labels: build, v2.0.0

#1447 [Tests] BWC test improvements
  bwctest.sh
  scripts/bwc/opensearch_dashboards_service.sh
  scripts/bwc/opensearch_service.sh
  scripts/bwc/utils.sh
  scripts/bwctest_osd.sh
Labels: ci, v2.0.0, test:bwc

#1454 update re2 build for arm under node 14
  src/dev/build/tasks/patch_native_modules_task.test.ts
  src/dev/build/tasks/patch_native_modules_task.ts
Labels: bug, v2.0.0

#1456 Bump moment from 2.29.1 to 2.29.2
  yarn.lock
Labels: dependencies, v2.0.0, cve

#1449 Resolves `async` to v3.2.3
  package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v2.0.0, cve

#1468 [Plugins] fix default path to plugins
  src/cli_plugin/install/settings.js
  src/cli_plugin/install/settings.test.js
Labels: v2.0.0

#1467 Deprecates non-inclusive config names
  packages/osd-config/src/deprecation/deprecation_factory.test.ts
  packages/osd-config/src/deprecation/deprecation_factory.ts
  packages/osd-config/src/deprecation/types.ts
  src/core/server/config/deprecation/core_deprecations.test.ts
  src/core/server/config/deprecation/core_deprecations.ts
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
Labels: :sanitize, rename, v2.0.0

#1469 [Tests][BWC][CI] handle distributions with qualifiers
  bwctest.sh
  scripts/bwctest_osd.sh
Labels: v2.0.0, test:bwc

#1451 Bumps `grunt` from v1.4.1 to v1.5.2
  package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: dependencies, v2.0.0, cve, backport 1.x, backport 1.3, v1.3.2

#1470 [Tests][BWC][CI] use ODFE 1.0.2
  bwctest.sh
Labels: ci, v2.0.0, test:bwc

#1474 [Tests][BWC][CI] update performance analzyer location
  scripts/bwc/opensearch_service.sh
Labels: ci, v2.0.0, test:bwc

#1478 Adds code coverage reporting
  .github/workflows/build_and_test_workflow.yml
  package.json
  src/dev/jest/config.js
Labels: test:unit, ci

#1472 [Bug] fix copy as curl
  src/plugins/console/public/application/components/console_menu.tsx
Labels: bug, v2.0.0, backport 2.x

#1487 Bumps Node.js from v14.18.2 to v14.19.1
  .node-version
  .nvmrc
  Dockerfile
  TESTING.md
  package.json
Labels: dependencies, v2.0.0, cve, backport 2.x, backport 2.0

#1498 Adds code coverage and GitHub Actions badges
  README.md
Labels: docs

#1442 Adds src/test_utils/ and src/core paths to the target clean patterns
  package.json
Labels: bug

#1496 fix(actions): Better type checks for icons
  examples/ui_actions_explorer/public/context_menu_examples/util.ts
  src/core/public/application/types.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/nav_links/to_nav_link.test.ts
  src/core/types/app_category.ts
  src/plugins/dashboard/public/application/actions/add_to_library_action.tsx
  src/plugins/dashboard/public/application/actions/clone_panel_action.tsx
  src/plugins/dashboard/public/application/actions/expand_panel_action.tsx
  src/plugins/dashboard/public/application/actions/library_notification_action.tsx
  src/plugins/dashboard/public/application/actions/replace_panel_action.tsx
  src/plugins/dashboard/public/application/actions/unlink_from_library_action.tsx
  src/plugins/embeddable/public/lib/actions/edit_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/customize_title/customize_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/inspect_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/remove_panel_action.ts
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/management/public/types.ts
  src/plugins/management/public/utils/management_item.ts
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
  src/plugins/ui_actions/public/actions/action.ts
  src/plugins/ui_actions/public/actions/action_internal.ts
  src/plugins/ui_actions/public/service/ui_actions_service.test.ts
  src/plugins/ui_actions/public/util/presentable.ts
  src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
Labels: backport pending

#1491 Fix: Re-rendering visualization when expression changes and improves typing
  examples/expressions_example/common/expression_functions/render/avatar_fn.ts
  examples/expressions_example/opensearch_dashboards.json
  examples/expressions_example/public/components/playground_section.tsx
  src/plugins/expressions/README.md
  src/plugins/expressions/common/expression_renderers/types.ts
  src/plugins/expressions/public/render.ts
  src/plugins/input_control_vis/public/input_control_fn.ts
  src/plugins/vis_type_table/public/table_vis_fn.ts
  src/plugins/vis_type_timeseries/public/metrics_fn.ts
  src/plugins/vis_type_vega/public/vega_fn.ts
  src/plugins/vis_type_vislib/public/pie_fn.ts
  src/plugins/vis_type_vislib/public/vis_type_vislib_vis_fn.ts
  src/plugins/visualizations/public/expressions/visualization_function.ts
  src/plugins/visualizations/public/expressions/visualization_renderer.tsx
  src/plugins/visualizations/public/index.ts
  src/plugins/visualizations/public/types.ts
Labels: visualizations

#1502 [Version] Increment to 3.0
  .github/workflows/build_and_test_workflow.yml
  dev-tools/get-version.sh
  package.json
  src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.test.ts
  src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
  src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts
Labels: v3.0.0

#1507 add release note for 2.0.0-rc1
  release-notes/opensearch-dashboards.release-notes-2.0.0-rc1.md
Labels: docs, v2.0.0, backport 2.x, backport 2.0

#1495 [Backport 1.x] Bumps chromedriver to v100 (#1410)
  .github/workflows/pr_check_workflow.yml
  yarn.lock
Labels: ci, backport

#1515 [CI] Create doc issue workflow
  .github/doc_issue_template.md
  .github/workflows/create_doc_issue.yml
  CONTRIBUTING.md
Labels: ci, v3.0.0

#1513 [Backport 1.3] Bump nanoid from 3.1.30 to 3.2.0
  yarn.lock
Labels: backport, cve, v1.3.2

#1514 [Backport 1.3] Bump minimist from 1.2.5 to 1.2.6
  yarn.lock
Labels: backport, cve, v1.3.2

#1518 [Backport 1.x] fix(actions): Better type checks for icons
  examples/ui_actions_explorer/public/context_menu_examples/util.ts
  src/core/public/application/types.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/nav_links/to_nav_link.test.ts
  src/core/types/app_category.ts
  src/plugins/dashboard/public/application/actions/add_to_library_action.tsx
  src/plugins/dashboard/public/application/actions/clone_panel_action.tsx
  src/plugins/dashboard/public/application/actions/expand_panel_action.tsx
  src/plugins/dashboard/public/application/actions/library_notification_action.tsx
  src/plugins/dashboard/public/application/actions/replace_panel_action.tsx
  src/plugins/dashboard/public/application/actions/unlink_from_library_action.tsx
  src/plugins/embeddable/public/lib/actions/edit_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/customize_title/customize_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/inspect_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/remove_panel_action.ts
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/management/public/types.ts
  src/plugins/management/public/utils/management_item.ts
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
  src/plugins/ui_actions/public/actions/action.ts
  src/plugins/ui_actions/public/actions/action_internal.ts
  src/plugins/ui_actions/public/service/ui_actions_service.test.ts
  src/plugins/ui_actions/public/util/presentable.ts
  src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
Labels: backport, v1.3.2

#1519 [Backport 1.3] fix(actions): Better type checks for icons
  examples/ui_actions_explorer/public/context_menu_examples/util.ts
  src/core/public/application/types.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/nav_links/to_nav_link.test.ts
  src/core/types/app_category.ts
  src/plugins/dashboard/public/application/actions/add_to_library_action.tsx
  src/plugins/dashboard/public/application/actions/clone_panel_action.tsx
  src/plugins/dashboard/public/application/actions/expand_panel_action.tsx
  src/plugins/dashboard/public/application/actions/library_notification_action.tsx
  src/plugins/dashboard/public/application/actions/replace_panel_action.tsx
  src/plugins/dashboard/public/application/actions/unlink_from_library_action.tsx
  src/plugins/embeddable/public/lib/actions/edit_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/customize_title/customize_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/inspect_panel_action.ts
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/remove_panel_action.ts
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/management/public/types.ts
  src/plugins/management/public/utils/management_item.ts
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
  src/plugins/ui_actions/public/actions/action.ts
  src/plugins/ui_actions/public/actions/action_internal.ts
  src/plugins/ui_actions/public/service/ui_actions_service.test.ts
  src/plugins/ui_actions/public/util/presentable.ts
  src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
Labels: backport, v1.3.2

#1528 [Backport 1.3] Bumps chromedriver to v100
  .github/workflows/pr_check_workflow.yml
Labels: ci, backport, v1.3.2

#1523 [Backport 1.3] Bump ejs from 3.1.6 to 3.1.7
  packages/osd-plugin-generator/package.json
  yarn.lock
Labels: backport, cve, v1.3.2

#1522 [Backport 1.x] Bump ejs from 3.1.6 to 3.1.7
  packages/osd-plugin-generator/package.json
  yarn.lock
Labels: backport, cve, v1.3.2

#1511 [Backport 1.3] Bumps `json-schema` from 0.2.3 to 0.4.0
  package.json
  yarn.lock
Labels: backport, cve, v1.3.2

#1516 [Backport 1.3] Bumps `grunt` from v1.4.1 to v1.5.2
  package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: backport, cve, v1.3.2

#1517 [Backport 1.3] Bump lodash-es from 4.17.15 to 4.17.21
  yarn.lock
Labels: backport, cve, v1.3.2

#1529 [Backport 1.x] Bumps `moment` from 2.29.1 to 2.29.2
  yarn.lock
Labels: backport, cve, v1.3.2

#1530 [Backport 1.3] Bumps `moment` from 2.29.1 to 2.29.2
  yarn.lock
Labels: backport, cve, v1.3.2
