Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-06, with the labels that each got.

#1649 [BUG] Remove duplicate var in the opensearch-dashboards-docker
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
Labels: bug, backport 1.x, backport 1.3, backport 2.x, backport 2.0, v1.3.3

#1653 [Backport 1.3] Removes irrelevant upsell in the timeout message
  .lycheeexclude
  src/plugins/data/public/index.ts
  src/plugins/data/public/public.api.md
  src/plugins/data/public/search/errors/timeout_error.test.tsx
  src/plugins/data/public/search/errors/timeout_error.tsx
  src/plugins/data/public/search/search_interceptor.ts
Labels: backport, v1.3.3

#1663 fix(Workflow): Fixes needs-documentation label workflow
  .github/workflows/create_doc_issue.yml
Labels: needs-documentation

#1650 [Bug] Fix metric vizualization cut off text
  src/plugins/vis_type_metric/public/components/metric_vis.scss
Labels: bug, backport 1.x, backport 1.3, backport 2.x, backport 2.0, v1.3.3

#1485 Changes config name in yml file to new non-deprecated name
  config/opensearch_dashboards.yml
Labels: v2.1.0, backport 2.x, needs-documentation, deprecation

#1189 Allow node patch versions to be higher on runtime
  src/setup_node_env/node_version_validator.js
  src/setup_node_env/node_version_validator.test.js
Labels: v2.1.0, backport 2.x, needs-documentation

#1682 Adds Josh Romero as co-maintainer
  MAINTAINERS.md
Labels: backport 2.x

#1693 Adds v1.3.3 release notes
  release-notes/opensearch-dashboards.release-notes-1.3.3.md
Labels: docs, backport 1.x, backport 1.3, v1.3.3

#1550 Fix wms maps can't load when can't request default map service
  .lycheeexclude
  src/plugins/maps_legacy/public/common/opensearch_maps_client.js
  src/plugins/maps_legacy/public/common/opensearch_maps_client.test.js
  src/plugins/maps_legacy/public/map/service_settings.js
  src/plugins/maps_legacy/public/map/service_settings.test.js
  src/plugins/region_map/public/region_map_visualization.js
Labels: bug, maps, v2.1.0, backport 2.x, needs-documentation

#1613 Bump version to 2.0.1
  package.json
Labels: versioning, v2.0.1

#1697 Fixes formatting and typos in documentation
  TYPESCRIPT.md
  packages/osd-eslint-import-resolver-opensearch-dashboards/lib/get_project_root.js
  src/core/server/saved_objects/migrations/README.md
Labels: docs, backport 1.x, backport 1.3, backport 2.x, backport 2.0, v2.0.1, v1.3.4

#1714 [Release 1.3.3] Version increment to 1.3.4
  package.json
Labels: versioning, v1.3.4

#1734 [D&D] Refactor to use AggService and introduce metric visualization
  src/plugins/vis_default_editor/public/components/sidebar/state/reducers.ts
  src/plugins/vis_type_metric/public/components/metric_vis_options.tsx
  src/plugins/vis_type_metric/public/index.ts
  src/plugins/vis_type_metric/public/metric_vis_fn.ts
  src/plugins/visualizations/public/legacy/build_pipeline.ts
  src/plugins/wizard/opensearch_dashboards.json
  src/plugins/wizard/public/application/components/side_nav.scss
  src/plugins/wizard/public/application/components/side_nav.tsx
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/config_panel.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/field_search.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/dropbox.scss
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/dropbox.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/title.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/use/use_dropbox.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/items/use/use_form_field.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/contributions/containers/data_tab/utils/schema_to_dropbox.tsx
  src/plugins/wizard/public/application/utils/state_management/config_slice.ts
  src/plugins/wizard/public/application/utils/state_management/datasource_slice.ts
  src/plugins/wizard/public/application/utils/state_management/hooks.ts
  src/plugins/wizard/public/application/utils/state_management/preload.ts
  src/plugins/wizard/public/application/utils/state_management/store.ts
  src/plugins/wizard/public/application/utils/state_management/style_slice.ts
  src/plugins/wizard/public/application/utils/state_management/visualization_slice.ts
  src/plugins/wizard/public/application/utils/use/index.ts
  src/plugins/wizard/public/application/utils/use/use_index_pattern.tsx
  src/plugins/wizard/public/application/utils/use/use_visualization_type.ts
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/plugin_services.ts
  src/plugins/wizard/public/services/type_service/types.ts
  src/plugins/wizard/public/services/type_service/visualization_type.test.tsx
  src/plugins/wizard/public/services/type_service/visualization_type.tsx
  src/plugins/wizard/public/types.ts
  src/plugins/wizard/public/visualizations/index.ts
  src/plugins/wizard/public/visualizations/metric/components/metric_viz_options.tsx
  src/plugins/wizard/public/visualizations/metric/index.ts
  src/plugins/wizard/public/visualizations/metric/metric_viz_type.ts
  src/plugins/wizard/public/visualizations/metric/to_expression.ts
Labels: drag & drop

#1744 Adds v2.0.1 release notes
  release-notes/opensearch-dashboards.release-notes-2.0.1.md
Labels: docs, backport 2.x, backport 2.0, v2.0.1

#1753 [CVE] Resolve `jpeg-js` to 0.4.4
  yarn.lock
Labels: high severity, cve, v2.1.0, backport 2.x

#1758 Bump the version to 2.0.2
  package.json
Labels: versioning

#1719 [Non-Inclusive Language] Replace isDevClusterMaster with isDevClusterManager
  packages/osd-config/src/__mocks__/env.ts
  packages/osd-config/src/__snapshots__/env.test.ts.snap
  packages/osd-config/src/env.test.ts
  packages/osd-config/src/env.ts
  src/core/server/bootstrap.ts
  src/core/server/http/http_service.test.ts
  src/core/server/http/http_service.ts
  src/core/server/legacy/legacy_service.test.ts
  src/core/server/legacy/legacy_service.ts
  src/core/server/plugins/plugins_service.ts
  src/core/test_helpers/osd_server.ts
  src/legacy/server/logging/rotate/index.ts
  src/legacy/server/logging/rotate/log_rotator.ts
Labels: v2.1.0, backport 2.x, non-inclusive language

#1752 [Deprecation] Deprecate setupMaster in favor of setupClusterManager
  src/cli/cluster/cluster.mock.ts
  src/cli/cluster/cluster_manager.ts
  src/cli/cluster/worker.ts
Labels: v2.1.0, backport 2.x

#1772 [CI][BWC] Date range for tests incorrect params
  cypress/integration/with-security/check_loaded_data.js
  cypress/integration/without-security/check_loaded_data.js
Labels: ci, test:bwc, v2.1.0, backport 2.x, backport 2.0

#1761 [Deprecation] Deprecate master nodes and replace with cluster_manager nodes
  src/plugins/console/public/lib/osd/osd.js
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.state.json
Labels: v2.1.0, backport 2.x, non-inclusive language

#1770 [CVE] Bump `tsd` to `0.21.0`
  packages/opensearch-safer-lodash-set/package.json
  packages/osd-apm-config-loader/package.json
  packages/osd-config-schema/package.json
  packages/osd-config/package.json
  packages/osd-std/package.json
  packages/osd-utility-types/package.json
  yarn.lock
Labels: medium severity, cve, v2.1.0, backport 2.x

#1780 [Non-Inclusive Lanuage] Replace references to master branch with main
  DEVELOPER_GUIDE.md
  examples/bfetch_explorer/public/plugin.tsx
  examples/developer_examples/README.md
  examples/embeddable_explorer/public/plugin.tsx
  examples/expressions_example/README.md
  examples/routing_example/public/app.tsx
  examples/search_examples/README.md
  examples/state_containers_examples/public/plugin.ts
  examples/ui_actions_explorer/public/plugin.tsx
  examples/url_generators_explorer/public/plugin.tsx
  packages/opensearch-eslint-config-opensearch-dashboards/typescript.js
  packages/osd-config/src/config_service.test.ts
  packages/osd-config/src/env.test.ts
  packages/osd-eslint-import-resolver-opensearch-dashboards/README.md
  packages/osd-eslint-import-resolver-opensearch-dashboards/import_resolver_opensearch_dashboards.js
  packages/osd-plugin-generator/README.md
  packages/osd-plugin-generator/template/README.md.ejs
  packages/osd-spec-to-console/README.md
  packages/osd-test/src/failed_tests_reporter/run_failed_tests_reporter_cli.ts
  release-notes/opensearch-dashboards.release-notes-1.1.0.md
  src/core/server/core_app/assets/legacy_dark_theme.css
  src/core/server/core_app/assets/legacy_light_theme.css
  src/core/server/http/http_config.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugins_discovery.test.ts
  src/dev/ci_setup/checkout_sibling_opensearch.sh
  src/dev/ci_setup/get_percy_env.js
  src/legacy/server/config/schema.js
  src/plugins/embeddable/README.md
  src/plugins/opensearch_dashboards_overview/README.md
  src/plugins/opensearch_dashboards_utils/common/state_containers/README.md
  src/plugins/opensearch_dashboards_utils/common/state_containers/create_state_container_react_helpers.ts
  src/plugins/opensearch_dashboards_utils/common/state_containers/index.ts
  src/plugins/opensearch_dashboards_utils/public/state_sync/README.md
  src/plugins/opensearch_dashboards_utils/public/state_sync/index.ts
  src/plugins/opensearch_dashboards_utils/public/state_sync/state_sync.ts
  src/plugins/opensearch_dashboards_utils/public/state_sync/state_sync_state_storage/create_osd_url_state_storage.ts
  src/plugins/opensearch_dashboards_utils/public/state_sync/state_sync_state_storage/create_session_storage_state_storage.ts
  tasks/docker_docs/Dockerfile
Labels: v2.1.0, backport 2.x, non-inclusive language

#1789 [CI] Update labels for doc issue creation workflow
  .github/workflows/create_doc_issue.yml
Labels: ci

#1778 [Non-Inclusive Language] Replace master in comments
  src/core/server/http/http_service.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
  src/plugins/telemetry/server/telemetry_collection/get_local_license.ts
  src/plugins/vis_type_timeseries/server/lib/vis_data/request_processors/series/date_histogram.js
Labels: v2.1.0, backport 2.x, deprecation

#1788 [Deprecation] Deprecate master_timeout in favor of cluster_manager_timeout
  packages/osd-spec-to-console/test/fixtures/cluster_health_autocomplete.json
  packages/osd-spec-to-console/test/fixtures/cluster_health_spec.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.allocation.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.indices.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.nodeattrs.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.nodes.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.pending_tasks.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.plugins.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.repositories.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.shards.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.snapshots.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.templates.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.thread_pool.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.delete_component_template.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.get_settings.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.health.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.pending_tasks.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.put_settings.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.reroute.json
  src/plugins/console/server/lib/spec_definitions/json/generated/cluster.state.json
  src/plugins/console/server/lib/spec_definitions/json/generated/delete_script.json
  src/plugins/console/server/lib/spec_definitions/json/generated/get_script.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.clone.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.close.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.create.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.delete_alias.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.delete_template.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.get.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.get_mapping.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.get_settings.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.get_template.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.put_alias.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.put_mapping.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.put_settings.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.put_template.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.rollover.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.shrink.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.split.json
  src/plugins/console/server/lib/spec_definitions/json/generated/indices.update_aliases.json
  src/plugins/console/server/lib/spec_definitions/json/generated/ingest.delete_pipeline.json
  src/plugins/console/server/lib/spec_definitions/json/generated/ingest.get_pipeline.json
  src/plugins/console/server/lib/spec_definitions/json/generated/ingest.put_pipeline.json
  src/plugins/console/server/lib/spec_definitions/json/generated/put_script.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.cleanup_repository.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.create.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.create_repository.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.delete.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.delete_repository.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.get.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.get_repository.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.restore.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.status.json
  src/plugins/console/server/lib/spec_definitions/json/generated/snapshot.verify_repository.json
  src/plugins/console/server/lib/spec_definitions/json/overrides/cluster.health.json
Labels: v2.1.0, backport 2.x, deprecation

#1586 [UX] Consolidate menu bars
  config/opensearch_dashboards.yml
  src/core/public/_variables.scss
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_controls/nav_controls_service.test.ts
  src/core/public/chrome/nav_controls/nav_controls_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_logo.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/home_icon.test.tsx.snap
  src/core/public/chrome/ui/header/_index.scss
  src/core/public/chrome/ui/header/branding/__snapshots__/opensearch_dashboards_custom_logo.test.tsx.snap
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.test.tsx
  src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_logo.test.tsx
  src/core/public/chrome/ui/header/home_icon.test.tsx
  src/core/public/chrome/ui/header/home_icon.tsx
  src/core/public/chrome/ui/header/home_loader.scss
  src/core/public/chrome/ui/header/home_loader.tsx
  src/core/public/core_system.ts
  src/core/public/rendering/_base.scss
  src/core/server/core_app/assets/default_branding/opensearch_logo_dark_mode.svg
  src/core/server/core_app/assets/default_branding/opensearch_logo_default_mode.svg
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/types/custom_branding.ts
  src/legacy/server/config/schema.js
  src/plugins/home/public/application/components/_home.scss
  src/plugins/opensearch_dashboards_overview/public/components/_overview.scss
  test/functional/apps/home/_add_data.js
  test/functional/apps/home/_add_data.ts
  test/functional/apps/home/_home.ts
  test/functional/apps/home/index.ts
  test/functional/apps/visualize/_custom_branding.js
  test/functional/apps/visualize/_custom_branding.ts
  test/functional/services/global_nav.ts
Labels: branding, v2.1.0, backport 2.x, needs-documentation

#1802 [UX] Change name of expanded header config
  config/opensearch_dashboards.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/home_icon.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/home_icon.test.tsx
  src/core/public/chrome/ui/header/home_icon.tsx
  src/core/public/core_system.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/types/custom_branding.ts
  src/legacy/server/config/schema.js
Labels: branding, v2.1.0, backport 2.x

#1800 [Deprecation] Deprecate cat master API in favor of cat cluster_manager
  src/core/server/opensearch/legacy/api_types.ts
  src/core/server/server.api.md
  src/plugins/console/server/lib/spec_definitions/json/generated/cat.cluster_manager.json
Labels: v2.1.0, backport 2.x, deprecation, backport 2.1

#1823 [Tests] update tests to reflect max zoom level for maps
  test/functional/apps/visualize/_tile_map.js
Labels: test:functional, backport 1.x, backport 1.3, v2.1.0, backport 2.x, backport 2.1

#1799 [Deprecation] Deprecate the apiVersion: master value and replace with main
  src/core/server/core_usage_data/core_usage_data_service.mock.ts
  src/core/server/opensearch/legacy/cluster_client.test.ts
  src/core/server/opensearch/legacy/opensearch_client_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
Labels: v2.1.0, backport 2.x, deprecation, backport 2.1

#1822 [Tests] update expected value for percentile ranks
  test/functional/apps/visualize/_metric_chart.js
Labels: test:functional, v3.0.0
