Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-12, with the labels that each got.

#2953 [Backport 1.3 - Manual] [Backport 1.x][CVE] Bump loader-utils to 2.0.3 to fix CVE-2022-37601 (#2707)
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: v1.3.7

#2965 Fix incorrect validation of time values in JUnit Reporter
  CHANGELOG.md
  src/dev/jest/junit_reporter.js
Labels: bug, test:integration, backport 1.x, backport 1.3, backport 2.x, v1.3.7

#2972 [Backport 1.3 - Manual] [Manual] [Backport 1.x] Bump minimatch to 3.0.5 and [IBM X-Force ID: 220063] unset-value to 2.0.1 (#2640) (#2946)
  CHANGELOG.md
  package.json
  yarn.lock
Labels: v1.3.7

#2963 [Windows] Make `yarn pkg-version` work across platforms
  dev-tools/get-version.sh
  package.json
Labels: enhancement, ci, backport 1.x, backport 1.3, backport 2.x, v1.3.7, Skip-Changelog

#2966 Add Windows CI to the GitHub workflow
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x

#2987 [Backport 1.x][Windows] Make `yarn pkg-version` work across platforms (#2963)
  package.json
Labels: backport 1.3, autocut

#2989 [Backport 1.x] Adds @osd/cross-platform (#2681 & #2703)
  CHANGELOG.md
  package.json
  packages/osd-config-schema/package.json
  packages/osd-config-schema/src/errors/schema_error.test.ts
  packages/osd-cross-platform/README.md
  packages/osd-cross-platform/package.json
  packages/osd-cross-platform/src/__snapshots__/path.test.ts.snap
  packages/osd-cross-platform/src/index.ts
  packages/osd-cross-platform/src/path.test.ts
  packages/osd-cross-platform/src/path.ts
  packages/osd-cross-platform/src/process.ts
  packages/osd-cross-platform/src/repo_root.ts
  packages/osd-cross-platform/tsconfig.json
  packages/osd-dev-utils/src/serializers/absolute_path_serializer.ts
  packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.js
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/node/cache.ts
  packages/osd-optimizer/src/optimizer/cache_keys.ts
  packages/osd-optimizer/src/optimizer/get_changes.test.ts
  packages/osd-plugin-generator/package.json
  packages/osd-plugin-generator/src/cli.ts
  packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts
  packages/osd-plugin-helpers/package.json
  packages/osd-plugin-helpers/src/cli.ts
  packages/osd-plugin-helpers/src/integration_tests/build.test.ts
  packages/osd-plugin-helpers/src/tasks/create_archive.ts
  packages/osd-pm/package.json
  packages/osd-pm/src/utils/projects.test.ts
  packages/osd-pm/src/utils/projects_tree.ts
  packages/osd-utils/package.json
  packages/osd-utils/src/index.ts
  packages/osd-utils/src/package_json/index.ts
  packages/osd-utils/src/path/index.ts
  src/cli_plugin/install/download.test.js
  src/cli_plugin/install/opensearch_dashboards.test.js
  src/cli_plugin/install/pack.test.js
  src/cli_plugin/list/list.test.js
  src/cli_plugin/remove/remove.test.js
  src/core/server/plugins/discovery/plugins_discovery.test.ts
  src/core/server/plugins/plugins_service.test.ts
  src/dev/build/lib/config.test.ts
  src/dev/build/lib/integration_tests/fs.test.ts
  src/dev/build/lib/integration_tests/scan_copy.test.ts
  src/dev/build/lib/scan_delete.test.ts
  src/dev/file.ts
  src/dev/i18n/integrate_locale_files.test.ts
  src/dev/i18n/utils/utils.js
  src/dev/jest/config.js
  src/dev/jest/integration_tests/junit_reporter.test.js
Labels: backport 1.3, v1.3.7

#2994 Make tests covering plugin installation on cluster snapshots work across platforms
  CHANGELOG.md
  packages/osd-opensearch/src/integration_tests/cluster.test.js
Labels: test:integration, backport 2.x, v2.5.0

#2995 [CVE] Bump loader-utils to 2.0.4 to fix CVE-2022-37599 and CVE-2022-37603
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: security vulnerability, cve, v1.3.7

#3006 Add @manasvinibs as maintainer
  MAINTAINERS.md
Labels: backport 2.x, Skip-Changelog

#3014 [Backport 2.x] Add @manasvinibs as maintainer (#3006) along with resolving conflict with main branch
  MAINTAINERS.md
Labels: Skip-Changelog

#2896 [Vis Builder] global data persistence for vis builder
  CHANGELOG.md
  src/plugins/vis_builder/public/application/app.tsx
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts
  src/plugins/vis_builder/public/plugin.test.ts
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/plugin_services.ts
  src/plugins/vis_builder/public/types.ts
Labels: enhancement, vis builder, backport 2.x, v2.5.0

#2990 Automates chromedriver version selection for tests
  .github/workflows/build_and_test_workflow.yml
  .gitignore
  CHANGELOG.md
  scripts/upgrade_chromedriver.js
Labels: ci, backport 1.x, backport 1.3, backport 2.x

#3020 Trim trailing slashes before checking no-restricted-path rule
  CHANGELOG.md
  packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.js
  packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.test.js
Labels: bug, test:unit, backport 1.x, backport 1.3, backport 2.x, backport 2.4

#3001 [Doc] Add readme for global query persistence
  CHANGELOG.md
  src/plugins/opensearch_dashboards_utils/README.md
  src/plugins/opensearch_dashboards_utils/docs/global_data_persistence.md
Labels: docs

#2973 [MD] Feature test connection
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/client/client_pool.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/index.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/edit_data_source/__snapshots__/edit_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/__snapshots__/edit_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: ux / ui, backport 2.x, multiple datasource, v2.5.0

#3066 [Chore] Add release notes for 1.3.7
  release-notes/opensearch-dashboards.release-notes-1.3.7.md
Labels: backport 1.x, backport 1.3, Skip-Changelog

#3070 [Chore] Add 2.4.1 release notes
  release-notes/opensearch-dashboards.release-notes-2.4.1.md
Labels: backport 2.x, Skip-Changelog

#2918 [Table Visualization][Bug] Fix Url content display in table
  CHANGELOG.md
  package.json
  src/plugins/vis_type_table_new/public/components/table_vis_component.tsx
  yarn.lock
Labels: bug, visualizations, backport 2.x, v2.5.0, tableVis

#3036 Bumps simple-git from 3.4.0 to 3.15.0
  CHANGELOG.md
  package.json
  packages/osd-opensearch/package.json
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 2.x

#3085 Fix boktorbb alias.
  MAINTAINERS.md
Labels: Skip-Changelog

#3073 [Infrastructure] Add `untriaged` label to issues workflow
  .github/workflows/add_untriaged_label.yml
Labels: Skip-Changelog

#2813 Point in time management plugin and empty state
  CHANGELOG.md
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
  src/plugins/point_in_time_management/opensearch_dashboards.json
  src/plugins/point_in_time_management/public/components/empty_state/__snapshots__/empty_state.test.tsx.snap
  src/plugins/point_in_time_management/public/components/empty_state/empty_state.test.tsx
  src/plugins/point_in_time_management/public/components/empty_state/empty_state.tsx
  src/plugins/point_in_time_management/public/components/empty_state/index.ts
  src/plugins/point_in_time_management/public/components/index.ts
  src/plugins/point_in_time_management/public/index.ts
  src/plugins/point_in_time_management/public/management_app/index.ts
  src/plugins/point_in_time_management/public/management_app/mount_management_section.tsx
  src/plugins/point_in_time_management/public/plugin.ts
  src/plugins/point_in_time_management/public/types.ts
  src/plugins/point_in_time_management/server/index.ts
  src/plugins/point_in_time_management/server/plugin.ts
  src/plugins/point_in_time_management/server/routes/index.ts
  src/plugins/point_in_time_management/server/types.ts
Labels: v2.5.0

#3080 Update console to use core.http instead of jQuery.ajax
  CHANGELOG.md
  src/plugins/console/public/application/contexts/services_context.tsx
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.ts
  src/plugins/console/public/application/index.tsx
  src/plugins/console/public/lib/opensearch/opensearch.ts
  test/functional/apps/console/_console.ts
Labels: refactor, backport 2.x, backport 2.0

#3119 [backport-2.0] Update console to use core.http instead of jQuery.ajax (#3080)
  src/plugins/console/public/application/contexts/services_context.tsx
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.ts
  src/plugins/console/public/application/index.tsx
  src/plugins/console/public/lib/opensearch/opensearch.ts
  test/functional/apps/console/_console.ts
Labels: backport

#3107 Add a new `vis_augmenter` plugin
  src/plugins/vis_augmenter/README.md
  src/plugins/vis_augmenter/opensearch_dashboards.json
  src/plugins/vis_augmenter/public/index.ts
  src/plugins/vis_augmenter/public/plugin.ts
  src/plugins/vis_augmenter/server/index.ts
  src/plugins/vis_augmenter/server/plugin.ts
Labels: Skip-Changelog

#3123 [Maintenance] Exempt feature branches from changelog verification
  .github/workflows/changelog_verifier.yml
Labels: Skip-Changelog

#3126 Gets rid of `github-checks-reporter`
  CHANGELOG.md
  package.json
  src/dev/ci_setup/setup_env.sh
  tasks/config/run.js
  yarn.lock
Labels: backport 1.x, backport 2.x

#3051 Updates NOTICE file, adds validation to GitHub CI
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
  NOTICE.txt
  package.json
  src/dev/build/tasks/notice_file_task.ts
  src/dev/notice/cli.js
  src/dev/notice/generate_notice_from_source.ts
Labels: backport 1.x, backport 1.3, backport 2.x

#3081 [Doc] Add current plugin persistence implementation readme
  CHANGELOG.md
  docs/plugins/data_persistence.md
  docs/plugins/img/URL_example.png
  docs/plugins/img/app_filter.png
  docs/plugins/img/app_persistence.png
  docs/plugins/img/app_query.png
  docs/plugins/img/global_filter.png
  docs/plugins/img/global_persistence.png
  docs/plugins/img/initialization.png
  docs/plugins/img/navigate.png
  docs/plugins/img/refresh.png
  docs/plugins/img/refresh_interval.png
  docs/plugins/img/storage_instance.png
  docs/plugins/img/time_range.png
  docs/plugins/img/visualization.png
Labels: docs

#3031 [CVE] Update package info and changelog for loader-utils bump to 2.0.4 fixing CVE-2022-37599 and CVE-2022-37603
  CHANGELOG.md
  package.json
Labels: cve, v3.0.0

#3043 Fixes misleading embeddable plugin error message
  CHANGELOG.md
  src/plugins/embeddable/public/lib/errors.ts
Labels: backport 1.x, backport 1.3, backport 2.x, v2.5.0, v1.3.8

#3088 [Vis Builder] Add redux store persistence
  CHANGELOG.md
  src/plugins/data/public/mocks.ts
  src/plugins/vis_builder/public/application/utils/mocks.ts
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.ts
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
Labels: vis builder, v2.5.0

#3045 Adds config override to fix obsolete theme:version config value of v8 (beta) rendering issue
  CHANGELOG.md
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_config.ts
Labels: backport 2.x, v2.5.0

#2967 Adds retrying flaky jest tests
  CHANGELOG.md
  package.json
  src/dev/jest/config.js
  yarn.lock
Labels: enhancement, test:unit, test:functional, backport 1.x, backport 1.3, backport 2.x, v2.5.0, v1.3.8

#3108 Add interfaces for layering data on Visualizations
  src/plugins/vis_augmenter/common/index.ts
  src/plugins/vis_augmenter/common/types.test.ts
  src/plugins/vis_augmenter/common/types.ts
  src/plugins/vis_augmenter/opensearch_dashboards.json
  src/plugins/vis_augmenter/public/expressions/index.ts
  src/plugins/vis_augmenter/public/expressions/vis_layers.ts
  src/plugins/vis_augmenter/public/plugin.ts
Labels: v2.5.0, Skip-Changelog
