Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2022-10, with the labels that each got.

#2431 [MD] Fix view single document issue by updating low-level search call param
  CHANGELOG.md
  src/plugins/discover/public/application/components/doc/use_opensearch_doc_search.ts
Labels: backport 2.x, multiple datasource, v2.4.0

#2486 [BUG] Plugin helpers fix related to fs promises module
  CHANGELOG.md
  packages/osd-plugin-helpers/src/tasks/update_versions.ts
Labels: backport 1.3, v1.3.6

#2428 Add sample config of multi data source to yml template.
  CHANGELOG.md
  config/opensearch_dashboards.yml
Labels: backport 2.x, multiple datasource, v2.4.0

#2448 Add dataSource & dataSourceManagement Readme
  CHANGELOG.md
  src/plugins/data_source/README.md
  src/plugins/data_source_management/README.md
Labels: backport 2.x, multiple datasource, v2.4.0

#2395 [Chore] Visualize link fix
  src/plugins/visualize/public/application/utils/get_table_columns.tsx
Labels: ux / ui, a11y

#2461 [Table Visualization] restore pagination to table vis
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/utils/index.ts
  src/plugins/vis_type_table/public/utils/use_pagination.ts
Labels: tableVis

#2384 [VizBuilder] Create a new wizard directly on a dashboard
  CHANGELOG.md
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/utils/get_top_nav_config.test.tsx
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/application/utils/mocks.ts
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/types.ts
Labels: vis builder

#2464 [Table Visualization] make table vis column resizable
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
  src/plugins/vis_type_table/public/types.ts
Labels: tableVis

#2503 [CI] Run functional test repo as workflow
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: test:functional, backport 2.x

#2514 [1.x] bump chromedriver to 106 to fix function test fail issue
  .github/workflows/pr_check_workflow.yml
  CHANGELOG.md
Labels: test:functional, backport 1.3, backport 1.2, backport 1.1, backport 1.0, v1.3.6

#2511 [backport 1.x][CVE-2022-0144] bump shelljs from 0.8.4 to 0.8.5
  CHANGELOG.md
  package.json
  release-notes/opensearch-dashboards.release-notes-1.3.6.md
  yarn.lock
Labels: cve, backport 1.3, v1.3.6

#2505 [MD] Address UX comments for index pattern pages
  CHANGELOG.md
  src/plugins/index_pattern_management/opensearch_dashboards.json
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.scss
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
  src/plugins/index_pattern_management/public/components/utils.ts
  src/plugins/index_pattern_management/public/types.ts
Labels: backport 2.x, multiple datasource

#2521 [MD] UX updates on data source page & validation changes
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_button/__snapshots__/create_button.test.tsx.snap
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/text_content/text_content.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.test.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/types.ts
  src/plugins/management/public/components/management_sidebar_nav/management_sidebar_nav.scss
  src/plugins/management/public/components/management_sidebar_nav/management_sidebar_nav.tsx
  src/plugins/management/public/types.ts
  src/plugins/management/public/utils/management_item.ts
Labels: ux / ui, backport 2.x, multiple datasource, v2.4.0

#2506 [MD] Display error toast for create index pattern with data source
  CHANGELOG.md
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.test.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts
Labels: backport 2.x, multiple datasource

#2527 [MD]Update copy on index patten config DS step
  CHANGELOG.md
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.scss
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
Labels: backport 2.x, multiple datasource

#2532 [MD] new UX changes for password fields and update password modal in data source management
  CHANGELOG.md
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
  src/plugins/data_source_management/public/components/text_content/text_content.ts
Labels: ux / ui, backport 2.x, multiple datasource, v2.4.0

#2508 Edit wizard directly on dashboard
  CHANGELOG.md
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
Labels: vis builder, v2.4.0

#2492 Updates functional test readme
  CHANGELOG.md
  TESTING.md
Labels: docs, backport 2.x

#2542 [MD]Add column service to index pattern & Register data source column
  CHANGELOG.md
  src/plugins/data_source/public/index.ts
  src/plugins/data_source/public/plugin.ts
  src/plugins/data_source/public/types.ts
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/components/__snapshots__/utils.test.ts.snap
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
  src/plugins/index_pattern_management/public/components/utils.ts
  src/plugins/index_pattern_management/public/index.ts
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/index_pattern_management/public/service/column_service/column_service.ts
  src/plugins/index_pattern_management/public/service/column_service/index.ts
  src/plugins/index_pattern_management/public/service/index_pattern_management_service.ts
  src/plugins/index_pattern_management/public/types.ts
Labels: backport 2.x, multiple datasource

#2523 [MD] Add experimental callout for index pattern section
  CHANGELOG.md
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/__snapshots__/experimental_callout.test.tsx.snap
  src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.test.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/index.ts
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Labels: ux / ui, backport 2.x, multiple datasource, v2.4.0

#2510 [MD] Add data source signing support
  CHANGELOG.md
  src/plugins/data_source/README.md
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/cryptography/cryptography_client.test.ts
  src/plugins/data_source/server/cryptography/cryptography_client.ts
  src/plugins/data_source/server/cryptography/index.ts
  src/plugins/data_source/server/cryptography_service.mocks.ts
  src/plugins/data_source/server/cryptography_service.test.ts
  src/plugins/data_source/server/cryptography_service.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/types.ts
Labels: backport 2.x, multiple datasource, v2.4.0

#2501 [MD] UX refactor for datasource create page
  .lycheeexclude
  CHANGELOG.md
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/text_content/text_content.ts
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/__snapshots__/experimental_callout.test.tsx.snap
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.test.tsx
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/index.ts
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
Labels: ux / ui, backport 2.x, multiple datasource, v2.4.0

#2557 [MD]Add data source config to opensearch-dashboards-docker
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
Labels: backport 2.x, multiple datasource

#2502 [Table Visualization] make table vis column sortable
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
  src/plugins/vis_type_table/public/table_vis_fn.ts
  src/plugins/vis_type_table/public/types.ts
Labels: tableVis

#2570 [MD] Make text content dynamically translated & update unit tests
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_button/__snapshots__/create_button.test.tsx.snap
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/text_content/index.ts
  src/plugins/data_source_management/public/components/text_content/text_content.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/__snapshots__/experimental_callout.test.tsx.snap
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.test.tsx
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/__snapshots__/experimental_callout.test.tsx.snap
  src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.test.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.tsx
Labels: backport 2.x, multiple datasource

#2567 [MD] Adding unit test coverage for Update data source management
  CHANGELOG.md
  src/plugins/data_source_management/public/components/edit_data_source/__snapshots__/edit_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/__snapshots__/edit_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/__snapshots__/update_password_modal.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/mocks.ts
Labels: test:unit, backport 2.x, multiple datasource, v2.4.0

#2562 [Table Visualization] format table cell and restore showTotal feature
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
Labels: tableVis

#2568 [Table Visualization]restore export csv feature to table vis
  src/plugins/vis_type_table/opensearch_dashboards.json
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_control.tsx
  src/plugins/vis_type_table/public/to_ast.ts
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts
Labels: tableVis

#2574 [MD] skip data source view when pick default
  CHANGELOG.md
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx
Labels: backport 2.x, multiple datasource

#2578 [Table Visualization] split table in rows and columns
  src/plugins/vis_type_table/public/components/table_vis_app.scss
  src/plugins/vis_type_table/public/components/table_vis_app.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
  src/plugins/vis_type_table/public/table_vis_response_handler.ts
Labels: tableVis

#2581 [VisBuilder] Change classname prefix wiz to vb
  CHANGELOG.md
  src/plugins/wizard/public/application/_variables.scss
  src/plugins/wizard/public/application/app.scss
  src/plugins/wizard/public/application/app.tsx
  src/plugins/wizard/public/application/components/data_tab/config_panel.scss
  src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
  src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
  src/plugins/wizard/public/application/components/data_tab/index.scss
  src/plugins/wizard/public/application/components/data_tab/index.tsx
  src/plugins/wizard/public/application/components/data_tab/schema_to_dropbox.tsx
  src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/wizard/public/application/components/data_tab/title.tsx
  src/plugins/wizard/public/application/components/left_nav.tsx
  src/plugins/wizard/public/application/components/option.scss
  src/plugins/wizard/public/application/components/option.tsx
  src/plugins/wizard/public/application/components/right_nav.tsx
  src/plugins/wizard/public/application/components/searchable_dropdown.scss
  src/plugins/wizard/public/application/components/searchable_dropdown.tsx
  src/plugins/wizard/public/application/components/side_nav.scss
  src/plugins/wizard/public/application/components/top_nav.scss
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/components/workspace.scss
  src/plugins/wizard/public/application/components/workspace.tsx
  src/plugins/wizard/public/embeddable/disabled_visualization.scss
  src/plugins/wizard/public/embeddable/disabled_visualization.tsx
Labels: vis builder, v2.4.0

#2583 [Table Visualization][IMPROVE] remove repeated column from split tables
  src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
Labels: tableVis

#2625 [MD]Address comments from UX sign-off meeting-Datasource list and create page
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
Labels: ux / ui, backport 2.x, multiple datasource, v2.4.0

#2635 [Vis Builder] Rename wizard to visBuilder in i18n id and formatted message id
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/data_source_select.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_search.tsx
  src/plugins/vis_builder/public/application/components/experimental_info.tsx
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/utils/breadcrumbs.ts
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/use/use_can_save.ts
  src/plugins/vis_builder/public/embeddable/disabled_visualization.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.ts
Labels: vis builder, backport 2.x, v2.4.0

#2639 [Vis Builder] Rename wizard to visBuilder in class name, type name and function name
  CHANGELOG.md
  src/plugins/vis_builder/common/index.ts
  src/plugins/vis_builder/common/vis_builder_saved_object_attributes.ts
  src/plugins/vis_builder/public/application/app.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_search.tsx
  src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/index.tsx
  src/plugins/vis_builder/public/application/utils/get_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.test.tsx
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/mocks.ts
  src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts
  src/plugins/vis_builder/public/application/utils/state_management/preload.ts
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/state_management/style_slice.ts
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
  src/plugins/vis_builder/public/application/utils/use/index.ts
  src/plugins/vis_builder/public/application/utils/use/use_index_pattern.tsx
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/application/utils/use/use_visualization_type.ts
  src/plugins/vis_builder/public/application/utils/vis_builder_state_validation.test.ts
  src/plugins/vis_builder/public/application/utils/vis_builder_state_validation.ts
  src/plugins/vis_builder/public/embeddable/disabled_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_component.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/index.ts
  src/plugins/vis_builder/public/plugin.test.ts
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/plugin_services.ts
  src/plugins/vis_builder/public/saved_visualizations/_saved_vis.ts
  src/plugins/vis_builder/public/saved_visualizations/saved_visualization_references.ts
  src/plugins/vis_builder/public/saved_visualizations/saved_visualizations.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.test.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.ts
  src/plugins/vis_builder/public/types.ts
  src/plugins/vis_builder/server/index.ts
  src/plugins/vis_builder/server/plugin.ts
  src/plugins/vis_builder/server/saved_objects/index.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_app.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_migration.test.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_migration.ts
  src/plugins/vis_builder/server/types.ts
Labels: vis builder, backport 2.x, v2.4.0

#2607 [BUG] fix suggestion list cutoff issue
  CHANGELOG.md
  src/plugins/data/public/ui/typeahead/_suggestion.scss
Labels: bug, ux / ui, backport 1.x, backport 2.x, v2.4.0

#2611 [MD] Address UX comments on index pattern stack
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
Labels: backport 2.x, multiple datasource, v2.4.0

#2582 [Table Visualization][BUG] remove local column width state
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/utils/use_pagination.ts
Labels: tableVis

#2640 [CVE 2022-3517] Bump minimatch to 3.0.5 and [IBM X-Force ID: 220063] unset-value to 2.0.1
  CHANGELOG.md
  package.json
  yarn.lock
Labels: security vulnerability, cve, backport 2.x

#2653 [CVE] Bump follow-redirects to 1.15.2 to fix CVE-2022-0155 and CVE-20…
  CHANGELOG.md
  package.json
  yarn.lock
Labels: security vulnerability, cve, v1.3.7

#2642 [Backport 2.x][MD]Address comments from UX signoff meeting-Datasource list and create page
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
Labels: multiple datasource, v2.4.0

#2660 [CVE] Remove storybook package to fix CVE-2021-42740 and CVE-2021-24033
  .eslintrc.js
  CHANGELOG.md
  package.json
  packages/osd-storybook/README.md
  packages/osd-storybook/index.ts
  packages/osd-storybook/lib/constants.ts
  packages/osd-storybook/lib/default_config.ts
  packages/osd-storybook/lib/register.ts
  packages/osd-storybook/lib/run_storybook_cli.ts
  packages/osd-storybook/lib/templates/index.ejs
  packages/osd-storybook/package.json
  packages/osd-storybook/preset.js
  packages/osd-storybook/tsconfig.json
  packages/osd-storybook/typings.d.ts
  packages/osd-storybook/webpack.config.ts
  packages/osd-storybook/yarn.lock
  scripts/storybook.js
  src/dev/precommit_hook/casing_check_config.js
  src/dev/storybook/aliases.ts
  src/dev/storybook/commands/clean.ts
  src/dev/storybook/run_storybook_cli.ts
  src/plugins/embeddable/.storybook/main.js
  src/plugins/embeddable/public/components/panel_options_menu/__examples__/panel_options_menu.stories.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/.storybook/main.js
  src/plugins/opensearch_dashboards_react/public/code_editor/README.md
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.stories.tsx
  tsconfig.base.json
  yarn.lock
Labels: security vulnerability, cve, v1.3.7

#2652 Apply get indice error handling in step index pattern
  CHANGELOG.md
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
Labels: backport 2.x, multiple datasource, v2.4.0

#2648 [Table Visualization][BUG] partical rows shows metrics for all columns
  src/plugins/vis_type_table/public/to_ast.ts
Labels: tableVis

#2668 [CVE] Bump prismjs to 1.29.0 to fix CVE-2022-23647
  CHANGELOG.md
  yarn.lock
Labels: security vulnerability, cve, backport 1.3, v1.3.7

#2632 [Vis Builder] Bug fixes for datasource picker and auto time interval
  CHANGELOG.md
  src/core/public/saved_objects/simple_saved_object.ts
  src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/vis_builder/public/application/components/option.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
  src/plugins/vis_builder/public/application/utils/use/index.ts
  src/plugins/vis_builder/public/application/utils/use/use_aggs.ts
  src/plugins/vis_builder/public/application/utils/validate_schema_state.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/services/type_service/types.ts
  src/plugins/vis_builder/public/services/type_service/visualization_type.tsx
  src/plugins/vis_builder/public/visualizations/metric/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/area/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/common/create_vis.ts
  src/plugins/vis_builder/public/visualizations/vislib/common/types.ts
  src/plugins/vis_builder/public/visualizations/vislib/histogram/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/line/to_expression.ts
Labels: vis builder, backport 2.x, v2.4.0

#2628 Last Updated Timestamp for visbuilder savedobject is getting Generated
  CHANGELOG.md
  src/plugins/saved_objects/public/types.ts
  src/plugins/vis_builder/common/vis_builder_saved_object_attributes.ts
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/visualizations/public/vis_types/vis_type_alias_registry.ts
Labels: vis builder, backport 2.x, v2.4.0

#2661 [MD] Refactor data source server side error handling
  CHANGELOG.md
  src/core/server/http/router/router.ts
  src/plugins/data/server/plugin.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
  src/plugins/data/server/search/search_service.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/lib/error.test.ts
  src/plugins/data_source/server/lib/error.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
  src/plugins/index_pattern_management/server/routes/resolve_index.ts
Labels: enhancement, backport 2.x, multiple datasource, v2.4.0

#2645 [Vis Builder] Rename wizard on save modal and visualization table
  CHANGELOG.md
  src/plugins/vis_builder/common/index.ts
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/visualize/public/application/components/visualize_listing.scss
  src/plugins/visualize/public/application/utils/get_table_columns.tsx
Labels: vis builder, backport 2.x, v2.4.0

#2673 Change save object type, wizard id and name to visBuilder
  CHANGELOG.md
  config/opensearch_dashboards.yml
  packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
  src/plugins/saved_objects/README.md
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/saved_objects_management/public/register_services.ts
  src/plugins/vis_builder/README.md
  src/plugins/vis_builder/common/index.ts
  src/plugins/vis_builder/common/vis_builder_saved_object_attributes.ts
  src/plugins/vis_builder/opensearch_dashboards.json
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/assets/vis_builder_icon.svg
  src/plugins/vis_builder/public/assets/vis_builder_icon_secondary_fill.svg
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/server/capabilities_provider.ts
  src/plugins/vis_builder/server/plugin.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_app.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_migration.test.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_migration.ts
  test/common/config.js
  test/functional/apps/vis_builder/_base.ts
  test/functional/apps/vis_builder/_experimental_vis.ts
  test/functional/apps/vis_builder/index.ts
  test/functional/apps/visualize/_chart_types.ts
  test/functional/config.js
  test/functional/page_objects/index.ts
  test/functional/page_objects/vis_builder_page.ts
Labels: vis builder, backport 2.x, v2.4.0

#2689 [CVE] Bump loader-utils to 2.0.3 to fix CVE-2022-37601
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: security vulnerability, cve, backport 1.x, backport 1.3, backport 1.2, backport 1.1, backport 1.0, backport 2.x, backport 2.0, backport 2.1, v2.4.0, backport 2.2, backport 2.3, v1.3.7

#2692 [Backport 2.x] [VizBuilder] Create a new wizard directly on a dashboard (#2384)
  CHANGELOG.md
  packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
  src/plugins/wizard/public/application/components/top_nav.tsx
  src/plugins/wizard/public/application/utils/get_top_nav_config.test.tsx
  src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
  src/plugins/wizard/public/application/utils/mocks.ts
  src/plugins/wizard/public/plugin.ts
  src/plugins/wizard/public/types.ts
Labels: v2.4.0

#2638 Removed Leftover X Pack references #2517
  CHANGELOG.md
  packages/osd-pm/src/utils/validate_dependencies.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/opensearch_index.ts
  src/dev/notice/cli.js
  src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
  src/plugins/data/README.md
Labels: backport 1.x, backport 2.x, v2.4.0

#2694 Revert "[@osd/cross-platform] Adds cross-platform helpers (#2681)"
  CHANGELOG.md
  package.json
  packages/osd-config-schema/package.json
  packages/osd-config-schema/src/errors/schema_error.test.ts
  packages/osd-cross-platform/README.md
  packages/osd-cross-platform/package.json
  packages/osd-cross-platform/src/index.ts
  packages/osd-cross-platform/src/path.ts
  packages/osd-cross-platform/src/process.ts
  packages/osd-cross-platform/tsconfig.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/optimizer/get_changes.test.ts
  packages/osd-plugin-generator/package.json
  packages/osd-plugin-generator/src/integration_tests/generate_plugin.test.ts
  packages/osd-plugin-helpers/package.json
  packages/osd-plugin-helpers/src/cli.ts
  packages/osd-plugin-helpers/src/integration_tests/build.test.ts
  packages/osd-pm/package.json
  packages/osd-pm/src/utils/projects_tree.ts
  packages/osd-utils/package.json
  packages/osd-utils/src/path/index.ts
  src/dev/build/lib/config.test.ts
Labels: backport 2.x

#2646 [Backport 1.x][BUG]fix suggestion list cutoff issue
  CHANGELOG.md
  src/plugins/data/public/ui/typeahead/_suggestion.scss
Labels: backport 1.3, backport 1.2, backport 1.1, backport 1.0

#2538 [MD] Add design documents of multiple data source feature
  CHANGELOG.md
  docs/multi-datasource/client_management_design.md
  docs/multi-datasource/high_level_design.md
  docs/multi-datasource/img/client_management_architecture.png
  docs/multi-datasource/img/client_management_dataflow.png
  docs/multi-datasource/img/dsm_flow.png
  docs/multi-datasource/img/hld_setup_diagram.png
  docs/multi-datasource/img/hld_vis_flow.png
  docs/multi-datasource/resources/client_management_architecture.puml
  docs/multi-datasource/resources/client_management_dataflow.puml
  docs/multi-datasource/resources/dsm_flow.puml
  docs/multi-datasource/user_stories.md
  src/plugins/data_source/README.md
Labels: docs, multiple datasource

#2690 [Backport 2.x]Add extension point in saved object management to register namespaces…
  CHANGELOG.md
  src/plugins/saved_objects_management/public/index.ts
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/lib/parse_query.test.ts
  src/plugins/saved_objects_management/public/lib/parse_query.ts
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/saved_objects_management/public/services/index.ts
  src/plugins/saved_objects_management/public/services/namespace_service.mock.ts
  src/plugins/saved_objects_management/public/services/namespace_service.ts
  src/plugins/saved_objects_management/public/services/types/namespace.ts
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
Labels: v2.4.0
