Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-09, with the labels that each got.

#4868 [Manual Backport 1.3] Test (linkchecker): Exclude checking dead link (#4720)
  .lycheeexclude
Labels: Skip-Changelog, v1.3.13

#4874 [WS-2021-0638][Security] Alias and bump mocha to v10.1.0
  .eslintrc.js
  CHANGELOG.md
  package.json
  packages/opensearch-eslint-config-opensearch-dashboards/javascript.js
  packages/opensearch-eslint-config-opensearch-dashboards/package.json
  packages/osd-test/src/functional_test_runner/integration/failure_hooks.test.js
  packages/osd-test/src/functional_test_runner/lib/mocha/filter_suites_by_tags.test.js
  packages/osd-test/src/functional_test_runner/lib/mocha/reporter/reporter.js
  packages/osd-test/src/functional_test_runner/lib/mocha/setup_mocha.js
  src/dev/mocha/__tests__/junit_report_generation.js
  src/dev/mocha/auto_junit_reporter.js
  src/dev/mocha/run_mocha_cli.js
  test/mocha_decorations.d.ts
  test/visual_regression/services/visual_testing/visual_testing.ts
  yarn.lock
Labels: v2.10.0

#4890 [Vis Colors] Update color mapper to prioritize unique colors per vis
  CHANGELOG.md
  src/plugins/charts/public/services/colors/colors.ts
  src/plugins/charts/public/services/colors/mapped_colors.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4889 [Data Explorer][Discover 2.0] Allow Top Nav to update based on index pattern change
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4845 Feat (Advanced Settings): Make new "Appearance" category
  CHANGELOG.md
  src/core/server/ui_settings/settings/accessibility.ts
  src/core/server/ui_settings/settings/navigation.ts
  src/core/server/ui_settings/settings/theme.ts
  src/plugins/advanced_settings/public/management_app/components/form/__snapshots__/form.test.tsx.snap
  src/plugins/advanced_settings/public/management_app/components/form/form.tsx
  src/plugins/advanced_settings/public/management_app/lib/get_category_name.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4897 Bump OUI to `1.3.0-rc.1`
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: Skip-Changelog

#4891 Fixes broken app when management is turned off
  CHANGELOG.md
  src/core/types/capabilities.ts
  src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_footer/overview_page_footer.tsx
  src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4896 Remove examples and other unwanted artifacts from installed dependencies
  CHANGELOG.md
  package.json
  scripts/postinstall.js
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4861 [Manual Backport 2.x][CCI] Fix EUI/OUI type errors (#3798)
  CHANGELOG.md
  src/plugins/advanced_settings/public/management_app/components/field/field.test.tsx
  src/plugins/advanced_settings/public/management_app/components/form/form.test.tsx
  src/plugins/advanced_settings/public/management_app/components/search/search.test.tsx
  src/plugins/advanced_settings/public/management_app/components/search/search.tsx
  src/plugins/data/public/ui/shard_failure_modal/shard_failure_open_modal_button.test.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.test.tsx
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.test.tsx
  src/plugins/discover/public/application/components/doc/doc.test.tsx
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer.test.tsx
  src/plugins/discover/public/application/components/loading_spinner/loading_spinner.test.tsx
  src/plugins/discover/public/application/components/table/table.test.tsx
  src/plugins/discover_legacy/public/application/angular/context/components/action_bar/action_bar.test.tsx
  src/plugins/discover_legacy/public/application/angular/doc_table/components/pager/tool_bar_pager_buttons.test.tsx
  src/plugins/discover_legacy/public/application/angular/doc_table/components/table_header/table_header.test.tsx
  src/plugins/discover_legacy/public/application/components/context_error_message/context_error_message.test.tsx
  src/plugins/embeddable/public/lib/embeddables/embeddable_root.test.tsx
  src/plugins/embeddable/public/lib/panel/embeddable_panel.test.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_flyout.test.tsx
  src/plugins/input_control_vis/public/components/editor/controls_tab.test.tsx
  src/plugins/input_control_vis/public/components/editor/list_control_editor.test.tsx
  src/plugins/input_control_vis/public/components/editor/range_control_editor.test.tsx
  src/plugins/input_control_vis/public/components/vis/input_control_vis.test.tsx
Labels: v2.10.0

#4906 Feat (home): Add new theme dashboard screenshots
  CHANGELOG.md
  src/plugins/home/public/application/components/new_theme_modal.tsx
  src/plugins/home/public/application/components/sample_data_set_cards.js
  src/plugins/home/public/assets/new_theme_dark.png
  src/plugins/home/public/assets/new_theme_light.png
  src/plugins/home/public/assets/sample_data_resources/ecommerce/dashboard_dark_new.png
  src/plugins/home/public/assets/sample_data_resources/ecommerce/dashboard_new.png
  src/plugins/home/public/assets/sample_data_resources/flights/dashboard_dark_new.png
  src/plugins/home/public/assets/sample_data_resources/flights/dashboard_new.png
  src/plugins/home/public/assets/sample_data_resources/logs/dashboard_dark_new.png
  src/plugins/home/public/assets/sample_data_resources/logs/dashboard_new.png
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/index.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/index.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_schema.ts
  src/plugins/home/server/services/sample_data/routes/list.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4932 Modify call out text for discover
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover_legacy/public/application/components/discover_legacy.tsx
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4936 Use themes' definitions to render the initial view.
  CHANGELOG.md
  packages/osd-ui-shared-deps/theme.ts
  src/core/server/rendering/views/fonts.tsx
  src/core/server/rendering/views/styles.tsx
  src/core/server/rendering/views/template.tsx
  src/core/server/rendering/views/theme.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4941 Bump OUI to `1.3.0`
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4948 [NodeJS18 Upgrade] Bump OpenSearch-Dashboards 2.10.0 to use nodejs 18.16.0 version and update changelog of 2.9.0/Unreleased Sections
  .node-version
  .nvmrc
  CHANGELOG.md
Labels: >upgrade, release, nodejs :lollipop:, v2.10.0

#4938 Fix (discover): Fix dismiss callout and next styling
  packages/osd-stylelint-config/config/global_selectors.json
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.scss
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover_legacy/public/application/components/discover_legacy.tsx
Labels: backport 2.x, discover, de-angular, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4562 [Console] Add support for JSON with long numerals
  CHANGELOG.md
  package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch/package.json
  packages/osd-std/README.md
  packages/osd-std/src/__snapshots__/json.test.ts.snap
  packages/osd-std/src/index.ts
  packages/osd-std/src/json.test.ts
  packages/osd-std/src/json.ts
  src/core/public/http/fetch.test.ts
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/client/mocks.ts
  src/core/server/opensearch/client/scoped_cluster_client.test.ts
  src/core/server/opensearch/client/scoped_cluster_client.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/lib/opensearch/opensearch.ts
  src/plugins/console/public/lib/utils/__tests__/__snapshots__/utils.test.ts.snap
  src/plugins/console/public/lib/utils/__tests__/utils.test.ts
  src/plugins/console/public/lib/utils/index.ts
  src/plugins/console/public/services/storage.ts
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
  src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/headers.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/params.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
  src/plugins/opensearch_ui_shared/__packages_do_not_import__/xjson/json_xjson_translation_tools/index.ts
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4946 [Manual backport 2.x] Bump OUI to `1.3.0` (#4941)
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/core/public/styles/_base.scss
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: v2.10.0

#4953 Correct the generated path for downloading plugins by their names on Windows
  .lycheeexclude
  CHANGELOG.md
  src/cli_plugin/install/settings.js
  src/cli_plugin/install/settings.test.js
Labels: backport 2.x, distinguished-contributor, v2.10.0, backport 2.10

#4967 [Manual Backport 2.x][Console] Add support for JSON with long numerals (#4562)
  CHANGELOG.md
  package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch/package.json
  packages/osd-std/README.md
  packages/osd-std/src/__snapshots__/json.test.ts.snap
  packages/osd-std/src/index.ts
  packages/osd-std/src/json.test.ts
  packages/osd-std/src/json.ts
  src/core/public/http/fetch.test.ts
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/client/mocks.ts
  src/core/server/opensearch/client/scoped_cluster_client.test.ts
  src/core/server/opensearch/client/scoped_cluster_client.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/lib/opensearch/opensearch.ts
  src/plugins/console/public/lib/utils/__tests__/__snapshots__/utils.test.ts.snap
  src/plugins/console/public/lib/utils/__tests__/utils.test.ts
  src/plugins/console/public/lib/utils/index.ts
  src/plugins/console/public/services/storage.ts
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
  src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/headers.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/params.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
  src/plugins/opensearch_ui_shared/__packages_do_not_import__/xjson/json_xjson_translation_tools/index.ts
  yarn.lock
Labels: v2.10.0, backport 2.10

#4977 Revert "[Console] Add support for JSON with long numerals (#4562) (#4967) (#4973)"
  package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch/package.json
  packages/osd-std/README.md
  packages/osd-std/src/__snapshots__/json.test.ts.snap
  packages/osd-std/src/index.ts
  packages/osd-std/src/json.test.ts
  packages/osd-std/src/json.ts
  src/core/public/http/fetch.test.ts
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/client/mocks.ts
  src/core/server/opensearch/client/scoped_cluster_client.test.ts
  src/core/server/opensearch/client/scoped_cluster_client.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/lib/opensearch/opensearch.ts
  src/plugins/console/public/lib/utils/__tests__/__snapshots__/utils.test.ts.snap
  src/plugins/console/public/lib/utils/__tests__/utils.test.ts
  src/plugins/console/public/lib/utils/index.ts
  src/plugins/console/public/services/storage.ts
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
  src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/headers.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/params.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
  src/plugins/opensearch_ui_shared/__packages_do_not_import__/xjson/json_xjson_translation_tools/index.ts
  yarn.lock
Labels: Skip-Changelog, v2.10.0

#4979 Add v2.10.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.10.0.md
Labels: backport main, backport 2.x, Skip-Changelog, v2.10.0

#3810 Feature: Dev Tools Query Export/Import
  CHANGELOG.md
  src/plugins/console/public/application/components/__snapshots__/import_flyout.test.tsx.snap
  src/plugins/console/public/application/components/__snapshots__/import_mode_control.test.tsx.snap
  src/plugins/console/public/application/components/__snapshots__/overwrite_modal.test.tsx.snap
  src/plugins/console/public/application/components/import_flyout.test.tsx
  src/plugins/console/public/application/components/import_flyout.tsx
  src/plugins/console/public/application/components/import_mode_control.test.tsx
  src/plugins/console/public/application/components/import_mode_control.tsx
  src/plugins/console/public/application/components/index.ts
  src/plugins/console/public/application/components/overwrite_modal.test.tsx
  src/plugins/console/public/application/components/overwrite_modal.tsx
  src/plugins/console/public/application/containers/main/get_top_nav.ts
  src/plugins/console/public/application/containers/main/main.tsx
  src/plugins/console/public/application/contexts/services_context.mock.ts
  src/plugins/console/public/application/contexts/services_context.tsx
  src/plugins/console/public/application/hooks/use_data_init/use_data_init.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.test.tsx
  src/plugins/console/public/application/index.tsx
  src/plugins/console/public/plugin.ts
Labels: ux / ui, backport 2.x, first-time-contributor, v2.10.0

#4492 Replace Tinymath with math.js
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/vis_type_timeseries/public/application/components/aggs/math.js
  src/plugins/vis_type_timeseries/server/lib/vis_data/response_processors/series/evaluate.ts
  src/plugins/vis_type_timeseries/server/lib/vis_data/response_processors/series/math.js
  src/plugins/vis_type_timeseries/server/lib/vis_data/response_processors/series/math.test.js
  yarn.lock
Labels: v3.0.0, first-time-contributor, breaking change

#4895 [Follow-up] Fix extraction script
  src/plugins/discover/public/application/components/doc_views/context/utils/use_query_actions.ts
  src/plugins/discover/public/application/components/doc_views/single_doc_app.tsx
  src/plugins/discover/public/application/view_components/utils/index_pattern_helper.ts
  src/plugins/vis_type_vega/public/expressions/line_vega_spec_fn.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.11.0

#4638 [Table Visualization] Fix width of multiple tables when rendered in column view
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
Labels: backport 2.x, tableVis, valued-contributor, v2.11.0

#4837 Fix filter actions on data table vis cells
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
Labels: backport 2.x, tableVis, first-time-contributor, v2.11.0

#4975 [2.x] Version increment from 2.10 to 2.11
  CHANGELOG.md
  package.json
Labels: v2.11.0

#5002 [1.3] [CVE-2023-26136] Bump word-wrap from 1.2.3 to 1.2.4
  CHANGELOG.md
  yarn.lock
Labels: cve, v1.3.13

#5016 [1.3][CVE-2022-21670] Bump markdown-it from 10.0.0 to 12.3.2
  CHANGELOG.md
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-release-notes/package.json
  yarn.lock
Labels: cve, v1.3.13

#5006 [1.3][CVE-2022-33987] Partially fix security issues for got by bumping @elastic/makelogs from 6.0.0 to 6.1.1 and update yarn.lock
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, v1.3.13

#5005 [1.3] Bump yo from 2.0.6 to 3.1.1
  CHANGELOG.md
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, v1.3.13

#4992 [BUG] Fix buildPointSeriesData unit test fails due to local timezone
  CHANGELOG.md
  src/plugins/discover/public/application/components/chart/utils/point_series.test.ts
Labels: bug, test:unit, backport 2.x, discover, distinguished-contributor, v2.11.0

#5029 [Discover 2.0] fixes add filter and dismissible callout
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/filter_columns.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover_legacy/public/application/components/discover_legacy.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.10.0, backport 2.10

#5024 [1.3][CVE-2023-0842] Bump xml2js from 0.4.22 to 0.6.2
  CHANGELOG.md
  package.json
  packages/osd-test/package.json
  yarn.lock
Labels: cve, v1.3.13

#5030 Chore: Add 1.3.13 release notes
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-1.3.13.md
Labels: backport main, v1.3.13

#5065 Updating yarn installation step from the Dev guide
  DEVELOPER_GUIDE.md
Labels: backport 1.3, backport 2.x, Skip-Changelog, first-time-contributor, v2.11.0, v1.3.14

#5072 Add `data-test-subj` for data explorer cypress test
  src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_inspect_button.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
Labels: test:functional, backport 2.x, Skip-Changelog, distinguished-contributor, data explorer, v2.11.0

#5087 [Data Explorer][Discover] Fix total hits issue for no time based data
  CHANGELOG.md
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
Labels: bug, backport 2.x, discover, de-angular, distinguished-contributor, data explorer, v2.11.0

#4882 Update optimizer webpack config to support ReactFlow dependency
  packages/osd-optimizer/src/worker/webpack.config.ts
Labels: dependencies, backport 2.x, Skip-Changelog, all-star-contributor

#5088 [Data Explorer] Delete legacy discover selenium tests
  test/functional/apps/context/_date_nanos.js
  test/functional/apps/context/_date_nanos_custom_timestamp.js
  test/functional/apps/context/_filters.js
  test/functional/apps/context/index.js
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/dashboard/panel_context_menu.ts
  test/functional/apps/discover/_date_nanos.js
  test/functional/apps/discover/_date_nanos_mixed.js
  test/functional/apps/discover/_discover.js
  test/functional/apps/discover/_discover_histogram.ts
  test/functional/apps/discover/_doc_navigation.js
  test/functional/apps/discover/_doc_table.ts
  test/functional/apps/discover/_errors.ts
  test/functional/apps/discover/_field_data.js
  test/functional/apps/discover/_field_visualize.ts
  test/functional/apps/discover/_filter_editor.js
  test/functional/apps/discover/_indexpattern_with_encoded_id.ts
  test/functional/apps/discover/_indexpattern_without_timefield.ts
  test/functional/apps/discover/_inspector.js
  test/functional/apps/discover/_large_string.js
  test/functional/apps/discover/_saved_queries.js
  test/functional/apps/discover/_shared_links.js
  test/functional/apps/discover/_sidebar.js
  test/functional/apps/discover/_source_filters.js
  test/functional/apps/discover/index.js
  test/functional/apps/home/_navigation.ts
  test/functional/apps/management/_handle_alias.js
  test/functional/apps/management/_scripted_fields.js
  test/functional/apps/visualize/_lab_mode.js
  test/functional/apps/visualize/index.ts
  test/functional/config.js
  test/functional/page_objects/discover_page.ts
  test/functional/services/dashboard/visualizations.ts
Labels: test:functional, de-angular, Skip-Changelog, distinguished-contributor, data explorer

#5067 Update yarn install step from dev guide
  DEVELOPER_GUIDE.md
  package.json
Labels: backport 1.3, backport 2.x, Skip-Changelog, valued-contributor, v2.11.0, v1.3.14

#5099 [Data Explorer][Discover][Function Test] Fix ciGroup4
  package.json
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/dashboard/dashboard_time_picker.js
  test/functional/page_objects/discover_page.ts
  test/functional/services/dashboard/expectations.ts
  test/functional/services/data_grid.ts
Labels: test:functional, discover, distinguished-contributor, data explorer

#5104 [Data Explorer][Discover][Functional Test] fix ciGroup 8
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  test/functional/apps/management/_handle_alias.js
  test/functional/page_objects/discover_page.ts
Labels: test:functional, discover, data explorer

#5105 Fix cigroup 1 with dataGridTable helper functions
  src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
  test/functional/apps/context/_context_navigation.js
  test/functional/apps/context/_date_nanos.js
  test/functional/apps/context/_discover_navigation.js
  test/functional/apps/context/_filters.js
  test/functional/apps/context/_size.js
  test/functional/apps/management/_scripted_fields.js
  test/functional/page_objects/discover_page.ts
  test/functional/services/data_grid.ts
Labels: test:functional, data explorer

#5111 [Data Explorer] Fix functional cigroup 3 for save search on dashboard filtering
  test/functional/apps/dashboard/dashboard_filter_bar.js
  test/functional/apps/dashboard/dashboard_filtering.js
  test/functional/services/dashboard/expectations.ts
  test/functional/services/data_grid.ts
Labels: test:functional, de-angular, data explorer

#5119 [Data Explorer] Fix ciGroup 2 with adding data-shared-item tags on save search
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/embeddable/search_embeddable.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
  test/functional/apps/dashboard/dashboard_query_bar.js
Labels: de-angular, data explorer

#5113 Add Bandini as maintainer
  CHANGELOG.md
  MAINTAINERS.md
Labels: valued-contributor

#5080 Modifying html fixtures to utilize jsx and fixing tests to include all p…
  DEVELOPER_GUIDE.md
  packages/osd-i18n/GUIDELINE.md
  packages/osd-i18n/README.md
  packages/osd-i18n/angular/package.json
  src/dev/i18n/README.md
  src/dev/i18n/__fixtures__/extract_default_translations/test_plugin_1/test_file_4.html
  src/dev/i18n/__fixtures__/extract_default_translations/test_plugin_2/test_file.html
  src/dev/i18n/__fixtures__/extract_default_translations/test_plugin_2/test_file.jsx
  src/dev/i18n/__fixtures__/extract_default_translations/test_plugin_4/test_file_4.jsx
  src/dev/i18n/__snapshots__/extract_default_translations.test.js.snap
  src/dev/i18n/extract_default_translations.test.js
Labels: de-angular, first-time-contributor

#5125 [Data Explorer] Fix ci group6
  test/functional/apps/home/_navigation.ts
  test/functional/apps/home/_sample_data.ts
Labels: de-angular, distinguished-contributor, v2.11.0

#5112 [Discover] Search on load fix
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/build_services.ts
Labels: discover, de-angular, distinguished-contributor, v2.11.0

#5131 [Data Explorer][Discover][Functional Test] Fix ciGroup7
  test/functional/apps/management/_index_pattern_results_sort.js
  test/functional/apps/management/_opensearch_dashboards_settings.js
  test/functional/apps/management/_scripted_fields.js
  test/functional/apps/management/_scripted_fields_preview.js
  test/functional/page_objects/discover_page.ts
  test/functional/services/data_grid.ts
Labels: test:functional, discover, data explorer

#5134 [CI] allow for manual triggered cypress test jobs to accept inputs
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x

#5085 Deangular: removes angular from notify and utils of opendashboards legacy
  package.json
  src/plugins/opensearch_dashboards_legacy/public/index.ts
  src/plugins/opensearch_dashboards_legacy/public/notify/lib/add_fatal_error.ts
  src/plugins/opensearch_dashboards_legacy/public/notify/lib/format_angular_http_error.ts
  src/plugins/opensearch_dashboards_legacy/public/notify/lib/index.ts
  src/plugins/opensearch_dashboards_legacy/public/utils/index.ts
  src/plugins/opensearch_dashboards_legacy/public/utils/osd_accessible_click.js
  src/plugins/opensearch_dashboards_legacy/public/utils/private.d.ts
  src/plugins/opensearch_dashboards_legacy/public/utils/private.js
  src/plugins/opensearch_dashboards_legacy/public/utils/register_listen_event_listener.js
  src/plugins/opensearch_dashboards_legacy/public/utils/system_api.ts
Labels: de-angular, first-time-contributor

#5114 [Discover] Misc fixes
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.scss
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover_legacy/public/application/components/discover_legacy.tsx
  src/plugins/opensearch_dashboards_legacy/public/notify/lib/add_fatal_error.ts
  src/plugins/opensearch_dashboards_legacy/public/notify/lib/index.ts
  src/plugins/opensearch_dashboards_legacy/public/plugin.ts
Labels: discover, de-angular, distinguished-contributor, v2.11.0

#5142 [CI] Cypress test run spec input
  .github/workflows/cypress_workflow.yml
Labels: ci, backport 2.x, Skip-Changelog
