Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-07, with the labels that each got.

#4453 Update main menu to display 'Dashboards' for consistency
  CHANGELOG.md
  COMMUNICATIONS.md
  src/plugins/dashboard/public/plugin.tsx
Labels: first-time-contributor

#4403 [CVE-2021-23382] Bump postcss from 8.2.10 to 8.4.24
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, v1.3.12

#4469 Adding Matt as a maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.3, backport 2.x, distinguished-contributor, v2.9.0, v1.3.12

#4478 [Dashboard De-Angular] Add dashboard class for discard flow
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/lib/get_app_state_defaults.ts
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/dashboard.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/saved_dashboards/_saved_dashboard.ts
  src/plugins/dashboard/public/types.ts
Labels: de-angular, dashboards, distinguished-contributor

#4479 [Dashboard De-Angular] Add breadcrumb with view/edit mode and unsaved flow
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/utils/breadcrumbs.ts
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
Labels: de-angular, dashboards, distinguished-contributor

#4480 [Dashboard De-Angular] Enable URL title param for initial filter on dashboard listing
  src/plugins/dashboard/public/application/components/dashboard_listing.tsx
Labels: de-angular, dashboards, distinguished-contributor

#4477 Add `color-scheme` to the root styling
  CHANGELOG.md
  src/core/server/rendering/views/styles.tsx
Labels: backport 2.x, distinguished-contributor, v2.9.0

#4299 Refactor hardcoded color to use OUI in `region_map`
  CHANGELOG.md
  src/plugins/region_map/public/choropleth_layer.js
Labels: backport 2.x, repeat-contributor, v2.9.0

#4491 [Dashboard De-Angular] Fix dashboard save and back button functional test
  src/plugins/dashboard/common/migrate_to_730_panels.ts
  src/plugins/dashboard/public/application/app.tsx
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/lib/embeddable_saved_object_converters.ts
  src/plugins/dashboard/public/application/lib/get_app_state_defaults.ts
  src/plugins/dashboard/public/application/lib/migrate_app_state.ts
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/types.ts
Labels: de-angular, dashboards, distinguished-contributor

#4495 [Dashboard De-Angular] Fix filter and query related functional tests in functional test group 3
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/lib/save_dashboard.ts
  src/plugins/dashboard/public/application/lib/update_saved_dashboard.ts
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/dashboard.ts
  src/plugins/dashboard/public/saved_dashboards/_saved_dashboard.ts
Labels: de-angular, dashboards, distinguished-contributor

#4484 Add comment about decoupling from embeddables plugin
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Labels: feature-anywhere, v2.9.0, seasoned-contributor

#4008 [Console] Convert lib/mappings to TypeScript
  CHANGELOG.md
  src/plugins/console/public/lib/mappings/__tests__/mapping.test.ts
  src/plugins/console/public/lib/mappings/mappings.ts
Labels: backport 2.x, CCI, repeat-contributor, v2.9.0

#4503 [Vis Augmenter] Minor follow up improvements
  CHANGELOG.md
  src/plugins/embeddable/public/lib/panel/embeddable_panel.tsx
  src/plugins/saved_objects/common/index.ts
  src/plugins/saved_objects/server/ui_settings.ts
  src/plugins/saved_objects_management/public/management_section/object_view/saved_object_view.tsx
  src/plugins/saved_objects_management/public/triggers/saved_object_delete_trigger.ts
  src/plugins/ui_actions/public/triggers/external_action_trigger.ts
  src/plugins/vis_augmenter/common/constants.ts
  src/plugins/vis_augmenter/public/actions/saved_object_delete_action.ts
  src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss
  src/plugins/vis_augmenter/public/view_events_flyout/components/view_events_flyout.tsx
  src/plugins/vis_augmenter/server/routes/stats.ts
  src/plugins/vis_type_vega/public/expressions/__snapshots__/helpers.test.js.snap
  src/plugins/vis_type_vega/public/expressions/helpers.test.js
  src/plugins/vis_type_vega/public/expressions/helpers.ts
  src/plugins/vis_type_vega/public/expressions/line_vega_spec_fn.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
  src/plugins/visualizations/public/plugin.ts
  src/plugins/visualize/public/application/components/visualize_listing.tsx
Labels: feature-anywhere, all-star-contributor, v2.9.0

#4506 [Manual][Backport 2.x]Update main menu to display 'Dashboards' for consistency (#4453)
  CHANGELOG.md
  COMMUNICATIONS.md
  src/plugins/dashboard/public/plugin.tsx
Labels: v2.9.0

#4513 Add TODOs regarding saved obj cleanup/deletion
  src/plugins/saved_objects_management/public/management_section/object_view/saved_object_view.tsx
  src/plugins/saved_objects_management/public/triggers/saved_object_delete_trigger.ts
  src/plugins/vis_augmenter/public/actions/saved_object_delete_action.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
  src/plugins/visualize/public/application/components/visualize_listing.tsx
Labels: feature-anywhere, all-star-contributor, v2.9.0

#4512 [Manual][Backport 2.x]Migrate from legacy elasticsearch client to opensearch-js client in `osd-opensearch-archiver` package
  CHANGELOG.md
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch-archiver/src/actions/empty_opensearch_dashboards_index.ts
  packages/osd-opensearch-archiver/src/actions/load.ts
  packages/osd-opensearch-archiver/src/actions/save.ts
  packages/osd-opensearch-archiver/src/actions/unload.ts
  packages/osd-opensearch-archiver/src/cli.ts
  packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/docs/index_doc_records_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/docs/index_doc_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/docs/test_stubs.ts
  packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/delete_index.ts
  packages/osd-opensearch-archiver/src/lib/indices/delete_index_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/generate_index_records_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/indices/generate_index_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/opensearch_dashboards_index.ts
  packages/osd-opensearch-archiver/src/lib/indices/test_stubs.ts
  packages/osd-opensearch-archiver/src/opensearch_archiver.ts
  test/common/services/opensearch_archiver.ts
Labels: client-consolidation, v2.9.0

#4383 Update header logo selection logic and assets
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_logo.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_logo.test.tsx
  src/core/public/chrome/ui/header/header_logo.tsx
  src/core/server/core_app/assets/default_branding/opensearch_logo_dark_mode.svg
  src/core/server/core_app/assets/default_branding/opensearch_logo_default_mode.svg
  src/core/server/core_app/assets/logos/opensearch_dashboards.svg
  src/core/server/core_app/assets/logos/opensearch_dashboards_darkmode.svg
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4467 [CI] Split build and verify into parallel jobs
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
  TESTING.md
  src/dev/jest/config.js
Labels: ci, backport 1.3, backport 2.x, distinguished-contributor

#4287 New management overview page and rename stack management to dashboard management
  CHANGELOG.md
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/public/components/breadcrumbs.test.ts
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/dev_tools/opensearch_dashboards.json
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/management/opensearch_dashboards.json
  src/plugins/management/public/components/landing/landing.tsx
  src/plugins/management/public/components/management_sections.tsx
  src/plugins/management/public/components/management_sidebar_nav/management_sidebar_nav.scss
  src/plugins/management/public/plugin.ts
  src/plugins/management/public/utils/breadcrumbs.ts
  src/plugins/management_overview/common/constants.ts
  src/plugins/management_overview/opensearch_dashboards.json
  src/plugins/management_overview/public/application.tsx
  src/plugins/management_overview/public/components/overview_card/__snapshots__/overview_card.test.tsx.snap
  src/plugins/management_overview/public/components/overview_card/index.ts
  src/plugins/management_overview/public/components/overview_card/overview_card.test.tsx
  src/plugins/management_overview/public/components/overview_card/overview_card.tsx
  src/plugins/management_overview/public/index.ts
  src/plugins/management_overview/public/overview_app.ts
  src/plugins/management_overview/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  test/functional/page_objects/header_page.ts
Labels: backport 2.x, first-time-contributor, v2.9.0

#4526 Retain the original sample data interface
  CHANGELOG.md
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/index.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/index.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
  src/plugins/home/server/services/sample_data/routes/install.ts
  src/plugins/home/server/services/sample_data/routes/list.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.ts
  src/plugins/home/server/services/sample_data/sample_data_registry.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.9.0

#4516 [Vis Augmenter Add UT for few fns
  CHANGELOG.md
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_augmenter/public/vega/helpers.test.ts
  src/plugins/vis_augmenter/public/vega/helpers.ts
Labels: backport 2.x, feature-anywhere, all-star-contributor, v2.9.0

#4519 [Data Explorer] Mount views dynamically with services
  src/plugins/data_explorer/public/components/app.tsx
  src/plugins/data_explorer/public/components/app_container.test.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/sidebar.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/services/view_service/types.ts
  src/plugins/data_explorer/public/services/view_service/view.ts
  src/plugins/discover/public/application/view_components/canvas/create_canvas.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/index.ts
  src/plugins/discover/public/application/view_components/panel/create_panel.tsx
  src/plugins/discover/public/application/view_components/panel/index.ts
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/plugin.ts
Labels: discover, de-angular, distinguished-contributor, data explorer

#4535 [Vis Augmenter] Update base vis height in view events flyout
  CHANGELOG.md
  src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss
  src/plugins/vis_augmenter/public/view_events_flyout/components/view_events_flyout.tsx
Labels: enhancement, backport 2.x, feature-anywhere, all-star-contributor, v2.9.0, backport 2.9

#4528 [Manual] [Backport 2.x] New management overview page and rename stack management to dashboard…
  CHANGELOG.md
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/public/components/breadcrumbs.test.ts
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/dev_tools/opensearch_dashboards.json
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/management/opensearch_dashboards.json
  src/plugins/management/public/components/landing/landing.tsx
  src/plugins/management/public/components/management_sections.tsx
  src/plugins/management/public/components/management_sidebar_nav/management_sidebar_nav.scss
  src/plugins/management/public/plugin.ts
  src/plugins/management/public/utils/breadcrumbs.ts
  src/plugins/management_overview/common/constants.ts
  src/plugins/management_overview/opensearch_dashboards.json
  src/plugins/management_overview/public/application.tsx
  src/plugins/management_overview/public/components/overview_card/__snapshots__/overview_card.test.tsx.snap
  src/plugins/management_overview/public/components/overview_card/index.ts
  src/plugins/management_overview/public/components/overview_card/overview_card.test.tsx
  src/plugins/management_overview/public/components/overview_card/overview_card.tsx
  src/plugins/management_overview/public/index.ts
  src/plugins/management_overview/public/overview_app.ts
  src/plugins/management_overview/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  test/functional/page_objects/header_page.ts
Labels: v2.9.0

#4504 Refactor app state and cleanup unused imports
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/embeddable/dashboard_container.tsx
  src/plugins/dashboard/public/application/embeddable/grid/dashboard_grid.tsx
  src/plugins/dashboard/public/application/index.tsx
  src/plugins/dashboard/public/application/lib/migrate_app_state.ts
  src/plugins/dashboard/public/application/lib/save_dashboard.ts
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/create_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/application/utils/index.ts
  src/plugins/dashboard/public/application/utils/mocks.ts
  src/plugins/dashboard/public/application/utils/stubs.ts
  src/plugins/dashboard/public/application/utils/use/index.ts
  src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.test.ts
  src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.test.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.test.ts
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.test.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/application/utils/utils.ts
  src/plugins/dashboard/public/dashboard.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/types.ts
  test/functional/apps/dashboard/dashboard_state.js
Labels: de-angular, dashboards, distinguished-contributor

#4540 Set dashboard container functions and fix license headers
  src/plugins/dashboard/public/application/app.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing.tsx
  src/plugins/dashboard/public/application/index.tsx
  src/plugins/dashboard/public/application/utils/breadcrumbs.ts
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
  src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/dashboard.ts
Labels: distinguished-contributor

#4502 Dashboard De-Angularization
  CHANGELOG.md
  package.json
  src/plugins/dashboard/common/migrate_to_730_panels.ts
  src/plugins/dashboard/public/application/_hacks.scss
  src/plugins/dashboard/public/application/app.scss
  src/plugins/dashboard/public/application/app.tsx
  src/plugins/dashboard/public/application/application.ts
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing.tsx
  src/plugins/dashboard/public/application/components/dashboard_no_match.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/components/index.ts
  src/plugins/dashboard/public/application/dashboard_app.html
  src/plugins/dashboard/public/application/dashboard_app.tsx
  src/plugins/dashboard/public/application/dashboard_app_controller.tsx
  src/plugins/dashboard/public/application/dashboard_empty_screen.scss
  src/plugins/dashboard/public/application/dashboard_empty_screen.tsx
  src/plugins/dashboard/public/application/dashboard_state.test.ts
  src/plugins/dashboard/public/application/dashboard_state_manager.ts
  src/plugins/dashboard/public/application/embeddable/_dashboard_container.scss
  src/plugins/dashboard/public/application/embeddable/dashboard_container.tsx
  src/plugins/dashboard/public/application/embeddable/grid/dashboard_grid.tsx
  src/plugins/dashboard/public/application/index.ts
  src/plugins/dashboard/public/application/index.tsx
  src/plugins/dashboard/public/application/legacy_app.js
  src/plugins/dashboard/public/application/lib/embeddable_saved_object_converters.ts
  src/plugins/dashboard/public/application/lib/migrate_app_state.ts
  src/plugins/dashboard/public/application/lib/save_dashboard.ts
  src/plugins/dashboard/public/application/lib/update_saved_dashboard.ts
  src/plugins/dashboard/public/application/listing/create_button.tsx
  src/plugins/dashboard/public/application/listing/dashboard_listing.js
  src/plugins/dashboard/public/application/listing/dashboard_listing.test.js
  src/plugins/dashboard/public/application/listing/dashboard_listing_ng_wrapper.html
  src/plugins/dashboard/public/application/top_nav/get_top_nav_config.ts
  src/plugins/dashboard/public/application/utils/breadcrumbs.ts
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/create_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/application/utils/get_no_items_message.tsx
  src/plugins/dashboard/public/application/utils/get_table_columns.tsx
  src/plugins/dashboard/public/application/utils/index.ts
  src/plugins/dashboard/public/application/utils/mocks.ts
  src/plugins/dashboard/public/application/utils/stubs.ts
  src/plugins/dashboard/public/application/utils/use/index.ts
  src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.test.ts
  src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.test.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.test.ts
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.test.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/dashboard.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/saved_dashboards/_saved_dashboard.ts
  src/plugins/dashboard/public/types.ts
  src/plugins/dashboard/server/saved_objects/migrations_730.test.ts
  test/functional/apps/dashboard/dashboard_state.js
Labels: backport 2.x, de-angular, dashboards, distinguished-contributor, v2.9.0, backport 2.9

#4550 Add v2.9.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.9.0.md
Labels: docs, backport 2.x, Skip-Changelog, v2.9.0, backport 2.9

#4554 Fix line to vega conversion bug
  src/plugins/vis_type_vega/public/expressions/helpers.test.js
  src/plugins/vis_type_vega/public/expressions/helpers.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, backport 2.9

#4556 Fix Node.js download link
  CHANGELOG.md
  src/dev/build/tasks/nodejs/node_download_info.ts
Labels: backport 2.x, distinguished-contributor, v2.9.0, backport 2.9

#4565 [Vis Augmenter] Fix stats API visualization ID bug
  src/plugins/vis_augmenter/server/routes/stats_helpers.test.ts
  src/plugins/vis_augmenter/server/routes/stats_helpers.ts
Labels: backport 2.x, Skip-Changelog, all-star-contributor, v2.9.0, backport 2.9

#4341 Refactor/remove breadcrumb styling
  src/core/public/_variables.scss
  src/core/public/chrome/public/assets/round_filter.svg
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.scss
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: distinguished-contributor

#4069 [CCI] Add new or remove extra tags and styles in `saved_objects_management` plugin
  CHANGELOG.md
  src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/intro.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/not_found_errors.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/object_view/components/intro.tsx
  src/plugins/saved_objects_management/public/management_section/object_view/components/not_found_errors.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_summary.scss
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx
Labels: backport 2.x, CCI, first-time-contributor, v2.10.0

#4527 Add documentation to vis_augmenter
  CHANGELOG.md
  src/plugins/vis_augmenter/README.md
  src/plugins/vis_augmenter/public/types.ts
  src/plugins/vis_augmenter/public/view_events_flyout/README.md
Labels: docs, backport 2.x, feature-anywhere, all-star-contributor, v2.10.0

#4577 [Vis Augmenter] Fix bug of undefined tooltip when all plugin layers are empty
  src/plugins/vis_augmenter/public/test_constants.ts
  src/plugins/vis_augmenter/public/vega/helpers.test.ts
  src/plugins/vis_augmenter/public/vega/helpers.ts
Labels: bug, backport 2.x, Skip-Changelog, all-star-contributor, v2.9.0, backport 2.9

#4563 [Data Explorer] Adds toggle between legacy and new discover
  src/plugins/data_explorer/opensearch_dashboards.json
  src/plugins/data_explorer/public/application.tsx
  src/plugins/data_explorer/public/components/app.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/index.scss
  src/plugins/data_explorer/public/plugin.ts
  src/plugins/data_explorer/public/services/view_service/types.ts
  src/plugins/data_explorer/public/types.ts
  src/plugins/discover/common/index.ts
  src/plugins/discover/public/application/view_components/canvas/canvas.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/panel/panel.tsx
  src/plugins/discover/public/index.ts
  src/plugins/discover/public/plugin.ts
  src/plugins/discover/server/ui_settings.ts
  src/plugins/discover_legacy/opensearch_dashboards.json
  src/plugins/discover_legacy/public/application/angular/discover.js
  src/plugins/discover_legacy/public/plugin.ts
Labels: discover, de-angular, distinguished-contributor, data explorer

#4501 chore (home): Update visual consistency dashboard TSVB colors
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.10.0

#4365 [VisLib] Replace legend color palette with OUI color palette
  CHANGELOG.md
  src/plugins/vis_type_vislib/public/vislib/components/legend/_legend.scss
  src/plugins/vis_type_vislib/public/vislib/components/legend/legend.test.tsx
  src/plugins/vis_type_vislib/public/vislib/components/legend/legend_item.tsx
  src/plugins/vis_type_vislib/public/vislib/components/legend/models.ts
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/page_objects/visualize_chart_page.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4426 Revert "[Manual backport 1.x][CCI] Replace `node` with `scripts/use_node` in functional tests"
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/app_link_test/package.json
  test/plugin_functional/plugins/core_app_status/package.json
  test/plugin_functional/plugins/core_plugin_a/package.json
  test/plugin_functional/plugins/core_plugin_appleave/package.json
  test/plugin_functional/plugins/core_plugin_b/package.json
  test/plugin_functional/plugins/core_plugin_chromeless/package.json
  test/plugin_functional/plugins/core_plugin_route_timeouts/package.json
  test/plugin_functional/plugins/core_plugin_static_assets/package.json
  test/plugin_functional/plugins/core_provider_plugin/package.json
  test/plugin_functional/plugins/data_search/package.json
  test/plugin_functional/plugins/doc_views_links_plugin/package.json
  test/plugin_functional/plugins/doc_views_plugin/package.json
  test/plugin_functional/plugins/index_patterns/package.json
  test/plugin_functional/plugins/management_test_plugin/package.json
  test/plugin_functional/plugins/opensearch_client_plugin/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_top_nav/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  test/plugin_functional/plugins/rendering_plugin/package.json
  test/plugin_functional/plugins/ui_settings_plugin/package.json
Labels: Skip-Changelog, v1.3.12

#3998 Removed KUI usage in maps_legacy plugin
  CHANGELOG.md
  src/plugins/maps_legacy/public/map/_legend.scss
  src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
Labels: backport 2.x, CCI, first-time-contributor, v2.10.0

#4581 Feature (home): Update visual consistency sample dashboard with more vis
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
Labels: Skip-Changelog, distinguished-contributor

#4595 Optimize `augment-vis` saved obj searching by adding arg to saved obj client
  CHANGELOG.md
  src/core/public/saved_objects/saved_objects_client.test.ts
  src/core/public/saved_objects/saved_objects_client.ts
  src/plugins/saved_objects/public/saved_object/saved_object_loader.ts
  src/plugins/vis_augmenter/public/actions/saved_object_delete_action.test.ts
  src/plugins/vis_augmenter/public/actions/saved_object_delete_action.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
Labels: enhancement, backport 2.x, Skip-Changelog, all-star-contributor, backport 2.9, vis-augmenter

#4390 [Markdown] Replace custom css styles and native html with OUI.
  CHANGELOG.md
  src/plugins/vis_type_markdown/public/markdown_options.tsx
  src/plugins/vis_type_markdown/public/markdown_vis.scss
  src/plugins/vis_type_markdown/public/markdown_vis_controller.tsx
Labels: backport 2.x, repeat-contributor, v2.10.0

#4468 [Data Explorer] Clean out angular contents in Discover
  src/plugins/discover/public/application/_discover.scss
  src/plugins/discover/public/application/components/chart/point_series.ts
  src/plugins/discover/public/application/components/create_discover_legacy_directive.ts
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx
  src/plugins/discover/public/application/components/discover_legacy.tsx
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer_render_tab.tsx
  src/plugins/discover/public/application/components/help_menu/help_menu_util.ts
  src/plugins/discover/public/application/components/histogram/histogram.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
  src/plugins/discover/public/application/components/sidebar/discover_index_pattern.tsx
  src/plugins/discover/public/application/components/skip_bottom_button/skip_bottom_button.tsx
  src/plugins/discover/public/application/components/table/table.tsx
  src/plugins/discover/public/application/components/table/table_helper.tsx
  src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
  src/plugins/discover/public/application/components/top_nav/open_search_panel.test.tsx
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/discover/public/application/components/top_nav/show_open_search_panel.tsx
  src/plugins/discover/public/application/components/uninitialized/uninitialized.tsx
  src/plugins/discover/public/application/doc_views/doc_views_helpers.tsx
  src/plugins/discover/public/application/doc_views/doc_views_registry.ts
  src/plugins/discover/public/application/doc_views/doc_views_types.ts
  src/plugins/discover/public/application/index.scss
  src/plugins/discover/public/opensearch_dashboards_services.ts
  src/plugins/discover/public/plugin.ts
Labels: distinguished-contributor

#4608 Add resource ID filtering in fetch `augment-vis` obj queries
  CHANGELOG.md
  src/plugins/saved_objects/public/saved_object/saved_object_loader.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Labels: enhancement, backport 2.x, all-star-contributor, v2.10.0, backport 2.9

#4609 Fix (styles): Make ace code editor themes consistent
  CHANGELOG.md
  src/core/public/styles/_ace_overrides.scss
  src/plugins/vis_default_editor/public/components/controls/raw_json.tsx
  src/plugins/vis_type_timeseries/public/application/components/markdown_editor.js
  src/plugins/vis_type_timeseries/public/application/components/panel_config/markdown.js
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4545 Version increment from 2.9 to 2.10
  package.json
Labels: versioning, Skip-Changelog, v2.10.0

#4475 Enable theme-switching via Advanced Settings to preview the Next theme
  CHANGELOG.md
  package.json
  packages/osd-optimizer/src/common/theme_tags.test.ts
  packages/osd-optimizer/src/common/theme_tags.ts
  packages/osd-optimizer/src/integration_tests/__snapshots__/basic_optimization.test.ts.snap
  packages/osd-optimizer/src/integration_tests/basic_optimization.test.ts
  packages/osd-optimizer/src/optimizer/cache_keys.test.ts
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  packages/osd-ui-shared-deps/theme.ts
  packages/osd-ui-shared-deps/webpack.config.js
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/core_app/styles/_globals_v8dark.scss
  src/core/public/core_app/styles/_globals_v8light.scss
  src/core/server/ui_settings/settings/theme.test.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_config.ts
  src/legacy/ui/ui_render/ui_render_mixin.js
  test/functional/services/combo_box.ts
  test/functional/services/common/find.ts
  test/functional/services/common/test_subjects.ts
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4150 [Console] Convert all non-autocomplete lib files to typescript
  CHANGELOG.md
  src/plugins/console/public/lib/autocomplete/__jest__/url_autocomplete.test.ts
  src/plugins/console/public/lib/autocomplete/body_completer.ts
  src/plugins/console/public/lib/autocomplete/components/url_pattern_matcher.ts
  src/plugins/console/public/lib/autocomplete/types.ts
  src/plugins/console/public/lib/curl_parsing/__tests__/curl_parsing.test.ts
  src/plugins/console/public/lib/curl_parsing/curl.ts
  src/plugins/console/public/lib/opensearch/__tests__/content_type.test.ts
  src/plugins/console/public/lib/osd/__tests__/kb.test.ts
  src/plugins/console/public/lib/osd/api.ts
  src/plugins/console/public/lib/osd/index.ts
  src/plugins/console/public/lib/osd/osd.ts
  src/plugins/console/public/lib/utils/__tests__/utils.test.ts
  typings/index.d.ts
Labels: CCI, repeat-contributor

#4272 [Table Visualization] Replace div containers with OuiFlex components
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_app.scss
  src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_app.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
Labels: backport 2.x, repeat-contributor, v2.10.0

#4625 Chore(CHANGELOG): Update to CHANGELOG post 2.9 release
  CHANGELOG.md
Labels: all-star-contributor

#4621 Refactor/remove breadcrumb styling main
  CHANGELOG.md
  src/core/public/_variables.scss
  src/core/public/chrome/public/assets/round_filter.svg
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.scss
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4451 [Manual][Backport 2.x][Vis colors] Update legacy mapped colors in charts plugin to use ouiPaletteColorBlind()
  src/plugins/charts/public/services/colors/color_palette.ts
  src/plugins/charts/public/services/colors/colors.test.ts
  src/plugins/charts/public/services/colors/colors_palette.test.ts
  src/plugins/charts/public/services/colors/mapped_colors.ts
  src/plugins/charts/server/plugin.ts
  src/plugins/vis_type_tagcloud/public/components/__snapshots__/tag_cloud_visualization.test.js.snap
  src/plugins/vis_type_tagcloud/public/components/tag_cloud_visualization.test.js
Labels: Skip-Changelog, v2.10.0

#4619 Feat (home): Add remaining vis type examples
  CHANGELOG.md
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
Labels: distinguished-contributor

#4564 [Data Explorer][Discover 2.0] Implement data fetch, index pattern, saved search for table vis
  src/plugins/discover/public/__mock__/index_pattern_mock.ts
  src/plugins/discover/public/application/components/data_grid/constants.ts
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_context.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_expand_button.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.test.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
  src/plugins/discover/public/application/components/utils/use_pagination.test.ts
  src/plugins/discover/public/application/components/utils/use_pagination.ts
  src/plugins/discover/public/application/doc_views/doc_views_types.ts
  src/plugins/discover/public/application/view_components/canvas/canvas.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table_app.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table_service.tsx
  src/plugins/discover/public/application/view_components/canvas/utils/use_discover_canvas_service.ts
  src/plugins/discover/public/application/view_components/utils/get_default_sort.ts
  src/plugins/discover/public/application/view_components/utils/get_sort.test.ts
  src/plugins/discover/public/application/view_components/utils/get_sort.ts
  src/plugins/discover/public/application/view_components/utils/get_sort_for_search_source.ts
  src/plugins/discover/public/application/view_components/utils/index_pattern_helper.ts
  src/plugins/discover/public/application/view_components/utils/update_data_source.ts
  src/plugins/discover/public/application/view_components/utils/use_saved_search.ts
Labels: discover, de-angular, distinguished-contributor, data explorer

#4580 [Data Explorer] State management + enhancements
  src/plugins/data_explorer/opensearch_dashboards.json
  src/plugins/data_explorer/public/application.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/sidebar.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/plugin.ts
  src/plugins/data_explorer/public/services/view_service/types.ts
  src/plugins/data_explorer/public/services/view_service/view.ts
  src/plugins/data_explorer/public/services/view_service/view_service.ts
  src/plugins/data_explorer/public/types.ts
  src/plugins/data_explorer/public/utils/mocks.ts
  src/plugins/data_explorer/public/utils/state_management/hooks.ts
  src/plugins/data_explorer/public/utils/state_management/index.ts
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
  src/plugins/data_explorer/public/utils/state_management/preload.ts
  src/plugins/data_explorer/public/utils/state_management/redux_persistence.test.tsx
  src/plugins/data_explorer/public/utils/state_management/redux_persistence.ts
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/data_explorer/public/utils/use/use_view.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/utils/state_management/index.ts
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/panel/panel.tsx
  src/plugins/discover/public/build_services.ts
  src/plugins/discover/public/plugin.ts
Labels: discover, de-angular, distinguished-contributor, data explorer

#4252 [i18n] fix generation scripts
  .i18nrc.json
  CHANGELOG.md
  scripts/i18n_check.js
  scripts/i18n_extract.js
  scripts/i18n_integrate.js
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/data/common/search/aggs/buckets/date_range_fn.ts
  src/plugins/dev_tools/public/application.tsx
  src/plugins/expressions/common/expression_functions/specs/opensearch_dashboards.ts
  src/plugins/opensearch_dashboards_overview/public/components/overview/__snapshots__/overview.test.tsx.snap
  src/plugins/opensearch_dashboards_overview/public/components/overview/overview.tsx
  src/plugins/telemetry/common/constants.ts
  src/plugins/visualizations/server/plugin.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.10.0
