Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-01, with the labels that each got.

#3110 [MD] Improve test connection
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/lib/error.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: multiple datasource, v2.5.0

#3166 Bump node version from 14.20.0 to 14.20.1 to resolve CVE-2022-35256
  .node-version
  .nvmrc
  CHANGELOG.md
  Dockerfile
  TESTING.md
  package.json
  yarn.lock
Labels: cve, v3.0.0, backport 2.x, v2.5.0

#3118 [CI] update yarn timeout for GitHub workflow on Windows
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
Labels: ci, backport 1.x, backport 1.3, backport 2.x, v2.5.0, backport 2.4

#3180 Updated MAINTAINERS.md format.
  MAINTAINERS.md
Labels: backport 1.x, backport 1.3, backport 2.x, Skip-Changelog

#3190 [CI] Record functional test artifacts in case of failure
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x

#3125 [Manual] [Backport 2.x] Automates chromedriver version selection for tests (#2990)
  .github/workflows/build_and_test_workflow.yml
  .gitignore
  CHANGELOG.md
  scripts/upgrade_chromedriver.js
Labels: backport 2.0, backport 2.1, v2.5.0, backport 2.2, backport 2.3, backport 2.4

#3194 [CI] Improve yarn's performance in workflows by caching yarn's cache folder
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
Labels: backport 2.x, v2.5.0

#3100 [Vis Builder] Add app filter and query persistence without using state container
  CHANGELOG.md
  docs/plugins/data_persistence.md
  src/plugins/data/public/index.ts
  src/plugins/data/public/public.api.md
  src/plugins/data/public/query/state_sync/README.md
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.ts
  src/plugins/data/public/query/state_sync/index.ts
  src/plugins/vis_builder/public/application/components/top_nav.tsx
Labels: vis builder, v2.5.0

#3197 [Tests] Skip tests inside the docs folder
  .github/workflows/build_and_test_workflow.yml
Labels: build, backport 2.x, v2.5.0, Skip-Changelog

#3175 [Backport 2.x][Manual]Adds retrying flaky jest tests (#2967)
  CHANGELOG.md
  package.json
  src/dev/jest/config.js
  yarn.lock
Labels: v2.5.0

#3178 [Backport 2.x][Manual] Gets rid of `github-checks-reporter` (#3126)
  CHANGELOG.md
  package.json
  src/dev/ci_setup/setup_env.sh
  tasks/config/run.js
  yarn.lock
Labels: v2.5.0

#3201 Update json5 to 1.0.2 and 2.2.3
  CHANGELOG.md
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 2.x, v2.5.0

#3188 [Backport 2.x][Manual] Bump node version from 14.20.0 to 14.20.1 to resolve CVE-2022-35256 (#3166)
  .node-version
  .nvmrc
  CHANGELOG.md
  Dockerfile
  TESTING.md
  package.json
Labels: v2.5.0

#3203 [Backport 2.x][Manual] [CI] Improve yarn's performance in workflows by caching yarn's cache folder (#3194)
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
Labels: v2.5.0

#3205 [Backport 2.x] [Manual] Update json5 to 1.0.2 and 2.2.3 (#3201)
  CHANGELOG.md
  yarn.lock
Labels: v2.5.0

#3160 [Feature] Allow order control in `createAggConfig`
  CHANGELOG.md
  src/plugins/data/common/search/aggs/agg_configs.test.ts
  src/plugins/data/common/search/aggs/agg_configs.ts
Labels: backport 2.x, v2.5.0, backport 2.5

#3211 [VisBuilder] Adds field unit tests
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/data_tab/utils/get_available_fields.test.ts
  src/plugins/vis_builder/public/application/components/data_tab/utils/get_field_details.test.ts
Labels: vis builder, backport 2.x, v2.5.0, backport 2.5

#3224 [Backport 2.x] [Manual] Fix boktorbb alias. (#3085)
  MAINTAINERS.md
Labels: v2.5.0, Skip-Changelog, backport 2.5

#3213 Fix bug that prevents selected join field to be used
  CHANGELOG.md
  src/plugins/region_map/public/region_map_visualization.js
Labels: backport 2.x, v2.5.0, backport 2.5

#3210 [VisBuilder] fixes filters for table visualisation
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/types.ts
  src/plugins/vis_type_table/public/index.ts
Labels: vis builder, backport 2.x, v2.5.0, backport 2.5

#3151 [2.x] Add aliased vega-lite v5 dependency and bundle from source
  CHANGELOG.md
  package.json
  packages/osd-babel-preset/common_preset.js
  packages/osd-babel-preset/package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
  src/plugins/vis_type_vega/public/default.spec.hjson
  src/plugins/vis_type_vega/public/lib/vega.js
  src/plugins/vis_type_vega/public/test_utils/default.spec.json
  src/plugins/vis_type_vega/public/test_utils/vegalite_graph.json
  src/plugins/vis_type_vega/public/vega_visualization.test.js
  src/plugins/vis_type_vega/server/usage_collector/get_usage_collector.test.ts
  yarn.lock
Labels: v2.5.0, backport 2.5

#3229 Increment version from 2.5.0 to 2.6.0
  CHANGELOG.md
  package.json
Labels: versioning

#3137 [VisBuilder] Fixes pipeline aggs
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/utils/state_management/handlers/editor_state.ts
  src/plugins/vis_builder/public/application/utils/state_management/handlers/parent_aggs.ts
  src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.ts
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/application/utils/validations/index.ts
  src/plugins/vis_builder/public/application/utils/validations/types.ts
  src/plugins/vis_builder/public/application/utils/validations/validate_aggregations.test.ts
  src/plugins/vis_builder/public/application/utils/validations/validate_aggregations.ts
  src/plugins/vis_builder/public/application/utils/validations/validate_schema_state.test.ts
  src/plugins/vis_builder/public/application/utils/validations/validate_schema_state.ts
  src/plugins/vis_builder/public/application/utils/validations/vis_builder_state_validation.test.ts
  src/plugins/vis_builder/public/application/utils/validations/vis_builder_state_validation.ts
  src/plugins/vis_builder/public/application/utils/vis_builder_state_validation.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
Labels: vis builder, backport 2.x, v2.5.0, backport 2.5

#3240 [Backport 2.x] [Manual] Updated MAINTAINERS.md to match recommended opensearch-project format…
  MAINTAINERS.md
Labels: v2.5.0, autocut

#3234 Add v2.5.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.5.0.md
Labels: docs, backport 2.x, v2.5.0, Skip-Changelog, backport 2.5

#3247 [MD]Update test connection button text
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
Labels: backport 2.x, multiple datasource, v2.5.0, backport 2.5

#3243 Update changelog changes on 2.x branch for 2.5 release
  CHANGELOG.md
Labels: v2.5.0, backport 2.5

#3250 [Backport 2.5] [Manual] Update changelog changes on 2.x branch for 2.5 release (#3243)
  CHANGELOG.md
Labels: v2.5.0, autocut

#3251 Update release notes text and include new changes in the release notes 2.5.0
  release-notes/opensearch-dashboards.release-notes-2.5.0.md
Labels: docs, backport 2.x, v2.5.0, Skip-Changelog, backport 2.5

#3239 [Chore] fix comment typo
  packages/osd-optimizer/src/worker/webpack.config.ts
Labels: v3.0.0, Skip-Changelog

#3274 feat: modify the branch to 2.5
  package.json
Labels: Skip-Changelog

#3207 [Docs] Fix documentation link for date math
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/vis_default_editor/public/components/controls/date_ranges.tsx
Labels: backport 1.x, backport 1.3, backport 2.x, Skip-Changelog, v2.6.0, v1.3.8

#3128 [Manual] [Backport 1.x] Automates chromedriver version selection for tests (#2990)
  .github/workflows/pr_check_workflow.yml
  .gitignore
  CHANGELOG.md
  scripts/upgrade_chromedriver.js
Labels: v1.3.8

#3296 [CI] Fix detection of Chrome's version on Darwin
  CHANGELOG.md
  scripts/upgrade_chromedriver.js
Labels: backport 2.x

#3299 Enhance the Build and Test workflow
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/pr_check_workflow.yml
  CHANGELOG.md
  package.json
  packages/osd-optimizer/src/worker/run_worker.ts
  src/dev/jest/config.js
  src/dev/jest/integration_tests/__fixtures__/test.js
  src/plugins/expressions/common/execution/execution_contract.test.ts
  yarn.lock
Labels: backport 1.3

#3018 [Maintenance] Bumps `re2` and `supertest`
  CHANGELOG.md
  package.json
  src/dev/build/tasks/patch_native_modules_task.test.ts
  src/dev/build/tasks/patch_native_modules_task.ts
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 2.x, v2.6.0, v1.3.8

#3313 Increment 2.5 branch to 2.5.1 after release
  package.json
Labels: Skip-Changelog

#2992 Add disablePrototypePoisoningProtection configuration
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/opensearch/client/client_config.test.ts
  src/core/server/opensearch/client/client_config.ts
  src/core/server/opensearch/opensearch_config.test.ts
  src/core/server/opensearch/opensearch_config.ts
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
Labels: backport 1.x, backport 2.x, v2.6.0, v1.3.8

#3322 [CVE-2022-25901][Partical Backport 1.x]Bump supertest
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3

#3326 [CVE-2022-25901][Partical Backport 1.3]Bump supertest
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, v1.3.8

#3341 [Manual Backport 1.3]Bumps simple-git from 3.4.0 to 3.15.0
  CHANGELOG.md
  package.json
  packages/osd-opensearch/package.json
  yarn.lock
Labels: v1.3.8

#3335 [Manual Backport 1.x][CVE-2022-46175] Update json5 to 1.0.2 and 2.2.3
  CHANGELOG.md
  yarn.lock
Labels: cve, backport 1.3

#3337 [Manual Backport 1.3][CVE-2022-46175] Update json5 to 1.0.2 and 2.2.3
  CHANGELOG.md
  yarn.lock
Labels: v1.3.8

#3345 [CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0
  CHANGELOG.md
  package.json
  packages/osd-opensearch/package.json
  yarn.lock
Labels: cve, backport 1.x, backport 1.3, backport 2.x, v1.3.8, backport 2.5, 2.5.1

#3348 [Manual Backport 2.x][CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0
  CHANGELOG.md
  package.json
  packages/osd-opensearch/package.json
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 2.5

#3338 [1.x] Update MAINTAINERS.md
  MAINTAINERS.md
Labels: backport 1.3, Skip-Changelog

#3346 [1.3] Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Skip-Changelog
