Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-05, with the labels that each got.

#3952 Bump `joi` to v14 to avoid the possibility of prototype poisoning in a nested dependency
  CHANGELOG.md
  package.json
  packages/osd-config-schema/package.json
  packages/osd-test/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, backport 2.7

#3895 bump version
  package.json
Labels: Skip-Changelog

#3968 Bump version to 2.7.1 for 2.7 branch
  package.json
Labels: Skip-Changelog

#3837 [Doc] Add communication guide
  CHANGELOG.md
  COMMUNICATIONS.md
  CONTRIBUTING.md
  DEVELOPER_GUIDE.md
  README.md
Labels: docs, v3.0.0

#3911 Fix wording and duplicate code in embeddable example plugin
  examples/embeddable_examples/public/searchable_list_container/searchable_list_container_component.tsx
  examples/embeddable_explorer/public/list_container_example.tsx
  src/plugins/embeddable/docs/input_and_output_state.md
Labels: Skip-Changelog, distinguished-contributor

#3742 [CVE-2021-35065][1.x] Bump glob-parent from 6.0.0 to 6.0.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.10

#3687 Finalize eligibility check for augmenting visualizations by vis augmenter
  src/plugins/vis_augmenter/public/index.ts
  src/plugins/vis_augmenter/public/test_constants.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_type_vega/public/expressions/__snapshots__/helpers.test.js.snap
  src/plugins/vis_type_vega/public/expressions/helpers.test.js
  src/plugins/vis_type_vega/public/expressions/helpers.ts
  src/plugins/vis_type_vislib/opensearch_dashboards.json
  src/plugins/vis_type_vislib/public/line_to_expression.ts
Labels: feature-anywhere, v2.8.0

#3970 [Manual backport 1.x][CCI] Replace `node` with `scripts/use_node` in functional tests
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/app_link_test/package.json
  test/plugin_functional/plugins/core_app_status/package.json
  test/plugin_functional/plugins/core_plugin_a/package.json
  test/plugin_functional/plugins/core_plugin_appleave/package.json
  test/plugin_functional/plugins/core_plugin_b/package.json
  test/plugin_functional/plugins/core_plugin_chromeless/package.json
  test/plugin_functional/plugins/core_plugin_route_timeouts/package.json
  test/plugin_functional/plugins/core_plugin_static_assets/package.json
  test/plugin_functional/plugins/core_provider_plugin/package.json
  test/plugin_functional/plugins/data_search/package.json
  test/plugin_functional/plugins/doc_views_links_plugin/package.json
  test/plugin_functional/plugins/doc_views_plugin/package.json
  test/plugin_functional/plugins/index_patterns/package.json
  test/plugin_functional/plugins/management_test_plugin/package.json
  test/plugin_functional/plugins/opensearch_client_plugin/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_top_nav/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  test/plugin_functional/plugins/rendering_plugin/package.json
  test/plugin_functional/plugins/ui_settings_plugin/package.json
Labels: backport 1.3, Skip-Changelog, v1.3.10

#3740 [CVE-2022-48285][1.x] Bump jszip from 3.7.1 to 3.10.1
  CHANGELOG.md
  yarn.lock
Labels: cve, backport 1.3, v1.3.10

#3997 [CI] setup Chrome and utilize binary path
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
  scripts/upgrade_chromedriver.js
Labels: distinguished-contributor

#4021 [Dashboards listing] fix listing limit
  CHANGELOG.md
  src/plugins/dashboard/public/application/legacy_app.js
Labels: distinguished-contributor

#3798 [CCI] Fix EUI/OUI type errors
  CHANGELOG.md
  src/plugins/advanced_settings/public/management_app/components/field/field.test.tsx
  src/plugins/advanced_settings/public/management_app/components/form/form.test.tsx
  src/plugins/advanced_settings/public/management_app/components/search/search.test.tsx
  src/plugins/advanced_settings/public/management_app/components/search/search.tsx
  src/plugins/dashboard/public/application/dashboard_empty_screen.test.tsx
  src/plugins/dashboard/public/application/tests/dashboard_container.test.tsx
  src/plugins/data/public/ui/shard_failure_modal/shard_failure_open_modal_button.test.tsx
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/discover/public/application/angular/context/components/action_bar/action_bar.test.tsx
  src/plugins/discover/public/application/angular/doc_table/components/pager/tool_bar_pager_buttons.test.tsx
  src/plugins/discover/public/application/angular/doc_table/components/table_header/table_header.test.tsx
  src/plugins/discover/public/application/components/context_error_message/context_error_message.test.tsx
  src/plugins/discover/public/application/components/doc/doc.test.tsx
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer.test.tsx
  src/plugins/discover/public/application/components/hits_counter/hits_counter.test.tsx
  src/plugins/discover/public/application/components/loading_spinner/loading_spinner.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_search.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.test.tsx
  src/plugins/discover/public/application/components/table/table.test.tsx
  src/plugins/discover/public/application/components/timechart_header/timechart_header.test.tsx
  src/plugins/embeddable/public/lib/embeddables/embeddable_root.test.tsx
  src/plugins/embeddable/public/lib/panel/embeddable_panel.test.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_flyout.test.tsx
  src/plugins/input_control_vis/public/components/editor/controls_tab.test.tsx
  src/plugins/input_control_vis/public/components/editor/list_control_editor.test.tsx
  src/plugins/input_control_vis/public/components/editor/range_control_editor.test.tsx
  src/plugins/input_control_vis/public/components/vis/input_control_vis.test.tsx
Labels: CCI, first-time-contributor

#3978 [CCI] Fix bottom bar visibility using createPortal
  CHANGELOG.md
  src/core/public/rendering/_base.scss
  src/core/public/rendering/app_containers.test.tsx
  src/core/public/rendering/app_containers.tsx
  src/plugins/advanced_settings/public/management_app/_advanced_settings.scss
  src/plugins/advanced_settings/public/management_app/components/form/form.test.tsx
  src/plugins/advanced_settings/public/management_app/components/form/form.tsx
Labels: backport 2.x, v2.8.0, CCI, first-time-contributor

#4040 Adds threshold to code coverage changes for project
  .github/.codecov.yml
  CHANGELOG.md
Labels: distinguished-contributor

#4042 Updates PR template for screenshots and test instructions
  .github/pull_request_template.md
Labels: devex, Skip-Changelog, distinguished-contributor

#3908 Replace `re2` with RegExp in timeline and add unit tests
  CHANGELOG.md
  package.json
  src/dev/build/tasks/patch_native_modules_task.test.ts
  src/dev/build/tasks/patch_native_modules_task.ts
  src/plugins/vis_type_timeline/server/series_functions/label.js
  src/plugins/vis_type_timeline/server/series_functions/label.test.js
  yarn.lock
Labels: enhancement, backport 1.x, backport 2.x, technical debt, v2.8.0

#4006 Add a `VisAugmenter` stats API
  src/plugins/vis_augmenter/common/augment_vis_saved_object_attributes.ts
  src/plugins/vis_augmenter/common/constants.ts
  src/plugins/vis_augmenter/common/index.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/_saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/types.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/test_helpers.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/server/plugin.ts
  src/plugins/vis_augmenter/server/routes/stats.ts
  src/plugins/vis_augmenter/server/routes/stats_helpers.test.ts
  src/plugins/vis_augmenter/server/routes/stats_helpers.ts
  src/plugins/vis_augmenter/server/saved_objects/augment_vis.ts
Labels: feature-anywhere, v2.8.0, valued-contributor

#4045 Bump highlight.js from 9.18.5 to 10.7.3 to solve security concerns
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: security fix, backport 1.x, backport 1.3, v1.3.10

#4060 Add 1.3.10 release note
  release-notes/opensearch-dashboards.release-notes-1.3.10.md
Labels: Skip-Changelog

#3957 [Multiple Datasource] Support Amazon OpenSearch Serverless
  CHANGELOG.md
  config/opensearch_dashboards.yml
  package.json
  packages/osd-opensearch/package.json
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/types.ts
  yarn.lock
Labels: ux / ui, backport 2.x, multiple datasource, v2.8.0, all-star-contributor

#4066 [Backport 2.x][Multiple Datasource] Support Amazon OpenSearch Serverless (#3957)
  config/opensearch_dashboards.yml
  package.json
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/types.ts
  yarn.lock
Labels: multiple datasource, Skip-Changelog, v2.8.0

#4110 Remove Sass from `tile_map` plugin
  CHANGELOG.md
  src/plugins/tile_map/public/_tile_map.scss
  src/plugins/tile_map/public/index.scss
Labels: v3.0.0, first-time-contributor

#3954 Design for New Saved Object Service Interface for Custom Repository
  CHANGELOG.md
  docs/saved_objects/img/current_saved_object_service_workflow.png
  docs/saved_objects/img/proposed_saved_object_service_workflow.png
  docs/saved_objects/resources/current_saved_object_service_workflow.puml
  docs/saved_objects/resources/proposed_saved_object_service_workflow.puml
  docs/saved_objects/saved_object_repository_factory_design.md
Labels: docs, repeat-contributor

#4120 showing default tooltip on mark
  src/plugins/vis_augmenter/public/constants.ts
  src/plugins/vis_augmenter/public/vega/helpers.ts
Labels: first-time-contributor

#4123 Support formatted tooltip for event marks
  src/plugins/vis_augmenter/public/test_constants.ts
  src/plugins/vis_augmenter/public/types.ts
  src/plugins/vis_augmenter/public/vega/helpers.test.ts
  src/plugins/vis_augmenter/public/vega/helpers.ts
Labels: valued-contributor

#3961 Add new advanced settings for vis augmenter
  config/opensearch_dashboards.yml
  src/plugins/opensearch_dashboards_usage_collection/server/collectors/management/schema.ts
  src/plugins/telemetry/schema/oss_plugins.json
  src/plugins/vis_augmenter/common/constants.ts
  src/plugins/vis_augmenter/config.ts
  src/plugins/vis_augmenter/public/plugin.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
  src/plugins/vis_augmenter/public/services.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_augmenter/server/index.ts
  src/plugins/vis_augmenter/server/plugin.ts
  src/plugins/visualizations/public/embeddable/create_vis_embeddable_from_object.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
  src/plugins/visualizations/public/services.ts
Labels: feature-anywhere, v2.8.0

#3924 enhance grouping for context menu options
  CHANGELOG.md
  examples/ui_actions_explorer/public/context_menu_examples/context_menu_examples.tsx
  src/plugins/ui_actions/public/actions/action.ts
  src/plugins/ui_actions/public/actions/action_internal.ts
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.test.ts
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.tsx
Labels: backport 2.x, feature-anywhere, v2.8.0, first-time-contributor

#4137 Adding Tao and Zilong to MAINTAINERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: repeat-contributor

#4126 [MD]Severless Support: update `data-test-subj`attribute for functional tests & fix bug in edit flow
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
Labels: backport 2.x, multiple datasource, Skip-Changelog, v2.8.0, all-star-contributor

#3955 Use `exec` in the CLI shell scripts to prevent new process creation
  CHANGELOG.md
  scripts/use_node
  src/dev/build/tasks/bin/scripts/opensearch-dashboards
  src/dev/build/tasks/bin/scripts/opensearch-dashboards-plugin
Labels: backport 2.x, distinguished-contributor

#4139 [Feature Anywhere] Expose external services to helper fns
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
Labels: feature-anywhere, v2.8.0, seasoned-contributor

#4171 chore (lychee): Add company.net to exclusion list
  .lycheeexclude
Labels: backport 1.x, backport 2.x, Skip-Changelog, v2.8.0, v1.3.11, backport 2.8

#4151 Bundle Node 14 as a fallback for operating systems that cannot run Node 18
  CHANGELOG.md
  scripts/use_node
  src/dev/build/tasks/create_archives_sources_task.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.ts
  src/dev/build/tasks/nodejs/node_download_info.ts
Labels: backport 2.x, v2.8.0, distinguished-contributor, backport 2.8

#4179 [MD] Update authentication helper text in create data source flow
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
Labels: backport 2.x, multiple datasource, Skip-Changelog, v2.8.0, all-star-contributor, backport 2.8

#4188 [CI] skip checksum verification for cypress tests
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x, v2.8.0, distinguished-contributor, backport 2.8
