Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-04, with the labels that each got.

#3721 Add an achievement badger to the PR
  .github/workflows/github-workflow-badger.yml
  CHANGELOG.md
Labels: ci

#3730 Updates the PR template to give an example linking issues with PR's
  .github/pull_request_template.md
Labels: backport 2.x, devex, Skip-Changelog

#3762 [FIX]gitignore
  .gitignore
Labels: backport 1.x, backport 1.3, backport 2.x, Skip-Changelog, v2.7.0, v1.3.10, CCI

#3726 [CVE-2022-25858][1.x]Bump terser from 4.8.0 to 4.8.1
  CHANGELOG.md
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3727 [CVE-2022-25758][1.x]Bump scss-tokenizer from 0.3.0 to 0.4.3
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3693 [Multiple DataSource]Refactor authentication type selection in create and edit data source forms
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/types.ts
Labels: refactor, backport 2.x, multiple datasource, v2.7.0

#3755 [Multiple Datasource] Remove experimental banner & badge
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
  src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/index.ts
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.tsx
  src/plugins/index_pattern_management/public/components/experimental_callout/index.ts
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Labels: backport 2.x, multiple datasource, Skip-Changelog, v2.7.0

#3604 [MD]Allow create and distinguish index pattern with same name but from different datasources
  CHANGELOG.md
  src/plugins/data/common/index_patterns/fields/utils.test.ts
  src/plugins/data/common/index_patterns/index.ts
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
  src/plugins/data/common/index_patterns/utils.test.ts
  src/plugins/data/common/index_patterns/utils.ts
  src/plugins/data/opensearch_dashboards.json
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/discover/public/application/components/sidebar/discover_index_pattern.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
  src/plugins/saved_objects/public/finder/saved_object_finder.tsx
  src/plugins/saved_objects_management/server/routes/find.ts
Labels: backport 2.x, multiple datasource, v2.7.0

#3754 [Multiple DataSource] Integrate multiple datasource with dev tool console
  CHANGELOG.md
  src/core/public/application/types.ts
  src/plugins/console/opensearch_dashboards.json
  src/plugins/console/public/application/containers/editor/editor.tsx
  src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.tsx
  src/plugins/console/public/application/containers/main/main.tsx
  src/plugins/console/public/application/containers/settings.tsx
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.ts
  src/plugins/console/public/application/index.tsx
  src/plugins/console/public/application/stores/request.ts
  src/plugins/console/public/lib/mappings/mappings.js
  src/plugins/console/public/lib/opensearch/opensearch.ts
  src/plugins/console/public/plugin.ts
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
  src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/mocks.ts
  src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
  src/plugins/console/server/routes/api/console/proxy/utils.ts
  src/plugins/console/server/routes/api/console/proxy/validation_config.ts
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/dev_tools/opensearch_dashboards.json
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/index.scss
  src/plugins/dev_tools/public/plugin.ts
Labels: backport 2.x, multiple datasource, v2.7.0, console

#3764 Update DEVELOPER_GUIDE.md
  CHANGELOG.md
  DEVELOPER_GUIDE.md
Labels: backport 2.x, CCI

#3686 Add delimiter for list of values
  CHANGELOG.md
  src/plugins/data/public/ui/filter_bar/filter_editor/phrases_values_input.tsx
Labels: backport 2.x, v2.7.0, CCI

#3738 [CVE-2021-23490][1.x] Bump parse-link-header from 1.0.1 to 2.0.0
  CHANGELOG.md
  packages/osd-test/package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3792 Update MAINTAINERS.md and CODEOWNERS
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 1.x, backport 1.3, backport 2.x, Skip-Changelog, v2.7.0, v1.3.10

#3816 Fix: Data Table rendering only in a small scrollable portion of the screen
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_app.scss
Labels: tableVis, v2.7.0, CCI, first-time-contributor

#3641 [CCI][#3590]Indicate that IE is no longer supported
  CHANGELOG.md
  src/core/public/chrome/chrome_service.tsx
Labels: backport 2.x, v2.7.0, CCI

#3685 [Doc Links Service] Clean up noDocumentation links
  CHANGELOG.md
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/timeline/public/components/timeline_deprecation.tsx
  src/plugins/visualize/public/application/utils/utils.ts
Labels: backport 2.x, v2.7.0, CCI

#3847 Remove unused url
  CHANGELOG.md
  src/plugins/discover/public/application/angular/doc_table/create_doc_table_react.tsx
  src/plugins/discover/public/application/doc_views/doc_views_helpers.tsx
Labels: first-time-contributor

#3676 Add satisfaction survey link to help menu
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/constants.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.test.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/injected_metadata/injected_metadata_service.mock.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/template.test.tsx
  src/legacy/server/config/schema.js
Labels: backport 2.x, v2.7.0

#3797 Fix: Update button position when number of rows per page is large
  CHANGELOG.md
  src/plugins/vis_type_table/public/utils/use_pagination.ts
Labels: tableVis, v2.7.0, CCI, first-time-contributor

#3806 [Console][Multiple Datasource]Fine tuned dev tool datasource selector UI
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/index.scss
Labels: ux / ui, backport 2.x, multiple datasource, Skip-Changelog, v2.7.0, console, all-star-contributor

#3842 Bump xml2js from 0.4.23 to 0.5.0
  CHANGELOG.md
  package.json
  packages/osd-test/package.json
  yarn.lock
Labels: v2.7.0, first-time-contributor

#3783 [CCI] Replace `node` with `scripts/use_node` in functional tests
  CHANGELOG.md
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/app_link_test/package.json
  test/plugin_functional/plugins/core_app_status/package.json
  test/plugin_functional/plugins/core_plugin_a/package.json
  test/plugin_functional/plugins/core_plugin_appleave/package.json
  test/plugin_functional/plugins/core_plugin_b/package.json
  test/plugin_functional/plugins/core_plugin_chromeless/package.json
  test/plugin_functional/plugins/core_plugin_route_timeouts/package.json
  test/plugin_functional/plugins/core_plugin_static_assets/package.json
  test/plugin_functional/plugins/core_provider_plugin/package.json
  test/plugin_functional/plugins/data_search/package.json
  test/plugin_functional/plugins/doc_views_links_plugin/package.json
  test/plugin_functional/plugins/doc_views_plugin/package.json
  test/plugin_functional/plugins/index_patterns/package.json
  test/plugin_functional/plugins/management_test_plugin/package.json
  test/plugin_functional/plugins/opensearch_client_plugin/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_top_nav/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  test/plugin_functional/plugins/rendering_plugin/package.json
  test/plugin_functional/plugins/ui_settings_plugin/package.json
Labels: backport 1.x, backport 1.3, backport 2.x, v2.7.0, v1.3.10, CCI, first-time-contributor

#3732 [VisBuilder] 2 way communication using UI actions and bug fixes
  CHANGELOG.md
  src/plugins/vis_builder/opensearch_dashboards.json
  src/plugins/vis_builder/public/application/app.tsx
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/utils/get_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/handle_vis_event.test.ts
  src/plugins/vis_builder/public/application/utils/handle_vis_event.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/plugin_services.ts
  src/plugins/vis_builder/public/saved_visualizations/saved_visualization_references.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.test.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.ts
  src/plugins/vis_builder/public/types.ts
Labels: vis builder, backport 2.x, v2.7.0

#3854 resolved get_keystore unit test
  CHANGELOG.md
  src/cli_keystore/get_keystore.test.js
Labels: backport 2.x, v2.7.0, CCI, first-time-contributor

#3747 Add docker files and instructions for debugging Selenium functional tests
  CHANGELOG.md
  TESTING.md
  dev-tools/install-docker-dev.sh
  docs/docker-dev/Dockerfile.selenium
  docs/docker-dev/docker-compose.selenium.yml
  docs/docker-dev/docker-dev-setup-manual.md
  docs/docker-dev/start-vnc.sh
Labels: docs, backport 2.x, v2.7.0

#3643 Omit adding the `osd-version` header when the Fetch request is to an external origin
  CHANGELOG.md
  src/core/public/http/fetch.ts
  src/core/public/ui_settings/__snapshots__/ui_settings_api.test.ts.snap
  src/core/server/http/integration_tests/lifecycle_handlers.test.ts
  src/core/server/http/lifecycle_handlers.test.ts
  src/core/server/http/lifecycle_handlers.ts
  src/plugins/bfetch/public/plugin.ts
  src/plugins/opensearch_dashboards_legacy/public/angular/angular_config.tsx
Labels: backport 2.x, v2.7.0

#3397 [Table Vis] move format table logic to table render and consolidate types
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_app.scss
  src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_app.tsx
  src/plugins/vis_type_table/public/components/table_vis_cell.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_cell.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_component_group.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
  src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
  src/plugins/vis_type_table/public/table_vis_fn.ts
  src/plugins/vis_type_table/public/table_vis_renderer.test.tsx
  src/plugins/vis_type_table/public/table_vis_response_handler.test.ts
  src/plugins/vis_type_table/public/table_vis_response_handler.ts
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/utils/__snapshots__/add_percentage_col.test.ts.snap
  src/plugins/vis_type_table/public/utils/add_percentage_col.test.ts
  src/plugins/vis_type_table/public/utils/add_percentage_col.ts
  src/plugins/vis_type_table/public/utils/convert_to_csv_data.test.ts
  src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts
  src/plugins/vis_type_table/public/utils/convert_to_formatted_data.test.ts
  src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
  src/plugins/vis_type_table/public/utils/get_table_ui_state.test.ts
  src/plugins/vis_type_table/public/utils/get_table_ui_state.ts
  src/plugins/vis_type_table/public/utils/index.ts
  src/plugins/vis_type_table/public/utils/use_pagination.test.ts
  src/plugins/vis_type_table/public/utils/use_pagination.ts
Labels: backport 2.x, tableVis, v2.7.0

#3752 Adds toast ID to toast api
  CHANGELOG.md
  src/core/public/notifications/toasts/toasts_api.test.ts
  src/core/public/notifications/toasts/toasts_api.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/plugin.ts
Labels: vis builder, backport 2.x, v2.7.0

#3626 Add tooltip to help icon
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
Labels: backport 1.x, backport 1.3, backport 2.x, v2.7.0, v1.3.10, CCI

#3862 [Dashboards Listing] Fix edit button
  src/plugins/dashboard/public/application/application.ts
  src/plugins/dashboard/public/application/legacy_app.js
Labels: backport 2.x, Skip-Changelog, v2.7.0, distinguished-contributor

#3869 [2.x Backport][Table Vis] move format table, consolidate types and add unit tests
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_app.scss
  src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_app.tsx
  src/plugins/vis_type_table/public/components/table_vis_cell.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_cell.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
  src/plugins/vis_type_table/public/components/table_vis_component_group.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
  src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
  src/plugins/vis_type_table/public/table_vis_fn.ts
  src/plugins/vis_type_table/public/table_vis_renderer.test.tsx
  src/plugins/vis_type_table/public/table_vis_response_handler.test.ts
  src/plugins/vis_type_table/public/table_vis_response_handler.ts
  src/plugins/vis_type_table/public/types.ts
  src/plugins/vis_type_table/public/utils/__snapshots__/add_percentage_col.test.ts.snap
  src/plugins/vis_type_table/public/utils/add_percentage_col.test.ts
  src/plugins/vis_type_table/public/utils/add_percentage_col.ts
  src/plugins/vis_type_table/public/utils/convert_to_csv_data.test.ts
  src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts
  src/plugins/vis_type_table/public/utils/convert_to_formatted_data.test.ts
  src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
  src/plugins/vis_type_table/public/utils/get_table_ui_state.test.ts
  src/plugins/vis_type_table/public/utils/get_table_ui_state.ts
  src/plugins/vis_type_table/public/utils/index.ts
  src/plugins/vis_type_table/public/utils/use_pagination.test.ts
  src/plugins/vis_type_table/public/utils/use_pagination.ts
Labels: v2.7.0

#3751 [VisBuilder] Adds UIState to vis, adds index patterns to embeddable, bug fixes
  CHANGELOG.md
  src/plugins/vis_builder/common/vis_builder_saved_object_attributes.ts
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/application/utils/schema.json
  src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts
  src/plugins/vis_builder/public/application/utils/state_management/preload.ts
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.ts
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/state_management/ui_state_slice.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/saved_visualizations/_saved_vis.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.test.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.ts
  src/plugins/vis_builder/public/types.ts
  src/plugins/vis_builder/server/saved_objects/vis_builder_app.ts
Labels: vis builder, backport 2.x, v2.7.0

#3870 [Manual Backport 2.x] Add tooltip to help icon (#3626)
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
Labels: autocut, v2.7.0

#3796 [FIX] Dashboard list integrated delete
  src/plugins/dashboard/public/application/application.ts
  src/plugins/dashboard/public/application/legacy_app.js
  src/plugins/dashboard/public/plugin.tsx
Labels: backport 2.x, Skip-Changelog, v2.7.0, first-time-contributor

#3879 Chore: Updates branch name
  package.json
Labels: Skip-Changelog, v2.7.0

#3884 Bump OUI to 1.1.1
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/__snapshots__/update_password_modal.test.tsx.snap
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, v2.7.0, distinguished-contributor, backport 2.7

#3875 Update 2.x changelog and create 2.7.0 release notes
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.7.0.md
Labels: v2.7.0, backport 2.7

#3889 [Forwardport main] Add 2.7.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.7.0.md
Labels: Skip-Changelog, v2.7.0, distinguished-contributor

#3896 Chore (release notes): polish 2.7.0 notes
  release-notes/opensearch-dashboards.release-notes-2.7.0.md
Labels: backport 2.x, Skip-Changelog, v2.7.0, distinguished-contributor, backport 2.7

#3871 [Manual Backport 1.x] Add tooltip to help icon
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
Labels: autocut, v1.3.10

#3872 [Manual Backport 1.3] Add tooltip to help icon (#3626)
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
Labels: autocut, v1.3.10

#3910 Fix header icon
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/header_help_menu.tsx
Labels: Skip-Changelog, v2.7.0

#3912 Add server side private IP blocking for data source endpoints validation
  .lycheeexclude
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/util/endpoint_validator.test.js
  src/plugins/data_source/server/util/endpoint_validator.ts
Labels: all-star-contributor

#3931 Docs (Jest): Update jest documentation links
  packages/opensearch-eslint-config-opensearch-dashboards/README.md
  scripts/jest.js
  scripts/jest_integration.js
  src/dev/jest/junit_reporter.js
Labels: backport 1.x, backport 2.x, Skip-Changelog, v2.8.0, v1.3.10, distinguished-contributor

#3929 Revert "[CCI] Replace jquery usage in console plugin with native methods"
  CHANGELOG.md
  src/plugins/console/public/application/models/legacy_core_editor/__tests__/input.test.js
  src/plugins/console/public/application/models/legacy_core_editor/__tests__/output_tokenization.test.js
  src/plugins/console/public/application/models/legacy_core_editor/legacy_core_editor.ts
  src/plugins/console/public/application/models/sense_editor/__tests__/integration.test.js
  src/plugins/console/public/application/models/sense_editor/__tests__/sense_editor.test.js
  src/plugins/console/public/application/models/sense_editor/sense_editor.test.mocks.ts
  src/plugins/console/public/lib/ace_token_provider/token_provider.test.ts
  src/plugins/console/public/lib/osd/osd.js
Labels: backport 2.x, v2.7.0, distinguished-contributor, backport 2.7

#3894 [Manual Backport 1.x] Update MAINTAINERS.md and CODEOWNERS
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 1.3, Skip-Changelog, v1.3.10

#3922 [BUG][Dashboard listing] push to history if dashboard otherwise nav
  src/plugins/dashboard/public/application/legacy_app.js
  src/plugins/dashboard/public/application/listing/create_button.test.tsx
  src/plugins/dashboard/public/application/listing/create_button.tsx
  test/plugin_functional/config.ts
  test/plugin_functional/plugins/dashboard_listing_test_plugin/opensearch_dashboards.json
  test/plugin_functional/plugins/dashboard_listing_test_plugin/package.json
  test/plugin_functional/plugins/dashboard_listing_test_plugin/public/index.ts
  test/plugin_functional/plugins/dashboard_listing_test_plugin/public/plugin.tsx
  test/plugin_functional/plugins/dashboard_listing_test_plugin/tsconfig.json
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
  test/plugin_functional/test_suites/dashboard_listing_plugin/index.ts
Labels: backport 2.x, Skip-Changelog, v2.7.0, backport 2.7

#3930 remove jquery console release note
  release-notes/opensearch-dashboards.release-notes-2.7.0.md
Labels: backport 2.x, Skip-Changelog, v2.7.0, distinguished-contributor, backport 2.7

#3770 [CCI] Update js-yaml to v4.0.5
  CHANGELOG.md
  package.json
  packages/osd-apm-config-loader/package.json
  packages/osd-apm-config-loader/src/utils/read_config.ts
  packages/osd-config/package.json
  packages/osd-config/src/raw/read_config.ts
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/limits.ts
  src/cli/serve/integration_tests/reload_logging_config.test.ts
  src/dev/stylelint/lint_files.js
  src/plugins/telemetry/server/collectors/usage/telemetry_usage_collector.ts
  tasks/function_test_groups.js
  yarn.lock
Labels: v3.0.0, CCI

#3649 Add VisLayer error toasts when rendering vis
  src/core/public/notifications/toasts/toasts_api.tsx
  src/plugins/vis_augmenter/public/index.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/test_helpers.ts
  src/plugins/vis_augmenter/public/types.test.ts
  src/plugins/vis_augmenter/public/types.ts
  src/plugins/vis_augmenter/public/utils/index.ts
  src/plugins/vis_augmenter/public/utils/test_helpers.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
  src/plugins/visualizations/public/plugin.ts
  src/plugins/visualizations/public/services.ts
Labels: visualizations, unified visualization UX, feature-anywhere, v2.8.0

#3788 Update README.md
  README.md
Labels: Skip-Changelog, first-time-contributor

#3947 [CVE-2023-2251] Bump yaml to 2.2.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 2.x, all-star-contributor
