Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-03, with the labels that each got.

#3489 Remove the unused `renovate.json5` file
  CHANGELOG.md
  renovate.json5
Labels: backport 1.x, backport 2.x

#3446 [Manual backport 1.x][CVE-2023-25653] Bump node-jose to 2.2.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3535 [CVE-2021-23807] Bump jsonpointer from 4.1.0 to 5.0.1
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3, v1.3.9

#3538 Update caniuse to fix failed integration tests
  CHANGELOG.md
  yarn.lock
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, v2.7.0, v1.3.9, backport 2.6

#3533 [CVE-2023-26486][CVE-2023-26487] Bump vega from 5.22.1 to 5.23.0
  CHANGELOG.md
  package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/vis_type_vega/public/__snapshots__/vega_visualization.test.js.snap
  yarn.lock
Labels: cve, backport 1.x, backport 1.3, backport 2.x, v2.7.0, v1.3.9, backport 2.6

#3537 [Dev] enable `opensearch snapshot` for Darwin
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
Labels: backport 1.x, backport 1.3, backport 2.x, v2.7.0, v1.3.9, backport 2.6

#3547 [Backport][2.x] Update caniuse to fix failed integration tests (#3538)
  CHANGELOG.md
  yarn.lock
Labels: backport 1.x, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3328 Simplifies `re2` upgrade instructions
  CHANGELOG.md
  src/dev/build/tasks/patch_native_modules_task.ts
Labels: backport 1.x, backport 1.3, backport 2.x, v2.7.0, v1.3.9

#3539 [Manual Backport 1.x] [CVE-2020-36632] Bump flat from 4.1.1 to 5.0.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3, v1.3.9

#3536 [CVE-2021-23424] Bump ansi-html from 0.0.7 to 0.0.8
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3, v1.3.9

#3549 [Manual Backport 2.x][CVE-2023-26486][CVE-2023-26487] Bump vega from 5.22.1 to 5.23.0
  CHANGELOG.md
  package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/vis_type_vega/public/__snapshots__/vega_visualization.test.js.snap
  yarn.lock
Labels: backport 2.6

#3548 [Backport][2.x] [Dev] enable `opensearch snapshot` for Darwin (#3537)
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
Labels: backport 1.x, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3562 [Manual Backport 1.x] docs(DEVELOPER_GUIDE): Make getting started comprehensive and reorgan…
  CHANGELOG.md
  DEVELOPER_GUIDE.md
Labels: backport 1.3, v1.3.9

#3561 [Manual Backport 1.x] Simplifies `re2` upgrade instructions (#3328)
  CHANGELOG.md
  src/dev/build/tasks/patch_native_modules_task.ts
Labels: backport 1.3, v1.3.9

#3302 Improved typings
  src/core/CONVENTIONS.md
Labels: backport 2.x, Skip-Changelog, v2.7.0

#3131 Add logic to collect `VisLayer`s in line chart render flow
  src/plugins/vis_augmenter/common/types.ts
  src/plugins/vis_augmenter/public/expressions/index.ts
  src/plugins/vis_augmenter/public/expressions/types.ts
  src/plugins/vis_augmenter/public/index.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/index.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/types.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/test_helpers.ts
  src/plugins/vis_augmenter/public/types.test.ts
  src/plugins/vis_augmenter/public/types.ts
  src/plugins/vis_augmenter/public/utils/index.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/visualizations/opensearch_dashboards.json
  src/plugins/visualizations/public/embeddable/create_vis_embeddable_from_object.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
  src/plugins/visualizations/public/legacy/build_pipeline.ts
  src/plugins/visualizations/public/services.ts
Labels: Skip-Changelog, v2.8.0

#3563 [Manual Backport 1.3] [CVE-2022-24999] Bump express from 4.17.1 to 4.18.2 (#3542)
  CHANGELOG.md
  package.json
  yarn.lock
Labels: v1.3.9

#3576 [1.x] Chore: Add release notes for 1.3.9
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-1.3.9.md
Labels: backport 1.3, v1.3.9

#3585 Chore: Update changelog for 1.3.9 release
  CHANGELOG.md
Labels: v1.3.9

#3578 [Manual Backport][2.6] [Dev] enable `opensearch snapshot` for Darwin (#3537)
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  packages/osd-opensearch/src/artifact.js
  packages/osd-opensearch/src/artifact.test.js
Labels: not in release

#3452 [Manual backport 2.x]Updates NOTICE file, adds validation to GitHub CI & Corrects NOTICE f…
  .github/workflows/build_and_test_workflow.yml
  NOTICE.txt
  package.json
  src/dev/build/tasks/notice_file_task.ts
  src/dev/notice/cli.js
  src/dev/notice/generate_notice_from_source.ts
Labels: Skip-Changelog, v2.7.0

#3495 [Vis Builder] Add metric to metric, bucket to bucket aggregation persistence
  CHANGELOG.md
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/utils/mocks.ts
  src/plugins/vis_builder/public/application/utils/state_management/shared_actions.ts
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
  src/plugins/vis_builder/public/application/utils/use/use_persisted_agg_params.test.tsx
  src/plugins/vis_builder/public/application/utils/use/use_persisted_agg_params.ts
Labels: vis builder

#3453 [Manual backport 1.x] Updates NOTICE file, adds validation to GitHub CI & Corrects NOTICE f…
  .github/workflows/build_and_test_workflow.yml
  NOTICE.txt
  package.json
  src/dev/build/tasks/notice_file_task.ts
  src/dev/notice/cli.js
  src/dev/notice/generate_notice_from_source.ts
Labels: backport 1.3, Skip-Changelog, v1.3.10

#3444 Add docker dev set up instruction
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  dev-tools/install-docker-dev.sh
  docs/docker-dev/docker-compose.yml
  docs/docker-dev/docker-dev-setup-manual.md
  docs/docker-dev/entrypoint.sh
  package.json
Labels: docs

#3514 ci: reduce redundancy by using matrix strategy on Windows and Linux workflows
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x, v2.7.0

#3613 [Forwardport main] Add 1.3.9 release notes
  release-notes/opensearch-dashboards.release-notes-1.3.9.md
Labels: Skip-Changelog

#3424 Add json worker to monaco editor
  CHANGELOG.md
  packages/osd-monaco/README.md
  packages/osd-monaco/src/index.ts
  packages/osd-monaco/src/json/index.ts
  packages/osd-monaco/src/json/worker/json.worker.ts
  packages/osd-monaco/src/monaco_environment.ts
  packages/osd-monaco/src/worker_store.ts
  packages/osd-monaco/src/xjson/language.ts
  packages/osd-monaco/webpack.config.js
Labels: backport 2.x, v2.7.0

#3609 [Manual Backport 2.x][CI] Reduce redundancy by using matrix strategy on workflows (#3514)
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
Labels: v2.7.0, backport 2.6

#3614 [Doc] UI actions explorer
  CHANGELOG.md
  examples/developer_examples/public/app.tsx
  examples/expressions_example/public/components/explorer_tab.tsx
  examples/state_containers_examples/public/plugin.ts
  examples/ui_actions_explorer/public/app.tsx
  examples/ui_actions_explorer/public/basic_tab.tsx
  examples/ui_actions_explorer/public/explorer_tab.tsx
  examples/ui_actions_explorer/public/plugin.tsx
  examples/ui_actions_explorer/public/trigger_context_example.tsx
  examples/ui_actions_explorer/public/types.ts
  src/plugins/ui_actions/README.md
  src/plugins/ui_actions/public/service/ui_actions_service.ts
Labels: backport 2.x, v2.7.0

#3508 Allow selecting the Node.js binary OSD uses
  CHANGELOG.md
  package.json
  packages/osd-ace/package.json
  packages/osd-analytics/package.json
  packages/osd-dev-utils/src/precommit_hook/script_source.ts
  packages/osd-i18n/package.json
  packages/osd-interpreter/package.json
  packages/osd-monaco/package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch/package.json
  packages/osd-plugin-generator/package.json
  packages/osd-plugin-generator/template/package.json.ejs
  packages/osd-plugin-helpers/package.json
  packages/osd-ui-shared-deps/package.json
  scripts/use_node
  scripts/use_node.bat
  src/dev/build/tasks/bin/copy_bin_scripts_task.ts
  src/dev/build/tasks/bin/scripts/opensearch-dashboards
  src/dev/build/tasks/bin/scripts/opensearch-dashboards-keystore
  src/dev/build/tasks/bin/scripts/opensearch-dashboards-keystore.bat
  src/dev/build/tasks/bin/scripts/opensearch-dashboards-plugin
  src/dev/build/tasks/bin/scripts/opensearch-dashboards-plugin.bat
  src/dev/build/tasks/bin/scripts/opensearch-dashboards.bat
  src/dev/ci_setup/setup.sh
  src/dev/ci_setup/setup_percy.sh
  src/setup_node_env/node_version_validator.test.js
  tasks/config/run.js
Labels: backport 2.x, v2.7.0

#3570 Cleanup and rebuild @osd/pm
  .lycheeexclude
  CHANGELOG.md
  packages/osd-pm/.babelrc
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/webpack.config.js
  yarn.lock
Labels: backport 2.x, v2.7.0

#3544 Refactor dev tool console to use opensearch-js client to send request
  CHANGELOG.md
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
  src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/headers.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/params.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/proxy_fallback.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
Labels: refactor, backport 2.x, multiple datasource, v2.7.0

#3633 [CCI] Adding second command to Install yarn step in Developer Guide
  DEVELOPER_GUIDE.md
Labels: backport 2.x, Skip-Changelog, v2.7.0, CCI

#3483 Add downgrade logic for branch in DocLinkService
  CHANGELOG.md
  src/core/public/doc_links/doc_links_service.test.ts
  src/core/public/doc_links/doc_links_service.ts
Labels: backport 2.x, v2.7.0

#3678 Bump styled-components from 5.3.5 to 5.3.9
  CHANGELOG.md
  packages/osd-babel-preset/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: dependencies, backport 2.x, v2.7.0

#3605 [Geospatial] Add new geo shape filter field to support geospatial search query
  CHANGELOG.md
  src/plugins/data/common/opensearch_query/filters/geo_shape_filter.test.ts
  src/plugins/data/common/opensearch_query/filters/geo_shape_filter.ts
  src/plugins/data/common/opensearch_query/filters/get_filter_field.ts
  src/plugins/data/common/opensearch_query/filters/index.ts
  src/plugins/data/common/opensearch_query/filters/types.ts
Labels: backport 2.x, v2.7.0

#2910 [Refactor] Replace url parse format resolve with whatwg url
  CHANGELOG.md
  examples/url_generators_examples/public/url_generator.ts
  packages/osd-dev-utils/src/osd_client/osd_client_requester.ts
  packages/osd-opensearch-archiver/src/cli.ts
  packages/osd-test/src/failed_tests_reporter/github_api.ts
  packages/osd-test/src/functional_test_runner/lib/config/config.ts
  packages/osd-test/src/functional_test_runner/lib/config/schema.ts
  packages/osd-test/src/functional_test_runner/lib/docker_servers/docker_servers_service.ts
  packages/osd-test/src/legacy_opensearch/legacy_opensearch_test_cluster.js
  packages/osd-test/src/legacy_opensearch/opensearch_test_config.js
  packages/osd-test/src/osd/osd_test_config.ts
  src/cli/serve/serve.js
  src/cli_plugin/install/download.js
  src/core/public/application/utils/parse_app_url.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/header_logo.tsx
  src/core/public/chrome/ui/header/home_loader.tsx
  src/core/server/http/base_path_proxy_server.ts
  src/core/server/http/http_server.mocks.ts
  src/core/server/http/http_server.ts
  src/core/server/http/https_redirect_server.ts
  src/core/server/opensearch/legacy/opensearch_client_config.ts
  src/plugins/console/server/lib/opensearch_proxy_config.ts
  src/plugins/console/server/lib/proxy_config.ts
  src/plugins/maps_legacy/public/map/service_settings.test.js
  src/plugins/share/public/components/url_panel_content.test.tsx
  src/plugins/share/public/components/url_panel_content.tsx
  src/plugins/share/public/lib/url_shortener.ts
  src/test_utils/get_url.js
  src/test_utils/get_url.test.ts
  test/api_integration/services/supertest.ts
  test/common/config.js
  test/common/services/deployment.ts
  test/common/services/legacy_opensearch.ts
  test/common/services/opensearch.ts
  test/common/services/opensearch_archiver.ts
  test/common/services/opensearch_dashboards_server/opensearch_dashboards_server.ts
  test/common/services/security/test_user.ts
  test/functional/apps/discover/_shared_links.js
  test/functional/page_objects/common_page.ts
  test/functional/page_objects/context_page.ts
  test/functional/services/supertest.ts
  test/plugin_functional/test_suites/application_links/redirect_app_links.ts
  test/plugin_functional/test_suites/core_plugins/application_leave_confirm.ts
  test/plugin_functional/test_suites/core_plugins/application_status.ts
  test/plugin_functional/test_suites/core_plugins/applications.ts
  test/server_integration/http/platform/headers.ts
  test/server_integration/http/ssl_redirect/config.js
  test/server_integration/services/supertest.js
Labels: v3.0.0

#3640 [Vega] Add Filter custom label for opensearchDashboardsAddFilter
  CHANGELOG.md
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
Labels: backport 2.x, v2.7.0

#3663 fix(vis_type_vega): Use default categorical color palette directly
  src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
Labels: backport 2.x, Skip-Changelog, v2.7.0, backport 2.6

#3729 [CVE-2021-3803][1.x] Bump nth-check from 1.0.2 to 2.0.1
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3739 [CVE-2021-23382][1.x] Bump postcss from 8.2.10 to 8.2.13
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3090 Dashboard Lists Integration
  CHANGELOG.md
  src/plugins/dashboard/public/application/application.ts
  src/plugins/dashboard/public/application/legacy_app.js
  src/plugins/dashboard/public/application/listing/__snapshots__/create_button.test.tsx.snap
  src/plugins/dashboard/public/application/listing/__snapshots__/dashboard_listing.test.js.snap
  src/plugins/dashboard/public/application/listing/create_button.test.tsx
  src/plugins/dashboard/public/application/listing/create_button.tsx
  src/plugins/dashboard/public/application/listing/dashboard_listing.js
  src/plugins/dashboard/public/application/listing/dashboard_listing.test.js
  src/plugins/dashboard/public/application/listing/dashboard_listing_ng_wrapper.html
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/types.ts
  src/plugins/opensearch_dashboards_react/public/table_list_view/README.md
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  test/functional/apps/dashboard/dashboard_clone.js
Labels: backport 2.x, v2.7.0

#3629 [CCI] Fix type errors in i18n
  CHANGELOG.md
  src/dev/i18n/integrate_locale_files.ts
  src/dev/i18n/tasks/check_compatibility.ts
  src/dev/i18n/tasks/check_configs.ts
  src/dev/i18n/tasks/extract_default_translations.ts
  src/dev/i18n/tasks/extract_untracked_translations.ts
  src/dev/i18n/tasks/index.ts
  src/dev/i18n/tasks/merge_configs.ts
  src/dev/i18n/utils/verify_icu_message.ts
  src/dev/run_i18n_check.ts
  src/dev/run_i18n_extract.ts
  src/dev/run_i18n_integrate.ts
Labels: CCI

#3723 [CVE-2022-1537][CVE-2022-0436][1.x]bump grunt from 1.4.1 to 1.5.3
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3725 [CVE-2021-3765][1.x] bump validator from 8.2.0 to 13.9.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.9

#3758 [Feature Anywhere] Fix visibleVisLayers ser/deser
  src/plugins/vis_augmenter/public/test_constants.ts
  src/plugins/vis_augmenter/public/vega/helpers.test.ts
  src/plugins/vis_augmenter/public/vega/helpers.ts
  src/plugins/vis_type_vega/public/data_model/types.ts
  src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
Labels: visualizations, unified visualization UX, feature-anywhere, v2.8.0

#3715 [Fix] VisType switching persistence and selectively show warning
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/utils/get_persisted_agg_params.test.tsx
  src/plugins/vis_builder/public/application/utils/get_persisted_agg_params.ts
  src/plugins/vis_builder/public/application/utils/state_management/shared_actions.ts
  src/plugins/vis_builder/public/application/utils/use/use_persisted_agg_params.test.tsx
  src/plugins/vis_builder/public/application/utils/use/use_persisted_agg_params.ts
  test/functional/apps/vis_builder/_base.ts
Labels: vis builder, backport 2.x, Skip-Changelog, v2.7.0
