Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-06, with the labels that each got.

#3116 Adds plugin manifest config to define OpenSearch plugin dependency and verifies if it is installed on the cluster
  CHANGELOG.md
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/integration_tests/plugins_service.test.ts
  src/core/server/plugins/plugin.test.ts
  src/core/server/plugins/plugin.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/plugins_service.test.ts
  src/core/server/plugins/plugins_system.test.ts
  src/core/server/plugins/plugins_system.ts
  src/core/server/plugins/types.ts
Labels: backport 2.x, v2.8.0, backport 2.8

#4191 Chore: Updates branch name
  package.json
Labels: Skip-Changelog, v2.8.0

#4164 [Table Visualization] Remove custom styling for text-align:center in favor of OUI utility class.
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_app.scss
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
Labels: backport 2.x, tableVis, repeat-contributor, v2.9.0

#4205 Revert "Adds plugin manifest config to define OpenSearch plugin dependency and verifies if it is installed (#3116) (#4195)"
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/integration_tests/plugins_service.test.ts
  src/core/server/plugins/plugin.test.ts
  src/core/server/plugins/plugin.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/plugins_service.test.ts
  src/core/server/plugins/plugins_system.test.ts
  src/core/server/plugins/plugins_system.ts
  src/core/server/plugins/types.ts
Labels: Skip-Changelog, v2.8.0

#4204 Add 2.8.0 release notes
  release-notes/opensearch-dashboards.release-notes-2.8.0.md
Labels: backport 2.x, Skip-Changelog, v2.8.0, distinguished-contributor, backport 2.8

#3890 Chore(CHANGELOG): Update with 2.7, 2.8 releases
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-1.3.10.md
  release-notes/opensearch-dashboards.release-notes-2.8.0.md
Labels: distinguished-contributor

#4149 [Saved Object Service] Adds Repository Factory Provider
  CHANGELOG.md
  src/core/server/legacy/legacy_service.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/saved_objects/saved_objects_service.mock.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/service/lib/scoped_client_provider.ts
Labels: backport 2.x, valued-contributor, v2.9.0, meta storage

#4245 [Feature Anywhere] Various bug fixes
  src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx
  src/plugins/vis_augmenter/public/view_events_flyout/components/event_vis_item.tsx
  src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss
  src/plugins/vis_augmenter/server/capabilities_provider.ts
  src/plugins/vis_augmenter/server/saved_objects/augment_vis.ts
Labels: feature-anywhere, v2.9.0, seasoned-contributor

#4144 add category option for context menus
  CHANGELOG.md
  examples/ui_actions_explorer/public/context_menu_examples/context_menu_examples.tsx
  examples/ui_actions_explorer/public/context_menu_examples/panel_group_options_and_context_actions.tsx
  src/plugins/ui_actions/README.md
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.test.ts
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.tsx
  src/plugins/ui_actions/public/util/presentable.ts
Labels: first-time-contributor

#4108 [Dashboard De-Angular] Add basic top nav bar structure
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/application/utils/utils.ts
  src/plugins/dashboard/public/types.ts
Labels: de-angular, dashboards, distinguished-contributor

#4026 [CCI] Add bluebird replaces for src/plugins/saved_objects
  CHANGELOG.md
  src/plugins/saved_objects/public/saved_object/saved_object.test.ts
Labels: backport 2.x, CCI, repeat-contributor, v2.9.0

#4208 [2.8 backport] Replace re2 with RegExp in timeline and add unit tests
  CHANGELOG.md
  package.json
  src/dev/build/tasks/patch_native_modules_task.test.ts
  src/dev/build/tasks/patch_native_modules_task.ts
  src/plugins/vis_type_timeline/server/series_functions/label.js
  src/plugins/vis_type_timeline/server/series_functions/label.test.js
  yarn.lock
Labels: not in release

#4251 [Feature Anywhere] More bug fixes
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_type_vega/public/vega_view/vega_view.js
Labels: feature-anywhere, v2.9.0, seasoned-contributor

#4250 Allow plugins get vis embeddable to show in flyouts
  src/plugins/vis_augmenter/public/index.ts
  src/plugins/vis_augmenter/public/view_events_flyout/components/index.ts
  src/plugins/vis_augmenter/public/view_events_flyout/components/utils.tsx
  src/plugins/vis_augmenter/public/view_events_flyout/components/view_events_flyout.tsx
Labels: repeat-contributor

#4266 Remove `lmdb-store` to fix backport issue
  CHANGELOG.md
  packages/osd-optimizer/package.json
  yarn.lock
Labels: bug, backport 2.8

#4275 Validate and correct change log after 2.8 release
  CHANGELOG.md
Labels: docs, Skip-Changelog, all-star-contributor

#4277 [Backport 1.3][CVE-2022-1537] Bump grunt from 1.5.2 to 1.5.3
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, v1.3.11

#4269 [Feature Anywhere] More bug fixes
  src/plugins/vis_augmenter/public/actions/plugin_resource_delete_action.test.ts
  src/plugins/vis_augmenter/public/constants.ts
  src/plugins/vis_augmenter/public/mocks.ts
  src/plugins/vis_augmenter/public/test_constants.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.test.ts
Labels: feature-anywhere, v2.9.0, seasoned-contributor

#4203 [2.x backport]Replace re2 with RegExp in timeline and add unit tests
  CHANGELOG.md
  package.json
  src/dev/build/tasks/patch_native_modules_task.test.ts
  src/dev/build/tasks/patch_native_modules_task.ts
  src/plugins/vis_type_timeline/server/series_functions/label.js
  src/plugins/vis_type_timeline/server/series_functions/label.test.js
  yarn.lock
Labels: v2.9.0

#4281 [Feature Anywhere] Fix bug of tooltip showing 'undefined' in certain cases
  src/plugins/vis_augmenter/public/test_constants.ts
  src/plugins/vis_augmenter/public/vega/helpers.test.ts
  src/plugins/vis_augmenter/public/vega/helpers.ts
Labels: bug, feature-anywhere, v2.9.0, seasoned-contributor

#4207 [2.8 backport] Bump `joi` to v14 to avoid the possibility of prototype poisoning in a nested dependency
  CHANGELOG.md
  package.json
  packages/osd-config-schema/package.json
  packages/osd-test/package.json
  yarn.lock
Labels: not in release

#4295 Merge main changes to Feature-Anywhere branch
  .github/CODEOWNERS
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
  examples/ui_actions_explorer/public/context_menu_examples/context_menu_examples.tsx
  examples/ui_actions_explorer/public/context_menu_examples/panel_group_options_and_context_actions.tsx
  release-notes/opensearch-dashboards.release-notes-1.3.10.md
  release-notes/opensearch-dashboards.release-notes-2.8.0.md
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/legacy/legacy_service.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/integration_tests/plugins_service.test.ts
  src/core/server/plugins/plugin.test.ts
  src/core/server/plugins/plugin.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/plugins/plugins_service.test.ts
  src/core/server/plugins/plugins_system.test.ts
  src/core/server/plugins/plugins_system.ts
  src/core/server/plugins/types.ts
  src/core/server/saved_objects/saved_objects_service.mock.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/service/lib/scoped_client_provider.ts
  src/plugins/saved_objects/public/saved_object/saved_object.test.ts
  src/plugins/ui_actions/README.md
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.test.ts
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.tsx
  src/plugins/ui_actions/public/util/presentable.ts
  src/plugins/vis_type_table/public/components/table_vis_app.scss
  src/plugins/vis_type_table/public/components/table_vis_component.tsx
Labels: repeat-contributor

#4309 Group ViewEvents option and bug fix
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx
  src/plugins/vis_augmenter/public/view_events_flyout/components/utils.tsx
Labels: valued-contributor

#3989 [DEVELOPER_GUIDE] resolving links
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  README.md
Labels: CCI, first-time-contributor

#4268 Enable data client with sample data server side
  .lycheeexclude
  CHANGELOG.md
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/home/opensearch_dashboards.json
  src/plugins/home/public/application/sample_data_client.js
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/index.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/index.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
  src/plugins/home/server/services/sample_data/routes/install.test.ts
  src/plugins/home/server/services/sample_data/routes/install.ts
  src/plugins/home/server/services/sample_data/routes/list.test.ts
  src/plugins/home/server/services/sample_data/routes/list.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.test.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.ts
  src/plugins/home/server/services/sample_data/sample_data_registry.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.9.0

#4211 [1.x backport] Bump `joi` to v14 to avoid the possibility of prototype poisoning in a nested dependency
  CHANGELOG.md
  package.json
  packages/osd-config-schema/package.json
  packages/osd-test/package.json
  yarn.lock
Labels: backport 1.3, v1.3.11

#4343 Upgrade the backport workflow
  .github/workflows/backport.yml
  CHANGELOG.md
Labels: backport 1.x, backport 1.3, backport 2.x, distinguished-contributor

#4237 Hide any output from `use_node` checking for Node compatibility
  CHANGELOG.md
  scripts/use_node
Labels: backport 2.x, distinguished-contributor, v2.9.0, backport 2.8

#4257 [Dashboard De-Angular] Add new/existing visualizations to dashboard
  package.json
  src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/embeddable/dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/dashboard_embeddable_editor.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/types.ts
Labels: de-angular, dashboards, distinguished-contributor

#4336 Allow queryStart to be passed into fetchVisEmbeddable
  src/plugins/vis_augmenter/public/view_events_flyout/components/utils.tsx
Labels: feature-anywhere, valued-contributor

#4327 [Feature Anywhere] Fix legacy tests / bug fixes
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
  src/plugins/vis_type_vega/public/expressions/vega_fn.ts
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
  src/plugins/vis_type_vega/public/vega_visualization.js
  src/plugins/vis_type_vislib/public/line_to_expression.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
  yarn.lock
Labels: feature-anywhere, v2.9.0, seasoned-contributor

#4346 [Dashboard De-Angular] Render empty dashboard screen when creating new dashboards
  src/plugins/dashboard/public/application/app.scss
  src/plugins/dashboard/public/application/app.tsx
  src/plugins/dashboard/public/application/dashboard_empty_screen.scss
  src/plugins/dashboard/public/application/dashboard_empty_screen.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
Labels: de-angular, dashboards

#4363 [Vis Colors] Update default color in TSVB to use `ouiPaletteColorBlind()[0]`
  CHANGELOG.md
  src/plugins/vis_type_timeseries/public/metrics_type.ts
Labels: all-star-contributor

#4264 Bump version to 2.9
  package.json
Labels: Skip-Changelog, v2.9.0

#4366 [Vis colors] Replace vis_type_timeline colors with `ouiPaletteColorBlind()`
  CHANGELOG.md
  src/plugins/vis_type_timeline/public/helpers/panel_utils.ts
Labels: all-star-contributor

#4290 [Lint] add custom stylelint rules and config
  .eslintignore
  .stylelintrc.yml
  CHANGELOG.md
  package.json
  packages/osd-stylelint-config/.stylelintrc.js
  packages/osd-stylelint-config/README.md
  packages/osd-stylelint-config/config/colors.json
  packages/osd-stylelint-config/config/global_selectors.json
  packages/osd-stylelint-config/package.json
  packages/osd-stylelint-plugin-stylelint/README.md
  packages/osd-stylelint-plugin-stylelint/package.json
  packages/osd-stylelint-plugin-stylelint/src/index.ts
  packages/osd-stylelint-plugin-stylelint/src/rules/index.ts
  packages/osd-stylelint-plugin-stylelint/src/rules/no_custom_colors/index.ts
  packages/osd-stylelint-plugin-stylelint/src/rules/no_modifying_global_selectors/index.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/compliance_engine.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/extract_regex.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/get_message.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/get_rules_from_config.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/index.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/is_color_property.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/is_valid_options.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/matches.ts
  packages/osd-stylelint-plugin-stylelint/tsconfig.json
  packages/osd-stylelint-plugin-stylelint/yarn.lock
Labels: distinguished-contributor, v2.9.0

#4342 [@osd/pm] Fix linked deps resolution
  CHANGELOG.md
  packages/osd-pm/dist/index.js
  packages/osd-pm/src/utils/__fixtures__/opensearch-dashboards-dev/package.json
  packages/osd-pm/src/utils/__fixtures__/opensearch-dashboards-dev/packages/bar/package.json
  packages/osd-pm/src/utils/__fixtures__/opensearch-dashboards-dev/packages/foo/package.json
  packages/osd-pm/src/utils/__fixtures__/opensearch-dashboards-dev/yarn.lock
  packages/osd-pm/src/utils/yarn_lock.test.ts
  packages/osd-pm/src/utils/yarn_lock.ts
  src/dev/build/tasks/__fixtures__/opensearch-dashboards-dev/yarn.lock
  src/dev/build/tasks/__snapshots__/copy_source_task.test.ts.snap
  src/dev/build/tasks/copy_source_task.test.ts
  src/dev/build/tasks/copy_source_task.ts
  src/dev/precommit_hook/casing_check_config.js
Labels: backport 2.x, distinguished-contributor, v2.9.0

#4344 Add configurable `defaults` and `overrides` to `uiSettings`
  CHANGELOG.md
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
  src/core/server/ui_settings/types.ts
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/ui_settings_config.ts
  src/core/server/ui_settings/ui_settings_service.mock.ts
  src/core/server/ui_settings/ui_settings_service.test.ts
  src/core/server/ui_settings/ui_settings_service.ts
  src/legacy/ui/ui_render/ui_render_mixin.js
Labels: backport 2.x, distinguished-contributor, v2.9.0

#4357 [Dashboard De-Angular] Add additional routing configurations
  src/plugins/dashboard/public/application/app.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing.tsx
  src/plugins/dashboard/public/application/components/dashboard_no_match.tsx
  src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/types.ts
Labels: de-angular, dashboards, distinguished-contributor

#4364 [Dashboard De-Angular] Enable time filter functionalities
  src/plugins/dashboard/public/application/components/dashboard_editor.tsx
  src/plugins/dashboard/public/application/lib/update_saved_dashboard.ts
  src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/dashboard/public/plugin.tsx
  test/functional/apps/dashboard/index.js
Labels: de-angular, dashboards, distinguished-contributor

#4294 Refactor hardcode color to use OUI in `maps_legacy`
  CHANGELOG.md
  src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
Labels: backport 2.x, repeat-contributor, v2.9.0

#4384 Remove broken flot documentation link for Ruby API
  packages/osd-ui-shared-deps/flot_charts/API.md
Labels: Skip-Changelog, distinguished-contributor

#4070 [CCI] Fix relationships header overflow
  CHANGELOG.md
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx
Labels: backport 2.x, first-time-contributor, v2.9.0

#4338 Bump sass-lint to 1.13.0 to fix eslint security issue
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 1.3, v1.3.12

#4401 [Dashboard De-Angular] No index pattern routing
  src/plugins/dashboard/public/plugin.tsx
Labels: de-angular, dashboards, distinguished-contributor

#4293 Refactor color maps to use OUI color palettes
  CHANGELOG.md
  src/plugins/charts/public/static/color_maps/color_maps.ts
  src/plugins/vis_type_vislib/public/vislib/visualizations/gauge_chart.test.js
Labels: repeat-contributor

#3964 [CCI] Remove unused tags in the navigation plugin
  CHANGELOG.md
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.test.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: needs more info, CCI, first-time-contributor, OUI compliance

#4265 Bump version to 2.8.1
  package.json
Labels: Skip-Changelog, v2.8.1

#4142 [Client consolidation] Migrate from legacy elasticsearch client to opensearch-js client in `osd-opensearch-archiver` package
  CHANGELOG.md
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch-archiver/src/actions/empty_opensearch_dashboards_index.ts
  packages/osd-opensearch-archiver/src/actions/load.ts
  packages/osd-opensearch-archiver/src/actions/save.ts
  packages/osd-opensearch-archiver/src/actions/unload.ts
  packages/osd-opensearch-archiver/src/cli.ts
  packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/docs/index_doc_records_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/docs/index_doc_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/docs/test_stubs.ts
  packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/delete_index.ts
  packages/osd-opensearch-archiver/src/lib/indices/delete_index_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/generate_index_records_stream.test.ts
  packages/osd-opensearch-archiver/src/lib/indices/generate_index_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/opensearch_dashboards_index.ts
  packages/osd-opensearch-archiver/src/lib/indices/test_stubs.ts
  packages/osd-opensearch-archiver/src/opensearch_archiver.ts
  test/common/services/opensearch_archiver.ts
Labels: backport 2.x, all-star-contributor, client-consolidation, v2.9.0

#4408 Chore (deps): Bump OUI to 1.1.2 to add anomoly detection icon
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.9.0

#4348 [Vis Colors] Update legacy seed colors to use `ouiPaletteColorBlind()`
  CHANGELOG.md
  src/plugins/charts/public/services/colors/color_palette.ts
  src/plugins/charts/public/services/colors/colors.test.ts
  src/plugins/charts/public/services/colors/colors.ts
  src/plugins/charts/public/services/colors/colors_palette.test.ts
  src/plugins/charts/public/services/colors/mapped_colors.test.ts
  src/plugins/charts/public/services/colors/seed_colors.test.ts
  src/plugins/charts/public/services/colors/seed_colors.ts
  test/functional/apps/dashboard/dashboard_state.js
Labels: needs more info, backport 2.x, all-star-contributor, v2.9.0

#4428 Updates Release notes for 1.3.11
  release-notes/opensearch-dashboards.release-notes-1.3.11.md
Labels: backport main, Skip-Changelog

#4392 [Stylelint] Add typing to Stylelint rules
  packages/osd-stylelint-plugin-stylelint/package.json
  packages/osd-stylelint-plugin-stylelint/src/rules/no_custom_colors/index.ts
  packages/osd-stylelint-plugin-stylelint/src/rules/no_modifying_global_selectors/index.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/is_color_property.ts
Labels: Skip-Changelog, repeat-contributor

#4398 [Vis colors] Update legacy mapped colors in charts plugin to use ouiPaletteColorBlind()
  CHANGELOG.md
  src/plugins/charts/public/services/colors/color_palette.ts
  src/plugins/charts/public/services/colors/colors.test.ts
  src/plugins/charts/public/services/colors/colors_palette.test.ts
  src/plugins/charts/public/services/colors/mapped_colors.ts
  src/plugins/charts/server/plugin.ts
  src/plugins/vis_type_tagcloud/public/components/__snapshots__/tag_cloud_visualization.test.js.snap
  src/plugins/vis_type_tagcloud/public/components/tag_cloud_visualization.test.js
Labels: all-star-contributor

#4411 [CVE-2022-25883] Resolve semver to 7.5.3 and remove unused package
  CHANGELOG.md
  package.json
  packages/osd-pm/package.json
  yarn.lock
Labels: cve, backport 2.x, v2.9.0

#4412 Enable sample data with Multiple datasource frontend
  CHANGELOG.md
  src/plugins/home/opensearch_dashboards.json
  src/plugins/home/public/application/components/sample_data_set_card.js
  src/plugins/home/public/application/components/sample_data_set_cards.js
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/home/public/application/opensearch_dashboards_services.ts
  src/plugins/home/public/plugin.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.9.0

#4339 Feature (home): Add vis audit sample dashboard
  CHANGELOG.md
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
Labels: backport 2.x, distinguished-contributor, v2.9.0

#4414 [Feature Anywhere] Fix unrelated changes to be synced with main
  .github/workflows/add_untriaged_label.yml
  CHANGELOG.md
  src/core/public/notifications/toasts/toasts_api.tsx
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/routes/test_connection.ts
  yarn.lock
Labels: feature-anywhere, v2.9.0, seasoned-contributor

#4443 [Feature Anywhere] Fix bug of charts in view events flyout not fetching vislayers
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Labels: bug, feature-anywhere, v2.9.0, seasoned-contributor

#4437 [Backport 1.3][CVE-2022-25883] Resolve semver to 7.5.3 and remove unused package
  CHANGELOG.md
  package.json
  packages/osd-pm/package.json
  yarn.lock
Labels: cve, v1.3.12

#4450 possible fix for flakey ci9 test
  test/functional/apps/visualize/_area_chart.js
Labels: ci, backport 1.x, backport 2.x, Skip-Changelog, distinguished-contributor, v2.9.0, v1.3.12

#4455 [Feature Anywhere] Update default setting; fix single snapshot
  config/opensearch_dashboards.yml
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
Labels: feature-anywhere, v2.9.0

#4446 Chore (VisBuilder): Update icon to use OUI icon
  CHANGELOG.md
  src/plugins/vis_builder/public/assets/vis_builder_icon.svg
  src/plugins/vis_builder/public/assets/vis_builder_icon_secondary_fill.svg
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.ts
Labels: backport 2.x, distinguished-contributor, v2.9.0
