Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-11, with the labels that each got.

#4498 Read Only Tenant Mode
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  docs/capabilities/read_only_mode.md
  src/core/public/application/application_service.tsx
  src/core/server/index.ts
  src/core/server/internal_types.ts
  src/core/server/legacy/legacy_service.test.ts
  src/core/server/legacy/legacy_service.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/security/readonly_service.test.ts
  src/core/server/security/readonly_service.ts
  src/core/server/security/security_service.mock.ts
  src/core/server/security/security_service.test.ts
  src/core/server/security/security_service.ts
  src/core/server/security/types.ts
  src/core/server/server.ts
  src/plugins/advanced_settings/server/plugin.ts
  src/plugins/console/server/plugin.ts
  src/plugins/dashboard/server/plugin.ts
  src/plugins/data/server/index_patterns/index_patterns_service.ts
  src/plugins/discover/server/plugin.ts
  src/plugins/saved_objects_management/server/plugin.ts
  src/plugins/visualize/server/plugin.ts
Labels: first-time-contributor

#5435 Fix navigation issue across dashboards
  CHANGELOG.md
  src/plugins/dashboard/public/application/embeddable/dashboard_container.tsx
Labels: backport 2.x, de-angular, dashboards, distinguished-contributor, backport 2.11, v2.11.1

#5109 [2.10] bump version to next patch version
  package.json
Labels: Skip-Changelog, v2.10.1

#5414 Bump `eslint-import-resolver-webpack` and `browserify-sign`
  CHANGELOG.md
  packages/osd-eslint-import-resolver-opensearch-dashboards/package.json
  yarn.lock
Labels: backport 1.3, backport 2.x, distinguished-contributor, v1.3.14, v2.12.0

#5441 [BUG] Fix Discover table panel size auto adjust in Dashboard
  CHANGELOG.md
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/embeddable/search_embeddable.scss
  src/plugins/discover/public/embeddable/search_embeddable.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
Labels: bug, backport 2.x, discover, distinguished-contributor, backport 2.11, v2.11.1

#5456 Add new MAINTAINERS to CODEOWNERS file
  .github/CODEOWNERS
  CHANGELOG.md
Labels: valued-contributor

#5455 Enhance darwin-arm64 release
  .github/workflows/build_and_test_workflow.yml
  src/dev/build/args.test.ts
  src/dev/build/args.ts
  src/dev/build/cli.ts
  src/dev/build/lib/fs.ts
  src/dev/build/tasks/create_archives_sources_task.ts
  src/dev/build/tasks/nodejs/__snapshots__/download_node_builds_task.test.ts.snap
  src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.ts
  src/dev/build/tasks/nodejs/node_shasums.test.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.12.0

#5465 Bump chromedriver from 107.0.3 to 119.0.1
  CHANGELOG.md
  Dockerfile
  package.json
  yarn.lock
Labels: backport 1.3, backport 2.x, maintenance, distinguished-contributor

#4710 [Decouple] Add new core service to expose functionality to verify plugin compatibility with OpenSearch plugins
  CHANGELOG.md
  src/core/public/plugins/plugin.test.ts
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/cross_compatibility/README.md
  src/core/server/cross_compatibility/cross_compatibility.mock.ts
  src/core/server/cross_compatibility/cross_compatibility_service.test.ts
  src/core/server/cross_compatibility/cross_compatibility_service.ts
  src/core/server/cross_compatibility/index.ts
  src/core/server/cross_compatibility/types.ts
  src/core/server/index.ts
  src/core/server/internal_types.ts
  src/core/server/legacy/legacy_service.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/plugins/plugins_service.test.ts
  src/core/server/plugins/plugins_service.ts
  src/core/server/plugins/plugins_system.test.ts
  src/core/server/plugins/plugins_system.ts
  src/core/server/plugins/types.ts
  src/core/server/server.test.ts
  src/core/server/server.ts
  src/core/types/cross_compatibility.ts
  src/core/types/index.ts
Labels: enhancement, backport 2.x, all-star-contributor, v2.12.0

#5429 [OSCI][FIX] Discover: Fix the Subfields Display Issue
  CHANGELOG.md
  src/plugins/data/common/index_patterns/index_patterns/flatten_hit.ts
Labels: backport 2.x, discover, first-time-contributor, v2.12.0

#5450 Add border for header navigation on right
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
Labels: backport 2.x, repeat-contributor, v2.12.0

#5486 Add Release Notes and update CHANGELOG.md for 2.11.1
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.11.1.md
Labels: docs, backport 2.x, distinguished-contributor, backport 2.11, v2.11.1

#5491 Remove #5428 from 2.11.1 release due to conflicts
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.11.1.md
Labels: docs, backport 2.x, Skip-Changelog, backport 2.11, v2.11.1

#5497 [2.11 Backport] Remove #5428 from 2.11.1 release due to conflicts
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.11.1.md
Labels: docs

#5496 [2.x Backport] Remove #5428 from 2.11.1 release due to conflicts
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-2.11.1.md
Labels: docs

#5451 [Chore] `--security` for snapshot and OSD server
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  package.json
  packages/osd-opensearch/src/cli_commands/snapshot.js
  packages/osd-opensearch/src/cluster.js
  packages/osd-opensearch/src/paths.js
  src/cli/serve/serve.js
Labels: distinguished-contributor
