Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-10, with the labels that each got.

#5095 [2.x][Console] Add support for JSON with long numerals (#4562)
  CHANGELOG.md
  package.json
  packages/osd-std/README.md
  packages/osd-std/src/__snapshots__/json.test.ts.snap
  packages/osd-std/src/index.ts
  packages/osd-std/src/json.test.ts
  packages/osd-std/src/json.ts
  src/core/public/http/fetch.test.ts
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/client/configure_client.ts
  src/core/server/opensearch/client/mocks.ts
  src/core/server/opensearch/client/scoped_cluster_client.test.ts
  src/core/server/opensearch/client/scoped_cluster_client.ts
  src/core/server/opensearch/client/types.ts
  src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/opensearch_index.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
  src/plugins/console/public/lib/opensearch/opensearch.ts
  src/plugins/console/public/lib/utils/__tests__/__snapshots__/utils.test.ts.snap
  src/plugins/console/public/lib/utils/__tests__/utils.test.ts
  src/plugins/console/public/lib/utils/index.ts
  src/plugins/console/public/services/storage.ts
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
  src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/headers.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/params.test.ts
  src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
  src/plugins/opensearch_ui_shared/__packages_do_not_import__/xjson/json_xjson_translation_tools/index.ts
  yarn.lock
Labels: v2.11.0

#5172 [CI][Cypress] set NODE_OPTIONS and cluster disk allocation
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x, distinguished-contributor, v2.11.0

#5138 Reoder dev guide for yarn install to work
  DEVELOPER_GUIDE.md
Labels: Skip-Changelog, valued-contributor

#4949 Bump `agentkeepalive` to v4.5.0
  CHANGELOG.md
  package.json
  src/core/server/legacy/integration_tests/logging.test.ts
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.11.0

#5130 [Console] Enhance support for JSON with long numerals
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/client/configure_client.ts
  src/core/server/opensearch/client/mocks.ts
  src/core/server/opensearch/client/scoped_cluster_client.test.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.11.0, do not backport

#5160 [BUG][Discover] Add onQuerySubmit to top nav and allow force update to embeddable
  CHANGELOG.md
  package.json
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/embeddable/search_embeddable.tsx
  test/functional/apps/dashboard/dashboard_query_bar.js
Labels: bug, backport 2.x, discover, distinguished-contributor, data explorer, v2.11.0

#5143 [Dashboard] Fix bugs on removing pinned global filters on dashboard page
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
Labels: backport 2.x, de-angular, dashboards, Skip-Changelog, v2.11.0

#5168 [Discover] A bunch of navigation fixes
  CHANGELOG.md
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/discover/public/application/components/doc_views/surrounding_docs_app.tsx
  src/plugins/discover/public/application/components/doc_views/surrounding_docs_view.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.scss
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/discover/public/application/helpers/breadcrumbs.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/context/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/opensearch_dashboards_services.ts
  src/plugins/opensearch_dashboards_utils/docs/global_data_persistence.md
Labels: backport 2.x, discover, de-angular, distinguished-contributor, v2.11.0

#5183 [Manual Backport 2.x] Update yarn install step from dev guide
  DEVELOPER_GUIDE.md
  package.json
Labels: autocut, v2.11.0

#5171 [BUG][Data Explorer][Discover] Automatically load solo added default index pattern
  CHANGELOG.md
  src/plugins/data_explorer/public/index.ts
  src/plugins/discover/public/application/utils/state_management/index.ts
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: bug, backport 2.x, discover, distinguished-contributor, data explorer, v2.11.0

#5184 [Manual Backport 1.3] Update yarn install step from dev guide (#5067)
  DEVELOPER_GUIDE.md
  package.json
Labels: autocut, v1.3.14

#5191 [BUG][Data Explorer][Discover] Allow data grid to auto adjust size based on fetched data count
  CHANGELOG.md
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: bug, backport 2.x, discover, distinguished-contributor, data explorer, v2.11.0

#5190 Fix visAugmenter forming empty key-value pairs in its calls to the SavedObject API
  CHANGELOG.md
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
Labels: backport 2.x, distinguished-contributor, backport 2.9, v2.11.0

#5199 Revert "[Backport 2.x] [BUG][Data Explorer][Discover] Automatically load solo added default index pattern"
  src/plugins/data_explorer/public/index.ts
  src/plugins/discover/public/application/utils/state_management/index.ts
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: Skip-Changelog

#5196 [Data Explorer] Add subject test id for testing data-shared-attribute
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.11.0

#5197 [CI][Cypress][Bug] use default `SOURCE` inputs for checkout
  .github/workflows/cypress_workflow.yml
Labels: ci, backport 2.x, Skip-Changelog, v2.11.0

#5195 [Discover] Fixes mobile layout
  packages/osd-stylelint-config/config/global_selectors.json
  packages/osd-stylelint-config/config/restricted_properties.json
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/discover/public/application/components/sidebar/discover_field.scss
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
Labels: backport 2.x, discover, de-angular, Skip-Changelog, distinguished-contributor, v2.11.0

#5206 [BUG][Data Explorer][Discover] Allow filter and query persist when refresh page or paste url to a new tab
  CHANGELOG.md
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/context/index.tsx
Labels: bug, backport 2.x, discover, distinguished-contributor, data explorer, v2.11.0

#5207 [Discover] Fixes DataTable rendering in discover
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: backport 2.x, discover, de-angular, Skip-Changelog, v2.11.0

#5213 Fix errors in conditions for activating `vizAugmenter`
  CHANGELOG.md
  src/plugins/vis_augmenter/public/utils/utils.ts
Labels: backport 2.x, distinguished-contributor, v2.11.0

#5174 [OSCI] [FIX] time conversion unit test bug
  CHANGELOG.md
  src/plugins/discover/public/application/components/chart/utils/point_series.test.ts
Labels: bug, test:unit, backport 2.x, first-time-contributor, v2.11.0

#5219 [Manual 2.x] De-angular backports collection
  package.json
  packages/osd-stylelint-config/config/global_selectors.json
  packages/osd-stylelint-config/config/restricted_properties.json
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/doc_views/surrounding_docs_app.tsx
  src/plugins/discover/public/application/components/doc_views/surrounding_docs_view.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.scss
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/discover/public/application/helpers/breadcrumbs.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/utils/state_management/index.ts
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/context/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/embeddable/search_embeddable.tsx
  src/plugins/discover/public/opensearch_dashboards_services.ts
  src/plugins/opensearch_dashboards_utils/docs/global_data_persistence.md
  test/functional/apps/dashboard/dashboard_query_bar.js
Labels: Skip-Changelog, v2.11.0

#5221 [Tests-refactor] Remove angular code from plugin_functional and update tests
  CHANGELOG.md
  test/plugin_functional/plugins/doc_views_plugin/public/plugin.tsx
  test/plugin_functional/test_suites/doc_views/doc_views.ts
Labels: test:functional, backport 2.x, de-angular, distinguished-contributor, v2.11.0

#5217 [OSCI] Remove ftr test from PR template
  .github/pull_request_template.md
  CHANGELOG.md
Labels: backport 2.x, first-time-contributor, v2.11.0

#5167 [Feature] Datasource selector of multiple datasources
  CHANGELOG.md
  src/plugins/data/public/data_sources/datasource/datasource.ts
  src/plugins/data/public/data_sources/datasource/factory.test.ts
  src/plugins/data/public/data_sources/datasource/factory.ts
  src/plugins/data/public/data_sources/datasource/index.ts
  src/plugins/data/public/data_sources/datasource/types.ts
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/data_sources/datasource_selector/index.tsx
  src/plugins/data/public/data_sources/datasource_selector/types.ts
  src/plugins/data/public/data_sources/datasource_services/datasource_service.test.ts
  src/plugins/data/public/data_sources/datasource_services/datasource_service.ts
  src/plugins/data/public/data_sources/datasource_services/index.ts
  src/plugins/data/public/data_sources/datasource_services/types.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.test.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.ts
  src/plugins/data/public/data_sources/default_datasource/index.ts
  src/plugins/data/public/data_sources/register_default_datasource.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/types.ts
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/plugin.ts
Labels: backport 2.x, first-time-contributor, v2.11.0

#5242 [BUG][Fuctional Test] Make setDefaultAbsoluteRange more robust and update doc views tests
  CHANGELOG.md
  test/functional/page_objects/time_picker.ts
  test/plugin_functional/test_suites/doc_views/doc_views.ts
  test/plugin_functional/test_suites/doc_views_links/doc_views_links.ts
Labels: bug, test:functional, backport 2.x, discover, distinguished-contributor, v2.11.0, backport 2.11

#5259 [Discover] Adds popular field to discover
  src/plugins/discover/public/application/helpers/popularize_field.ts
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
Labels: backport 2.x, discover, de-angular, Skip-Changelog, distinguished-contributor, v2.11.0, backport 2.11

#5258 [Discover] Fixes recently accessed
  src/plugins/discover/public/application/utils/state_management/index.ts
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/saved_searches/_saved_search.ts
  src/plugins/discover/public/saved_searches/types.ts
Labels: backport 2.x, discover, de-angular, Skip-Changelog, v2.11.0, backport 2.11

#5238 [Data Explorer] Removed X icon in data source selection.
  CHANGELOG.md
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
Labels: backport 2.x, first-time-contributor, data explorer, v2.11.0, backport 2.11

#5261 [BUG][Discover] Allow default columns settings
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/utils/filter_columns.test.ts
  src/plugins/discover/public/application/view_components/utils/filter_columns.ts
Labels: bug, backport 2.x, discover, Skip-Changelog, v2.11.0, backport 2.11

#5133 Support for TLS v1.3
  CHANGELOG.md
  src/core/server/core_usage_data/core_usage_data_service.mock.ts
  src/core/server/core_usage_data/core_usage_data_service.test.ts
  src/core/server/http/__snapshots__/http_config.test.ts.snap
  src/core/server/http/ssl_config.test.ts
  src/core/server/http/ssl_config.ts
Labels: backport 2.x, first-time-contributor

#5286 [Fix] typo in 2.11.0 release note header
  release-notes/opensearch-dashboards.release-notes-2.11.0.md
Labels: Skip-Changelog, first-time-contributor

#5298 [CI] Cypress tests support ciGroups
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: backport 2.x, distinguished-contributor, v2.12.0, backport 2.11

#5166 [Fix] Added documentation link for the dev tools' help menu
  CHANGELOG.md
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/utils/util.ts
Labels: backport 2.x, OSCI, first-time-contributor, v2.12.0

#5293 [OSCI][Doc]Updated EUI doc site links to OUI doc site
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  src/plugins/home/server/services/tutorials/lib/tutorial_schema.ts
  src/plugins/home/server/services/tutorials/lib/tutorials_registry_types.ts
  src/plugins/opensearch_dashboards_legacy/public/notify/toasts/TOAST_NOTIFICATIONS.md
Labels: backport 2.x, OSCI, first-time-contributor, v2.12.0

#5092 [Workspace] Feature/workspace service core module
  CHANGELOG.md
  src/core/public/application/capabilities/capabilities_service.mock.ts
  src/core/public/application/types.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/core_system.test.mocks.ts
  src/core/public/core_system.test.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/mocks.ts
  src/core/public/plugins/plugin_context.ts
  src/core/public/plugins/plugins_service.test.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/capabilities/capabilities_service.mock.ts
  src/core/server/capabilities/capabilities_service.test.ts
  src/core/server/capabilities/capabilities_service.ts
  src/core/server/capabilities/integration_tests/capabilities_service.test.ts
  src/core/server/capabilities/resolve_capabilities.test.ts
  src/core/types/capabilities.ts
  src/core/types/index.ts
  src/core/types/workspace.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: first-time-contributor, workspace

#5309 [CVE-2023-45133] Add package resolution for `@babel/traverse` to `7.23.2` to fix vulnerability
  CHANGELOG.md
  package.json
  yarn.lock
Labels: high severity, cve, backport 2.x, distinguished-contributor, v2.12.0

#5304 [Fix] Change panel header & update snapshot
  src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
Labels: backport 2.x, Skip-Changelog, first-time-contributor, v2.12.0

#5290 [Fix] Add platform "darwin-arm64" to unit test
  CHANGELOG.md
  src/dev/build/lib/config.test.ts
  src/dev/build/lib/config.ts
  src/dev/build/lib/platform.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
Labels: backport 2.x, OSCI, first-time-contributor, v2.12.0

#5170 [Fix] ValidationError when setting `maps.proxyOpenSearchMapsServiceInMaps`
  CHANGELOG.md
  src/plugins/maps_legacy/server/index.ts
Labels: backport 2.x, OSCI, first-time-contributor, v2.12.0

#5294 [Version] Bumps version to 2.12.0
  CHANGELOG.md
  package.json
Labels: v2.12.0

#5324 [Data Explorer] Fix share link of save search
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
Labels: backport 2.x, de-angular, Skip-Changelog, data explorer, v2.12.0, backport 2.11

#5340 [OSCI][CI] set-output is deprecated
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/cypress_workflow.yml
  CHANGELOG.md
Labels: ci, backport 2.x, OSCI, first-time-contributor, backport 2.11

#5383 [CI][Test] Add plugin functional tests on GitHub Actions
  .github/workflows/build_and_test_workflow.yml
  CHANGELOG.md
  test/plugin_functional/config.ts
  test/plugin_functional/test_suites/core_plugins/ui_settings.ts
Labels: backport 2.x, distinguished-contributor, backport 2.11, v2.11.1

#5075 [Workspace][Feature]Setup workspace skeleton and implement basic CRUD API
  CHANGELOG.md
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/config.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/index.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/index.ts
  src/plugins/workspace/server/saved_objects/workspace.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.ts
  test/api_integration/apis/index.js
  test/api_integration/apis/workspace/index.ts
Labels: repeat-contributor, workspace
