Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-08, with the labels that each got.

#4656 Increment version to 1.3.12
  CHANGELOG.md
  package.json
Labels: v1.3.12

#4658 Fix (Legacy Maps): Add necessary specificity for dark mode style over…
  CHANGELOG.md
  src/plugins/maps_legacy/public/map/_leaflet_overrides.scss
  src/plugins/maps_legacy/public/map/_legend.scss
  src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4651 Bump `node-sass` to a version that uses a newer `libsass`
  CHANGELOG.md
  packages/osd-interpreter/package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4649 Update webpack environment targets
  .browserslistrc
  CHANGELOG.md
  packages/osd-babel-preset/node_preset.js
  packages/osd-babel-preset/package.json
  packages/osd-babel-preset/webpack_preset.js
  packages/osd-optimizer/postcss.config.js
  packages/osd-optimizer/src/integration_tests/__snapshots__/basic_optimization.test.ts.snap
  tsconfig.browser.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4648 Reduce the amount of comments in compiled CSS and bundled CSS-in-JS
  CHANGELOG.md
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-ui-framework/Gruntfile.js
  packages/osd-ui-framework/dist/kui_dark.css
  packages/osd-ui-framework/dist/kui_light.css
  packages/osd-ui-framework/dist/kui_next_dark.css
  packages/osd-ui-framework/dist/kui_next_light.css
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  packages/osd-ui-shared-deps/webpack.config.js
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4641 [Dashboard De-Angular] Add more unit tests for utils folder
  CHANGELOG.md
  src/plugins/dashboard/public/application/utils/breadcrumbs.test.tsx
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.test.tsx
Labels: test:unit, backport 2.x, de-angular, dashboards, distinguished-contributor, v2.10.0

#4674 Fix --font-text CSS var usage and add more leaflet font overrides
  packages/osd-ui-framework/src/global_styling/variables/_font.scss
  src/plugins/maps_legacy/public/map/_custom_button.scss
  src/plugins/maps_legacy/public/map/_leaflet_overrides.scss
  src/plugins/maps_legacy/public/map/_legend.scss
  src/plugins/maps_legacy/public/map/index.scss
Labels: backport 2.x, Skip-Changelog, v2.10.0

#4686 [1.3] Force semver resolution to 7.5.3
  package.json
  yarn.lock
Labels: Skip-Changelog, distinguished-contributor, v1.3.12

#4682 [CVE-2023-26136] [1.3] Resolve tough-cookie to 4.1.3
  CHANGELOG.md
  package.json
  src/core/server/http/cookie_session_storage.test.ts
  yarn.lock
Labels: v1.3.12

#4684 [Manual Backport 1.x] chore (lychee): Add company.net to exclusion list (#4171)
  .lycheeexclude
Labels: Skip-Changelog, v1.3.13

#4690 Chore: Add 1.3.12 release notes
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-1.3.12.md
Labels: backport main, v1.3.12

#4696 Add saved objects service status api
  CHANGELOG.md
  src/core/server/legacy/legacy_service.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/saved_objects/saved_objects_service.mock.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/saved_objects/saved_objects_service.ts
Labels: backport 2.x, valued-contributor, v2.10.0

#4720 Test (linkchecker): Exclude checking dead link
  .lycheeexclude
Labels: backport 1.3, backport 2.x, Skip-Changelog, distinguished-contributor, v2.10.0, v1.3.13

#4681 [Backport 2.x] Reduce the amount of comments in compiled CSS
  CHANGELOG.md
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-ui-framework/Gruntfile.js
  packages/osd-ui-framework/dist/kui_dark.css
  packages/osd-ui-framework/dist/kui_light.css
  packages/osd-ui-framework/dist/kui_next_dark.css
  packages/osd-ui-framework/dist/kui_next_light.css
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  packages/osd-ui-shared-deps/webpack.config.js
  yarn.lock
Labels: v2.10.0

#4650 [@osd/pm] Automate multi-target bootstrap and build
  CHANGELOG.md
  packages/osd-ace/package.json
  packages/osd-ace/scripts/build.js
  packages/osd-ace/tsconfig.json
  packages/osd-dev-utils/src/simple_opensearch_dashboards_platform_plugin_discovery.ts
  packages/osd-i18n/package.json
  packages/osd-i18n/scripts/build.js
  packages/osd-i18n/tsconfig.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-pm/README.md
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/src/commands/bootstrap.ts
  packages/osd-pm/src/production/build_production_projects.ts
  packages/osd-pm/src/utils/__fixtures__/opensearch-dashboards/packages/bar/package.json
  packages/osd-pm/src/utils/package_json.ts
  packages/osd-pm/src/utils/project.test.ts
  packages/osd-pm/src/utils/project.ts
  packages/osd-pm/src/utils/targeted_build.ts
  packages/osd-std/package.json
  packages/osd-std/src/index.ts
  packages/osd-std/tsconfig.json
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4622 [Data Explorer][Discover 2.0] Add initial DiscoverChart
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
  src/plugins/discover/public/application/components/chart/histogram/type.ts
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.test.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/index.ts
  src/plugins/discover/public/application/components/chart/timechart_header/index.ts
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.test.tsx
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.tsx
  src/plugins/discover/public/application/components/chart/utils/create_histogram_configs.ts
  src/plugins/discover/public/application/components/chart/utils/get_dimension.test.ts
  src/plugins/discover/public/application/components/chart/utils/get_dimensions.ts
  src/plugins/discover/public/application/components/chart/utils/index.ts
  src/plugins/discover/public/application/components/chart/utils/point_series.test.ts
  src/plugins/discover/public/application/components/chart/utils/point_series.ts
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.scss
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/create_search_source.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: discover, de-angular, distinguished-contributor, data explorer

#4739 [Chore] Update CHANGELOG.md with 1.3.12 release changes
  CHANGELOG.md
Labels: not in release, all-star-contributor

#4741 Feat (home): Remove color customizations from sample dashboards
  CHANGELOG.md
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
  src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4721 Increment version to 1.3.13
  CHANGELOG.md
  package.json
Labels: v1.3.13

#4687 Fix functional tests for legacy discover plugin
  test/functional/apps/context/_date_nanos.js
  test/functional/apps/context/_date_nanos_custom_timestamp.js
  test/functional/apps/context/_filters.js
  test/functional/apps/context/index.js
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/dashboard/panel_context_menu.ts
  test/functional/apps/discover/_date_nanos.js
  test/functional/apps/discover/_date_nanos_mixed.js
  test/functional/apps/discover/_discover.js
  test/functional/apps/discover/_discover_histogram.ts
  test/functional/apps/discover/_doc_navigation.js
  test/functional/apps/discover/_doc_table.ts
  test/functional/apps/discover/_errors.ts
  test/functional/apps/discover/_field_data.js
  test/functional/apps/discover/_field_visualize.ts
  test/functional/apps/discover/_filter_editor.js
  test/functional/apps/discover/_indexpattern_with_encoded_id.ts
  test/functional/apps/discover/_indexpattern_without_timefield.ts
  test/functional/apps/discover/_inspector.js
  test/functional/apps/discover/_large_string.js
  test/functional/apps/discover/_saved_queries.js
  test/functional/apps/discover/_shared_links.js
  test/functional/apps/discover/_sidebar.js
  test/functional/apps/discover/_source_filters.js
  test/functional/apps/home/_navigation.ts
  test/functional/apps/management/_handle_alias.js
  test/functional/apps/management/_scripted_fields.js
  test/functional/apps/visualize/_lab_mode.js
  test/functional/apps/visualize/index.ts
  test/functional/config.js
  test/functional/services/dashboard/visualizations.ts
Labels: de-angular, distinguished-contributor, data explorer

#4742 Bump version of tinygradient from 0.4.3 to 1.1.5
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3, backport 2.x, valued-contributor, v2.10.0, v1.3.13

#4719 Remove visualization editor background
  CHANGELOG.md
  src/plugins/vis_default_editor/public/_default.scss
Labels: backport 2.x, valued-contributor, v2.10.0

#4745 [Data Explorer] Saved object integration
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/services/view_service/types.ts
  src/plugins/data_explorer/public/utils/state_management/preload.ts
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/components/top_nav/open_search_panel.test.tsx
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/discover/public/application/components/top_nav/show_open_search_panel.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/migrate_state.ts
  src/plugins/discover/public/saved_searches/_saved_search.ts
  src/plugins/discover/public/saved_searches/types.ts
  src/plugins/discover_legacy/public/application/components/discover_legacy.tsx
Labels: discover, de-angular, distinguished-contributor, data explorer

#4754 [Data Explorer] Fix dashboard test for legacy discover
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/dashboard/dashboard_time_picker.js
Labels: de-angular, distinguished-contributor, data explorer

#4640 [Dashboard De-Angular] Add unit tests for dashboard_listing and dashboard_top_nav
  CHANGELOG.md
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_listing/dashboard_listing.test.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.test.tsx
  src/plugins/dashboard/public/application/utils/mocks.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.test.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
Labels: test:unit, needs more info, backport 2.x, de-angular, dashboards, distinguished-contributor

#4760 Add @curq as co-maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: distinguished-contributor

#4756 [Data Explorer][Discover 2.0] Implement column actions
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/utils/state_management/common.test.ts
  src/plugins/discover/public/application/utils/state_management/common.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
Labels: distinguished-contributor

#4769 Updated README.md to fix the Communication guide Link
  README.md
Labels: backport 2.x, Skip-Changelog, first-time-contributor

#4771 Add missing 1.3.x patch release notes to 2.x branch
  release-notes/opensearch-dashboards.release-notes-1.3.10.md
  release-notes/opensearch-dashboards.release-notes-1.3.11.md
  release-notes/opensearch-dashboards.release-notes-1.3.12.md
  release-notes/opensearch-dashboards.release-notes-1.3.2.md
  release-notes/opensearch-dashboards.release-notes-1.3.3.md
  release-notes/opensearch-dashboards.release-notes-1.3.5.md
  release-notes/opensearch-dashboards.release-notes-1.3.6.md
  release-notes/opensearch-dashboards.release-notes-1.3.9.md
Labels: Skip-Changelog

#4764 [Data Explorer] Altrnate result state views + fixes
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/loading_spinner/loading_spinner.scss
  src/plugins/discover/public/application/components/loading_spinner/loading_spinner.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/components/top_nav/open_search_panel.test.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover_legacy/public/application/angular/discover.js
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_item.tsx
Labels: discover, de-angular, distinguished-contributor, data explorer

#4701 Remove minimum constraint on OpenSearch hosts to allow empty host and refactor status API to not include OpenSearch status when host is empty
  CHANGELOG.md
  src/core/server/opensearch/client/cluster_client.ts
  src/core/server/opensearch/opensearch_config.ts
  src/core/server/opensearch/opensearch_service.test.ts
  src/core/server/opensearch/opensearch_service.ts
  src/core/server/opensearch/status.ts
Labels: backport 2.x, valued-contributor, v2.10.0

#4805 Eliminate duplicate dashboard breadcrumb text ID
  src/plugins/dashboard/public/application/utils/breadcrumbs.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor

#4804 Bump lmdb from 2.8.0 to 2.8.5
  CHANGELOG.md
  yarn.lock
Labels: backport 2.x, v2.10.0

#4612 [Decouple] Allow plugin manifest config to define semver compatible OpenSearch plugin and verify if it is installed on the cluster
  CHANGELOG.md
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/integration_tests/plugins_service.test.ts
  src/core/server/plugins/plugin.test.ts
  src/core/server/plugins/plugin.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/plugins_service.test.ts
  src/core/server/plugins/plugins_system.test.ts
  src/core/server/plugins/plugins_system.ts
  src/core/server/plugins/types.ts
Labels: enhancement, backport 2.x, all-star-contributor, v2.10.0

#4787 [Data Explorer][Discover 2.0] Enable sort and cell actions for table
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_actions.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/saved_searches/types.ts
Labels: discover, de-angular, distinguished-contributor, data explorer

#4827 [Data Explorer][Discover 2.0] Change to inspect icon and update hint msg
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_context.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_expand_button.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_inspect_button.tsx
Labels: discover, data explorer, v2.10.0

#4828 [CI] Fix BWC related CI failures by swapping dist url with snapshot url
  .github/workflows/build_and_test_workflow.yml
  scripts/bwc/opensearch_service.sh
Labels: Skip-Changelog

#4850 [Data Explorer][Discover 2.0] Add missing change interval on TimeChart and improve fetch
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: bug, backport 2.x, discover, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4838 [Data Explorer][Discover 2.0] Replace hide column and add move left/right
  src/plugins/discover/public/application/components/data_grid/constants.ts
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/utils/state_management/common.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4857 [Data Explorer] Add dismissible callout for discover
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover_legacy/public/application/components/discover_legacy.tsx
Labels: ux / ui, backport 2.x, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4856 [Data Explorer] Fix breadcrumb for data explorer
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4863 Fix snapshots that didn't get updated between PRs
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: Skip-Changelog, v2.10.0

#4858 [Data Explorer] Fix darkmode for histogram
  src/plugins/discover/public/application/components/chart/_histogram.scss
  src/plugins/discover/public/application/components/chart/chart.tsx
Labels: backport 2.x, Skip-Changelog, data explorer, v2.10.0

#4855 [Data Explorer][Discover 2.0] Append popout icon to oui link for doc viewer links
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.test.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
  src/plugins/discover/public/application/utils/state_management/common.test.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4867 [Manual Backport 2.x] Updated README.md (#4769)
  README.md
Labels: autocut, v2.10.0

#4860 [Manual Backport 2.x][@osd/pm] Automate multi-target bootstrap and build (#4650)
  packages/osd-ace/package.json
  packages/osd-ace/scripts/build.js
  packages/osd-ace/tsconfig.json
  packages/osd-dev-utils/src/simple_opensearch_dashboards_platform_plugin_discovery.ts
  packages/osd-i18n/package.json
  packages/osd-i18n/scripts/build.js
  packages/osd-i18n/tsconfig.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-pm/README.md
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/src/commands/bootstrap.ts
  packages/osd-pm/src/production/build_production_projects.ts
  packages/osd-pm/src/utils/__fixtures__/opensearch-dashboards/packages/bar/package.json
  packages/osd-pm/src/utils/package_json.ts
  packages/osd-pm/src/utils/project.test.ts
  packages/osd-pm/src/utils/project.ts
  packages/osd-pm/src/utils/targeted_build.ts
  packages/osd-std/package.json
  packages/osd-std/src/index.ts
  packages/osd-std/tsconfig.json
Labels: autocut, v2.10.0

#4636 [BUG] Fix management overview page duplicate rendering
  CHANGELOG.md
  src/plugins/management_overview/public/__snapshots__/application.test.tsx.snap
  src/plugins/management_overview/public/application.test.tsx
  src/plugins/management_overview/public/application.tsx
  src/plugins/management_overview/public/plugin.ts
Labels: backport 2.x, repeat-contributor, v2.10.0

#4715 [Next theme] Add modal to notify users of theme updates
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/home/config.ts
  src/plugins/home/public/application/components/__snapshots__/home.test.js.snap
  src/plugins/home/public/application/components/home.js
  src/plugins/home/public/application/components/home.test.js
  src/plugins/home/public/application/components/new_theme_modal.tsx
  src/plugins/home/server/index.ts
  test/common/config.js
Labels: backport 2.x, distinguished-contributor, v2.10.0

#4680 Removing html angular extractor for issue 4018
  CHANGELOG.md
  src/dev/i18n/__snapshots__/extract_default_translations.test.js.snap
  src/dev/i18n/extract_default_translations.js
  src/dev/i18n/extractors/__snapshots__/html.test.js.snap
  src/dev/i18n/extractors/html.js
  src/dev/i18n/extractors/html.test.js
  src/dev/i18n/extractors/index.js
Labels: first-time-contributor

#4870 [Data Explorer] Fixes save search glitch + misc
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/application/components/skip_bottom_button/index.ts
  src/plugins/discover/public/application/components/skip_bottom_button/skip_bottom_button.test.tsx
  src/plugins/discover/public/application/components/skip_bottom_button/skip_bottom_button.tsx
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: backport 2.x, discover, Skip-Changelog, data explorer, v2.10.0

#4879 Update baseline images for functional tests
  test/functional/screenshots/baseline/area_chart.png
  test/functional/screenshots/baseline/tsvb_dashboard.png
Labels: Skip-Changelog, distinguished-contributor

#4875 [Data Explorer][Discover 2.0] Fix issues when change index pattern
  src/plugins/discover/public/application/components/sidebar/lib/get_index_pattern_field_list.ts
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/filter_columns.test.ts
  src/plugins/discover/public/application/view_components/utils/filter_columns.ts
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, data explorer, v2.10.0

#4884 Change color fn used to calculate icon colors for search typeahead
  src/plugins/data/public/ui/typeahead/_suggestion.scss
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.10.0

#4854 [Next Theme] Make `next` theme the default
  CHANGELOG.md
  packages/osd-ui-shared-deps/theme.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/server/ui_settings/ui_settings_config.ts
Labels: backport 2.x, v2.10.0

#4821 [Data Explorer][Discover 2.0] Fix display for index pattern without a default time field
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: backport 2.x, discover, Skip-Changelog, data explorer, v2.10.0
