Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-02, with the labels that each got.

#3367 Add 1.3.8 release notes
  release-notes/opensearch-dashboards.release-notes-1.3.8.md
Labels: backport 1.x, backport 1.3, backport 2.x, Skip-Changelog, v1.3.8

#3374 Update `VisLayer` data models
  src/plugins/vis_augmenter/common/types.test.ts
  src/plugins/vis_augmenter/common/types.ts
Labels: visualizations, feature-anywhere

#3109 Add a new `augment-vis` saved object type
  src/plugins/saved_objects/README.md
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/lib/in_app_url.test.ts
  src/plugins/saved_objects_management/public/lib/in_app_url.ts
  src/plugins/saved_objects_management/public/management_section/object_view/saved_object_view.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/saved_objects_management/public/register_services.ts
  src/plugins/vis_augmenter/public/index.ts
  src/plugins/vis_augmenter/public/plugin.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/_saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/index.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.test.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/index.ts
  src/plugins/vis_augmenter/public/saved_augment_vis/utils/test_helpers.ts
  src/plugins/vis_augmenter/public/services.ts
  src/plugins/vis_augmenter/public/types.ts
  src/plugins/vis_augmenter/server/capabilities_provider.ts
  src/plugins/vis_augmenter/server/plugin.ts
  src/plugins/vis_augmenter/server/saved_objects/augment_vis.ts
  src/plugins/vis_augmenter/server/saved_objects/index.ts
Labels: Skip-Changelog, v2.6.0

#3403 Prevent primitive linting limitations from being applied to unit tests found under `src/setup_node_env`
  .eslintrc.js
  CHANGELOG.md
  src/setup_node_env/node_version_validator.test.js
  src/setup_node_env/root/force.test.js
  src/setup_node_env/root/is_root.test.js
Labels: backport 2.x, v2.6.0

#3411 [Security]Bump hapi/statehood to 7.0.4
  CHANGELOG.md
  yarn.lock
Labels: security vulnerability, backport 2.x, backport 2.5, 2.5.1

#3409 [CVE-2022-25881] Resolve `http-cache-semantics` to `4.1.1`
  CHANGELOG.md
  yarn.lock
Labels: cve, backport 1.x, backport 1.3, backport 2.x, backport 2.5

#3416 [CVE-2023-25166] Bump formula to 3.0.1
  CHANGELOG.md
  yarn.lock
Labels: cve, backport 1.x, backport 2.x

#3399 Add ui setting to configure custom vector map's size parameter
  CHANGELOG.md
  src/plugins/region_map/common/constants/shared.ts
  src/plugins/region_map/common/index.ts
  src/plugins/region_map/public/choropleth_layer.js
  src/plugins/region_map/public/components/map_choice_options.tsx
  src/plugins/region_map/public/region_map_visualization.js
  src/plugins/region_map/public/services.ts
  src/plugins/region_map/server/routes/opensearch.ts
  src/plugins/region_map/server/ui_settings.ts
Labels: maps, v2.6.0

#3390 [search telemetry] Fixes search telemetry's observable object that won't be GC-ed
  CHANGELOG.md
  src/plugins/data/server/plugin.ts
  src/plugins/data/server/search/collectors/usage.ts
  src/plugins/data/server/search/search_service.test.ts
  src/plugins/data/server/search/search_service.ts
Labels: backport 2.x, v2.6.0

#3419 [CVE-2020-36632] Bumps flat from 4.1.1 to 5.0.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, v2.6.0

#3308 Corrects NOTICE file copyright date range
  CHANGELOG.md
  NOTICE.txt
  src/dev/notice/generate_notice_from_source.ts
Labels: v2.6.0

#3359 Upgrade vega-tooltip to 0.30.0 to support custom tooltips #3358
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 2.x, v2.6.0

#3402 Allow relaxing the Node.js runtime version requirement
  CHANGELOG.md
  src/setup_node_env/__snapshots__/node_version_validator.test.js.snap
  src/setup_node_env/node_version_validator.js
  src/setup_node_env/node_version_validator.test.js
Labels: backport 2.x, v2.6.0

#3437 [Manual backport 2.5][CVE-2022-25881] Resolve http-cache-semantics to 4.1.1 (#3409)
  CHANGELOG.md
  yarn.lock
Labels: cve, 2.5.1

#3436 [Manual backport 2.x][CVE-2022-25881] Resolve http-cache-semantics to 4.1.1 (#3409)
  CHANGELOG.md
  yarn.lock
Labels: cve, v2.6.0

#3454 [Manual Backport 2.x] [CVE-2023-25166] Bump formula to 3.0.1 (#3416)
  CHANGELOG.md
  yarn.lock
Labels: v2.6.0

#3455 [CVE-2022-25758][CVE-2020-24025] Bump node-sass to 7.0.3 and sass-loader to 10.4.1 in 2.x
  CHANGELOG.md
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: cve, v2.6.0

#3375 Increment version to 1.3.9
  CHANGELOG.md
  package.json
Labels: v1.3.9

#3451 [CVE-2022-2499][backport 1.x] Resolve qs from 6.5.3 to 6.11.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.3, v1.3.9

#3450 [CVE-2022-24999] Resolve qs from 6.5.3 to 6.11.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, v2.6.0

#3443 Upgrade yarn version to be compatible with @openearch-project/opensearch
  CHANGELOG.md
  package.json
Labels: backport 2.x, v2.6.0

#3464 Revert "[Manual Backport 2.x][MD] Support SigV4 as a new auth type of datasource"
  CHANGELOG.md
  package.json
  packages/osd-opensearch/package.json
  src/dev/jest/config.js
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/client/client_pool.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/client/index.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/index.ts
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/types.ts
  yarn.lock
Labels: v2.6.0

#3467 Make build scripts find and use the latest version of Node.js that satisfies `engines.node`
  CHANGELOG.md
  src/dev/build/lib/config.test.ts
  src/dev/build/lib/config.ts
  src/dev/build/tasks/create_archives_sources_task.ts
  src/dev/build/tasks/nodejs/download_node_builds_task.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/extract_node_builds_task.ts
  src/dev/build/tasks/nodejs/node_download_info.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
  src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
  src/dev/build/tasks/notice_file_task.ts
  src/dev/build/tasks/verify_env_task.ts
Labels: enhancement, backport 2.x, v2.6.0

#3463 Relax Node.js version to `^14.20.1` and bump `.nvmrc` to `v14.21.3`
  .node-version
  .nvmrc
  CHANGELOG.md
  package.json
  src/dev/node_versions_must_match.test.ts
Labels: enhancement, backport 2.x, v2.6.0

#3456 [Multiple DataSource] Refactor test connection to support SigV4 auth type
  CHANGELOG.md
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/data_source_service.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, v2.6.0

#3106 Create switch to render line charts using vega-lite
  src/plugins/vis_type_vega/public/components/vega_vis_editor.tsx
  src/plugins/vis_type_vega/public/expressions/line_vega_spec_fn.test.js
  src/plugins/vis_type_vega/public/expressions/line_vega_spec_fn.ts
  src/plugins/vis_type_vega/public/expressions/vega_fn.ts
  src/plugins/vis_type_vega/public/index.ts
  src/plugins/vis_type_vega/public/plugin.ts
  src/plugins/vis_type_vega/public/vega_request_handler.ts
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
  src/plugins/vis_type_vislib/opensearch_dashboards.json
  src/plugins/vis_type_vislib/public/line.ts
  src/plugins/vis_type_vislib/public/line_to_expression.ts
  src/plugins/visualizations/public/index.ts
  src/plugins/visualizations/public/legacy/build_pipeline.ts
Labels: Skip-Changelog

#3484 Add 2.6 release note
  release-notes/opensearch-dashboards.release-notes-2.6.0.md
Labels: backport 2.x, Skip-Changelog, v2.6.0, backport 2.6

#3491 Feature: bump branch to 2.6
  package.json
Labels: Skip-Changelog

#3503 [BUG][TSVB] Fix serial diff agg link
  CHANGELOG.md
  src/plugins/vis_type_timeseries/public/application/components/aggs/serial_diff.js
Labels: bug, backport 1.x, backport 1.3, backport 2.x, backport 2.6
