Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2023-12, with the labels that each got.

#5564 [Manual Backport 1.3] Add package resolution for @babel/traverse
  package.json
  yarn.lock
Labels: autocut

#5574 Add 1.3.14 release notes
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-1.3.14.md
Labels: backport main, backport 2.x, v1.3.14

#5577 [BUG][Data] Support for custom filters with heterogeneous data fields
  CHANGELOG.md
  src/plugins/data/common/opensearch_query/opensearch_query/filter_matches_index.test.ts
  src/plugins/data/common/opensearch_query/opensearch_query/filter_matches_index.ts
Labels: backport 1.3, backport 2.x, distinguished-contributor, v2.12.0, backport 2.11

#5594 [Admin] Add @SuZhou-Joe as a maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.x, backport 2.x, maintenance, distinguished-contributor, v2.12.0

#5475 Modify data source text for dev tool
  src/plugins/dev_tools/public/application.tsx
Labels: backport 2.x, Skip-Changelog, valued-contributor

#5470 Bump typescript and axios
  CHANGELOG.md
  package.json
  packages/osd-babel-preset/common_preset.js
  packages/osd-cross-platform/src/repo_root.ts
  packages/osd-dev-utils/package.json
  packages/osd-dev-utils/src/osd_client/osd_client_requester.ts
  packages/osd-opensearch-archiver/src/cli.ts
  packages/osd-pm/dist/index.js
  packages/osd-telemetry-tools/src/tools/__snapshots__/extract_collectors.test.ts.snap
  packages/osd-test/src/failed_tests_reporter/github_api.ts
  packages/osd-test/src/functional_test_runner/lib/lifecycle_phase.ts
  packages/osd-ui-shared-deps/package.json
  packages/osd-ui-shared-deps/webpack.config.js
  src/core/public/application/application_service.test.ts
  src/core/public/application/integration_tests/application_service.test.tsx
  src/core/public/application/ui/app_container.test.tsx
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/recently_accessed/recently_accessed_service.test.ts
  src/core/public/context/context_service.ts
  src/core/public/core_app/core_app.ts
  src/core/public/doc_links/doc_links_service.ts
  src/core/public/fatal_errors/fatal_errors_service.tsx
  src/core/public/http/fetch.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/public/integrations/integrations_service.ts
  src/core/public/notifications/notifications_service.ts
  src/core/public/rendering/rendering_service.tsx
  src/core/public/ui_settings/ui_settings_api.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/public/ui_settings/ui_settings_service.ts
  src/core/server/context/context_service.ts
  src/core/server/http/http_service.ts
  src/core/server/http/router/response_adapter.ts
  src/core/server/logging/appenders/file/file_appender.ts
  src/core/server/logging/logging_service.ts
  src/core/server/metrics/metrics_service.ts
  src/core/server/opensearch/client/cluster_client.test.ts
  src/core/server/opensearch/opensearch_service.ts
  src/core/server/rendering/rendering_service.tsx
  src/core/server/status/status_service.ts
  src/dev/build/lib/download.ts
  src/dev/build/lib/fs.ts
  src/dev/jest/config.js
  src/plugins/opensearch_dashboards_utils/common/of.test.ts
  tsconfig.base.json
  yarn.lock
Labels: v3.0.0, distinguished-contributor

#5511 [Fix] Duplicate Icon Rendering in Markdown Visualization Editor
  src/plugins/vis_type_markdown/public/markdown_options.tsx
Labels: bug, backport 2.x, Skip-Changelog, repeat-contributor, v2.12.0

#5503 [Manual][Backport 2.x][Decouple] Add new core service to expose functionality to verify plugin compatibility with OpenSearch plugins
  src/core/public/plugins/plugin.test.ts
  src/core/public/plugins/plugins_service.test.ts
  src/core/server/cross_compatibility/README.md
  src/core/server/cross_compatibility/cross_compatibility.mock.ts
  src/core/server/cross_compatibility/cross_compatibility_service.test.ts
  src/core/server/cross_compatibility/cross_compatibility_service.ts
  src/core/server/cross_compatibility/index.ts
  src/core/server/cross_compatibility/types.ts
  src/core/server/index.ts
  src/core/server/internal_types.ts
  src/core/server/legacy/legacy_service.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/plugins/plugins_service.test.ts
  src/core/server/plugins/plugins_service.ts
  src/core/server/plugins/plugins_system.test.ts
  src/core/server/plugins/plugins_system.ts
  src/core/server/plugins/types.ts
  src/core/server/server.test.ts
  src/core/server/server.ts
  src/core/types/cross_compatibility.ts
  src/core/types/index.ts
Labels: enhancement, Skip-Changelog, v2.12.0, decouple

#5432 [Fix] Inactive State on 'Discover' Tab in Side Navigation Menu
  CHANGELOG.md
  src/core/public/chrome/ui/header/nav_link.test.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
Labels: bug, backport 2.x, repeat-contributor, v2.12.0

#5349 [Fix] Remove empty suggestion history
  CHANGELOG.md
  src/plugins/data/public/ui/typeahead/suggestion_component.test.tsx
  src/plugins/data/public/ui/typeahead/suggestion_component.tsx
Labels: backport 2.x, repeat-contributor, v2.12.0

#5418 [OSCI][ADD] More tests for overview
  CHANGELOG.md
  src/plugins/opensearch_dashboards_overview/public/components/overview/__snapshots__/overview.test.tsx.snap
  src/plugins/opensearch_dashboards_overview/public/components/overview/overview.test.tsx
Labels: test:unit, backport 1.3, backport 2.x, first-time-contributor, v2.12.0

#5273 [Data Explorer] Readme
  src/plugins/data_explorer/README.md
Labels: docs, backport 2.x, Skip-Changelog, distinguished-contributor

#5568 fix: Dev tools console autocomplete issue #5567
  CHANGELOG.md
  src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
  src/plugins/console/public/lib/mappings/__tests__/mapping.test.ts
  src/plugins/console/public/lib/mappings/mappings.ts
  src/plugins/console/public/lib/opensearch/http_response.mock.ts
Labels: bug, backport 2.x, first-time-contributor, v2.12.0

#5537 [OSCI][Fix][Discover]Prevent Adding Timefield to the Side Nav Selected Fields on Column Removal
  CHANGELOG.md
  src/plugins/discover/public/application/view_components/panel/index.tsx
Labels: bug, backport 2.x, discover, first-time-contributor, v2.12.0

#5540 adding documentation on files in util in addition to a README.md with an overview of each file and its exported functions
  packages/osd-stylelint-plugin-stylelint/src/utils/README.md
  packages/osd-stylelint-plugin-stylelint/src/utils/compliance_engine.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/extract_regex.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/get_message.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/get_rules_from_config.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/is_color_property.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/is_valid_options.ts
  packages/osd-stylelint-plugin-stylelint/src/utils/matches.ts
Labels: docs, backport 2.x, Skip-Changelog, first-time-contributor, v2.12.0

#5572 Custom Branding: Relative URL should be allowed
  CHANGELOG.md
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
Labels: backport 2.x, first-time-contributor

#5593 [Manual Backport 2.x] Replace `node-sass` with `sass-embedded` (#5338)
  .github/workflows/build_and_test_workflow.yml
  package.json
  packages/osd-interpreter/package.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/integration_tests/__snapshots__/basic_optimization.test.ts.snap
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-ui-framework/Gruntfile.js
  packages/osd-ui-framework/package.json
  packages/osd-ui-framework/src/components/local_nav/_local_search.scss
  packages/osd-ui-shared-deps/package.json
  scripts/postinstall.js
  src/core/public/core_app/styles/_mixins.scss
  src/core/public/styles/_ace_overrides.scss
  src/plugins/data/public/ui/filter_bar/_global_filter_item.scss
  src/plugins/data/public/ui/saved_query_management/_saved_query_management_component.scss
  src/plugins/opensearch_dashboards_react/public/markdown/_markdown.scss
  src/plugins/vis_builder/public/application/app.scss
  src/plugins/vis_builder/public/application/components/data_tab/dropbox.scss
  src/plugins/vis_builder/public/application/components/workspace.scss
  src/plugins/vis_default_editor/public/_agg_params.scss
  src/plugins/vis_type_timeseries/public/application/components/_vis_with_splits.scss
  src/plugins/vis_type_timeseries/public/application/visualizations/views/_metric.scss
  src/plugins/vis_type_vislib/public/vislib/lib/layout/_layout.scss
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: Skip-Changelog, v2.12.0

#5244 feat: Introduce `registerCollapsibleNavHeader` to ChromeService
  CHANGELOG.md
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/plugins/plugin_context.ts
  src/core/public/plugins/plugins_service.test.ts
Labels: first-time-contributor, workspace

#5626 [Data Explorer] Fix missing field error from taking down the page
  CHANGELOG.md
  src/plugins/discover/public/application/components/chart/utils/create_histogram_configs.ts
Labels: distinguished-contributor

#5508 [osci23] implmented advance setting in Dicover: MODIFY_COLUMN_ON_SWITCH
  CHANGELOG.md
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/filter_columns.test.ts
  src/plugins/discover/public/application/view_components/utils/filter_columns.ts
Labels: bug, backport 2.x, discover, first-time-contributor, v2.12.0
