Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-05, with the labels that each got.

#6683 Optimize scrolling behavior of Discover table
  changelogs/fragments/6683.yml
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  test/functional/apps/dashboard/dashboard_time_picker.js
  test/functional/apps/home/_sample_data.ts
Labels: backport 2.x, distinguished-contributor, v2.14.0, backport 2.14

#6703 fix (startup): fix font theme key
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.14.0, backport 2.14

#6701 fix: register right navigation for dev tool only when console is enabled
  src/plugins/dev_tools/public/plugin.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.14.0, backport 2.14

#6443 [saved objects] enable deletion of saved objects by type if configured
  changelogs/fragments/6443.yml
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/index_migrator.ts
  src/core/server/saved_objects/migrations/core/migration_context.test.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/core/migration_opensearch_client.test.ts
  src/core/server/saved_objects/migrations/core/migration_opensearch_client.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/core/server/saved_objects/saved_objects_config.ts
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
Labels: backport 2.x, distinguished-contributor, v2.14.0, operational excellence, backport 2.14

#6722 [tests] fix tests related to #6443
  changelogs/fragments/6722.yml
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
Labels: distinguished-contributor

#6712 feat: add config for topRightNavigation
  CHANGELOG.md
  changelogs/fragments/6712.yml
  config/opensearch_dashboards.yml
  src/core/public/chrome/ui/header/right_navigation_button.tsx
  src/core/server/mocks.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/legacy/server/config/schema.js
  src/plugins/console/server/plugin.ts
  src/plugins/dev_tools/public/plugin.ts
Labels: backport 2.x, valued-contributor, v2.14.0, backport 2.14

#6734 Revert "fix (startup): fix font theme key (#6703) (#6707)"
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
Labels: v2.14.0

#6736 Revert "[Manual Backport 2.x] Feat (core): Make theme settings user-specific and user-configurable (#5652) (#6681)"
  CHANGELOG.md
  docs/theme.md
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/fonts.tsx
  src/core/server/rendering/views/styles.tsx
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/core/server/rendering/views/theme.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/types/ui_settings.ts
  src/legacy/ui/ui_render/bootstrap/app_bootstrap.js
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
  src/legacy/ui/ui_render/bootstrap/template.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/components/field/field.tsx
  src/plugins/advanced_settings/public/management_app/lib/to_editable_config.ts
  src/plugins/advanced_settings/public/management_app/types.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/public/register_nav_control.tsx
  src/plugins/opensearch_dashboards_usage_collection/server/collectors/management/schema.ts
  src/plugins/telemetry/schema/oss_plugins.json
  test/functional/apps/visualize/_custom_branding.ts
  test/functional/screenshots/baseline/tsvb_dashboard.png
Labels: v2.14.0

#6735 [Manual Backport 2.14] [ignoreFilterIfFieldNotInIndex] Parse query string filters to determine if fields match an index (#6126)
  package.json
  src/plugins/data/common/opensearch_query/opensearch_query/filter_matches_index.test.ts
  src/plugins/data/common/opensearch_query/opensearch_query/filter_matches_index.ts
  src/plugins/data/common/opensearch_query/opensearch_query/index.ts
  src/plugins/data/public/ui/filter_bar/filter_item.tsx
  yarn.lock
Labels: v2.14.0

#6729 [Multiple Datasource Test]add more test for icon and aggregated view
  changelogs/fragments/6729.yml
  src/plugins/data_source_management/public/components/custom_database_icon/__snapshots__/empty_icon.test.tsx.snap
  src/plugins/data_source_management/public/components/custom_database_icon/__snapshots__/error_icon.test.tsx.snap
  src/plugins/data_source_management/public/components/custom_database_icon/empty_icon.test.tsx
  src/plugins/data_source_management/public/components/custom_database_icon/error_icon.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
Labels: backport 2.x, valued-contributor, v2.15.0

#6733 [OSD Availability] Prevent OSD process crashes when disk is full
  changelogs/fragments/6733.yml
  config/opensearch_dashboards.yml
  src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
  src/legacy/server/config/schema.js
  src/legacy/server/logging/configuration.js
  src/legacy/server/logging/log_reporter.js
  src/legacy/server/logging/log_reporter.test.js
Labels: backport 2.x, seasoned-contributor, v2.15.0

#6678 [MDS] Modify toast + popover warning to include incompatible datasources
  changelogs/fragments/6678.yml
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.test.tsx
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, v2.15.0

#6742 [Multiple Datasource Test] Add test for edit data source form
  changelogs/fragments/6742.yml
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.test.tsx
  src/plugins/data_source_management/public/mocks.ts
Labels: backport 2.x, valued-contributor, v2.15.0

#6759 Make Field Name Search Filter Case Insensitive
  changelogs/fragments/6759.yml
  src/plugins/discover/public/application/components/sidebar/lib/field_filter.ts
Labels: backport 2.x, repeat-contributor, v2.15.0

#6752 [Multiple Datasource Test] Add test for error_menu, item, data_source_multi_selectable
  changelogs/fragments/6752.yml
  src/plugins/data_source_management/public/components/data_source_error_menu/__snapshots__/data_source_error_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_error_menu/data_source_error_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_item/data_source_item.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
Labels: backport 2.x, valued-contributor, v2.15.0

#6705 [2.14][chore] update release notes
  CHANGELOG.md
  changelogs/fragments/5652.yml
  changelogs/fragments/6427.yml
  changelogs/fragments/6443.yml
  changelogs/fragments/6477.yml
  changelogs/fragments/6524.yml
  changelogs/fragments/6527.yml
  changelogs/fragments/6544.yml
  changelogs/fragments/6571.yml
  changelogs/fragments/6575.yml
  changelogs/fragments/6584.yml
  changelogs/fragments/6599.yml
  changelogs/fragments/6625.yml
  changelogs/fragments/6636.yml
  changelogs/fragments/6648.yml
  changelogs/fragments/6668.yml
  changelogs/fragments/6669.yml
  changelogs/fragments/6683.yml
  changelogs/fragments/6712.yml
  changelogs/fragments/6722.yml
  release-notes/opensearch-dashboards.release-notes-2.14.0.md
Labels: backport 2.x, Skip-Changelog, v2.14.0, backport 2.14

#6771 add http://www.site.com to lycheeignore
  .lycheeignore
  changelogs/fragments/6771.yml
Labels: backport 2.x, seasoned-contributor

#6756 [Workspace] Fix: Show a error toast when workspace read only user delete saved objects
  changelogs/fragments/6756.yml
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: backport 2.x, repeat-contributor, v2.15.0

#6778 Updating security reachout email
  SECURITY.md
Labels: docs, backport 2.x, first-time-contributor

#6788 add @zhyuanqi as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/6788.yml
Labels: backport 2.x, maintenance, all-star-contributor

#6585 [OE] Adds dev doc script to precommit hook
  changelogs/fragments/6585.yml
  scripts/precommit_hook.js
  src/dev/precommit_hook/check_dev_docs.js
  src/dev/precommit_hook/get_files_for_commit.js
  src/dev/precommit_hook/index.js
  src/dev/run_precommit_hook.js
Labels: distinguished-contributor

#6790 Move @BSFishy to emeritus maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/6790.yml
Labels: backport 2.x, maintenance, all-star-contributor

#6798 add @mengweieric as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/6798.yml
Labels: backport 2.x, all-star-contributor

#6799 Add OpenAPI specification for get and create saved object APIs
  changelogs/fragments/6799.yml
  docs/openapi/README.md
  docs/openapi/saved_objects/index.html
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, all-star-contributor

#6715 [Multiple datasource] Adjust the padding size for aggregated view
  changelogs/fragments/6715.yml
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
Labels: valued-contributor

#6776 [Workspace] Fix workspace name duplication check
  changelogs/fragments/6776.yml
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, valued-contributor, workspace, v2.15.0

#6721 Add Server Side batching for UI Metric Collectors
  changelogs/fragments/6721.yml
  src/core/server/saved_objects/service/lib/repository.ts
  src/plugins/usage_collection/common/constants.ts
  src/plugins/usage_collection/server/config.ts
  src/plugins/usage_collection/server/plugin.ts
  src/plugins/usage_collection/server/report/store_report.test.ts
  src/plugins/usage_collection/server/report/store_report.ts
  src/plugins/usage_collection/server/routes/index.ts
  src/plugins/usage_collection/server/routes/report_metrics.ts
  src/plugins/usage_collection/server/types.ts
Labels: backport 2.x, repeat-contributor, v2.15.0

#6822 [MD] Fix server sider endpoint validation by passing in request when creating datasource client
  changelogs/fragments/6822.yml
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
Labels: backport 2.x, multiple datasource, distinguished-contributor, v2.15.0

#6105 [Workspace]Import sample data to current workspace
  changelogs/fragments/6105.yml
  src/plugins/home/common/constants.ts
  src/plugins/home/public/application/application.test.tsx
  src/plugins/home/public/application/application.tsx
  src/plugins/home/public/application/components/home_app.js
  src/plugins/home/public/application/components/home_app.test.tsx
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/home/public/application/components/tutorial_directory.test.tsx
  src/plugins/home/public/application/index.ts
  src/plugins/home/public/application/opensearch_dashboards_services.mock.ts
  src/plugins/home/public/plugin.test.ts
  src/plugins/home/public/plugin.ts
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/index.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/index.ts
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
  src/plugins/home/server/services/sample_data/routes/install.test.ts
  src/plugins/home/server/services/sample_data/routes/install.ts
  src/plugins/home/server/services/sample_data/routes/list.test.ts
  src/plugins/home/server/services/sample_data/routes/list.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.test.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.ts
  src/plugins/workspace/public/components/workspace_overview/__snapshots__/workspace_overview.test.tsx.snap
  src/plugins/workspace/public/components/workspace_overview/all_get_started_cards.ts
Labels: backport 2.x, first-time-contributor, workspace, v2.15.0

#6554 [Workspace] Dashboard admin(groups/users) implementation
  changelogs/fragments/6554.yml
  config/opensearch_dashboards.yml
  src/core/server/mocks.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/core/server/utils/workspace.test.ts
  src/core/server/utils/workspace.ts
  src/legacy/server/config/schema.js
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: backport 2.x, first-time-contributor, workspace, v2.15.0

#6782 fix for quickrange to use datemath to parse datetime strings
  changelogs/fragments/6782.yml
  src/plugins/data/common/data_frames/data_frame_utils.test.ts
  src/plugins/data/common/data_frames/utils.ts
Labels: backport 2.x, first-time-contributor, v2.15.0

#6777 fix vega visualization error message not been formatted
  changelogs/fragments/6777.yml
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
Labels: backport 2.x, valued-contributor, v2.15.0

#6851 Fix index pattern data source reference not updated in sample data
  changelogs/fragments/6851.yml
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.15.0

#6855 Add example in create API for create index pattern, vega visualizatinn, dashboards for docs
  changelogs/fragments/6855.yml
  docs/_sidebar.md
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0

#6856 Add openAPI doc for saved_object find api
  changelogs/fragments/6856.yml
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0

#6859 Add OpenAPI specification for bulk create and bulk update saved object APIs
  changelogs/fragments/6859.yml
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0

#6861 [Data][Ui] Query Editor
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/query_editor/_index.scss
  src/plugins/data/public/ui/query_editor/_language_switcher.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/fetch_index_patterns.ts
  src/plugins/data/public/ui/query_editor/index.tsx
  src/plugins/data/public/ui/query_editor/language_switcher.tsx
  src/plugins/data/public/ui/query_editor/no_data_popover.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: distinguished-contributor, failed changeset

#6860 Add OpenAPI specification for bulk_get saved object APIs
  changelogs/fragments/6860.yml
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0

#6864 Add OpenAPI specification for update, delete and migrate saved object API
  changelogs/fragments/6864.yml
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0

#6867 [Backport 2.x] Add example in create API for create index pattern, vega visualizatinn, dashboards for docs
  changelogs/fragments/6855.yml
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, Skip-Changelog, v2.15.0

#6870 [2.x] Increment version to 2.15.0
  package.json
Labels: Skip-Changelog

#6827 [Multiple Datasource] Add data source selection service to support storing and getting selected data source updates
  changelogs/fragments/6827.yml
  examples/multiple_data_source_examples/public/components/data_source_view_example.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/service/data_source_selection_service.test.ts
  src/plugins/data_source_management/public/service/data_source_selection_service.ts
  src/plugins/home/public/application/components/tutorial_directory.test.tsx
  src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.test.tsx
Labels: valued-contributor

#6879 [Bug] Remove unused import and property
  changelogs/fragments/6879.yml
  examples/multiple_data_source_examples/public/components/data_source_view_example.tsx
Labels: backport 2.x, all-star-contributor, v2.15.0

#6843 [Multi Datasource] Unify getDefaultDataSourceId and export
  changelogs/fragments/6843.yml
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: valued-contributor

#6872 Add OpenAPI specification for import and export saved object api
  docs/openapi/saved_objects/examples/export_objects_response.yaml
  docs/openapi/saved_objects/examples/import.ndjson
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0

#6885 Add OpenAPI specifications for resolve import errors api
  changelogs/fragments/6885.yml
  docs/openapi/saved_objects/saved_objects.yml
Labels: docs, backport 2.x, v2.15.0
