Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-04, with the labels that each got.

#6299 [manual backport 2.x][MDS] Install Vega sample data (#6218)
  src/core/server/index.ts
  src/core/server/saved_objects/import/index.ts
  src/core/server/saved_objects/import/utils.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/test_utils/visualization_objects.json
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: multiple datasource, Skip-Changelog

#6287 [Multiple Datasource] Move data source selectable to its own folder, fix test and a few type errors for data source selectable component
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/index.ts
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/mocks.ts
Labels: seasoned-contributor

#6291 [BUG] Fix bug in data source aggregated view to change it to depend on displayAllCompatibleDataSources property to show the badge value
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
Labels: multiple datasource, seasoned-contributor, v2.14.0

#6225 [Workspace] Add workspace column to saved objects page
  CHANGELOG.md
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/workspace_column/index.ts
  src/plugins/workspace/public/components/workspace_column/workspace_colum.test.tsx
  src/plugins/workspace/public/components/workspace_column/workspace_column.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor, workspace

#6052 [Workspace]Add permission control logic for workspace
  CHANGELOG.md
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/index.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/core/server/saved_objects/index.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/permission_control/client.mock.ts
  src/plugins/workspace/server/permission_control/client.test.ts
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: first-time-contributor, workspace

#6302 [Multiple Datasource] Create examples about how to consume data source components
  examples/multiple_data_source_examples/README.md
  examples/multiple_data_source_examples/opensearch_dashboards.json
  examples/multiple_data_source_examples/public/application.tsx
  examples/multiple_data_source_examples/public/components/constants.ts
  examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_multi_selectable_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_selectable_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_selector_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_via_top_nav_menu.tsx
  examples/multiple_data_source_examples/public/components/data_source_view_example.tsx
  examples/multiple_data_source_examples/public/components/home.tsx
  examples/multiple_data_source_examples/public/components/types.ts
  examples/multiple_data_source_examples/public/index.ts
  examples/multiple_data_source_examples/public/plugin.ts
  examples/multiple_data_source_examples/public/types.ts
  examples/multiple_data_source_examples/tsconfig.json
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.14.0

#6315 [Multiple DataSource]Add datasource query for DataSourceView component to add label when only pass id
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, repeat-contributor, v2.14.0

#6333 [Multiple Datasource] Pass selected data sources to plugin consumers when the multi-select component initially loads
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
Labels: repeat-contributor

#6293 [Multiple Datasource] Enhanced data source selector with default datasource shows as first choice
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/dev_tools/public/application.tsx
  src/plugins/home/public/application/components/tutorial_directory.js
Labels: backport 2.x, multiple datasource, repeat-contributor, v2.14.0

#6193 [Chore] Adds untriaged only to issues not opened by collaborators
  .github/workflows/add-untriaged.yml
Labels: Skip-Changelog, distinguished-contributor

#6303 [Workspace] Add APIs to support plugin state in request
  CHANGELOG.md
  src/core/server/utils/index.ts
  src/core/server/utils/workspace.test.ts
  src/core/server/utils/workspace.ts
Labels: seasoned-contributor, workspace

#6327 Add default icon for selectable component and make sure the default datasource shows automatically
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/plugin.test.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: backport 2.x, multiple datasource, repeat-contributor, v2.14.0

#6348 [Multiple Datasource] Add installedPlugins list to data source saved …
  CHANGELOG.md
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/fetch_data_source_metadata.test.ts
  src/plugins/data_source/server/routes/fetch_data_source_metadata.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.14.0, version decoupling

#6270 [Workspace] Add update workspace page
  CHANGELOG.md
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_updater/index.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_updater_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: first-time-contributor, workspace

#6350 [2.x] Increment version to 2.14.0
  package.json
Labels: Skip-Changelog, v2.14.0

#6347 Relax the use of `ignoreVersionMismatch`
  CHANGELOG.md
  src/core/server/opensearch/opensearch_config.ts
Labels: backport 2.x, distinguished-contributor, v2.14.0

#5815 [Discover - datasource selector] Add extension group title and modal
  CHANGELOG.md
  package.json
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data_explorer/public/components/sidebar/index.test.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/__mock__/index.test.mock.ts
  yarn.lock
Labels: backport 2.x, repeat-contributor, v2.14.0

#6361 [MD]Read hideLocalCluster setting from yml and set in data source selector and data source menu
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/create_data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: all-star-contributor

#6371 [Tests] Add integtest.sh script for build to trigger Dashboards cypress tests
  integtest.sh
Labels: Skip-Changelog, distinguished-contributor

#6358 [Multiple DataSource] DataSourceSelectable support to render label by getting it from dataSourceOptions
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
Labels: repeat-contributor

#6357 [MD]Add default icon in multi-selectable picker
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/__snapshots__/data_source_filter_group.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_multi_selectable/__snapshots__/data_source_multi_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_filter_group.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_filter_group.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_option.test.tsx
  src/plugins/data_source_management/public/components/data_source_option.tsx
Labels: backport 2.x, multiple datasource, valued-contributor

#6248 Fix for checkForFunctionProperty so that order does not matter
  CHANGELOG.md
  src/plugins/vis_type_vega/public/data_model/utils.test.js
  src/plugins/vis_type_vega/public/data_model/utils.ts
Labels: bug, backport 2.x, repeat-contributor, v2.14.0

#6234 [Workspace] Filter left nav menu items according to the current workspace
  CHANGELOG.md
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: repeat-contributor, workspace

#6372 [MDS] Update Data source selector behavior for defaultOption
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, repeat-contributor, v2.14.0

#6400 [MD] Add OpenSearch cluster group label to top of single selectable dropdown
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
Labels: backport 2.x, multiple datasource, v2.14.0

#6387 [Backport 2.x][Workspace]Optional workspaces params in repository (#5949)
  config/opensearch_dashboards.yml
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
  src/core/server/saved_objects/import/check_conflicts.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/create.ts
  src/core/server/saved_objects/routes/export.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/resolve_import_errors.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/serialization/serializer.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/saved_objects/types.ts
  src/core/types/saved_objects.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: autocut, workspace, v2.14.0

#6364 Improve dynamic configurations by adding cache and simplifying client fetch
  CHANGELOG.md
  src/plugins/application_config/server/opensearch_config_client.test.ts
  src/plugins/application_config/server/opensearch_config_client.ts
  src/plugins/application_config/server/plugin.test.ts
  src/plugins/application_config/server/plugin.ts
  src/plugins/application_config/server/types.ts
  src/plugins/csp_handler/server/csp_handlers.test.ts
  src/plugins/csp_handler/server/csp_handlers.ts
Labels: backport 2.x, repeat-contributor, v2.14.0, backport 2.13

#6360 [OSCI] Removed KUI usage in visualizations -- Completion of Original PR
  CHANGELOG.md
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/visualizations/public/embeddable/disabled_lab_visualization.tsx
  src/plugins/visualizations/public/plugin.ts
  src/plugins/visualizations/public/services.ts
Labels: backport 2.x, technical debt, distinguished-contributor, v2.14.0

#6411 Fix test in PR 6360
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: test:unit, backport 2.x, Skip-Changelog, v2.14.0

#6413 Fix Lint Checker error due to unvisiable URL
  .lycheeexclude
Labels: bug, backport 2.x, Skip-Changelog, distinguished-contributor, v2.14.0

#6288 [Workspace] Add duplicate saved objects API
  CHANGELOG.md
  src/plugins/saved_objects/README.md
  src/plugins/workspace/README.md
  src/plugins/workspace/server/integration_tests/duplicate.test.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/routes/index.ts
Labels: first-time-contributor, workspace

#6409 [Backport 2.x] [Workspace] Add a workspace client in workspace plugin
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/workspace_client.mock.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
Labels: autocut, workspace, v2.14.0

#6365 [Workspace] Support workspace in saved objects client in server side.
  CHANGELOG.md
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
  src/core/server/saved_objects/import/check_conflicts.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/create.ts
  src/core/server/saved_objects/routes/export.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor, workspace

#6402 Replace control characters in logs
  CHANGELOG.md
  packages/osd-std/src/clean.test.ts
  packages/osd-std/src/clean.ts
  packages/osd-std/src/index.ts
  src/core/server/legacy/logging/legacy_logging_server.test.ts
  src/core/server/legacy/logging/legacy_logging_server.ts
  src/core/server/logging/layouts/conversions/message.ts
  src/core/server/logging/layouts/json_layout.test.ts
  src/core/server/logging/layouts/json_layout.ts
  src/core/server/logging/layouts/pattern_layout.test.ts
Labels: backport 1.3, backport 2.x, distinguished-contributor, v2.14.0

#6424 [Backport 2.x] [Workspace] Delete saved objects by workspace
  src/core/server/index.ts
  src/core/server/saved_objects/service/lib/repository.mock.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: autocut, workspace, v2.14.0

#6441 fix thresholds for repeat-contributor to avoid logical confusion on f…
  .github/workflows/github-workflow-badger.yml
Labels: Skip-Changelog, first-time-contributor

#6399 Validation succeed as long as status code in response is 200
  CHANGELOG.md
  src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
Labels: backport 2.x, multiple datasource, first-time-contributor, backport 2.13

#6444 [Backport 2.x][Workspace] Validate if workspace exists when setup inside a workspace
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/__snapshots__/workspace_fatal_error.test.tsx.snap
  src/plugins/workspace/public/components/workspace_fatal_error/index.ts
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.test.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
Labels: autocut, workspace, v2.14.0

#6437 Remove duplicate data source attribute interface
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.14.0

#6398 Update CSP handler to only query and modify frame ancestors instead of all CSP directives
  CHANGELOG.md
  src/plugins/csp_handler/README.md
  src/plugins/csp_handler/server/csp_handlers.test.ts
  src/plugins/csp_handler/server/csp_handlers.ts
  src/plugins/csp_handler/server/csp_header_utils.test.ts
  src/plugins/csp_handler/server/csp_header_utils.ts
Labels: backport 2.x, repeat-contributor, v2.14.0, backport 2.13

#6416 Refactor read-only component to cover more edge cases
  CHANGELOG.md
  examples/multiple_data_source_examples/public/components/data_source_view_example.tsx
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.14.0

#6449 Add a few dev guide based on observations
  DEVELOPER_GUIDE.md
Labels: all-star-contributor

#6448 Add dev guide for pull request
  DEVELOPER_GUIDE.md
Labels: all-star-contributor

#6438 [Multiple Datasource] Fix style of data source option inside popover for data source selector, selectable, multi select components
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_item/data_source_item.test.tsx
  src/plugins/data_source_management/public/components/data_source_item/data_source_item.tsx
  src/plugins/data_source_management/public/components/data_source_item/index.ts
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_multi_selectable/__snapshots__/data_source_filter_group.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_filter_group.scss
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_filter_group.tsx
  src/plugins/data_source_management/public/components/data_source_option.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.scss
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.scss
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.14.0

#6451 [Backport 2.x][Workspace] Add base path when parsing url in http service
  src/core/public/http/http_service.test.ts
  src/core/public/http/http_service.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
Labels: autocut, workspace, v2.14.0

#6474 fix dynamic config API calls to pass correct input
  CHANGELOG.md
  src/plugins/application_config/server/routes/index.test.ts
  src/plugins/application_config/server/routes/index.ts
Labels: backport 2.x, repeat-contributor, v2.14.0, backport 2.13

#6431 [MD] Add dropdown header to data source single selector
  CHANGELOG.md
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.scss
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.test.tsx
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
  src/plugins/data_source_management/public/components/drop_down_header/index.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: enhancement, backport 2.x, multiple datasource, v2.14.0

#6395 [Multiple DataSource] Do not support import data source object to Local cluster when not enable data source
  CHANGELOG.md
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/import/validate_object_id.test.ts
  src/core/server/saved_objects/import/validate_object_id.ts
  src/core/server/saved_objects/routes/import.ts
  src/plugins/saved_objects_management/public/lib/import_file.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
Labels: backport 2.x, valued-contributor, v2.14.0

#6440 [Multiple Datasource] Add error state to all data source menu components to show error component and consolidate all fetch errors
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_error_menu/data_source_error_menu.tsx
  src/plugins/data_source_management/public/components/data_source_error_menu/index.ts
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.14.0

#6298 [MDS] TSVB Support
  CHANGELOG.md
  src/plugins/data/server/index.ts
  src/plugins/data/server/index_patterns/index.ts
  src/plugins/data/server/index_patterns/routes.ts
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_selector/index.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/vis_type_timeseries/common/constants.ts
  src/plugins/vis_type_timeseries/common/vis_schema.ts
  src/plugins/vis_type_timeseries/opensearch_dashboards.json
  src/plugins/vis_type_timeseries/public/application/components/annotations_editor.js
  src/plugins/vis_type_timeseries/public/application/components/index_pattern.js
  src/plugins/vis_type_timeseries/public/application/components/lib/create_data_source_change_handler.test.ts
  src/plugins/vis_type_timeseries/public/application/components/lib/create_data_source_change_handler.ts
  src/plugins/vis_type_timeseries/public/application/components/vis_editor.js
  src/plugins/vis_type_timeseries/public/application/lib/fetch_fields.js
  src/plugins/vis_type_timeseries/public/plugin.ts
  src/plugins/vis_type_timeseries/public/services.ts
  src/plugins/vis_type_timeseries/server/lib/get_fields.ts
  src/plugins/vis_type_timeseries/server/lib/search_strategies/strategies/abstract_search_strategy.test.js
  src/plugins/vis_type_timeseries/server/lib/search_strategies/strategies/abstract_search_strategy.ts
  src/plugins/vis_type_timeseries/server/lib/vis_data/get_annotations.js
  src/plugins/vis_type_timeseries/server/lib/vis_data/get_series_data.js
  src/plugins/vis_type_timeseries/server/lib/vis_data/get_table_data.js
  src/plugins/vis_type_timeseries/server/plugin.ts
  src/plugins/vis_type_timeseries/server/routes/fields.ts
Labels: backport 2.x, multiple datasource, repeat-contributor, v2.14.0

#5519 [OSCI][FEAT] Changelog Project - PoC Changelog and release notes automation tool - OpenSearch Dashboards
  .github/pull_request_template.md
  .github/workflows/changelog_verifier.yml
  .github/workflows/opensearch_changelog_workflow.yml
  changelogs/README.md
  package.json
  scripts/generate_release_note.js
  src/dev/generate_release_note.ts
  src/dev/generate_release_note_helper.ts
Labels: backport 2.x, first-time-contributor, failed changeset, v2.14.0

#6385 [MDS] Support for Timeline
  CHANGELOG.md
  src/plugins/vis_type_timeline/opensearch_dashboards.json
  src/plugins/vis_type_timeline/public/helpers/timeline_request_handler.ts
  src/plugins/vis_type_timeline/server/handlers/chain_runner.js
  src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.test.ts
  src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.ts
  src/plugins/vis_type_timeline/server/lib/services.ts
  src/plugins/vis_type_timeline/server/plugin.ts
  src/plugins/vis_type_timeline/server/routes/run.ts
  src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
  src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
  src/plugins/vis_type_timeline/server/types.ts
Labels: backport 2.x, repeat-contributor, v2.15.0

#6494 [Manual][Backport 2.x][MD] Add dropdown header to Data source single selector (#6431)
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.scss
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.test.tsx
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
  src/plugins/data_source_management/public/components/drop_down_header/index.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: multiple datasource, Skip-Changelog

#6465 Modify the button of selectable component to fix the title overflow issue
  CHANGELOG.md
  src/plugins/data_source_management/public/components/button_title.scss
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
Labels: valued-contributor

#6496 [BUG] Add error body instead of swallow it in DataSourceError
  src/plugins/data_source/server/lib/error.test.ts
  src/plugins/data_source/server/lib/error.ts
Labels: backport 2.x, Skip-Changelog, all-star-contributor, v2.14.0

#6378 [Workspace] Add permission tab to workspace create update page
  CHANGELOG.md
  src/core/types/saved_objects.ts
  src/core/types/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: repeat-contributor

#6499 add empty state and test except the aggregated view
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/no_data_source/index.tsx
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.test.tsx
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
Labels: Skip-Changelog, valued-contributor

#6498 [BUG] Check for duplicate data source id before fetching the data sources in index pattern selector
  src/plugins/data/public/ui/index_pattern_select/index_pattern_select.test.tsx
  src/plugins/data/public/ui/index_pattern_select/index_pattern_select.tsx
Labels: backport 2.x, multiple datasource, Skip-Changelog, all-star-contributor, v2.14.0

#6455 Hide datasource and settings menu in dashboard management when in workspace
  CHANGELOG.md
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: repeat-contributor, workspace

#6458 [Workspace] Add Workspace filter to saved objects management page
  CHANGELOG.md
  src/core/public/index.ts
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/lib/fetch_export_by_type_and_search.ts
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/lib/parse_query.test.ts
  src/plugins/saved_objects_management/public/lib/parse_query.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/utils.test.ts
  src/plugins/saved_objects_management/public/utils.ts
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: valued-contributor, workspace, v2.14.0

#6459 [Workspace] fix apps are missing when updating a workspace
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_updater/index.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_updater_app.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.ts
Labels: Skip-Changelog, repeat-contributor, workspace

#6497 UI change for datasource view picker to enable selectable
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.scss
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
Labels: backport 2.x, multiple datasource, valued-contributor, failed changeset, v2.14.0

#6515 For selectable component, remove group label and close popover after selection
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
Labels: backport 2.x, multiple datasource, Skip-Changelog, valued-contributor, v2.14.0

#6500 [MDS] Refactor DataSourceAggregatedView
  examples/multiple_data_source_examples/public/application.tsx
  examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
  examples/multiple_data_source_examples/public/components/home.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
Labels: backport 2.x, multiple datasource, Skip-Changelog, valued-contributor, v2.14.0

#6514 [Multiple Datasource] add popover for Data Source empty state
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.scss
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.test.tsx
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
Labels: backport 2.x, multiple datasource, Skip-Changelog, valued-contributor, v2.14.0

#6477 [MD]Refactor dev tool to use dataSourceManagement.ui API to get DataSourceSelector
  changelogs/fragments/6477.yml
  src/plugins/dev_tools/opensearch_dashboards.json
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/plugin.ts
Labels: backport 2.x, multiple datasource, distinguished-contributor, v2.14.0

#6531 [Backport 2.x][Workspace]Add permission control logic for workspace
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/index.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/core/server/saved_objects/index.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/permission_control/client.mock.ts
  src/plugins/workspace/server/permission_control/client.test.ts
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: Skip-Changelog, workspace, v2.14.0

#6549 [Multiple Datasource]update no data source text font and button size
  CHANGELOG.md
  src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
Labels: Skip-Changelog, valued-contributor

#6527 [BUG] Fix permission check failed with empty workspace for find method
  changelogs/fragments/6527.yml
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: valued-contributor

#6544 Refactor saved object management plugin to use datasourceManagement ui API to get DataSourceSelector
  changelogs/fragments/6544.yml
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
Labels: backport 2.x, multiple datasource, distinguished-contributor, v2.14.0

#6545 Fix on data source selectable and readonly component are not consistent
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
Labels: backport 2.x, multiple datasource, valued-contributor, v2.14.0

#6541 [MDS] Refactor dropdown header + Aggregate view UI
  examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.14.0

#6560 [Manual backport 2.x][MDS] Refactor dropdown header + Aggregate view UI (#6541)
  examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
  examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
Labels: v2.14.0

#6524 [Workspace] Handle data sources and advanced settings as global object.
  changelogs/fragments/6524.yml
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: seasoned-contributor, workspace

#6566 [MDS] Update Selectable props
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.14.0

#6575 [Workspace] Make dashboards management available
  changelogs/fragments/6575.yml
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: first-time-contributor, workspace

#6589 [Discover - Testing purpose only] data selector enhancement
  src/plugins/data/public/data_sources/datasource/datasource.ts
  src/plugins/data/public/data_sources/datasource/factory.ts
  src/plugins/data/public/data_sources/datasource/index.ts
  src/plugins/data/public/data_sources/datasource/types.ts
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/data_sources/datasource_selector/types.ts
  src/plugins/data/public/data_sources/datasource_services/datasource_service.ts
  src/plugins/data/public/data_sources/datasource_services/index.ts
  src/plugins/data/public/data_sources/datasource_services/types.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.ts
  src/plugins/data/public/data_sources/register_default_datasource.ts
  src/plugins/data/public/index.ts
  src/plugins/data_explorer/public/components/sidebar/index.tsx
Labels: repeat-contributor, failed changeset

#6570 [Multiple Datasource] Add new error database icon to handle error state for data source component
  src/plugins/data_source_management/public/components/custom_database_icon/error_icon.tsx
  src/plugins/data_source_management/public/components/custom_database_icon/index.ts
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_error_menu/data_source_error_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/toast_button/index.ts
  src/plugins/data_source_management/public/components/toast_button/reload_button.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, Skip-Changelog, all-star-contributor, v2.14.0

#6595 [MQL] support different query languages
  package.json
  packages/opensearch-datemath/index.d.ts
  packages/opensearch-datemath/index.js
  packages/osd-opensearch/src/cli_commands/snapshot.js
  packages/osd-opensearch/src/cluster.js
  src/cli/serve/serve.js
  src/plugins/data/common/constants.ts
  src/plugins/data/common/data_frames/_df_cache.ts
  src/plugins/data/common/data_frames/fields/index.ts
  src/plugins/data/common/data_frames/fields/types.ts
  src/plugins/data/common/data_frames/index.ts
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/data/common/index.ts
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
  src/plugins/data/common/opensearch_query/opensearch_query/build_opensearch_query.ts
  src/plugins/data/common/opensearch_query/opensearch_query/index.ts
  src/plugins/data/common/search/opensearch_search/types.ts
  src/plugins/data/common/search/search_source/create_search_source.test.ts
  src/plugins/data/common/search/search_source/mocks.ts
  src/plugins/data/common/search/search_source/search_source.test.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/common/search/search_source/types.ts
  src/plugins/data/common/search/types.ts
  src/plugins/data/common/types.ts
  src/plugins/data/public/data_sources/datasource_services/datasource_service.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/search/search_interceptor.ts
  src/plugins/data/public/search/search_service.ts
  src/plugins/data/public/search/types.ts
  src/plugins/data/public/services.ts
  src/plugins/data/public/types.ts
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/index_pattern_select/index_pattern_select.tsx
  src/plugins/data/public/ui/query_string_input/_index.scss
  src/plugins/data/public/ui/query_string_input/_language_switcher.scss
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/types.ts
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data/server/search/opensearch_search/get_default_search_params.ts
  src/plugins/data/server/search/search_service.ts
  src/plugins/data/server/search/types.ts
  src/plugins/data/server/ui_settings.ts
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_edit.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  yarn.lock
Labels: distinguished-contributor, failed changeset

#6594 [Multiple Datasource] Pass data source menu to top nav via function instead of using component
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/index.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.test.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: Skip-Changelog, all-star-contributor

#6598 [MQL] Cleanup unused helper function
  src/plugins/data/common/opensearch_query/opensearch_query/index.ts
Labels: distinguished-contributor, failed changeset

#6425 Update link-checker and clean up ignore-list
  .github/workflows/links_checker.yml
  .lycheeexclude
  .lycheeignore
  CHANGELOG.md
  test/functional/services/common/browser.ts
  test/functional/services/lib/web_element_wrapper/web_element_wrapper.ts
Labels: backport 2.x, distinguished-contributor, v2.14.0, operational excellence

#6428 Bump `codecov/codecov-action` to v4
  .github/workflows/build_and_test_workflow.yml
Labels: backport 2.x, Skip-Changelog, distinguished-contributor

#6510 [Workspace] introducing workspace level ui settings
  src/core/types/workspace.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_ui_settings_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: repeat-contributor, workspace, failed changeset

#6609 Fix wrong data source management filter id
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, repeat-contributor, workspace

#6427 [Workspace] Add workspaceAvailability field into application
  changelogs/fragments/6427.yml
  src/core/public/application/application_service.test.ts
  src/core/public/application/application_service.tsx
  src/core/public/application/index.ts
  src/core/public/application/integration_tests/application_service.test.tsx
  src/core/public/application/types.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_links/to_nav_link.test.ts
  src/core/public/chrome/nav_links/to_nav_link.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/plugins/home/public/plugin.ts
  src/plugins/opensearch_dashboards_overview/public/plugin.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: seasoned-contributor, workspace

#6617 [Multiple Datasource] Fix style for mobile view of a few data source components
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.scss
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.scss
Labels: Skip-Changelog, all-star-contributor, v2.14.0

#6126 [ignoreFilterIfFieldNotInIndex] Parse query string filters to determine if fields match an index
  package.json
  src/plugins/data/common/opensearch_query/opensearch_query/filter_matches_index.test.ts
  src/plugins/data/common/opensearch_query/opensearch_query/filter_matches_index.ts
  src/plugins/data/common/opensearch_query/opensearch_query/index.ts
  src/plugins/data/public/ui/filter_bar/filter_item.tsx
  yarn.lock
Labels: backport 2.x, first-time-contributor, v2.14.0

#6599 Improve the perceived performance of Discover
  changelogs/fragments/6599.yml
  package.json
  src/plugins/discover/public/application/components/data_grid/data_grid.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  test/functional/apps/dashboard/dashboard_time_picker.js
  test/functional/apps/home/_sample_data.ts
  test/functional/services/dashboard/expectations.ts
  yarn.lock
Labels: backport 2.x, distinguished-contributor, failed changeset, v2.14.0

#6625 [Workspace] Hide dashboard overview
  changelogs/fragments/6625.yml
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: repeat-contributor

#6626 [Workspace] fix: Navigate to apps by using hard refresh in collasibleNavHeader
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: bug, Skip-Changelog, repeat-contributor, workspace, v2.14.0

#6473 Update dev docs
  docs/_sidebar.md
Labels: Skip-Changelog, repeat-contributor

#6604 [MD]Fix data source link to point to correct page, and use in page redirect instead of reloading
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.test.tsx
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
  src/plugins/data_source_management/public/plugin.ts
Labels: backport 2.x, multiple datasource, distinguished-contributor, v2.14.0

#6630 Lock Chrome version until ChromeDriver's release pipeline is fixed
  .github/workflows/build_and_test_workflow.yml
Labels: Skip-Changelog, distinguished-contributor

#6584 [Workspace] Add workspace overview page
  changelogs/fragments/6584.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_overview/__snapshots__/workspace_overview.test.tsx.snap
  src/plugins/workspace/public/components/workspace_overview/all_get_started_cards.ts
  src/plugins/workspace/public/components/workspace_overview/getting_start_card.test.tsx
  src/plugins/workspace/public/components/workspace_overview/getting_start_card.tsx
  src/plugins/workspace/public/components/workspace_overview/getting_start_modal.test.tsx
  src/plugins/workspace/public/components/workspace_overview/getting_start_modal.tsx
  src/plugins/workspace/public/components/workspace_overview/index.scss
  src/plugins/workspace/public/components/workspace_overview/types.ts
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.test.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview_content.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview_settings.tsx
  src/plugins/workspace/public/components/workspace_overview_app.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor, workspace, v2.14.0

#6543 [MDS] TSVB Add import logic
  src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
  src/core/server/saved_objects/import/check_conflict_for_data_source.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/import/utils.test.ts
  src/core/server/saved_objects/import/utils.ts
  src/plugins/vis_type_timeseries/server/lib/services.ts
  src/plugins/vis_type_timeseries/server/lib/test_utils/test_params.json
  src/plugins/vis_type_timeseries/server/lib/timeseries_visualization_client_wrapper.test.ts
  src/plugins/vis_type_timeseries/server/lib/timeseries_visualization_client_wrapper.ts
  src/plugins/vis_type_timeseries/server/plugin.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.14.0

#6559 Extract the button component for datasource picker to avoid duplicate code
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/popover_button/popover_button.test.tsx
  src/plugins/data_source_management/public/components/popover_button/popover_button.tsx
Labels: backport 2.x, multiple datasource, valued-contributor, v2.14.0

#6631 [MD] Add endpoint validation to create data source API
  src/plugins/data_source/server/data_source_service.mock.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/fetch_data_source_metadata.test.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/util/constants.ts
Labels: distinguished-contributor, v2.14.0

#6648 Fix datasource conntection failure
  changelogs/fragments/6648.yml
  src/plugins/data_source/server/plugin.ts
Labels: seasoned-contributor

#6651 [Manual backport 2.x][MD]Fix datasource connection failure (#6648)
  changelogs/fragments/6648.yml
  src/plugins/data_source/server/plugin.ts
Labels: multiple datasource, Skip-Changelog, v2.14.0

#6650 [Workspace] fix: update DSM id in workspace
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#6654 Support multi data source in Region map
  CHANGELOG.md
  src/plugins/region_map/opensearch_dashboards.json
  src/plugins/region_map/public/choropleth_layer.js
  src/plugins/region_map/public/region_map_type.js
  src/plugins/region_map/public/region_map_visualization.js
  src/plugins/region_map/public/services.ts
  src/plugins/region_map/server/routes/opensearch.ts
Labels: backport 2.x, Skip-Changelog, repeat-contributor, v2.14.0

#5327 Add autocommit styles to ace overrides
  CHANGELOG.md
  src/core/public/styles/_ace_overrides.scss
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.14.0

#6590 [Manual Backport 1.3] Replace control characters before logging (#6402)
  packages/osd-std/src/clean.test.ts
  packages/osd-std/src/clean.ts
  packages/osd-std/src/index.ts
  src/core/server/legacy/logging/legacy_logging_server.test.ts
  src/core/server/legacy/logging/legacy_logging_server.ts
  src/core/server/logging/layouts/conversions/message.ts
  src/core/server/logging/layouts/json_layout.test.ts
  src/core/server/logging/layouts/json_layout.ts
  src/core/server/logging/layouts/pattern_layout.test.ts
Labels: autocut

#6669 [Workspace] Fix: optimization on handling invalid workspace id in workspace_ui_settings wrapper
  changelogs/fragments/6669.yml
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: bug, backport 2.x, seasoned-contributor, workspace, v2.14.0

#6668 [Workspace] Fix: keep disallowed types when importing with overwrite
  changelogs/fragments/6668.yml
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: bug, backport 2.x, seasoned-contributor, workspace, v2.14.0

#5652 Feat (core): Make theme settings user-specific and user-configurable
  CHANGELOG.md
  docs/theme.md
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/fonts.tsx
  src/core/server/rendering/views/styles.tsx
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/core/server/rendering/views/theme.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/types/ui_settings.ts
  src/legacy/ui/ui_render/bootstrap/app_bootstrap.js
  src/legacy/ui/ui_render/bootstrap/bootstrap.js.hbs
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/components/field/field.tsx
  src/plugins/advanced_settings/public/management_app/lib/to_editable_config.ts
  src/plugins/advanced_settings/public/management_app/types.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/public/register_nav_control.tsx
  src/plugins/opensearch_dashboards_usage_collection/server/collectors/management/schema.ts
  src/plugins/telemetry/schema/oss_plugins.json
  test/functional/apps/visualize/_custom_branding.ts
  test/functional/screenshots/baseline/tsvb_dashboard.png
Labels: backport 2.x, distinguished-contributor, failed changeset, v2.14.0

#6681 [Manual Backport 2.x] Feat (core): Make theme settings user-specific and user-configurable (#5652)
  CHANGELOG.md
  docs/theme.md
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/fonts.tsx
  src/core/server/rendering/views/styles.tsx
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/core/server/rendering/views/theme.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/types/ui_settings.ts
  src/legacy/ui/ui_render/bootstrap/app_bootstrap.js
  src/legacy/ui/ui_render/bootstrap/bootstrap.js.hbs
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/components/field/field.tsx
  src/plugins/advanced_settings/public/management_app/lib/to_editable_config.ts
  src/plugins/advanced_settings/public/management_app/types.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/public/register_nav_control.tsx
  src/plugins/opensearch_dashboards_usage_collection/server/collectors/management/schema.ts
  src/plugins/telemetry/schema/oss_plugins.json
  test/functional/apps/visualize/_custom_branding.ts
  test/functional/screenshots/baseline/tsvb_dashboard.png
Labels: v2.14.0

#6553 feat: Add `rightNavigationButton` component in chrome service for applications to register and add dev tool to top right navigation
  CHANGELOG.md
  src/core/public/chrome/constants.ts
  src/core/public/chrome/index.ts
  src/core/public/chrome/ui/header/__snapshots__/right_navigation_button.test.tsx.snap
  src/core/public/chrome/ui/header/index.ts
  src/core/public/chrome/ui/header/right_navigation_button.test.tsx
  src/core/public/chrome/ui/header/right_navigation_button.tsx
  src/core/public/chrome/ui/index.ts
  src/core/public/index.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dev_tools/opensearch_dashboards.json
  src/plugins/dev_tools/public/plugin.ts
Labels: backport 2.x, Skip-Changelog, repeat-contributor, v2.14.0

#6460 [VisBuilder ] Fix filter and query bugs in the saved objects
  CHANGELOG.md
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.test.tsx
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/saved_visualizations/transforms.ts
  src/plugins/visualizations/public/index.ts
Labels: bug, vis builder, backport 2.x, Skip-Changelog, distinguished-contributor, v2.14.0

#6636 [BUG] Allow Save in Top Nav Menu to capture filter and query
  changelogs/fragments/6636.yml
  src/plugins/vis_builder/public/application/components/top_nav.tsx
Labels: vis builder, backport 2.x, distinguished-contributor, failed changeset, v2.14.0

#6688 [Chore] Fix Link checker for adobe urls
  .lycheeignore
Labels: backport 1.3, backport 2.x, Skip-Changelog, distinguished-contributor, v2.14.0

#6571 [Discover] Data selector enhancement
  changelogs/fragments/6571.yml
  src/plugins/data/public/data_sources/constants.tsx
  src/plugins/data/public/data_sources/datasource/datasource.ts
  src/plugins/data/public/data_sources/datasource/factory.test.ts
  src/plugins/data/public/data_sources/datasource/factory.ts
  src/plugins/data/public/data_sources/datasource/index.ts
  src/plugins/data/public/data_sources/datasource/types.ts
  src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.test.tsx
  src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/data_sources/datasource_selector/types.ts
  src/plugins/data/public/data_sources/datasource_services/datasource_service.test.ts
  src/plugins/data/public/data_sources/datasource_services/datasource_service.ts
  src/plugins/data/public/data_sources/datasource_services/index.ts
  src/plugins/data/public/data_sources/datasource_services/types.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.test.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.ts
  src/plugins/data/public/data_sources/register_default_datasource.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data_explorer/public/components/sidebar/index.test.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/__mock__/index.test.mock.ts
Labels: backport 2.x, repeat-contributor, data explorer, v2.14.0
