Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-07, with the labels that each got.

#7060 [navigation-next] feat: introduce new interface for group
  changelogs/fragments/7060.yml
  src/core/public/chrome/README.md
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_group/index.ts
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/utils.test.ts
  src/core/public/chrome/utils.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/types/index.ts
  src/core/types/nav_group.ts
  src/core/utils/default_app_categories.ts
  src/core/utils/default_nav_groups.ts
  src/core/utils/index.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/home/server/ui_settings.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, navigation

#6923 Close any open flyouts when changing view mode of the dashboard
  changelogs/fragments/6923.yml
  src/core/public/overlays/flyout/__snapshots__/flyout_service.test.tsx.snap
  src/core/public/overlays/flyout/flyout_service.mock.ts
  src/core/public/overlays/flyout/flyout_service.test.tsx
  src/core/public/overlays/flyout/flyout_service.tsx
  src/core/public/overlays/overlay_service.mock.ts
  src/core/public/overlays/overlay_service.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
Labels: backport 2.x, distinguished-contributor, v2.16.0

#7079 Move decideClient and decideLegacyClient to data source plugin util
  src/plugins/data/server/index.ts
  src/plugins/data/server/index_patterns/index.ts
  src/plugins/data/server/index_patterns/routes.ts
  src/plugins/data/server/search/opensearch_search/decide_client.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
  src/plugins/data_source/common/util/decide_client.test.ts
  src/plugins/data_source/common/util/decide_client.ts
  src/plugins/data_source/common/util/index.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/data_source/server/index.ts
  src/plugins/vis_type_timeseries/server/lib/get_fields.ts
Labels: refactor, multiple datasource, distinguished-contributor, v2.16.0

#7136 [Backport 2.x][navigation-next] feat: introduce new interface for group (#7060)
  changelogs/fragments/7060.yml
  src/core/public/chrome/README.md
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_group/index.ts
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/utils.test.ts
  src/core/public/chrome/utils.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/types/index.ts
  src/core/types/nav_group.ts
  src/core/utils/default_app_categories.ts
  src/core/utils/default_nav_groups.ts
  src/core/utils/index.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/home/server/ui_settings.ts
Labels: Skip-Changelog, v2.16.0

#7103 [Workspace] Capabilities service add dashboard admin flag
  changelogs/fragments/7103.yml
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0

#7149 [CVE] Bump up axios to 1.7.2 to fix SNYK-JS-AXIOS-6144788
  changelogs/fragments/7149.yml
  yarn.lock
Labels: cve, backport 2.x, seasoned-contributor, v2.16.0

#7153 [CVE-2024-37890] Bump ws from `8.5.0` to `8.17.1` and from `7.5.7` to `7.5.10`
  changelogs/fragments/7153.yml
  yarn.lock
Labels: cve, backport 2.x, distinguished-contributor, v2.16.0

#7159 Antlr autocomplete
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/dql/generated/DQLLexer.interp
  src/plugins/data/public/antlr/dql/generated/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/generated/DQLLexer.ts
  src/plugins/data/public/antlr/dql/generated/DQLParser.interp
  src/plugins/data/public/antlr/dql/generated/DQLParser.tokens
  src/plugins/data/public/antlr/dql/generated/DQLParser.ts
  src/plugins/data/public/antlr/dql/generated/DQLParserListener.ts
  src/plugins/data/public/antlr/dql/generated/DQLParserVisitor.ts
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.tokens
  src/plugins/data/public/antlr/dql/grammar/DQLLexer.g4
  src/plugins/data/public/antlr/dql/grammar/DQLParser.g4
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: repeat-contributor, failed changeset

#7160 dql Antlr autocomplete
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx
Labels: repeat-contributor, failed changeset

#7146 [Multiple Datasource][Version Decoupling] Add support of required backend plugins check on data sources
  changelogs/fragments/7146.yml
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/plugin.test.ts
  src/core/server/plugins/plugin.ts
  src/core/server/plugins/types.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
  src/plugins/index_pattern_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, version decoupling, v2.16.0

#7157 [Discover-next] add datasource container
  changelogs/fragments/7157.yml
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/types.ts
  src/plugins/data/public/ui/ui_service.ts
Labels: backport 2.x, distinguished-contributor, v2.16.0, discover-next

#7101 [Workspace][Data Source] Support data source assignment in workspace
  changelogs/fragments/7101.yml
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.mock.ts
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/plugins/workspace/common/types.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0

#7152 [navigation-next]feat: add description field in App.
  changelogs/fragments/7152.yml
  src/core/public/application/application_service.test.ts
  src/core/public/application/types.ts
  src/core/public/chrome/nav_links/to_nav_link.test.ts
Labels: backport 2.x, all-star-contributor, v2.16.0, navigation

#7125 [Workspace]Restrict saved objects finding when workspace enabled
  changelogs/fragments/7125.yml
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0

#7172 [Multiple Datasource][Version Decoupling] Add data source version and installed plugins in MDS data source viewer returns
  changelogs/fragments/7172.yml
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, version decoupling, v2.16.0

#7115 [Workspace] feat: comply recent items with workspace
  changelogs/fragments/7115.yml
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/recently_accessed/recently_accessed_service.test.ts
  src/core/public/chrome/recently_accessed/recently_accessed_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/nav_link.test.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/core_system.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0

#7165 [Workspace] Delete the virtual global workspace
  changelogs/fragments/7165.yml
  src/core/public/index.ts
  src/core/server/index.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0

#7183 [Discover-next] (QueryEditorExtensions) change isEnabled to an observable
  changelogs/fragments/7183.yml
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
Labels: backport 2.x, valued-contributor, v2.16.0, discover-next

#7196 [admin] add Viraj to be a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/7196.yml
Labels: backport 2.x, v2.16.0

#7186 [Workspace]Add instruction for force enable new navigation for workspace
  config/opensearch_dashboards.yml
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, workspace, v2.16.0

#7198 [Look&feel] Use small List Groups
  src/plugins/data/public/ui/saved_query_management/saved_query_list_item.tsx
  src/plugins/saved_objects/public/finder/saved_object_finder.tsx
Labels: backport 2.x, distinguished-contributor, v2.16.0, look & feel

#7156 [Look&Feel] Standard Paragraph Text Size
  src/core/public/application/ui/app_not_found_screen.tsx
  src/core/public/core_app/errors/url_overflow_ui.tsx
  src/core/public/core_app/status/components/server_status.tsx
  src/core/public/fatal_errors/__snapshots__/fatal_errors_screen.test.tsx.snap
  src/core/public/fatal_errors/fatal_errors_screen.tsx
  src/plugins/console/public/application/components/__snapshots__/overwrite_modal.test.tsx.snap
  src/plugins/console/public/application/components/import_flyout.tsx
  src/plugins/console/public/application/components/overwrite_modal.tsx
  src/plugins/console/public/application/components/something_went_wrong_callout.tsx
  src/plugins/console/public/application/components/welcome_panel.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/__snapshots__/clone_modal.test.js.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/clone_modal.tsx
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/dashboard_empty_screen.tsx
  src/plugins/data/public/index_patterns/index_patterns/on_unsupported_time_pattern.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/saved_query_form/save_query_form.tsx
  src/plugins/data_explorer/public/components/no_view.tsx
  src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/embeddable/public/lib/embeddables/embeddable_root.tsx
  src/plugins/inspector/public/views/data/components/__snapshots__/data_view.test.tsx.snap
  src/plugins/inspector/public/views/data/components/data_view.tsx
  src/plugins/management/public/components/landing/landing.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  src/plugins/opensearch_dashboards_react/public/util/mount_point_portal.test.tsx
  src/plugins/opensearch_dashboards_react/public/util/mount_point_portal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/overwrite_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/vis_builder/public/application/components/right_nav.tsx
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_type_timeseries/public/application/components/annotations_editor.js
  src/plugins/vis_type_timeseries/public/application/components/markdown_editor.js
  src/plugins/vis_type_timeseries/public/application/components/panel_config/table.js
  src/plugins/visualizations/public/wizard/__snapshots__/new_vis_modal.test.tsx.snap
  src/plugins/visualizations/public/wizard/type_selection/new_vis_help.test.tsx
  src/plugins/visualizations/public/wizard/type_selection/new_vis_help.tsx
  src/plugins/visualizations/public/wizard/type_selection/vis_help_text.tsx
  src/plugins/visualize/public/application/utils/get_table_columns.tsx
Labels: ux / ui, refactor, backport 2.x, Skip-Changelog, distinguished-contributor, v2.16.0, look & feel

#7197 [OE] skip running tests if CODEOWNERS was change
  .github/workflows/build_and_test_workflow.yml
  changelogs/fragments/7197.yml
Labels: backport 2.x, operational excellence, v2.16.0

#7211 feat: address styling of non-primary buttons by making secondary/empty
  changelogs/fragments/7211.yml
  src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/input_control_vis/public/components/editor/__snapshots__/controls_tab.test.tsx.snap
  src/plugins/input_control_vis/public/components/editor/controls_tab.tsx
  src/plugins/input_control_vis/public/components/vis/__snapshots__/input_control_vis.test.tsx.snap
  src/plugins/input_control_vis/public/components/vis/input_control_vis.tsx
  src/plugins/share/public/components/url_panel_content.tsx
Labels: backport 2.x, first-time-contributor, v2.16.0, look & feel

#7192 [Look&Feel] Refactor to use semantic headers for page, modal & flyout
  changelogs/fragments/7192.yml
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/__snapshots__/clone_modal.test.js.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/clone_modal.tsx
  src/plugins/dashboard/public/application/utils/get_no_items_message.tsx
  src/plugins/data/public/ui/saved_query_form/save_query_form.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/inspector/public/ui/__snapshots__/inspector_panel.test.tsx.snap
  src/plugins/inspector/public/ui/inspector_panel.tsx
  src/plugins/management/public/components/landing/landing.tsx
  src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/__snapshots__/overview_page_header.test.tsx.snap
  src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.tsx
  src/plugins/saved_objects/public/save_modal/__snapshots__/saved_object_save_modal.test.tsx.snap
  src/plugins/saved_objects/public/save_modal/saved_object_save_modal.tsx
  src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/object_view/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/visualize/public/application/utils/get_table_columns.tsx
Labels: ux / ui, backport 2.x, distinguished-contributor, v2.16.0, look & feel

#7200 [Look&Feel] Update Popover Padding Size
  changelogs/fragments/7200.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field.tsx
Labels: backport 2.x, first-time-contributor, v2.16.0, look & feel

#7195 [Look&Feel] Consistency of Plus Icons
  changelogs/fragments/7195.yml
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/create_button.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_listing/create_button.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/get_top_nav_config.ts
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/dashboard_empty_screen.tsx
  src/plugins/dashboard/public/application/utils/get_no_items_message.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/saved_object_finder_create_new.tsx
  src/plugins/index_pattern_management/public/components/create_button/create_button.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  src/plugins/vis_default_editor/public/components/controls/date_ranges.tsx
  src/plugins/visualize/public/application/utils/get_table_columns.tsx
Labels: backport 2.x, first-time-contributor, v2.16.0, look & feel

#7133 [Workspace]Refactor workspace form UI
  changelogs/fragments/7133.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_create_action_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0

#7166 [Navigation-Next] Add current nav group into chrome service
  changelogs/fragments/7166.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, navigation

#7225 [Manual] [Backport 2.x] [Look&Feel] Update Popover Padding Size
  changelogs/fragments/7200.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field.tsx
Labels: Skip-Changelog, failed changeset

#7220 [OE] Improved untriaged workflow
  .github/workflows/add-untriaged.yml
Labels: Skip-Changelog, distinguished-contributor, operational excellence

#7226 [Look&Feel] Update dashboards & visualization list title to use standard size
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
Labels: backport 2.x, Skip-Changelog, v2.16.0, look & feel

#7232 [Look&Feel] Use small EuiTabs and EuiTabbedContent across the board
  changelogs/fragments/7232.yml
  src/plugins/dev_tools/public/application.tsx
  src/plugins/discover/public/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer.tsx
  src/plugins/home/public/application/components/feature_directory.js
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/index_pattern_management/public/components/edit_index_pattern/tabs/tabs.tsx
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/__snapshots__/help_flyout.test.tsx.snap
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/help_flyout.tsx
  src/plugins/vis_type_timeseries/public/application/components/vis_picker.js
Labels: backport 2.x, distinguished-contributor, v2.16.0, look & feel

#7242 [Workspace]Register workspace settings under setup and settings
  changelogs/fragments/7242.yml
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0, navigation

#7188 [Workspace] [Data Source] feat: support workspace level default data source
  changelogs/fragments/7188.yml
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0

#7213 [Workspace] Disable select data source panel for non dashboard admin in workspace create/edit page
  changelogs/fragments/7213.yml
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0

#7229 [Backport 2.x][Navigation-Next] Add current nav group into chrome service
  changelogs/fragments/7166.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog

#7107 Add Drag & Drop Across Axis Functionality to Vis Builder
  changelogs/fragments/7107.yml
  src/plugins/vis_builder/public/application/components/data_tab/config_panel.tsx
  src/plugins/vis_builder/public/application/components/data_tab/constants.ts
  src/plugins/vis_builder/public/application/components/data_tab/drag_drop/add_field_to_configuration.ts
  src/plugins/vis_builder/public/application/components/data_tab/drag_drop/move_field_between_schemas.ts
  src/plugins/vis_builder/public/application/components/data_tab/drag_drop/reorder_fields_within_schema.ts
  src/plugins/vis_builder/public/application/components/data_tab/drag_drop/replace_field_in_configuration.ts
  src/plugins/vis_builder/public/application/components/data_tab/dropbox.scss
  src/plugins/vis_builder/public/application/components/data_tab/dropbox.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_selector.scss
  src/plugins/vis_builder/public/application/components/data_tab/field_selector.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_selector.tsx
  src/plugins/vis_builder/public/application/components/data_tab/index.tsx
  src/plugins/vis_builder/public/application/components/data_tab/schema_to_dropbox.tsx
  src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
  src/plugins/vis_builder/public/application/components/data_tab/utils/get_valid_aggregations.tsx
  src/plugins/vis_builder/public/application/components/draggable_accordion.scss
  src/plugins/vis_builder/public/application/components/draggable_accordion.tsx
Labels: vis builder, backport 2.x, valued-contributor

#7270 Add OpenAPI specification for API for retrieving fields of index pattern
  changelogs/fragments/7270.yml
  docs/openapi/index_patterns/index.html
  docs/openapi/index_patterns/index_patterns.yml
Labels: docs, repeat-contributor, v2.16.0

#7057 Condence context menus
  src/plugins/console/public/application/components/console_menu.tsx
  src/plugins/data/public/ui/filter_bar/filter_item.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/saved_object_finder_create_new.tsx
  src/plugins/index_pattern_management/public/components/create_button/create_button.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/indices_list/indices_list.tsx
  src/plugins/inspector/public/ui/inspector_view_chooser.tsx
  src/plugins/inspector/public/views/data/components/download_options.tsx
  src/plugins/inspector/public/views/requests/components/request_selector.tsx
  src/plugins/saved_objects/public/finder/saved_object_finder.tsx
  src/plugins/share/public/components/share_context_menu.tsx
  src/plugins/share/public/components/url_panel_content.tsx
  src/plugins/vis_default_editor/public/components/agg_add.tsx
Labels: distinguished-contributor, failed changeset, look & feel

#7273 [navigation-next] Add new category
  changelogs/fragments/7273.yml
  src/core/utils/default_app_categories.ts
Labels: backport main, all-star-contributor

#7281 [Manual Backport][2.x][Workspace] [Data Source] feat: support workspace level default data source
  changelogs/fragments/7188.yml
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: Skip-Changelog

#7214 [DataSource] Restrict to manage data source on the DSM UI
  changelogs/fragments/7214.yml
  config/opensearch_dashboards.yml
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
Labels: backport 2.x, valued-contributor, workspace, v2.16.0

#7277 [Look&Feel] Apply missing pattern guidance to Dashboards experience
  src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_flyout.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_options_menu.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/indices_list/__snapshots__/indices_list.test.tsx.snap
  src/plugins/share/public/components/__snapshots__/share_context_menu.test.tsx.snap
  src/plugins/visualizations/public/wizard/__snapshots__/new_vis_modal.test.tsx.snap
  src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.16.0, look & feel

#7265 Remove unnecessary markdown rendering
  src/plugins/opensearch_dashboards_utils/public/history/redirect_when_missing.tsx
Labels: valued-contributor, failed changeset

#7291 [Discover-next] remove plugin config toggle for data enhancements
  changelogs/fragments/7291.yml
  config/opensearch_dashboards.yml
  package.json
  src/core/server/rendering/views/template.tsx
  src/plugins/data/common/constants.ts
  src/plugins/data/config.ts
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/server/ui_settings.ts
Labels: backport 2.x, distinguished-contributor, v2.16.0

#7241 [Workspace] Support workspace detail page
  changelogs/fragments/7241.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/index.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_content.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.scss
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_enter_details_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/components/workspace_overview/__snapshots__/workspace_overview.test.tsx.snap
  src/plugins/workspace/public/components/workspace_overview/all_get_started_cards.ts
  src/plugins/workspace/public/components/workspace_overview/getting_start_card.test.tsx
  src/plugins/workspace/public/components/workspace_overview/getting_start_card.tsx
  src/plugins/workspace/public/components/workspace_overview/getting_start_modal.test.tsx
  src/plugins/workspace/public/components/workspace_overview/getting_start_modal.tsx
  src/plugins/workspace/public/components/workspace_overview/index.scss
  src/plugins/workspace/public/components/workspace_overview/types.ts
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.test.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview_settings.tsx
  src/plugins/workspace/public/components/workspace_updater_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor, workspace, v2.16.0

#7230 [navigation-next] Add new left navigation
  changelogs/fragments/7230.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_controls/nav_controls_service.test.ts
  src/core/public/chrome/nav_controls/nav_controls_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_nav_controls.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/index.ts
  src/core/utils/default_app_categories.ts
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/advanced_settings/public/plugin.test.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/plugin.test.tsx
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/discover/public/plugin.test.ts
  src/plugins/discover/public/plugin.ts
  src/plugins/home/public/mocks/index.ts
  src/plugins/home/public/plugin.test.mocks.ts
  src/plugins/home/public/plugin.ts
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/index_pattern_management/public/plugin.test.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/management/public/components/settings_icon.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/management_overview/public/plugin.ts
  src/plugins/opensearch_dashboards_overview/public/plugin.ts
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, v2.16.0, navigation

#7303 [Manual Backport][2.x][Data Source] Restrict to manage data source on the DSM UI
  changelogs/fragments/7214.yml
  config/opensearch_dashboards.yml
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
Labels: Skip-Changelog

#7307 Disable input in edit data source when data_source.manageableBy is none
  changelogs/fragments/7307.yml
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/__snapshots__/update_password_modal.test.tsx.snap
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx
Labels: backport 2.x, multiple datasource, first-time-contributor, v2.16.0

#7282 [Navigation-next] Enable landing page for settings and data administration
  changelogs/fragments/7282.yml
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/index.ts
  src/plugins/management/public/components/feature_cards/__snapshots__/feature_cards.test.tsx.snap
  src/plugins/management/public/components/feature_cards/feature_cards.test.tsx
  src/plugins/management/public/components/feature_cards/feature_cards.tsx
  src/plugins/management/public/landing_page_application.test.tsx
  src/plugins/management/public/landing_page_application.tsx
  src/plugins/management/public/plugin.ts
Labels: backport 2.x, all-star-contributor, v2.16.0, navigation

#7179 Fixes recently accessed for saved search
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.16.0

#7296 [Workspace] Recover data source management in workspace
  changelogs/fragments/7296.yml
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0

#7221 [Workspace] use registered nav groups in workspace form
  changelogs/fragments/7221.yml
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0, navigation

#7254 [workspace] Fix not able to query legacy data when have at least 1 workspace
  src/plugins/management/public/components/feature_cards/__snapshots__/feature_cards.test.tsx.snap
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/utils.test.ts
  src/plugins/saved_objects_management/public/utils.ts
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, workspace, v2.16.0

#7318 [Workspace]Add "All use case" option to workspace form
  changelogs/fragments/7318.yml
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: seasoned-contributor

#7299 refactor: density and consistency changes for discover and query bar
  changelogs/fragments/7299.yml
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/filter_bar/_global_filter_item.scss
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/_table_header.scss
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/components/json_code_block/__snapshots__/json_code_block.test.tsx.snap
  src/plugins/discover/public/application/components/json_code_block/json_code_block.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/inspector/public/ui/inspector_view_chooser.tsx
Labels: backport 2.x, repeat-contributor, v2.16.0, look & feel

#7201 New core plugin for dynamic content rendering
  changelogs/fragments/7201.yml
  src/plugins/content_management/opensearch_dashboards.json
  src/plugins/content_management/public/app.tsx
  src/plugins/content_management/public/components/card_container/card_container.test.tsx
  src/plugins/content_management/public/components/card_container/card_container.tsx
  src/plugins/content_management/public/components/card_container/card_container_factory.test.ts
  src/plugins/content_management/public/components/card_container/card_container_factory.ts
  src/plugins/content_management/public/components/card_container/card_embeddable.test.tsx
  src/plugins/content_management/public/components/card_container/card_embeddable.tsx
  src/plugins/content_management/public/components/card_container/card_embeddable_factory.test.ts
  src/plugins/content_management/public/components/card_container/card_embeddable_factory.ts
  src/plugins/content_management/public/components/card_container/card_list.test.tsx
  src/plugins/content_management/public/components/card_container/card_list.tsx
  src/plugins/content_management/public/components/custom_content_embeddable.test.tsx
  src/plugins/content_management/public/components/custom_content_embeddable.tsx
  src/plugins/content_management/public/components/custom_content_embeddable_factory.test.ts
  src/plugins/content_management/public/components/custom_content_embeddable_factory.ts
  src/plugins/content_management/public/components/index.ts
  src/plugins/content_management/public/components/page_render.test.tsx
  src/plugins/content_management/public/components/page_render.tsx
  src/plugins/content_management/public/components/section_input.test.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/components/section_render.test.tsx
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/content_management/public/index.ts
  src/plugins/content_management/public/mocks.ts
  src/plugins/content_management/public/plugin.ts
  src/plugins/content_management/public/services/content_management/content_management_service.test.ts
  src/plugins/content_management/public/services/content_management/content_management_service.ts
  src/plugins/content_management/public/services/content_management/index.ts
  src/plugins/content_management/public/services/content_management/page.test.ts
  src/plugins/content_management/public/services/content_management/page.ts
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/content_management/public/services/index.ts
  src/plugins/content_management/public/types.ts
  src/plugins/embeddable/public/lib/embeddables/embeddable_root.tsx
  src/plugins/home/common/constants.ts
  src/plugins/home/opensearch_dashboards.json
  src/plugins/home/public/application/components/home_app.js
  src/plugins/home/public/application/home_render.tsx
  src/plugins/home/public/application/opensearch_dashboards_services.mock.ts
  src/plugins/home/public/application/opensearch_dashboards_services.ts
  src/plugins/home/public/plugin.test.ts
  src/plugins/home/public/plugin.ts
Labels: backport 2.x, valued-contributor, v2.16.0

#7309 New Query Enhancement UI
  changelogs/fragments/7309.yml
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/_language_selector.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/language_selector.test.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Labels: backport 2.x, distinguished-contributor, v2.16.0, discover-next

#7045 [Workspace] Refactor the UI of workspace picker
  changelogs/fragments/7045.yml
  src/core/public/chrome/index.ts
  src/core/public/chrome/recently_accessed/index.ts
  src/core/public/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/recent_workspace_manager.test.ts
  src/plugins/workspace/public/recent_workspace_manager.ts
Labels: backport 2.x, valued-contributor, workspace, v2.16.0

#7328 [Navigation] Update dev tools tab css for new left navigation
  changelogs/fragments/7328.yml
  src/plugins/dev_tools/public/index.scss
Labels: backport 2.x, first-time-contributor

#7342 [Manual Backport][2.x][Workspace] Refactor the UI of workspace picker
  changelogs/fragments/7045.yml
  src/core/public/chrome/index.ts
  src/core/public/chrome/recently_accessed/index.ts
  src/core/public/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/recent_workspace_manager.test.ts
  src/plugins/workspace/public/recent_workspace_manager.ts
Labels: Skip-Changelog

#7333 [Workspace] Register four get started cards in home page
  changelogs/fragments/7333.yml
  src/plugins/content_management/public/components/card_container/card_container.tsx
  src/plugins/content_management/public/components/card_container/card_embeddable.test.tsx
  src/plugins/content_management/public/components/card_container/card_embeddable.tsx
  src/plugins/content_management/public/components/page_render.tsx
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/home/public/index.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/home_get_start_card/index.ts
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, valued-contributor, v2.16.0

#7327 fix: Fix wrapping of labels in filter by type popover
  changelogs/fragments/7327.yml
  src/plugins/data_explorer/public/components/sidebar/index.scss
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
Labels: backport 2.x, repeat-contributor, v2.16.0, look & feel

#7305 [navigation-next] fix: redirect to standard index pattern applications while nav group is enabled
  changelogs/fragments/7305.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/utils/default_app_categories.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.test.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/management/public/components/management_app/management_app.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
Labels: backport main, all-star-contributor

#7247 [Navigation-next]Register workspace list card into home page
  changelogs/fragments/7247.yml
  src/core/types/workspace.ts
  src/plugins/workspace/public/components/service_card/__snapshots__/workspace_list_card.test.tsx.snap
  src/plugins/workspace/public/components/service_card/index.ts
  src/plugins/workspace/public/components/service_card/workspace_list_card.test.tsx
  src/plugins/workspace/public/components/service_card/workspace_list_card.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0

#7347 fix: data source selector in dev tools tab moved to left
  changelogs/fragments/7347.yml
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/index.scss
Labels: backport 2.x, valued-contributor, v2.16.0

#7351 [HomePage] Add home page static list card
  changelogs/fragments/7351.yml
  src/plugins/home/public/application/components/__snapshots__/home_list_card.test.tsx.snap
  src/plugins/home/public/application/components/home_list_card.test.tsx
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/home/public/application/home_render.tsx
Labels: backport 2.x, seasoned-contributor, v2.16.0

#7237 [navigation-next] feat: add recent works in new homepage
  changelogs/fragments/7237.yml
  src/core/public/chrome/index.ts
  src/core/public/chrome/recently_accessed/recently_accessed_service.ts
  src/core/public/chrome/ui/header/index.ts
  src/core/public/chrome/ui/index.ts
  src/core/public/index.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.test.ts
  src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/saved_searches/types.ts
  src/plugins/home/public/application/home_render.tsx
  src/plugins/saved_objects/public/saved_object/helpers/save_saved_object.ts
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/management_section/recent_work.test.tsx
  src/plugins/saved_objects_management/public/management_section/recent_work.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/saved_visualizations/_saved_vis.ts
  src/plugins/visualize/public/application/utils/use/use_saved_vis_instance.test.ts
  src/plugins/visualize/public/application/utils/use/use_saved_vis_instance.ts
Labels: backport 2.x, all-star-contributor, v2.16.0, navigation

#7231 [Look&Feel] Replace browser tooltip usage with OUI tooltip
  changelogs/fragments/7231.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/home_loader.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/right_navigation_button.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/chrome/ui/header/home_loader.test.tsx
  src/core/public/chrome/ui/header/home_loader.tsx
  src/core/public/chrome/ui/header/right_navigation_button.tsx
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.test.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_bucket.tsx
  src/plugins/vis_type_vislib/public/vislib/components/legend/__snapshots__/legend.test.tsx.snap
  src/plugins/vis_type_vislib/public/vislib/components/legend/legend.tsx
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: backport 2.x, repeat-contributor, v2.16.0, look & feel

#7363 Bump OUI to 1.8.0
  changelogs/fragments/7363.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.16.0

#7329 Compress data source selector on management's data sources page
  changelogs/fragments/7329.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/dev_tools/public/application.tsx
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/query_enhancements/public/data_source_connection/components/connections_bar.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/vis_type_timeseries/public/application/components/index_pattern.js
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.16.0, look & feel

#7341 [Look&Feel] Apply missing guidance for visBuilder
  changelogs/fragments/7341.yml
  src/plugins/data/public/ui/apply_filters/apply_filter_popover_content.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_bucket.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_bucket.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_details.tsx
  src/plugins/vis_default_editor/public/components/sidebar/controls.tsx
Labels: enhancement, backport 2.x, repeat-contributor, v2.16.0, look & feel

#7373 [Manual] [Backport 2.x] [Look&Feel] Apply missing guidance for visBuilder
  changelogs/fragments/7341.yml
  src/plugins/data/public/ui/apply_filters/apply_filter_popover_content.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_bucket.test.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_bucket.tsx
  src/plugins/vis_builder/public/application/components/data_tab/field_details.tsx
  src/plugins/vis_default_editor/public/components/sidebar/controls.tsx
Labels: failed changeset, v2.16.0, look & feel

#7357 [Workspace]Hide create workspace button for non dashboard admin
  changelogs/fragments/7357.yml
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0

#7257 [Navigation] Add recent items popup in top navigation
  changelogs/fragments/7257.yml
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/recent_items.test.tsx.snap
  src/core/public/chrome/ui/header/assets/recent_items.svg
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/recent_items.test.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
  src/core/typings.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, navigation

#7361 add dataSourceId to dataSet
  src/plugins/data/public/data_sources/datasource/types.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.test.ts
  src/plugins/data/public/data_sources/default_datasource/default_datasource.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.16.0

#7285 feat: support PPL in vega visualization
  changelogs/fragments/7285.yml
  src/plugins/data/common/search/search_source/fetch/get_search_params.ts
  src/plugins/data/server/search/routes/search.test.ts
  src/plugins/data/server/search/routes/search.ts
  src/plugins/data/server/search/types.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/search/ppl_raw_search_strategy.ts
  src/plugins/vis_type_vega/public/data_model/ppl_parser.test.ts
  src/plugins/vis_type_vega/public/data_model/ppl_parser.ts
  src/plugins/vis_type_vega/public/data_model/search_api.ts
  src/plugins/vis_type_vega/public/data_model/types.ts
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
  src/plugins/visualizations/public/legacy/build_pipeline.ts
Labels: backport 2.x, valued-contributor, v2.16.0, vega

#7336 [Auto Suggest] OpenSearch SQL autosuggest with ANTLR
  .eslintignore
  .eslintrc.js
  changelogs/fragments/7336.yml
  config/opensearch_dashboards.yml
  package.json
  packages/osd-babel-preset/webpack_preset.js
  packages/osd-monaco/src/xjson/lexer_rules/index.ts
  packages/osd-monaco/src/xjson/lexer_rules/opensearchsql.ts
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLLexer.interp
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLLexer.tokens
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLLexer.ts
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLParser.interp
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLParser.tokens
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLParser.ts
  src/plugins/data/public/antlr/opensearch_sql/.generated/OpenSearchSQLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/constants.ts
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.interp
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.tokens
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.interp
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.tokens
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParserBaseListener.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParserListener.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/OpenSearchSQLLexer.g4
  src/plugins/data/public/antlr/opensearch_sql/grammar/OpenSearchSQLParser.g4
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_sql/parse.test.ts
  src/plugins/data/public/antlr/opensearch_sql/parse.ts
  src/plugins/data/public/antlr/opensearch_sql/sql_error_listener.test.ts
  src/plugins/data/public/antlr/opensearch_sql/sql_error_listerner.ts
  src/plugins/data/public/antlr/opensearch_sql/symbol_table.test.ts
  src/plugins/data/public/antlr/opensearch_sql/symbol_table.ts
  src/plugins/data/public/antlr/opensearch_sql/table.test.ts
  src/plugins/data/public/antlr/opensearch_sql/table.ts
  src/plugins/data/public/antlr/shared/cursor.test.ts
  src/plugins/data/public/antlr/shared/cursor.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/query_editor/_language_switcher.scss
  src/plugins/data/public/ui/query_editor/language_switcher.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/types.ts
  src/plugins/query_enhancements/public/plugin.tsx
  yarn.lock
Labels: backport 2.x, valued-contributor, v2.16.0, backport 2.16

#7382 [Manual][Backport 2.x][Workspace]Hide create workspace button for non dashboard admin
  changelogs/fragments/7357.yml
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: failed changeset

#7360 [Navigation-next] Enrich breadcrumbs by workspace and use case
  changelogs/fragments/7360.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, navigation, backport 2.16

#7326 Move TopNavLinks to new Nav Bar Discover
  src/core/public/application/types.ts
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data_explorer/public/components/__snapshots__/app_container.test.tsx.snap
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/constants.ts
  src/plugins/discover/common/index.ts
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
Labels: backport 2.x, discover, valued-contributor, v2.16.0

#7395 [Manual Backport][2.x][Data Source] Restrict to manage data source on the DSM UI
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
Labels: Skip-Changelog, v2.16.0, backport 2.16

#7396 [Bug][DataSource] No restriction on setting default data source
  changelogs/fragments/7396.yml
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
Labels: backport 2.x, seasoned-contributor, v2.16.0, backport 2.16

#6478 [Workspace] Copy selected/all saved objects
  changelogs/fragments/6478.yml
  src/plugins/saved_objects_management/public/index.ts
  src/plugins/saved_objects_management/public/lib/duplicate_saved_objects.test.ts
  src/plugins/saved_objects_management/public/lib/duplicate_saved_objects.ts
  src/plugins/saved_objects_management/public/lib/index.ts
  src/plugins/saved_objects_management/public/management_section/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_modal.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/utils.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/utils.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.mocks.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/types.ts
  src/plugins/workspace/public/components/workspace_column/workspace_column.tsx
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, first-time-contributor, workspace, v2.16.0, backport 2.16

#7272 fix(queryEnhancements): fix dataSource.id reference to enable tests
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/server/routes/query_assist/agents.test.ts
  src/plugins/query_enhancements/server/types.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.16.0, discover-next

#7288 [VisBuilder] Add Capability to generate dynamic vega
  changelogs/fragments/7288.yml
  src/plugins/advanced_settings/public/management_app/lib/get_category_name.ts
  src/plugins/expressions/public/index.ts
  src/plugins/vis_builder/common/constants.ts
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
  src/plugins/vis_builder/public/plugin.test.ts
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/services/type_service/types.ts
  src/plugins/vis_builder/public/services/type_service/visualization_type.tsx
  src/plugins/vis_builder/public/types.ts
  src/plugins/vis_builder/public/visualizations/common/expression_helpers.ts
  src/plugins/vis_builder/public/visualizations/vega/components/axes.test.ts
  src/plugins/vis_builder/public/visualizations/vega/components/axes.ts
  src/plugins/vis_builder/public/visualizations/vega/components/encoding.test.ts
  src/plugins/vis_builder/public/visualizations/vega/components/encoding.ts
  src/plugins/vis_builder/public/visualizations/vega/components/legend.test.ts
  src/plugins/vis_builder/public/visualizations/vega/components/legend.ts
  src/plugins/vis_builder/public/visualizations/vega/components/mark.test.ts
  src/plugins/vis_builder/public/visualizations/vega/components/mark.ts
  src/plugins/vis_builder/public/visualizations/vega/components/tooltip.test.ts
  src/plugins/vis_builder/public/visualizations/vega/components/tooltip.ts
  src/plugins/vis_builder/public/visualizations/vega/utils/expression_helper.test.ts
  src/plugins/vis_builder/public/visualizations/vega/utils/expression_helper.ts
  src/plugins/vis_builder/public/visualizations/vega/utils/helpers.test.ts
  src/plugins/vis_builder/public/visualizations/vega/utils/helpers.ts
  src/plugins/vis_builder/public/visualizations/vega/utils/types.ts
  src/plugins/vis_builder/public/visualizations/vega/vega_lite_spec_builder.test.ts
  src/plugins/vis_builder/public/visualizations/vega/vega_lite_spec_builder.ts
  src/plugins/vis_builder/public/visualizations/vega/vega_spec_builder.test.ts
  src/plugins/vis_builder/public/visualizations/vega/vega_spec_builder.ts
  src/plugins/vis_builder/public/visualizations/vega/vega_spec_factory.ts
  src/plugins/vis_builder/public/visualizations/vislib/area/to_expression.test.ts
  src/plugins/vis_builder/public/visualizations/vislib/area/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/common/create_vis.ts
  src/plugins/vis_builder/public/visualizations/vislib/histogram/to_expression.test.ts
  src/plugins/vis_builder/public/visualizations/vislib/histogram/to_expression.ts
  src/plugins/vis_builder/public/visualizations/vislib/line/to_expression.test.ts
  src/plugins/vis_builder/public/visualizations/vislib/line/to_expression.ts
  src/plugins/vis_builder/server/plugin.ts
  src/plugins/vis_type_vislib/public/index.ts
  src/plugins/visualizations/public/index.ts
Labels: vis builder, backport 2.x, distinguished-contributor, v2.16.0, vega

#7420 [Multiple Datasource][Version Decoupling] Add data source version and installed plugins in data source viewer returns
  changelogs/fragments/7420.yml
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, version decoupling, backport 2.16

#7405 [Bug][Workspace] Navigate to detail page when clicking all use case workspace
  changelogs/fragments/7405.yml
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: backport 2.x, seasoned-contributor, v2.16.0, backport 2.16

#7432 [Workspace]Fix breadcrumbs not set properly when out a workspace
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.16.0, backport 2.16

#7437 [navigation-next]fix: breadcrumb issue found in data source management and other similar cases.
  changelogs/fragments/7401.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/opensearch_dashboards_react/public/react_router_navigate/index.ts
  src/plugins/opensearch_dashboards_react/public/react_router_navigate/react_router_navigate.test.tsx
  src/plugins/opensearch_dashboards_react/public/react_router_navigate/react_router_navigate.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, backport 2.16

#7419 [2.16] Fix minor issues for Direct Query Datasource
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/server/routes/data_connections_router.ts
Labels: backport main, backport 2.x, failed changeset, v2.16.0

#7440 [Bug][Data Source] Move data source manageable feature flag to DSM plugin
  changelogs/fragments/7440.yml
  config/opensearch_dashboards.yml
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/common/types.ts
  src/plugins/data_source_management/config.ts
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/server/index.ts
  src/plugins/data_source_management/server/plugin.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, backport 2.16

#7444 Bump browserslist from `4.22.1` to `4.23.2` to resolve integration test error
  yarn.lock
Labels: backport 2.x, Skip-Changelog, maintenance, distinguished-contributor, failed changeset, backport 2.16

#6674 [VisBuilder][BUG] Flat render structure in Metric and Table Vis
  changelogs/fragments/6674.yml
  src/plugins/vis_type_metric/public/components/__snapshots__/metric_vis_component.test.tsx.snap
  src/plugins/vis_type_metric/public/components/metric_vis_component.tsx
  src/plugins/vis_type_metric/public/metric_vis_renderer.tsx
  src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
  src/plugins/vis_type_table/public/components/table_vis_app.tsx
  src/plugins/vis_type_table/public/table_vis_renderer.tsx
  src/plugins/vis_type_table/public/utils/get_table_ui_state.ts
Labels: bug, vis builder, backport 2.x, v2.16.0, backport 2.16

#7408 [Manual backport 2.x] [Discover-next] toggle enhancements
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/7314.yml
  package.json
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data/server/ui_settings.ts
  src/plugins/query_enhancements/opensearch_dashboards.json
  test/common/config.js
Labels: failed changeset

#7450 [2.x][Manual Backport] Bump browserslist from 4.22.1 to 4.23.2 to resolve integ test error
  yarn.lock
Labels: Skip-Changelog, maintenance

#7451 [2.16][Manual Backport] Bump browserslist from 4.22.1 to 4.23.2 to resolve integ test error
  yarn.lock
Labels: Skip-Changelog

#7458 [admin] add Sean to be a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/7458.yml
Labels: docs, backport 2.x, v2.16.0, backport 2.16

#7457 [Manual backport 2.x] New Query Enhancement UI
  changelogs/fragments/7309.yml
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/_language_selector.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/language_selector.test.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Labels: autocut, failed changeset, backport 2.16

#7456 [2.16 MDS]Fix access control tab fetching for remote cluster
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/access_control_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
Labels: failed changeset

#7022 Fix add filter for numeric scripted field
  src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.test.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx
Labels: bug, backport 2.x, discover, distinguished-contributor, v2.16.0

#7207 fix(discover): break new lines in table cell
  changelogs/fragments/7207.yml
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
Labels: bug, backport 2.x, discover, valued-contributor, backport 2.16

#7435 [Bug][Workspace] Add permission validation at workspace detail page
  changelogs/fragments/7435.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.tsx
Labels: backport 2.x, seasoned-contributor, workspace, v2.16.0, backport 2.16

#7366 [Manual] [Backport 2.x] [Look&Feel] Replace browser tooltip usage with OUI tooltip
  changelogs/fragments/7231.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/home_loader.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/right_navigation_button.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/chrome/ui/header/home_loader.test.tsx
  src/core/public/chrome/ui/header/home_loader.tsx
  src/core/public/chrome/ui/header/right_navigation_button.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.test.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_bucket.tsx
  src/plugins/vis_type_vislib/public/vislib/components/legend/__snapshots__/legend.test.tsx.snap
  src/plugins/vis_type_vislib/public/vislib/components/legend/legend.tsx
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: failed changeset, v2.16.0, backport 2.16

#7464 fix(query assist): update reading data source id from dataset manager
  src/plugins/data/public/query/dataset_manager/dataset_manager.test.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.ts
  src/plugins/data/public/query/mocks.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/components/index_selector.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/hooks/use_indices.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: Skip-Changelog, valued-contributor, v2.16.0

#6301 Update locales.js for support pl language
  packages/osd-i18n/src/core/locales.js
Labels: needs more info, i18n, backport 2.x, first-time-contributor, v2.16.0, backport 2.16

#7473 [2.x][Manual Backport 2.x] Bump up axios to 1.7.2 to fix SNYK-JS-AXIOS-6144788 (#7149)
  changelogs/fragments/7149.yml
  yarn.lock
Labels: failed changeset

#7478 fix: update recent items icon from SVG to react component
  changelogs/fragments/7478.yml
  src/core/public/chrome/ui/header/__snapshots__/recent_items.test.tsx.snap
  src/core/public/chrome/ui/header/assets/recent_items.svg
  src/core/public/chrome/ui/header/recent_items.tsx
  src/core/public/chrome/ui/header/recent_items_icon.tsx
  src/core/typings.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, backport 2.16

#7467 [Auto Suggest] DQL autosuggest with ANTLR
  changelogs/fragments/7391.yml
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.interp
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.ts
  src/plugins/data/public/antlr/dql/.generated/DQLParser.interp
  src/plugins/data/public/antlr/dql/.generated/DQLParser.tokens
  src/plugins/data/public/antlr/dql/.generated/DQLParser.ts
  src/plugins/data/public/antlr/dql/.generated/DQLParserVisitor.ts
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.tokens
  src/plugins/data/public/antlr/dql/grammar/DQLLexer.g4
  src/plugins/data/public/antlr/dql/grammar/DQLParser.g4
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/autocomplete/autocomplete_service.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx
Labels: backport 2.x, repeat-contributor, failed changeset, v2.16.0, backport 2.16

#7461 [forwardport main] Fix minor issues for Direct Query Datasource (#7419)
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/access_control_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/installed_integrations_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/server/routes/data_connections_router.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, backport 2.16

#7489 [tests][discover-next] update the tests and async nature of the dataset navigator
  .lycheeignore
  src/plugins/dashboard/public/application/components/dashboard_listing/dashboard_listing.test.tsx
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.ts
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
Labels: Skip-Changelog, distinguished-contributor, discover-next

#7470 [DataSet Navigator] Rewire S3 components
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/types.tsx
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Labels: Skip-Changelog, repeat-contributor

#7494 Fix UI and detection of external data source in query assist
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: Skip-Changelog, valued-contributor, v2.16.0

#7463 [Auto Suggest] Add MDS Support Along with A Few Cleanup and tests
  .gitignore
  changelogs/fragments/7463.yml
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.interp
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.tokens
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.interp
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.tokens
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParserBaseListener.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParserListener.java
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: valued-contributor, v2.16.0

#7496 More styling on query enhancement UI
  changelogs/fragments/7425.yml
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
Labels: Skip-Changelog, distinguished-contributor

#7498 [Auto Suggest] DQL Updates
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: repeat-contributor, failed changeset

#7497 [MDS] Fix the hide local cluster config
  changelogs/fragments/7497.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
Labels: backport 2.x, valued-contributor, backport 2.16

#7502 [navigation-next]feat: make collapsed new left nav align with hamburger icon
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
Labels: backport 2.x, Skip-Changelog, v2.16.0, navigation, backport 2.16

#7508 fix: update icon of recent items from OUI library to enable dark mode
  changelogs/fragments/7508.yml
  src/core/public/chrome/ui/header/__snapshots__/recent_items.test.tsx.snap
  src/core/public/chrome/ui/header/recent_items.tsx
  src/core/public/chrome/ui/header/recent_items_icon.tsx
Labels: backport 2.x, seasoned-contributor, v2.16.0, navigation, backport 2.16

#7500 [Discover 2.0] Miscellaneous Changes for Dataset Navigator
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/index.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/catalog_cache/cache_loader.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/hooks/direct_query_hook.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/hooks/index.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/index.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/utils/query_session_utils.ts
  src/plugins/data/public/ui/index.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Labels: valued-contributor, failed changeset

#7499 Remove height on global styling of top nav
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
Labels: distinguished-contributor, failed changeset

#7484 [Workspace] refactor saved object client addToWorkspaces and deleteFromWorkspaces function params structure
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/core/server/saved_objects/service/saved_objects_client.ts
Labels: backport 2.x, seasoned-contributor, v2.16.0, backport 2.16

#7493 [Look&Feel] Revert tooltip addition for navigation menu
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.16.0, look & feel, backport 2.16

#7531 fix: use xs buttons for discover table cell filter buttons
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
Labels: Skip-Changelog, repeat-contributor

#7542 [Discover 2.0] Updating fetch functions to include local cluster
  changelogs/fragments/7542.yml
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_data_sources.ts
  src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_external_data_sources.ts
Labels: backport 2.x, valued-contributor, v2.16.0, backport 2.16

#7233 [Sample Data] Update demo dashboard title
  changelogs/fragments/7233.yml
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
Labels: backport 2.x, distinguished-contributor, v2.16.0, backport 2.16

#7541 Fix babel error
  changelogs/fragments/7541.yml
  package.json
  yarn.lock
Labels: v2.16.0, backport 2.16

#7546 [Discover Next] Fixes Discover styles
  changelogs/fragments/7546.yml
  packages/osd-stylelint-config/config/global_selectors.json
  src/plugins/data/public/ui/dataset_navigator/_dataset_navigator.scss
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/_index.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/dql_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/index.ts
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/index.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/query_editor/types.ts
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/discover/public/application/components/chart/_histogram.scss
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.scss
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
Labels: backport 2.x, distinguished-contributor, v2.16.0, discover-next, backport 2.16

#7524 [Manual] [Backport 2.x] [Look&Feel] Revert tooltip addition for navigation menu
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: failed changeset

#7525 [Manual] [Backport 2.16] [Look&Feel] Revert tooltip addition for navigation menu
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: failed changeset

#7553 [admin] add Joshua to be a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/7553.yml
Labels: docs, backport 2.x, v2.16.0, backport 2.16

#7530 [Look&Feel] Discover and Query Management fix
  changelogs/fragments/7530.yml
  src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/vis_type_vislib/public/vislib/components/legend/__snapshots__/legend.test.tsx.snap
  src/plugins/vis_type_vislib/public/vislib/components/legend/_legend.scss
  src/plugins/vis_type_vislib/public/vislib/components/legend/legend.tsx
Labels: backport 2.x, valued-contributor, v2.16.0, look & feel, backport 2.16

#7452 Bump OUI to 1.8.1
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.16.0, backport 2.16

#7540 [discover-next][bug] add max height to dataset navigator and use memoization
  package.json
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.ts
  src/plugins/data/public/query/state_sync/create_global_query_observable.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.ts
  src/plugins/data/public/ui/dataset_navigator/_dataset_navigator.scss
  src/plugins/data/public/ui/dataset_navigator/create_dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Labels: backport 2.x, v2.16.0, discover-next, backport 2.16

#7528 [MDS] Bug-fix Fix data source picker trigger local cluster call by default
  changelogs/fragments/7528.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
Labels: backport 2.x, valued-contributor, v2.16.0, backport 2.16

#7552 Fix query assist after #7492, #7546, #7540
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/query/dataset_manager/dataset_manager.mock.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.test.ts
  src/plugins/data/public/query/mocks.ts
  src/plugins/data/public/ui/dataset_navigator/create_dataset_navigator.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/query_enhancements/public/index.scss
  src/plugins/query_enhancements/public/query_assist/_index.scss
  src/plugins/query_enhancements/public/query_assist/components/__snapshots__/call_outs.test.tsx.snap
  src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, Skip-Changelog, valued-contributor, v2.16.0, backport 2.16

#7565 [Workspace]Add workspaces and permissions fields into saved objects _bulk_get response
  changelogs/fragments/7565.yml
  src/core/server/saved_objects/service/lib/included_fields.test.ts
  src/core/server/saved_objects/service/lib/included_fields.ts
  src/core/server/saved_objects/service/lib/repository.test.js
Labels: backport 2.x, seasoned-contributor, v2.16.0, backport 2.16

#7566 [Discover next] Fixes dataset navigator menu styling & search error toast
  packages/osd-stylelint-config/config/global_selectors.json
  src/core/public/notifications/toasts/toasts_api.tsx
  src/plugins/data/public/search/search_interceptor.ts
  src/plugins/data/public/ui/dataset_navigator/_dataset_navigator.scss
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
Labels: backport 2.x, distinguished-contributor, v2.16.0, discover-next, backport 2.16

#7551 [navigation]fix: redirect user to home in global when workspace is enabled
  changelogs/fragments/7551.yml
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
Labels: bug, backport 2.x, all-star-contributor, v2.16.0, backport 2.16

#7567 [Discover 2.0] Loading fix for databases
  changelogs/fragments/7567.yml
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
Labels: backport 2.x, valued-contributor, v2.16.0, discover-next, backport 2.16

#7574 [2.x manual backport] BP for #7542, #7540, #7552, #7566, #7567
  changelogs/fragments/7542.yml
  changelogs/fragments/7567.yml
  package.json
  packages/osd-stylelint-config/config/global_selectors.json
  src/core/public/notifications/toasts/toasts_api.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.mock.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.test.ts
  src/plugins/data/public/query/dataset_manager/dataset_manager.ts
  src/plugins/data/public/query/mocks.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.ts
  src/plugins/data/public/query/state_sync/create_global_query_observable.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.ts
  src/plugins/data/public/search/search_interceptor.ts
  src/plugins/data/public/ui/dataset_navigator/_dataset_navigator.scss
  src/plugins/data/public/ui/dataset_navigator/create_dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_data_sources.ts
  src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_external_data_sources.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/index.scss
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/_index.scss
  src/plugins/query_enhancements/public/query_assist/components/__snapshots__/call_outs.test.tsx.snap
  src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Labels: Skip-Changelog, v2.16.0

#7543 [Auto Suggest] Add back reverted MDS support, tests and cleanup for sql auto suggest
  .gitignore
  changelogs/fragments/7463.yml
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.interp
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLLexer.tokens
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.interp
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParser.tokens
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParserBaseListener.java
  src/plugins/data/public/antlr/opensearch_sql/grammar/.antlr/OpenSearchSQLParserListener.java
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap
Labels: backport 2.x, valued-contributor, v2.16.0

#7523 [Look&Feel] Apply small popover padding and add Oui tooltip
  changelogs/fragments/7523.yml
  src/core/public/chrome/ui/header/recent_items.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/table/__snapshots__/table.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/table/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/vis_augmenter/public/view_events_flyout/components/event_vis_item_icon.tsx
Labels: backport 2.x, valued-contributor, v2.17.0, look & feel

#7581 Fix discover options' location
  changelogs/fragments/7581.yml
  src/plugins/discover/public/application/components/chart/chart.tsx
Labels: backport 2.x, distinguished-contributor, v2.16.0, discover-next

#7585 [discover-next] disable show doc links for PPL
  changelogs/fragments/7585.yml
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, v2.16.0, discover-next, backport 2.16

#7391 [Auto Suggest] DQL autosuggest with ANTLR
  changelogs/fragments/7391.yml
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.interp
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.ts
  src/plugins/data/public/antlr/dql/.generated/DQLParser.interp
  src/plugins/data/public/antlr/dql/.generated/DQLParser.tokens
  src/plugins/data/public/antlr/dql/.generated/DQLParser.ts
  src/plugins/data/public/antlr/dql/.generated/DQLParserVisitor.ts
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.tokens
  src/plugins/data/public/antlr/dql/grammar/DQLLexer.g4
  src/plugins/data/public/antlr/dql/grammar/DQLParser.g4
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/autocomplete/autocomplete_service.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx
Labels: backport 2.x, repeat-contributor, v2.16.0, discover-next, backport 2.16

#7486 [Look&Feel] Use small context menu across the board
  src/plugins/home/public/application/components/__snapshots__/sample_data_view_data_button.test.js.snap
  src/plugins/home/public/application/components/sample_data_view_data_button.js
  src/plugins/vis_type_vega/public/components/vega_actions_menu.tsx
  src/plugins/vis_type_vega/public/components/vega_help_menu.tsx
Labels: enhancement, backport 2.x, Skip-Changelog, v2.17.0, look & feel
