Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-12, with the labels that each got.

#8888 [Workspace] Isolate objects based on workspace when calling get/bulkGet
  changelogs/fragments/8888.yml
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: distinguished-contributor, workspace, v2.19.0

#8993 fix: support imports without extensions in cypress webpack build
  changelogs/fragments/8993.yml
  cypress.config.js
  cypress.config.ts
  package.json
Labels: repeat-contributor

#8930 [Discover] Fix Initialization if No Saved Query
  changelogs/fragments/8930.yml
  src/plugins/discover/public/application/view_components/utils/use_search.test.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, discover, seasoned-contributor, discover-next

#8739 [Workspace][Bug] Check if workspaces exists when creating saved objects
  changelogs/fragments/8739.yml
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#8992 [Discover] fix PPL to not throw error if aggregation query fails
  src/plugins/query_enhancements/common/utils.test.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.test.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.ts
Labels: backport 2.x, all-star-contributor, failed changeset

#8994 Bump version to 2.19 for 2.x branch
  package.json
Labels: Skip-Changelog

#8995 Upgrade Cypress to v12
  changelogs/fragments/8926.yml
  changelogs/fragments/8993.yml
  cypress.config.ts
  cypress.json
  cypress/support/e2e.js
  package.json
  yarn.lock
Labels: Skip-Changelog, repeat-contributor

#8876 [Query enhancements] use status 503 if search strategy throws 500
  src/plugins/query_enhancements/server/routes/index.test.ts
  src/plugins/query_enhancements/server/routes/index.ts
Labels: backport 2.x, discover, Skip-Changelog, all-star-contributor, discover-next, v2.19.0

#8894 [Manual backport 2.x] #8744 #8882
  changelogs/fragments/8744.yml
  changelogs/fragments/8882.yml
  package.json
  yarn.lock
Labels: autocut, failed changeset, v2.19.0

#8925 Revert "[augmenter] do not support datasources with no version (#8915)"
  changelogs/fragments/8915.yml
  src/plugins/vis_augmenter/public/plugin.ts
  src/plugins/vis_augmenter/public/services.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx
  src/plugins/vis_type_vislib/public/line_to_expression.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Labels: Skip-Changelog, all-star-contributor

#9003 [Workspace] Clear the attribute of error objects
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, workspace

#8611 bump `url` to 0.11.4
  changelogs/fragments/8611.yml
  package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, v2.19.0

#9007 [CVE-2024-45590][CVE-2024-45296] Resolve cves for 1.3 by bumping `body-parser` and `path-to-regexp`
  package.json
  yarn.lock
Labels: cve, v1.3.20

#8842 [Workspace]Fix error toasts in sample data page
  changelogs/fragments/8842.yml
  src/plugins/home/public/application/opensearch_dashboards_services.ts
  src/plugins/home/public/application/sample_data_client.js
  src/plugins/home/public/application/sample_data_client.test.js
  src/plugins/home/public/plugin.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.ts
Labels: backport 2.x, distinguished-contributor, workspace

#9014 fix: update the osd-plugin-generator template to reference the correct button
  packages/osd-plugin-generator/template/public/components/app.tsx.ejs
Labels: Skip-Changelog, first-time-contributor

#8932 [Discover] Support custom logic to insert time filter based on dataset type
  changelogs/fragments/8932.yml
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/ui/dataset_selector/configurator.test.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/routes/index.ts
Labels: backport 2.x, all-star-contributor

#9027 [Discover Test] TestID-69: Filtering. Add data-test-subj tags.
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/lib/filter_label.test.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/lib/filter_label.tsx
Labels: backport 2.x, Skip-Changelog, first-time-contributor, v2.19.0

#9029 TESTID-140: add queryEditorLanguageOptions data-test-subj on language_selector.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
Labels: backport 2.x, Skip-Changelog, first-time-contributor, v2.19.0

#9033 Added release notes for 1.3.20
  release-notes/opensearch-dashboards.release-notes-1.3.20.md
Labels: Skip-Changelog, repeat-contributor

#9034 Fix saved search loading issue
  changelogs/fragments/9034.yml
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: discover, v2.17.1

#9039 [Manual backport 2.x]Bump `@opensearch-project/opensearch-next` from 2.9.0 to 2.13.0 (#8886)
  changelogs/fragments/8886.yml
  package.json
  scripts/postinstall.js
  yarn.lock
Labels: failed changeset

#9031 [Manual bckport 2.x] bump `url` to 0.11.4 (#8611)
  changelogs/fragments/8611.yml
  package.json
  yarn.lock
Labels: failed changeset, backport 2.17

#9038 Add workspace utility
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/remove_workspace.js
  cypress/utils/dashboards/setup_workspace.js
  cypress/utils/dashboards/workspace-plugin/commands.js
  cypress/utils/dashboards/workspace-plugin/constants.js
Labels: Skip-Changelog, all-star-contributor

#8905 Fix toggle column action in the discover page
  changelogs/fragments/8905.yml
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer_tab.test.tsx
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer_tab.tsx
Labels: bug, backport 2.x, discover, first-time-contributor, v2.19.0

#9048 Migrate query enhancement tests from functional repo to main
  .eslintignore
  .github/workflows/cypress_workflow.yml
  .github/workflows/links_checker.yml
  .gitignore
  changelogs/fragments/9048.yml
  cypress.config.ts
  cypress/fixtures/discover/data.json.txt
  cypress/fixtures/discover/mappings.json.txt
  cypress/fixtures/logstash/mappings.json.txt
  cypress/fixtures/timestamp/data.json.txt
  cypress/fixtures/timestamp/data_with_index_pattern.json.txt
  cypress/fixtures/timestamp/mappings.json.txt
  cypress/integration/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/apps/query_enhancements/queries.spec.js
  cypress/integration/core_opensearch_dashboards/dashboard_sanity_test_spec.js
  cypress/integration/dashboard_sanity_test.spec.js
  cypress/support/e2e.js
  cypress/utils/apps/commands.js
  cypress/utils/apps/constants.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/constants.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/index.d.ts
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/helpers.js
  cypress/utils/index.d.ts
  package.json
Labels: Skip-Changelog, distinguished-contributor

#9051 Add missing data-test-subj tags for data plugin
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/data/public/query/query_string/language_service/lib/recent_query.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/saved_query_flyouts/saved_query_card.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_list_item.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/shard_failure_modal/__snapshots__/shard_failure_description.test.tsx.snap
  src/plugins/data/public/ui/shard_failure_modal/shard_failure_description.tsx
  src/plugins/data/public/ui/shard_failure_modal/shard_failure_description_header.tsx
  src/plugins/data/public/ui/typeahead/__snapshots__/suggestion_component.test.tsx.snap
  src/plugins/data/public/ui/typeahead/suggestion_component.tsx
Labels: Skip-Changelog, all-star-contributor

#9049 Add missing data-test-subj tags for discover plugin
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/default_discover_table/pagination.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/components/doc_views/single_doc_app.tsx
  src/plugins/discover/public/application/components/doc_views/surrounding_docs_view.tsx
  src/plugins/discover/public/application/components/loading_spinner/loading_spinner.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_bucket.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_data_frame.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/table/table.tsx
  src/plugins/discover/public/application/components/table/table_row.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.19.0

#9074 refactor some query-enhancement utility functions, add some missing typings
  changelogs/fragments/9074.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/queries.spec.js
  cypress/utils/apps/commands.js
  cypress/utils/apps/index.d.ts
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/index.d.ts
Labels: repeat-contributor, discover_2.0-test

#9045 [Manual backport 2.17] Bump `@opensearch-project/opensearch-next` from 2.9.0 to 2.13.0 (#9039)
  changelogs/fragments/8886.yml
  package.json
  scripts/postinstall.js
  yarn.lock
Labels: failed changeset

#8838 [MDS] Fix showing DQS sources list in workspaces
  changelogs/fragments/8838.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, first-time-contributor, v2.19.0

#9064 Improve CI checks on PRs
  .github/workflows/build_and_test_workflow.yml
  changelogs/fragments/9064.yml
  docs/_sidebar.md
  src/dev/license_checker/config.ts
  yarn.lock
Labels: distinguished-contributor

#9058 chore: Update oui to 1.18
  changelogs/fragments/9058.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, v2.19.0

#9082 Re-enable dataset_selector.spec.js and queries.spec.js under workspace
  changelogs/fragments/9082.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/constants.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/queries.spec.js
  cypress/support/e2e.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/dashboards/commands.js
  package.json
Labels: distinguished-contributor

#9116 [Workspace] fix: hide collaborators page on nav when newHomePage is disabled
  changelogs/fragments/9116.yml
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#8519 [workspace]Fix/UI of assets table
  changelogs/fragments/8519.yml
  src/core/server/ui_settings/saved_objects/ui_settings.ts
  src/plugins/data_source/server/saved_objects/data_source.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/components/workspace_column/workspace_colum.test.tsx
  src/plugins/workspace/public/components/workspace_column/workspace_column.tsx
Labels: backport 2.x, valued-contributor, workspace, v2.19.0

#9070 [Workspace] add missing method for workspace client interface
  changelogs/fragments/9070.yml
  src/core/public/index.ts
  src/core/public/workspace/types.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/server/index.ts
  src/core/types/workspace.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
  src/plugins/workspace/public/constants.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, distinguished-contributor, workspace, v2.19.0

#9059 [workspace] fix: manage link does not do anything
  changelogs/fragments/9059.yml
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.test.tsx
  src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.19.0

#9042 Disable buttons in sample data cards for read-only users
  changelogs/fragments/9042.yml
  src/plugins/home/public/application/components/sample_data_set_card.js
Labels: backport 2.x, home, seasoned-contributor, workspace, v2.19.0

#8237 [workspace] fix the UI of delete modal in the save objects(assets) page
  changelogs/fragments/8237.yml
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: backport 2.x, valued-contributor, workspace, v2.19.0

#9129 Make createWorkspaceIndexPatterns to handle no default cluster and clean up
  changelogs/fragments/9129.yml
  cypress.config.ts
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/constants.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/queries.spec.js
  cypress/utils/apps/commands.js
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/apps/workspace/commands.js
  cypress/utils/apps/workspace/index.d.ts
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/index.d.ts
Labels: backport 2.x, v2.19.0, discover_2.0-test

#9135 add data-test-subj
  src/plugins/data_explorer/public/components/sidebar/index.tsx
Labels: Skip-Changelog, first-time-contributor
