Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-06, with the labels that each got.

#6888 Cleanup styling and pre-work for data source selecotr
  plugins-extra/.gitignore
  plugins-extra/query_enhancements/target/public/.osd-optimizer-cache
  plugins-extra/query_enhancements/target/public/queryEnhancements.plugin.js
  plugins-extra/query_enhancements/target/public/queryEnhancements.plugin.js.map
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/mocks.ts
  src/plugins/data/public/ui/query_editor/index.tsx
  src/plugins/data/public/ui/query_editor/language_switcher.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
Labels: distinguished-contributor

#6811 Bug Fixes for Vis Builder
  changelogs/fragments/6811.yml
  src/plugins/vis_builder/public/application/components/data_tab/dropbox.scss
  src/plugins/visualizations/public/persisted_state/persisted_state.ts
Labels: vis builder, backport 2.x, repeat-contributor, v2.15.0

#6831 [Workspace] Only OSD admin can create workspace
  changelogs/fragments/6831.yml
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: backport 2.x, repeat-contributor, workspace, v2.15.0

#6770 [CVE-2024-33883] Bump ejs from `3.1.7` to `3.1.10`
  changelogs/fragments/6770.yml
  packages/osd-plugin-generator/package.json
  yarn.lock
Labels: cve, backport 2.x, distinguished-contributor, v2.15.0

#6894 [Discover-next] Add search bar extensions
  src/plugins/data/public/index.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/search_bar_extensions/index.ts
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.test.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extensions.test.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extensions.tsx
  src/plugins/data/public/ui/types.ts
Labels: first-time-contributor, failed changeset

#6780 [Discover][Bug] Migrate global state from legacy URL
  changelogs/fragments/6780.yml
  src/plugins/discover/public/migrate_state.ts
  src/plugins/discover/public/migrate_states.test.ts
Labels: bug, backport 2.x, discover, distinguished-contributor, v2.15.0

#6908 [BUG] fix default data source bug
  changelogs/fragments/6908.yml
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.15.0

#6492 Bump tar from 6.1.13 to 6.2.1
  changelogs/fragments/6492.yml
  package.json
  yarn.lock
Labels: cve, backport 2.x, repeat-contributor, v2.15.0

#4695 docs: remove `attributes.` in SavedObjectsFindOptions.fields example
  src/core/server/saved_objects/types.ts
Labels: needs more info, backport 2.x, Skip-Changelog, first-time-contributor, v2.15.0

#6918 [Backport 2.x][OSCI][FEAT] Changelog Project - PoC Changelog and release notes automation tool
  .github/pull_request_template.md
  .github/workflows/changelog_verifier.yml
  .github/workflows/opensearch_changelog_workflow.yml
  changelogs/README.md
  package.json
  scripts/generate_release_note.js
  src/dev/generate_release_note.ts
  src/dev/generate_release_note_helper.ts
Labels: v2.15.0

#6911 [CVE-2024-4067][CVE-2024-4068] Bump packages dependent on `braces` versions lower than 3.0.3
  .eslintrc.js
  changelogs/fragments/6911.yml
  package.json
  packages/osd-ace/package.json
  packages/osd-eslint-import-resolver-opensearch-dashboards/package.json
  packages/osd-eslint-plugin-eslint/package.json
  packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.test.js
  packages/osd-interpreter/package.json
  packages/osd-monaco/package.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/integration_tests/basic_optimization.test.ts
  packages/osd-optimizer/src/integration_tests/bundle_cache.test.ts
  packages/osd-optimizer/src/optimizer/watcher.ts
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/src/production/build_production_projects.ts
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, failed changeset, v2.15.0

#6915 Use JSON11 for handling long numerals
  changelogs/fragments/6915.yml
  package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch/package.json
  packages/osd-std/package.json
  packages/osd-std/src/json.ts
  yarn.lock
Labels: backport 2.x, distinguished-contributor, failed changeset, v2.15.0

#6899 [MD]Remove endpoint validation for create data source saved object API
  changelogs/fragments/6899.yml
  src/plugins/data_source/server/data_source_service.mock.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
Labels: backport 2.x, multiple datasource, distinguished-contributor, v2.15.0

#6904 Add disable multi-tenancy instruction when enable workspace
  config/opensearch_dashboards.yml
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.15.0

#6795 Add .lycheeignore and changelogs/fragments to workflow ignore
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/cypress_workflow.yml
Labels: backport 2.x, failed changeset, v2.15.0

#6928 [MD]Use placeholder for data source credentials fields when export saved object
  changelogs/fragments/6928.yml
  src/core/server/saved_objects/export/get_sorted_objects_for_export.test.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
Labels: backport 2.x, distinguished-contributor, v2.15.0

#6932 Update release notes for 1.3.17
  CHANGELOG.md
  release-notes/opensearch-dashboards.release-notes-1.3.17.md
Labels: Skip-Changelog

#6919 Modify the adding sample data part for timeline
  src/core/server/index.ts
  src/core/server/saved_objects/import/index.ts
  src/core/server/saved_objects/import/utils.test.ts
  src/core/server/saved_objects/import/utils.ts
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: backport 2.x, multiple datasource, v2.15.0

#6935 Add release notes for 1.3.17
  release-notes/opensearch-dashboards.release-notes-1.3.17.md
Labels: Skip-Changelog, repeat-contributor

#6833 Discover Flint datasource selector implementation
  src/plugins/data/common/search/search_source/fetch/get_search_params.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/common/search/search_source/types.ts
  src/plugins/data/public/data_sources/constants.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
  src/plugins/discover/public/application/view_components/utils/use_datasource.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: first-time-contributor, failed changeset, v2.15.0, discover-next

#6933 [Discover-next] Address comments for search bar extensions and query assist
  plugins-extra/query_enhancements/common/index.ts
  plugins-extra/query_enhancements/public/plugin.tsx
  plugins-extra/query_enhancements/public/query_assist/components/call_outs.tsx
  plugins-extra/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  plugins-extra/query_enhancements/public/query_assist/components/query_assist_input.tsx
  plugins-extra/query_enhancements/public/query_assist/components/submit_button.tsx
  plugins-extra/query_enhancements/public/query_assist/hooks/use_generate.ts
  plugins-extra/query_enhancements/public/query_assist/utils/create_extension.tsx
  plugins-extra/query_enhancements/server/routes/query_assist/agents.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar_extensions/index.ts
  src/plugins/data/public/ui/search_bar_extensions/index.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.test.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extensions.test.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extensions.tsx
Labels: repeat-contributor, failed changeset

#6846 Add server.ssl.cipherSuites to example opensearch_dashboards.yml
  config/opensearch_dashboards.yml
Labels: backport 2.x, Skip-Changelog, first-time-contributor, v2.15.0

#6940 [MDS] Fix sample data to use datasources for TSVB visualizations
  changelogs/fragments/6940.yml
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: backport 2.x, seasoned-contributor, v2.15.0

#6913 [Manual Backport 2.x] [Multiple DataSource] Do not support import data source object to Local cluster when not enable data source
  CHANGELOG.md
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/import/validate_object_id.test.ts
  src/core/server/saved_objects/import/validate_object_id.ts
  src/core/server/saved_objects/routes/import.ts
  src/plugins/saved_objects_management/public/lib/import_file.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
Labels: v2.15.0

#6920 [Multi DataSource] Add removedComponentIds for data source selection service
  changelogs/fragments/6920.yml
  src/plugins/data_source_management/public/service/data_source_selection_service.test.ts
  src/plugins/data_source_management/public/service/data_source_selection_service.ts
  src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap
Labels: backport 2.x, seasoned-contributor, v2.15.0

#6937 Update json5 dependency
  package.json
Labels: backport 2.x, Skip-Changelog, first-time-contributor, v2.15.0

#6949 [Discover-Next] Async Queries Implemention
  plugins-extra/query_enhancements/common/index.ts
  plugins-extra/query_enhancements/public/plugin.tsx
  plugins-extra/query_enhancements/public/search/sql_async_search_interceptor.ts
  plugins-extra/query_enhancements/server/plugin.ts
  plugins-extra/query_enhancements/server/routes/index.ts
  plugins-extra/query_enhancements/server/search/async/sql_async_facet.ts
  plugins-extra/query_enhancements/server/search/async/sql_async_jobs_facet.ts
  plugins-extra/query_enhancements/server/search/sql/sql_async_search_strategy.ts
  src/plugins/data/common/constants.ts
  src/plugins/data/common/data_frames/_df_cache.ts
  src/plugins/data/common/data_frames/_session_cache.ts
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/data/common/query/types.ts
  src/plugins/data/common/search/search_source/fetch/get_search_params.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/common/types.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/search/search_service.ts
  src/plugins/data/public/search/types.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/server/search/search_service.ts
  src/plugins/data/server/ui_settings.ts
Labels: repeat-contributor, failed changeset

#6903 [MDS] Use DataSourceError to replace Error in getDataSourceById call
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.test.ts
  src/plugins/data_source/common/data_sources/error.ts
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/data_source/server/index.ts
  src/plugins/data_source/server/lib/error.test.ts
  src/plugins/data_source/server/lib/error.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, seasoned-contributor, v2.15.0

#6953 [discover-next] some lint clean up and added override toggle
  plugins-extra/query_enhancements/common/index.ts
  plugins-extra/query_enhancements/public/search/sql_search_interceptor.ts
  plugins-extra/query_enhancements/server/plugin.ts
  plugins-extra/query_enhancements/server/search/ppl/ppl_facet.ts
  plugins-extra/query_enhancements/server/search/sql/sql_facet.ts
  plugins-extra/query_enhancements/server/ui_settings.ts
  src/cli/cluster/cluster_manager.ts
  src/dev/precommit_hook/casing_check_config.js
  src/plugins/data/common/constants.ts
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data/server/ui_settings.ts
  src/plugins/data_explorer/public/components/sidebar/index.tsx
Labels: distinguished-contributor, failed changeset, discover-next

#6955 [discover-next] fix advanced settings
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data_explorer/public/components/sidebar/index.tsx
Labels: distinguished-contributor

#6948 Fix web log sample visualization & vis-builder not rendering with data source issue
  changelogs/fragments/6948.yml
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: backport 2.x, multiple datasource, distinguished-contributor, v2.15.0

#6167 [Data Explorer] Allow render from View directly, not from Data Explorer
  src/plugins/data_explorer/public/components/app.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/utils/use/shallow_equal.test.ts
  src/plugins/data_explorer/public/utils/use/shallow_equal.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, discover, distinguished-contributor, data explorer, v2.15.0

#6951 [2.x] Cleanup yarn.lock
  packages/osd-pm/dist/index.js
  yarn.lock
Labels: Skip-Changelog, v2.15.0

#6907 [Workspace]Change workspace description field to textarea
  changelogs/fragments/6907.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
Labels: backport 2.x, valued-contributor, v2.15.0

#6887 [Workspace]Feat add use cases to workspace form
  changelogs/fragments/6887.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.scss
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, valued-contributor, workspace, v2.15.0

#6964 Update sidecar z-index style
  changelogs/fragments/6964.yml
  src/core/public/overlays/sidecar/components/sidecar.scss
Labels: backport 2.x, seasoned-contributor, v2.15.0

#6969 [discover] update advanced settings to restore state completely
  plugins-extra/query_enhancements/server/ui_settings.ts
  src/plugins/data/config.ts
  src/plugins/data/public/ui/query_editor/language_switcher.test.tsx
  src/plugins/data/public/ui/query_editor/language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.test.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/legacy_language_switcher.test.tsx
  src/plugins/data/public/ui/query_string_input/legacy_language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.test.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/public/ui/types.ts
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data/server/ui_settings.ts
Labels: distinguished-contributor, failed changeset

#6925 [Manual backport 2.x][CVE-2024-4067][CVE-2024-4068] Bump packages dependent on `braces` versions lower than 3.0.3 (#6911)
  .eslintrc.js
  changelogs/fragments/6911.yml
  package.json
  packages/osd-ace/package.json
  packages/osd-eslint-import-resolver-opensearch-dashboards/package.json
  packages/osd-eslint-plugin-eslint/package.json
  packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.test.js
  packages/osd-interpreter/package.json
  packages/osd-monaco/package.json
  packages/osd-optimizer/package.json
  packages/osd-optimizer/src/integration_tests/basic_optimization.test.ts
  packages/osd-optimizer/src/integration_tests/bundle_cache.test.ts
  packages/osd-optimizer/src/optimizer/watcher.ts
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/src/production/build_production_projects.ts
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: Skip-Changelog, v2.15.0

#6436 [VisBuilder] Change VisBuilder from experimental to production
  changelogs/fragments/6436.yml
  src/plugins/vis_builder/public/application/components/experimental_info.tsx
  src/plugins/vis_builder/public/application/components/workspace.scss
  src/plugins/vis_builder/public/application/components/workspace.tsx
  src/plugins/vis_builder/public/embeddable/disabled_embeddable.tsx
  src/plugins/vis_builder/public/embeddable/disabled_visualization.scss
  src/plugins/vis_builder/public/embeddable/disabled_visualization.tsx
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/plugin.test.ts
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/services/type_service/types.ts
  src/plugins/vis_builder/public/services/type_service/visualization_type.tsx
  test/functional/apps/vis_builder/_experimental_vis.ts
  test/functional/apps/vis_builder/index.ts
Labels: vis builder, backport 2.x, distinguished-contributor, v2.15.0

#6970 [Manual backport 2.x] Use JSON11 for handling long numerals (#6915)
  changelogs/fragments/6915.yml
  package.json
  packages/osd-std/package.json
  packages/osd-std/src/json.ts
  yarn.lock
Labels: Skip-Changelog, v2.15.0

#6954 Modify the import for timeline visualization to includes data source name in MDS scenario
  src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
  src/core/server/saved_objects/import/check_conflict_for_data_source.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
Labels: backport 2.x, multiple datasource, v2.15.0

#6972 [Discover-next] Support data sources for query assist
  plugins-extra/query_enhancements/common/query_assist/index.ts
  plugins-extra/query_enhancements/opensearch_dashboards.json
  plugins-extra/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  plugins-extra/query_enhancements/public/query_assist/components/query_assist_input.tsx
  plugins-extra/query_enhancements/public/query_assist/utils/create_extension.tsx
  plugins-extra/query_enhancements/public/query_assist/utils/get_mds_id.ts
  plugins-extra/query_enhancements/public/query_assist/utils/index.ts
  plugins-extra/query_enhancements/server/plugin.ts
  plugins-extra/query_enhancements/server/routes/index.ts
  plugins-extra/query_enhancements/server/routes/query_assist/agents.ts
  plugins-extra/query_enhancements/server/routes/query_assist/routes.ts
  plugins-extra/query_enhancements/server/types.ts
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: repeat-contributor, failed changeset, discover-next

#6966 [WIP] Async Queries Followup
  plugins-extra/query_enhancements/public/search/sql_async_search_interceptor.ts
  plugins-extra/query_enhancements/server/routes/index.ts
  plugins-extra/query_enhancements/server/search/async/sql_async_facet.ts
  plugins-extra/query_enhancements/server/search/ppl/ppl_search_strategy.ts
  src/plugins/data/common/search/search_source/fetch/get_search_params.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/search/search_service.ts
  src/plugins/data/server/search/search_service.ts
Labels: repeat-contributor, failed changeset, discover-next

#6978 Revert 815d2bd7c612450e2a15a6543c7e74558adf4a81 "[Manual Backport 2.x] Feat (core): Make theme settings user-specific and user-configurable (#5652) (#6681)"
  CHANGELOG.md
  docs/theme.md
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/types.ts
  src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
  src/core/server/rendering/views/fonts.tsx
  src/core/server/rendering/views/styles.tsx
  src/core/server/rendering/views/template.test.tsx
  src/core/server/rendering/views/template.tsx
  src/core/server/rendering/views/theme.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/types/ui_settings.ts
  src/legacy/ui/ui_render/bootstrap/app_bootstrap.js
  src/legacy/ui/ui_render/bootstrap/template.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/components/field/field.tsx
  src/plugins/advanced_settings/public/management_app/lib/to_editable_config.ts
  src/plugins/advanced_settings/public/management_app/types.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/public/register_nav_control.tsx
  src/plugins/opensearch_dashboards_usage_collection/server/collectors/management/schema.ts
  src/plugins/telemetry/schema/oss_plugins.json
  test/functional/apps/visualize/_custom_branding.ts
  test/functional/screenshots/baseline/tsvb_dashboard.png
Labels: Skip-Changelog, failed changeset, v2.15.0

#6898 Add missing aria-label for discover page
  docs/_sidebar.md
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/query_string_input/legacy_language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/table/table_row.tsx
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_item.tsx
Labels: backport 2.x, discover, distinguished-contributor, v2.15.0

#6977 [GHSA-x565-32qp-m3vf] Bump `jimp` to remove phin dependency
  changelogs/fragments/6977.yml
  package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.15.0

#6979 Add changelog for PR 6954
  changelogs/fragments/6954.yml
Labels: backport 2.x, Skip-Changelog, v2.15.0

#6986 Add missing change log for 2.15 MDS PRs
  changelogs/fragments/6385.yml
  changelogs/fragments/6395.yml
  changelogs/fragments/6919.yml
Labels: backport 2.x, Skip-Changelog, v2.15.0

#6985 [Manual backport 2.x][GHSA-x565-32qp-m3vf] Bump `jimp` to remove phin dependency (#6977)
  changelogs/fragments/6977.yml
  package.json
  yarn.lock
Labels: failed changeset, v2.15.0

#6987 [Manual Backport 2.x] Add missing aria-label for discover page
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/query_string_input/legacy_language_switcher.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/table/table_row.tsx
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu_item.tsx
Labels: Skip-Changelog

#6988 Add changelog for #6898
  changelogs/fragments/6167.yml
  changelogs/fragments/6898.yml
Labels: Skip-Changelog, distinguished-contributor, v2.15.0

#6980 Add Suchit to be a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/6980.yml
Labels: backport 2.x, distinguished-contributor, v2.15.0

#2732 [Release] Add release.yml for release notes automation
  .github/release.yml
Labels: release, backport 2.x, Skip-Changelog, failed changeset

#7009 Move release note to correct folder
  release-notes/opensearch-dashboards.release-notes-2.15.0.md
Labels: backport 2.x, seasoned-contributor, failed changeset

#6974 Add Scripted Field Support in Vis Builder
  src/plugins/vis_builder/public/application/components/data_tab/utils/get_available_fields.test.ts
  src/plugins/vis_builder/public/application/components/data_tab/utils/get_available_fields.ts
Labels: backport 2.x, valued-contributor, v2.16.0

#7012 Bump 2.x to 2.16.0
  package.json
Labels: failed changeset

#7018 update docs sidebar
  docs/_sidebar.md
Labels: Skip-Changelog, all-star-contributor, do not backport, v2.15.0

#7017 Optimize scrolling behavior of Discover table
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.15.0, backport 2.15

#7026 [Multiple Datasource][Version Decoupling] Add data source engine type to data source saved object
  changelogs/fragments/7026.yml
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/fetch_data_source_metadata.test.ts
  src/plugins/data_source/server/routes/fetch_data_source_metadata.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
Labels: multiple datasource, version decoupling, v2.16.0

#6983 [BUG][Discover] Check if the timestamp is already included to remove duplicate col
  changelogs/fragments/6983.yml
  src/plugins/discover/public/application/components/default_discover_table/helper.test.tsx
  src/plugins/discover/public/application/components/default_discover_table/helper.tsx
  src/plugins/discover/public/application/components/doc_viewer/doc_viewer_render_tab.tsx
Labels: bug, backport 2.x, discover, distinguished-contributor, v2.16.0

#7058 [Discover] Allow the last column of a table wider than the window to show up properly
  changelogs/fragments/7058.yml
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
Labels: backport 2.x, distinguished-contributor, v2.15.0, backport 2.15

#7068 Update release notes for 2.15
  release-notes/opensearch-dashboards.release-notes-2.15.0.md
Labels: Skip-Changelog, v2.15.0

#7025 Highlight the anchor row in surrounding doc view
  changelogs/fragments/7025.yml
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/doc_views/doc_views_types.ts
Labels: backport 2.x, discover, distinguished-contributor, v2.16.0

#7069 Update error message in timeline visualization when MDS disabled
  changelogs/fragments/7069.yml
  src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.test.ts
  src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.ts
Labels: ux / ui, backport 2.x, multiple datasource, distinguished-contributor, v2.16.0

#7034 [Discover-next] Add query editor extensions
  changelogs/fragments/7034.yml
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/query_editor/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/public/ui/types.ts
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: backport 2.x, repeat-contributor, v2.16.0, discover-next

#7087 Remove angular related comment and code
  changelogs/fragments/7087.yml
  packages/osd-ui-framework/src/global_styling/mixins/_global_mixins.scss
  src/plugins/vis_type_vislib/public/vislib/components/tooltip/_hierarchical_tooltip_formatter.js
Labels: backport 2.x, distinguished-contributor, v2.16.0

#7059 [Discover-Next] conditionally render selector
  changelogs/fragments/7059.yml
  package.json
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/ui/query_editor/_language_selector.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/types.ts
  src/plugins/data/server/search/opensearch_search/get_default_search_params.test.ts
  src/plugins/data/server/search/opensearch_search/get_default_search_params.ts
Labels: backport 2.x, distinguished-contributor, v2.16.0, discover-next

#7106 [Discover-Next] Adding datasources support for dataframes
  changelogs/fragments/7106.yml
  package.json
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/search/search_service.ts
  src/plugins/data/server/search/search_service.ts
Labels: backport 2.x, repeat-contributor, v2.16.0, discover-next

#5951 [Discover] Allow save query to load correctly in Discover
  src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/context/index.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/url_generator.ts
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.test.ts
  src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
  src/plugins/vis_builder/public/plugin.ts
  src/plugins/vis_builder/public/types.ts
  src/plugins/vis_builder/server/capabilities_provider.ts
Labels: bug, backport 2.x, discover, distinguished-contributor, v2.16.0

#7051 Fix colors of visualizations with more than 10 items
  changelogs/fragments/7051.yml
  src/plugins/charts/public/services/colors/mapped_colors.ts
Labels: bug, backport 2.x, repeat-contributor, v2.16.0

#7100 [Multiple Datasource][Version Decoupling] Support Version Decoupling in Index Patterns Dashboards Plugin
  changelogs/fragments/7100.yml
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/plugin.test.ts
  src/core/server/plugins/plugin.ts
  src/core/server/plugins/types.ts
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/index_pattern_management/opensearch_dashboards.json
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
  src/plugins/index_pattern_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, version decoupling, v2.16.0

#7077 Fix object empty check and minor perf issue in query editor extensions
  changelogs/fragments/7077.yml
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
Labels: backport 2.x, valued-contributor, v2.16.0, discover-next
