Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-08, with the labels that each got.

#7609 [dataset-nav][bug] get connections by cluster and update client namespace
  changelogs/fragments/7609.yml
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
  src/plugins/data/public/ui/dataset_navigator/index.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/catalog_cache/cache_loader.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/catalog_cache/cache_manager.ts
  src/plugins/data/public/ui/dataset_navigator/lib/constants.ts
  src/plugins/data/public/ui/dataset_navigator/lib/index.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/requests/index.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/requests/sql.ts
  src/plugins/data/public/ui/dataset_navigator/lib/types.tsx
  src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_external_data_sources.ts
  src/plugins/data/public/ui/dataset_navigator/lib/utils/index.ts
  src/plugins/data/public/ui/dataset_navigator/lib/utils/query_session_utils.ts
  src/plugins/data/public/ui/dataset_navigator/lib/utils/shared.ts
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/index.ts
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/search/index.ts
  src/plugins/query_enhancements/server/search/ppl_raw_search_strategy.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.ts
  src/plugins/query_enhancements/server/types.ts
  src/plugins/query_enhancements/server/utils/facet.ts
  src/plugins/query_enhancements/server/utils/index.ts
  src/plugins/query_enhancements/server/utils/plugins.ts
Labels: backport 2.x, distinguished-contributor, v2.16.0, backport 2.16

#7596 [Workspace] add validation for data source in get and bulk_get methods
  changelogs/fragments/7596.yml
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: all-star-contributor, workspace, v2.17.0

#7547 [Workspace] update workspace-list-card and home-list-card
  changelogs/fragments/7547.yml
  src/plugins/home/public/application/components/__snapshots__/home_list_card.test.tsx.snap
  src/plugins/home/public/application/components/home_list_card.test.tsx
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/workspace/public/components/service_card/__snapshots__/workspace_list_card.test.tsx.snap
  src/plugins/workspace/public/components/service_card/workspace_list_card.test.tsx
  src/plugins/workspace/public/components/service_card/workspace_list_card.tsx
Labels: first-time-contributor, workspace, v2.17.0

#7613 [navigation]fix: add sample data to left navigation
  changelogs/fragments/7613.yml
  src/plugins/home/public/plugin.ts
Labels: bug, backport 2.x, all-star-contributor, v2.16.0, navigation, backport 2.16

#7603 [Look&Feel] Update paragraph text sizes across remaining OSD
  changelogs/fragments/7603.yml
  src/plugins/console/public/application/components/help_panel.tsx
  src/plugins/console/public/application/containers/console_history/console_history.tsx
  src/plugins/dashboard/public/application/utils/__snapshots__/get_no_items_message.test.tsx.snap
  src/plugins/dashboard/public/application/utils/get_no_items_message.test.tsx
  src/plugins/dashboard/public/application/utils/get_no_items_message.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/data_source_creation_panel/__snapshots__/create_data_source_panel_header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel_header.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_page_header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/__snapshots__/acceleration_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/__snapshots__/access_control_tab.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/access_control_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/utils/__snapshots__/no_access_page.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/utils/no_access_page.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/field_editor/__snapshots__/field_editor.test.tsx.snap
  src/plugins/index_pattern_management/public/components/field_editor/field_editor.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Labels: backport 2.x, valued-contributor, v2.17.0, look & feel

#7621 [Look&Feel] apply small list pattern guidance to remaning OSD experiences
  examples/embeddable_examples/public/multi_task_todo/multi_task_todo_component.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, look & feel

#7624 fix: get start section cards not aligned
  changelogs/fragments/7624.yml
  src/plugins/content_management/public/components/card_container/card_container.tsx
  src/plugins/content_management/public/components/card_container/card_embeddable.tsx
  src/plugins/content_management/public/components/card_container/card_list.tsx
  src/plugins/content_management/public/components/card_container/types.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/services/content_management/types.ts
Labels: seasoned-contributor, v2.17.0

#6421 fix bug: management section id not match the key defined in capabilities
  src/plugins/management/common/contants.ts
  src/plugins/management/public/management_sections_service.test.ts
  src/plugins/management/public/management_sections_service.ts
  src/plugins/management/server/capabilities_provider.ts
Labels: backport 2.x, repeat-contributor, v2.17.0

#7550 Fix browser warnings
  changelogs/fragments/7550.yml
  src/plugins/content_management/public/components/page_render.tsx
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/home/public/application/home_render.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: first-time-contributor, v2.17.0

#7575 [Doc] Documentation of content management plugin
  changelogs/fragments/7575.yml
  src/plugins/content_management/README.md
Labels: docs, seasoned-contributor, v2.17.0

#7633 fix: do not throw exception if content provider id exists
  changelogs/fragments/7633.yml
  src/plugins/content_management/public/components/section_input.test.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/services/content_management/content_management_service.ts
  src/plugins/content_management/public/services/content_management/page.test.ts
  src/plugins/content_management/public/services/content_management/page.ts
Labels: seasoned-contributor

#7586 [Look&Feel] Apply small tabs pattern guidance to remaining OSD experiences
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/__snapshots__/acceleration_details_flyout.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_details_flyout.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
Labels: enhancement, backport 2.x, distinguished-contributor, v2.17.0, look & feel

#7512 [Worksapce]Add blank check for workspace name
  changelogs/fragments/7512.yml
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
Labels: seasoned-contributor, v2.17.0

#7600 Add a util function to generate the relative redirectUrl
  changelogs/fragments/7600.yml
  src/core/server/http/http_tools.test.ts
  src/core/server/http/http_tools.ts
  src/core/server/http/index.ts
Labels: all-star-contributor, workspace, v2.17.0

#7618 [navigation]feat: replace analytics nav group with essentials
  changelogs/fragments/7618.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/utils/default_nav_groups.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/discover/public/plugin.ts
  src/plugins/home/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/utils.test.ts
Labels: all-star-contributor, v2.17.0, navigation

#7616 [Look&Feel] Use semantic headers for page, modal, & flyouts across the board
  changelogs/fragments/7616.yml
  src/plugins/advanced_settings/public/component_registry/page_title/__snapshots__/page_title.test.tsx.snap
  src/plugins/advanced_settings/public/component_registry/page_title/page_title.tsx
  src/plugins/console/public/application/components/__snapshots__/import_flyout.test.tsx.snap
  src/plugins/console/public/application/components/help_panel.tsx
  src/plugins/console/public/application/components/import_flyout.tsx
  src/plugins/console/public/application/components/settings_modal.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/data_source_creation_panel/__snapshots__/create_data_source_panel_header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel_header.test.tsx
  src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel_header.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_page_header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_creation/create/create_acceleration_header.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/__snapshots__/configure_amazon_s3_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/__snapshots__/review_amazon_s3_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/configure_amazon_s3_data_source.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/review_amazon_s3_data_source.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/__snapshots__/configure_prometheus_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/__snapshots__/review_prometheus_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/configure_prometheus_data_source.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/review_prometheus_data_source.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
  src/plugins/management_overview/public/__snapshots__/application.test.tsx.snap
  src/plugins/management_overview/public/application.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: backport 2.x, valued-contributor, v2.17.0, look & feel

#7619 [navigation]feat: make parent item unclickable and fix duplicate items in landing page.
  changelogs/fragments/7619.yml
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/utils.test.ts
  src/core/public/chrome/utils.ts
  src/core/public/index.ts
  src/plugins/management/public/plugin.ts
  src/plugins/workspace/public/plugin.ts
Labels: bug, all-star-contributor, v2.17.0, navigation

#7503 feat: provide new embeddable option to hide embeddable panel action button
  changelogs/fragments/7503.yml
  src/plugins/embeddable/common/types.ts
  src/plugins/embeddable/public/lib/panel/embeddable_panel.test.tsx
  src/plugins/embeddable/public/lib/panel/embeddable_panel.tsx
  src/plugins/embeddable/public/lib/panel/panel_header/panel_header.tsx
Labels: backport 2.x, seasoned-contributor, v2.17.0

#7671 [Workspace]Fix page crash caused by invalid workspace color
  changelogs/fragments/7671.yml
  src/plugins/workspace/common/__tests__/utils.test.ts
  src/plugins/workspace/common/utils.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/server/routes/index.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7627 [Workspace] Set the default color to first color from the palette
  changelogs/fragments/7627.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
Labels: backport 2.x, first-time-contributor, workspace, v2.17.0

#7612 [Workspace] feat: only allow essential use case when creating workspace if all data sources are serverless
  changelogs/fragments/7612.yml
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7651 feat: [contentManagement] allow to update section input after page rendered
  changelogs/fragments/7651.yml
  src/plugins/content_management/public/components/card_container/types.ts
  src/plugins/content_management/public/components/section_input.test.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/components/types.ts
  src/plugins/content_management/public/plugin.ts
  src/plugins/content_management/public/services/content_management/content_management_service.test.ts
  src/plugins/content_management/public/services/content_management/content_management_service.ts
  src/plugins/content_management/public/services/content_management/page.test.ts
  src/plugins/content_management/public/services/content_management/page.ts
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/content_management/public/types.ts
Labels: backport 2.x, seasoned-contributor, v2.17.0, content-management

#7695 fix: add missing doc entry for content management plugin
  docs/_sidebar.md
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.17.0

#7691 Allow customizing `restrictWidth` and `paddingSize` of `TableListView`
  changelogs/fragments/7691.yml
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0, look & feel

#7702 [WorkSpace] Refractor homepage assets list section
  changelogs/fragments/7702.yml
  src/plugins/saved_objects_management/public/management_section/recent_work.test.tsx
  src/plugins/saved_objects_management/public/management_section/recent_work.tsx
  src/plugins/saved_objects_management/public/plugin.ts
Labels: backport 2.x, repeat-contributor, v2.17.0

#7656 [Workspace]Add name and description characters limitation
  changelogs/fragments/7656.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_form/fields/workspace_description_field.test.tsx
  src/plugins/workspace/public/components/workspace_form/fields/workspace_description_field.tsx
  src/plugins/workspace/public/components/workspace_form/fields/workspace_name_field.test.tsx
  src/plugins/workspace/public/components/workspace_form/fields/workspace_name_field.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/workspace_create_action_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_create_action_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_enter_details_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/server/routes/index.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7697 [Workspace][Page header] Integrate new page header for workspace pages
  changelogs/fragments/7697.yml
  src/plugins/management/opensearch_dashboards.json
  src/plugins/management/public/components/feature_cards/__snapshots__/feature_cards.test.tsx.snap
  src/plugins/management/public/components/feature_cards/feature_cards.test.tsx
  src/plugins/management/public/components/feature_cards/feature_cards.tsx
  src/plugins/management/public/landing_page_application.test.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
Labels: backport 2.x, all-star-contributor, v2.17.0, look & feel

#7598 [Workspace] Refactor workspace detail page
  changelogs/fragments/7598.yml
  src/plugins/workspace/common/types.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_content.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/public/workspace_client.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7687 Refactor search bar & filters to conditionally render new look with application header
  changelogs/fragments/7687.yml
  src/plugins/data/common/constants.ts
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.test.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.test.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0, look & feel

#7721 Allow `screenTitle` to be present when SearchBar is not in Application header
  changelogs/fragments/7721.yml
  src/plugins/navigation/public/top_nav_menu/_index.scss
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0

#7723 Simplify `TopNavControlDescriptionData` to to be followed by links
  changelogs/fragments/7723.yml
  src/core/public/chrome/ui/header/header_controls_container.scss
  src/plugins/navigation/public/top_nav_menu/top_nav_control_data.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_control_item.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0

#7655 [navigation] Left navigation collective
  changelogs/fragments/7655.yml
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/utils/default_app_categories.ts
  src/core/utils/default_nav_groups.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/home/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.test.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/management/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, v2.17.0, navigation

#7726 feat: fix unit test error
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
Labels: backport main, Skip-Changelog, all-star-contributor

#7501 [Workspace] Support getting workspace client from coreStart
  changelogs/fragments/7501.yml
  src/core/public/index.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/saved_objects_management/public/index.ts
  src/plugins/saved_objects_management/public/lib/duplicate_saved_objects.test.ts
  src/plugins/saved_objects_management/public/lib/duplicate_saved_objects.ts
  src/plugins/saved_objects_management/public/lib/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.mocks.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/workspace_client.mock.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7625 refactor: simplify theme configuration and defaulting
  changelogs/fragments/7625.yml
  docs/theme.md
  packages/osd-optimizer/src/common/theme_tags.ts
  packages/osd-ui-shared-deps/index.d.ts
  packages/osd-ui-shared-deps/index.js
  packages/osd-ui-shared-deps/theme.ts
  packages/osd-ui-shared-deps/theme_config.d.ts
  packages/osd-ui-shared-deps/theme_config.js
  src/core/public/ui_settings/__snapshots__/ui_settings_client.test.ts.snap
  src/core/public/ui_settings/types.ts
  src/core/public/ui_settings/ui_settings_client.test.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/public/ui_settings/ui_settings_service.mock.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/server/ui_settings/types.ts
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/ui_settings_config.ts
  src/core/server/ui_settings/ui_settings_service.mock.ts
  src/legacy/ui/ui_render/bootstrap/bootstrap.js.hbs
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
Labels: backport 2.x, repeat-contributor, v2.17.0, look & feel

#7735 Update Recent popover to always render breadcrumbs with full length
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0

#7720 [Release 2.17.0] Increment to 2.17.0
  package.json
Labels: Skip-Changelog

#7745 [discover] update interfaces and move dataset manager
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/index.tsx
  src/plugins/data/public/query/mocks.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/query_string/dataset_manager/dataset_manager.mock.ts
  src/plugins/data/public/query/query_string/dataset_manager/dataset_manager.test.ts
  src/plugins/data/public/query/query_string/dataset_manager/dataset_manager.ts
  src/plugins/data/public/query/query_string/dataset_manager/index.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/query/state_sync/create_global_query_observable.ts
  src/plugins/data/public/query/state_sync/types.ts
Labels: distinguished-contributor, failed changeset, discover-next

#7746 [Manual Backport 2.x] refactor: simplify theme configuration and defaulting (#7625)
  changelogs/fragments/7625.yml
  docs/theme.md
  packages/osd-optimizer/src/common/theme_tags.ts
  packages/osd-ui-shared-deps/index.d.ts
  packages/osd-ui-shared-deps/index.js
  packages/osd-ui-shared-deps/theme.ts
  packages/osd-ui-shared-deps/theme_config.d.ts
  packages/osd-ui-shared-deps/theme_config.js
  src/core/public/ui_settings/__snapshots__/ui_settings_client.test.ts.snap
  src/core/public/ui_settings/types.ts
  src/core/public/ui_settings/ui_settings_client.test.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/public/ui_settings/ui_settings_service.mock.ts
  src/core/server/rendering/rendering_service.tsx
  src/core/server/ui_settings/settings/theme.ts
  src/core/server/ui_settings/types.ts
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/ui_settings_config.ts
  src/core/server/ui_settings/ui_settings_service.mock.ts
  src/legacy/ui/ui_render/bootstrap/startup.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
Labels: Skip-Changelog

#7728 [Backport 2.x] [navigation] Left navigation collective
  changelogs/fragments/7655.yml
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/utils/default_app_categories.ts
  src/core/utils/default_nav_groups.ts
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/home/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.test.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/management/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/utils.ts
Labels: Skip-Changelog

#7732 [CVE-2024-37890][1.3] Bump ws from `6.2.2` to `6.2.3` and from `7.5.3` to `7.5.10`
  yarn.lock
Labels: cve, Skip-Changelog, v1.3.19

#7736 [1.3][CVE-2024-28863] Bump tar from `6.1.11` to `6.2.1`
  yarn.lock
Labels: cve, Skip-Changelog, v1.3.19

#7737 [1.3][CVE-2024-28849] Bump follow-redirects from `1.15.2` to `1.15.6`
  package.json
  yarn.lock
Labels: cve, Skip-Changelog, v1.3.19

#7738 [1.3][CVE-2024-29041] Bump express from 4.18.2 to 4.19.2
  package.json
  yarn.lock
Labels: cve, Skip-Changelog, v1.3.19

#7741 Revisit updated header spacing
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/recent_items.test.tsx.snap
  src/core/public/chrome/ui/header/header.scss
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_controls_container.scss
  src/core/public/chrome/ui/header/recent_items.scss
  src/core/public/chrome/ui/header/recent_items.tsx
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/navigation/public/top_nav_menu/_index.scss
  src/plugins/navigation/public/top_nav_menu/top_nav_control_item.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0

#7701 Add an unified storage class for data plugin
  src/plugins/data/common/index.ts
  src/plugins/data/common/storage/index.ts
  src/plugins/data/common/storage/storage.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/lib/add_to_query_log.ts
  src/plugins/data/public/query/lib/get_query_log.ts
  src/plugins/data/public/query/persisted_log/persisted_log.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/query_string/query_history.ts
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
  src/plugins/data/public/query/timefilter/time_history.ts
  src/plugins/data/public/query/timefilter/timefilter_service.ts
  src/plugins/data/public/types.ts
  src/plugins/data/public/ui/query_string_input/no_data_popover.tsx
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.test.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/settings/settings.ts
  src/plugins/data/public/ui/ui_service.ts
Labels: distinguished-contributor, v2.17.0, discover-next

#7744 Refactor: update page header for settings, objects and index pattern page
  changelogs/fragments/7744.yml
  src/plugins/advanced_settings/opensearch_dashboards.json
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/advanced_settings/public/management_app/advanced_settings.test.tsx
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/public/types.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/description.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/description.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/description.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/index.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/tabs/tabs.tsx
  src/plugins/index_pattern_management/public/mocks.ts
  src/plugins/management/public/components/management_app/management_app.tsx
  src/plugins/management/public/components/management_app/management_router.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
Labels: backport 2.x, all-star-contributor, v2.17.0, look & feel

#7640 [Workspace] Update workspace list page table
  changelogs/fragments/7640.yml
  src/plugins/workspace/public/components/delete_workspace_modal/__snapshots__/delete_workspace_modal.test.tsx.snap
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.test.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#7725 fix ts type of injectSearchSourceReferences to avoid type casting
  src/plugins/data/common/search/search_source/inject_references.ts
  src/plugins/saved_objects/public/saved_object/helpers/apply_opensearch_resp.ts
  src/plugins/vis_builder/public/saved_visualizations/saved_visualization_references.ts
  src/plugins/visualizations/public/saved_visualizations/saved_visualization_references.ts
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.17.0

#7708 [Workspace] Support workspace initial page
  changelogs/fragments/7708.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/assets/background_dark.svg
  src/plugins/workspace/public/assets/background_light.svg
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.test.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/components/workspace_initial_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7768 [Workspace]fix the parameter misalignment error in the workspace_detail_page
  changelogs/fragments/7768.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#7769 [Manual backport 2.x] Refactor: update page header for settings, objects and index pattern page
  changelogs/fragments/7744.yml
  src/plugins/advanced_settings/opensearch_dashboards.json
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/advanced_settings/public/management_app/advanced_settings.test.tsx
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/public/types.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/description.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/description.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/description.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/index.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/tabs/tabs.tsx
  src/plugins/index_pattern_management/public/mocks.ts
  src/plugins/management/public/components/management_app/management_app.tsx
  src/plugins/management/public/components/management_app/management_router.tsx
  src/plugins/management/public/plugin.ts
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
Labels: Skip-Changelog

#7758 [Autocomplete - SQL] Minor interface change to add suggestion type and move suggestion provider registration location
  changelogs/fragments/7758.yml
  packages/osd-monaco/src/xjson/lexer_rules/opensearchsql.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: valued-contributor

#7712 Add Application Page Header for Visualize Pages
  changelogs/fragments/7712.yml
  src/plugins/dashboard/public/application/components/dashboard_listing/dashboard_listing.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  src/plugins/vis_builder/public/application/app.tsx
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/visualize/public/application/app.tsx
  src/plugins/visualize/public/application/components/visualize_byvalue_editor.tsx
  src/plugins/visualize/public/application/components/visualize_editor.tsx
  src/plugins/visualize/public/application/components/visualize_listing.tsx
  src/plugins/visualize/public/application/components/visualize_top_nav.tsx
  src/plugins/visualize/public/application/utils/constants.ts
  src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
Labels: backport 2.x, seasoned-contributor, v2.17.0, look & feel

#7693 feat: card section and dashboards section UX improvements
  src/plugins/content_management/public/components/card_container/card_list.tsx
  src/plugins/content_management/public/components/card_container/types.ts
  src/plugins/content_management/public/components/section_input.test.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/services/content_management/types.ts
Labels: backport 2.x, seasoned-contributor, v2.17.0, content-management

#7527 [Vis-Builder] Fix Droppable Areas not highlighting while dragging a Field
  changelogs/fragments/7527.yml
  src/plugins/vis_builder/public/application/components/data_tab/config_panel.tsx
  src/plugins/vis_builder/public/application/components/data_tab/constants.ts
  src/plugins/vis_builder/public/application/components/data_tab/dropbox.tsx
  src/plugins/vis_builder/public/application/components/data_tab/index.tsx
  src/plugins/vis_builder/public/application/components/data_tab/schema_to_dropbox.tsx
  src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
Labels: bug, vis builder, backport 2.x, v2.17.0

#7777 [Look & Feel] Appearance Popover Button Change
  changelogs/fragments/7777.yml
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
Labels: backport 2.x, first-time-contributor, v2.17.0, look & feel

#7788 [Page Header]Make saved queries a context menu item in filter options instead of a button
  src/plugins/data/public/ui/filter_bar/filter_options.test.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
Labels: enhancement, backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0

#7774 Adapt the newsfeed button to the updated header
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
  src/plugins/newsfeed/public/components/newsfeed_header_nav_button.scss
  src/plugins/newsfeed/public/components/newsfeed_header_nav_button.tsx
  src/plugins/newsfeed/public/plugin.tsx
Labels: backport 2.x, v2.17.0

#7781 [2.x manual backport]Change the locale dynamically by adding &i18n-locale to URL (#7686)
  changelogs/fragments/7686.yml
  packages/osd-i18n/src/core/i18n.test.ts
  packages/osd-i18n/src/core/i18n.ts
  src/core/public/application/scoped_history.test.ts
  src/core/public/application/scoped_history.ts
  src/core/public/locale_helper.test.ts
  src/core/public/locale_helper.ts
  src/core/public/osd_bootstrap.test.mocks.ts
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/dev/jest/config.js
  src/legacy/server/i18n/index.ts
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/legacy/ui/ui_render/ui_render_mixin.test.js
Labels: failed changeset, v2.17.0

#7776 [Rebase #6730 and fix tests] Fix/UI settings overrides
  src/core/server/ui_settings/settings/theme.ts
  src/core/server/ui_settings/types.ts
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/ui_settings_config.ts
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  test/functional/apps/visualize/_custom_branding.ts
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
  yarn.lock
Labels: bug, backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0

#7796 Fix new header allowing their single-child's overflowing
  changelogs/fragments/7796.yml
  src/core/public/chrome/ui/header/header.scss
Labels: backport 2.x, distinguished-contributor, v2.17.0

#7703 [Workspaces]Add features in use case card and preselect first use case
  changelogs/fragments/7703.yml
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_form_available_use_cases.test.ts
  src/plugins/workspace/public/components/workspace_form/use_form_available_use_cases.ts
  src/plugins/workspace/public/components/workspace_form/workspace_enter_details_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/mocks.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7801 Add `flush` to `TopNavControlLinkData`
  changelogs/fragments/7801.yml
  src/plugins/navigation/public/top_nav_menu/top_nav_control_data.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_control_item.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0

#5282 [Workspace] Add workspace design documentation
  src/plugins/workspace/README.md
Labels: workspace, failed changeset, v2.17.0

#7771 [Workspace] Refactor: workspace detail page header
  changelogs/fragments/7771.yml
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.scss
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7804 Fix query assistant fetching agent bug
  changelogs/fragments/7804.yml
  src/plugins/query_enhancements/server/routes/query_assist/agents.test.ts
  src/plugins/query_enhancements/server/routes/query_assist/agents.ts
Labels: backport 2.x, first-time-contributor, failed changeset, v2.17.0

#7795 [Workspace] Adjust the appearance of collaborator panel
  changelogs/fragments/7795.yml
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#7785 [Workspace] feat: Add workspace navigation for default route
  changelogs/fragments/7785.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_panel.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7802 [navigation]feat: add home icon in left bottom
  changelogs/fragments/7802.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/plugins/home/public/application/components/home_icon.test.tsx
  src/plugins/home/public/application/components/home_icon.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: backport 2.x, distinguished-contributor, v2.17.0, navigation

#7749 [navigation] Fix: breadcrumb is not correct when clicking inspect / edit in Assets page
  changelogs/fragments/7749.yml
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/workspace/public/services/use_case_service.ts
Labels: bug, backport 2.x, distinguished-contributor, v2.17.0, navigation

#7811 [CVE-2017-16100] Use a patched version of `dns-sync`
  changelogs/fragments/7811.yml
  package.json
  yarn.lock
Labels: backport 1.3, backport 2.x, distinguished-contributor, v2.17.0

#7529 [VisBuilder-Next] Migrate legacy visualizations to visbuilder by mapping the url
  changelogs/fragments/7529.yml
  src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.test.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/vis_builder/public/application/utils/breadcrumbs.ts
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/use/use_can_save.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/visualize/public/application/components/visualize_listing.tsx
  src/plugins/visualize/public/application/utils/construct_vis_builder_path.ts
  src/plugins/visualize/public/application/utils/contruct_vis_builder_path.test.ts
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: enhancement, first-time-contributor, v2.17.0, visbuilder-next

#7827 Fix the adoption of the new header in the index pattern management pages
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0

#7829 Readjust spacing of header
  src/core/public/chrome/ui/header/header.scss
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0

#7812 fix: correct size of dashboard panel options icon button
  changelogs/fragments/7812.yml
  src/plugins/embeddable/public/lib/panel/panel_header/panel_options_menu.tsx
Labels: backport 2.x, valued-contributor, v2.17.0, look & feel

#7834 [navigation]fix: unit test failure introduced by #7749
  src/plugins/workspace/public/services/use_case_service.test.ts
Labels: test:unit, Skip-Changelog, distinguished-contributor

#7817 [Workspace]Fix maximum call stack error in use case service
  changelogs/fragments/7817.yml
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: bug, backport 2.x, seasoned-contributor, v2.17.0

#7841 [Workspace]Remove default appended features
  changelogs/fragments/7841.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7842 [Refactor] [Workspace] Use small button, small padding and compressed.
  changelogs/fragments/7842.yml
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7850 [Disocver Next] Fixes language selection for indices +1
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
Labels: discover, Skip-Changelog, distinguished-contributor, v2.17.0, discover-next

#7810 [Autocomplete] PPL Autocomplete
  .gitignore
  changelogs/fragments/7810.yml
  package.json
  packages/osd-monaco/src/xjson/lexer_rules/index.ts
  packages/osd-monaco/src/xjson/lexer_rules/opensearchppl.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.tokens
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.tokens
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLLexer.g4
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLParser.g4
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/antlr/shared/general_error_listerner.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/plugin.ts
Labels: valued-contributor

#7852 [discover] Updates to mocks for tests and ci
  src/plugins/data/common/constants.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/language_service/language_service.mock.ts
  src/plugins/data/public/query/query_string/query_string_manager.mock.ts
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: distinguished-contributor, failed changeset

#7836 [Backport 2.x][navigation]feat: add home icon in left bottom (#7802)
  changelogs/fragments/7802.yml
  packages/osd-pm/dist/index.js
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/plugins/home/public/application/components/home_icon.test.tsx
  src/plugins/home/public/application/components/home_icon.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: Skip-Changelog

#7818 [Workspace] feat: add data source and owners column to workspace list page table
  src/core/public/index.ts
  src/core/public/saved_objects/simple_saved_object.ts
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7673 [Workspace]Essential/Analytics(All) use case overview page
  changelogs/fragments/7673.yml
  src/core/public/index.ts
  src/core/utils/default_nav_groups.ts
  src/core/utils/index.ts
  src/plugins/content_management/public/components/card_container/card_embeddable.test.tsx
  src/plugins/content_management/public/components/card_container/card_embeddable.tsx
  src/plugins/content_management/public/components/card_container/card_list.tsx
  src/plugins/content_management/public/components/card_container/types.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/content_management/public/constants.ts
  src/plugins/content_management/public/index.ts
  src/plugins/content_management/public/mocks.ts
  src/plugins/content_management/public/services/content_management/content_management_service.test.ts
  src/plugins/content_management/public/services/content_management/content_management_service.ts
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/home/common/constants.ts
  src/plugins/home/public/application/components/home_app.js
  src/plugins/home/public/application/components/home_list_card.test.tsx
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.test.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.tsx
  src/plugins/home/public/application/home_render.tsx
  src/plugins/home/public/index.ts
  src/plugins/home/public/plugin.ts
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/use_case_overview/get_started_cards.tsx
  src/plugins/workspace/public/components/use_case_overview/index.ts
  src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx
  src/plugins/workspace/public/components/workspace_use_case_overview_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7854 Added release notes for 1.3.19
  release-notes/opensearch-dashboards.release-notes-1.3.19.md
Labels: Skip-Changelog, repeat-contributor

#7865 chore: Update oui to 1.12
  changelogs/fragments/7865.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, valued-contributor, v2.17.0, look & feel

#7593 [Auto Suggest] DQL Updates
  .gitignore
  changelogs/fragments/7593.yml
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLLexer.tokens
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.interp
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.java
  src/plugins/data/public/antlr/dql/grammar/.antlr/DQLParser.tokens
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/autocomplete/autocomplete_service.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx
Labels: backport 2.x, valued-contributor, v2.17.0, discover-next

#7866 [discover] Query editor UI changes
  changelogs/fragments/7866.yml
  docs/_sidebar.md
  src/plugins/data/public/query/query_string/language_service/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/flyout_containers.tsx
  src/plugins/data/public/query/query_string/language_service/get_query_control_links.tsx
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/dedup.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/eval.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/fields.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/head.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/index.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/parse.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/rare.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/rename.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/search.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/sort.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/stats.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/syntax.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/top.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/where.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/condition.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/datetime.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/full_text_search.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/index.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/math.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/string.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/groups.tsx
  src/plugins/data/public/query/query_string/language_service/ppl_docs/language_structure/datatypes.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/language_structure/identifiers.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/language_structure/index.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/overview.tsx
  src/plugins/data/public/query/query_string/language_service/ppl_reference_flyout.tsx
  src/plugins/data/public/query/query_string/language_service/recent_query.tsx
  src/plugins/data/public/query/query_string/language_service/sql_reference_flyout.tsx
  src/plugins/data/public/query/query_string/query_history.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/query_editor/_language_selector.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0, discover-next

#7716 [navigation] display workspace picker content when outside workspace and nav group
  changelogs/fragments/7716.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_groups.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/utils.ts
  src/plugins/data_explorer/public/plugin.ts
  src/plugins/home/public/plugin.ts
  src/plugins/index_pattern_management/public/plugin.test.ts
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, v2.17.0, navigation

#7833 [Page Header]Implement new page header for admin data sources page
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/__snapshots__/query_permissions.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/__snapshots__/configure_amazon_s3_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/configure_amazon_s3_data_source.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/configure_direct_query_data_sources.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/__snapshots__/configure_prometheus_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/configure_prometheus_data_source.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/query_permissions.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/management_app/mount_management_section.test.tsx
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/types.ts
Labels: Skip-Changelog, first-time-contributor

#7861 [Look&Feel] [Workspace] Use compress EuiDescriptionList
  src/plugins/workspace/public/components/service_card/workspace_list_card.tsx
Labels: Skip-Changelog, all-star-contributor

#7878 [Manual Backport][2.x][Workspace] Use small button, small padding and compressed.
  changelogs/fragments/7842.yml
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: Skip-Changelog

#7875 tweaks the new homepage styles
  src/plugins/content_management/public/components/page_render.tsx
  src/plugins/content_management/public/components/section_input.test.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/home/public/application/components/__snapshots__/home_list_card.test.tsx.snap
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/home/public/application/home_render.tsx
  src/plugins/saved_objects_management/public/management_section/recent_work.tsx
  src/plugins/workspace/public/components/service_card/__snapshots__/workspace_list_card.test.tsx.snap
  src/plugins/workspace/public/components/service_card/workspace_list_card.tsx
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.17.0, look & feel

#7871 Support injecting `DataStructureMeta` from `QueryEditorExtensions` for Query Assist
  changelogs/fragments/7871.yml
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/utils.ts
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: seasoned-contributor

#7890 fix(queryAssist): allow dataset with `DATA_SOURCE` type
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.17.0

#7885 [Discover 2.0] UI Fixes
  docs/openapi/README.md
  src/core/public/overlays/modal/modal_service.tsx
  src/plugins/data/public/ui/dataset_selector/_dataset_configurator.scss
  src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss
  src/plugins/data/public/ui/dataset_selector/_index.scss
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
Labels: Skip-Changelog, distinguished-contributor

#7889 [Manual backport 2.x] Query editor UI changes
  changelogs/fragments/7866.yml
  src/plugins/data/public/query/query_string/language_service/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/flyout_containers.tsx
  src/plugins/data/public/query/query_string/language_service/get_query_control_links.tsx
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/dedup.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/eval.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/fields.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/head.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/index.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/parse.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/rare.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/rename.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/search.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/sort.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/stats.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/syntax.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/top.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/commands/where.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/condition.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/datetime.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/full_text_search.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/index.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/math.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/functions/string.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/groups.tsx
  src/plugins/data/public/query/query_string/language_service/ppl_docs/language_structure/datatypes.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/language_structure/identifiers.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/language_structure/index.ts
  src/plugins/data/public/query/query_string/language_service/ppl_docs/overview.tsx
  src/plugins/data/public/query/query_string/language_service/ppl_reference_flyout.tsx
  src/plugins/data/public/query/query_string/language_service/recent_query.tsx
  src/plugins/data/public/query/query_string/language_service/sql_reference_flyout.tsx
  src/plugins/data/public/query/query_string/query_history.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/query_editor/_language_selector.scss
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: failed changeset

#7887 fix: broken dql doc link
  src/plugins/data/public/query/query_string/language_service/get_query_control_links.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0, discover-next

#7894 add tests for query assist extension and data structures utils
  src/plugins/data/public/query/query_string/dataset_service/lib/utils.test.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7870 [discover] registered languages interceptor clean up and aggs
  changelogs/fragments/7870.yml
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/datasets/s3_handler.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.ts
Labels: backport 2.x, discover, distinguished-contributor, v2.17.0, discover-next

#7898 [discover] update query assist icon
  src/plugins/query_enhancements/public/assets/query_assist_mark.svg
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7896 [discover] Query editor UI clean up
  changelogs/fragments/7896.yml
  src/plugins/data/public/query/query_string/language_service/default_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/get_query_control_links.tsx
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_editor/flyout_containers.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/dedup.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/eval.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/fields.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/head.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/parse.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/rare.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/rename.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/search.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/sort.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/stats.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/syntax.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/top.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/where.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/condition.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/datetime.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/full_text_search.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/math.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/string.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/groups.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/datatypes.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/identifiers.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/overview.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_reference_flyout.tsx
  src/plugins/query_enhancements/public/query_editor/query_language_reference.tsx
  src/plugins/query_enhancements/public/query_editor/sql_reference_flyout.tsx
Labels: backport 2.x, discover, distinguished-contributor, v2.17.0

#7843 [Page Header]consume new breadcrumb components from oui
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header_breadcrumbs.scss
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, look & feel

#7886 [Page Header]Render filter bar in full width with application header
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.scss
  src/core/public/chrome/ui/header/header.tsx
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, look & feel

#7874 [navigation]fix: only show scrollbar when expanded
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
Labels: bug, backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, navigation

#7901 Fix issue when bootstrapping on 2.x
  changelogs/fragments/7901.yml
  src/core/server/config/service/config_store_client/opensearch_config_store.test.ts
  src/core/server/config/service/config_store_client/opensearch_config_store_client.ts
Labels: seasoned-contributor

#7858 [Bug][Workspace]fix: revert new home page ui setting for workspace default route
  changelogs/fragments/7858.yml
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7918 [Discover 2.0] Fixed recent query and Data Selector styles
  packages/osd-stylelint-config/config/global_selectors.json
  src/plugins/data/public/query/query_string/language_service/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/recent_query.tsx
  src/plugins/data/public/query/query_string/query_history.ts
  src/plugins/data/public/ui/dataset_selector/_dataset_configurator.scss
  src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss
  src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, v2.17.0

#7917 [discover] S3 data connection
  changelogs/fragments/7917.yml
  src/plugins/data/common/constants.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/query_enhancements/public/datasets/s3_handler.ts
Labels: backport 2.x, discover, v2.17.0, discover-next

#7902 [Manual backport 2.x] [discover] Query editor UI clean up (#7896)
  changelogs/fragments/7896.yml
  src/plugins/data/public/query/query_string/language_service/default_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/get_query_control_links.tsx
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_editor/flyout_containers.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/dedup.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/eval.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/fields.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/head.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/parse.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/rare.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/rename.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/search.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/sort.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/stats.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/syntax.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/top.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/where.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/condition.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/datetime.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/full_text_search.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/math.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/string.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/groups.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/datatypes.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/identifiers.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/overview.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_reference_flyout.tsx
  src/plugins/query_enhancements/public/query_editor/query_language_reference.tsx
  src/plugins/query_enhancements/public/query_editor/sql_reference_flyout.tsx
Labels: Skip-Changelog, failed changeset

#7900 [Backport 2.x] [discover] registered languages interceptor clean up and aggs (#7870)
  changelogs/fragments/7870.yml
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/datasets/s3_handler.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.ts
Labels: discover, Skip-Changelog, failed changeset, v2.17.0

#7750 [Workspace]Add right sidebar to workspace create form
  changelogs/fragments/7750.yml
  src/plugins/workspace/public/components/workspace_creator/__snapshots__/workspace_faq_panel.test.tsx.snap
  src/plugins/workspace/public/components/workspace_creator/utils.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.scss
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_faq_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_faq_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_form/fields/index.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_enter_details_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7884 [Workspace]Validate features parameter in workspace create and update API
  changelogs/fragments/7884.yml
  src/core/server/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/common/utils.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_ui_settings_wrapper.test.ts
  src/plugins/workspace/server/workspace_client.mock.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.17.0

#7913 [workspace] refine style of workspace list table
  changelogs/fragments/7913.yml
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#7879 [Workspace] Update collaborator input to text field
  changelogs/fragments/7879.yml
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#7857 [Workspace] refactor: workspace initial page
  changelogs/fragments/7857.yml
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7935 Fix Run button position when datepicker is not visible
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7832 [Manual Backport 2.x][VisBuilder-Next] Migrate legacy visualizations to visbuilder by mapping the url (#7529)
  changelogs/fragments/7529.yml
  src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.test.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx
  src/plugins/vis_builder/public/application/utils/breadcrumbs.ts
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts
  src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx
  src/plugins/vis_builder/public/application/utils/state_management/store.ts
  src/plugins/vis_builder/public/application/utils/use/use_can_save.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/visualize/public/application/components/visualize_listing.tsx
  src/plugins/visualize/public/application/utils/construct_vis_builder_path.ts
  src/plugins/visualize/public/application/utils/contruct_vis_builder_path.test.ts
  test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
Labels: failed changeset

#7929 fix(discover): add data source management link in data selector
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7932 [Auto Suggest] PPL autocomplete and interface changes
  .gitignore
  changelogs/fragments/7758.yml
  changelogs/fragments/7810.yml
  package.json
  packages/osd-monaco/src/xjson/lexer_rules/index.ts
  packages/osd-monaco/src/xjson/lexer_rules/opensearchppl.ts
  packages/osd-monaco/src/xjson/lexer_rules/opensearchsql.ts
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.tokens
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.tokens
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLLexer.g4
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLParser.g4
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/antlr/shared/general_error_listerner.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, valued-contributor, v2.17.0
