Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-01, with the labels that each got.

#5634 Move @seanneumann to emeritus maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.3, backport 2.x, distinguished-contributor

#5315 Replace OuiSelect component with OuiSuperSelect in data-source plugin
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, valued-contributor, v2.12.0

#5637 Bump OUI to 1.4.0
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5669 [CVE-2023-26159] Bump follow-redirects from 1.15.2 to 1.15.4
  CHANGELOG.md
  package.json
  yarn.lock
Labels: seasoned-contributor

#5668 Remove duplicate sample data as id 90943e30-9a47-11e8-b64d-95841ca0b2…
  CHANGELOG.md
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
Labels: backport 2.x, first-time-contributor, v2.12.0

#5592 [Discover] Add long numerals support
  .eslintignore
  CHANGELOG.md
  package.json
  packages/osd-std/src/json.ts
  packages/osd-ui-shared-deps/package.json
  scripts/postinstall.js
  src/core/public/http/fetch.test.ts
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
  src/core/public/ui_settings/__snapshots__/ui_settings_client.test.ts.snap
  src/core/public/ui_settings/ui_settings_client.test.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/server/http/router/response.ts
  src/core/server/http/router/response_adapter.ts
  src/plugins/console/public/lib/opensearch/opensearch.ts
  src/plugins/data/common/field_formats/content_types/html_content_type.ts
  src/plugins/data/common/field_formats/converters/color.test.ts
  src/plugins/data/common/field_formats/converters/numeral.ts
  src/plugins/data/common/field_formats/converters/source.test.ts
  src/plugins/data/common/field_formats/converters/url.test.ts
  src/plugins/data/common/field_formats/field_format.test.ts
  src/plugins/data/common/index_patterns/index_patterns/format_hit.ts
  src/plugins/data/common/opensearch_query/filters/range_filter.test.ts
  src/plugins/data/common/opensearch_query/filters/range_filter.ts
  src/plugins/data/common/opensearch_query/kuery/ast/_generated_/kuery.js
  src/plugins/data/common/opensearch_query/kuery/ast/ast.test.ts
  src/plugins/data/common/opensearch_query/kuery/ast/kuery.peg
  src/plugins/data/common/search/opensearch_search/types.ts
  src/plugins/data/common/search/search_source/parse_json.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/common/search/types.ts
  src/plugins/data/public/search/search_interceptor.test.ts
  src/plugins/data/public/search/search_interceptor.ts
  src/plugins/data/public/ui/filter_bar/filter_bar.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/lib/filter_label.tsx
  src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx
  src/plugins/data/server/search/opensearch_search/decide_client.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
  src/plugins/data/server/search/routes/search.ts
  src/plugins/data/server/search/search_service.ts
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/doc/use_opensearch_doc_search.ts
  src/plugins/discover/public/application/components/json_code_block/json_code_block.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/inspector/public/views/requests/components/details/req_details_request.tsx
  src/plugins/inspector/public/views/requests/components/details/req_details_response.tsx
  src/plugins/saved_objects/public/saved_object/helpers/apply_opensearch_resp.ts
  src/plugins/saved_objects/public/saved_object/helpers/serialize_saved_object.ts
  src/plugins/vis_type_timeline/common/_generated_/chain.js
  src/plugins/vis_type_timeline/public/components/timeline_expression_input_helpers.ts
  tasks/config/peg.js
  tasks/config/run.js
  tasks/function_test_groups.js
  yarn.lock
Labels: backport 2.x, distinguished-contributor

#5660 Chore (deps): remove ui-select angular dev dep
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5662 Chore (ui-shared-deps): Clean up direct usage of OUI theme JSON
  CHANGELOG.md
  src/plugins/expressions/public/react_expression_renderer.tsx
  src/plugins/index_pattern_management/public/components/create_button/create_button.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts
  src/plugins/vis_type_vislib/public/vislib/components/tooltip/tooltip.js
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5610 [Discover] Data Grid Pagination Options
  CHANGELOG.md
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/utils/page_size_options.test.ts
  src/plugins/discover/public/application/components/utils/page_size_options.ts
  src/plugins/discover/public/application/components/utils/use_pagination.test.ts
  src/plugins/discover/public/application/components/utils/use_pagination.ts
Labels: backport 2.x, discover, first-time-contributor, v2.12.0

#5663 Fix Datasource testing connection don't validate endpoints with path
  CHANGELOG.md
  src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
Labels: backport 2.x, first-time-contributor, v2.12.0

#5719 [Datasource selector] Sort datasource option list alphabetically
  CHANGELOG.md
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
Labels: backport 2.x, first-time-contributor, v2.12.0, backport 2.11

#5736 [Security] Updates dev guide for security
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  src/cli/serve/serve.js
Labels: backport 2.x, distinguished-contributor

#5733 [Discover] Fix 0 filters applied state
  CHANGELOG.md
  src/plugins/discover/public/application/components/sidebar/discover_field_search.test.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
Labels: backport 2.x, discover, distinguished-contributor, v2.12.0, backport 2.11

#5749 [2.11] Update caniuse to `1.0.30001580`
  yarn.lock
Labels: Skip-Changelog, 2.11.2

#5758 Initial UI fixes for discover
  packages/osd-stylelint-config/config/global_selectors.json
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/no_view.tsx
  src/plugins/data_explorer/public/components/sidebar/index.scss
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.scss
  src/plugins/data_explorer/public/index.ts
  src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/_doc_table.scss
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/_table_header.scss
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field.scss
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
Labels: distinguished-contributor

#5756 Add datasource picker component and use it in devtools and tutorial page when multiple datasource is enabled
  CHANGELOG.md
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/data_source_picker/data_source_picker.js
  src/plugins/dev_tools/public/application.tsx
  src/plugins/home/public/application/components/tutorial_directory.js
Labels: backport 2.x, multiple datasource, first-time-contributor, v2.12.0

#5760 Table optimization with lazy loading
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
Labels: distinguished-contributor

#5761 [Discover with Legacy Table] fix copy issue and open feedbacks in a new tab
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/top_nav/table_feedbacks_panel.tsx
Labels: distinguished-contributor

#5764 [Discover] Fix more UI
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/data_sources/datasource_selector/types.ts
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: distinguished-contributor

#5763 [Discover] Fixes table optimization
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
Labels: distinguished-contributor
