Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-09, with the labels that each got.

#7839 [Workspace] Enable direct query connections to support in workspace
  changelogs/fragments/7839.yml
  src/plugins/data_source_management/public/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/common/types.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/assets/prometheus_logo.svg
  src/plugins/workspace/public/assets/s3_logo.svg
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.scss
  src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.test.tsx
  src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/direct_query_connection_icon.tsx
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7922 Fix dynamicConfigService mock import
  src/core/server/config/index.ts
  src/core/server/config/mocks.ts
  src/core/server/config/service/config_store_client/dummy_config_store_client.test.ts
  src/core/server/config/service/config_store_client/dummy_config_store_client.ts
  src/core/server/config/service/configuration_client.mock.ts
  src/core/server/config/utils/utils.ts
  src/core/server/mocks.ts
  src/plugins/data_source/server/routes/fetch_data_source_metadata.test.ts
  src/plugins/data_source/server/routes/test_connection.test.ts
  src/plugins/usage_collection/server/routes/integration_tests/stats.test.ts
  src/plugins/workspace/server/integration_tests/duplicate.test.ts
Labels: backport 2.x, seasoned-contributor, v2.17.0

#7916 refactor: update header description for data source management when in workspace
  changelogs/fragments/7916.yml
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/__snapshots__/acceleration_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_table.test.tsx
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/types.ts
Labels: all-star-contributor

#7954 [Workspace]Fix dynamicConfigServiceMock import path in workspace routes UT
  changelogs/fragments/7954.yml
  src/plugins/workspace/server/routes/index.test.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7933 [Workspace]Redirect to use case landing page after workspace create
  changelogs/fragments/7933.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7910 refactor: Update page header for edit object page
  changelogs/fragments/7910.yml
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/object_view/components/header.test.tsx
  src/plugins/saved_objects_management/public/management_section/object_view/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/object_view/saved_object_view.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_edition_page.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7877 [Workspace] search use case overview page
  changelogs/fragments/7877.yml
  src/plugins/content_management/public/components/card_container/card_list.test.tsx
  src/plugins/content_management/public/components/card_container/card_list.tsx
  src/plugins/content_management/public/components/card_container/types.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/home/public/application/application.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.test.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_app.test.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_app.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.test.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.tsx
  src/plugins/home/public/application/index.ts
  src/plugins/home/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, v2.17.0

#7920 [Workspace] Refactor get start card at new home page
  changelogs/fragments/7920.yml
  src/plugins/content_management/public/components/card_container/card_embeddable.tsx
  src/plugins/content_management/public/components/card_container/types.ts
  src/plugins/content_management/public/components/section_input.ts
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/workspace/public/components/home_get_start_card/index.ts
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7805 [Workspace] Refactor the style of recent items card in the header
  changelogs/fragments/7805.yml
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/recent_items.test.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, repeat-contributor, v2.17.0, navigation

#7859 refactor: add workspace info in index pattern and asset header and update workspace header
  changelogs/fragments/7859.yml
  src/plugins/index_pattern_management/public/components/breadcrumbs.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/empty_index_pattern_prompt/empty_index_pattern_prompt.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/index_pattern_management/public/types.ts
  src/plugins/management/public/components/feature_cards/__snapshots__/feature_cards.test.tsx.snap
  src/plugins/management/public/components/feature_cards/feature_cards.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7973 [Page header]Make header bottom border line only render for application header
  src/core/public/chrome/ui/header/header.scss
Labels: bug, backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, look & feel

#7948 Discover Bug Fixes
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/query_enhancements/server/utils/facet.ts
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7926 fix(discover): disable cache only on `indexPatterns.get` to prevent crash
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7924 fix(discover): switch language based on dataset selection
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0

#7943 [discover] async query and caching
  changelogs/fragments/7943.yml
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.test.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts
  src/plugins/data/public/query/query_string/index.ts
  src/plugins/data/public/query/query_string/language_service/index.ts
  src/plugins/data/public/query/query_string/language_service/language_service.mock.ts
  src/plugins/data/public/query/query_string/language_service/language_service.test.ts
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/language_service/lib/_index.scss
  src/plugins/data/public/query/query_string/language_service/lib/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/lib/default_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/lib/get_query_control_links.tsx
  src/plugins/data/public/query/query_string/language_service/lib/index.ts
  src/plugins/data/public/query/query_string/language_service/lib/recent_query.tsx
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/query/types.ts
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/query_enhancements/README.md
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/datasets/index.ts
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
  src/plugins/query_enhancements/server/utils/facet.ts
Labels: backport 2.x, discover, distinguished-contributor, v2.17.0, discover-next

#7979 [backport 2.x] [discover] async query and caching (#7943)
  changelogs/fragments/7943.yml
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.test.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts
  src/plugins/data/public/query/query_string/index.ts
  src/plugins/data/public/query/query_string/language_service/index.ts
  src/plugins/data/public/query/query_string/language_service/language_service.mock.ts
  src/plugins/data/public/query/query_string/language_service/language_service.test.ts
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/language_service/lib/_index.scss
  src/plugins/data/public/query/query_string/language_service/lib/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/lib/default_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/lib/get_query_control_links.tsx
  src/plugins/data/public/query/query_string/language_service/lib/index.ts
  src/plugins/data/public/query/query_string/language_service/lib/recent_query.tsx
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/query/types.ts
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/query_enhancements/README.md
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/datasets/index.ts
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
  src/plugins/query_enhancements/server/utils/facet.ts
Labels: discover, failed changeset, v2.17.0

#7981 [discover][bug] configurator dataset issue
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.test.ts
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, v2.17.0, discover-next

#7984 [Manual][Backport 2.x] Backport 7884 and 7954 to 2.x
  changelogs/fragments/7884.yml
  changelogs/fragments/7954.yml
  src/core/server/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/common/utils.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_ui_settings_wrapper.test.ts
  src/plugins/workspace/server/workspace_client.mock.ts
Labels: failed changeset

#7986 [Bug] [Workspace]Fix workspace detail classname definition
  changelogs/fragments/7986.yml
  src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.scss
  src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.tsx
Labels: all-star-contributor

#7823 [navigation] Add workspace icon to left nav / workspace picker menu / home page.
  changelogs/fragments/7823.yml
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/plugins/content_management/public/mocks.ts
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.scss
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.scss
  src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, workspace, v2.17.0, navigation

#7969 [New]feat: add related connections and nested view to datasource table.
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/direct_query_table.scss
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, Skip-Changelog, repeat-contributor

#7925 Add Data connection saved-object type for external connections
  changelogs/fragments/7925.yml
  src/plugins/data_source/common/data_connections/data_connection_saved_object_attributes.ts
  src/plugins/data_source/common/data_connections/index.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/data_connection.ts
  src/plugins/data_source/server/saved_objects/index.ts
Labels: backport 2.x, first-time-contributor, v2.17.0

#7997 [discover] pass connection title correctly and set session id
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/server/utils/facet.ts
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, v2.17.0, discover-next

#7987 [Workspace] Hide delete button for non OSD admin
  changelogs/fragments/7987.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#7989 [Workspace]Hide saved object import button when user is outside workspace
  changelogs/fragments/7989.yml
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7992 [Workspace] Hide first home breadcrumbs within workspace
  changelogs/fragments/7992.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0

#7967 [Workspace] add use case cards when workspace is disabled, refine the style of recent_work in the home page.
  src/core/utils/default_nav_groups.ts
  src/plugins/home/public/application/components/use_case_card.test.ts
  src/plugins/home/public/application/components/use_case_card.ts
  src/plugins/home/public/application/home_render.test.tsx
  src/plugins/home/public/application/home_render.tsx
  src/plugins/saved_objects_management/public/management_section/recent_work.tsx
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
Labels: backport 2.x, valued-contributor, workspace, v2.17.0

#7881 [Workspace] Content menu picker in side bar and enable searching
  changelogs/fragments/7881.yml
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#8021 Fix 2.x issue
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
Labels: failed changeset

#7959 [Data Source]Add data source permission wrapper and dataSourceAdmin role
  changelogs/fragments/7959.yml
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/utils/auth_info.test.ts
  src/core/server/utils/auth_info.ts
  src/core/server/utils/index.ts
  src/core/server/utils/workspace.test.ts
  src/core/server/utils/workspace.ts
  src/plugins/data_source_management/common/index.ts
  src/plugins/data_source_management/config.ts
  src/plugins/data_source_management/server/plugin.ts
  src/plugins/data_source_management/server/saved_objects/data_source_permission_client_wrapper.test.ts
  src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
  src/plugins/workspace/server/permission_control/client.test.ts
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.17.0

#7961 [Workspace] Refactor 'Associate data sources' in create page to support direct query connections
  changelogs/fragments/7961.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.scss
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, repeat-contributor, workspace, v2.17.0

#8027 [discover] undefined datasource fix for index patterns for PPL and SQL
  src/plugins/query_enhancements/server/utils/facet.test.ts
  src/plugins/query_enhancements/server/utils/facet.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, discover-next, backport 2.17

#7930 [Fix] Show Alias Fields in Discover Tab
  changelogs/fragments/7930.yml
  src/plugins/data/common/constants.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/server/ui_settings.ts
Labels: backport 2.x, discover, valued-contributor, v2.17.0, backport 2.17

#8025 add Huy as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/8025.yml
Labels: docs, backport 2.x, all-star-contributor

#8026 Bump `micromatch` from 4.0.7 to 4.0.8
  changelogs/fragments/8026.yml
  yarn.lock
Labels: backport 2.x, distinguished-contributor, backport 2.17

#8043 [Workspace]Deny get or bulkGet for global data source
  changelogs/fragments/8043.yml
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0, backport 2.17

#7991 [Auto Suggest] Look and Feel changes
  changelogs/fragments/7991.yml
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx
Labels: backport 2.x, discover, valued-contributor, v2.17.0, backport 2.17

#8059 display direct query connections of local cluster in data sources page
  src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_page_header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/constants.ts
Labels: backport 2.x, Skip-Changelog, repeat-contributor, backport 2.17

#8068 [Manual backport 2.17]display direct query connections of local cluster in data sources page (#8059)
  src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_page_header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.test.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/constants.ts
Labels: failed changeset

#8045 fix: order of query editor extensions not working
  changelogs/fragments/8045.yml
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
  src/plugins/query_enhancements/public/query_assist/_index.scss
Labels: backport 2.x, discover, all-star-contributor, v2.17.0, backport 2.17

#8080 Mark user personal settings as experimental
  changelogs/fragments/7953.yml
  src/core/server/ui_settings/create_or_upgrade_saved_config/create_or_upgrade_saved_config.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/utils.ts
  src/core/types/ui_settings.ts
  src/plugins/advanced_settings/server/saved_objects/user_ui_settings_client_wrapper.ts
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: Skip-Changelog, all-star-contributor

#8079 [Workspace]Fix workspace description error when name invalid
  changelogs/fragments/8079.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
Labels: bug, backport 2.x, all-star-contributor, workspace, v2.17.0, backport 2.17

#8070 [discover] Update S3 Connections logo in Dataset Selector
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: backport 2.x, discover, Skip-Changelog, first-time-contributor, v2.17.0, discover-next, backport 2.17

#8064 Fix header look and feel changes
  src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/embeddable/empty/dashboard_empty_screen.scss
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/visualize/public/application/components/visualize_listing.tsx
  src/plugins/visualize/public/application/components/visualize_top_nav.tsx
Labels: backport 2.x, v2.17.0, backport 2.17

#8076 [navigation]feat: add `sample data` menu back
  changelogs/fragments/8076.yml
  docs/_sidebar.md
  src/core/server/utils/auth_info.ts
  src/plugins/home/common/constants.ts
  src/plugins/home/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: backport 2.x, v2.17.0, navigation, backport 2.17

#7962 [navigation]feat: fix left nav in small screen
  changelogs/fragments/7962.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header.scss
  src/core/public/chrome/ui/header/header.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0, navigation, backport 2.17

#8033 Readjust space between the search bar and the actions
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/navigation/public/top_nav_menu/_index.scss
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.17.0, backport 2.17

#8098 [navigation]feat: add `sample data` menu back (#8076)
  changelogs/fragments/8076.yml
  src/core/server/utils/auth_info.ts
  src/plugins/home/common/constants.ts
  src/plugins/home/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: backport 2.x

#8071 Manually Adding CHANGELOG.md Changes
  CHANGELOG.md
Labels: Skip-Changelog

#8085 fix: it should not create multiple query editor extension container
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
Labels: backport 2.x, Skip-Changelog, all-star-contributor, discover-next, backport 2.17

#8086 [Bug][Workspace]Fix page display errors and add loading status
  changelogs/fragments/8086.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.17.0, backport 2.17

#8102 Bump browserslist to prevent integration test errors
  package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, backport 2.17

#8060 Fix row rendering in infinite scroll
  changelogs/fragments/8060.yml
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.test.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
Labels: backport 2.x, discover, repeat-contributor, v2.17.0, discover-next, backport 2.17

#8121 [Discover] Fix refresh on index
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
Labels: backport 2.x, discover, v2.17.0, backport 2.17

#7999 Filter Saved Search Based on AppName Supported by Language
  src/plugins/dashboard/public/application/utils/create_dashboard_container.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/discover/public/embeddable/search_embeddable_factory.tsx
  src/plugins/embeddable/public/plugin.tsx
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/saved_objects/public/finder/saved_object_finder.tsx
  src/plugins/visualizations/public/plugin.ts
  src/plugins/visualizations/public/services.ts
  src/plugins/visualizations/public/wizard/new_vis_modal.tsx
  src/plugins/visualizations/public/wizard/search_selection/search_selection.tsx
  src/plugins/visualizations/public/wizard/show_new_vis.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, v2.17.0, backport 2.17

#8118 fix: data source permission client wrapper error of not returning explicitly the saved object client functions
  changelogs/fragments/8118.yml
  src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
Labels: backport 2.x, multiple datasource, all-star-contributor, v2.17.0, backport 2.17

#8128 [Manual backport] [Backport 2.17] data source permission client wrapper error of not returning explicitly the saved object client functions
  changelogs/fragments/8118.yml
  src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
Labels: multiple datasource, failed changeset, v2.17.0

#8127 [Manual backport] [Backport 2.x] data source permission client wrapper error of not returning explicitly the saved object client functions
  changelogs/fragments/8118.yml
  src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
Labels: multiple datasource, failed changeset, v2.17.0

#8113 Extended Dataset type config to provide search options like strategy
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Labels: backport 2.x, discover, repeat-contributor, failed changeset, v2.17.0

#8100 Remove unsupported languages for dataset
  changelogs/fragments/8100.yml
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/types.ts
Labels: backport 2.x, discover, distinguished-contributor, v2.17.0

#8108 Correct the size of disabled ValidatedDualRange components in InputControl visualizations
  changelogs/fragments/8108.yml
  src/plugins/input_control_vis/public/components/vis/__snapshots__/range_control.test.tsx.snap
  src/plugins/input_control_vis/public/components/vis/range_control.tsx
Labels: backport 2.x, distinguished-contributor, v2.17.0, backport 2.17

#8143 [discover ]Adjust icon size to fix spacing in action table
  src/plugins/discover/public/application/components/table/table_row_btn_filter_add.tsx
  src/plugins/discover/public/application/components/table/table_row_btn_filter_exists.tsx
  src/plugins/discover/public/application/components/table/table_row_btn_filter_remove.tsx
  src/plugins/discover/public/application/components/table/table_row_btn_toggle_column.tsx
Labels: backport 2.x, Skip-Changelog, repeat-contributor, v2.18.0

#8151 [Workspace][Navigation] fix: hide workspace detail title in old nav
  changelogs/fragments/8151.yml
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace

#8152 Allow unknown query parameter for ui settings route
  src/core/server/ui_settings/routes/delete.ts
  src/core/server/ui_settings/routes/get.ts
  src/core/server/ui_settings/routes/set.ts
  src/core/server/ui_settings/routes/set_many.ts
Labels: backport 2.x, Skip-Changelog, all-star-contributor, v2.17.0, backport 2.17

#8167 Fix Discover Embeddable not showing _source when all other column are removed
  changelogs/fragments/8167.yml
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
Labels: backport 2.x, discover, seasoned-contributor, v2.17.0, backport 2.17

#8087 [Auto Suggest] PPL autocomplete fixes
  changelogs/fragments/8087.yml
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLParser.g4
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, valued-contributor, v2.18.0

#8176 fix path-to-regex cve
  changelogs/fragments/8176.yml
  package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, backport 2.17

#8179 [Manual backport 2.17] Sync query and filter when refreshing discover page
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: autocut, failed changeset

#8168 Sync query and filter when refreshing discover page
  changelogs/fragments/8168.yml
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, discover, v2.17.0

#8184 [Dynamic Config] Fix bug when attempting dynamic config index creation
  changelogs/fragments/8184.yml
  src/core/server/config/service/config_store_client/opensearch_config_store.test.ts
  src/core/server/config/service/config_store_client/opensearch_config_store_client.ts
  src/core/server/config/utils/utils.test.ts
  src/core/server/config/utils/utils.ts
Labels: backport 2.x, seasoned-contributor, backport 2.17

#7178 fix(discover): truncate height of table cell
  changelogs/fragments/7178.yml
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
Labels: backport 2.x, valued-contributor, v2.18.0

#8198 [Manual backport 2.17] [CVE-2024-45296] Bump path-to-regexp to 1.9.0, 3.3.0, and 6.3.0 #8197
  changelogs/fragments/8176.yml
  package.json
  yarn.lock
Labels: Skip-Changelog, v2.17.0

#8200 [Workspace] feat: update workspace server to support data connection type
  changelogs/fragments/8200.yml
  src/plugins/data_source/common/index.ts
  src/plugins/data_source/opensearch_dashboards.json
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/common/types.ts
  src/plugins/workspace/common/utils.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor, v2.18.0

#8197 [CVE-2024-45296] Bump path-to-regexp to 1.9.0, 3.3.0, and 6.3.0
  changelogs/fragments/8176.yml
  changelogs/fragments/8197.yml
  package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.17.0

#7891 [Look&Feel] Updated Discover No Results panel
  changelogs/fragments/7891.yml
  src/plugins/discover/public/application/components/no_results/no_results.tsx
Labels: backport 2.x, seasoned-contributor, look & feel, 2.17.1

#8209 Fix data-connection objects title in saved-objects page
  src/plugins/data_source/common/data_connections/data_connection_saved_object_attributes.ts
  src/plugins/data_source/server/saved_objects/data_connection.ts
Labels: repeat-contributor

#8188 [Workspace]Fix workspace detail UI bugs
  changelogs/fragments/8188.yml
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_panel.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8213 [Workspace]Add tooltip in workspace settings top delete button
  changelogs/fragments/8213.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8187 Use local clusterState call during healthchecks
  changelogs/fragments/8187.yml
  src/core/server/opensearch/version_check/ensure_opensearch_version.ts
Labels: first-time-contributor

#8225 Post 2.17 to bump version to next
  changelogs/fragments/8225.yml
  package.json
Labels: seasoned-contributor

#8223 fix: fix overlay offsets on pages with feature header
  changelogs/fragments/8223.yml
  src/core/public/chrome/ui/header/header.scss
Labels: backport 2.x, valued-contributor, backport 2.17, 2.17.1

#8171 [Page Header] Add responsiveness for page header
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.scss
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
Labels: backport 2.x, Skip-Changelog, look & feel, backport 2.17, 2.17.1

#8144 [Manual backport 2.x] Bump browserslist to prevent integration test errors (#8102)
  package.json
  yarn.lock
Labels: Skip-Changelog, v2.18.0

#8218 [navigation] Remove nav group for dev tools
  changelogs/fragments/8218.yml
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
Labels: backport 2.x, all-star-contributor, navigation, 2.17.1

#8199 [Bug] Fix ppl commands
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Labels: first-time-contributor, failed changeset

#8246 chore: Update oui to 1.13
  changelogs/fragments/8246.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, valued-contributor, look & feel, backport 2.17, 2.17.1

#8232 Use @osd/std to prettify objects for display
  changelogs/fragments/8232.yml
  src/plugins/data/common/field_formats/utils/as_pretty_string.test.ts
  src/plugins/data/common/field_formats/utils/as_pretty_string.ts
Labels: backport 2.x, distinguished-contributor, backport 2.17, 2.17.1

#8233 Set Legacy Discover Table as Default for Discover 2.0 Experience
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
Labels: backport 2.x, discover, Skip-Changelog, all-star-contributor, v2.18.0

#8236 [Workspace] Drop user personal settings page
  changelogs/fragments/8236.yml
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/server/plugin.ts
Labels: all-star-contributor, workspace, 2.17.1

#8186 Add data summary panel in discover
  changelogs/fragments/8186.yml
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/public/search/search_service.ts
  src/plugins/data/public/search/types.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/query_enhancements/common/config.ts
  src/plugins/query_enhancements/common/query_assist/index.ts
  src/plugins/query_enhancements/common/query_assist/types.ts
  src/plugins/query_enhancements/opensearch_dashboards.json
  src/plugins/query_enhancements/public/assets/sparkle_hollow.svg
  src/plugins/query_enhancements/public/assets/sparkle_mark.svg
  src/plugins/query_enhancements/public/assets/sparkle_solid.svg
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/_index.scss
  src/plugins/query_enhancements/public/query_assist/components/index.ts
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_button.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_button.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/hooks/index.ts
  src/plugins/query_enhancements/public/query_assist/hooks/use_query_assist.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/public/types.ts
Labels: backport 2.x, discover, repeat-contributor, failed changeset

#8215 [Bug] Fix: use workspace type icons and compressed input
  changelogs/fragments/8215.yml
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8013 [Workspace] Integrate workspace front end with data connection type saved object
  changelogs/fragments/8013.yml
  src/plugins/data_source/common/index.ts
  src/plugins/workspace/common/types.ts
  src/plugins/workspace/public/assets/cloudwatch_logo.svg
  src/plugins/workspace/public/assets/security_lake_logo.svg
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/__snapshots__/connection_type_icon.test.tsx.snap
  src/plugins/workspace/public/components/workspace_form/connection_type_icon.test.tsx
  src/plugins/workspace/public/components/workspace_form/connection_type_icon.tsx
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/direct_query_connection_icon.tsx
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8217 [Bug] Fix initial page UI issues
  changelogs/fragments/8217.yml
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8274 Temporary fix for a bug with Chrome 129 when handling mask-image
  changelogs/fragments/8274.yml
  src/core/public/styles/_base.scss
Labels: backport 2.x, distinguished-contributor, backport 2.17, 2.17.1

#8226 [discover] Clean up enhanced search API
  changelogs/fragments/8226.yml
  src/plugins/data/common/constants.ts
  src/plugins/data/common/search/search_source/fetch/get_search_params.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/services/connections_service.ts
  src/plugins/query_enhancements/public/services/index.ts
  src/plugins/query_enhancements/public/types.ts
  src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
  src/plugins/query_enhancements/server/routes/index.ts
Labels: backport 2.x, discover, distinguished-contributor, discover-next, backport 2.17, 2.17.1

#8252 Fix running recent query button
  changelogs/fragments/8252.yml
  src/plugins/data/public/query/query_string/language_service/lib/recent_query.tsx
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/query/query_string/query_history.ts
Labels: distinguished-contributor

#8282 [Backport 2.x] Expose method to register search strategy routes in query enhancement
  changelogs/fragments/8245.yml
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/types.ts
Labels: failed changeset

#8245 Expose method to register search strategy routes in query enhancement
  changelogs/fragments/8245.yml
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/types.ts
Labels: backport 2.x, discover, repeat-contributor, backport 2.17, 2.17.1

#8299 Expose datasets and data_frames directories for specific imports
  changelogs/fragments/8299.yml
  src/plugins/data/opensearch_dashboards.json
Labels: backport 2.x, discover, repeat-contributor, backport 2.17, 2.17.1

#8308 remove unnecessary multiple data source doc link
  docs/multi-datasource/high_level_design.md
Labels: backport 2.x, Skip-Changelog, all-star-contributor, v2.18.0

#8309 chore: Exclude https://sites.google.com/site/murmurhash from link check
  .lycheeignore
Labels: backport 2.x, Skip-Changelog, all-star-contributor, v2.18.0

#8235 test(usage_collection): expose a function to mock plugin start
  src/plugins/usage_collection/public/mocks.ts
Labels: backport 2.x, Skip-Changelog, all-star-contributor

#8289 [navigation]fix: add xxl and xxxl for left nav responsiveness
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/header.tsx
Labels: bug, backport 2.x, Skip-Changelog, OUI, navigation, 2.17.1

#8305 Increment version to 2.17.1
  package.json
Labels: failed changeset

#8189 [navigation]fix: optimize the logic to detect current nav group
  changelogs/fragments/8189.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
Labels: backport 2.x, distinguished-contributor, navigation, 2.17.1

#8292 [Page Header]Add responsiveness for application header
  src/core/public/chrome/ui/header/header.scss
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: backport 2.x, distinguished-contributor, failed changeset, look & feel, 2.17.1

#8320 fix: update osd to respect new oui breakpoints
  changelogs/fragments/8320.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/home/public/application/components/_solutions_section.scss
  src/plugins/opensearch_dashboards_overview/public/components/_overview.scss
  src/plugins/vis_default_editor/public/_default.scss
  src/plugins/vis_default_editor/public/_sidebar.scss
Labels: backport 2.x, valued-contributor

#8263 [Manual backport 2.x][Workspace] Drop user personal settings page (#8236)
  changelogs/fragments/8236.yml
  src/plugins/advanced_settings/public/plugin.ts
  src/plugins/advanced_settings/server/plugin.ts
Labels: failed changeset

#8227 Change page title of application headers to h1 and xs
  changelogs/fragments/8227.yml
  src/plugins/navigation/public/top_nav_menu/_index.scss
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: backport 2.x, distinguished-contributor, backport 2.17, 2.17.1

#8222 Update data explorer ui to use compressed components
  changelogs/fragments/8222.yml
  src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
Labels: backport 2.x, discover, repeat-contributor, backport 2.17, 2.17.1

#8346 [CVE-2024-45801] Bump `dompurify` from 3.0.11 to 3.1.6
  changelogs/fragments/8346.yml
  yarn.lock
Labels: backport 2.x, distinguished-contributor, backport 2.17, 2.17.1

#8329 [Page Header]Fix responsiveness issue for dashboards & visualization app headers
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, look & feel, backport 2.17, v2.18.0

#8334 refactor: move the render of query extension control buttons to extension component
  changelogs/fragments/8334.yml
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_button.tsx
Labels: backport 2.x, all-star-contributor, discover-next

#8351 Refactor branch deletion workflow for backport branches
  .github/workflows/delete_backport_branch.yml
Labels: backport 2.x, repeat-contributor, failed changeset

#8359 [Manual backport 2.x][Page Header]Fix responsiveness for dashboards & visualization app headers (#8329)
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
Labels: Skip-Changelog, 2.17.1

#8347 [discover] fix too many queries sent
  changelogs/fragments/8347.yml
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/ui/dataset_selector/dataset_selector.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/discover/public/application/view_components/utils/update_search_source.ts
Labels: backport 2.x, discover, distinguished-contributor, discover-next, v2.18.0

#8331 fix discover input background not shrink
  changelogs/fragments/8331.yml
  src/plugins/data/public/ui/query_editor/_query_editor.scss
Labels: backport 2.x, discover, discover-next, v2.18.0

#8335 Fix HeaderControl not rendered if not mount in initial rendering
  changelogs/fragments/8335.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/utils/index.ts
  src/core/public/utils/use_observable_value.test.ts
  src/core/public/utils/use_observable_value.ts
Labels: backport 2.x, all-star-contributor, v2.18.0

#8369 Add release notes for 2.17.1
  CHANGELOG.md
  changelogs/fragments/8274.yml
  changelogs/fragments/8346.yml
  docs/_sidebar.md
  release-notes/opensearch-dashboards.release-notes-2.17.1.md
Labels: backport 2.x, distinguished-contributor, backport 2.17, 2.17.1

#8370 [Manual backport 2.17] Add release notes for 2.17.1
  CHANGELOG.md
  changelogs/fragments/8274.yml
  changelogs/fragments/8346.yml
  release-notes/opensearch-dashboards.release-notes-2.17.1.md
Labels: failed changeset

#8153 [Workspace]Disable "Save changes" button on character limit exceeded
  changelogs/fragments/8153.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8315 [Worksapce] Hide delete button for non osd admins in workspace list
  changelogs/fragments/8315.yml
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, valued-contributor, workspace

#8291 Update sample data page UI when useUpdatedUX enabled
  changelogs/fragments/8291.yml
  src/plugins/home/opensearch_dashboards.json
  src/plugins/home/public/application/application.tsx
  src/plugins/home/public/application/components/sample_data_set_cards.js
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/home/public/application/components/tutorial_directory.test.tsx
  src/plugins/home/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace

#8265 [Workspace]Fix workspace assets page UI bugs
  changelogs/fragments/8265.yml
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_modal.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_mode_control.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_summary.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace

#8375 [Workspace]Update details panel UI in workspace create page
  changelogs/fragments/8375.yml
  src/plugins/workspace/public/components/workspace_creator/creator_details_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_form/fields/workspace_name_field.tsx
Labels: all-star-contributor

#8216 Add tooltips for sidebar icon buttons
  changelogs/fragments/8216.yml
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/home/public/application/components/home_icon.test.tsx
  src/plugins/home/public/application/components/home_icon.tsx
  src/plugins/management/public/components/settings_icon.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: backport 2.x, valued-contributor, workspace, 2.17.1

#8372 chore: Update oui to 1.14
  changelogs/fragments/8372.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/core/server/core_app/assets/fonts/fira_code/FiraCode-VariableFont_wght.ttf
  src/core/server/core_app/assets/fonts/fira_code/LICENSE.txt
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Bold.ttf
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Bold.woff2
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Light.ttf
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Light.woff2
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Medium.ttf
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Medium.woff2
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Regular.ttf
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-Regular.woff2
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-SemiBold.ttf
  src/core/server/core_app/assets/fonts/fira_code/static/FiraCode-SemiBold.woff2
  src/core/server/core_app/assets/fonts/readme.md
  src/core/server/rendering/views/fonts.tsx
  src/legacy/ui/ui_render/ui_render_mixin.js
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, look & feel, v2.18.0

#8303 [Workspace] fix breadcrumbs for workspace
  .lycheeignore
  changelogs/fragments/8303.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
  src/core/public/chrome/ui/header/header_breadcrumbs.tsx
  src/plugins/content_management/public/constants.ts
  src/plugins/home/public/application/components/usecase_overview/search_use_case_app.test.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_app.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_name/workspace_name.test.tsx
  src/plugins/workspace/public/components/workspace_name/workspace_name.tsx
  src/plugins/workspace/public/components/workspace_use_case_overview_app.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8330 [Workspace] Redirect "Sample data" link to the page in the same workspace
  changelogs/fragments/8330.yml
  src/plugins/dashboard/public/application/utils/get_no_items_message.test.tsx
  src/plugins/dashboard/public/application/utils/get_no_items_message.tsx
Labels: backport 2.x, valued-contributor, workspace

#8139 [Workspace] Fix fit&finish for workspace overview page
  changelogs/fragments/8139.yml
  src/core/public/doc_links/doc_links_service.ts
  src/core/utils/default_nav_groups.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/content_management/public/components/card_container/card_embeddable.tsx
  src/plugins/content_management/public/components/card_container/card_list.test.tsx
  src/plugins/content_management/public/components/card_container/card_list.tsx
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/content_management/public/services/content_management/types.ts
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/home/public/application/components/_index.scss
  src/plugins/home/public/application/components/home_list_card.test.tsx
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.test.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.tsx
  src/plugins/home/public/application/components/usecase_overview/search_overview.scss
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.test.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.tsx
  src/plugins/home/public/application/home_render.test.tsx
  src/plugins/home/public/application/home_render.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/saved_objects_management/public/management_section/recent_work.test.tsx
  src/plugins/saved_objects_management/public/management_section/recent_work.tsx
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/workspace/public/components/use_case_overview/get_started_cards.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx
Labels: backport 2.x, all-star-contributor, workspace, 2.17.1

#8317 [Workspace][Bug]Fix workspace detail page issues
  changelogs/fragments/8317.yml
  src/core/public/application/application_leave.tsx
  src/core/public/application/application_service.tsx
  src/core/public/application/types.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_panel.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: backport 2.x, all-star-contributor, workspace

#8381 [Workspace] Refactor summary panel in workspace create page
  changelogs/fragments/8381.yml
  src/plugins/workspace/public/components/workspace_creator/__snapshots__/workspace_faq_panel.test.tsx.snap
  src/plugins/workspace/public/components/workspace_creator/utils.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.scss
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_faq_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_faq_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8383 [Workspace] Refactor data source association panel
  changelogs/fragments/8383.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
Labels: backport 2.x, valued-contributor, workspace

#8286 [navigation]feat: remember state when expand / collapse left nav
  changelogs/fragments/8286.yml
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
Labels: backport 2.x, distinguished-contributor, navigation, 2.17.1
