Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-03, with the labels that each got.

#5997 [MD]Fix schema for test connection to separate validation based on auth type
  CHANGELOG.md
  src/plugins/data_source/server/routes/test_connection.test.ts
  src/plugins/data_source/server/routes/test_connection.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#5855 Add support for dynamic application configurations
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/mocks.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/legacy/server/config/schema.js
  src/plugins/application_config/README.md
  src/plugins/application_config/common/index.ts
  src/plugins/application_config/config.ts
  src/plugins/application_config/opensearch_dashboards.json
  src/plugins/application_config/server/index.ts
  src/plugins/application_config/server/opensearch_config_client.test.ts
  src/plugins/application_config/server/opensearch_config_client.ts
  src/plugins/application_config/server/plugin.test.ts
  src/plugins/application_config/server/plugin.ts
  src/plugins/application_config/server/routes/index.test.ts
  src/plugins/application_config/server/routes/index.ts
  src/plugins/application_config/server/string_utils.test.ts
  src/plugins/application_config/server/string_utils.ts
  src/plugins/application_config/server/types.ts
Labels: backport 2.x, first-time-contributor, v2.13.0

#5949 [Workspace]Optional workspaces params in repository
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
  src/core/server/saved_objects/import/check_conflicts.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/create.ts
  src/core/server/saved_objects/routes/export.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/resolve_import_errors.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/serialization/serializer.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/saved_objects/types.ts
  src/core/types/saved_objects.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: repeat-contributor, workspace, v2.13.0

#6008 [BUG][Discover] Enable 'Back to Top' Feature in Discover for scrolling to top
  CHANGELOG.md
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: distinguished-contributor

#6010 [CI] Fixes buid and test workflow
  .github/workflows/build_and_test_workflow.yml
Labels: Skip-Changelog, distinguished-contributor

#6012 [Workspace]Following pr for #5949
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: Skip-Changelog, workspace, v2.13.0

#5999 Add release notes for 1.3.15
  release-notes/opensearch-dashboards.release-notes-1.3.15.md
Labels: backport main, Skip-Changelog

#6023 Correct release notes typo
  release-notes/opensearch-dashboards.release-notes-1.3.15.md
Labels: backport main, Skip-Changelog

#6002 [Multi Data Source] Render credential form registered from AuthMethod
  CHANGELOG.md
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
Labels: backport 2.x, multiple datasource, valued-contributor

#5084 [Workspace][Feature] Add ACL related functions
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/server/saved_objects/permission_control/index.ts
  src/core/server/saved_objects/saved_objects_config.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/saved_objects/serialization/serializer.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/types/saved_objects.ts
Labels: first-time-contributor, workspace

#6041 [Discover] Fix lazy loading
  CHANGELOG.md
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
Labels: distinguished-contributor

#6025 Create a migration function for datasource to add migrationVersion field
  CHANGELOG.md
  src/plugins/data_source/server/saved_objects/data_source.test.ts
  src/plugins/data_source/server/saved_objects/data_source.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#6042 [MD] Change cluster selector component name to data source selector
  CHANGELOG.md
  src/plugins/data_source_management/public/components/cluster_selector/create_cluster_selector.tsx
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/create_data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_selector/index.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/index.scss
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#6055 Correct CHANGELOG
  CHANGELOG.md
Labels: Skip-Changelog, maintenance, seasoned-contributor

#6057 [MD] Expose a few properties for customize the appearance of the data source selector component
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/create_data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#6082 [MD] Create data source menu component able to be mount to nav bar
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_menu/index.ts
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: multiple datasource, valued-contributor

#6061 Add functional test cypress workflow improvements and enable the workflow for in-house tests
  .github/workflows/cypress_workflow.yml
  .github/workflows/release_cypress_workflow.yml
  CHANGELOG.md
  cypress/utils/commands.js
  package.json
  scripts/common/opensearch_service.sh
  scripts/cypress_tests.sh
Labels: distinguished-contributor

#6062 Handles auth methods from auth registry in DataSourceSavedObjectsClientWrapper
  CHANGELOG.md
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.13.0

#6049 [Multiple Datasource] Handle form values(request payload) if the selected type is available in the authentication registry.
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.test.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#5975 [MDS] Support Vega Visualizations
  CHANGELOG.md
  src/plugins/vis_type_vega/opensearch_dashboards.json
  src/plugins/vis_type_vega/public/data_model/opensearch_query_parser.ts
  src/plugins/vis_type_vega/public/data_model/search_api.test.ts
  src/plugins/vis_type_vega/public/data_model/search_api.ts
  src/plugins/vis_type_vega/public/data_model/types.ts
  src/plugins/vis_type_vega/public/default.spec.hjson
  src/plugins/vis_type_vega/public/plugin.ts
  src/plugins/vis_type_vega/public/services.ts
  src/plugins/vis_type_vega/public/vega_request_handler.ts
Labels: multiple datasource, first-time-contributor

#6014 [Workspace] Consume workspace id in saved object client
  CHANGELOG.md
  src/core/public/saved_objects/saved_objects_client.test.ts
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/public/saved_objects/saved_objects_service.mock.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.test.ts
  src/core/server/saved_objects/import/resolve_import_errors.test.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor, workspace

#6013 [Workspace] Delete saved objects by workspace
  CHANGELOG.md
  src/core/server/index.ts
  src/core/server/saved_objects/service/lib/repository.mock.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: repeat-contributor, workspace, v2.13.0

#6108 [Multiple Datasource] Export DataSourcePluginRequestContext at top level for plugins to use
  CHANGELOG.md
  src/plugins/data_source/server/index.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.13.0

#5977 [Docs] Creates Developer docs GH page code
  .nojekyll
  CHANGELOG.md
  docs/DOCS_README.md
  docs/_sidebar.md
  docs/index.html
  index.html
  package.json
  scripts/generate_docs_sidebar.js
Labels: distinguished-contributor

#6109 [Multiple Datasource] Test connection schema validation for registered auth types
  CHANGELOG.md
  src/plugins/data_source/server/routes/test_connection.test.ts
  src/plugins/data_source/server/routes/test_connection.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#6094 [Workspace] Add a workspace client in workspace plugin
  CHANGELOG.md
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/workspace_client.mock.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
Labels: valued-contributor, workspace

#6118 [Workspace] Add WorkspacePluginSetup interface
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/types.ts
Labels: Skip-Changelog, valued-contributor, workspace

#6125 [Multiple Datasource] Add component to show single selected data source in read only mode
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/data_source_view/index.ts
Labels: seasoned-contributor

#6021 [CVE-2024-27088] Bump es5-ext from `0.10.59` to `0.10.64`
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cve, backport 2.x, distinguished-contributor, v2.13.0

#6137 Rename cypress config file to its version supported convention
  CHANGELOG.md
  cypress.config.js
  cypress.json
Labels: distinguished-contributor

#6136 Move @kristenTian to emeritus maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.x, backport 2.x, maintenance, valued-contributor

#6060 [Workspace] Add workspace id in basePath
  CHANGELOG.md
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/http/base_path.test.ts
  src/core/public/http/base_path.ts
  src/core/public/http/http_service.mock.ts
  src/core/public/http/http_service.test.ts
  src/core/public/http/http_service.ts
  src/core/public/http/types.ts
  src/core/public/index.ts
  src/core/public/utils/index.ts
  src/core/server/utils/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
Labels: valued-contributor, workspace

#6122 [Multiple DataSource] DataSource creation and edition page improvement to better support registered auth types
  CHANGELOG.md
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.test.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#5920 Add sidecar service
  CHANGELOG.md
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/overlays/index.ts
  src/core/public/overlays/overlay_service.mock.ts
  src/core/public/overlays/overlay_service.ts
  src/core/public/overlays/sidecar/__snapshots__/sidecar_service.test.tsx.snap
  src/core/public/overlays/sidecar/components/__snapshots__/resizable_button.test.tsx.snap
  src/core/public/overlays/sidecar/components/__snapshots__/sidecar.test.tsx.snap
  src/core/public/overlays/sidecar/components/resizable_button.scss
  src/core/public/overlays/sidecar/components/resizable_button.test.tsx
  src/core/public/overlays/sidecar/components/resizable_button.tsx
  src/core/public/overlays/sidecar/components/sidecar.scss
  src/core/public/overlays/sidecar/components/sidecar.test.tsx
  src/core/public/overlays/sidecar/components/sidecar.tsx
  src/core/public/overlays/sidecar/helper.test.ts
  src/core/public/overlays/sidecar/helper.ts
  src/core/public/overlays/sidecar/index.ts
  src/core/public/overlays/sidecar/sidecar_service.mock.ts
  src/core/public/overlays/sidecar/sidecar_service.test.tsx
  src/core/public/overlays/sidecar/sidecar_service.tsx
  src/core/public/public.api.md
  src/core/public/rendering/app_containers.test.tsx
  src/core/public/rendering/app_containers.tsx
  src/core/public/rendering/rendering_service.tsx
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/opensearch_dashboards_react/README.md
  src/plugins/opensearch_dashboards_react/public/overlays/create_react_overlays.test.tsx
  src/plugins/opensearch_dashboards_react/public/overlays/create_react_overlays.tsx
  src/plugins/opensearch_dashboards_react/public/overlays/types.ts
Labels: backport 2.x, first-time-contributor, v2.13.0

#6152 [Multiple Datasource] Fix data source filter bug and add tests
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/utils.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.13.0

#6140 [Manual][Backport 2.x][CVE-2024-27088] Bump es5-ext from `0.10.59` to `0.10.64` (#6021)
  CHANGELOG.md
  package.json
  yarn.lock
Labels: v2.13.0

#6148 Employ a patched version of hoek that addresses CVE-2020-36604
  CHANGELOG.md
  package.json
  yarn.lock
Labels: distinguished-contributor

#6135 Improves connection pooling support for AWSSigV4 clients in data sources.
  CHANGELOG.md
  package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch/package.json
  src/core/server/opensearch/client/configure_client.ts
  src/core/server/opensearch/client/mocks.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source/server/client/configure_client.test.mocks.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
  src/plugins/data_source/server/types.ts
  src/plugins/data_source/server/util/credential_provider.ts
  yarn.lock
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.13.0

#5950 [Docs] Adds testing requirements for PR's
  TESTING.md
Labels: docs, Skip-Changelog, distinguished-contributor

#6129 [Multiple Datasource] Add data source aggregated view to show all compatible data sources or only show used data sources
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/index.ts
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx
Labels: multiple datasource, seasoned-contributor, v2.14.0

#6117 [Docs] Adds developer docs web link
  DEVELOPER_GUIDE.md
Labels: Skip-Changelog, distinguished-contributor

#6168 Update 2.12 changelog to reflect correct change list and move unreleased ones to its section
  CHANGELOG.md
Labels: distinguished-contributor

#6185 [BUG] Fix obsolete snapshots for test within data source management plugin
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
Labels: seasoned-contributor

#6176 [Manual][Backport 2.x] Improves connection pooling support for AWSSigV4 clients in data sources (#6135)
  package.json
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source/server/client/configure_client.test.mocks.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
  src/plugins/data_source/server/types.ts
  src/plugins/data_source/server/util/credential_provider.ts
  yarn.lock
Labels: Skip-Changelog

#6164 Pass request headers when making application config calls
  CHANGELOG.md
  src/plugins/application_config/README.md
  src/plugins/application_config/server/routes/index.test.ts
  src/plugins/application_config/server/routes/index.ts
  src/plugins/application_config/server/types.ts
  src/plugins/csp_handler/server/csp_handlers.ts
Labels: backport 2.x, v2.13.0

#6170 [Discover] options button in canvas to toggle legacy mode
  CHANGELOG.md
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/components/utils/local_storage.ts
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  test/functional/apps/dashboard/dashboard_filter_bar.js
  test/functional/apps/dashboard/dashboard_filtering.js
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/management/_scripted_fields.js
  test/functional/page_objects/discover_page.ts
  test/plugin_functional/test_suites/doc_views/doc_views.ts
Labels: backport 2.x, discover, distinguished-contributor, v2.13.0

#6147 Bump axios to 0.28.0 in 2.x
  CHANGELOG.md
  packages/osd-dev-utils/package.json
  packages/osd-dev-utils/src/osd_client/osd_client_requester.ts
  packages/osd-test/src/failed_tests_reporter/github_api.ts
  packages/osd-ui-shared-deps/package.json
  scripts/postinstall.js
  yarn.lock
Labels: v2.13.0

#6178 add version number to newly created datasource object
  CHANGELOG.md
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
  src/plugins/data_source/server/routes/data_source_connection_validator.ts
  src/plugins/data_source/server/routes/fetch_data_source_version.test.ts
  src/plugins/data_source/server/routes/fetch_data_source_version.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.13.0, version decoupling

#6186 Add set default datasource
  CHANGELOG.md
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
Labels: backport 2.x, multiple datasource, first-time-contributor

#6175 [Multiple Datasource] Use data source filter function before rendering
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
Labels: seasoned-contributor

#6194 Add release notes for 2.13.0
  release-notes/opensearch-dashboards.release-notes-2.13.0.md
Labels: backport 2.x, Skip-Changelog, v2.13.0

#6201 [CVE-2024-28849] Bump follow-redirects from 1.15.4 to 1.15.6
  CHANGELOG.md
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.13.0

#6206 [Manual][Backport 2.x][CVE-2020-36604] Employ a patched version of hoek that addresses CVE-2020-36604 (#6148)
  package.json
  yarn.lock
Labels: Skip-Changelog, v2.13.0

#6209 Update release notes for 2.13
  release-notes/opensearch-dashboards.release-notes-2.13.0.md
Labels: backport 2.x, Skip-Changelog

#6123 [MDS] Add Vega support for importing saved objects
  CHANGELOG.md
  src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
  src/core/server/saved_objects/import/check_conflict_for_data_source.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/test_utils/vega_spec_with_multiple_urls.hjson
  src/core/server/saved_objects/import/test_utils/vega_spec_with_multiple_urls.json
  src/core/server/saved_objects/import/test_utils/vega_spec_with_multiple_urls_mds.hjson
  src/core/server/saved_objects/import/test_utils/vega_spec_with_multiple_urls_mds.json
  src/core/server/saved_objects/import/test_utils/vega_spec_with_opensearch_query.hjson
  src/core/server/saved_objects/import/test_utils/vega_spec_with_opensearch_query.json
  src/core/server/saved_objects/import/test_utils/vega_spec_without_opensearch_query.hjson
  src/core/server/saved_objects/import/test_utils/vega_spec_without_opensearch_query.json
  src/core/server/saved_objects/import/utils.test.ts
  src/core/server/saved_objects/import/utils.ts
  src/plugins/vis_type_vega/server/plugin.ts
  src/plugins/vis_type_vega/server/services.ts
  src/plugins/vis_type_vega/server/test_utils/vega_outdated_references_mds.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_up_to_date_urls_mds.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_multiple_urls.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_multiple_urls.json
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_multiple_urls_mds.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_multiple_urls_mds.json
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_opensearch_query.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_opensearch_query.json
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_opensearch_query_mds.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_with_opensearch_query_mds.json
  src/plugins/vis_type_vega/server/test_utils/vega_spec_without_opensearch_query.hjson
  src/plugins/vis_type_vega/server/test_utils/vega_spec_without_opensearch_query.json
  src/plugins/vis_type_vega/server/types.ts
  src/plugins/vis_type_vega/server/utils.test.ts
  src/plugins/vis_type_vega/server/utils.ts
  src/plugins/vis_type_vega/server/vega_visualization_client_wrapper.test.ts
  src/plugins/vis_type_vega/server/vega_visualization_client_wrapper.ts
Labels: backport 2.x, multiple datasource, first-time-contributor, v2.13.0

#6217 [Admin] Add @xinruiba as a maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: maintenance, valued-contributor

#6208 [Manually backport 2.x] Move @kristenTian to emeritus maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: Skip-Changelog

#6223 [manual][backport-2.x] Add @xinruiba as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: Skip-Changelog

#6228 Add release notes for 2.13
  release-notes/opensearch-dashboards.release-notes-2.13.0.md
Labels: Skip-Changelog

#6154 [Workspace] Validate if workspace exists when setup inside a workspace
  CHANGELOG.md
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/__snapshots__/workspace_fatal_error.test.tsx.snap
  src/plugins/workspace/public/components/workspace_fatal_error/index.ts
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.test.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
Labels: valued-contributor, workspace

#6150 [Workspace] Register a workspace dropdown menu at the top of left nav bar
  CHANGELOG.md
  src/core/public/index.ts
  src/core/public/mocks.ts
  src/core/public/utils/index.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: first-time-contributor, workspace

#6231 Add icon in datasource table page to show the default datasource
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
Labels: backport 2.x, multiple datasource, first-time-contributor, v2.14.0

#6233 [Workspace] Add base path when parsing url in http service
  CHANGELOG.md
  src/core/public/http/http_service.test.ts
  src/core/public/http/http_service.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
Labels: bug, seasoned-contributor, workspace

#6171 [Multiple Datasources] Add TLS configuration for multiple data sources
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/client/client_config.test.ts
  src/plugins/data_source/server/client/client_config.ts
  src/plugins/data_source/server/legacy/client_config.test.ts
  src/plugins/data_source/server/legacy/client_config.ts
  src/plugins/data_source/server/util/tls_settings_provider.test.ts
  src/plugins/data_source/server/util/tls_settings_provider.ts
Labels: backport 2.x, repeat-contributor

#6245 [osd/std] Add additional recovery from false-positives in handling of long numerals
  CHANGELOG.md
  packages/osd-std/src/json.ts
Labels: backport 2.x, distinguished-contributor, v2.13.0, backport 2.13

#6250 [CI][Tests] set legacy browser warning
  .github/workflows/cypress_workflow.yml
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, backport 2.13

#6253 [osd/std] Add fallback mechanism when recovery from false-positives in handling of long numerals fails
  CHANGELOG.md
  packages/osd-std/src/json.ts
Labels: backport 2.x, distinguished-contributor, v2.13.0, backport 2.13

#6255 fix a doc reference typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs, backport 2.x, Skip-Changelog, first-time-contributor

#6238 [Multiple DataSource] Codebase maintenance involves updating typos and removing unused imported packages
  CHANGELOG.md
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.mock.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client_utils.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/fetch_data_source_version.test.ts
  src/plugins/data_source/server/routes/fetch_data_source_version.ts
  src/plugins/data_source/server/routes/test_connection.test.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
  src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source_management/public/auth_registry/index.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.test.ts
  src/plugins/data_source_management/public/components/validation/datasource_form_validation.ts
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.test.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.14.0

#6256 [Multiple Datasource] Refactor data source menu and interface to allow cleaner selection of component and related configurations
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_menu/index.ts
  src/plugins/data_source_management/public/components/data_source_menu/types.ts
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/plugin.ts
Labels: seasoned-contributor

#6179 [Workspace]Add create workspace page
  CHANGELOG.md
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_creator/index.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_cancel_modal.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/hooks.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: first-time-contributor, workspace

#6257 [Multiple Datasource] Remove arrow down icon from data source selectable component
  CHANGELOG.md
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx
Labels: seasoned-contributor

#6268 [Multiple Datasource] Allow top nav menu to mount data source menu for use case when both menus are mounted
  CHANGELOG.md
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/navigation/opensearch_dashboards.json
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.test.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: backport 2.x, multiple datasource, seasoned-contributor, v2.14.0

#6182 [Workspace] Add workspace list page
  CHANGELOG.md
  src/core/public/index.ts
  src/core/public/utils/debounce.test.ts
  src/core/public/utils/debounce.ts
  src/core/public/utils/index.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/__snapshots__/delete_workspace_modal.test.tsx.snap
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.test.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/index.ts
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: repeat-contributor, workspace

#6237 Make sure customer always have a default datasource
  CHANGELOG.md
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
Labels: repeat-contributor

#6282 Fix sslConfig for multiple datasource to handle when certificateAuthorities is unset
  CHANGELOG.md
  src/plugins/data_source/server/client/client_config.test.ts
  src/plugins/data_source/server/client/client_config.ts
  src/plugins/data_source/server/legacy/client_config.test.ts
  src/plugins/data_source/server/legacy/client_config.ts
  src/plugins/data_source/server/util/tls_settings_provider.test.ts
  src/plugins/data_source/server/util/tls_settings_provider.ts
Labels: repeat-contributor

#6218 [MDS] Install Vega sample data
  CHANGELOG.md
  src/core/server/index.ts
  src/core/server/saved_objects/import/index.ts
  src/core/server/saved_objects/import/utils.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
  src/plugins/home/server/services/sample_data/data_sets/test_utils/visualization_objects.json
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: backport 2.x, multiple datasource, first-time-contributor, v2.14.0

#6244 [Backport 2.x] [Multiple Datasources] Add TLS configuration for multiple data sources (#6171)
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/client/client_config.test.ts
  src/plugins/data_source/server/client/client_config.ts
  src/plugins/data_source/server/legacy/client_config.test.ts
  src/plugins/data_source/server/legacy/client_config.ts
  src/plugins/data_source/server/util/tls_settings_provider.test.ts
  src/plugins/data_source/server/util/tls_settings_provider.ts
Labels: v2.14.0
