Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-11, with the labels that each got.

#8778 [Discover] Remove Default Cluster
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, v2.19.0

#8783 fix: staled closure inside chrome_service
  changelogs/fragments/8783.yml
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
Labels: backport 2.x, distinguished-contributor, v2.18.0, backport 2.18

#8781 [Discover] Update async search response type
  changelogs/fragments/8781.yml
  src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Labels: valued-contributor

#8583 Fix data source info is missing in default query when click Discover from other pages
  changelogs/fragments/8583.yml
  src/plugins/data/public/mocks.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
Labels: backport 2.x, discover, repeat-contributor, discover-next, v2.18.0, backport 2.18

#8785 [Discover] Update Version Filter for Data Sources
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor

#8703 Add query enhancement cypress tests to Github CI
  .github/workflows/cypress_workflow.yml
  package.json
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
Labels: ci, backport 2.x, distinguished-contributor, failed changeset, operational excellence, v2.19.0

#8797 [Backport 2.x] fix: staled closure inside chrome_service
  changelogs/fragments/8783.yml
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
Labels: Skip-Changelog, workspace

#8799 [Discover] Makes caching dataset options optional
  changelogs/fragments/8799.yml
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, discover, distinguished-contributor, discover-next, v2.19.0

#8803 [Discover] Query editor state sync fixes
  changelogs/fragments/8803.yml
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, distinguished-contributor, discover-next, v2.19.0

#8744 Revert back to using the official release of `vega-interpreter`
  changelogs/fragments/8744.yml
  package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.19.0

#8782 [ciGroup6 fix] add data-test-subj for refresh data button in discover
  src/plugins/discover/public/application/components/uninitialized/uninitialized.tsx
Labels: backport 2.x, flakey-test, v2.19.0

#8816 [discover] temporarily disable recent datasets
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, discover-next, v2.19.0

#8738 [Workspace]Fix error message missed in workspace creator name input
  changelogs/fragments/8738.yml
  src/plugins/workspace/public/components/workspace_creator/creator_details_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_form/index.ts
Labels: backport 2.x, distinguished-contributor, workspace, v2.19.0

#8786 [Workspace]Fix flights sample data copy in workspace assets page
  changelogs/fragments/8786.yml
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: backport 2.x, distinguished-contributor

#8806 [Discover] Decouple `data$` updates to prevent rows clearing on hook re-render
  changelogs/fragments/8806.yml
  src/plugins/data/public/query/timefilter/timefilter_service.mock.ts
  src/plugins/discover/public/application/view_components/utils/use_search.test.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/mocks.ts
Labels: all-star-contributor

#8827 Remove `head 10` for PPL default query to unblock cypress test failures
  changelogs/fragments/8827.yml
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, discover, distinguished-contributor, discover-next

#8828 Remove data enhancement options from yaml config
  changelogs/fragments/8828.yml
  config/opensearch_dashboards.yml
Labels: backport 2.x, discover, first-time-contributor, discover-next, v2.19.0

#8137 [Workspace] Integrate dashboard admin with dynamic config
  changelogs/fragments/8137.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8833 [workspace] Add test id for workspace multi-deletion button
  changelogs/fragments/8833.yml
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, seasoned-contributor, workspace

#8843 [Autocomplete] PPL table name parser fix
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLLexer.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLParser.g4
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.ts
Labels: backport 2.x

#8834 [Workspace] Add unit tests for inspect page url
  changelogs/fragments/8834.yml
  src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.test.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/utils.test.ts
  src/plugins/saved_objects_management/public/utils.ts
Labels: backport 2.x, all-star-contributor

#8848 Fix template queries loading and update getSampleQuery interface
  changelogs/fragments/8848.yml
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.test.tsx
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
Labels: first-time-contributor

#8832 [Discover] Fix discover query loading state
  src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.test.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, discover, Skip-Changelog, all-star-contributor, discover-next

#8857 [Workspace][Bug] Fix inspect page url error
  changelogs/fragments/8857.yml
  src/plugins/saved_objects_management/common/types.ts
  src/plugins/saved_objects_management/public/utils.test.ts
  src/plugins/saved_objects_management/public/utils.ts
  src/plugins/saved_objects_management/server/lib/find_relationships.test.ts
  src/plugins/saved_objects_management/server/lib/find_relationships.ts
Labels: distinguished-contributor

#8867 [Discover] Add max height and scroll to error message body
  changelogs/fragments/8867.yml
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
Labels: backport 2.x, repeat-contributor, v2.19.0

#8863 Keep previous query result if current query result in error
  changelogs/fragments/8863.yml
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: backport 2.x, discover, distinguished-contributor, discover-next

#8839 Fix a typo while inspecting values for large numerals in OSD and the JS client
  changelogs/fragments/8839.yml
  packages/osd-std/src/json.test.ts
  packages/osd-std/src/json.ts
  scripts/postinstall.js
Labels: backport 2.x, distinguished-contributor, v2.19.0

#8871 [Discover] Dataset search on page load issues
  changelogs/fragments/8871.yml
  src/plugins/discover/public/application/view_components/utils/use_search.test.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, discover, distinguished-contributor, discover-next

#8866 [Discover] Hide Date Picker For Unsupported Types
  changelogs/fragments/8866.yml
  src/plugins/data/public/query/query_string/language_service/language_service.mock.ts
  src/plugins/data/public/ui/query_editor/query_editor_top_row.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
Labels: backport 2.x, discover, seasoned-contributor, discover-next

#8780 [Bug] Make release note generation more resilient by gracefully handling invalid changelog fragments
  src/dev/generate_release_note.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, operational excellence

#8864 Adjusted source of QueryStringManager functions for flyout.
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.test.tsx
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: backport 2.x, discover, Skip-Changelog, first-time-contributor, discover-next

#8855 [chore]upgrade actions/upload-artifact to v4
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/cypress_workflow.yml
  .github/workflows/release_cypress_workflow.yml
  changelogs/fragments/8855.yml
Labels: backport 2.x, all-star-contributor

#8883 Use currently selected data source when no source attached to saved query
  changelogs/fragments/8883.yml
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_flyouts/save_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_form/helpers.tsx
  src/plugins/data/public/ui/saved_query_form/save_query_form.tsx
  src/plugins/data/public/ui/search_bar/lib/populate_state_from_saved_query.test.ts
  src/plugins/data/public/ui/search_bar/lib/populate_state_from_saved_query.ts
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: backport 2.x, discover, valued-contributor, discover-next

#8896 Added framework to get default query string using dataset and language combination
  changelogs/fragments/8896.yml
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
Labels: discover, seasoned-contributor, discover-next

#8899 Only support copy for query templates
  changelogs/fragments/8899.yml
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
Labels: backport 2.x, seasoned-contributor

#8897 [Manual backport 2.x] Add data test subject for discover cypress test (#8682)
  changelogs/fragments/8682.yml
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.tsx
Labels: failed changeset

#8898 [Manual backport 2.x] Add query enhancement cypress tests to Github CI (#8703)
  .github/workflows/cypress_workflow.yml
  package.json
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
Labels: failed changeset

#8872 Remove filter out serverless cluster and add support to extract index name
  changelogs/fragments/8872.yml
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: backport 2.x, discover, distinguished-contributor, discover-next

#8909 Re-enable serverless mds support for index pattern
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
Labels: Skip-Changelog, distinguished-contributor

#8911 Reenable filter for s3
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: Skip-Changelog, distinguished-contributor

#8912 Fix query editor cursor alignment by removing monaco css overrides
  changelogs/fragments/8912.yml
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
Labels: repeat-contributor

#8915 [augmenter] do not support datasources with no version
  changelogs/fragments/8915.yml
  src/plugins/vis_augmenter/public/plugin.ts
  src/plugins/vis_augmenter/public/services.ts
  src/plugins/vis_augmenter/public/utils/utils.test.ts
  src/plugins/vis_augmenter/public/utils/utils.ts
  src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx
  src/plugins/vis_type_vislib/public/line_to_expression.ts
  src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Labels: backport 2.x, distinguished-contributor, v2.19.0

#8928 Mitigate the incorrect layout of Discover due to a race condition between loading column definition and data
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
Labels: backport 2.x, distinguished-contributor, v2.19.0

#8900 [Workspace] feat: optimize recent items and filter out items whose workspace is deleted
  changelogs/fragments/8900.yml
  src/core/public/chrome/ui/header/recent_items.test.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8951 [Auto Suggest] SQL Syntax Highlighting fix
  changelogs/fragments/8951.yml
  packages/osd-monaco/src/xjson/lexer_rules/opensearchsql.ts
Labels: backport 2.x, discover, seasoned-contributor, discover-next

#8926 Update Cypress to v12
  changelogs/fragments/8926.yml
  cypress.config.js
  cypress.json
  cypress/support/e2e.js
  package.json
  yarn.lock
Labels: repeat-contributor
