Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-02, with the labels that each got.

#5772 Change sort icon according to current sort conditions
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
Labels: distinguished-contributor

#5773 Fix breadcrumb navigation on context page for both legacy and data grid table
  src/plugins/discover/public/application/helpers/breadcrumbs.ts
Labels: discover, distinguished-contributor

#5770 Add pagination to discover embeddable
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
Labels: discover, distinguished-contributor

#5779 [Discover] Prevent wrapping of time series cells
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
Labels: distinguished-contributor

#5780 Vertically align the text in QueryStringInputUI with other elements on the page
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
Labels: distinguished-contributor

#5783 Use `ouiCodeFont` in Discover and reduce text size
  src/core/server/core_app/assets/legacy_dark_theme.css
  src/core/server/core_app/assets/legacy_light_theme.css
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/default_discover_table/_doc_table.scss
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
Labels: distinguished-contributor

#5784 [Discover] Display filter buttons at top right of the cell
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
Labels: distinguished-contributor

#5788 [Discover] Fix overflow of the expanded document
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
Labels: distinguished-contributor

#5787 update feedback msg
  src/plugins/discover/public/application/components/top_nav/table_feedbacks_panel.tsx
Labels: distinguished-contributor

#5771 Resolve sorting and two Settings: default sort & short dots
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/helper.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/utils/state_management/common.test.ts
  src/plugins/discover/public/application/utils/state_management/common.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
Labels: discover, distinguished-contributor

#5778 [Discover] Fixes pagination style
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/_pagination.scss
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/pagination.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/utils/get_default_sort.ts
  src/plugins/discover/public/embeddable/search_embeddable.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
  src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss
Labels: distinguished-contributor

#5776 Routing for surrounding doc link should work without a question mark appending to the end
  src/plugins/discover/public/migrate_state.ts
Labels: discover, distinguished-contributor

#5675 [PM] Enhance single version requirements imposed during bootstrapping
  CHANGELOG.md
  packages/osd-pm/README.md
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/src/cli.ts
  packages/osd-pm/src/commands/bootstrap.ts
  packages/osd-pm/src/utils/project.ts
  packages/osd-pm/src/utils/scripts.ts
  packages/osd-pm/src/utils/validate_dependencies.ts
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5795 [Discover] Legacy table type fixes
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/default_discover_table/helper.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/utils/get_sort_for_search_source.ts
  src/plugins/discover/public/embeddable/types.ts
  src/plugins/discover/public/saved_searches/types.ts
Labels: distinguished-contributor

#5797 [CVE-2020-8203] Bump `cheerio` to fix vulnerable `lodash` dependency
  CHANGELOG.md
  package.json
  packages/osd-dev-utils/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5806 [Manual][Backport 2.x] [CVE-2020-8203] Bump `cheerio` to fix vulnerable `lodash` dependency
  CHANGELOG.md
  package.json
  packages/osd-dev-utils/package.json
  yarn.lock
Labels: v2.12.0

#5781 Add datasource picker to import saved object flyout when multiple data source is enabled
  CHANGELOG.md
  src/plugins/data_source_management/opensearch_dashboards.json
  src/plugins/data_source_management/public/components/cluster_selector/__snapshots__/cluster_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/cluster_selector/cluster_selector.test.tsx
  src/plugins/data_source_management/public/components/cluster_selector/cluster_selector.tsx
  src/plugins/data_source_management/public/components/cluster_selector/index.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/index.scss
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/lib/import_file.ts
  src/plugins/saved_objects_management/public/lib/resolve_import_errors.ts
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_mode_control.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  test/functional/apps/dashboard/time_zones.js
  test/functional/apps/management/_import_objects.js
  test/functional/apps/management/_mgmt_import_saved_objects.js
  test/functional/page_objects/management/saved_objects_page.ts
Labels: backport 2.x, multiple datasource, v2.12.0

#5769 [Manual][Backport 2.x][OSCI][ADD] More tests for overview (#5418)
  CHANGELOG.md
  src/plugins/opensearch_dashboards_overview/public/components/overview/__snapshots__/overview.test.tsx.snap
  src/plugins/opensearch_dashboards_overview/public/components/overview/overview.test.tsx
Labels: v2.12.0

#5803 Bump `msgpackr` from `1.9.7` to `1.10.1`
  CHANGELOG.md
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5799 [Manual Backport 2.x][PM] Enhance single version requirements imposed during bootstrapping (#5675)
  CHANGELOG.md
  packages/osd-pm/README.md
  packages/osd-pm/dist/index.js
  packages/osd-pm/package.json
  packages/osd-pm/src/cli.ts
  packages/osd-pm/src/commands/bootstrap.ts
  packages/osd-pm/src/utils/project.ts
  packages/osd-pm/src/utils/scripts.ts
  packages/osd-pm/src/utils/validate_dependencies.ts
Labels: v2.12.0

#5808 [Discover] Update toggle to button
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
Labels: discover

#5751 Datasource id is required if multiple datasource is enabled and no default cluster supported
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/data/server/search/opensearch_search/decide_client.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.test.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
Labels: backport 2.x, multiple datasource

#5814 [Data Explorer] Adds support for line count
  src/plugins/discover/public/application/components/data_grid/constants.ts
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_toolbar.tsx
Labels: discover, distinguished-contributor, v2.12.0

#5816 Add swith to datagrid table and fix ciGroup1
  test/functional/apps/context/_context_navigation.js
  test/functional/apps/context/_date_nanos.js
  test/functional/apps/context/_discover_navigation.js
  test/functional/apps/context/_filters.js
  test/functional/apps/context/_size.js
  test/functional/apps/home/_sample_data.ts
  test/functional/apps/management/_scripted_fields.js
  test/functional/page_objects/discover_page.ts
  test/functional/services/dashboard/expectations.ts
Labels: distinguished-contributor

#5777 Update import api to have data source id to allow import saved objects from uploading files to have data source
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
  src/core/server/saved_objects/import/check_conflict_for_data_source.ts
  src/core/server/saved_objects/import/check_origin_conflicts.ts
  src/core/server/saved_objects/import/collect_saved_objects.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/regenerate_ids.test.ts
  src/core/server/saved_objects/import/regenerate_ids.ts
  src/core/server/saved_objects/import/resolve_import_errors.test.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/resolve_import_errors.ts
Labels: backport 2.x, first-time-contributor, v2.12.0

#5820 [Manual Backport 2.x ]Update import api to have data source id to allow import saved objects from uploading files to have data source
  CHANGELOG.md
  src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
  src/core/server/saved_objects/import/check_conflict_for_data_source.ts
  src/core/server/saved_objects/import/check_origin_conflicts.ts
  src/core/server/saved_objects/import/collect_saved_objects.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/regenerate_ids.test.ts
  src/core/server/saved_objects/import/regenerate_ids.ts
  src/core/server/saved_objects/import/resolve_import_errors.test.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/resolve_import_errors.ts
Labels: first-time-contributor

#5821 Fix pluign ftr tests
  test/plugin_functional/test_suites/doc_views/doc_views.ts
Labels: distinguished-contributor

#5801 [Manual Backport 1.3] Move @seanneumann to emeritus maintainer (#5634)
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: autocut, v1.3.15

#5811 [MD] Support local cluster by default
  src/plugins/data_source/config.ts
Labels: Skip-Changelog

#5802 [Manual backport 2.x][Security] Updates dev guide for security (#5736)
  DEVELOPER_GUIDE.md
  src/cli/serve/serve.js
Labels: autocut, v2.12.0

#5619 Fix (TableVis): Properly filter table columns when sending to filter …
  CHANGELOG.md
  src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
Labels: distinguished-contributor, v2.12.0

#5824 Update snapshot for failed ciGroup3
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
Labels: distinguished-contributor

#5822 Fix functional 3 and 4 for discover legacy
  test/functional/apps/dashboard/dashboard_filter_bar.js
  test/functional/apps/dashboard/dashboard_filtering.js
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/dashboard/dashboard_time_picker.js
Labels: discover, distinguished-contributor, v2.12.0

#5826 Solve cigroup 7 flakiness
  test/functional/apps/management/_scripted_fields.js
Labels: distinguished-contributor

#5825 Updates 2.12 branch name in the package.json
  package.json
Labels: Skip-Changelog, v2.12.0

#5830 Bump node version to 18.19.0
  .node-version
  .nvmrc
  CHANGELOG.md
  Dockerfile
  TESTING.md
Labels: backport 2.x, distinguished-contributor, v2.12.0

#5836 [Data Exploerer] Persist line height
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_toolbar.tsx
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
Labels: discover, v2.12.0

#5835 Update table revert changelog
  CHANGELOG.md
  packages/osd-ui-shared-deps/package.json
Labels: distinguished-contributor

#5841 [Discover] Update fonts of the datagrid
  src/plugins/discover/public/application/components/data_grid/_data_grid_table.scss
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
Labels: backport 2.x, Skip-Changelog, v2.12.0, backport 2.12

#5852 Add release note for 2.12
  release-notes/opensearch-dashboards.release-notes-2.12.0.md
Labels: backport 2.x, Skip-Changelog, backport 2.12

#5859 [Manual Backport 2.12][CVE-2023-26159] Bump follow-redirects from 1.15.2 to 1.15.4 (#5669)
  package.json
  yarn.lock
Labels: autocut, v2.12.0

#5862 Bump oui to 1.5.1
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  release-notes/opensearch-dashboards.release-notes-2.12.0.md
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.12.0, backport 2.12

#5860 [Manual Backport 2.x][CVE-2023-26159] Bump follow-redirects from 1.15.2 to 1.15.4 (#5669)
  package.json
  yarn.lock
Labels: autocut, v2.13.0

#5864 [Manual backport 2.12] Bump oui to 1.5.1 (#5862)
  CHANGELOG.md
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  release-notes/opensearch-dashboards.release-notes-2.12.0.md
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: autocut, v2.12.0

#5851 [Multi data source] Add interfaces to register add-on authentication method from plug-in module
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source_management/public/auth_registry/index.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.test.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/mocks.ts
Labels: backport 2.x, valued-contributor, v2.13.0

#5827 [MD] Able to hide "Local Cluster" option
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.test.tsx
  src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.tsx
  src/plugins/data/server/search/opensearch_search/decide_client.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.test.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
  src/plugins/data_source/config.ts
  src/plugins/data_source/public/index.ts
  src/plugins/data_source/public/plugin.ts
  src/plugins/data_source/public/types.ts
  src/plugins/data_source/server/index.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/components/cluster_selector/__snapshots__/cluster_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/cluster_selector/cluster_selector.test.tsx
  src/plugins/data_source_management/public/components/cluster_selector/cluster_selector.tsx
  src/plugins/dev_tools/public/application.tsx
  src/plugins/home/public/application/components/sample_data_set_card.js
  src/plugins/home/public/application/components/sample_data_set_cards.js
  src/plugins/home/public/application/components/tutorial_directory.js
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/__snapshots__/step_data_source.test.tsx.snap
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/index_pattern_management/public/types.ts
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
Labels: repeat-contributor

#5886 Update `caniuse-lite`
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.12.0, backport 2.12

#5725 [Tests] Add Github workflow for Test Orchestrator in FT Repo to run cypress tests within Dashboards repo
  .github/workflows/dashboards_cypress_workflow.yml
  CHANGELOG.md
  cypress.config.js
  cypress/integration/core_opensearch_dashboards/dashboard_sanity_test_spec.js
  package.json
  scripts/bwctest_osd.sh
  scripts/common/opensearch_dashboards_service.sh
  scripts/common/opensearch_service.sh
  scripts/common/utils.sh
  scripts/cypress_tests.sh
  yarn.lock
Labels: distinguished-contributor, v2.13.0

#5895 Add api registry and allow it to be added into client config in data source plugin
  CHANGELOG.md
  docs/multi-datasource/client_management_design.md
  src/plugins/data_source/server/client/client_config.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/legacy/client_config.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/schema_registry/custom_api_schema_registry.test.ts
  src/plugins/data_source/server/schema_registry/custom_api_schema_registry.ts
  src/plugins/data_source/server/schema_registry/index.ts
  src/plugins/data_source/server/types.ts
Labels: repeat-contributor

#5874 [Manual Backport 2.x][Multi data source] Add interfaces to register add-on authentication method from plug-in module
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.test.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source_management/public/auth_registry/index.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.test.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/mocks.ts
Labels: multiple datasource, v2.13.0

#5915 [FTR][Chore] baseline the screenshots for area and tsvb
  CHANGELOG.md
  test/functional/screenshots/baseline/area_chart.png
  test/functional/screenshots/baseline/tsvb_dashboard.png
Labels: backport 2.x, distinguished-contributor, backport 2.12

#5718 [OSCI][FEAT] Rollout OSD - Proposal Changelog and Release Notes Project
  .github/pull_request_template.md
  .github/workflows/changelog_verifier.yml
  .github/workflows/opensearch_changelog_workflow.yml
  changelogs/README.md
  changeset file for PR #29 created
  changeset file for PR #29 updated
  package.json
  scripts/generate_release_note.js
  src/dev/generate_release_note.ts
  src/dev/generate_release_note_helper.ts
Labels: first-time-contributor

#5926 Upgrade chromedriver to fix bootstrapping errors
  CHANGELOG.md
  package.json
  yarn.lock
Labels: test:functional, backport 2.x, first-time-contributor, v2.13.0, backport 2.12

#5907 [MD] Concatenate data source name with index pattern name and change delimiter to double colon
  CHANGELOG.md
  src/plugins/data/common/index_patterns/lib/get_title.test.ts
  src/plugins/data/common/index_patterns/lib/get_title.ts
  src/plugins/data/common/index_patterns/utils.test.ts
  src/plugins/data/common/index_patterns/utils.ts
  src/plugins/data/public/ui/index_pattern_select/index_pattern_select.tsx
Labels: backport 2.x, repeat-contributor, v2.13.0

#5881 Refactor getClient and getLegacyClient to use authentication method registry
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.mock.ts
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/client/configure_client.test.mocks.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source/server/util/credential_provider.ts
Labels: multiple datasource, seasoned-contributor

#5934 [Bug][Discover] Allow saved sort from search embeddable to load in Dashboard
  CHANGELOG.md
  src/plugins/discover/public/embeddable/search_embeddable.tsx
Labels: bug, backport 2.x, discover, distinguished-contributor, v2.13.0

#5931 [Chore] Update changelog post 2.12
  CHANGELOG.md
Labels: backport 1.x, backport 2.x, backport 2.12

#5929 [2.x] Increment version to 2.13.0
  package.json
Labels: Skip-Changelog, v2.13.0

#5946 [BUG] Support duplicate index pattern name
  CHANGELOG.md
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
Labels: backport 2.x, repeat-contributor, v2.13.0

#5948 [Discover] Fixes safari overflow bug
  CHANGELOG.md
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
Labels: backport 2.x, distinguished-contributor, v2.13.0

#5955 [Manual backport 2.x] [Chore] Update changelog post 2.12 (#5931)
  CHANGELOG.md
Labels: backport 2.12

#5944 Fix missing customApiRegistryPromise param for test connection
  CHANGELOG.md
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/test_connection.test.ts
  src/plugins/data_source/server/routes/test_connection.ts
Labels: backport 2.x, multiple datasource, valued-contributor, v2.13.0

#5964 [CI] Skip workflow for non release branches on push
  .github/workflows/build_and_test_workflow.yml
Labels: ci, Skip-Changelog, distinguished-contributor

#5940 [Manual Backport 2.x] Refactor getClient and getLegacyClient to use authentication method registry (#5881)
  CHANGELOG.md
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source/server/auth_registry/authentication_methods_registry.mock.ts
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/client/configure_client.test.mocks.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/client/configure_client.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/routes/test_connection.ts
  src/plugins/data_source/server/types.ts
  src/plugins/data_source/server/util/credential_provider.ts
Labels: multiple datasource, v2.13.0

#5882 [MD] Improved error handling for the search API when a null value is passed for the dataSourceId.
  CHANGELOG.md
  src/plugins/data/server/search/opensearch_search/decide_client.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.test.ts
  src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
  src/plugins/data/server/search/search_service.ts
  src/plugins/data_source/server/plugin.ts
  src/plugins/data_source/server/types.ts
Labels: backport 2.x, repeat-contributor, v2.13.0

#5970 Fixes authentication_methods_registry.mock module
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/routes/test_connection.test.ts
Labels: backport 2.x, multiple datasource, Skip-Changelog, v2.13.0

#5956 [osd/std] Add additional recovery from false-positives in handling of long numerals
  CHANGELOG.md
  packages/osd-std/src/json.ts
Labels: backport 2.x, distinguished-contributor, v2.13.0, backport 2.12

#5974 [Manual Backport 2.x] Fixes authentication_methods_registry.mock module (#5970)
  src/plugins/data_source/server/auth_registry/index.ts
  src/plugins/data_source/server/client/configure_client.test.ts
  src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
  src/plugins/data_source/server/routes/test_connection.test.ts
Labels: Skip-Changelog, v2.13.0

#5916 Hide/Show authentication method in multi data source plugin based on configuration
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/plugins/data_source/config.ts
  src/plugins/data_source/public/plugin.ts
  src/plugins/data_source/public/types.ts
  src/plugins/data_source/server/index.ts
  src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, multiple datasource, repeat-contributor, v2.13.0

#5967 Fix link to documentation for geoHash precision
  CHANGELOG.md
  src/plugins/maps_legacy/server/ui_settings.ts
Labels: backport 2.x, distinguished-contributor

#5982 [Admin] Add @ruanyl as a maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: repeat-contributor

#5988 [Admin] Add @BionIT as a maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: valued-contributor
