Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2024-10, with the labels that each got.

#8382 [Workspace] Refactor collaborators panel at workspace create
  changelogs/fragments/8382.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
Labels: backport 2.x, valued-contributor, workspace

#8214 [Discover] Display Cache Time and Clear Cache Button
  changelogs/fragments/8214.yml
  src/plugins/data/common/storage/storage.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
Labels: backport 2.x, discover, seasoned-contributor, discover-next, v2.18.0

#8415 add Hailong-am as maintainer
  MAINTAINERS.md
  changelogs/fragments/8415.yml
Labels: backport 2.x, distinguished-contributor

#8410 Fix unprefixed and duplicate i18n identifiers in workspace plugin
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx
  src/plugins/workspace/public/components/workspace_column/workspace_column.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
  src/plugins/workspace/public/components/workspace_form/fields/workspace_name_field.tsx
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8407 Fix duplicate i18n identifiers in visualize plugin
  changelogs/fragments/8407.yml
  src/plugins/visualize/public/application/components/visualize_listing.tsx
  src/plugins/visualize/public/application/components/visualize_top_nav.tsx
  src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8345 Add UI Metric for Discover 2.0
  src/plugins/data/public/ui/index_pattern_select/index_pattern_select.test.tsx
  src/plugins/data_explorer/opensearch_dashboards.json
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/plugin.ts
  src/plugins/data_explorer/public/services.ts
  src/plugins/data_explorer/public/types.ts
  src/plugins/data_explorer/public/ui_metric/constants.ts
  src/plugins/data_explorer/public/ui_metric/index.ts
  src/plugins/data_explorer/public/ui_metric/report_ui_metric.ts
  src/plugins/discover/opensearch_dashboards.json
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/opensearch_dashboards_services.ts
  src/plugins/discover/public/plugin.ts
  src/plugins/discover/public/ui_metric/constants.ts
  src/plugins/discover/public/ui_metric/index.ts
  src/plugins/discover/public/ui_metric/report_ui_metric.ts
Labels: backport 2.x, discover, Skip-Changelog, all-star-contributor, discover-next, v2.18.0

#8268 [workspace]feat: validate workspace when find objects
  changelogs/fragments/8268.yml
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/routes/index.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.mock.ts
Labels: backport 2.x, distinguished-contributor, workspace

#8405 Fix duplicate i18n identifier in savedObjectsManagement plugin
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8398 Fix dynamic uses of i18n in indexPatternManagement plugin
  changelogs/fragments/8398.yml
  src/plugins/index_pattern_management/public/components/breadcrumbs.ts
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#7938 [navigation] feat: Render dev tools inside a modal
  changelogs/fragments/7938.yml
  src/plugins/console/public/application/components/__snapshots__/top_nav_menu.test.tsx.snap
  src/plugins/console/public/application/components/top_nav_menu.test.tsx
  src/plugins/console/public/application/components/top_nav_menu.tsx
  src/plugins/console/public/application/containers/editor/editor.tsx
  src/plugins/console/public/application/containers/main/get_top_nav.ts
  src/plugins/console/public/application/containers/main/get_top_nav.tsx
  src/plugins/console/public/application/containers/main/main.tsx
  src/plugins/console/public/styles/_app.scss
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/dev_tools_icon.scss
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/dev_tools/public/plugin.ts
Labels: backport 2.x, distinguished-contributor, workspace, navigation

#8429 Fix flaky IndexPatternSelect test in data plugin
  src/plugins/data/public/ui/index_pattern_select/index_pattern_select.test.tsx
Labels: distinguished-contributor

#8403 Fix dynamic uses of i18n in home plugin
  changelogs/fragments/8403.yml
  src/plugins/home/server/ui_settings.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8408 Fix unprefixed i18n identifiers in management plugin
  changelogs/fragments/8408.yml
  src/plugins/management/public/components/settings_icon.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8255 [Discover] Support data connections and multi-select table in dataset picker
  changelogs/fragments/8255.yml
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/query/query_string/index.ts
  src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss
  src/plugins/data/public/ui/dataset_selector/_index.scss
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
  src/plugins/data_source/opensearch_dashboards.json
Labels: backport 2.x, discover, seasoned-contributor, discover-next, v2.18.0

#8435 [Workspace] Remove whats new in workspace overview page
  changelogs/fragments/8435.yml
  src/plugins/home/public/application/components/home_list_card.test.tsx
  src/plugins/home/public/application/components/home_list_card.tsx
  src/plugins/home/public/application/home_render.test.tsx
  src/plugins/home/public/application/home_render.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8247 [BUG] fixed wrapping of date
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
Labels: backport 2.x, discover, repeat-contributor, failed changeset, discover-next, v2.18.0

#8409 Fix unprefixed and duplicate i18n identifiers in visAugmenter plugin
  changelogs/fragments/8409.yml
  src/plugins/vis_augmenter/public/actions/plugin_resource_delete_action.ts
  src/plugins/vis_augmenter/public/actions/saved_object_delete_action.ts
  src/plugins/vis_augmenter/public/view_events_flyout/actions/open_events_flyout_action.ts
  src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx
  src/plugins/vis_augmenter/server/plugin.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8413 [Workspace]Refactor use case selector in workspace creation page
  changelogs/fragments/8413.yml
  src/core/utils/default_nav_groups.ts
  src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
  src/plugins/workspace/public/components/workspace_creator/creator_details_panel.tsx
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case_flyout.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case_flyout.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/default_workspace.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/default_workspace.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8340 Temporary fix for a bug with Chrome 129 when handling mask-image
  src/core/public/styles/_base.scss
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, backport 2.17, backport 2.17-next

#8393 Fix dynamic uses of i18n and correct duplicate i18n identifiers in console plugin
  changelogs/fragments/8393.yml
  src/plugins/console/public/application/components/import_flyout.tsx
  src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8404 Fix dynamic uses of i18n in opensearchDashboardsReact plugin
  changelogs/fragments/8404.yml
  src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8400 Fix dynamic uses of i18n in visTypeTimeline plugin
  src/plugins/vis_type_timeline/server/series_functions/graphite.js
  src/plugins/vis_type_timeline/server/series_functions/graphite.test.js
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8392 Fix dynamic uses of i18n in core
  changelogs/fragments/8392.yml
  src/core/public/i18n/i18n_eui_mapping.tsx
  src/core/server/rendering/views/template.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8401 Fix unprefixed i18n identifiers in dashboard plugin
  changelogs/fragments/8401.yml
  src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8455 [i18n] Fix i18n String in New Discover Cache Time
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
Labels: i18n, backport 2.x, Skip-Changelog, seasoned-contributor, discover-next, v2.18.0

#8445 [Workspace]Fix use case hidden features not accessible
  changelogs/fragments/8445.yml
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case_flyout.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case_flyout.tsx
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8422 [Workspace] feat: support use case populate for workspace create and list page
  changelogs/fragments/8422.yml
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/default_workspace.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8332 [navigation]Refactor: flatten left nav in Analytics(all) use case
  changelogs/fragments/8332.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_groups.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups_label.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/chrome/ui/header/variables.scss
  src/core/public/chrome/utils.ts
  src/core/utils/default_app_categories.ts
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/home/public/application/components/home_icon.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/management/public/components/feature_cards/__snapshots__/feature_cards.test.tsx.snap
  src/plugins/management/public/components/feature_cards/feature_cards.test.tsx
  src/plugins/management/public/components/feature_cards/feature_cards.tsx
  src/plugins/management/public/components/settings_icon.tsx
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, workspace, navigation

#8461 [Workspace]Restrict at least one data source in workspace creation page
  changelogs/fragments/8461.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8414 Split .i18nrc across `src`, `packages`, and `examples`
  .i18nrc.json
  examples/.i18nrc.json
  packages/.i18nrc.json
  src/.i18nrc.json
  src/dev/build/args.test.ts
  src/dev/build/args.ts
  src/dev/build/build_distributables.ts
  src/dev/build/cli.ts
  src/dev/build/tasks/copy_source_task.ts
  src/dev/build/tasks/copy_translations_task.ts
  src/dev/build/tasks/index.ts
  src/dev/i18n/config.ts
  src/dev/i18n/constants.ts
  src/dev/i18n/index.ts
  src/dev/i18n/tasks/check_configs.ts
  src/dev/i18n/tasks/merge_configs.ts
  src/dev/run_i18n_check.ts
  src/dev/run_i18n_extract.ts
  src/dev/run_i18n_integrate.ts
  src/legacy/server/i18n/index.ts
  src/plugins/data_explorer/.i18nrc.json
  src/plugins/query_enhancements/.i18nrc.json
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8397 Fix dynamic uses of i18n and correct unprefixed i18n identifiers in queryEnhancements plugin
  changelogs/fragments/8397.yml
  src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/public/query_editor/query_language_reference.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8396 Fix dynamic uses of i18n in discover plugin
  changelogs/fragments/8396.yml
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
  src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8424 Add preliminary translations for de-DE, es-419, es-ES, fr-CA, fr-FR, id-ID, it-IT, ja-JP, ko-KR, pt-BR, pt-PT, tr-TR, zh-CN, and zh-TW
  changelogs/fragments/8424.yml
  packages/.i18nrc.json
  packages/translations/tr-TR.json
  src/.i18nrc.json
  src/translations/de-DE.json
  src/translations/es-419.json
  src/translations/es-ES.json
  src/translations/fr-CA.json
  src/translations/fr-FR.json
  src/translations/id-ID.json
  src/translations/it-IT.json
  src/translations/ja-JP.json
  src/translations/ko-KR.json
  src/translations/pt-BR.json
  src/translations/pt-PT.json
  src/translations/tr-TR.json
  src/translations/zh-CN.json
  src/translations/zh-TW.json
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8443 Compress the OuiSearchBar instances used on Advanced Settings and Saved Object Management pages
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/advanced_settings/public/management_app/components/search/__snapshots__/search.test.tsx.snap
  src/plugins/advanced_settings/public/management_app/components/search/search.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
Labels: backport 2.x, distinguished-contributor, look & feel, v2.18.0

#8406 Fix unprefixed i18n identifiers in visTypeVega plugin
  changelogs/fragments/8406.yml
  src/plugins/vis_type_vega/public/data_model/search_api.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8399 Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in visBuilder plugin
  changelogs/fragments/8399.yml
  src/plugins/vis_builder/public/application/components/top_nav.tsx
  src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
  src/plugins/vis_builder/public/application/utils/use/use_can_save.ts
  src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
  src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
  src/plugins/vis_builder/public/visualizations/metric/components/metric_viz_options.tsx
  src/plugins/vis_builder/public/visualizations/metric/metric_viz_type.ts
  src/plugins/vis_builder/public/visualizations/table/components/table_viz_options.tsx
  src/plugins/vis_builder/public/visualizations/table/table_viz_type.ts
  src/plugins/vis_builder/public/visualizations/vislib/area/area_vis_type.ts
  src/plugins/vis_builder/public/visualizations/vislib/area/components/area_vis_options.tsx
  src/plugins/vis_builder/public/visualizations/vislib/common/basic_vis_options.tsx
  src/plugins/vis_builder/public/visualizations/vislib/histogram/components/histogram_vis_options.tsx
  src/plugins/vis_builder/public/visualizations/vislib/histogram/histogram_vis_type.ts
  src/plugins/vis_builder/public/visualizations/vislib/line/components/line_vis_options.tsx
  src/plugins/vis_builder/public/visualizations/vislib/line/line_vis_type.ts
  src/plugins/vis_builder/server/plugin.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8412 Fix unprefixed i18n identifiers in examples
  changelogs/fragments/8412.yml
  examples/embeddable_examples/public/list_container/list_container_factory.ts
  examples/embeddable_examples/public/todo/todo_ref_embeddable_factory.tsx
  examples/expressions_example/common/expression_functions/action/quick_form_fn.ts
  examples/multiple_data_source_examples/public/components/data_source_via_top_nav_menu.tsx
  examples/search_examples/public/components/app.tsx
  examples/state_containers_examples/public/with_data_services/components/app.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8395 Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in data plugin
  src/plugins/data/public/data_sources/constants.tsx
  src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.tsx
  src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
  src/plugins/data/public/query/query_string/language_service/lib/default_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/data/public/search/errors/timeout_error.test.tsx
  src/plugins/data/public/search/errors/timeout_error.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_string_input/language_switcher.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8402 Fix incorrect use of TopNavControlDescriptionData in dataSourceManagement plugin
  changelogs/fragments/8402.yml
  src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel.tsx
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8394 Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in dataSourceManagement plugin
  changelogs/fragments/8394.yml
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/components/create_button/__snapshots__/create_button.test.tsx.snap
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
  src/plugins/data_source_management/public/components/data_source_error_menu/data_source_error_menu.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/__snapshots__/data_source_optional_label_suffix.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/data_source_optional_label_suffix.scss
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/data_source_optional_label_suffix.test.tsx
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/data_source_optional_label_suffix.tsx
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/index.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_details_flyout.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/utils/associated_objects_tab_utils.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
  src/plugins/data_source_management/public/components/popover_button/popover_button.tsx
  src/plugins/data_source_management/public/components/toast_button/manage_data_source_button.tsx
  src/plugins/data_source_management/public/components/toast_button/reload_button.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/types.ts
  src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8483 Fix inconsistent i18n key names in workspace and examples
  changelogs/fragments/8483.yml
  examples/ui_actions_explorer/public/app.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
Labels: all-star-contributor

#8480 chore: Update oui to 1.15 and consume $ouiSideNavBackgroundColor
  changelogs/fragments/8480.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/variables.scss
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, look & feel, v2.18.0

#8484 [Workspace]Remove workspace name populate after use case selected
  changelogs/fragments/8484.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8322 [Enhancement] Keyboard shortcut for running queries
  changelogs/fragments/8322.yml
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, repeat-contributor, failed changeset, discover-next, v2.18.0

#8368 fix(queryEnhancements): data.search() should not ignore the `strategy` passed as parameter
  changelogs/fragments/8368.yml
  src/plugins/data/public/search/search_service.ts
Labels: backport 2.x, discover, all-star-contributor, discover-next

#8411 Add i18n checks to PR workflows
  .github/workflows/build_and_test_workflow.yml
  changelogs/fragments/8411.yml
  package.json
  src/dev/i18n/integrate_locale_files.ts
  src/dev/i18n/tasks/check_compatibility.ts
  src/dev/run_i18n_check.ts
  src/translations/de-DE.json
  src/translations/es-ES.json
  src/translations/fr-FR.json
  src/translations/ko-KR.json
  src/translations/tr-TR.json
  src/translations/zh-CN.json
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8423 Add precommit hook to validate i18n
  changelogs/fragments/8423.yml
  src/dev/i18n/extract_default_translations.d.ts
  src/dev/i18n/extractors/index.d.ts
  src/dev/i18n/index.ts
  src/dev/i18n/tasks/check_default_messages_in_files.ts
  src/dev/i18n/tasks/check_files_for_untracked_translations.ts
  src/dev/i18n/tasks/index.ts
  src/dev/i18n/utils/index.ts
  src/dev/i18n/utils/utils.js
  src/dev/precommit_hook/check_i18n.js
  src/dev/precommit_hook/index.js
  src/dev/run_precommit_hook.js
Labels: distinguished-contributor

#8486 [Workspace]Add WorkspaceCollaboratorTypesService and AddCollaboratorsModal
  changelogs/fragments/8486.yml
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/index.ts
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborator_input.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborator_input.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborators_panel.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborators_panel.tsx
  src/plugins/workspace/public/constants.ts
  src/plugins/workspace/public/index.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/register_default_collaborator_types.test.tsx
  src/plugins/workspace/public/register_default_collaborator_types.tsx
  src/plugins/workspace/public/services/index.ts
  src/plugins/workspace/public/services/workspace_collaborator_types_service.test.ts
  src/plugins/workspace/public/services/workspace_collaborator_types_service.ts
  src/plugins/workspace/public/types.ts
Labels: backport 2.x, all-star-contributor, workspace

#8490 Bump axios, chokidar, mocha, and elliptic
  changelogs/fragments/8490.yml
  package.json
  yarn.lock
Labels: v3.0.0, distinguished-contributor

#8503 Fix: pass hide local cluster flag to data source menu in sample data page
  changelogs/fragments/8503.yml
  src/plugins/home/public/application/components/tutorial_directory.js
Labels: backport 2.x, distinguished-contributor, workspace, look & feel

#8489 [navigation]feat: update border style when new left nav expanded
  changelogs/fragments/8489.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
Labels: backport 2.x, distinguished-contributor, workspace, look & feel

#8460 [Fix] Replace segmented button with tabs for OpenSearch connections and Direct query connections
  changelogs/fragments/8460.yml
  src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8481 Poll for results from frontend for async search
  changelogs/fragments/8481.yml
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/common/utils/helpers.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Labels: backport 2.x, valued-contributor, discover-next, v2.18.0

#8467 [Workspace] Refactor new home page
  changelogs/fragments/8467.yml
  src/plugins/home/public/plugin.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/assets/background_dark.svg
  src/plugins/workspace/public/assets/background_light.svg
  src/plugins/workspace/public/components/home_get_start_card/index.ts
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.scss
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.test.tsx
  src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/utils.test.ts
  src/plugins/workspace/public/components/workspace_initial/utils.ts
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.scss
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.test.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_use_case_card.test.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_use_case_card.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_use_case_card_gradient_variables.scss
  src/plugins/workspace/public/components/workspace_initial_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8516 [Manual backport 2.x] Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in dataSourceManagement plugin (#8394)
  changelogs/fragments/8394.yml
  src/plugins/data_source_management/public/components/breadcrumbs.ts
  src/plugins/data_source_management/public/components/constants.tsx
  src/plugins/data_source_management/public/components/create_button/__snapshots__/create_button.test.tsx.snap
  src/plugins/data_source_management/public/components/create_button/create_button.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
  src/plugins/data_source_management/public/components/data_source_error_menu/data_source_error_menu.tsx
  src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/__snapshots__/data_source_optional_label_suffix.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/data_source_optional_label_suffix.scss
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/data_source_optional_label_suffix.test.tsx
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/data_source_optional_label_suffix.tsx
  src/plugins/data_source_management/public/components/data_source_optional_label_suffix/index.ts
  src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_details_flyout.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/utils/associated_objects_tab_utils.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
  src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
  src/plugins/data_source_management/public/components/popover_button/popover_button.tsx
  src/plugins/data_source_management/public/components/toast_button/manage_data_source_button.tsx
  src/plugins/data_source_management/public/components/toast_button/reload_button.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/data_source_management/public/types.ts
  src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
Labels: i18n, failed changeset, v2.18.0

#8518 [manual backport 2.x] Add precommit hook to validate i18n (#8423)
  changelogs/fragments/8423.yml
  src/dev/i18n/extract_default_translations.d.ts
  src/dev/i18n/extractors/index.d.ts
  src/dev/i18n/index.ts
  src/dev/i18n/tasks/check_default_messages_in_files.ts
  src/dev/i18n/tasks/check_files_for_untracked_translations.ts
  src/dev/i18n/tasks/index.ts
  src/dev/i18n/utils/index.ts
  src/dev/i18n/utils/utils.js
  src/dev/precommit_hook/check_i18n.js
  src/dev/precommit_hook/index.js
  src/dev/run_precommit_hook.js
Labels: i18n, failed changeset, v2.18.0

#8497 Allow overriding the themeTag temporarily via the query-string
  packages/osd-ui-shared-deps/theme_config.d.ts
  packages/osd-ui-shared-deps/theme_config.js
  src/core/server/http/http_server.mocks.ts
  src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
  src/core/server/rendering/views/styles.tsx
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/ui_settings_config.ts
  src/legacy/ui/ui_render/bootstrap/template.js.hbs
  src/legacy/ui/ui_render/ui_render_mixin.js
Labels: v2.18.0

#8524 [Workspace]Analytics use case overview and essential use case overview crashed
  changelogs/fragments/8524.yml
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace

#8517 [Manual backport 2.x] Add i18n checks to PR workflows (#8411)
  .github/workflows/build_and_test_workflow.yml
  changelogs/fragments/8411.yml
  package.json
  src/dev/i18n/integrate_locale_files.ts
  src/dev/i18n/tasks/check_compatibility.ts
  src/dev/run_i18n_check.ts
  src/translations/de-DE.json
  src/translations/es-ES.json
  src/translations/fr-FR.json
  src/translations/ko-KR.json
  src/translations/tr-TR.json
  src/translations/zh-CN.json
Labels: i18n, autocut, failed changeset, v2.18.0

#8166 [Discover] UI Updates to Dataset Configurator
  changelogs/fragments/8166.yml
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/mocks.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, discover, seasoned-contributor, discover-next, v2.18.0

#8494 [Discover] support custom callback to combine multiple dataset selections
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor, discover-next, v2.18.0

#8501 [Workspace]feat: add collaborator table to workspace detail page
  changelogs/fragments/8501.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/__snapshots__/add_collaborator_button.test.tsx.snap
  src/plugins/workspace/public/components/workspace_form/__snapshots__/workspace_collaborator_table.test.tsx.snap
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.test.tsx
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
  src/plugins/workspace/public/constants.ts
Labels: backport 2.x, all-star-contributor, workspace

#8472 Switch OSD Optimizer to rely on file hashes instead of `mtime`s
  changelogs/fragments/8472.yml
  packages/osd-optimizer/src/common/bundle.test.ts
  packages/osd-optimizer/src/common/bundle.ts
  packages/osd-optimizer/src/integration_tests/bundle_cache.test.ts
  packages/osd-optimizer/src/node/cache.ts
  packages/osd-optimizer/src/node/node_auto_tranpilation.ts
  packages/osd-optimizer/src/optimizer/bundle_cache.ts
  packages/osd-optimizer/src/optimizer/cache_keys.test.ts
  packages/osd-optimizer/src/optimizer/cache_keys.ts
  packages/osd-optimizer/src/optimizer/get_hashes.test.ts
  packages/osd-optimizer/src/optimizer/get_hashes.ts
  packages/osd-optimizer/src/worker/run_compilers.ts
Labels: backport 2.x, repeat-contributor, infra, v2.18.0

#8530 Encode searchId as it tends to be decoded after adds into url
  changelogs/fragments/8530.yml
  src/plugins/visualizations/public/wizard/new_vis_modal.tsx
Labels: visualizations, backport 2.x, all-star-contributor, discover-next, v2.18.0

#8500 feat: introducing workspace level ui settings and hide non-global ui settings from advance settings page
  changelogs/fragments/8500.yml
  src/core/server/index.ts
  src/core/server/internal_types.ts
  src/core/server/legacy/legacy_service.test.ts
  src/core/server/legacy/legacy_service.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/server.ts
  src/core/server/workspace/index.ts
  src/core/server/workspace/mocks.ts
  src/core/server/workspace/workspace_service.ts
  src/core/types/ui_settings.ts
  src/plugins/advanced_settings/public/management_app/advanced_settings.tsx
  src/plugins/data/server/plugin.ts
  src/plugins/data/server/ui_settings.ts
Labels: backport 2.x, all-star-contributor, workspace

#8504 Allow hiding the TSVB axis for time series
  changelogs/fragments/8504.yml
  src/plugins/vis_type_timeseries/public/application/components/aggs/_agg_row.scss
  src/plugins/vis_type_timeseries/public/application/components/aggs/moving_average.js
  src/plugins/vis_type_timeseries/public/application/components/aggs/serial_diff.js
  src/plugins/vis_type_timeseries/public/application/components/aggs/top_hit.js
  src/plugins/vis_type_timeseries/public/application/components/panel_config/gauge.js
  src/plugins/vis_type_timeseries/public/application/components/panel_config/table.js
  src/plugins/vis_type_timeseries/public/application/components/panel_config/timeseries.js
  src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/config.js
  src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js
  src/plugins/vis_type_timeseries/public/application/visualizations/constants/chart.js
  src/plugins/vis_type_timeseries/public/metrics_type.ts
Labels: backport 2.x, tsvb, distinguished-contributor, v2.18.0

#8548 Hide Doc links for Unsupported Langauges
  src/plugins/discover/public/plugin.ts
Labels: backport 2.x, discover, Skip-Changelog, all-star-contributor, discover-next, v2.18.0

#8529 [Page Header] Update the title of recent menu
  changelogs/fragments/8529.yml
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, valued-contributor, look & feel

#8543 [Workspace] refactor: update workspace collaborator table UI
  changelogs/fragments/8543.yml
  src/plugins/workspace/public/assets/background_pic.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/__snapshots__/add_collaborator_button.test.tsx.snap
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8535 Implement correct normalization of locales in i18n
  packages/osd-i18n/src/core/i18n.test.ts
  packages/osd-i18n/src/core/i18n.ts
  packages/osd-i18n/src/core/locales.js
  packages/osd-i18n/src/loader.ts
  src/core/public/application/scoped_history.test.ts
  src/core/public/application/scoped_history.ts
  src/core/public/locale_helper.test.ts
  src/core/public/locale_helper.ts
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/legacy/ui/ui_render/ui_render_mixin.test.js
Labels: i18n, backport 2.x, distinguished-contributor, v2.18.0

#8561 [Manual backport 2.x] Implement correct normalization of locales in i18n (#8535)
  packages/osd-i18n/src/core/i18n.test.ts
  packages/osd-i18n/src/core/i18n.ts
  packages/osd-i18n/src/core/locales.js
  packages/osd-i18n/src/loader.ts
  src/core/public/application/scoped_history.test.ts
  src/core/public/application/scoped_history.ts
  src/core/public/locale_helper.test.ts
  src/core/public/locale_helper.ts
  src/core/public/osd_bootstrap.test.ts
  src/core/public/osd_bootstrap.ts
  src/core/server/rendering/rendering_service.test.ts
  src/core/server/rendering/rendering_service.tsx
  src/legacy/ui/ui_render/ui_render_mixin.js
  src/legacy/ui/ui_render/ui_render_mixin.test.js
Labels: i18n, failed changeset, v2.18.0

#8133 [Discover] Adding Recent Datasets
  src/plugins/data/common/constants.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
  src/plugins/data/public/query/types.ts
  src/plugins/data/public/ui/dataset_selector/dataset_selector.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/server/ui_settings.ts
Labels: backport 2.x, discover, seasoned-contributor, discover-next, v2.18.0

#8352 Add discover summary error info and button click logic enhancement
  changelogs/fragments/8352.yml
  src/plugins/query_enhancements/common/query_assist/index.ts
  src/plugins/query_enhancements/common/query_assist/types.ts
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: backport 2.x, discover, repeat-contributor, failed changeset, discover-next, v2.18.0

#8545 Refactor workspace datasource association
  changelogs/fragments/8545.yml
  src/core/public/index.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/types.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/workspace/public/components/data_source_association/data_source_association.test.tsx
  src/plugins/workspace/public/components/data_source_association/data_source_association.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, all-star-contributor, workspace

#8554 [Workspace] Fix new home page small screen display issues
  changelogs/fragments/8554.yml
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.scss
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_use_case_card.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8540 [Workspace]Replace connections copy with data sources
  changelogs/fragments/8540.yml
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8564 chore: Update oui to 1.16
  changelogs/fragments/8564.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, look & feel, v2.18.0

#8570 [Workspace] Fix workspace update issue
  changelogs/fragments/8570.yml
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8574 [Workspace]Show add collaborators modal until collaborators added
  changelogs/fragments/8574.yml
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.tsx
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8541 [workspace]fix the workspace selector jump that occurs when hovering and clicking.
  changelogs/fragments/8541.yml
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
Labels: backport 2.x, valued-contributor, workspace

#8538 [Workspace] Add global search bar into left nav
  changelogs/fragments/8538.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/global_search/global_search_service.test.ts
  src/core/public/chrome/global_search/global_search_service.ts
  src/core/public/chrome/global_search/index.ts
  src/core/public/chrome/index.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_search_bar.test.tsx
  src/core/public/chrome/ui/header/header_search_bar.tsx
  src/core/public/index.ts
  src/core/utils/default_nav_groups.ts
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dev_tools/opensearch_dashboards.json
  src/plugins/dev_tools/public/application.tsx
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/dev_tools/public/global_search/__snapshots__/search_devtool_command.test.tsx.snap
  src/plugins/dev_tools/public/global_search/search_devtool_command.test.tsx
  src/plugins/dev_tools/public/global_search/search_devtool_command.tsx
  src/plugins/dev_tools/public/plugin.test.ts
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/workspace/public/components/global_search/page_item.test.tsx
  src/plugins/workspace/public/components/global_search/page_item.tsx
  src/plugins/workspace/public/components/global_search/search_pages_command.test.tsx
  src/plugins/workspace/public/components/global_search/search_pages_command.tsx
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, all-star-contributor, workspace

#8569 [workspace]add last admin validation when deleting collaborators
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
Labels: backport 2.x, valued-contributor, workspace

#8544 [Datasource management] Direct query connections fit and finish fixes
  changelogs/fragments/8544.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/data_source_management/public/management_app/mount_management_section.tsx
Labels: backport 2.x, repeat-contributor

#8562 Handle Server Side Errors
  src/plugins/data/server/dql_telemetry/route.ts
  src/plugins/vis_type_timeseries/server/lib/timeseries_visualization_client_wrapper.ts
Labels: backport 2.x, Skip-Changelog, all-star-contributor, discover-next, v2.18.0

#8581 [Workspace] Disable copy all button when there is no saved objects in assets page
  changelogs/fragments/8581.yml
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8531 [Workspace]Display duplicate collaborators error in add collaborators modal
  changelogs/fragments/8531.yml
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/duplicate_collaborator_error.ts
  src/plugins/workspace/public/components/add_collaborators_modal/index.ts
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborator_input.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborator_input.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborators_panel.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborators_panel.tsx
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.test.tsx
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8537 [MDS] Mute the non-mds endpoints for direct query data connections
  changelogs/fragments/8537.yml
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/server/routes/data_connections_router.ts
  src/plugins/data_source_management/server/routes/index.ts
Labels: backport 2.x, valued-contributor

#8563 Bump axios, chokidar, mocha, and elliptic #8490
  changelogs/fragments/8490.yml
  package.json
  yarn.lock
Labels: cve, failed changeset, v2.18.0

#8603 Upgrade JSON11 from 1.1.2 to 2.0.0
  changelogs/fragments/8603.yml
  package.json
  packages/osd-std/package.json
  yarn.lock
Labels: backport 2.x, distinguished-contributor, v2.18.0

#8513 Add SearchOnLoad Preference for dataset
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: discover, Skip-Changelog, all-star-contributor, discover-next, v2.18.0

#8607 [Workspace] Limit workspace colors
  changelogs/fragments/8607.yml
  src/plugins/workspace/public/components/workspace_creator/creator_details_panel.tsx
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx
Labels: backport 2.x, seasoned-contributor, workspace

#8594 [Workspace] feat: add workspace collaborators page
  changelogs/fragments/8594.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/__snapshots__/workspace_collaborators_app.test.tsx.snap
  src/plugins/workspace/public/components/workspace_collaborators/__snapshots__/workspace_collaborators.test.tsx.snap
  src/plugins/workspace/public/components/workspace_collaborators/workspace_collaborators.test.tsx
  src/plugins/workspace/public/components/workspace_collaborators/workspace_collaborators.tsx
  src/plugins/workspace/public/components/workspace_collaborators_app.test.tsx
  src/plugins/workspace/public/components/workspace_collaborators_app.tsx
  src/plugins/workspace/public/components/workspace_form/__snapshots__/workspace_collaborator_table.test.tsx.snap
  src/plugins/workspace/public/components/workspace_form/add_collaborator_button.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: backport 2.x, all-star-contributor, workspace

#8619 [Workspace] fine-tune workspace list page compressed style to align with compressed table
  changelogs/fragments/8619.yml
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8617 [Workspace] Update default workspace permission and users config support wildcard
  changelogs/fragments/8617.yml
  config/opensearch_dashboards.yml
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8615 [Workspace] Refactor workspace detail page
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
  src/plugins/workspace/public/components/data_source_association/data_source_association.test.tsx
  src/plugins/workspace/public/components/data_source_association/data_source_association.tsx
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_form_content.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_panel.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
  src/plugins/workspace/public/components/workspace_initial/workspace_use_case_card.tsx
  src/plugins/workspace/public/components/workspace_list/__snapshots__/default_workspace.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace

#8606 [Workspace] Fix content management render dashboard with duplicate visualizations
  changelogs/fragments/8606.yml
  src/plugins/content_management/public/components/section_input.test.ts
  src/plugins/content_management/public/components/section_input.ts
Labels: backport 2.x, all-star-contributor, workspace

#8624 feat(contentManagement): expose page API to allow remove section
  changelogs/fragments/8624.yml
  src/plugins/content_management/public/components/section_render.tsx
  src/plugins/content_management/public/plugin.ts
  src/plugins/content_management/public/services/content_management/page.test.ts
  src/plugins/content_management/public/services/content_management/page.ts
  src/plugins/content_management/public/types.ts
Labels: backport 2.x, all-star-contributor, workspace

#8600 fix: Fix padding and responsive behavior of page header
  changelogs/fragments/8600.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.scss
  src/core/public/chrome/ui/header/header.tsx
Labels: backport 2.x, seasoned-contributor, look & feel, v2.18.0

#8598 Move DatasetSelector from data plugin queryString comp to DataExplorer
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/application/components/sidebar/lib/get_index_pattern_field_list.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor

#8592 [workspace]Fix workspace selector style alignment
  changelogs/fragments/8592.yml
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
Labels: backport 2.x, valued-contributor, workspace

#8640 chore: Update oui to 1.17
  changelogs/fragments/8640.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, look & feel, v2.18.0

#8614 fix: Update content and styling of use case getting started cards
  changelogs/fragments/8614.yml
  src/plugins/home/public/application/components/sample_data/sample_data_card.test.tsx
  src/plugins/home/public/application/components/sample_data/sample_data_card.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.test.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.tsx
  src/plugins/workspace/public/components/use_case_overview/get_started_cards.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.scss
  src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx
Labels: backport 2.x, seasoned-contributor, look & feel, v2.18.0

#8620 [Workspace] add data-connection type support for association modal
  changelogs/fragments/8620.yml
  src/plugins/workspace/public/components/data_source_association/data_source_association.test.tsx
  src/plugins/workspace/public/components/data_source_association/data_source_association.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8641 [Workspace]Response forbidden error for not permitted workspace
  changelogs/fragments/8641.yml
  src/plugins/home/server/services/sample_data/routes/install.test.ts
  src/plugins/home/server/services/sample_data/routes/install.ts
Labels: backport 2.x, all-star-contributor, workspace

#8621 [workspace]add admin validation when changing the last administrator to a lesser access
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
Labels: backport 2.x, valued-contributor, workspace

#8604 [Workspace]Disable confirm button during collaborators operation
  changelogs/fragments/8604.yml
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8648 [Workspace] Workspace assets page crashed after library_write permission revoked
  changelogs/fragments/8648.yml
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8651 Update Discover appearance
  changelogs/fragments/8651.yml
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/data_explorer/public/components/sidebar/index.scss
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/discover/public/application/components/chart/_histogram.scss
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/_table_header.scss
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/navigation/public/top_nav_menu/_index.scss
Labels: backport 2.x, discover, distinguished-contributor, discover-next, v2.18.0

#8555 [Async search Discover] Poll for results when current request completes
  changelogs/fragments/8555.yml
  src/plugins/data/common/utils/helpers.ts
Labels: valued-contributor, discover-next

#8601 Fix Queries of Unsupported types appearing on Visualize & Vis Builder Search Bar
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/query/types.ts
  src/plugins/data/public/services.ts
Labels: backport 2.x, Skip-Changelog, discover-next, v2.18.0

#8636 Fix Documentation for various languages in Discover
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/query_string/index.ts
  src/plugins/data/public/query/query_string/language_service/index.ts
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/language_service/lib/default_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/lib/dql_language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/lib/index.ts
  src/plugins/data/public/query/query_string/language_service/lib/language_reference.tsx
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language_reference.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_editor/flyout_containers.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/dedup.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/eval.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/fields.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/head.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/parse.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/rare.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/rename.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/search.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/sort.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/stats.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/syntax.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/top.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/commands/where.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/condition.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/datetime.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/full_text_search.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/math.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/functions/string.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/groups.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/datatypes.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/identifiers.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/language_structure/index.ts
  src/plugins/query_enhancements/public/query_editor/ppl_docs/overview.tsx
  src/plugins/query_enhancements/public/query_editor/ppl_reference_flyout.tsx
  src/plugins/query_enhancements/public/query_editor/query_language_reference.tsx
  src/plugins/query_enhancements/public/query_editor/sql_reference_flyout.tsx
  src/plugins/query_enhancements/public/query_editor_extensions/index.ts
  src/plugins/query_enhancements/public/query_editor_extensions/ppl_language_reference.tsx
  src/plugins/query_enhancements/public/query_editor_extensions/sql_language_reference.tsx
Labels: backport 2.x, discover, Skip-Changelog, discover-next, v2.18.0

#8613 Improve Empty State Handling: Add No Index Patterns Panel with Data Selection in Discover View
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/ui/_common.scss
  src/plugins/data/public/ui/_index.scss
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/no_index_patterns/index.ts
  src/plugins/data/public/ui/no_index_patterns/no_index_patterns_panel.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
  src/plugins/data_explorer/public/utils/state_management/redux_persistence.test.tsx
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, discover-next, v2.18.0

#8616 [Discover]Sample Queries and Saved Queries in No Results Page
  changelogs/fragments/8616.yml
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/ui/_common.scss
  src/plugins/discover/public/application/components/no_results/no_results.scss
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, discover, seasoned-contributor, discover-next, v2.18.0

#8659 [bug] Discover UI stuck on searching after deleting index pattern
  changelogs/fragments/8659.yml
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
Labels: backport 2.x, discover, distinguished-contributor, discover-next, v2.18.0

#8587 [WIP] Add support for otel sample data - logs, traces and metrics
  changelogs/fragments/8587.yml
  src/plugins/home/public/application/components/__snapshots__/sample_data_view_data_button.test.js.snap
  src/plugins/home/public/application/components/sample_data_set_card.js
  src/plugins/home/public/application/components/sample_data_view_data_button.js
  src/plugins/home/public/application/components/sample_data_view_data_button.test.js
  src/plugins/home/public/assets/sample_data_resources/otel/otel_traces.png
  src/plugins/home/public/assets/sample_data_resources/otel/otel_traces_dark.png
  src/plugins/home/public/assets/sample_data_resources/otel/otel_traces_dark_new.png
  src/plugins/home/public/assets/sample_data_resources/otel/otel_traces_new.png
  src/plugins/home/server/services/sample_data/data_sets/otel/index.ts
  src/plugins/home/server/services/sample_data/data_sets/otel/logs_field_mappings.ts
  src/plugins/home/server/services/sample_data/data_sets/otel/metrics_field_mappings.ts
  src/plugins/home/server/services/sample_data/data_sets/otel/sample_logs.json.gz
  src/plugins/home/server/services/sample_data/data_sets/otel/sample_metrics.json.gz
  src/plugins/home/server/services/sample_data/data_sets/otel/sample_service_map.json.gz
  src/plugins/home/server/services/sample_data/data_sets/otel/sample_traces.json.gz
  src/plugins/home/server/services/sample_data/data_sets/otel/services_field_mappings.ts
  src/plugins/home/server/services/sample_data/data_sets/otel/traces_field_mappings.ts
  src/plugins/home/server/services/sample_data/data_sets/util.test.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
  src/plugins/home/server/services/sample_data/lib/create_index_name.test.ts
  src/plugins/home/server/services/sample_data/lib/create_index_name.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_schema.ts
  src/plugins/home/server/services/sample_data/routes/install.ts
  src/plugins/home/server/services/sample_data/routes/list.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.ts
  src/plugins/home/server/services/sample_data/sample_data_registry.ts
Labels: backport 2.x, repeat-contributor

#8663 [Manual backport 2.x] [Discover]Sample Queries and Saved Queries in No Results Page #8616
  changelogs/fragments/8616.yml
  changelogs/fragments/8651.yml
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/ui/_common.scss
  src/plugins/data/public/ui/_index.scss
  src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/no_index_patterns/index.ts
  src/plugins/data/public/ui/no_index_patterns/no_index_patterns_panel.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_string_input/_query_bar.scss
  src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
  src/plugins/data_explorer/public/components/app_container.scss
  src/plugins/data_explorer/public/components/sidebar/index.scss
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
  src/plugins/data_explorer/public/utils/state_management/redux_persistence.test.tsx
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/discover/public/application/components/chart/_histogram.scss
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.tsx
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
  src/plugins/discover/public/application/components/default_discover_table/_table_header.scss
  src/plugins/discover/public/application/components/no_results/no_results.scss
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
  src/plugins/navigation/public/top_nav_menu/_index.scss
  src/plugins/query_enhancements/public/datasets/s3_type.ts
  src/plugins/query_enhancements/public/plugin.tsx
Labels: discover, failed changeset, discover-next, v2.18.0

#8665 [bug] address different issues with dataset selector
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
  src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/ui/_index.scss
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/no_index_patterns/index.ts
  src/plugins/data/public/ui/no_index_patterns/no_index_patterns_panel.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
  src/plugins/data_explorer/public/utils/state_management/redux_persistence.test.tsx
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.scss
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, discover-next, v2.18.0

#8650 Fix random big number during loading in query editor result
  changelogs/fragments/8650.yml
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
Labels: distinguished-contributor

#8668 Fix No data selected appearance
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.scss
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: discover, Skip-Changelog, distinguished-contributor, discover-next, v2.18.0

#8492 Update Observability Data Sources with Type and Redirection
  changelogs/fragments/8492.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_details_flyout.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_util.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_utils.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_details_flyout.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_details_flyout.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/utils/associated_objects_tab_utils.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/utils/associated_objects_tab_utils.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
  src/plugins/data_source_management/public/plugin.ts
Labels: backport 2.x, valued-contributor, v2.18.0

#8670 [Mnaual backport 2.x] Combined #8598, #8651, #8613, #8616, #8659, #8665, #8650, #8668
  changelogs/fragments/8650.yml
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
  src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/data/public/ui/_index.scss
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/no_index_patterns/index.ts
  src/plugins/data/public/ui/no_index_patterns/no_index_patterns_panel.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
  src/plugins/data/public/ui/search_bar/create_search_bar.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/public/ui/ui_service.ts
  src/plugins/data_explorer/public/components/app_container.tsx
  src/plugins/data_explorer/public/components/sidebar/index.tsx
  src/plugins/data_explorer/public/index.ts
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
  src/plugins/data_explorer/public/utils/state_management/redux_persistence.test.tsx
  src/plugins/data_explorer/public/utils/state_management/store.ts
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.scss
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.tsx
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/discover/public/application/components/sidebar/lib/get_index_pattern_field_list.ts
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/query_enhancements/public/plugin.tsx
Labels: failed changeset

#8674 fix: fixed unsupported language issue due to cached language in localStorage
  changelogs/fragments/8674.yml
  src/plugins/data/public/query/query_string/query_string_manager.ts
Labels: backport 2.x, all-star-contributor

#8609 Add support for s3 fields in discover
  changelogs/fragments/8609.yml
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
  src/plugins/data/common/index_patterns/types.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
  src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/public/datasets/s3_type.test.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: repeat-contributor, discover-next, v2.18.0

#8682 Add data test subject for discover cypress test
  changelogs/fragments/8682.yml
  src/plugins/data/public/query/query_string/language_service/lib/language_reference.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.tsx
Labels: distinguished-contributor

#8649 [workspace] update search bar layout and align workspace selector
  changelogs/fragments/8649.yml
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/header_search_bar.test.tsx
  src/core/public/chrome/ui/header/header_search_bar.tsx
  src/plugins/workspace/public/components/global_search/page_item.tsx
  src/plugins/workspace/public/components/global_search/search_pages_command.tsx
Labels: backport 2.x, all-star-contributor, workspace, v2.18.0

#8685 [discover] optimize rendering language options
  src/plugins/data/public/ui/query_editor/language_selector.tsx
Labels: backport 2.x, discover, distinguished-contributor, failed changeset, discover-next, v2.18.0

#8565 [Discover] Add Footer Bar for Single Line Editor
  changelogs/fragments/8565.yml
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/common/utils/helpers.ts
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Labels: backport 2.x, discover, seasoned-contributor, discover-next, v2.18.0

#8689 [bug] set saved search instance for Discover based on dataset
  src/plugins/data/common/search/search_source/create_search_source.ts
  src/plugins/data/public/index.ts
  src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, discover, discover-next, v2.18.0

#8693 [Sample data] Update otel sample data description
  changelogs/fragments/8693.yml
  src/plugins/home/server/services/sample_data/data_sets/otel/index.ts
Labels: backport 2.x, repeat-contributor, v2.18.0

#8694 [CI] Adding Missing Snapshot for `query_result.test.tsx`
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
Labels: discover, Skip-Changelog, seasoned-contributor, v2.18.0

#8691 [2.x-manual-backport][Discover] Add Footer Bar for Single Line Editor (#8565)
  changelogs/fragments/8565.yml
  src/plugins/data/common/data_frames/types.ts
  src/plugins/data/common/utils/helpers.ts
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/_recent_query.scss
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Labels: failed changeset, v2.18.0

#8469 Saved queries new UI
  changelogs/fragments/8469.yml
  config/opensearch_dashboards.yml
  src/plugins/data/config.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/saved_query/saved_query_service.test.ts
  src/plugins/data/public/query/saved_query/saved_query_service.ts
  src/plugins/data/public/query/saved_query/types.ts
  src/plugins/data/public/services.ts
  src/plugins/data/public/ui/_index.scss
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_flyouts/save_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_flyouts/saved_query_card.tsx
  src/plugins/data/public/ui/saved_query_flyouts/saved_query_flyouts.scss
  src/plugins/data/public/ui/saved_query_form/helpers.tsx
  src/plugins/data/public/ui/saved_query_form/index.ts
  src/plugins/data/public/ui/saved_query_form/save_query_form.tsx
  src/plugins/data/public/ui/saved_query_management/delete_saved_query_confirmation_modal.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_list_item.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.test.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/server/index.ts
  src/plugins/data/server/saved_objects/query.ts
Labels: backport 2.x, valued-contributor, discover-next, v2.19.0

#8705 [Backport 2.x] Saved queries new UI (#8469)
  changelogs/fragments/8469.yml
  config/opensearch_dashboards.yml
  src/plugins/data/config.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query/query_service.ts
  src/plugins/data/public/query/saved_query/saved_query_service.test.ts
  src/plugins/data/public/query/saved_query/saved_query_service.ts
  src/plugins/data/public/query/saved_query/types.ts
  src/plugins/data/public/services.ts
  src/plugins/data/public/ui/_index.scss
  src/plugins/data/public/ui/filter_bar/filter_options.tsx
  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_flyouts/save_query_flyout.tsx
  src/plugins/data/public/ui/saved_query_flyouts/saved_query_card.tsx
  src/plugins/data/public/ui/saved_query_flyouts/saved_query_flyouts.scss
  src/plugins/data/public/ui/saved_query_form/helpers.tsx
  src/plugins/data/public/ui/saved_query_form/index.ts
  src/plugins/data/public/ui/saved_query_form/save_query_form.tsx
  src/plugins/data/public/ui/saved_query_management/delete_saved_query_confirmation_modal.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_list_item.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.test.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
  src/plugins/data/public/ui/search_bar/search_bar.tsx
  src/plugins/data/server/index.ts
  src/plugins/data/server/saved_objects/query.ts
Labels: failed changeset

#8709 [workspace]fix: make goto router support workspace
  changelogs/fragments/8709.yml
  src/core/server/index.ts
  src/plugins/share/server/routes/goto.ts
Labels: backport 2.x, distinguished-contributor, workspace, v2.18.0

#8708 [Discover] Modify the search bar info box content for sql/ppl
  changelogs/fragments/8708.yml
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/language_reference.test.tsx
  src/plugins/data/public/query/query_string/language_service/lib/language_reference.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_editor_extensions/ppl_language_reference.tsx
  src/plugins/query_enhancements/public/query_editor_extensions/sql_language_reference.tsx
Labels: backport 2.x, valued-contributor, v2.19.0

#8713 [Enhancement] Update auto-complete-api-with-mds
  changelogs/fragments/8713.yml
  src/plugins/data/public/autocomplete/providers/value_suggestion_provider.ts
  src/plugins/data/server/autocomplete/value_suggestions_route.ts
Labels: backport 2.x, repeat-contributor, failed changeset, v2.19.0

#8720 Revert "[workspace]fix: make goto router support workspace"
  changelogs/fragments/8709.yml
  src/core/server/index.ts
  src/plugins/share/server/routes/goto.ts
Labels: distinguished-contributor, failed changeset

#8719 fix: generate short url with workspace info
  changelogs/fragments/8719.yml
  src/core/server/index.ts
  src/plugins/share/public/services/share_menu_manager.tsx
  src/plugins/share/server/routes/lib/short_url_assert_valid.test.ts
  src/plugins/share/server/routes/lib/short_url_assert_valid.ts
Labels: backport 2.x, distinguished-contributor, workspace

#8725 Update connections API error handling to use 503 for service unavailability
  src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.19.0

#8726 [Discover] use consistent icon for query assist feature
  src/plugins/query_enhancements/public/assets/query_assist_mark.svg
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_input.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, discover, Skip-Changelog, seasoned-contributor

#8723 Update QueryHistory to use sessionStorage
  src/plugins/data/public/query/query_string/query_history.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
Labels: backport 2.x, discover, Skip-Changelog, distinguished-contributor, discover-next, v2.18.0

#8680 [Workspace] Refactor: update change access modal display name
  changelogs/fragments/8680.yml
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
Labels: backport 2.x, all-star-contributor, workspace

#8712 [discover] query editor and language selector state fixes
  changelogs/fragments/8712.yml
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/configurator.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data/public/ui/query_editor/language_selector.test.tsx
  src/plugins/data/public/ui/query_editor/language_selector.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, distinguished-contributor, discover-next, v2.18.0

#8707 [BUG][Discover] Ensure save query loaded properly from asset
  changelogs/fragments/8707.yml
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: bug, backport 2.x, discover, distinguished-contributor

#8724 fixed ppl polling; save dataset in saved queries
  changelogs/fragments/8724.yml
  src/plugins/data/public/query/saved_query/saved_query_service.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Labels: backport 2.x, valued-contributor, v2.19.0

#8743 [Discover] fix error handling in query enhancement facet
  changelogs/fragments/8743.yml
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
  src/plugins/query_enhancements/server/utils/facet.ts
Labels: backport 2.x, discover, all-star-contributor, discover-next, v2.18.0

#8755 [Discover] Prevent wrapping of time fields
  changelogs/fragments/8755.yml
  src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
Labels: backport 2.x, distinguished-contributor, v2.18.0, backport 2.18

#8747 [2.x Manual Backport] Follow up on 8723 comment (#8733)
  src/plugins/data/public/query/query_string/query_history.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
Labels: Skip-Changelog, v2.18.0

#8742 [CVE-2024-48948] Bump `elliptic` from 6.5.7 to 6.6.0
  changelogs/fragments/8742.yml
  yarn.lock
Labels: cve, backport 2.x, distinguished-contributor, v2.18.0, backport 2.18

#8752 [Discover] add sample queries for PPL
  src/plugins/discover/public/application/components/no_results/no_results.tsx
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, Skip-Changelog, all-star-contributor, v2.18.0, backport 2.18
