Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-08, with the labels that each got.

#10308 [Left nav]Revert left navigation changes
  changelogs/fragments/10021.yml
  changelogs/fragments/10132.yml
  changelogs/fragments/10240.yml
  changelogs/fragments/10271.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/shared_links.spec.js
  cypress/utils/commands.js
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_groups.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/simple_popover.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_help_menu.test.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/chrome/ui/header/left_bottom_action_button.scss
  src/core/public/chrome/ui/header/left_bottom_action_button.test.tsx
  src/core/public/chrome/ui/header/left_bottom_action_button.tsx
  src/core/public/chrome/ui/header/simple_popover.test.tsx
  src/core/public/chrome/ui/header/simple_popover.tsx
  src/core/public/chrome/ui/index.ts
  src/core/public/index.ts
  src/core/utils/default_app_categories.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dev_tools/public/dev_tools_icon.scss
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/dev_tools/public/dev_tools_modal.test.tsx
  src/plugins/dev_tools/public/dev_tools_modal.tsx
  src/plugins/dev_tools/public/plugin.test.ts
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/discover/public/plugin.ts
  src/plugins/home/public/application/components/home_icon.test.tsx
  src/plugins/home/public/application/components/home_icon.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/management/public/components/settings_icon.tsx
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: Skip-Changelog, distinguished-contributor

#10174 [Explore] Add empty state component when no rule matched
  src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_empty_state.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
Labels: Skip-Changelog, seasoned-contributor

#10322 [TEST] Fix cigroup 12 and 15
  changelogs/fragments/10322.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/recent_queries.spec.js
  src/plugins/explore/public/components/top_nav/utils/validate_time_range.test.ts
Labels: distinguished-contributor

#10309 [Workspace]bug fix: ValidationError in ui setting
  changelogs/fragments/10309.yml
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: distinguished-contributor

#10262 [Query Enhancements] improve resources API type definition
  src/plugins/query_enhancements/server/routes/resources/routes.test.ts
  src/plugins/query_enhancements/server/routes/resources/routes.ts
Labels: Skip-Changelog, distinguished-contributor

#10321 [Explore] Implement bidirectional URL-Redux synchronization (fixed conflicts)
  changelogs/fragments/10313.yml
  changelogs/fragments/10321.yml
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.ts
  src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.ts
  src/plugins/explore/public/application/utils/state_management/actions/export_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/meta/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/meta/meta_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/meta/meta_slice.ts
  src/plugins/explore/public/application/utils/state_management/store.test.ts
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/application/utils/state_management/utils/state_comparison.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/state_comparison.ts
Labels: distinguished-contributor

#10189 [Explore] Log patterns container
  src/plugins/explore/public/application/register_tabs.ts
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/application/utils/state_management/actions/export_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/patterns_table/patterns_container.test.tsx
  src/plugins/explore/public/components/patterns_table/patterns_container.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table.stories.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table.test.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table_columns.test.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table_columns.tsx
  src/plugins/explore/public/components/patterns_table/utils/constants.ts
  src/plugins/explore/public/components/patterns_table/utils/patterns_table.stubs.ts
  src/plugins/explore/public/components/patterns_table/utils/utils.test.tsx
  src/plugins/explore/public/components/patterns_table/utils/utils.tsx
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.stories.tsx
  src/plugins/explore/public/components/tabs/action_bar/patterns_settings/patterns_settings_popover_button.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/patterns_settings/patterns_settings_popover_button.tsx
  src/plugins/explore/public/components/tabs/action_bar/patterns_settings/patterns_settings_popover_content.scss
  src/plugins/explore/public/components/tabs/action_bar/patterns_settings/patterns_settings_popover_content.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/patterns_settings/patterns_settings_popover_content.tsx
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.tsx
  src/plugins/explore/public/components/top_nav/query_execution_button/query_execution_button.test.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.test.tsx
  src/plugins/explore/public/services/tab_registry/tab_registry_service.ts
Labels: seasoned-contributor

#10323 [Explore] fix: correctly update time filter when loading save query
  changelogs/fragments/10323.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js
  src/plugins/explore/public/components/query_panel/query_panel_widgets/save_query/save_query.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/save_query/save_query.tsx
Labels: distinguished-contributor

#10317 [Explore] Add cypress test for chart type and field selectors
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/build_vis.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/vis_type_switch.spec.js
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
Labels: Skip-Changelog, all-star-contributor

#10328 [Explore] fixed linting error of new discover state of tab slice
  changelogs/fragments/10328.yml
  src/plugins/explore/public/application/utils/state_management/utils/state_comparison.test.ts
  yarn.lock
Labels: distinguished-contributor

#10314 [TEST] Fix shared links for PPL in explore
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/shared_links.spec.js
Labels: distinguished-contributor

#10332 [Explore] Fix New button URL state management issue
  changelogs/fragments/10332.yml
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.test.ts
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.ts
Labels: distinguished-contributor

#10270 [Banner Plugin] Support New UI with no overlap
  changelogs/fragments/10270.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/header.scss
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/core_system.test.ts
  src/core/public/core_system.ts
  src/core/public/rendering/app_containers.tsx
  src/core/public/rendering/rendering_service.tsx
  src/plugins/banner/public/index.scss
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: repeat-contributor, banner

#10333 Fix PPL query millisecond precision in date filtering
  changelogs/fragments/10333.yml
  src/plugins/query_enhancements/common/utils.test.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/search/filters/filter_utils.test.ts
Labels: distinguished-contributor

#10336 [Explore] Fix query execution button issue when use using date picker quick selections
  changelogs/fragments/10336.yml
  src/plugins/explore/public/components/top_nav/top_nav.tsx
Labels: distinguished-contributor

#10337 [Explore] Refactor generated query to have max height and scrollable
  changelogs/fragments/10337.yml
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.scss
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.tsx
Labels: distinguished-contributor

#10334 [Explore] change query language UI
  changelogs/fragments/10334.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/ai_editor.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/language_specific_display.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_ui.spec.js
  src/plugins/explore/public/components/query_panel/query_panel_editor/query_panel_editor.scss
  src/plugins/explore/public/components/query_panel/query_panel_editor/query_panel_editor.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_editor/query_panel_editor.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/index.ts
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.scss
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/ppl_reference/index.ts
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/ppl_reference/ppl_reference.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/ppl_reference/ppl_reference.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/ppl_reference/ppl_reference.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_toggle/language_toggle.scss
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_toggle/language_toggle.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_toggle/language_toggle.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/selected_language/selected_language.scss
  src/plugins/explore/public/components/query_panel/query_panel_widgets/selected_language/selected_language.tsx
Labels: distinguished-contributor

#10345 Fix: Discover plugin shows empty page instead of no-index-patterns UI when no index patterns
  changelogs/fragments/10345.yml
  src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
Labels: distinguished-contributor

#10311 [Explore] Fix Legend Visibility Logic for Visualizations
  changelogs/fragments/10311.yml
  src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
Labels: repeat-contributor

#10347 [Explore] add tooltip to language reference and don't throw error
  changelogs/fragments/10347.yml
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.scss
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.tsx
Labels: distinguished-contributor, explore

#10360 [Explore] add error boundary to tab content
  changelogs/fragments/10360.yml
  src/plugins/explore/public/components/tabs/tabs.tsx
Labels: distinguished-contributor

#10357 [Explore] fix url state not properly synced with saved search
  changelogs/fragments/10357.yml
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.ts
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/components/top_nav/top_nav.tsx
  src/plugins/explore/public/components/visualizations/add_to_dashboard_button.tsx
  src/plugins/explore/public/helpers/save_explore.ts
Labels: distinguished-contributor

#10355 [Traces] Update for datasets, redirection, and accordion timeline
  changelogs/fragments/10355.yml
  packages/osd-stylelint-config/config/global_selectors.json
  src/plugins/explore/public/application/pages/traces/trace_details/public/gantt_chart_vega/gantt_chart_vega.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/gantt_chart_vega/gantt_constants.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/top_nav_buttons.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_panel.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_panel.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_helpers.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_helpers.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_trace.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_trace.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/state/trace_app_state.test.ts
  src/plugins/explore/public/application/pages/traces/trace_details/state/trace_app_state.ts
  src/plugins/explore/public/application/pages/traces/trace_details/trace_view.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/trace_view.tsx
  src/plugins/explore/public/components/data_table/tabe_cell/table_cell.test.tsx
  src/plugins/explore/public/components/data_table/tabe_cell/table_source_cell.scss
  src/plugins/explore/public/components/data_table/table_cell/table_cell.scss
  src/plugins/explore/public/components/data_table/table_cell/table_cell.test.tsx
  src/plugins/explore/public/components/data_table/table_cell/table_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/table_source_cell.scss
  src/plugins/explore/public/components/data_table/table_cell/table_source_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.scss
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.test.tsx
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.tsx
  src/plugins/explore/public/components/data_table/table_row/table_row.test.tsx
  src/plugins/explore/public/components/data_table/table_row/table_row.tsx
  src/plugins/explore/public/components/doc_viewer/trace_details_view/trace_details_view.scss
  src/plugins/explore/public/components/doc_viewer/trace_details_view/trace_details_view.tsx
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/public/utils/trace_field_constants.ts
Labels: repeat-contributor, explore

#9805 [workspace] fix default data source not set when re-associating after deletion
  changelogs/fragments/9805.yml
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/data_source_table/use_data_source_updater.test.ts
  src/plugins/data_source_management/public/components/data_source_table/use_data_source_updater.ts
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/index.ts
  src/plugins/workspace/public/components/data_source_association/data_source_association.tsx
Labels: all-star-contributor

#10363 Fix Error Highlighting after switching languages
  changelogs/fragments/10363.yml
  packages/osd-monaco/src/ppl/language.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/editor_options/query_editor_options.ts
Labels: distinguished-contributor

#10366 [Explore] reset legacy state when changing dataset
  changelogs/fragments/10366.yml
  src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/index.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.ts
  src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
Labels: distinguished-contributor

#10325 [Banner Plugin] Add cache for banner hide
  changelogs/fragments/10325.yml
  src/plugins/banner/public/components/global_banner.tsx
Labels: repeat-contributor, banner

#10370 [Explore] Allow Refresh to run query
  changelogs/fragments/10370.yml
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.ts
Labels: distinguished-contributor

#10369 [Explore] Resolve ScopedHistory navigation scope error in explore plugin
  changelogs/fragments/10369.yml
  src/plugins/explore/public/components/visualizations/visualization_builder.test.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.ts
  src/plugins/explore/public/plugin.ts
Labels: distinguished-contributor

#10365 [Explore] update discover visualization empty state
  changelogs/fragments/10365.yml
  src/plugins/explore/public/components/visualizations/visualization_empty_state.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
Labels: distinguished-contributor

#10362 [Explore] Introduce facet filter
  changelogs/fragments/10362.yml
  src/plugins/explore/public/components/fields_selector/discover_sidebar.scss
  src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.tsx
  src/plugins/explore/public/components/fields_selector/facet_field.test.tsx
  src/plugins/explore/public/components/fields_selector/facet_field.tsx
  src/plugins/explore/public/components/fields_selector/facet_list.test.tsx
  src/plugins/explore/public/components/fields_selector/facet_list.tsx
  src/plugins/explore/public/components/fields_selector/facet_value.scss
  src/plugins/explore/public/components/fields_selector/facet_value.test.tsx
  src/plugins/explore/public/components/fields_selector/facet_value.tsx
  src/plugins/explore/public/components/fields_selector/field_list.test.tsx
  src/plugins/explore/public/components/fields_selector/field_list.tsx
  src/plugins/explore/public/components/fields_selector/lib/group_fields.test.ts
  src/plugins/explore/public/components/fields_selector/lib/group_fields.ts
Labels: distinguished-contributor

#10358 [Explore] Infer tooltip date format dynamically
  changelogs/fragments/10358.yml
  src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/area/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/area/to_expression.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/line/to_expression.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.tsx
  src/plugins/explore/public/components/visualizations/utils/utils.test.ts
  src/plugins/explore/public/components/visualizations/utils/utils.ts
Labels: repeat-contributor

#10373 Add Autosuggest for AI Mode
  packages/osd-monaco/src/xjson/lexer_rules/index.ts
  src/plugins/data/public/antlr/prompt/code_completion.test.ts
  src/plugins/data/public/antlr/prompt/code_completion.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/editor_options/prompt_editor_options.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.test.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.ts
Labels: distinguished-contributor

#10324 [Banner Plugin] Refactor Banner Extensibility Model via Chrome Service
  changelogs/fragments/10324.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/header_banner.tsx
  src/core/public/core_system.test.ts
  src/core/public/core_system.ts
  src/core/public/rendering/app_containers.tsx
  src/core/public/rendering/rendering_service.tsx
  src/plugins/banner/public/index.scss
  src/plugins/banner/public/plugin.test.ts
  src/plugins/banner/public/plugin.ts
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: repeat-contributor, banner

#10378 [CVE-2025-6545][CVE-2025-7783] Bump pbkdf2 from 3.1.2 to 3.1.3 and set form-data to 4.0.4
  changelogs/fragments/10378.yml
  package.json
  yarn.lock
Labels: cve, distinguished-contributor, backport 3.2

#10379 [datasets] allow apps to configure available types in the explorer
  changelogs/fragments/10379.yml
  src/plugins/data/public/ui/dataset_select/dataset_select.tsx
  src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/explore/common/config.ts
  src/plugins/explore/public/build_services.ts
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.tsx
  src/plugins/explore/public/types.ts
Labels: distinguished-contributor, explore, datasets

#10375 [Explore] refactor chart available mappings
  src/plugins/explore/public/components/visualizations/area/area_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
  src/plugins/explore/public/components/visualizations/heatmap/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/to_expression.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
  src/plugins/explore/public/components/visualizations/rule_repository.test.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/scatter/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/style_panel.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/utils/utils.test.ts
  src/plugins/explore/public/components/visualizations/utils/utils.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.ts
  src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_container_utils.test.ts
  src/plugins/explore/public/components/visualizations/visualization_container_utils.ts
  src/plugins/explore/public/components/visualizations/visualization_registry.test.ts
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
Labels: distinguished-contributor

#10387 Fix Autocomplete Tests
  changelogs/fragments/10387.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
  cypress/utils/apps/explore/autocomplete.js
Labels: distinguished-contributor

#10389 Update the Insertion Text for Fields in NL Autocomplete
  src/plugins/data/public/antlr/prompt/code_completion.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.ts
Labels: distinguished-contributor

#10393 Trace Details: Log correlation (tabs+redirect)
  changelogs/fragments/10393.yml
  src/plugins/explore/public/application/pages/traces/trace_details/constants/span_detail_tabs.ts
  src/plugins/explore/public/application/pages/traces/trace_details/constants/trace_detail_tabs.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/correlation_service.test.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/correlation_service.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/logs_data_table.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/logs_data_table.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/span_logs_tab.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/span_logs_tab.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/trace_logs_tab.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/trace_logs_tab.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/url_builder.test.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/url_builder.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_panel.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_tabs.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_tabs/span_overview_tab.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/trace_detail_tabs.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/trace_detail_tabs.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_logs.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_logs.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/trace_view.tsx
Labels: repeat-contributor, failed changeset

#10406 [Explore] Traces - Trace default columns UI setting
  changelogs/fragments/10406.yml
  src/plugins/explore/common/index.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/server/plugin.ts
  src/plugins/explore/server/trace_ui_settings.ts
Labels: distinguished-contributor

#10408 Fix Value Suggestions for Columns containing @ and .
  changelogs/fragments/10408.yml
  packages/osd-monaco/src/ppl/constants.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
Labels: distinguished-contributor

#10390 [Explore] Refactor visualization builder
  changelogs/fragments/10390.yml
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/resizable_vis_control_and_tabs.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/resizable_vis_control_and_tabs.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.tsx
  src/plugins/explore/public/components/visualizations/add_to_dashboard_button.tsx
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel_render.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.test.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.types.ts
  src/plugins/explore/public/components/visualizations/visualization_builder_utils.test.ts
  src/plugins/explore/public/components/visualizations/visualization_builder_utils.ts
  src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
  src/plugins/explore/public/components/visualizations/visualization_render.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_render.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.test.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/plugin.ts
Labels: distinguished-contributor

#10418 Trace Details: Support external datasets
  changelogs/fragments/10418.yml
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/correlation_service.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/url_builder.test.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/logs/url_builder.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/services/service_map.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_tabs/span_overview_tab.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/utils/span_data_utils.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_helpers.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_helpers.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_logs.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_trace.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/server/ppl_request_trace.tsx
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.test.tsx
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.tsx
  src/plugins/explore/public/components/doc_viewer/trace_details_view/trace_details_view.tsx
Labels: repeat-contributor

#10400 fix to only show index selector when needed
  changelogs/fragments/10400.yml
  src/plugins/visualizations/public/wizard/new_vis_actions.test.tsx
  src/plugins/visualizations/public/wizard/new_vis_actions.tsx
Labels: distinguished-contributor

#10426 Add common VSCode launch configurations to `launch.json`
  .vscode/launch.json
  changelogs/fragments/10426.yml
Labels: all-star-contributor

#10273 Update version compatibility process between OSD and its plugins
  changelogs/fragments/10273.yml
  src/cli_plugin/install/index.js
  src/cli_plugin/install/index.test.js
  src/cli_plugin/install/install.js
  src/cli_plugin/install/opensearch_dashboards.js
  src/cli_plugin/install/opensearch_dashboards.test.js
  src/cli_plugin/install/settings.js
  src/cli_plugin/install/settings.test.js
  src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
  src/core/server/plugins/discovery/plugin_manifest_parser.ts
  src/core/server/plugins/discovery/plugins_discovery.test.ts
Labels: first-time-contributor

#10419 [Explore] Refactor visualization registry
  changelogs/fragments/10419.yml
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.test.ts
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/rule_repository.test.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.ts
  src/plugins/explore/public/components/visualizations/visualization_builder_utils.test.ts
  src/plugins/explore/public/components/visualizations/visualization_builder_utils.ts
  src/plugins/explore/public/components/visualizations/visualization_registry.test.ts
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
  src/plugins/explore/public/components/visualizations/visualization_render.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.test.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/services/visualization_registry_service.test.ts
Labels: distinguished-contributor

#10430 [Keyboard-shortcuts] Suppress keyboard shortcut conflict warnings in production builds
  changelogs/fragments/10430.yml
  src/core/public/keyboard_shortcut/key_parser.ts
  src/core/public/keyboard_shortcut/keyboard_shortcut_service.test.ts
  src/core/public/keyboard_shortcut/keyboard_shortcut_service.ts
Labels: repeat-contributor

#10413 Optimize Value Suggestions in Autocomplete
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js
  cypress/utils/apps/explore/autocomplete.js
  cypress/utils/apps/query_enhancements/autocomplete.js
  src/plugins/data/common/index_patterns/fields/index_pattern_field.ts
  src/plugins/data/common/index_patterns/types.ts
  src/plugins/data/common/search/search_source/types.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/prompt/code_completion.test.ts
  src/plugins/data/public/antlr/prompt/code_completion.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/components/fields_selector/lib/get_details.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Labels: distinguished-contributor

#10432 Discover:Traces: Update default columns and facets
  changelogs/fragments/10432.yml
  src/plugins/explore/public/components/fields_selector/lib/group_fields.ts
  src/plugins/explore/server/trace_ui_settings.ts
Labels: valued-contributor

#10412 [Explore] Introduce tab content error guard
  changelogs/fragments/10412.yml
  src/plugins/explore/common/index.ts
  src/plugins/explore/public/application/register_tabs.ts
  src/plugins/explore/public/application/utils/hooks/use_tab_error.test.ts
  src/plugins/explore/public/application/utils/hooks/use_tab_error.ts
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.ts
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/resizable_vis_control_and_tabs.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/resizable_vis_control_and_tabs.tsx
  src/plugins/explore/public/components/error_panel/error_panel.stories.tsx
  src/plugins/explore/public/components/error_panel/error_panel.test.tsx
  src/plugins/explore/public/components/error_panel/error_panel.tsx
  src/plugins/explore/public/components/error_panel/index.ts
  src/plugins/explore/public/components/tabs/error_guard/error_code_block/error_code_block.scss
  src/plugins/explore/public/components/tabs/error_guard/error_code_block/error_code_block.stories.tsx
  src/plugins/explore/public/components/tabs/error_guard/error_code_block/error_code_block.test.tsx
  src/plugins/explore/public/components/tabs/error_guard/error_code_block/error_code_block.tsx
  src/plugins/explore/public/components/tabs/error_guard/error_code_block/index.ts
  src/plugins/explore/public/components/tabs/error_guard/error_guard.scss
  src/plugins/explore/public/components/tabs/error_guard/error_guard.stories.tsx
  src/plugins/explore/public/components/tabs/error_guard/error_guard.test.tsx
  src/plugins/explore/public/components/tabs/error_guard/error_guard.tsx
  src/plugins/explore/public/components/tabs/tabs.test.tsx
  src/plugins/explore/public/components/tabs/tabs.tsx
Labels: distinguished-contributor

#10450 [Explore] Traces - add a link to detail page in expanded row
  changelogs/fragments/10450.yml
  src/plugins/explore/public/components/data_table/table_cell/empty_table_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/non_filterable_table_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/source_field_table_cell.scss
  src/plugins/explore/public/components/data_table/table_cell/source_field_table_cell.test.tsx
  src/plugins/explore/public/components/data_table/table_cell/source_field_table_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/table_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/table_source_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.test.tsx
  src/plugins/explore/public/components/data_table/table_cell/trace_utils/trace_utils.tsx
  src/plugins/explore/public/components/data_table/table_row/expanded_table_row/expanded_table_row.test.tsx
  src/plugins/explore/public/components/data_table/table_row/expanded_table_row/expanded_table_row.tsx
  src/plugins/explore/public/components/data_table/table_row/expanded_table_row/span_link.test.tsx
  src/plugins/explore/public/components/data_table/table_row/expanded_table_row/span_link.tsx
  src/plugins/explore/public/components/data_table/table_row/table_row.test.tsx
  src/plugins/explore/public/components/data_table/table_row/table_row.tsx
  src/plugins/explore/public/components/data_table/table_row/table_row_content.test.tsx
  src/plugins/explore/public/components/data_table/table_row/table_row_content.tsx
Labels: distinguished-contributor

#10444 [Explore] disable charts in traces
  changelogs/fragments/10444.yml
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.tsx
Labels: distinguished-contributor

#10433 [Keyboard-shortcuts] Add two-key sequence support
  src/core/public/keyboard_shortcut/constants.ts
  src/core/public/keyboard_shortcut/key_parser.ts
  src/core/public/keyboard_shortcut/keyboard_shortcut_service.test.ts
  src/core/public/keyboard_shortcut/keyboard_shortcut_service.ts
  src/core/public/keyboard_shortcut/sequence_handler.test.ts
  src/core/public/keyboard_shortcut/sequence_handler.ts
  src/core/public/keyboard_shortcut/utils.ts
Labels: repeat-contributor

#10453 [Query Enhancements] Add Cypress Test for Enter key behaviour
  changelogs/fragments/10453.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/language_specific_display.spec.js
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: distinguished-contributor

#10449 [Explore] Metric viz with sparkline
  changelogs/fragments/10449.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/add_vis_to_dashboard.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis_metric.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/vis_type_switch.spec.js
  cypress/utils/commands.explore.js
  src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/metric/to_expression.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/value/value_calculation_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/value/value_calculation_selector.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/font_size_input_field.tsx
  src/plugins/explore/public/components/visualizations/utils/utils.test.ts
  src/plugins/explore/public/components/visualizations/utils/utils.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.ts
Labels: distinguished-contributor
