Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-01, with the labels that each got.

#9113 [Discover] Adding Cypress Tests for S3 Datasets
  .github/workflows/cypress_workflow_with_s3.yml
  changelogs/fragments/9113.yml
  cypress.config.ts
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/s3_dataset.spec.js
  cypress/utils/apps/query_enhancements/constants.js
Labels: all-star-contributor

#7690 [Workspace][Bug] Unable to copy assets to a workspace without assigning related data source
  changelogs/fragments/7690.yml
  src/core/public/workspace/types.ts
  src/core/server/saved_objects/import/create_saved_objects.test.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/import/utils.test.ts
  src/core/server/saved_objects/import/utils.ts
  src/core/server/saved_objects/import/validate_data_sources.test.ts
  src/core/server/saved_objects/import/validate_data_sources.ts
  src/core/server/saved_objects/import/validate_references.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/duplicate.test.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/routes/index.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.19.0

#9004 [Workspace] fix: Fix workspace page hanging with none collaborators for non dashboard admin
  changelogs/fragments/9004.yml
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#9119 [Discover 2.0 Testing] Create Filtering Test (TestId-69: Filtering)
  changelogs/fragments/9119.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/utils/field_display_filtering.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/workspace/commands.js
  cypress/utils/commands.js
  cypress/utils/dashboards/data_explorer/elements.js
  cypress/utils/index.d.ts
Labels: repeat-contributor

#9024 [Workspace] fix:Prevent user from visiting dashboards / visualizations when out of a workspace
  changelogs/fragments/9024.yml
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.19.0

#9112 Add tests for saved search creation and loading for query enhancement
  changelogs/fragments/9112.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/queries.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/utils/saved_search.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/index.d.ts
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/apps/workspace/commands.js
  cypress/utils/apps/workspace/index.d.ts
  cypress/utils/commands.js
  cypress/utils/index.d.ts
Labels: repeat-contributor

#9153 fix: 0 rendered in discover when there are no results
  changelogs/fragments/9153.yml
  src/plugins/discover/public/application/components/no_results/no_results.tsx
Labels: backport 2.x, repeat-contributor

#9057 Update data source details to use small buttons
  changelogs/fragments/9057.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/__snapshots__/acceleration_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_util.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_utils.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/associated_objects_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/utils/__snapshots__/associated_objects_refresh_button.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/associated_object_management/utils/associated_objects_refresh_button.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/__snapshots__/access_control_tab.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/access_control_tab.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/__snapshots__/installed_integrations_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/installed_integrations_table.tsx
Labels: backport 2.x, first-time-contributor

#8907 [Workspace] Add privacy levels to the workspace
  changelogs/fragments/8907.yml
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.test.tsx
  src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.tsx
  src/plugins/workspace/public/components/workspace_collaborators/__snapshots__/workspace_collaborators.test.tsx.snap
  src/plugins/workspace/public/components/workspace_collaborators/workspace_collaborators.tsx
  src/plugins/workspace/public/components/workspace_creator/utils.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx
  src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail_form_content.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_privacy_setting_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_privacy_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_setting.scss
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_setting_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_setting_select.tsx
Labels: backport 2.x, seasoned-contributor, workspace, v2.19.0

#8906 [workspace] refactor: refactor the bulk_get handler in permission wrapper when item has permission error
  changelogs/fragments/8906.yml
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.19.0

#8931 [Auto Suggest] DQL Parsing updates and Fixes
  changelogs/fragments/8931.yml
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.interp
  src/plugins/data/public/antlr/dql/.generated/DQLLexer.ts
  src/plugins/data/public/antlr/dql/.generated/DQLParser.ts
  src/plugins/data/public/antlr/dql/.generated/DQLParserVisitor.ts
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/dql/grammar/DQLLexer.g4
Labels: backport 2.x, discover, seasoned-contributor, discover-next

#8999 [workspace]add 2 step loading in 'Associate data sources' modal
  changelogs/fragments/8999.yml
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, seasoned-contributor, workspace, v2.19.0

#9052 [Enhancement] Use HTTP service instead of fetch for plugin check
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_creation/create/create_acceleration.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_creation/create/create_acceleration.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_creation/selectors/__snapshots__/preview_sql_definition.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_creation/selectors/preview_sql_definition.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_creation/selectors/preview_sql_definition.tsx
Labels: backport 2.x, seasoned-contributor

#9164 [Workspace] Support to dissociate data connection object since DSM list has supported to display
  changelogs/fragments/9164.yml
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/types.ts
Labels: backport 2.x, distinguished-contributor, v2.19.0

#9159 Fix Unhandled Error Response of dev tool with MDS
  changelogs/fragments/9159.yml
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
Labels: enhancement, backport 2.x, multiple datasource, distinguished-contributor, v2.19.0

#9145 Add a learn more flyout to the collaborators page
  changelogs/fragments/9145.yml
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/workspace/public/components/workspace_collaborators/workspace_collaborators.tsx
  src/plugins/workspace/public/components/workspace_form/__snapshots__/workspace_privacy_flyout.test.tsx.snap
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_flyout.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_flyout.tsx
Labels: backport 2.x, seasoned-contributor, workspace

#8737 [Workspace] Fix UI issues in workspace detail and create page
  changelogs/fragments/8737.yml
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.scss
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.scss
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.scss
  src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
Labels: backport 2.x, seasoned-contributor, workspace, v2.19.0

#8136 Fix the display and jump logic for recent assets
  changelogs/fragments/8136.yml
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/recently_accessed/recently_accessed_service.test.ts
  src/core/public/chrome/recently_accessed/recently_accessed_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/nav_link.test.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/plugins/saved_objects_management/public/management_section/recent_work.tsx
Labels: backport 2.x, valued-contributor, workspace, v2.19.0

#9151 [Cypress][Fix] Update saved search utilities
  changelogs/fragments/9151.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/utils/saved_search.js
Labels: repeat-contributor, discover_2.0-test

#9172 chore: Update oui to 1.19
  changelogs/fragments/9172.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: backport 2.x, seasoned-contributor, v2.19.0

#9079 chore: use relative paths in cypress
  changelogs/fragments/9079.yml
  cypress/utils/commands.js
Labels: repeat-contributor, discover_2.0-test

#9181 Update text in workspace collaborators text box
  src/plugins/workspace/public/components/workspace_form/workspace_privacy_setting_panel.tsx
Labels: backport 2.x, Skip-Changelog, first-time-contributor

#9193 [Backport 2.x] Fix Unhandled Error Response of dev tool with MDS (#9159)
  changelogs/fragments/9159.yml
  src/plugins/console/server/routes/api/console/proxy/create_handler.ts
Labels: Skip-Changelog, v2.19.0

#9187 [workspace] fix set as default error in data source and index pattern
  changelogs/fragments/9187.yml
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
Labels: backport 2.x, seasoned-contributor, workspace

#9166 [Discover 2.0 Testing] Create View List of Saved Queries Test (Test-Id 124: View list of Saved query)
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/9166.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/saved_queries_flyout.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/saved_queries_popover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/query_enhancements/field_display_filtering.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  cypress/utils/apps/query_enhancements/saved_search.js
  src/plugins/data/public/ui/saved_query_form/helpers.tsx
  src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
Labels: repeat-contributor, discover_2.0-test

#9197 change casing to folder structures to be compliant with our rules
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_dataset.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_flyout.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_popover.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/with_security/check_advanced_settings.js
  cypress/integration/with_security/check_default_page.js
  cypress/integration/with_security/check_filter_and_query.js
  cypress/integration/with_security/check_loaded_data.js
  cypress/integration/with_security/check_timeline.js
  cypress/integration/with_security/helpers/generate_data.js
  cypress/integration/with_security/plugins/.gitignore
  cypress/integration/without_security/check_advanced_settings.js
  cypress/integration/without_security/check_default_page.js
  cypress/integration/without_security/check_filter_and_query.js
  cypress/integration/without_security/check_loaded_data.js
  cypress/integration/without_security/check_timeline.js
  cypress/integration/without_security/helpers/generate_data.js
  cypress/integration/without_security/plugins/.gitignore
  package.json
Labels: Skip-Changelog, repeat-contributor

#8874 [Workspace]Dismiss get started for search/essential/analytics overview page
  changelogs/fragments/8874.yml
  src/plugins/content_management/public/mocks.ts
  src/plugins/home/common/constants.ts
  src/plugins/home/public/application/application.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_app.test.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_app.tsx
  src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/home/server/plugin.test.ts
  src/plugins/home/server/plugin.ts
  src/plugins/home/server/ui_settings.test.ts
  src/plugins/home/server/ui_settings.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx
  src/plugins/workspace/public/components/workspace_use_case_overview_app.test.tsx
  src/plugins/workspace/public/components/workspace_use_case_overview_app.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/ui_settings.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#9189 [Workspace] update workspace not found message to generic message
  changelogs/fragments/9189.yml
  src/plugins/workspace/server/integration_tests/duplicate.test.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#8287 [Workspace] Address UI issues of index patterns
  changelogs/fragments/8287.yml
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.test.tsx
  src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/__snapshots__/scripted_field_table.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/__snapshots__/header.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.test.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/scripted_field_table.test.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/scripted_fields_table.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/__snapshots__/source_filters_table.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/add_filter/__snapshots__/add_filter.test.tsx.snap
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/add_filter/add_filter.test.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/add_filter/add_filter.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/source_filters_table.test.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/source_filters_table.tsx
  src/plugins/index_pattern_management/public/components/edit_index_pattern/tabs/tabs.tsx
  src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Labels: backport 2.x, valued-contributor, workspace, look & feel, v2.19.0

#8716 Add data2summary check in data summary panel in discover
  changelogs/fragments/8716.yml
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/utils/constant.ts
  src/plugins/query_enhancements/public/query_assist/utils/get_is_summary_agent.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/get_is_summary_agent.ts
Labels: backport 2.x, seasoned-contributor, v2.19.0

#8892 [Manual Backport 2.x] Upgrade actions/upload-artifact to v4
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/8855.yml
Labels: Skip-Changelog, failed changeset

#9200 [Fix] Saved Search Integ Test Update: update saving a new saved search test spec
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/query_enhancements/saved_search.js
Labels: Skip-Changelog, repeat-contributor, discover_2.0-test

#9208 refactor query enhancement tests
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_dataset.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_flyout.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_popover.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/field_display_filtering.js
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  cypress/utils/apps/query_enhancements/shared.js
Labels: Skip-Changelog, valued-contributor, discover_2.0-test

#9176 [Discover] [Vizbuilder] fix: Cleanup OsdUrlStateStorage subscription in TopNav
  changelogs/fragments/9167.yml
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.ts
  src/plugins/data/public/query/state_sync/index.ts
  src/plugins/data/public/query/state_sync/use_connect_to_query_state.test.ts
  src/plugins/data/public/query/state_sync/use_connect_to_query_state.ts
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/vis_builder/public/application/components/top_nav.tsx
Labels: backport 2.x, first-time-contributor, v2.19.0

#9212 add data-test-subjs that are required for TESTID-51
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, Skip-Changelog, valued-contributor, discover_2.0-test

#8275 [Auto Suggest] PPL & SQL Value Suggestion
  changelogs/fragments/8275.yml
  src/plugins/data/common/constants.ts
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLParser.g4
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.test.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/constants.ts
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_sql/table.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/data/server/ui_settings.ts
Labels: backport 2.x, discover, valued-contributor, discover-next, v2.19.0

#9222 [Workspace]Update workspace privacy setting link
  changelogs/fragments/9222.yml
  src/core/public/doc_links/doc_links_service.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
Labels: backport 2.x, distinguished-contributor, v2.19.0

#9209 Remove bypass of getting cypress cache
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/9209.yml
Labels: backport 2.x, distinguished-contributor

#9219 chore: remove unused/redundant functions from field_display_filtering_utils
  cypress/utils/apps/query_enhancements/field_display_filtering.js
Labels: backport 2.x, Skip-Changelog, valued-contributor, discover_2.0-test

#9150 Create cypress command namespacing util
  changelogs/fragments/9150.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_dataset.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/dashboard_sanity_test.spec.ts
  cypress/utils/apps/workspace/commands.js
  cypress/utils/command_namespace.js
  cypress/utils/commands.js
  cypress/utils/dashboards/remove_workspace.js
  cypress/utils/dashboards/setup_workspace.js
  cypress/utils/index.d.ts
Labels: repeat-contributor, discover_2.0-test

#9226 [Workspace]feat: enable maximum workspaces
  changelogs/fragments/9226.yml
  config/opensearch_dashboards.yml
  src/plugins/workspace/config.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/workspace_client.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: backport 2.x, distinguished-contributor, workspace, v2.19.0

#9223 Add navControlsPrimaryHeaderRight slot to header
  changelogs/fragments/9223.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_controls/nav_controls_service.test.ts
  src/core/public/chrome/nav_controls/nav_controls_service.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: backport 2.x, distinguished-contributor, v2.19.0

#9228 Move query assistant summary toggle to AI assistant dropdown list
  changelogs/fragments/9228.yml
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/components/index.ts
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_button.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_button.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/hooks/use_query_assist.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/public/types.ts
Labels: backport 2.x, distinguished-contributor, v2.19.0

#9237 [workspace]fix the bug that mistakenly classify data connection
  changelogs/fragments/9237.yml
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#9236 Fixing console error when the data source has an empty description
  changelogs/fragments/9236.yml
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/mocks.ts
Labels: backport 2.x, first-time-contributor, workspace, v2.19.0

#9262 update cy.createInitialWorkspaceWithDataSource -> cy.osd.createInitialWorkspaceWithDataSource
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_flyout.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_popover.spec.js
Labels: Skip-Changelog, valued-contributor, discover_2.0-test

#9269 style: Update sidecar style to align with new page header
  changelogs/fragments/9269.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/overlays/sidecar/components/sidecar.scss
Labels: backport 2.x, distinguished-contributor, v2.19.0

#9259 [Workspace]DQC can not be assigned to a workspace due to validation
  changelogs/fragments/9259.yml
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: backport 2.x, all-star-contributor, workspace, v2.19.0

#9275 [Workspace]fix: recent item links are not correctly constructed
  changelogs/fragments/9275.yml
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/recent_items.test.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, distinguished-contributor, workspace, v2.19.0

#9215 TESTID-51 Add test for language-specific display
  changelogs/fragments/9215.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/language_specific_display.spec.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/language_specific_display.js
Labels: backport 2.x, valued-contributor, discover_2.0-test

#9279 [CI] Update CI Group 11 Run Command
  package.json
Labels: backport 2.x, Skip-Changelog, all-star-contributor

#9248 [Discover] Query Editor Shortcut Fires Incorrect Query
  changelogs/fragments/9248.yml
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: backport 2.x, discover, all-star-contributor

#9229 [TESTID-125,126,127,128,129] Saved Query Test Scope
  changelogs/fragments/9229.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_flyout.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_popover.spec.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/commands.js
  cypress/utils/index.d.ts
Labels: backport 2.x, repeat-contributor, discover_2.0-test

#9265 Add Tests for Relative and Quick Select Time Range Selection
  changelogs/fragments/9265.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/time_range_selection.spec.js
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/apps/query_enhancements/time_range_selection.js
Labels: backport 2.x, all-star-contributor, v2.19.0, discover_2.0-test

#9287 [TESTID-125,126,127,128,129] Saved Query Test Scope Add Todo for Workaround
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
Labels: backport 2.x, Skip-Changelog, repeat-contributor, v2.19.0, discover_2.0-test

#9120 [Auto Suggest] Fix Grammar Changes
  changelogs/fragments/9120.yml
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.interp
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParser.ts
  src/plugins/data/public/antlr/opensearch_ppl/.generated/OpenSearchPPLParserVisitor.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/data/public/antlr/opensearch_ppl/grammar/OpenSearchPPLParser.g4
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.test.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_sql/opensearch_sql_autocomplete.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
Labels: seasoned-contributor

#9263 [Discover]chore: disable sorting on columns header for PPL and SQL
  changelogs/fragments/9263.yml
  src/plugins/data/common/osd_field_types/osd_field_types.ts
  src/plugins/data/public/query/query_string/language_service/language_service.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/discover/public/application/components/default_discover_table/helper.test.tsx
  src/plugins/discover/public/application/components/default_discover_table/helper.tsx
  src/plugins/query_enhancements/public/plugin.tsx
Labels: bug, repeat-contributor, discover-next, v2.19.0

#9255 Add Tests for Simple dataset Selector
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/9255.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/simple_dataset_selector.spec.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/simple_dataset_selector.js
  package.json
Labels: backport 2.x, all-star-contributor, v2.19.0, discover_2.0-test

#9302 Update cross-spawn dependecy in yarn.lock
  changelogs/fragments/9302.yml
  yarn.lock
Labels: v2.19.0

#9154 [Cypress Test] Add and Refactor TESTID-140 sidebar spec and TESTID-46,47,49 sharing spec
  changelogs/fragments/9154.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/shared_links.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/apps/query_enhancements/shared_links.js
  cypress/utils/apps/query_enhancements/sidebar.js
  cypress/utils/apps/query_enhancements/table.js
  package.json
Labels: backport 2.x, distinguished-contributor, v2.19.0, discover_2.0-test, backport 2.19

#9288 TESTID-116, TESTID-115, TESTID-61 - Tests for Saved Searches in Dashboard
  changelogs/fragments/9288.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search_in_dashboards.spec.js
  cypress/utils/apps/query_enhancements/saved.js
  package.json
Labels: backport 2.x, valued-contributor, v2.19.0, discover_2.0-test, backport 2.19

#9072 Fix add to dashboard after saving (with unit tests)
  changelogs/fragments/9072.yml
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.test.tsx
  src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
  src/plugins/dashboard/public/application/utils/mocks.ts
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
Labels: backport 2.x, repeat-contributor, v2.19.0, backport 2.19
