Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-02, with the labels that each got.

#9285 [Cypress][TESTID-147] Add tests for table canvas in discover
  changelogs/fragments/9285.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/shared_links.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/table.spec.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/shared.js
  package.json
Labels: backport 2.x, discover_2.0-test, v2.20.0

#9292 [TESTID-58,59] Inspect functionality for Discover and Visualizations
  changelogs/fragments/9292.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js
  cypress/utils/apps/query_enhancements/doc_table.js
  cypress/utils/apps/query_enhancements/field_display_filtering.js
  cypress/utils/apps/query_enhancements/inspect.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/commands.js
  package.json
Labels: backport 2.x, valued-contributor, discover_2.0-test, v2.20.0

#9319 [TEST] refactor all tests to be consistent across different source codes
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/language_specific_display.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_dataset.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search_in_dashboards.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/shared_links.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/simple_dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/table.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/time_range_selection.spec.js
  cypress/support/e2e.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/apps/workspace/commands.js
  cypress/utils/commands.js
  cypress/utils/commands.osd.js
  cypress/utils/dashboards/remove_workspace.js
  cypress/utils/dashboards/setup_workspace.js
  cypress/utils/helpers.js
  cypress/utils/index.d.ts
  docs/_sidebar.md
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, discover_2.0-test, v2.20.0

#9298 [Discover] chore: Improve scrolling experience
  changelogs/fragments/9298.yml
  src/plugins/discover/public/application/components/chart/_histogram.scss
  src/plugins/discover/public/application/components/default_discover_table/_doc_table.scss
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
Labels: backport 2.x, discover, repeat-contributor

#9339 [TEST] update tests to use only data-logs-1
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/language_specific_display.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search_in_dashboards.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/time_range_selection.spec.js
  cypress/utils/apps/query_enhancements/dataset_selector.js
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  cypress/utils/constants.js
Labels: backport 2.x, Skip-Changelog, seasoned-contributor, discover_2.0-test, v2.20.0

#9340 [Workspace]bugfix: remove workspace prefix when calling `get` in recent assets
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, v2.19.0, backport 2.19

#9343 Change from `Cluster` to `Data sources` for Indexes type in dataset selector column
  changelogs/fragments/9343.yml
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
Labels: backport 2.x, discover, distinguished-contributor, v2.20.0

#9345 Add ciGroup13 for query tests
  .github/workflows/cypress_workflow.yml
  package.json
Labels: backport 2.x, Skip-Changelog, distinguished-contributor, discover_2.0-test, v2.20.0

#9352 Add retry mechanism for flaky share menu test
  changelogs/fragments/9352.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/shared_links.spec.js
  cypress/utils/apps/query_enhancements/shared_links.js
Labels: backport 2.x, distinguished-contributor, discover_2.0-test, v2.20.0

#9314 add a check for the sort visibility in language_specific_display
  changelogs/fragments/9314.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/language_specific_display.spec.js
Labels: backport 2.x, seasoned-contributor

#9291 Add doc on triaging
  TRIAGING.md
  changelogs/fragments/9291.yml
Labels: backport 2.x, valued-contributor

#9366 Update actions/cache from v1 to v4 to address deprecation warning
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/9366.yml
Labels: backport 2.x, maintenance, distinguished-contributor, discover_2.0-test, v2.20.0

#8759 Handle invalid geospatial request in region map
  src/plugins/region_map/server/routes/opensearch.ts
Labels: Skip-Changelog, repeat-contributor, failed changeset

#9368 Update DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: docs, backport 2.x, first-time-contributor, failed changeset

#9362 [Documentation] Add alternative Docker Development Environment Setup documentation.
  changelogs/fragments/9362.yml
  docs/docker-dev/docker-dev-setup-manual.md
Labels: valued-contributor

#9331 [TESTID-77] Index Patterns Caching functionality for Discover
  changelogs/fragments/9331.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/caching.spec.js
  cypress/utils/apps/query_enhancements/caching.js
  package.json
Labels: backport 2.x, valued-contributor, discover_2.0-test, v2.20.0

#9316 [Discover] fix: Clean up sync URL subscription in Discover plugin topNav
  changelogs/fragments/9316.yml
  src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/state_sync/index.ts
  src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
  src/plugins/data/public/query/state_sync/use_sync_state_with_url.test.ts
  src/plugins/data/public/query/state_sync/use_sync_state_with_url.ts
  src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Labels: backport 2.x, discover, repeat-contributor

#9322 [TESTID-64,80,UI] Add cypress test for autocomplete feature
  changelogs/fragments/9322.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/autocomplete_query.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/autocomplete_switch.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/autocomplete_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/caching.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/simple_dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/time_range_selection.spec.js
  cypress/utils/apps/query_enhancements/autocomplete.js
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/commands.osd.js
  docs/_sidebar.md
  package.json
Labels: backport 2.x, discover_2.0-test, v2.20.0

#9152 feat(vis_type_vega): support reading time field
  changelogs/fragments/9152.yml
  src/plugins/vis_type_vega/public/data_model/ppl_parser.test.ts
  src/plugins/vis_type_vega/public/data_model/ppl_parser.ts
  src/plugins/vis_type_vega/public/data_model/vega_parser.ts
Labels: backport 2.x, all-star-contributor

#9384 [TESTID-17] Add tests for query testing and advanced settings
  .github/workflows/cypress_workflow.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/advanced_settings.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries_more.spec.js
  cypress/utils/apps/query_enhancements/queries.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/commands.js
  cypress/utils/commands.osd.js
  package.json
Labels: backport 2.x, failed changeset, discover_2.0-test, v2.20.0

#9307 [Recent Queries]: add all recent queries tests
  changelogs/fragments/9307.yml
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/recent_queries.spec.js
  cypress/utils/apps/query_enhancements/recent_queries.js
  cypress/utils/apps/query_enhancements/shared.js
  package.json
  yarn.lock
Labels: backport 2.x, repeat-contributor, discover_2.0-test, v2.20.0

#9290 [TESTID-66] Add histogram tests
  changelogs/fragments/9290.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/histogram_interaction.spec.js
  cypress/utils/apps/query_enhancements/histogram_interaction.js
  package.json
Labels: backport 2.x, repeat-contributor, discover_2.0-test, v2.20.0

#9396 Remove reload in saved_search spec as bug has been resolved
  changelogs/fragments/9396.yml
  cypress/utils/apps/query_enhancements/saved.js
Labels: backport 2.x, valued-contributor, discover_2.0-test, v2.20.0

#9402 [Follow-up #9386] Add TODO and omit for hide missing values for SQL and PPL
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js
Labels: backport 2.x, Skip-Changelog, discover_2.0-test, v2.20.0

#9398 [TESTID-234] Add tests for query editor display
  changelogs/fragments/9398.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries_ui.spec.js
  cypress/utils/apps/query_enhancements/queries.js
  package.json
Labels: backport 2.x, discover_2.0-test, v2.20.0

#9383 Enable overwrite on upload artifact
  .github/workflows/build_and_test_workflow.yml
  .github/workflows/cypress_workflow.yml
  .github/workflows/cypress_workflow_with_s3.yml
  .github/workflows/release_cypress_workflow.yml
Labels: Skip-Changelog, repeat-contributor

#9407 Version Bump from 2.19.0 to 2.19.1
  changelogs/fragments/9407.yml
  package.json
Labels: backport 2.x, failed changeset

#9405 [Discover]: Make colour of discover histogram match theme
  changelogs/fragments/9405.yml
  src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
Labels: backport 2.x, discover, repeat-contributor

#9382 [Discover] chore: Fix view single document page content padding
  changelogs/fragments/9382.yml
  src/plugins/discover/public/application/components/doc/doc.tsx
Labels: backport 2.x, discover, repeat-contributor, v2.20.0

#9406 Update lycheeignore
  .lycheeignore
Labels: backport 2.x, Skip-Changelog, repeat-contributor, v2.20.0

#9355 [Discover] Cancel S3 Queries Using SQL Plugin
  changelogs/fragments/9355.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_dataset.spec.js
  cypress/utils/apps/query_enhancements/constants.js
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
  src/plugins/query_enhancements/server/utils/plugins.ts
Labels: backport 2.x, discover, all-star-contributor, v2.20.0

#9296 [Discover] support description in data-structures
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/ui/dataset_selector/_dataset_table.scss
  src/plugins/data/public/ui/dataset_selector/_index.scss
  src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
Labels: backport 2.x, discover, Skip-Changelog, all-star-contributor

#9379 Render PPL time column using the correct time zone
  changelogs/fragments/9379.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/inspect.spec.js
  src/plugins/data/common/constants.ts
  src/plugins/data/common/data_frames/utils.test.ts
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
  src/plugins/data/common/search/aggs/buckets/date_histogram.ts
  src/plugins/data/common/search/aggs/utils/calculate_auto_time_expression.ts
  src/plugins/data/common/search/opensearch_search/types.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, discover, distinguished-contributor

#9433 Fix flakieness in cypress tests
  changelogs/fragments/9433.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/query_enhancements/saved_queries.js
Labels: v3.0.0, distinguished-contributor, discover_2.0-test

#9436 Format PPL date fields to `YYYY-MM-DDTHH:mm:ss.SSSZ`
  changelogs/fragments/9436.yml
  src/plugins/query_enhancements/public/plugin.tsx
Labels: backport 2.x, discover, distinguished-contributor

#9358 [TEST] add more osd namespacing
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/saved_search.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/simple_dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/language_specific_display.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/saved_search_in_dashboards.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/time_range_selection.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/caching.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/shared_links.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/table.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/advanced_settings.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/histogram_interaction.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_more.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/s3_dataset.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_query.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_switch.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/recent_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/sidebar.spec.js
  cypress/integration/with_security/check_timeline.js
  cypress/integration/without_security/check_timeline.js
  cypress/support/e2e.js
  cypress/utils/apps/commands.js
  cypress/utils/apps/data_explorer/commands.js
  cypress/utils/apps/data_explorer/index.d.ts
  cypress/utils/apps/index.d.ts
  cypress/utils/apps/query_enhancements/autocomplete.js
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/constants.js
  cypress/utils/apps/query_enhancements/dataset_selector.js
  cypress/utils/apps/query_enhancements/histogram_interaction.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/apps/query_enhancements/shared_links.js
  cypress/utils/apps/query_enhancements/time_range_selection.js
  cypress/utils/apps/workspace/commands.js
  cypress/utils/apps/workspace/index.d.ts
  cypress/utils/commands.osd.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/index.d.ts
  cypress/utils/dashboards/workspace-plugin/commands.js
  cypress/utils/dashboards/workspace_plugin/commands.js
  cypress/utils/dashboards/workspace_plugin/constants.js
  cypress/utils/index.d.ts
  package.json
Labels: Skip-Changelog, seasoned-contributor

#9277 [workspace]Hide the assistant entry when there isn't data2summary agent
  changelogs/fragments/9277.yml
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/hooks/use_query_assist.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
  src/plugins/query_enhancements/public/types.ts
Labels: backport 2.x, all-star-contributor

#9408 Feature/data importer
  src/plugins/data_importer/public/components/data_importer_app.tsx
  src/plugins/data_importer/public/components/import_type_selector.tsx
  src/plugins/data_importer/public/components/preview_table.scss
  src/plugins/data_importer/public/components/preview_table.tsx
  src/plugins/data_importer/server/routes/cat_indices.ts
  src/plugins/data_importer/server/routes/import_file.ts
  yarn.lock
Labels: first-time-contributor, failed changeset

#9444 [TEST] add setting sort for PPL and SQL for inspect.spec
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/inspect.spec.js
  cypress/utils/apps/query_enhancements/inspect.js
Labels: v3.0.0, Skip-Changelog, seasoned-contributor, discover_2.0-test

#9347 Fix flatten hit modify original array
  changelogs/fragments/9347.yml
  src/plugins/data/common/index_patterns/index_patterns/flatten_hit.ts
  src/plugins/data/common/index_patterns/index_patterns/index_pattern.test.ts
Labels: v3.0.0, distinguished-contributor

#9446 remove deprecated CssDistFilename for 3.0
  changelogs/fragments/9446.yml
  packages/osd-ui-shared-deps/index.d.ts
  packages/osd-ui-shared-deps/index.js
Labels: v3.0.0, seasoned-contributor, do not backport

#9411 Bump axios from 0.28.1 to 0.29.0 in 2.x
  packages/osd-dev-utils/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: cve, backport 2.x, Skip-Changelog, backport 2.19, v2.19.1

#9412 Bump markdown-it from 12.3.2 to 13.0.2
  changelogs/fragments/9412.yml
  package.json
  packages/osd-dev-utils/package.json
  yarn.lock
Labels: cve, backport 2.x, distinguished-contributor, backport 2.19, v2.19.1

#9447 Bump dompurify from 3.1.6 to 3.2.4
  changelogs/fragments/9447.yml
  package.json
  yarn.lock
Labels: cve, backport 2.x, backport 2.19, v2.19.1

#9452 [2.x-manual-backport] Bump markdown-it from 12.3.2 to 13.0.2 (#9412)
  changelogs/fragments/9412.yml
  package.json
  packages/osd-dev-utils/package.json
  yarn.lock
Labels: Skip-Changelog, backport 2.19

#9429 Allow v8/v9 as default setting
  packages/osd-ui-shared-deps/theme_config.d.ts
  packages/osd-ui-shared-deps/theme_config.js
  src/core/server/ui_settings/settings/theme.test.ts
  src/core/server/ui_settings/settings/theme.ts
  src/core/server/ui_settings/ui_settings_config.ts
Labels: Skip-Changelog, valued-contributor

#9448 remove withLongNumerals in HttpFetchOptions as it is deprecated in 3.0
  changelogs/fragments/9448.yml
  src/core/public/http/fetch.ts
  src/core/public/http/types.ts
Labels: v3.0.0, do not backport

#9458 Add release notes for 2.19.1
  CHANGELOG.md
  changelogs/fragments/9325.yml
  changelogs/fragments/9407.yml
  changelogs/fragments/9412.yml
  changelogs/fragments/9447.yml
  release-notes/opensearch-dashboards.release-notes-2.19.1.md
Labels: Skip-Changelog, failed changeset

#9435 Add debug documentation and configuration
  .vscode/launch.json
  DEVELOPER_GUIDE.md
  changelogs/fragments/9435.yml
Labels: valued-contributor

#9462 Refactor changes
  changelogs/fragments/9462.yml
  src/plugins/data_importer/public/components/__snapshots__/data_importer_app.test.tsx.snap
  src/plugins/data_importer/public/components/__snapshots__/import_type_selector.test.tsx.snap
  src/plugins/data_importer/public/components/data_importer_app.test.tsx
  src/plugins/data_importer/public/components/data_importer_app.tsx
  src/plugins/data_importer/public/lib/cat_indices.test.ts
  src/plugins/data_importer/public/lib/cat_indices.ts
  src/plugins/data_importer/public/lib/import_file.test.ts
  src/plugins/data_importer/public/lib/import_file.ts
  src/plugins/data_importer/public/lib/import_text.test.ts
  src/plugins/data_importer/public/lib/import_text.ts
  src/plugins/data_importer/public/lib/preview.ts
  src/plugins/data_importer/public/types.ts
  src/plugins/data_importer/server/routes/cat_indices.ts
  src/plugins/data_importer/server/routes/import_file.ts
  src/plugins/data_importer/server/routes/import_text.ts
  src/plugins/data_importer/server/routes/preview.ts
Labels: seasoned-contributor

#9430 [Discover] Add New Mappings for S3 Type
  changelogs/fragments/9430.yml
  src/plugins/query_enhancements/common/types.ts
  src/plugins/query_enhancements/public/datasets/s3_type.ts
Labels: all-star-contributor
