Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-07, with the labels that each got.

#10013 [Explore] Refactor Explore Redux state and improve persistence performance
  src/plugins/explore/public/application/components/header_dataset_selector.tsx
  src/plugins/explore/public/application/components/query_panel.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/hooks/use_tab_results.test.tsx
  src/plugins/explore/public/application/utils/state_management/README.md
  src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/persistence_middleware.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/system/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/system/system_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/system/system_slice.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/query_panel/components/editor_stack/resuable_editor.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
  src/plugins/explore/public/components/tabs/tabs.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: Skip-Changelog, explore

#10035 [Explore] Add tab storage and fix nav save
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/components/top_nav/top_nav_links/get_top_nav_links.ts
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_open/open_search_panel/open_search_panel.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.tsx
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_component.tsx
  src/plugins/explore/public/saved_explore/transforms.ts
  src/plugins/explore/public/types/saved_explore_types.ts
  src/plugins/explore/server/saved_objects/explore.ts
Labels: Skip-Changelog, distinguished-contributor

#9991 [Explore]add visualization to dashboard from Vis tab
  src/plugins/explore/opensearch_dashboards.json
  src/plugins/explore/public/application/legacy/discover/opensearch_dashboards_services.ts
  src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts
  src/plugins/explore/public/build_services.ts
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.tsx
  src/plugins/explore/public/components/visualizations/add_to_dashboard_button.tsx
  src/plugins/explore/public/components/visualizations/add_to_dashboard_modal.tsx
  src/plugins/explore/public/components/visualizations/style_panel/utils.tsx
  src/plugins/explore/public/components/visualizations/utils/add_to_dashboard.ts
  src/plugins/explore/public/components/visualizations/visualization_container.scss
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/helpers/save_explore.ts
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/public/types.ts
Labels: all-star-contributor

#10039 [Explore] Refactor use saved explore hook
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts
Labels: distinguished-contributor, failed changeset

#10032 fix datepicker locaiton in classic experience
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: distinguished-contributor, failed changeset

#10037 Update Area, Pie and Metric style panel UI
  src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/area/to_expression.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes.tsx
  src/plugins/explore/public/components/visualizations/style_panel/custom_ranges.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid/grid.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
  src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.tsx
Labels: distinguished-contributor, failed changeset

#10030 update banner font
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
Labels: distinguished-contributor, failed changeset

#10027 remove flavor from UI Slice
  src/plugins/explore/public/application/utils/state_management/README.md
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
Labels: distinguished-contributor, failed changeset

#10043 [Explore] Refactor query management: Fix query history and remove duplicate actions
  src/plugins/explore/public/application/components/header_dataset_selector.tsx
  src/plugins/explore/public/application/components/query_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/helpers/migrate_legacy_query.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/discover_table.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/update_search_source.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_index_pattern.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_search.ts
  src/plugins/explore/public/application/legacy/discover/migrate_state.ts
  src/plugins/explore/public/application/legacy/discover/migrate_states.test.ts
  src/plugins/explore/public/application/legacy/discover/ui_metric/report_ui_metric.ts
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.ts
  src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts
  src/plugins/explore/public/application/utils/interfaces.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.ts
  src/plugins/explore/public/application/utils/state_management/slices/system/system_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/query_panel/query_panel.tsx
  src/plugins/explore/public/components/results_summary/results_summary_panel.tsx
  src/plugins/explore/public/embeddable/types.ts
  src/plugins/explore/public/services/tab_registry/tab_registry_service.ts
  src/plugins/explore/public/url_generator.ts
Labels: Skip-Changelog, distinguished-contributor

#10024 [Explore] Add execute dispatch to histogram and quick select
  src/plugins/explore/public/application/legacy/discover/application/components/chart/chart.tsx
  src/plugins/explore/public/components/query_panel/components/footer/date_time_selector.tsx
  src/plugins/explore/public/components/query_panel/components/footer/index.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
Labels: Skip-Changelog, all-star-contributor

#10053 [Explore] tweaks visualization panel styles
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: distinguished-contributor, failed changeset

#10050 rework 9957
  src/plugins/data/public/query/saved_query/saved_query_service.ts
  src/plugins/explore/public/components/query_panel/components/editor_stack/editor_stack.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/prompt_editor.tsx
  src/plugins/explore/public/components/query_panel/components/footer/index.scss
  src/plugins/explore/public/components/query_panel/hooks/index.ts
  src/plugins/explore/public/components/query_panel/hooks/use_query_assist/index.ts
  src/plugins/explore/public/components/query_panel/hooks/use_query_assist/use_query_assist.ts
  src/plugins/explore/public/components/query_panel/index.scss
  src/plugins/explore/public/components/query_panel/query_panel.tsx
  src/plugins/explore/public/components/query_panel/utils/constants.ts
  src/plugins/explore/public/components/query_panel/utils/error.ts
Labels: distinguished-contributor, failed changeset

#10048 [Explore] Update fields selector grouping
  changelogs/fragments/10048.yml
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.test.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/group_fields.test.ts
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/group_fields.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
Labels: all-star-contributor

#10064 [Explore] Allow switch dataset to update recent query
  src/plugins/explore/public/application/components/header_dataset_selector.tsx
  src/plugins/explore/public/application/utils/state_management/__mocks__/chart_utils.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/data_factories.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/index.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/services.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/store.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts
Labels: Skip-Changelog, distinguished-contributor

#10055 [Explore] change name of add to dashboard modal
  changelogs/fragments/10055.yml
  src/plugins/explore/public/components/visualizations/add_to_dashboard_modal.tsx
Labels: all-star-contributor

#10062 [Explore] Update scatter style panel UI
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/to_expression.ts
Labels: all-star-contributor

#10069 [Explore] handle state correctly when switching dataset
  src/plugins/explore/public/application/components/header_dataset_selector.tsx
  src/plugins/explore/public/application/utils/get_prompt_mode_is_available/get_prompt_mode_is_available.test.ts
  src/plugins/explore/public/application/utils/get_prompt_mode_is_available/get_prompt_mode_is_available.ts
  src/plugins/explore/public/application/utils/get_prompt_mode_is_available/index.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/index.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
Labels: distinguished-contributor, failed changeset

#10072 [Explore] Move chart component to explore component folder
  changelogs/fragments/10072.yml
  src/plugins/explore/public/application/legacy/discover/application/components/chart/timechart_header/timechart_header.scss
  src/plugins/explore/public/application/legacy/discover/application/components/panel/canvas_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/discover_canvas.scss
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/discover_table.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/index.ts
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
  src/plugins/explore/public/components/chart/_histogram.scss
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/chart/chart.tsx
  src/plugins/explore/public/components/chart/discover_chart_container.scss
  src/plugins/explore/public/components/chart/discover_chart_container.tsx
  src/plugins/explore/public/components/chart/histogram/histogram.tsx
  src/plugins/explore/public/components/chart/histogram/type.ts
  src/plugins/explore/public/components/chart/timechart_header/index.ts
  src/plugins/explore/public/components/chart/timechart_header/timechart_header.test.tsx
  src/plugins/explore/public/components/chart/timechart_header/timechart_header.tsx
  src/plugins/explore/public/components/chart/utils/create_histogram_configs.ts
  src/plugins/explore/public/components/chart/utils/get_dimension.test.ts
  src/plugins/explore/public/components/chart/utils/get_dimensions.ts
  src/plugins/explore/public/components/chart/utils/index.ts
  src/plugins/explore/public/components/chart/utils/point_series.test.ts
  src/plugins/explore/public/components/chart/utils/point_series.ts
  src/plugins/explore/public/components/top_nav/top_nav.tsx
Labels: all-star-contributor

#10045 [Explore] Support PPL filters in Explore
  changelogs/fragments/10045.yml
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/explore/public/application/context/editor_context/editor_context.tsx
  src/plugins/explore/public/application/hooks/editor_hooks/index.ts
  src/plugins/explore/public/application/hooks/editor_hooks/use_change_query_editor.test.ts
  src/plugins/explore/public/application/hooks/editor_hooks/use_change_query_editor.ts
  src/plugins/explore/public/application/hooks/index.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/search/filters/filter_utils.test.ts
  src/plugins/query_enhancements/public/search/filters/filter_utils.ts
  src/plugins/query_enhancements/public/search/filters/index.ts
  src/plugins/query_enhancements/public/search/filters/natural_language_filter_utils.test.ts
  src/plugins/query_enhancements/public/search/filters/natural_language_filter_utils.ts
  src/plugins/query_enhancements/public/search/filters/parser.ts
  src/plugins/query_enhancements/public/search/filters/ppl_filter_utils.test.ts
  src/plugins/query_enhancements/public/search/filters/ppl_filter_utils.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.test.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Labels: all-star-contributor

#10077 fix some broken unit tests
  src/plugins/explore/public/application/utils/state_management/__mocks__/chart_utils.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.test.ts
  src/plugins/explore/public/components/query_panel/editor_stack/edit_toolbar/edit_toolbar.test.tsx
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
Labels: distinguished-contributor, failed changeset

#10080 [Explore] Replace custom query error handling with QueryResult component
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/index.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.test.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.test.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.test.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/state_management/__mocks__/chart_utils.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.ts
  src/plugins/explore/public/application/utils/state_management/types.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/query_panel/footer/query_error.test.tsx
  src/plugins/explore/public/components/query_panel/footer/query_error.tsx
  src/plugins/explore/public/components/query_panel/footer/query_panel_footer.test.tsx
  src/plugins/explore/public/components/query_panel/footer/query_panel_footer.tsx
  src/plugins/explore/public/components/query_panel/footer/types.ts
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
  src/plugins/explore/public/components/top_nav/top_nav.tsx
Labels: Skip-Changelog, distinguished-contributor

#10067 [Explore] Add axes selector on style panel
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
  src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/to_expression.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_container_utils.ts
  src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/saved_explore/transforms.ts
Labels: Skip-Changelog, seasoned-contributor

#10084 [Explore] fix saved explore cannot open from a dashboard
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/components/top_nav/top_nav.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_factory.tsx
  src/plugins/explore/public/plugin.ts
Labels: distinguished-contributor, failed changeset

#10085 [Explore] turn on grid in scatter
  changelogs/fragments/10085.yml
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/standard_axes_options.tsx
Labels: all-star-contributor

#10086 [Explore] tweaks styles panel and use compressed style components
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/exclusive_style.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/chart_type_switcher.tsx
  src/plugins/explore/public/components/visualizations/style_panel/custom_ranges.tsx
  src/plugins/explore/public/components/visualizations/style_panel/general_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/standard_axes_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/style_accordion.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/utils.tsx
  src/plugins/explore/public/components/visualizations/visualization.tsx
Labels: distinguished-contributor, failed changeset

#10087 [Explore] Add axes select support for other chat types
  src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/area/to_expression.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/to_expression.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/to_expression.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/to_expression.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_chart_utils.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/standard_axes_options.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/utils/utils.ts
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: Skip-Changelog, seasoned-contributor

#10091 [Explore] Fix recent query bug to allow run query update query history via middleware
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts
  src/plugins/explore/public/components/top_nav/top_nav.tsx
Labels: Skip-Changelog, distinguished-contributor

#10092 [Explore] Update explore chart UI
  changelogs/fragments/10092.yml
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/components/chart/_histogram.scss
  src/plugins/explore/public/components/chart/chart.tsx
  src/plugins/explore/public/components/chart/discover_chart_container.scss
  src/plugins/explore/public/components/chart/discover_chart_container.tsx
  src/plugins/explore/public/components/chart/histogram/histogram.tsx
  src/plugins/explore/public/components/chart/timechart_header/timechart_header.tsx
Labels: all-star-contributor

#10094 support key-value
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
Labels: distinguished-contributor, failed changeset

#10096 [Explore] fix Viz tab scroll and resize behavior
  changelogs/fragments/10096.yml
  src/plugins/explore/public/application/register_tabs.ts
  src/plugins/explore/public/components/tabs/tabs.scss
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.scss
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: all-star-contributor

#10097 fix options for top_editor
  src/plugins/explore/public/components/query_panel/utils/use_top_editor/use_top_editor.ts
Labels: distinguished-contributor, failed changeset

#10076 [Explore] only allow PPL to be filterable in explore and dashboards
  src/plugins/query_enhancements/public/plugin.tsx
Labels: Skip-Changelog, all-star-contributor

#10095 Add Documentations for PPL Commands
  changelogs/fragments/10095.yml
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/ppl_documentation.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.ts
  src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts
Labels: distinguished-contributor

#10089 [Explore] add tests and storybook in style panel
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/standard_axes_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/standard_axes_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/standard_axes_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/general_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/general_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/general_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid/grid.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid/grid.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/index.ts
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.tsx
  src/plugins/explore/public/components/visualizations/style_panel/style_accordion.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/utils.test.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.tsx
Labels: all-star-contributor

#10108 [Explore] fix duplicated completion provider registration
  src/plugins/explore/public/components/query_panel/utils/types.ts
  src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.test.tsx
  src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.ts
Labels: Skip-Changelog, all-star-contributor

#10110 Filter out Null Values in Suggestions
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
Labels: distinguished-contributor

#10113 [Explore] fix a issue that cause chart time range update unexpectedly
  changelogs/fragments/10113.yml
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/chart/chart.tsx
Labels: all-star-contributor

#10114 save to query string manager with source
  src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.test.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.test.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.test.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/hooks/use_tab_results.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_tab_results.ts
  src/plugins/explore/public/application/utils/languages/index.ts
  src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.ts
  src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/index.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/index.ts
  src/plugins/explore/public/application/utils/languages/ppl/index.ts
  src/plugins/explore/public/application/utils/languages/ppl/strip_stats_from_query/index.ts
  src/plugins/explore/public/application/utils/languages/ppl/strip_stats_from_query/strip_stats_from_query.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/strip_stats_from_query/strip_stats_from_query.ts
  src/plugins/explore/public/application/utils/languages/types.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/store.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.ts
  src/plugins/explore/public/components/chart/discover_chart_container.tsx
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
Labels: distinguished-contributor, failed changeset

#10121 [Explore] Fix axes select not get update when we click switch axes button and add unit tests
  src/plugins/explore/public/components/visualizations/chart_type_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_container_utils.test.ts
Labels: Skip-Changelog, seasoned-contributor

#10112 Add auto-version increment workflow
  .github/workflows/version-increment.yml
Labels: Skip-Changelog, repeat-contributor

#10127 Fix Antlr to Moncao Token Mappings
  changelogs/fragments/10127.yml
  packages/osd-monaco/src/ppl/constants.ts
  src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts
Labels: distinguished-contributor

#10130 Feature/icon in left nav
  changelogs/fragments/10021.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/shared_links.spec.js
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_groups.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/simple_popover.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/simple_popover.test.tsx
  src/core/public/chrome/ui/header/simple_popover.tsx
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/discover/public/plugin.ts
  src/plugins/home/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, distinguished-contributor

#10131 [Explore] added table type visualization
  src/plugins/data/common/osd_field_types/types.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts
  src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
  src/plugins/explore/public/components/visualizations/constants.ts
  src/plugins/explore/public/components/visualizations/table/table_vis.test.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/table/table_vis_config.ts
  src/plugins/explore/public/components/visualizations/table/table_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis_options.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
  src/plugins/explore/public/embeddable/explore_embeddable.test.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_component.tsx
Labels: Skip-Changelog, distinguished-contributor

#10099 [Explore] fix linting errors
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/visualization.stories.tsx
  src/plugins/explore/public/components/visualizations/visualization.test.tsx
Labels: Skip-Changelog, distinguished-contributor

#10128 [Explore] Query editor style update
  src/plugins/explore/public/components/query_panel/editor_stack/bottom_editor/bottom_editor.scss
  src/plugins/explore/public/components/query_panel/editor_stack/bottom_editor/bottom_editor.test.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/bottom_editor/bottom_editor.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/edit_toolbar/edit_toolbar.scss
  src/plugins/explore/public/components/query_panel/editor_stack/edit_toolbar/edit_toolbar.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.scss
  src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.test.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/edit_toolbar/edit_toolbar.scss
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/edit_toolbar/edit_toolbar.stories.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/edit_toolbar/edit_toolbar.test.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/edit_toolbar/edit_toolbar.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/edit_toolbar/index.ts
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.scss
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.test.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.tsx
  src/plugins/explore/public/components/query_panel/footer/filter_panel_toggle/filter_panel_toggle.scss
  src/plugins/explore/public/components/query_panel/footer/query_panel_footer.scss
  src/plugins/explore/public/components/query_panel/footer/query_panel_footer.test.tsx
  src/plugins/explore/public/components/query_panel/footer/recent_queries_button/recent_queries_button.scss
  src/plugins/explore/public/components/query_panel/footer/save_query/save_query.scss
  src/plugins/explore/public/components/query_panel/query_panel.scss
  src/plugins/explore/public/components/query_panel/query_panel.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
  src/plugins/explore/public/components/query_panel/shared.scss
  src/plugins/explore/public/components/query_panel/utils/editor_options/prompt_editor_options.ts
  src/plugins/explore/public/components/query_panel/utils/editor_options/query_editor_options.ts
  src/plugins/explore/public/components/query_panel/utils/editor_options/shared.ts
  src/plugins/explore/public/components/query_panel/utils/types.ts
  src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.test.tsx
  src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.ts
  src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts
Labels: distinguished-contributor, failed changeset

#10106 [Explore] Add dynamic tab selection based on visualization compatibility
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.ts
  src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
  src/plugins/explore/public/application/utils/hooks/use_tab_results.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_tab_results.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/data_factories.ts
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.ts
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/index.ts
  src/plugins/explore/public/application/utils/state_management/actions/export_actions.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.ts
  src/plugins/explore/public/application/utils/state_management/actions/transaction_actions.ts
  src/plugins/explore/public/application/utils/state_management/middleware/overall_status_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/overall_status_middleware.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.ts
  src/plugins/explore/public/application/utils/state_management/slices/results/results_slice.ts
  src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/chart/chart.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.tsx
  src/plugins/explore/public/components/query_panel/footer/query_panel_footer.test.tsx
  src/plugins/explore/public/components/query_panel/footer/query_panel_footer.tsx
  src/plugins/explore/public/components/query_panel/footer/save_query/save_query.stories.tsx
  src/plugins/explore/public/components/query_panel/footer/save_query/save_query.test.tsx
  src/plugins/explore/public/components/query_panel/footer/save_query/save_query.tsx
  src/plugins/explore/public/components/query_panel/utils/use_time_filter/use_time_filter.test.tsx
  src/plugins/explore/public/components/query_panel/utils/use_time_filter/use_time_filter.ts
  src/plugins/explore/public/components/tabs/tabs.test.tsx
  src/plugins/explore/public/components/tabs/tabs.tsx
Labels: Skip-Changelog, distinguished-contributor

#10141 [Explore] Fix new
  src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.ts
  src/plugins/explore/public/components/top_nav/top_nav.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/get_top_nav_links.test.ts
  src/plugins/explore/public/components/top_nav/top_nav_links/get_top_nav_links.ts
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.test.ts
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.ts
Labels: distinguished-contributor, failed changeset

#10129 [Explore] Style panel UX changes
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/line/line_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/legend/legend.tsx
  src/plugins/explore/public/components/visualizations/style_panel/style_accordion.scss
  src/plugins/explore/public/components/visualizations/style_panel/style_accordion.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
  src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: Skip-Changelog, seasoned-contributor

#10152 Add Bar Size Control Switch
  changelogs/fragments/10152.yml
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
Labels: repeat-contributor

#10021 [Navigation] Support icon in left navigation
  changelogs/fragments/10021.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/shared_links.spec.js
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_groups.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/simple_popover.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/simple_popover.test.tsx
  src/core/public/chrome/ui/header/simple_popover.tsx
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/discover/public/plugin.ts
  src/plugins/home/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
  src/plugins/workspace/public/plugin.ts
Labels: distinguished-contributor

#10134 [explore] dataset select bug fixes and clean up
  current_design.txt
  docs/_sidebar.md
  docs/plugins/data/datasets/data_views.md
  src/plugins/data/common/data_views/data_views/_view_cache.ts
  src/plugins/data/common/data_views/data_views/data_view.test.ts
  src/plugins/data/common/data_views/data_views/data_view.ts
  src/plugins/data/common/data_views/data_views/data_views.test.ts
  src/plugins/data/common/data_views/data_views/data_views.ts
  src/plugins/data/common/data_views/data_views/index.ts
  src/plugins/data/common/data_views/lib/validate_data_view.test.ts
  src/plugins/data/common/data_views/types.ts
  src/plugins/data/common/index_patterns/types.ts
  src/plugins/data/public/data_views/data_views/redirect_no_data_view.tsx
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/dataset_select/_dataset_select.scss
  src/plugins/data/public/ui/dataset_select/dataset_details.tsx
  src/plugins/data/public/ui/dataset_select/dataset_select.tsx
  src/plugins/explore/public/application/context/dataset_context/dataset_context.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/get_prompt_mode_is_available/get_prompt_mode_is_available.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.ts
  src/plugins/explore/public/components/data_table/data_view_adapter.tsx
  src/plugins/explore/public/components/top_nav/top_nav.tsx
Labels: Skip-Changelog, distinguished-contributor, explore, datasets

#10154 Reorder Autocomplete Suggestions
  package.json
  packages/osd-monaco/src/ppl/language.ts
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.ts
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: distinguished-contributor

#10149 [Explore] Loader for prompt to query
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/on_editor_run/call_agent/call_agent.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/on_editor_run/call_agent/call_agent.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.test.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.tsx
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.scss
  src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.tsx
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
Labels: distinguished-contributor, failed changeset

#10142 [explore] reset store when unmounting app
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/plugin.ts
Labels: Skip-Changelog, distinguished-contributor

#10158 [Explore] Fix a issue causing unnecessary saved object fetch and top nav loading icon flicker
  changelogs/fragments/10158.yml
  src/plugins/explore/public/application/pages/logs/logs_page.test.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.test.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.test.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_container.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_container.tsx
Labels: all-star-contributor

#10159 Fix unit tests and add coverage for explore vis
  src/plugins/explore/public/components/visualizations/area/area_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/area/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/pie/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/rule_repository.test.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/visualization.test.tsx
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.test.ts
Labels: distinguished-contributor, failed changeset

#10140 [Explore] Change fields selector default setting to show missing fields
  changelogs/fragments/10140.yml
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_field_search.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_filter.test.ts
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_filter.ts
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/tabs/action_bar/action_bar.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv.tsx
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.tsx
  src/plugins/explore/public/components/visualizations/add_to_dashboard_button.tsx
Labels: all-star-contributor

#10162 [Explore] Improve UT coverage in chart component
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/chart/discover_chart_container.test.tsx
  src/plugins/explore/public/components/chart/histogram/histogram.test.tsx
  src/plugins/explore/public/components/chart/histogram/type.test.ts
  src/plugins/explore/public/components/chart/utils/create_histogram_configs.test.ts
  src/plugins/explore/public/components/tabs/patterns_tab.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/url_generator.ts
Labels: Skip-Changelog, all-star-contributor

#10187 [Explore] Reorganize and rewrite a clean query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
Labels: distinguished-contributor, failed changeset

#10178 Fix ts errors in explore public folder
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/discover/public/__mock__/index_pattern_mock.ts
  src/plugins/discover/public/actions/abort_data_query_action.test.ts
  src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/discover/public/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
  src/plugins/explore/public/application/legacy/discover/__mock__/index_pattern_mock.ts
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
  src/plugins/explore/public/application/legacy/discover/application/helpers/popularize_field.test.ts
  src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/rule_repository.test.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.test.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.test.tsx
  src/plugins/expressions/common/expression_types/expression_type.test.ts
  src/plugins/expressions/common/mocks.ts
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/__snapshots__/help_flyout.test.tsx.snap
Labels: Skip-Changelog, distinguished-contributor

#10168 [datasets] style improvements for dataset select
  src/plugins/data/public/ui/dataset_select/_dataset_details.scss
  src/plugins/data/public/ui/dataset_select/_dataset_select.scss
  src/plugins/data/public/ui/dataset_select/dataset_details.tsx
  src/plugins/data/public/ui/dataset_select/dataset_select.tsx
Labels: Skip-Changelog, distinguished-contributor, explore, datasets

#10169 [Explore] Improve UT coverage for topNav component
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_open/open_search_panel/open_search_panel.test.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.test.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_share/helpers.test.ts
Labels: Skip-Changelog, all-star-contributor

#10171 [Explore] Move field selector component out of legacy folder
  src/plugins/explore/public/application/legacy/discover/application/components/default_discover_table/table_header.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/index.ts
  src/plugins/explore/public/components/chart/discover_chart_container.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_container.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.tsx
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/fields_selector/discover_field.scss
  src/plugins/explore/public/components/fields_selector/discover_field.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_bucket.scss
  src/plugins/explore/public/components/fields_selector/discover_field_bucket.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_data_frame.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_details.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_details.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_search.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_search.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.scss
  src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.tsx
  src/plugins/explore/public/components/fields_selector/fields_selector_panel.tsx
  src/plugins/explore/public/components/fields_selector/index.ts
  src/plugins/explore/public/components/fields_selector/lib/display_index_pattern_creation.tsx
  src/plugins/explore/public/components/fields_selector/lib/field_calculator.test.ts
  src/plugins/explore/public/components/fields_selector/lib/field_calculator.ts
  src/plugins/explore/public/components/fields_selector/lib/field_filter.test.ts
  src/plugins/explore/public/components/fields_selector/lib/field_filter.ts
  src/plugins/explore/public/components/fields_selector/lib/get_details.ts
  src/plugins/explore/public/components/fields_selector/lib/get_field_type_name.ts
  src/plugins/explore/public/components/fields_selector/lib/get_index_pattern_field_list.ts
  src/plugins/explore/public/components/fields_selector/lib/get_warnings.ts
  src/plugins/explore/public/components/fields_selector/lib/group_fields.test.ts
  src/plugins/explore/public/components/fields_selector/lib/group_fields.ts
  src/plugins/explore/public/components/fields_selector/lib/visualize_trigger_utils.ts
  src/plugins/explore/public/components/fields_selector/string_progress_bar.tsx
  src/plugins/explore/public/components/fields_selector/types.ts
  src/plugins/explore/public/components/panel/canvas_panel.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_share/helpers.ts
  src/plugins/explore/public/helpers/view_component_utils/filter_columns.test.ts
  src/plugins/explore/public/helpers/view_component_utils/filter_columns.ts
  src/plugins/explore/public/helpers/view_component_utils/get_default_sort.ts
  src/plugins/explore/public/helpers/view_component_utils/get_sort.test.ts
  src/plugins/explore/public/helpers/view_component_utils/get_sort.ts
  src/plugins/explore/public/helpers/view_component_utils/get_sort_for_search_source.ts
Labels: Skip-Changelog, all-star-contributor

#10194 [Explore] Fix set dataset change editor mode
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.ts
Labels: distinguished-contributor, failed changeset

#10199 fix ut for query_action
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
Labels: distinguished-contributor, failed changeset

#10198 Fix explore plugin query panel reset on page reload due to DatasetSelect initialization
  src/plugins/data/public/ui/dataset_select/dataset_select.tsx
Labels: Skip-Changelog, distinguished-contributor

#10195 [Explore] Fix UT mock
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
  src/plugins/explore/public/components/container/bottom_container/bottom_container.test.tsx
  src/plugins/explore/public/components/data_table/explore_data_table.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_details.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx
  src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_share/helpers.test.ts
  src/plugins/explore/public/helpers/view_component_utils/filter_columns.test.ts
Labels: Skip-Changelog, distinguished-contributor

#10200 Fix unit tests for explore vis
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
Labels: distinguished-contributor, failed changeset

#10204 [Explore] Fix type and ut
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
Labels: distinguished-contributor, failed changeset

#10206 [Explore] fix bar tests
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
Labels: Skip-Changelog, distinguished-contributor

#10116 [Explore] Fixing Cypress integration tests
  .github/workflows/cypress_workflow.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/saved_explore.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/simple_dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/language_specific_display.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/time_range_selection.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/caching.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/download_csv.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/shared_links.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/table.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/histogram_interaction.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_more.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_query.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_switch.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/recent_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/sidebar.spec.js
  cypress/utils/apps/explore/autocomplete.js
  cypress/utils/apps/explore/dataset_selector.js
  cypress/utils/apps/explore/download_csv.js
  cypress/utils/apps/explore/saved.js
  cypress/utils/apps/explore/saved_queries.js
  cypress/utils/apps/explore/simple_dataset_selector.js
  cypress/utils/commands.explore.js
  cypress/utils/commands.osd.js
Labels: Skip-Changelog, all-star-contributor

#10224 [Manual Backport 2.19] Fix GHSA-vjh7-7g9h-fjfh by bumping elliptic
  package.json
  yarn.lock
Labels: cve, Skip-Changelog

#10234 add release notes for 2.19.3
  CHANGELOG.md
  changelogs/fragments/9843.yml
  release-notes/opensearch-dashboards.release-notes-2.19.3.md
Labels: Skip-Changelog

#10251 Fix banner text font and alignment
  changelogs/fragments/10251.yml
  src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.scss
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.scss
Labels: seasoned-contributor

#10240 [Left navigation] fix: type to allow euiIconType / icon to be undefined
  changelogs/fragments/10240.yml
  src/core/public/chrome/nav_group/nav_group_service.ts
Labels: distinguished-contributor

#10254 Reset baseline limit for dashboard and discover
  baselines/lighthouse_baseline.json
  changelogs/fragments/10254.yml
Labels: seasoned-contributor

#10250 [Autocomplete] Fix parse command
  packages/osd-antlr-grammar/src/index.ts
  packages/osd-monaco/ppl-test.html
  packages/osd-monaco/src/xjson/lexer_rules/opensearchppl.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/data/public/antlr/opensearch_ppl/simplified_ppl_grammar/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
Labels: distinguished-contributor

#10260 [Explore] handle the PPL query that starts with "show"
  changelogs/fragments/10260.yml
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
Labels: distinguished-contributor

#10259 [Explore] minor update on the edit query placement
  changelogs/fragments/10259.yml
  src/plugins/explore/public/components/query_panel/query_panel_editor/query_panel_editor.scss
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.scss
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.tsx
Labels: distinguished-contributor

#10261 [Explore] Update field selector collapse UI
  changelogs/fragments/10261.yml
  cypress/utils/apps/explore/sidebar.js
  src/plugins/explore/public/application/utils/state_management/__mocks__/store.ts
  src/plugins/explore/public/application/utils/state_management/actions/export_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/chart/discover_chart_container.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_container.test.tsx
  src/plugins/explore/public/components/container/bottom_container/bottom_container.tsx
  src/plugins/explore/public/components/data_table/explore_data_table.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_header.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_header.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.scss
  src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.tsx
  src/plugins/explore/public/components/fields_selector/fields_selector_panel.test.tsx
  src/plugins/explore/public/components/fields_selector/fields_selector_panel.tsx
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/filter_panel_toggle/filter_panel_toggle.scss
  src/plugins/explore/public/components/query_panel/query_panel_widgets/filter_panel_toggle/filter_panel_toggle.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/filter_panel_toggle/filter_panel_toggle.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/filter_panel_toggle/filter_panel_toggle.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/filter_panel_toggle/index.ts
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.tsx
  src/plugins/explore/public/components/tabs/tabs.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
Labels: distinguished-contributor

#10229 [Explore] Add title options in style panel
  src/plugins/explore/public/components/visualizations/area/area_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
  src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/area/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/area/to_expression.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/to_expression.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/line/to_expression.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/pie/to_expression.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/scatter/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
  src/plugins/explore/public/components/visualizations/style_panel/title/title.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/title/title.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/title/title.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/visualization.stories.tsx
Labels: Skip-Changelog, seasoned-contributor

#10132 [Left nav] Update navigation footer to comply with latest design
  changelogs/fragments/10132.yml
  cypress/utils/commands.js
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
  src/core/public/chrome/ui/header/collapsible_nav_groups.tsx
  src/core/public/chrome/ui/header/header_help_menu.test.tsx
  src/core/public/chrome/ui/header/header_help_menu.tsx
  src/core/public/chrome/ui/header/left_bottom_action_button.scss
  src/core/public/chrome/ui/header/left_bottom_action_button.test.tsx
  src/core/public/chrome/ui/header/left_bottom_action_button.tsx
  src/core/public/chrome/ui/index.ts
  src/core/public/index.ts
  src/core/utils/default_app_categories.ts
  src/plugins/dev_tools/public/dev_tools_icon.test.tsx
  src/plugins/dev_tools/public/dev_tools_icon.tsx
  src/plugins/dev_tools/public/dev_tools_modal.scss
  src/plugins/dev_tools/public/dev_tools_modal.test.tsx
  src/plugins/dev_tools/public/dev_tools_modal.tsx
  src/plugins/dev_tools/public/plugin.test.ts
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/home/public/application/components/home_icon.test.tsx
  src/plugins/home/public/application/components/home_icon.tsx
  src/plugins/home/public/plugin.ts
  src/plugins/management/public/components/settings_icon.tsx
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
  src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.test.ts
  src/plugins/workspace/public/services/use_case_service.ts
Labels: distinguished-contributor

#10263 [TEST] add cypress test for default vis on rule matching
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/10263.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis.spec.js
  package.json
  src/plugins/explore/public/components/visualizations/line/line_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/visualization.tsx
Labels: distinguished-contributor

#10284 Update oui to 1.21
  changelogs/fragments/10284.yml
  package.json
  packages/osd-ui-framework/package.json
  packages/osd-ui-shared-deps/package.json
  test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
  test/plugin_functional/plugins/osd_sample_panel_action/package.json
  test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
  yarn.lock
Labels: distinguished-contributor

#10281 [Explore] fix osd url state not synced correctly
  changelogs/fragments/10281.yml
  src/plugins/explore/public/application/utils/hooks/use_url_state_sync.ts
  src/plugins/explore/public/components/fields_selector/discover_field_header.tsx
Labels: distinguished-contributor

#10282 Fix Doc Version Tests
  changelogs/fragments/10282.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js
Labels: distinguished-contributor

#9983 Increment version to 3.2.0
  package.json
Labels: valued-contributor, failed changeset

#10274 [Explore] Segregate Keywords into Commands, Operators , Functions in Suggestions
  changelogs/fragments/10274.yml
  cypress/utils/apps/explore/autocomplete.js
  cypress/utils/apps/query_enhancements/autocomplete.js
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.test.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx
Labels: distinguished-contributor

#10300 [explore] - new search to search
  src/plugins/explore/public/components/top_nav/top_nav.tsx
Labels: Skip-Changelog, distinguished-contributor

#10264 [Banner Plugin] Integrate UI Settings Support for Configurable Global Banner
  changelogs/fragments/10264.yml
  src/.i18nrc.json
  src/plugins/banner/public/components/global_banner.test.tsx
  src/plugins/banner/public/components/global_banner.tsx
  src/plugins/banner/public/plugin.ts
  src/plugins/banner/public/render_banner.test.ts
  src/plugins/banner/public/render_banner.ts
  src/plugins/banner/public/types.ts
  src/plugins/banner/server/index.ts
  src/plugins/banner/server/plugin.test.ts
  src/plugins/banner/server/plugin.ts
  src/plugins/banner/server/routes/get_config.test.ts
  src/plugins/banner/server/routes/get_config.ts
  src/plugins/banner/server/ui_settings.ts
Labels: repeat-contributor, banner

#10302 Add Tests for Filter In/ Filter Out Actions in Explore
  changelogs/fragments/10302.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/field_display_filtering.spec.js
  cypress/utils/apps/explore/autocomplete.js
Labels: distinguished-contributor

#10265 [Explore] Move datepicker and run button to global header
  changelogs/fragments/10265.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_query.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/s3_tests/s3_dataset.spec.js
  cypress/utils/apps/explore/saved.js
  cypress/utils/commands.explore.js
  src/plugins/data/public/index.ts
  src/plugins/explore/public/application/hooks/editor_hooks/use_change_query_editor/use_change_query_editor.test.ts
  src/plugins/explore/public/application/hooks/editor_hooks/use_change_query_editor/use_change_query_editor.ts
  src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.ts
  src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/services.ts
  src/plugins/explore/public/application/utils/state_management/__mocks__/store.ts
  src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.ts
  src/plugins/explore/public/application/utils/state_management/actions/export_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/on_editor_run/on_editor_run.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/on_editor_run/on_editor_run.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/timefilter_sync_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/timefilter_sync_middleware.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
  src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.test.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.ts
  src/plugins/explore/public/application/utils/state_management/store.test.ts
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/chart/chart.test.tsx
  src/plugins/explore/public/components/chart/chart.tsx
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.test.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.ts
  src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/date_time_range_picker/date_time_range_picker.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/date_time_range_picker/date_time_range_picker.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/date_time_range_picker/date_time_range_picker.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/run_query_button/index.ts
  src/plugins/explore/public/components/query_panel/query_panel_widgets/run_query_button/run_query_button.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/run_query_button/run_query_button.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/run_query_button/run_query_button.tsx
  src/plugins/explore/public/components/top_nav/query_execution_button/index.ts
  src/plugins/explore/public/components/top_nav/query_execution_button/query_execution_button.stories.tsx
  src/plugins/explore/public/components/top_nav/query_execution_button/query_execution_button.test.tsx
  src/plugins/explore/public/components/top_nav/query_execution_button/query_execution_button.tsx
  src/plugins/explore/public/components/top_nav/top_nav.tsx
  src/plugins/explore/public/components/top_nav/utils/validate_time_range.test.ts
  src/plugins/explore/public/components/top_nav/utils/validate_time_range.ts
  src/plugins/navigation/public/top_nav_menu/_index.scss
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.test.tsx
  src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Labels: distinguished-contributor, explore

#10310 Add Test to validate PPL query not starting with source
  changelogs/fragments/10310.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_more.spec.js
Labels: distinguished-contributor

#10269 [explore] move dataset select to query panel widgets
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/10269.yml
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/caching.spec.js
  cypress/utils/commands.explore.js
  src/plugins/data/common/constants.ts
  src/plugins/data/common/data_views/data_view.stub.ts
  src/plugins/data/common/data_views/data_views/data_view.ts
  src/plugins/data/common/data_views/data_views/data_views.ts
  src/plugins/data/common/data_views/index.ts
  src/plugins/data/common/data_views/lib/get_from_saved_object.ts
  src/plugins/data/common/data_views/types.ts
  src/plugins/data/common/data_views/utils.ts
  src/plugins/data/common/index_patterns/index_pattern.stub.ts
  src/plugins/data/common/index_patterns/lib/get_from_saved_object.ts
  src/plugins/data/common/index_patterns/types.ts
  src/plugins/data/public/data_views/data_views/redirect_no_data_view.tsx
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/ui/dataset_select/_dataset_details.scss
  src/plugins/data/public/ui/dataset_select/_dataset_select.scss
  src/plugins/data/public/ui/dataset_select/dataset_details.tsx
  src/plugins/data/public/ui/dataset_select/dataset_select.stories.tsx
  src/plugins/data/public/ui/dataset_select/dataset_select.tsx
  src/plugins/data/public/ui/dataset_select/index.tsx
  src/plugins/explore/public/application/context/dataset_context/dataset_context.tsx
  src/plugins/explore/public/application/legacy/discover/opensearch_dashboards_services.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.ts
  src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.test.ts
  src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.ts
  src/plugins/explore/public/application/utils/state_management/store.test.ts
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/build_services.ts
  src/plugins/explore/public/components/data_table/data_view_adapter.tsx
  src/plugins/explore/public/components/fields_selector/lib/get_index_pattern_field_list.ts
  src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.ts
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/index.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/query_panel_widgets.tsx
  src/plugins/explore/public/components/top_nav/top_nav.tsx
  src/plugins/explore/public/types.ts
  src/plugins/query_enhancements/public/search/filters/filter_utils.test.ts
Labels: distinguished-contributor, explore, datasets

#10307 [TEST] Unskip saved queries test for explore
  changelogs/fragments/10307.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js
Labels: distinguished-contributor
