Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-06, with the labels that each got.

#9833 [Explore] fix ciGroup15 for explore
  .github/workflows/cypress_workflow.yml
Labels: Skip-Changelog, all-star-contributor

#9848 [Fix] Revert workspaces=* and add warning log
  changelogs/fragments/9848.yml
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: distinguished-contributor

#9850 Fix broken CI job
  .github/workflows/links_checker.yml
  .lycheeignore
  ts_error_baseline.json
Labels: Skip-Changelog, seasoned-contributor

#9803 [Chore] Clean up workspace type error
  src/plugins/workspace/public/components/add_collaborators_modal/index.ts
  src/plugins/workspace/public/components/data_source_association/data_source_association.test.tsx
  src/plugins/workspace/public/components/global_search/search_pages_command.test.tsx
  src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
  src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
  src/plugins/workspace/public/components/workspace_detail_app.tsx
  src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
  src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_list/default_workspace.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx
  src/plugins/workspace/public/components/workspace_use_case_overview_app.test.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/register_default_collaborator_types.test.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/public/workspace_client.mock.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/duplicate.test.ts
  src/plugins/workspace/server/permission_control/client.mock.ts
  src/plugins/workspace/server/routes/index.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  ts_error_baseline.json
Labels: repeat-contributor, failed changeset

#9847 Add raintygao as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: Skip-Changelog, distinguished-contributor

#9844 Remove Migrations for Explore App
  src/plugins/explore/server/saved_objects/search.ts
  src/plugins/explore/server/saved_objects/search_migrations.test.ts
  src/plugins/explore/server/saved_objects/search_migrations.ts
Labels: distinguished-contributor, explore

#9849 [Explore] Add tabs in explore, add data table to log tab
  changelogs/fragments/9849.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/field_display_filtering.spec.js
  src/plugins/explore/public/application/legacy/discover/application/components/chart/hits_counter/hits_counter.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer_render_tab.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer_tab.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/download_csv/download_csv.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/download_csv/use_download_csv.ts
  src/plugins/explore/public/application/legacy/discover/application/components/results_action_bar/results_action_bar.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.test.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_calculator.test.ts
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_calculator.ts
  src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/get_details.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/index.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_search.ts
  src/plugins/explore/public/application/legacy/discover/opensearch_dashboards_services.ts
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/tabs/tabs.scss
  src/plugins/explore/public/components/tabs/tabs.stories.tsx
  src/plugins/explore/public/components/tabs/tabs.tsx
  src/plugins/explore/public/helpers/data_table_helper.tsx
  src/plugins/explore/public/plugin.ts
Labels: explore

#9842 [Explore] create new explore/discover experience banners
  changelogs/fragments/9842.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js
  src/plugins/explore/public/application/legacy/data_explorer/application.tsx
  src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.scss
  src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.stories.tsx
  src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.test.tsx
  src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.tsx
  src/plugins/explore/public/components/experience_banners/classic_experience_banner/index.ts
  src/plugins/explore/public/components/experience_banners/constants.ts
  src/plugins/explore/public/components/experience_banners/create_query_editor_extension_config.test.tsx
  src/plugins/explore/public/components/experience_banners/create_query_editor_extension_config.tsx
  src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.stories.tsx
  src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.test.tsx
  src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.tsx
  src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/index.ts
  src/plugins/explore/public/components/experience_banners/index.ts
  src/plugins/explore/public/components/experience_banners/new_experience_banner/index.ts
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.scss
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.stories.tsx
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.test.tsx
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.tsx
  src/plugins/explore/public/plugin.ts
Labels: all-star-contributor, explore

#9816 [Feature] Vended Dashboard Synchronization
  changelogs/fragments/9816.yml
  src/plugins/data_source_management/config.ts
  src/plugins/data_source_management/framework/hooks/direct_query_hook.tsx
  src/plugins/data_source_management/framework/types.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_sync/direct_query_sync_banner.scss
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_sync/direct_query_sync_banner.test.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_sync/direct_query_sync_banner.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_sync/direct_query_sync_utils.test.ts
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_sync/direct_query_sync_utils.ts
  src/plugins/data_source_management/public/components/frame_work_test/hooks/drect_query_hook.test.tsx
  src/plugins/data_source_management/public/constants.ts
  src/plugins/data_source_management/public/index.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/data_source_management/public/plugin.test.ts
  src/plugins/data_source_management/public/plugin.ts
  src/plugins/opensearch_dashboards_utils/public/index.ts
  src/plugins/opensearch_dashboards_utils/public/state_management/url/index.ts
  ts_error_baseline.json
Labels: seasoned-contributor, v3.1.0

#9855 [Improvement] Add two integration tests for workspace=*
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
Labels: Skip-Changelog, distinguished-contributor

#9857 Update @testing-library/user-event version
  changelogs/fragments/9857.yml
  package.json
  src/plugins/explore/public/components/data_table/data_table.test.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer.test.tsx
  yarn.lock
Labels: all-star-contributor

#9843 Bump version to 2.19.3
  changelogs/fragments/9843.yml
  package.json
Labels: v2.19.3

#9853 [Chore] Remove alias in permission controlled UI settings wrapper
  src/core/server/ui_settings/saved_objects/permission_controlled_ui_settings_wrapper.test.ts
  src/core/server/ui_settings/saved_objects/permission_controlled_ui_settings_wrapper.ts
Labels: Skip-Changelog, valued-contributor

#9863 docs: Update maintainer responsibilies on merging
  MAINTAINERS.md
  changelogs/fragments/9863.yml
Labels: seasoned-contributor

#9834 [Explore] Line chart auto visualization
  changelogs/fragments/9834.yml
  src/plugins/data/common/osd_field_types/types.ts
  src/plugins/explore/opensearch_dashboards.json
  src/plugins/explore/public/application/legacy/data_explorer/types.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/index.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_search.ts
  src/plugins/explore/public/components/visualizations/line/__snapshots__/line_vis_options.test.tsx.snap
  src/plugins/explore/public/components/visualizations/line/line_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/line/line_chart_utils.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/line/to_expression.ts
  src/plugins/explore/public/components/visualizations/rule_repository.test.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/grid_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/index.ts
  src/plugins/explore/public/components/visualizations/style_panel/option.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/option.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_options.tsx
  src/plugins/explore/public/components/visualizations/types.test.ts
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/collections.test.ts
  src/plugins/explore/public/components/visualizations/utils/collections.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/utils/to_expression.ts
  src/plugins/explore/public/components/visualizations/utils/use_debounced_value.test.ts
  src/plugins/explore/public/components/visualizations/utils/use_debounced_value.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.test.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization.stories.tsx
  src/plugins/explore/public/components/visualizations/visualization.test.tsx
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.scss
  src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.test.ts
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/public/services/visualization_registry_service.test.ts
  src/plugins/explore/public/services/visualization_registry_service.ts
  src/plugins/explore/public/types.ts
Labels: distinguished-contributor, explore

#9867 feat: make default index pattern method more robust
  changelogs/fragments/9867.yml
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.test.ts
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
Labels: distinguished-contributor

#9870 [Explore] Banner in query explore
  src/plugins/explore/public/application/app.scss
  src/plugins/explore/public/application/app.tsx
  src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.test.tsx
  src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.tsx
Labels: Skip-Changelog, all-star-contributor

#9879 Skip failing selenium test "should show Percentiles"
  test/functional/apps/visualize/_metric_chart.js
Labels: Skip-Changelog, all-star-contributor, skips-test

#9846 [CVE-2024-4068] add package resolution for micromatch
  changelogs/fragments/9846.yml
  package.json
  packages/osd-storybook/package.json
  yarn.lock
Labels: cve, all-star-contributor

#9856 [Discover] Adding Back Unknown Fields
  changelogs/fragments/9856.yml
  src/plugins/data/common/index_patterns/index_patterns/flatten_hit.ts
  src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
  src/plugins/discover/public/application/components/sidebar/lib/get_index_pattern_field_list.ts
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/filter_columns.test.ts
  src/plugins/discover/public/application/view_components/utils/filter_columns.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: all-star-contributor, backport 3.1

#9892 making 3.1.0 release notes
  CHANGELOG.md
  changelogs/fragments/9409.yml
  changelogs/fragments/9602.yml
  changelogs/fragments/9605.yml
  changelogs/fragments/9611.yml
  changelogs/fragments/9625.yml
  changelogs/fragments/9651.yml
  changelogs/fragments/9662.yml
  changelogs/fragments/9694.yml
  changelogs/fragments/9696.yml
  changelogs/fragments/9697.yml
  changelogs/fragments/9700.yml
  changelogs/fragments/9701.yml
  changelogs/fragments/9703.yml
  changelogs/fragments/9707.yml
  changelogs/fragments/9724.yml
  changelogs/fragments/9726.yml
  changelogs/fragments/9730.yml
  changelogs/fragments/9734.yml
  changelogs/fragments/9735.yml
  changelogs/fragments/9738.yml
  changelogs/fragments/9770.yml
  changelogs/fragments/9773.yml
  changelogs/fragments/9776.yml
  changelogs/fragments/9777.yml
  changelogs/fragments/9784.yml
  changelogs/fragments/9789.yml
  changelogs/fragments/9795.yml
  changelogs/fragments/9798.yml
  changelogs/fragments/9809.yml
  changelogs/fragments/9813.yml
  changelogs/fragments/9815.yml
  changelogs/fragments/9816.yml
  changelogs/fragments/9818.yml
  changelogs/fragments/9820.yml
  changelogs/fragments/9824.yml
  changelogs/fragments/9831.yml
  changelogs/fragments/9834.yml
  changelogs/fragments/9838.yml
  changelogs/fragments/9842.yml
  changelogs/fragments/9846.yml
  changelogs/fragments/9848.yml
  changelogs/fragments/9849.yml
  changelogs/fragments/9856.yml
  changelogs/fragments/9857.yml
  changelogs/fragments/9863.yml
  changelogs/fragments/9867.yml
  changelogs/fragments/9875.yml
  docs/_sidebar.md
  release-notes/opensearch-dashboards.release-notes-3.1.0.md
Labels: Skip-Changelog, all-star-contributor, backport 3.1

#9896 [Backport 3.1] making 3.1.0 release notes
  CHANGELOG.md
  changelogs/fragments/9409.yml
  changelogs/fragments/9602.yml
  changelogs/fragments/9605.yml
  changelogs/fragments/9611.yml
  changelogs/fragments/9625.yml
  changelogs/fragments/9651.yml
  changelogs/fragments/9662.yml
  changelogs/fragments/9694.yml
  changelogs/fragments/9696.yml
  changelogs/fragments/9697.yml
  changelogs/fragments/9700.yml
  changelogs/fragments/9701.yml
  changelogs/fragments/9703.yml
  changelogs/fragments/9707.yml
  changelogs/fragments/9724.yml
  changelogs/fragments/9726.yml
  changelogs/fragments/9730.yml
  changelogs/fragments/9734.yml
  changelogs/fragments/9735.yml
  changelogs/fragments/9738.yml
  changelogs/fragments/9770.yml
  changelogs/fragments/9773.yml
  changelogs/fragments/9776.yml
  changelogs/fragments/9777.yml
  changelogs/fragments/9784.yml
  changelogs/fragments/9789.yml
  changelogs/fragments/9795.yml
  changelogs/fragments/9798.yml
  changelogs/fragments/9809.yml
  changelogs/fragments/9813.yml
  changelogs/fragments/9815.yml
  changelogs/fragments/9816.yml
  changelogs/fragments/9818.yml
  changelogs/fragments/9820.yml
  changelogs/fragments/9824.yml
  changelogs/fragments/9831.yml
  changelogs/fragments/9834.yml
  changelogs/fragments/9838.yml
  changelogs/fragments/9842.yml
  changelogs/fragments/9846.yml
  changelogs/fragments/9848.yml
  changelogs/fragments/9849.yml
  changelogs/fragments/9856.yml
  changelogs/fragments/9857.yml
  changelogs/fragments/9863.yml
  changelogs/fragments/9867.yml
  changelogs/fragments/9875.yml
  docs/_sidebar.md
  release-notes/opensearch-dashboards.release-notes-3.1.0.md
Labels: all-star-contributor, failed changeset

#9903 Fix CVE 2025-5889
  changelogs/fragments/9903.yml
  yarn.lock
Labels: all-star-contributor, backport 3.1

#9910 update 3.1 release-notes to include #9903
  CHANGELOG.md
  changelogs/fragments/9903.yml
  release-notes/opensearch-dashboards.release-notes-3.1.0.md
Labels: Skip-Changelog, backport 3.1

#9914 [Backport 3.1] update 3.1 release-notes to include #9903
  CHANGELOG.md
  changelogs/fragments/9903.yml
  release-notes/opensearch-dashboards.release-notes-3.1.0.md
Labels: distinguished-contributor, failed changeset

#9906 [Explore] Fix autocomplete service and update temp query_panel
  src/plugins/data/public/index.ts
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/query_editor/index.tsx
  src/plugins/explore/public/application/app.tsx
  src/plugins/explore/public/application/components/query_panel.tsx
  src/plugins/explore/public/build_services.ts
  src/plugins/explore/public/components/query_panel/components/footer/index.scss
  src/plugins/explore/public/types.ts
Labels: Skip-Changelog, distinguished-contributor, explore

#9901 Consume tab registry service and related state in explore tabs
  changelogs/fragments/9901.yml
  src/plugins/explore/public/application/app.tsx
  src/plugins/explore/public/application/register_tabs.ts
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/tabs/action_bar/action_bar.tsx
  src/plugins/explore/public/components/tabs/logs_tab.tsx
  src/plugins/explore/public/components/tabs/tabs.scss
  src/plugins/explore/public/components/tabs/tabs.tsx
  src/plugins/explore/public/components/tabs/vis_tab.tsx
  src/plugins/explore/public/components/visualizations/utils/to_expression.ts
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/services/tab_registry/tab_registry_service.ts
Labels: all-star-contributor

#9919 [Explore] Fix refresh by removing duplicate sync
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
Labels: Skip-Changelog, distinguished-contributor, explore

#9854 [UI setting] feat: keep backward compatibility for UI setting client.
  changelogs/fragments/9854.yml
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: backwards-compatibility, distinguished-contributor

#9912 [Explore] Fix explore vis types
  changelogs/fragments/9912.yml
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
  src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization.stories.tsx
  src/plugins/explore/public/components/visualizations/visualization.test.tsx
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: distinguished-contributor

#9908 [Explore] feat: add explore embeddable
  changelogs/fragments/9908.yml
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/index_pattern_helper.ts
  src/plugins/explore/public/application/legacy/discover/embeddable/constants.ts
  src/plugins/explore/public/application/legacy/discover/embeddable/index.ts
  src/plugins/explore/public/application/legacy/discover/embeddable/search_embeddable.scss
  src/plugins/explore/public/application/legacy/discover/embeddable/search_embeddable.tsx
  src/plugins/explore/public/application/legacy/discover/embeddable/search_embeddable_component.tsx
  src/plugins/explore/public/application/legacy/discover/embeddable/search_embeddable_factory.tsx
  src/plugins/explore/public/application/legacy/discover/embeddable/types.ts
  src/plugins/explore/public/application/legacy/discover/opensearch_dashboards_services.ts
  src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts
  src/plugins/explore/public/build_services.ts
  src/plugins/explore/public/embeddable/constants.ts
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_component.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_factory.tsx
  src/plugins/explore/public/embeddable/index.ts
  src/plugins/explore/public/embeddable/types.ts
  src/plugins/explore/public/plugin.ts
Labels: distinguished-contributor

#9932 [Explore] fix histogram UI
  changelogs/fragments/9932.yml
  src/plugins/explore/public/application/app.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
Labels: all-star-contributor

#9920 [Explore vis] Bar chart with vis controls
  changelogs/fragments/9920.yml
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
Labels: distinguished-contributor

#9940 [Explore] Fix: PPL queries requiring two clicks to work correctly
  src/plugins/explore/public/application/components/header_dataset_selector.tsx
  src/plugins/explore/public/application/components/query_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/utils/state_management/index.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_index_pattern.ts
  src/plugins/explore/public/application/utils/state_management/actions/export_actions.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts
  src/plugins/explore/public/application/utils/state_management/slices/query_slice.ts
  src/plugins/explore/public/application/utils/state_management/store.ts
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
  src/plugins/explore/public/components/data_table/explore_data_table.tsx
  src/plugins/explore/public/components/tabs/action_bar/action_bar.tsx
  src/plugins/explore/public/components/tabs/logs_tab.tsx
  src/plugins/explore/public/components/tabs/tabs.tsx
Labels: Skip-Changelog, distinguished-contributor, explore

#9941 [Explore] Fix: Align Explore Plugin Date Picker Behavior with Discover
  src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.ts
Labels: Skip-Changelog, distinguished-contributor, explore

#9943 update new experience banner to persist the dismissed banner via localStorage
  src/plugins/explore/public/components/experience_banners/constants.ts
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.test.tsx
  src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.tsx
Labels: distinguished-contributor, failed changeset, explore

#9942 Explore vis developer doc
  src/plugins/explore/public/components/visualizations/README.md
  src/plugins/explore/public/components/visualizations/RULES.md
Labels: distinguished-contributor

#9933 [Patterns] Basic table UI + tests
  changelogs/fragments/9933.yml
  src/plugins/explore/public/application/register_tabs.ts
  src/plugins/explore/public/components/patterns_table/patterns_container.test.tsx
  src/plugins/explore/public/components/patterns_table/patterns_container.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table.stories.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table.test.tsx
  src/plugins/explore/public/components/patterns_table/patterns_table.tsx
  src/plugins/explore/public/components/patterns_table/utils/constants.ts
  src/plugins/explore/public/components/patterns_table/utils/patterns_table.stubs.ts
  src/plugins/explore/public/components/patterns_table/utils/utils.test.tsx
  src/plugins/explore/public/components/patterns_table/utils/utils.tsx
  src/plugins/explore/public/components/tabs/patterns_tab.test.tsx
  src/plugins/explore/public/components/tabs/patterns_tab.tsx
Labels: seasoned-contributor

#9946 [Explore] Fix: Preserve selected tab when query run, correctly update cacheKeys when query run
  changelogs/fragments/9946.yml
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/components/tabs/tabs.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
Labels: all-star-contributor

#9947 Ruchi/query panel explore
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/application/utils/state_management/selectors/index.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui_slice.ts
  src/plugins/explore/public/components/query_panel/components/editor_stack/editor_stack.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/index.scss
  src/plugins/explore/public/components/query_panel/components/editor_stack/prompt_editor.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/query_editor.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/resuable_editor.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/shared.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/types.ts
  src/plugins/explore/public/components/query_panel/components/footer/actions/index.tsx
  src/plugins/explore/public/components/query_panel/components/footer/actions/registry.ts
  src/plugins/explore/public/components/query_panel/components/footer/date_time_selector.tsx
  src/plugins/explore/public/components/query_panel/components/footer/index.tsx
  src/plugins/explore/public/components/query_panel/hooks/useEditorMode.ts
  src/plugins/explore/public/components/query_panel/index.scss
  src/plugins/explore/public/components/query_panel/index.ts
  src/plugins/explore/public/components/query_panel/index.tsx
  src/plugins/explore/public/components/query_panel/query_panel.stories.tsx
  src/plugins/explore/public/components/query_panel/query_panel.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
  src/plugins/explore/public/components/query_panel/types.ts
  src/plugins/explore/public/components/query_panel/utils/type_detection/constants.ts
  src/plugins/explore/public/components/query_panel/utils/type_detection/index.ts
Labels: valued-contributor, failed changeset

#9971 Remove FieldName Suggestion directly after a FieldName in Field list
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/simplified_ppl_grammar/opensearch_ppl_autocomplete.ts
Labels: distinguished-contributor

#9972 [Explore] Fix: Adjust panels layout
  changelogs/fragments/9972.yml
  src/plugins/explore/public/application/components/query_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/panel/canvas_panel.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.scss
  src/plugins/explore/public/application/pages/logs/logs_page.test.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.scss
  src/plugins/explore/public/application/pages/metrics/metrics_page.test.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.scss
  src/plugins/explore/public/application/pages/traces/traces_page.test.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  yarn.lock
Labels: all-star-contributor

#9986 add margin between the banners
  src/plugins/data/public/ui/query_editor/_query_editor.scss
Labels: distinguished-contributor, failed changeset

#9987 update title of explore pages
  src/plugins/explore/public/application/index.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/helpers/use_flavor_id/index.ts
  src/plugins/explore/public/helpers/use_flavor_id/use_flavor_id.test.ts
  src/plugins/explore/public/helpers/use_flavor_id/use_flavor_id.ts
Labels: distinguished-contributor, failed changeset

#9978 [Explore] feat: support loading state from object
  changelogs/fragments/9978.yml
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/open_search_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts
  src/plugins/explore/public/application/utils/state_management/slices/ui_slice.ts
  src/plugins/explore/public/application/utils/state_management/utils/url.ts
  src/plugins/explore/public/types/saved_explore_types.ts
  src/plugins/explore/server/saved_objects/explore.ts
Labels: distinguished-contributor

#9995 minor type and prop changes
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/open_search_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/types.ts
Labels: distinguished-contributor, failed changeset

#9996 remove inspect from top nav
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
Labels: distinguished-contributor, failed changeset

#9998 remove all portal refs and consolidate style sheets on pages
  src/plugins/explore/public/application/components/header_dataset_selector.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/pages/explore_page.scss
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.scss
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.scss
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/components/query_panel/components/footer/date_time_selector.tsx
  src/plugins/explore/public/components/query_panel/components/footer/index.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
Labels: distinguished-contributor, failed changeset

#9999 more top nav refactor
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
Labels: distinguished-contributor, failed changeset

#10003 [Explore] Add AI summary component in explore plugin
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
  src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/assets/sparkle_mark.svg
  src/plugins/explore/public/build_services.ts
  src/plugins/explore/public/components/results_summary/results_summary.test.tsx
  src/plugins/explore/public/components/results_summary/results_summary.tsx
  src/plugins/explore/public/components/results_summary/results_summary_panel.scss
  src/plugins/explore/public/components/results_summary/results_summary_panel.tsx
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/public/types.ts
Labels: Skip-Changelog, seasoned-contributor

#9979 [Explore] Add fields selection when there is no rule matched
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/visualization.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
Labels: Skip-Changelog, seasoned-contributor

#10000 Fix Autocomplete Bugs
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/antlr/shared/utils.test.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/explore/public/components/query_panel/components/editor_stack/resuable_editor.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
Labels: distinguished-contributor, failed changeset

#10001 [Explore] feat: Add inspection button to action bar in tabs
  changelogs/fragments/10001.yml
  src/plugins/explore/public/application/utils/hooks/use_cache_keys.ts
  src/plugins/explore/public/application/utils/hooks/use_tab_results.test.tsx
  src/plugins/explore/public/application/utils/hooks/use_tab_results.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
  src/plugins/explore/public/application/utils/state_management/slices/query/query_slice.ts
  src/plugins/explore/public/components/patterns_table/patterns_container.tsx
  src/plugins/explore/public/components/tabs/action_bar/action_bar.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/constants.ts
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_callout.scss
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_callout.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_callout.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_popover_content.scss
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_popover_content.stories.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_popover_content.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv_popover_content.tsx
  src/plugins/explore/public/components/tabs/action_bar/download_csv/index.ts
  src/plugins/explore/public/components/tabs/action_bar/download_csv/use_download_csv.test.ts
  src/plugins/explore/public/components/tabs/action_bar/download_csv/use_download_csv.ts
  src/plugins/explore/public/components/tabs/action_bar/download_csv/use_download_csv_toasts.test.ts
  src/plugins/explore/public/components/tabs/action_bar/download_csv/use_download_csv_toasts.tsx
  src/plugins/explore/public/components/tabs/action_bar/hits_counter/hits_counter.scss
  src/plugins/explore/public/components/tabs/action_bar/hits_counter/hits_counter.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/hits_counter/hits_counter.tsx
  src/plugins/explore/public/components/tabs/action_bar/hits_counter/index.ts
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.scss
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.tsx
  src/plugins/explore/public/components/visualizations/visualization_container.tsx
  src/plugins/explore/public/types.ts
Labels: all-star-contributor

#9953 [Explore] Support filters for Explore PPL visualizations
  changelogs/fragments/9953.yml
  src/plugins/data/public/mocks.ts
  src/plugins/data/public/search/search_service.test.ts
  src/plugins/data/public/search/search_service.ts
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/search/filters/parser.test.ts
  src/plugins/query_enhancements/public/search/filters/parser.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.test.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Labels: all-star-contributor

#10004 [Explore] add new create panel dropdown to dashboard
  src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/show_add_panel_popover.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/dashboard/public/index.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/dashboard/public/types.ts
  src/plugins/dashboard/public/ui_triggers.ts
  src/plugins/explore/opensearch_dashboards.json
  src/plugins/explore/public/helpers/visualization_action_menu.tsx
  src/plugins/explore/public/plugin.ts
  src/plugins/visualizations/opensearch_dashboards.json
  src/plugins/visualizations/public/plugin.ts
  src/plugins/visualizations/public/vis_types/types_service.ts
  src/plugins/visualizations/public/wizard/new_vis_actions.tsx
Labels: distinguished-contributor, failed changeset

#10005 [Explore]feat: add table for explore embeddable
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
  src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
  src/plugins/explore/public/embeddable/explore_embeddable.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_component.tsx
  src/plugins/explore/public/embeddable/explore_embeddable_factory.tsx
  src/plugins/explore/public/saved_explore/transforms.ts
  src/plugins/explore/public/types/saved_explore_types.ts
Labels: distinguished-contributor

#9976 Add Shenoy Pratik (`@ps48`) as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/9976.yml
Labels: docs, distinguished-contributor

#10025 make old saved search findable in open top nav panel
  src/plugins/saved_objects/public/finder/saved_object_finder.tsx
Labels: distinguished-contributor, failed changeset

#10011 Ruchi/saved query
  src/plugins/data/public/index.ts
  src/plugins/data/public/query/saved_query/saved_query_service.ts
  src/plugins/data/public/ui/search_bar/index.tsx
  src/plugins/explore/public/components/query_panel/components/editor_stack/resuable_editor.tsx
  src/plugins/explore/public/components/query_panel/components/footer/date_time_selector.tsx
  src/plugins/explore/public/components/query_panel/components/footer/index.tsx
  src/plugins/explore/public/components/query_panel/components/footer/save_query.tsx
  src/plugins/explore/public/components/query_panel/query_panel.tsx
Labels: seasoned-contributor, failed changeset
