Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-04, with the labels that each got.

#9634 [CVE-2024-53382] Add prismjs 1.30.0 to resolutions
  changelogs/fragments/9634.yml
  package.json
  yarn.lock
Labels: all-star-contributor

#9618 Bump monaco-editor from 0.30.1 to 0.52.0
  changelogs/fragments/9618.yml
  cypress/utils/apps/query_enhancements/commands.js
  package.json
  packages/osd-monaco/package.json
  packages/osd-monaco/src/json/worker/json.worker.ts
  packages/osd-monaco/src/monaco.d.ts
  packages/osd-monaco/src/monaco.ts
  packages/osd-monaco/src/monaco_environment.ts
  packages/osd-monaco/src/xjson/worker/xjson.worker.ts
  packages/osd-ui-shared-deps/webpack.config.js
  src/dev/jest/config.js
  src/plugins/opensearch_dashboards_react/public/code_editor/__snapshots__/code_editor.test.tsx.snap
  yarn.lock
Labels: v3.0.0, breaking change, autocomplete improvement

#9628 [TEST] Reenable saved search test and convert it to use before and after
  changelogs/fragments/9628.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/saved_search.spec.js
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/commands.osd.js
  cypress/utils/index.d.ts
Labels: backport 2.x, all-star-contributor

#9641 Upgrade @aws-crypto/client-node to ^4.2.0 and aws-sdk from v2 to v3
  CHANGELOG.md
  package.json
  src/dev/jest/config.js
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
  yarn.lock
Labels: valued-contributor, failed changeset

#9649 [CVE-2025-27789][CVE-2024-12905] Bump @babel/runtime and tar-fs
  changelogs/fragments/9649.yml
  packages/osd-interpreter/package.json
  packages/osd-opensearch/package.json
  packages/osd-test/package.json
  yarn.lock
Labels: all-star-contributor

#9637 fix: trim the url for creating data source
  changelogs/fragments/9637.yml
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
Labels: first-time-contributor

#9647 feat: support streaming when content type is event stream
  changelogs/fragments/9647.yml
  src/core/public/http/fetch.test.ts
  src/core/public/http/fetch.ts
Labels: enhancement, distinguished-contributor

#9659 Discover Grid filter fix
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/9659.yml
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
Labels: repeat-contributor

#9663 Fix issue connecting to data source with SigV4 auth after upgrading aws sdk from v2 to v3
  package.json
  src/plugins/data_source/server/legacy/configure_legacy_client.ts
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
  yarn.lock
Labels: valued-contributor, failed changeset

#9655 Extend the query editor extension to include action bar button area
  changelogs/fragments/9655.yml
  docs/_sidebar.md
  docs/plugins/data/query-editor-enhancements.md
  docs/plugins/data/resources/query_editor_enhancements.png
  src/plugins/data/public/index.ts
  src/plugins/data/public/public.api.md
  src/plugins/data/public/types.ts
  src/plugins/data/public/ui/index.ts
  src/plugins/data/public/ui/query_editor/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/index.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.test.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
  src/plugins/data/public/ui/query_editor/query_editor_extensions/utils.test.ts
  src/plugins/data/public/ui/query_editor/query_editor_extensions/utils.ts
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.scss
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.scss
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.tsx
Labels: v3.0.0, all-star-contributor

#9669 Add Release Notes for 3.0.0-beta1
  CHANGELOG.md
  changelogs/fragments/9304.yml
  changelogs/fragments/9420.yml
  changelogs/fragments/9465.yml
  changelogs/fragments/9467.yml
  changelogs/fragments/9497.yml
  changelogs/fragments/9525.yml
  changelogs/fragments/9531.yml
  changelogs/fragments/9575.yml
  changelogs/fragments/9581.yml
  changelogs/fragments/9601.yml
  changelogs/fragments/9618.yml
  changelogs/fragments/9623.yml
  changelogs/fragments/9628.yml
  changelogs/fragments/9634.yml
  changelogs/fragments/9637.yml
  changelogs/fragments/9647.yml
  changelogs/fragments/9649.yml
  changelogs/fragments/9655.yml
  docs/_sidebar.md
  release-notes/opensearch-dashboards.release-notes-3.0.0-beta1.md
Labels: Skip-Changelog, all-star-contributor

#9478 [Workspace] Display error handling page when the enter the workspace in stale state
  changelogs/fragments/9478.yml
  src/core/public/index.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/workspace_validation.service.test.ts
  src/plugins/workspace/public/services/workspace_validation_service.ts
  src/plugins/workspace/public/workspace_client.ts
Labels: repeat-contributor

#9656 [TEST] Add saved search related test cases
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/saved_search.spec.js
  cypress/utils/apps/query_enhancements/saved.js
Labels: Skip-Changelog, seasoned-contributor

#9603 Fix: Skip appending time range to ppl when not querying with source
  changelogs/fragments/9603.yml
  src/plugins/query_enhancements/common/utils.test.ts
  src/plugins/query_enhancements/common/utils.ts
  src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Labels: seasoned-contributor

#9674 Fix: copy essential property to generated request
  changelogs/fragments/9674.yml
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
Labels: distinguished-contributor

#9676 Fix issue with adding sample data to data source
  changelogs/fragments/9676.yml
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
Labels: v3.0.0, distinguished-contributor

#9668 [Discover]Fix dataset selector flashing
  changelogs/fragments/9668.yml
  src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss
Labels: distinguished-contributor

#9586 Fix: Correctly show error message in DQL and PPL query editor
  changelogs/fragments/9586.yml
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.test.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/common/utils.ts
Labels: seasoned-contributor

#9681 [CVE-2025-27789] Bump @babel/runtime,@babel/helpers and @babel/runtime-corejs3
  changelogs/fragments/9681.yml
  package.json
  yarn.lock
Labels: all-star-contributor

#9666 fix: close suggestions after query submission
  changelogs/fragments/9666.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_input.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_input.tsx
Labels: v3.0.0, repeat-contributor

#9665 [Workspace] Fix issue when workspace is disabled
  changelogs/fragments/9665.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/core/public/chrome/utils.ts
  src/plugins/home/public/plugin.ts
Labels: v3.0.0, distinguished-contributor

#9509 Minor UX fixes for discover summary
  changelogs/fragments/9509.yml
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/query_enhancements/public/query_assist/_index.scss
  src/plugins/query_enhancements/public/query_assist/components/__snapshots__/call_outs.test.tsx.snap
  src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_input.tsx
Labels: repeat-contributor

#9678 Fix connect queryparams resulting in signer error
  changelogs/fragments/9678.yml
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
Labels: repeat-contributor

#9685 Update yarn lock
  yarn.lock
Labels: all-star-contributor

#9686 Fix + re-enable determineMapping tests
  src/plugins/data_importer/server/utils/determine_mapping.test.ts
Labels: all-star-contributor

#9346 [Workspace] Filter out recent items with errors
  changelogs/fragments/9346.yml
  src/core/public/chrome/ui/header/recent_items.test.tsx
  src/core/public/chrome/ui/header/recent_items.tsx
Labels: distinguished-contributor, workspace

#9566 [Cross-Cluster-Search] Show cross cluster connections in Data Sources and Workspaces page
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.scss
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.scss
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: v3.0.0, all-star-contributor

#9660 [Cross-Cluster-Search] Show cross cluster connections in Index Pattern and Discover Page
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/opensearch_dashboards.json
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.test.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
  src/plugins/data/public/query/query_string/dataset_service/lib/utils.ts
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/constants/index.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.test.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_remote_connections.test.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_remote_connections.tsx
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/index.ts
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/remote_connections.scss
  src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
  src/plugins/index_pattern_management/public/components/utils.ts
  src/plugins/index_pattern_management/public/types.ts
Labels: all-star-contributor

#9694 Fix Ci failures
  changelogs/fragments/9694.yml
  src/core/server/rendering/rendering_service.test.ts
  test/common/config.js
  test/functional/apps/visualize/_custom_branding.ts
Labels: all-star-contributor

#9589 Fix: Correctly show error message in DQL and PPL query editor
  src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
  src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx
  src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
  src/plugins/query_enhancements/common/utils.test.ts
  src/plugins/query_enhancements/common/utils.ts
Labels: repeat-contributor

#9605 [Discover]fix: should clear previous query if input invalid questions
  changelogs/fragments/9605.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
Labels: all-star-contributor

#9409 [workspace]remove * when calling find in data source association modal and in workspace list page
  changelogs/fragments/9409.yml
  src/core/public/saved_objects/saved_objects_client.ts
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Labels: all-star-contributor, workspace

#9662 [Navigation] Support left navigation search for OSD without workspace
  changelogs/fragments/9662.yml
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/global_search/global_search_service.test.ts
  src/core/public/chrome/global_search/global_search_service.ts
  src/core/public/chrome/index.ts
  src/core/public/chrome/ui/global_search/page_item.test.tsx
  src/core/public/chrome/ui/global_search/page_item.tsx
  src/core/public/chrome/ui/global_search/search_pages_command.test.tsx
  src/core/public/chrome/ui/global_search/search_pages_command.tsx
  src/core/public/chrome/ui/index.ts
  src/core/public/chrome/ui/nav_group_element.tsx
  src/core/public/chrome/utils.test.ts
  src/core/public/chrome/utils.ts
  src/core/public/index.ts
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/components/global_search/page_item.tsx
  src/plugins/workspace/public/components/global_search/search_pages_command.test.tsx
  src/plugins/workspace/public/components/global_search/search_pages_command.tsx
  src/plugins/workspace/public/components/global_search/workspace_global_search_item.test.tsx
  src/plugins/workspace/public/components/global_search/workspace_global_search_item.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: repeat-contributor

#9701 Cancel existing query when new natural language prompt is being generated-new
  changelogs/fragments/9701.yml
  src/plugins/discover/public/actions/abort_data_query_action.test.ts
  src/plugins/discover/public/actions/abort_data_query_action.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/discover/public/build_services.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/hooks/use_generate.test.ts
  src/plugins/query_enhancements/public/query_assist/hooks/use_generate.ts
  src/plugins/query_enhancements/public/services/index.ts
  src/plugins/query_enhancements/public/types.ts
  src/plugins/ui_actions/public/index.ts
  src/plugins/ui_actions/public/plugin.ts
  src/plugins/ui_actions/public/triggers/abort_data_query_trigger.ts
  src/plugins/ui_actions/public/triggers/index.ts
Labels: all-star-contributor

#9625 Fix a issue that can cause incorrect query to fire when switch plugin
  changelogs/fragments/9625.yml
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/data/public/query/state_sync/connect_to_query_state.ts
  src/plugins/data/public/ui/dataset_selector/index.test.tsx
  src/plugins/data/public/ui/dataset_selector/index.tsx
  src/plugins/data/public/ui/query_string_input/query_string_input.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: seasoned-contributor

#9651 Data source opensearch client honors the timeout settings in yaml file
  changelogs/fragments/9651.yml
  src/plugins/data_source/config.ts
  src/plugins/data_source/server/client/client_config.test.ts
  src/plugins/data_source/server/client/client_config.ts
  src/plugins/data_source/server/data_source_service.test.ts
  src/plugins/data_source/server/legacy/client_config.test.ts
  src/plugins/data_source/server/legacy/client_config.ts
  src/plugins/data_source/server/plugin.ts
Labels: repeat-contributor

#9697 Bringing back storybook for isolated component testing
  .eslintrc.js
  changelogs/fragments/9697.yml
  docs/_sidebar.md
  package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  packages/osd-storybook/README.md
  packages/osd-storybook/index.ts
  packages/osd-storybook/lib/constants.ts
  packages/osd-storybook/lib/default_config.ts
  packages/osd-storybook/lib/register.ts
  packages/osd-storybook/lib/run_storybook_cli.ts
  packages/osd-storybook/package.json
  packages/osd-storybook/preset.js
  packages/osd-storybook/tsconfig.json
  packages/osd-storybook/typings.d.ts
  packages/osd-storybook/webpack.config.ts
  packages/osd-storybook/yarn.lock
  scripts/storybook.js
  src/dev/precommit_hook/casing_check_config.js
  src/dev/storybook/aliases.ts
  src/dev/storybook/commands/clean.ts
  src/dev/storybook/run_storybook_cli.ts
  src/plugins/discover/.storybook/main.js
  src/plugins/discover/.storybook/preview.ts
  src/plugins/discover/public/application/components/download_csv/download_csv_popover_content.stories.tsx
  yarn.lock
Labels: v3.0.0, all-star-contributor

#9729 Add release notes for 2.19.2
  CHANGELOG.md
  changelogs/fragments/9659.yml
  changelogs/fragments/9694.yml
  changelogs/fragments/9699.yml
  release-notes/opensearch-dashboards.release-notes-2.19.2.md
Labels: Skip-Changelog

#9730 Fix SigV4 signing mismatch issue with `?v` query parameter
  changelogs/fragments/9730.yml
  src/plugins/data_source/server/legacy/http_aws_es/connector.js
  src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
Labels: v3.0.0, multiple datasource, distinguished-contributor

#9728 Fix Ci failure due to Java version
  .github/workflows/build_and_test_workflow.yml
Labels: distinguished-contributor

#9700 fix user appearance not working
  changelogs/fragments/9700.yml
  src/core/public/ui_settings/ui_settings_client.test.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/plugins/advanced_settings/public/header_user_theme_menu.tsx
Labels: distinguished-contributor

#9696 Add tooltip and disabled to panel item
  CHANGELOG.md
  changelogs/fragments/9696.yml
  src/plugins/ui_actions/public/actions/action.ts
  src/plugins/ui_actions/public/actions/action_internal.ts
  src/plugins/ui_actions/public/context_menu/build_eui_context_menu_panels.tsx
Labels: repeat-contributor
