Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-03, with the labels that each got.

#9468 Prevent `_cat/indices` when there is no datasource available
  src/plugins/data_importer/public/application.tsx
  src/plugins/data_importer/public/components/data_importer_app.tsx
Labels: seasoned-contributor, failed changeset

#9464 [Workspace] organizing generated summary by using markdown format
  changelogs/fragments/9464.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: all-star-contributor

#9139 Upgrading `opensearch` client to 3.x
  package.json
  packages/osd-opensearch-archiver/package.json
  packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.ts
  packages/osd-opensearch-archiver/src/lib/indices/opensearch_dashboards_index.ts
  packages/osd-opensearch/package.json
  yarn.lock
Labels: first-time-contributor, failed changeset

#9463 [doc] Initial version of Understanding Discover 2.0
  changelogs/fragments/9463.yml
  docs/_sidebar.md
  docs/plugins/discover/resources/components.svg
  docs/plugins/discover/resources/data_structure_example.svg
  docs/plugins/discover/resources/search_context.svg
  docs/plugins/discover/understand_and_extend_discover.md
Labels: docs, discover, discover-next

#9439 [TEST] use before/after and consolidate
  changelogs/fragments/9439.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/a_check.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/saved_search.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/simple_dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/dataset_selector.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/language_specific_display.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/saved_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/saved_search_in_dashboards.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/time_range_selection.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/caching.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/field_display_filtering.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/shared_links.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/table.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/advanced_settings.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/histogram_interaction.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_more.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_query.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_switch.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/recent_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/sidebar.spec.js
  cypress/utils/apps/commands.js
  cypress/utils/apps/index.d.ts
  cypress/utils/apps/query_enhancements/commands.js
  cypress/utils/apps/query_enhancements/index.d.ts
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/commands.osd.js
  cypress/utils/helpers.js
  cypress/utils/index.d.ts
Labels: backport 2.x, seasoned-contributor, discover_2.0-test

#9481 feat: allow to customize discover summary panel title
  changelogs/fragments/9481.yml
  src/plugins/query_enhancements/common/config.ts
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: backport 2.x, all-star-contributor

#9492 [Workspace] fix: text size in generated summary should be s
  changelogs/fragments/9492.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: all-star-contributor

#9361 Add MDS to msearch
  changelogs/fragments/9361.yml
  src/plugins/data/common/search/search_source/legacy/call_client.ts
  src/plugins/data/common/search/search_source/legacy/default_search_strategy.test.ts
  src/plugins/data/common/search/search_source/legacy/default_search_strategy.ts
  src/plugins/data/common/search/search_source/legacy/fetch_soon.test.ts
  src/plugins/data/common/search/search_source/legacy/fetch_soon.ts
  src/plugins/data/common/search/search_source/legacy/types.ts
  src/plugins/data/common/search/search_source/search_source.ts
  src/plugins/data/public/search/legacy/call_msearch.test.ts
  src/plugins/data/public/search/legacy/call_msearch.ts
  src/plugins/data/server/search/routes/call_msearch.ts
  src/plugins/data/server/search/routes/msearch.ts
Labels: multiple datasource, distinguished-contributor

#9493 Fix failed build integration test by update caniuse-lite version in yarn.lock
  yarn.lock
Labels: Skip-Changelog, repeat-contributor

#9484 Remove @elastic/filesaver in favor of file-saver
  changelogs/fragments/9484.yml
  package.json
  src/plugins/console/public/application/containers/main/main.tsx
  src/plugins/inspector/public/views/data/lib/export_csv.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.mocks.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts
  yarn.lock
Labels: v3.0.0, seasoned-contributor, do not backport

#9488 chore: remove formatNumWithCommas
  changelogs/fragments/9488.yml
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.tsx
  src/plugins/discover/public/application/helpers/format_number_with_commas.ts
  src/plugins/discover/public/application/helpers/index.ts
Labels: v3.0.0, seasoned-contributor, do not backport

#9490 [CI] Update Discover Integration Tests S3 Workflow
  .github/workflows/cypress_workflow_with_s3.yml
  changelogs/fragments/9490.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_tests/s3_dataset.spec.js
  package.json
Labels: all-star-contributor

#9487 Add more tests + general refactoring
  src/plugins/data_importer/README.md
  src/plugins/data_importer/public/components/data_importer_app.tsx
  src/plugins/data_importer/public/lib/cat_indices.test.ts
  src/plugins/data_importer/public/lib/import_file.test.ts
  src/plugins/data_importer/public/lib/preview_file.test.ts
  src/plugins/data_importer/public/lib/preview_file.ts
  src/plugins/data_importer/server/plugin.ts
  src/plugins/data_importer/server/routes/cat_indices.ts
Labels: seasoned-contributor, failed changeset

#9494 [workspace] feat: changes the position of the query summary and query editor
  changelogs/fragments/9494.yml
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: all-star-contributor

#9503 [CVE-2023-28155][CVE-2023-44270][CVE-2024-55565] Resolve the CVE by bumping nanoid, cypress/request and postcss
  changelogs/fragments/9503.yml
  package.json
  packages/osd-optimizer/package.json
  packages/osd-ui-framework/package.json
  yarn.lock
Labels: v3.0.0, all-star-contributor

#9485 Skeleton of prometheus data selection
  package.json
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/data_source/common/data_connections/data_connection_saved_object_attributes.ts
  src/plugins/data_source/common/data_sources/types.ts
  src/plugins/discover/public/application/components/sidebar/metrics_sidebar.tsx
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_prometheus.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/assets/prometheus_mark.svg
  src/plugins/query_enhancements/public/datasets/prometheus_type.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/routes/metrics/routes.ts
  src/plugins/query_enhancements/server/search/index.ts
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
  src/plugins/query_enhancements/server/utils/plugins.ts
Labels: Skip-Changelog, valued-contributor

#9511 deprecate the discover:newExpereince
  changelogs/fragments/9511.yml
  src/plugins/discover/public/application/components/data_grid/data_grid.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_actions.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_context.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_inspect_button.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_toolbar.tsx
  src/plugins/discover/public/application/components/utils/local_storage.ts
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
Labels: backport 2.x, all-star-contributor

#9507 Fix CVE-2025-27152 by bumping axios
  changelogs/fragments/9507.yml
  package.json
  packages/osd-dev-utils/package.json
  packages/osd-ui-shared-deps/package.json
  yarn.lock
Labels: v3.0.0, all-star-contributor

#9512 Use `depth.limit` instead of `nested_objects.limit` as the validation for deeply nested objects
  src/plugins/data_importer/server/routes/preview.ts
  src/plugins/data_importer/server/utils/util.test.ts
  src/plugins/data_importer/server/utils/util.ts
Labels: seasoned-contributor, failed changeset

#9504 Discover summary trigger updates
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/data/public/search/mocks.ts
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
  src/plugins/query_enhancements/public/query_assist/hooks/use_query_assist.ts
  src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Labels: all-star-contributor, failed changeset

#9516 Fix data frame null or undefined object conversion error
  changelogs/fragments/9516.yml
  src/plugins/data/common/data_frames/utils.test.ts
  src/plugins/data/common/data_frames/utils.ts
Labels: distinguished-contributor

#9498 move hits location and show number of rows alongside it
  changelogs/fragments/9498.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/queries.spec.js
  cypress/utils/commands.osd.js
  cypress/utils/index.d.ts
  src/plugins/discover/public/application/components/chart/_histogram.scss
  src/plugins/discover/public/application/components/chart/chart.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.scss
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.test.tsx
  src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.tsx
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.scss
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.test.tsx
  src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.tsx
  src/plugins/discover/public/application/components/discover_options/discover_options.tsx
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.scss
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.test.tsx
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.scss
  src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: all-star-contributor

#9519 fixed an regression and failed test
  changelogs/fragments/9519.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: all-star-contributor

#9514 [Navigation] fix: make nav icon style compatible with sidecar
  changelogs/fragments/9514.yml
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/overlays/index.ts
  src/core/public/overlays/sidecar/helper.test.ts
  src/core/public/overlays/sidecar/helper.ts
  src/core/public/overlays/sidecar/index.ts
Labels: distinguished-contributor

#9532 [Query enhancement]feat: Append prompt for query assistant in request payload
  changelogs/fragments/9532.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/constant.ts
  src/plugins/query_enhancements/public/query_assist/utils/index.ts
  src/plugins/query_enhancements/public/query_assist/utils/prompt.test.ts
  src/plugins/query_enhancements/public/query_assist/utils/prompt.ts
Labels: distinguished-contributor

#9533 Add better error handling and messages
  src/plugins/data_importer/public/components/data_importer_app.tsx
  src/plugins/data_importer/public/types.ts
  src/plugins/data_importer/server/parsers/csv_parser.test.ts
  src/plugins/data_importer/server/parsers/csv_parser.ts
  src/plugins/data_importer/server/parsers/json_parser.test.ts
  src/plugins/data_importer/server/parsers/json_parser.ts
  src/plugins/data_importer/server/parsers/ndjson_parser.test.ts
  src/plugins/data_importer/server/parsers/ndjson_parser.ts
  src/plugins/data_importer/server/parsers/test_utils/invalid_json.json
  src/plugins/data_importer/server/parsers/test_utils/ndjson_test_cases.ts
  src/plugins/data_importer/server/routes/import_file.ts
  src/plugins/data_importer/server/routes/import_text.ts
  src/plugins/data_importer/server/routes/preview.ts
  src/plugins/data_importer/server/types.ts
  src/plugins/data_importer/server/utils/determine_mapping.test.ts
  src/plugins/data_importer/server/utils/determine_mapping.ts
  src/plugins/data_importer/server/utils/util.test.ts
  src/plugins/data_importer/server/utils/util.ts
Labels: all-star-contributor

#9522 Prometheus manager and search strategy
  src/plugins/data/public/query/query_string/dataset_service/types.ts
  src/plugins/query_enhancements/common/constants.ts
  src/plugins/query_enhancements/public/plugin.tsx
  src/plugins/query_enhancements/public/search/promql_search_interceptor.ts
  src/plugins/query_enhancements/server/connections/clients/base_connection_client.ts
  src/plugins/query_enhancements/server/connections/clients/sql_connection_client.ts
  src/plugins/query_enhancements/server/connections/managers/base_connection_manager.ts
  src/plugins/query_enhancements/server/connections/managers/prometheus_manager.ts
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
  src/plugins/query_enhancements/server/utils/plugins.ts
Labels: Skip-Changelog, valued-contributor

#9529 [Discover] fix: Correctly load saved search from snapshot URL
  changelogs/fragments/9529.yml
  src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.test.tsx
  src/plugins/discover/public/application/view_components/utils/use_search.ts
Labels: backport 2.x, valued-contributor

#9523 [Discover] fix: Correctly show selected cols from saved search
  changelogs/fragments/9523.yml
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: valued-contributor

#9541 [Discover] fix: correctly load saved search query in query editor
  changelogs/fragments/9541.yml
  src/plugins/data/public/ui/search_bar/search_bar.tsx
Labels: valued-contributor

#9545 Fix table not rendering data
  src/plugins/data_importer/public/components/preview_table.tsx
  src/plugins/data_importer/server/routes/preview.ts
Labels: all-star-contributor, failed changeset

#9534 Add pull request write permission for github token
  .github/workflows/performance_testing.yml
  changelogs/fragments/9534.yml
Labels: repeat-contributor

#9553 [workspace] discover summary should use markdown
  changelogs/fragments/9553.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: all-star-contributor

#9552 fix: clear discover summary if t2ppl failed
  changelogs/fragments/9552.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_input.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: all-star-contributor

#9554 rename discover summary metric name
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: Skip-Changelog, all-star-contributor, failed changeset

#9557 Consume deserialized prometheus results
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
Labels: Skip-Changelog, seasoned-contributor

#9555 [TEST] fix delete all old workspaces
  cypress/utils/commands.osd.js
Labels: backport 2.x, Skip-Changelog, discover_2.0-test

#9465 [workspace] Prevent user from visiting discover when out of a workspace
  changelogs/fragments/9465.yml
  src/plugins/data_explorer/public/plugin.ts
  src/plugins/discover/public/plugin.ts
Labels: all-star-contributor

#9560 [TESTS] make download_csv tests smaller to reduce the num of crashes
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/download_csv.spec.js
  cypress/utils/apps/query_enhancements/download_csv.js
  cypress/utils/apps/query_enhancements/shared.js
  cypress/utils/index.d.ts
Labels: v3.0.0, Skip-Changelog, do not backport

#9467 Add Joey Liu (`@Maosaic`) as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  changelogs/fragments/9467.yml
Labels: docs, backport 2.x, distinguished-contributor

#9404 Remove obsolete compose version specifier
  docs/docker-dev/docker-compose.selenium.yml
  docs/docker-dev/docker-compose.yml
  tasks/docker_docs/docker-compose.yml
Labels: Skip-Changelog, first-time-contributor

#9567 improve prometheus auto-step calculation and result handling
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
Labels: Skip-Changelog, seasoned-contributor

#9501 Initial logic flow for building visualization expressions in discover
  .github/workflows/build_plugin.yml
  src/plugins/discover/opensearch_dashboards.json
  src/plugins/discover/public/application/components/chart/utils/create_visualization_configs.ts
  src/plugins/discover/public/application/components/visualizations/vislib/line/line_vis_type.ts
  src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
  src/plugins/discover/public/application/view_components/canvas/discover_visualization.scss
  src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_visualization_types.ts
  src/plugins/discover/public/plugin.ts
Labels: distinguished-contributor, failed changeset

#9569 Update visualization when there is change
  src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
  src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx
Labels: distinguished-contributor, failed changeset

#9571 Add showVisualization setting in language config
  src/plugins/data/public/query/query_string/language_service/types.ts
  src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx
  src/plugins/query_enhancements/public/plugin.tsx
Labels: distinguished-contributor, failed changeset

#9570 update prometheus response interface, plot series on same y scale
  src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
Labels: Skip-Changelog, seasoned-contributor

#9575 Fix: fix potential memory leak in getDirectQueryConnections with node 20
  changelogs/fragments/9575.yml
  src/plugins/data_source/config.ts
  src/plugins/data_source_management/server/routes/data_connections_router.ts
Labels: nodejs :lollipop:, v3.0.0, distinguished-contributor

#9525 [doc] getting started with Discover 2.0
  changelogs/fragments/9525.yml
  docs/_sidebar.md
  docs/plugins/discover/getting_started_with_discover.md
Labels: docs, discover, distinguished-contributor, discover-next

#9574 create and integrate the clientside resource client factory
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/resources/base_resource_client.ts
  src/plugins/data/public/resources/prometheus_resource_client.ts
  src/plugins/data/public/resources/resource_client_factory.ts
  src/plugins/data/public/types.ts
  src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
  src/plugins/discover/public/application/view_components/utils/use_prometheus.ts
  src/plugins/query_enhancements/server/connections/clients/base_connection_client.ts
  src/plugins/query_enhancements/server/connections/managers/prometheus_manager.ts
  src/plugins/query_enhancements/server/routes/resources/routes.ts
Labels: Skip-Changelog, seasoned-contributor

#9596 Prometheus demo papercut fixes
  src/plugins/query_enhancements/public/datasets/prometheus_type.ts
  src/plugins/visualizations/public/components/_visualization.scss
Labels: seasoned-contributor, failed changeset

#9371 feat: Add MDS support for index pattern validate script
  src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/test_script.tsx
  src/plugins/index_pattern_management/public/components/field_editor/field_editor.tsx
  src/plugins/index_pattern_management/public/components/field_editor/lib/validate_script.ts
  src/plugins/index_pattern_management/public/components/field_editor/types.ts
  src/plugins/index_pattern_management/server/routes/preview_scripted_field.ts
Labels: enhancement, multiple datasource, distinguished-contributor

#9581 fix permission issue for performance tsting
  .github/workflows/performance_testing.yml
  changelogs/fragments/9581.yml
Labels: repeat-contributor, failed changeset

#9599 Fix legend name and layout
  src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
Labels: distinguished-contributor, failed changeset

#9524 [Auto Suggest] PromQL Autocomplete
  packages/osd-monaco/src/xjson/lexer_rules/index.ts
  packages/osd-monaco/src/xjson/lexer_rules/promql.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/promql/.generated/PromQLLexer.interp
  src/plugins/data/public/antlr/promql/.generated/PromQLLexer.tokens
  src/plugins/data/public/antlr/promql/.generated/PromQLLexer.ts
  src/plugins/data/public/antlr/promql/.generated/PromQLParser.interp
  src/plugins/data/public/antlr/promql/.generated/PromQLParser.tokens
  src/plugins/data/public/antlr/promql/.generated/PromQLParser.ts
  src/plugins/data/public/antlr/promql/.generated/PromQLParserVisitor.ts
  src/plugins/data/public/antlr/promql/aggregation_visitor.ts
  src/plugins/data/public/antlr/promql/code_completion.test.ts
  src/plugins/data/public/antlr/promql/code_completion.ts
  src/plugins/data/public/antlr/promql/constants.ts
  src/plugins/data/public/antlr/promql/grammar/PromQLLexer.g4
  src/plugins/data/public/antlr/promql/grammar/PromQLParser.g4
  src/plugins/data/public/antlr/promql/instant_selector_visitor.test.ts
  src/plugins/data/public/antlr/promql/instant_selector_visitor.ts
  src/plugins/data/public/antlr/promql/promql_autocomplete.test.ts
  src/plugins/data/public/antlr/promql/promql_autocomplete.ts
  src/plugins/data/public/antlr/shared/constants.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
Labels: Skip-Changelog, seasoned-contributor

#9420 [Workspace] Fix find saved object within a workspace without queryparams return all the saved objects
  changelogs/fragments/9420.yml
  src/plugins/saved_objects_management/server/routes/find.test.ts
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
Labels: repeat-contributor, workspace

#9601 fix: Query assistant doesn't refresh generated ppl
  changelogs/fragments/9601.yml
  src/plugins/data/public/query/query_string/query_string_manager.test.ts
  src/plugins/data/public/query/query_string/query_string_manager.ts
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
Labels: all-star-contributor

#9587 [Prometheus] Add alertmanager and alert group resources
  src/plugins/query_enhancements/server/connections/clients/base_connection_client.ts
  src/plugins/query_enhancements/server/connections/clients/promql_connection_client.ts
  src/plugins/query_enhancements/server/connections/managers/prometheus_manager.ts
  src/plugins/query_enhancements/server/routes/resources/routes.ts
Labels: seasoned-contributor, failed changeset

#9615 Define upper bound for prometheus datapoints sent to the frontend
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
Labels: Skip-Changelog, seasoned-contributor

#9616 Prometheus demo polish and query fix
  changelogs/fragments/9516.yml
  src/plugins/data/common/data_frames/utils.test.ts
  src/plugins/data/common/data_frames/utils.ts
  src/plugins/discover/public/application/components/sidebar/metrics_sidebar.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_visualization_save_modal.tsx
Labels: Skip-Changelog, seasoned-contributor

#9497 Bump `monaco-editor` from 0.17.0 to 0.30.1
  changelogs/fragments/9497.yml
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_switch.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js
  cypress/utils/apps/query_enhancements/autocomplete.js
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  package.json
  packages/osd-monaco/package.json
  packages/osd-monaco/src/json/worker/json.worker.ts
  packages/osd-monaco/src/monaco.ts
  packages/osd-monaco/src/test_setup.js
  packages/osd-monaco/src/xjson/language.ts
  packages/osd-monaco/webpack.config.js
  packages/osd-ui-shared-deps/webpack.config.js
  src/dev/jest/config.integration.js
  src/dev/jest/config.js
  src/dev/jest/setup/mocks.js
  src/dev/jest/setup/monaco_mock.js
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.test.tsx
  src/plugins/vis_type_timeline/public/components/timeline_expression_input.tsx
  yarn.lock
Labels: v3.0.0, distinguished-contributor, breaking change, autocomplete improvement

#9607 Revert "[Query enhancement]feat: Append prompt for query assistant in…
  CHANGELOG.md
  src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
  src/plugins/query_enhancements/public/query_assist/utils/constant.ts
  src/plugins/query_enhancements/public/query_assist/utils/index.ts
  src/plugins/query_enhancements/public/query_assist/utils/prompt.test.ts
  src/plugins/query_enhancements/public/query_assist/utils/prompt.ts
Labels: first-time-contributor, failed changeset

#9617 [Manual backport 2.x] Correctly show selected cols from saved search (#9523)
  changelogs/fragments/9523.yml
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
Labels: autocut, failed changeset

#9624 QoL improvements for kubecon discover demo
  src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
  src/plugins/data/public/resources/prometheus_resource_client.ts
  src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
  src/plugins/discover/public/application/view_components/panel/index.tsx
  src/plugins/discover/public/application/view_components/utils/use_prometheus.ts
  src/plugins/discover/public/application/view_components/utils/use_search.ts
  src/plugins/query_enhancements/public/datasets/prometheus_type.ts
  src/plugins/query_enhancements/server/connections/managers/prometheus_manager.ts
  src/plugins/query_enhancements/server/routes/resources/routes.ts
  src/plugins/query_enhancements/server/search/promql_search_strategy.ts
Labels: Skip-Changelog, seasoned-contributor

#9626 monaco bump cherry pick
  changelogs/fragments/9497.yml
  cypress.config.ts
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_switch.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js
  cypress/utils/apps/query_enhancements/autocomplete.js
  cypress/utils/apps/query_enhancements/saved.js
  cypress/utils/apps/query_enhancements/saved_queries.js
  package.json
  packages/osd-monaco/package.json
  packages/osd-monaco/src/json/worker/json.worker.ts
  packages/osd-monaco/src/monaco.d.ts
  packages/osd-monaco/src/monaco.ts
  packages/osd-monaco/src/monaco_environment.ts
  packages/osd-monaco/src/test_setup.js
  packages/osd-monaco/src/xjson/language.ts
  packages/osd-monaco/src/xjson/worker/xjson.worker.ts
  packages/osd-monaco/webpack.config.js
  packages/osd-ui-shared-deps/webpack.config.js
  src/dev/jest/config.integration.js
  src/dev/jest/config.js
  src/dev/jest/setup/mocks.js
  src/dev/jest/setup/monaco_mock.js
  src/plugins/data/public/antlr/dql/code_completion.test.ts
  src/plugins/data/public/ui/query_editor/_query_editor.scss
  src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
  src/plugins/data/public/ui/query_editor/editors/shared.tsx
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/opensearch_dashboards_react/public/code_editor/__snapshots__/code_editor.test.tsx.snap
  src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.test.tsx
  src/plugins/vis_type_timeline/public/components/timeline_expression_input.tsx
  yarn.lock
Labels: seasoned-contributor, failed changeset

#9606 feat: add wanglam as maintainer of OSD
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: Skip-Changelog, distinguished-contributor

#9531 [Discover] Remove the "newExperience" table option in Discover
  changelogs/fragments/9531.yml
  src/plugins/discover/public/application/components/data_grid/_data_grid_table.scss
  src/plugins/discover/public/application/components/data_grid/data_grid.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_actions.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.test.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_context.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_inspect_button.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
  src/plugins/discover/public/application/components/data_grid/data_grid_toolbar.tsx
  src/plugins/discover/public/application/components/discover_options/discover_options.tsx
  src/plugins/discover/public/application/components/doc_views/context_app.tsx
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.test.tsx
  src/plugins/discover/public/application/components/results_action_bar/results_action_bar.tsx
  src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
  src/plugins/discover/public/application/view_components/canvas/index.tsx
  src/plugins/discover/public/embeddable/search_embeddable_component.tsx
  test/functional/apps/context/_context_navigation.js
  test/functional/apps/context/_date_nanos.js
  test/functional/apps/context/_date_nanos_custom_timestamp.js
  test/functional/apps/context/_discover_navigation.js
  test/functional/apps/context/_filters.js
  test/functional/apps/context/_size.js
  test/functional/apps/context/index.js
  test/functional/apps/dashboard/dashboard_filter_bar.js
  test/functional/apps/dashboard/dashboard_filtering.js
  test/functional/apps/dashboard/dashboard_query_bar.js
  test/functional/apps/dashboard/dashboard_state.js
  test/functional/apps/management/_scripted_fields.js
  test/functional/config.js
  test/functional/page_objects/discover_page.ts
  test/functional/services/doc_table.ts
  test/plugin_functional/test_suites/doc_views/doc_views.ts
Labels: all-star-contributor

#9627 update promql autocomplete with better representation of suggestions
  src/plugins/data/public/antlr/dql/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
  src/plugins/data/public/antlr/promql/code_completion.ts
  src/plugins/data/public/antlr/promql/constants.ts
  src/plugins/data/public/antlr/promql/promql_autocomplete.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
  src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
  src/plugins/data/public/index.ts
  src/plugins/data/public/resources/resource_client_factory.ts
  src/plugins/data/public/ui/query_editor/query_editor.tsx
  src/plugins/discover/public/application/view_components/utils/use_prometheus.ts
Labels: seasoned-contributor, failed changeset

#9623 Bump vega from 5.23.0 to 5.32.0
  changelogs/fragments/9623.yml
  package.json
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/vis_type_vega/public/lib/vega.js
  src/plugins/vis_type_vega/public/vega_request_handler.ts
  yarn.lock
Labels: cve, v3.0.0, distinguished-contributor
