Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-09, with the labels that each got.

#10478 Moving Data Importer to Data Administration under settings
  changelogs/fragments/10478.yml
  src/plugins/data_importer/common/constants.ts
  src/plugins/data_importer/public/plugin.ts
Labels: repeat-contributor

#10467 [visTypeVega] Fix vega tooltip flashing
  changelogs/fragments/10467.yml
  src/plugins/vis_type_vega/public/vega_view/vega_base_view.js
  src/plugins/vis_type_vega/public/vega_view/vega_tooltip.js
Labels: distinguished-contributor, vega

#10465 [Explore] add histogram
  changelogs/fragments/10465.yml
  src/plugins/explore/public/components/visualizations/bar/bar_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/bar/bar_chart_utils.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bucket_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bucket_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/collections.ts
Labels: distinguished-contributor

#10482 [Explore] Metric viz style update
  changelogs/fragments/10482.yml
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/metric/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/percentage/percentage_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/percentage/percentage_selector.tsx
  src/plugins/explore/public/components/visualizations/style_panel/value/value_calculation_selector.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/value/value_calculation_selector.tsx
  src/plugins/explore/public/components/visualizations/theme/color_palettes.ts
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/calculation.test.ts
  src/plugins/explore/public/components/visualizations/utils/calculation.ts
  src/plugins/explore/public/components/visualizations/utils/utils.test.ts
  src/plugins/explore/public/components/visualizations/utils/utils.ts
Labels: distinguished-contributor

#10451 [Explore] Add gauge vis
  changelogs/fragments/10451.yml
  src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
  src/plugins/explore/public/components/visualizations/area/to_expression.ts
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/to_expression.ts
  src/plugins/explore/public/components/visualizations/constants.ts
  src/plugins/explore/public/components/visualizations/gauge/gauge_chart_utils.test.ts
  src/plugins/explore/public/components/visualizations/gauge/gauge_chart_utils.ts
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_config.ts
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.stories.tsx
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.tsx
  src/plugins/explore/public/components/visualizations/gauge/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/gauge/to_expression.ts
  src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/line/to_expression.ts
  src/plugins/explore/public/components/visualizations/rule_repository.test.ts
  src/plugins/explore/public/components/visualizations/rule_repository.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_custom_values.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_custom_values.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_panel.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_panel.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/threshold.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/threshold.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/threshold.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/utils.test.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/utils.ts
  src/plugins/explore/public/components/visualizations/style_panel/utils.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/use_debounced_value.ts
  src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
  src/plugins/explore/public/components/visualizations/visualization_registry.ts
Labels: distinguished-contributor

#10471 chore: remove obsolete Web API polyfills
  changelogs/fragments/10471.yml
  package.json
  packages/osd-ui-shared-deps/package.json
  packages/osd-ui-shared-deps/polyfills.js
  src/dev/jest/setup/polyfills.js
  src/plugins/data/server/lib/get_request_aborted_signal.ts
  yarn.lock
Labels: first-time-contributor

#10483 [Explore] Update dataset interface in fields selector component
  changelogs/fragments/10483.yml
  src/core/public/mocks.ts
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/explore/public/components/fields_selector/discover_field.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_bucket.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_details.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_details.tsx
  src/plugins/explore/public/components/fields_selector/discover_field_header.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx
  src/plugins/explore/public/components/fields_selector/discover_sidebar.tsx
  src/plugins/explore/public/components/fields_selector/facet_field.test.tsx
  src/plugins/explore/public/components/fields_selector/facet_field.tsx
  src/plugins/explore/public/components/fields_selector/facet_list.test.tsx
  src/plugins/explore/public/components/fields_selector/facet_list.tsx
  src/plugins/explore/public/components/fields_selector/facet_value.tsx
  src/plugins/explore/public/components/fields_selector/field_list.test.tsx
  src/plugins/explore/public/components/fields_selector/field_list.tsx
  src/plugins/explore/public/components/fields_selector/fields_selector_panel.tsx
  src/plugins/explore/public/components/fields_selector/lib/field_calculator.test.ts
  src/plugins/explore/public/components/fields_selector/lib/field_calculator.ts
  src/plugins/explore/public/components/fields_selector/lib/field_filter.ts
  src/plugins/explore/public/components/fields_selector/lib/get_details.ts
  src/plugins/explore/public/components/fields_selector/lib/get_index_pattern_field_list.ts
  src/plugins/explore/public/components/fields_selector/lib/get_warnings.ts
  src/plugins/explore/public/components/fields_selector/lib/group_fields.ts
  src/plugins/explore/public/components/fields_selector/lib/visualize_trigger_utils.ts
Labels: distinguished-contributor

#10500 [Traces] Add tests for Traces Page
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces_sanity.spec.js
  cypress/utils/commands.explore.js
  cypress/utils/commands.osd.js
  cypress/utils/index.d.ts
Labels: Skip-Changelog, distinguished-contributor

#10504 Trace:Details Cypress testing
  changelogs/fragments/10504.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces_sanity.spec.js
Labels: seasoned-contributor

#10503 Add PPL Formatter
  changelogs/fragments/10503.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/recent_queries.spec.js
  cypress/utils/apps/explore/autocomplete.js
  cypress/utils/apps/explore/shared_links.js
  packages/osd-monaco/src/monaco.ts
  packages/osd-monaco/src/ppl/formatter.test.ts
  packages/osd-monaco/src/ppl/formatter.ts
  packages/osd-monaco/src/ppl/language.ts
  src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/editor_options/query_editor_options.ts
Labels: distinguished-contributor

#10516 [Explore] Add show raw data toggle
  changelogs/fragments/10516.yml
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.test.tsx
  src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis.tsx
  src/plugins/explore/public/components/visualizations/visualization_builder.test.ts
  src/plugins/explore/public/components/visualizations/visualization_builder.ts
  src/plugins/explore/public/components/visualizations/visualization_render.test.tsx
  src/plugins/explore/public/components/visualizations/visualization_render.tsx
Labels: valued-contributor

#10399 Add route path to request
  CHANGELOG.md
  src/legacy/server/logging/log_format.js
Labels: Skip-Changelog, repeat-contributor

#10512 [Explore] refactor explore viz debounced input
  src/plugins/explore/public/components/visualizations/add_to_dashboard_modal.tsx
  src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
  src/plugins/explore/public/components/visualizations/bar/bucket_options.test.tsx
  src/plugins/explore/public/components/visualizations/bar/bucket_options.tsx
  src/plugins/explore/public/components/visualizations/constants.ts
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_exclusive_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/line/line_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/to_expression.ts
  src/plugins/explore/public/components/visualizations/pie/pie_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/pie/to_expression.ts
  src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.tsx
  src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/axes.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/standard_axes_options.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/axes/standard_axes_options.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_custom_values.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_panel.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_panel.tsx
  src/plugins/explore/public/components/visualizations/style_panel/title/title.tsx
  src/plugins/explore/public/components/visualizations/style_panel/utils.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis_config.ts
  src/plugins/explore/public/components/visualizations/table/table_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/table/table_vis_options.tsx
  src/plugins/explore/public/components/visualizations/types.ts
  src/plugins/explore/public/components/visualizations/utils/font_size_input_field.tsx
  src/plugins/explore/public/components/visualizations/utils/to_expression.ts
  src/plugins/explore/public/components/visualizations/utils/use_debounced_value.test.ts
  src/plugins/explore/public/components/visualizations/utils/use_debounced_value.ts
Labels: distinguished-contributor

#10497 [Explore]add units panel for gauge and metric
  changelogs/fragments/10497.yml
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_config.test.tsx
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_config.ts
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.tsx
  src/plugins/explore/public/components/visualizations/gauge/to_expression.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
  src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
  src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/metric/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/unit/collection.test.ts
  src/plugins/explore/public/components/visualizations/style_panel/unit/collection.ts
  src/plugins/explore/public/components/visualizations/style_panel/unit/style.scss
  src/plugins/explore/public/components/visualizations/style_panel/unit/unit_panel.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/unit/unit_panel.tsx
  src/plugins/explore/public/components/visualizations/types.ts
Labels: distinguished-contributor

#10528 fix: make global setting nullable when getting / updating workspace scope settings
  changelogs/fragments/10528.yml
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: distinguished-contributor

#10532 Fix result table error ui
  changelogs/fragments/10532.yml
  src/plugins/explore/public/components/tabs/error_guard/error_guard.tsx
Labels: seasoned-contributor

#10485 [Query enhancements] support custom component to create data structure
  src/plugins/data/common/datasets/types.ts
  src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx
  src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
Labels: distinguished-contributor, failed changeset

#10535 [Explore] Patterns Calcite workarounds
  changelogs/fragments/10535.yml
  src/plugins/explore/public/components/patterns_table/patterns_container.tsx
  src/plugins/explore/public/components/patterns_table/utils/constants.ts
  src/plugins/explore/public/components/patterns_table/utils/utils.test.ts
  src/plugins/explore/public/components/patterns_table/utils/utils.ts
Labels: all-star-contributor

#10537 [Explore] bring up sample queries
  src/plugins/explore/public/application/legacy/discover/application/components/no_results/no_results.scss
  src/plugins/explore/public/application/legacy/discover/application/components/no_results/no_results.tsx
Labels: Skip-Changelog, distinguished-contributor

#10540 [Explore] Patterns tab Error Handling updates
  changelogs/fragments/10540.yml
  src/plugins/explore/public/application/register_tabs.ts
  src/plugins/explore/public/components/patterns_table/utils/utils.test.ts
  src/plugins/explore/public/components/patterns_table/utils/utils.ts
  src/plugins/explore/public/components/tabs/error_guard/error_guard.tsx
  src/plugins/explore/public/components/tabs/error_guard/patterns_error_guard.test.tsx
  src/plugins/explore/public/components/tabs/error_guard/patterns_error_guard.tsx
  src/plugins/explore/public/components/tabs/patterns_tab.tsx
Labels: all-star-contributor

#10536 Update Simplified PPL grammar to latest version
  changelogs/fragments/10536.yml
  cypress/utils/apps/explore/autocomplete.js
  package.json
  packages/osd-antlr-grammar/package.json
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLLexer.interp
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLLexer.tokens
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLLexer.ts
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLParser.interp
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLParser.tokens
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLParser.ts
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/.generated/OpenSearchPPLParserVisitor.ts
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/grammar/OpenSearchPPLLexer.g4
  packages/osd-antlr-grammar/src/opensearch_ppl_simplified/grammar/OpenSearchPPLParser.g4
  packages/osd-monaco/package.json
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/constants.ts
  src/plugins/data/public/antlr/opensearch_ppl/simplified_ppl_grammar/opensearch_ppl_autocomplete.test.ts
  src/plugins/data/public/antlr/opensearch_ppl/simplified_ppl_grammar/opensearch_ppl_autocomplete.ts
  src/plugins/data/public/antlr/opensearch_ppl/simplified_ppl_grammar/symbol_table_parser.ts
  src/plugins/data/public/antlr/opensearch_sql/parse.ts
  src/plugins/data/public/antlr/shared/types.ts
  src/plugins/data/public/antlr/shared/utils.ts
  yarn.lock
Labels: distinguished-contributor

#10551 Bump version to 2.19.4
  package.json
Labels: failed changeset

#10548 [Explore] add a flag to config discover vis theme from localStorage for development
  changelogs/fragments/10548.yml
  src/plugins/explore/public/components/visualizations/theme/default_colors.ts
Labels: distinguished-contributor

#10557 [Explore] show query panel even if there are no datasets
  changelogs/fragments/10557.yml
  src/plugins/explore/public/application/pages/logs/logs_page.tsx
Labels: distinguished-contributor

#10573 [Explore] backtick the dataset name when source=* and describe=* is omitted
  changelogs/fragments/10573.yml
  src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
Labels: distinguished-contributor

#10565 Trace:Details Update span table flyout button
  changelogs/fragments/10565.yml
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_panel.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.scss
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.tsx
Labels: repeat-contributor

#10584 Fix inconsistent icons in table fields
  changelogs/fragments/10584.yml
  src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/default_discover_table/table_cell.tsx
  src/plugins/explore/public/components/data_table/table_cell/table_cell.tsx
Labels: seasoned-contributor

#10579 [Explore Vis]fix value options sum in gauge and metric panels are not working
  changelogs/fragments/10579.yml
  src/plugins/explore/public/components/visualizations/gauge/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/gauge/to_expression.ts
  src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
  src/plugins/explore/public/components/visualizations/metric/to_expression.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_utils.test.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold_utils.ts
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/threshold.stories.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/threshold.test.tsx
  src/plugins/explore/public/components/visualizations/style_panel/threshold_lines/threshold.tsx
Labels: distinguished-contributor

#10587 Update limits for lighthouse and bundle
  baselines/lighthouse_baseline.json
  packages/osd-optimizer/limits.yml
Labels: Skip-Changelog, all-star-contributor

#10590 vis(vega): default set flag exposeDebugObjectToWindow to true
  changelogs/fragments/10590.yml
  src/plugins/vis_type_vega/config.ts
Labels: distinguished-contributor

#10598 Fix source command detection if we have a field expression before source
  changelogs/fragments/10598.yml
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
Labels: distinguished-contributor, OSD

#10588 Make explore experience default
  changelogs/fragments/10588.yml
  config/opensearch_dashboards.yml
  src/plugins/explore/server/index.ts
Labels: distinguished-contributor, OSD
