Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-05, with the labels that each got.

#9742 [Fix Failing CI] Disable Concurrent Segment Search for OpenSearch in CI
  .github/workflows/cypress_workflow.yml
  test/common/config.js
Labels: distinguished-contributor

#9732 update storybook to the latest v6
  package.json
  packages/osd-storybook/package.json
  yarn.lock
Labels: Skip-Changelog, all-star-contributor

#9724 [explore] add plugin
  changelogs/fragments/9724.yml
  docs/_sidebar.md
  package.json
  src/dev/storybook/aliases.ts
  src/plugins/explore/.storybook/main.js
  src/plugins/explore/.storybook/preview.ts
  src/plugins/explore/README.md
  src/plugins/explore/common/index.ts
  src/plugins/explore/config.ts
  src/plugins/explore/opensearch_dashboards.json
  src/plugins/explore/public/application.tsx
  src/plugins/explore/public/components/app.tsx
  src/plugins/explore/public/index.scss
  src/plugins/explore/public/index.ts
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/public/types.ts
  src/plugins/explore/server/index.ts
  src/plugins/explore/server/plugin.ts
  src/plugins/explore/server/routes/index.ts
  src/plugins/explore/server/types.ts
Labels: distinguished-contributor, discover-next, explore

#9738 Performance scripts fix
  .github/workflows/lighthouse_testing.yml
  .github/workflows/performance_testing.yml
  baselines/lighthouse_baseline.json
  changelogs/fragments/9738.yml
  packages/osd-optimizer/limits.yml
Labels: valued-contributor

#9771 [Documentation] Update 3.0 Release Notes
  CHANGELOG.md
  changelogs/fragments/9409.yml
  changelogs/fragments/9602.yml
  changelogs/fragments/9605.yml
  changelogs/fragments/9625.yml
  changelogs/fragments/9651.yml
  changelogs/fragments/9662.yml
  changelogs/fragments/9694.yml
  changelogs/fragments/9696.yml
  changelogs/fragments/9697.yml
  changelogs/fragments/9700.yml
  changelogs/fragments/9701.yml
  changelogs/fragments/9730.yml
  release-notes/opensearch-dashboards.release-notes-3.0.0.md
Labels: Skip-Changelog, all-star-contributor, backport 3.0

#9734 Fix collaborators displays under custom tab on left navigation when saved object permission is disabled
  changelogs/fragments/9734.yml
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor

#9703 Add validation for deleted data source in default index pattern
  changelogs/fragments/9703.yml
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.test.ts
  src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
Labels: first-time-contributor

#9205 Support path alias for webpack and babel
  packages/osd-babel-preset/node_preset.js
  packages/osd-babel-preset/package.json
  packages/osd-optimizer/src/worker/bundle_refs_plugin.ts
  packages/osd-optimizer/src/worker/webpack.config.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  tsconfig.base.json
  yarn.lock
Labels: all-star-contributor

#9611 fixed an issue that the initial result summary generated with the wrong data
  changelogs/fragments/9611.yml
  src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
Labels: all-star-contributor

#9723 [Fix] filter out Opensearch Data sources in Associate Direct Query Sources Modal
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx
  src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
Labels: distinguished-contributor

#9735 Fix chatbot flyout cannot be resized beyond the window size
  changelogs/fragments/9735.yml
  src/core/public/overlays/sidecar/components/resizable_button.test.tsx
  src/core/public/overlays/sidecar/components/resizable_button.tsx
  src/core/public/overlays/sidecar/helper.ts
  src/core/public/overlays/sidecar/sidecar_service.tsx
Labels: valued-contributor

#9707 Add the support for new OpenSearch type match_only_text/wildcard
  changelogs/fragments/9707.yml
  src/plugins/data/common/osd_field_types/osd_field_types_factory.ts
  src/plugins/data/common/osd_field_types/types.ts
Labels: distinguished-contributor

#9784 fix path alias not working for distribution builds
  changelogs/fragments/9784.yml
  packages/osd-babel-preset/node_preset.js
  src/dev/build/tasks/transpile_babel_task.ts
Labels: all-star-contributor

#9790 Update base line error list to fix CI
  src/plugins/workspace/server/workspace_client.mock.ts
  ts_error_baseline.json
Labels: Skip-Changelog, seasoned-contributor

#9789 bump 3.1.0
  changelogs/fragments/9789.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js
  package.json
Labels: all-star-contributor

#9773 [Explore] support explore feature flag and workspace types
  changelogs/fragments/9773.yml
  src/core/public/index.ts
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/explore/common/config.ts
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/server/index.ts
  src/plugins/explore/server/plugin.ts
  src/plugins/explore/server/routes/index.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/common/utils.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/server/routes/index.ts
Labels: discover, all-star-contributor, explore

#9799 Update baseline TS error
  ts_error_baseline.json
Labels: Skip-Changelog, seasoned-contributor

#9804 [Discover] Fix scroll bar not showing up for dataset table
  src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss
Labels: Skip-Changelog, all-star-contributor

#9726 [workspace] support multiple-scopes ui settings
  changelogs/fragments/9726.yml
  src/core/public/ui_settings/__snapshots__/ui_settings_api.test.ts.snap
  src/core/public/ui_settings/__snapshots__/ui_settings_client.test.ts.snap
  src/core/public/ui_settings/types.ts
  src/core/public/ui_settings/ui_settings_api.test.ts
  src/core/public/ui_settings/ui_settings_api.ts
  src/core/public/ui_settings/ui_settings_client.test.ts
  src/core/public/ui_settings/ui_settings_client.ts
  src/core/public/ui_settings/ui_settings_service.mock.ts
  src/core/public/ui_settings/ui_settings_service.test.ts
  src/core/public/ui_settings/ui_settings_service.ts
  src/core/server/index.ts
  src/core/server/ui_settings/index.ts
  src/core/server/ui_settings/routes/get.ts
  src/core/server/ui_settings/routes/set_many.ts
  src/core/server/ui_settings/ui_settings_client.test.ts
  src/core/server/ui_settings/ui_settings_client.ts
  src/core/server/ui_settings/utils.ts
  src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap
  src/plugins/advanced_settings/public/management_app/advanced_settings.test.tsx
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
  src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
  src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
  src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/__snapshots__/data_source_multi_selectable.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
  src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
  src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
  src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
  src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
  src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
  src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
  src/plugins/data_source_management/public/components/utils.test.ts
  src/plugins/data_source_management/public/components/utils.ts
  src/plugins/data_source_management/public/mocks.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_ui_settings_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
  src/plugins/workspace/server/ui_settings.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: all-star-contributor

#9777 [State Management Framework] Add Base Implementation, Utils, Hooks & Examples
  changelogs/fragments/9777.yml
  docs/_sidebar.md
  examples/state_management_example/.i18nrc.json
  examples/state_management_example/README.md
  examples/state_management_example/common/index.ts
  examples/state_management_example/opensearch_dashboards.json
  examples/state_management_example/package.json
  examples/state_management_example/public/application.tsx
  examples/state_management_example/public/components/app.tsx
  examples/state_management_example/public/components/index.ts
  examples/state_management_example/public/components/state_backends_demo.tsx
  examples/state_management_example/public/index.scss
  examples/state_management_example/public/index.ts
  examples/state_management_example/public/observable_counter_service.ts
  examples/state_management_example/public/plugin.ts
  examples/state_management_example/public/redux_counter_service.ts
  examples/state_management_example/public/state/counter_actions.ts
  examples/state_management_example/public/state/counter_selector.ts
  examples/state_management_example/public/state/counter_service_factory.ts
  examples/state_management_example/public/state/counter_state.ts
  examples/state_management_example/public/state/index.ts
  examples/state_management_example/public/state/redux_counter_service.ts
  examples/state_management_example/public/types.ts
  examples/state_management_example/translations/ja-JP.json
  examples/state_management_example/tsconfig.json
  package.json
  src/plugins/opensearch_dashboards_react/public/index.ts
  src/plugins/opensearch_dashboards_react/public/state_management/README.md
  src/plugins/opensearch_dashboards_react/public/state_management/context/index.ts
  src/plugins/opensearch_dashboards_react/public/state_management/context/plugin_store_context.tsx
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/hooks.test.tsx
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/index.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/mocks/index.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/mocks/test_actions.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/mocks/test_selectors.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/mocks/test_state.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/use_actions.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/use_plugin_keys.ts
  src/plugins/opensearch_dashboards_react/public/state_management/hooks/use_selector.ts
  src/plugins/opensearch_dashboards_react/public/state_management/index.ts
  src/plugins/opensearch_dashboards_react/public/state_management/store/action_selector_store.ts
  src/plugins/opensearch_dashboards_react/public/state_management/store/global_store.ts
  src/plugins/opensearch_dashboards_react/public/state_management/store/index.ts
  src/plugins/opensearch_dashboards_utils/common/index.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/base_action.test.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/base_action.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/base_selector.test.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/base_selector.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/index.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/mocks/mock_actions.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/mocks/mock_selector.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/mocks/mock_state_adapter.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/state_adapter.test.ts
  src/plugins/opensearch_dashboards_utils/common/state_management/state_adapter.ts
  src/plugins/opensearch_dashboards_utils/public/index.ts
  yarn.lock
Labels: distinguished-contributor

#9783 Add doc viewer component to explore plugin
  .lycheeignore
  package.json
  packages/osd-storybook/package.json
  packages/osd-storybook/webpack.config.ts
  packages/osd-stylelint-config/config/global_selectors.json
  packages/osd-stylelint-config/config/restricted_properties.json
  src/.i18nrc.json
  src/plugins/discover/public/__mock__/index_pattern_mock.ts
  src/plugins/discover/public/index.ts
  src/plugins/explore/.storybook/preview.ts
  src/plugins/explore/public/components/doc_viewer/doc_viewer.scss
  src/plugins/explore/public/components/doc_viewer/doc_viewer.stories.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer.test.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_tab/doc_viewer_render_error.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_tab/doc_viewer_render_tab.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_tab/doc_viewer_tab.test.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_tab/doc_viewer_tab.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table.scss
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table.test.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/field_name/field_name.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/field_name/field_type_name.ts
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_btn_collapse.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_btn_filter_add.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_btn_filter_exists.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_btn_filter_remove.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_btn_toggle_column.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_container.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_icon_no_mapping.tsx
  src/plugins/explore/public/components/doc_viewer/doc_viewer_table/table_row/table_row_icon_underscore.tsx
  src/plugins/explore/public/components/doc_viewer/json_code_block/json_code_block.tsx
  src/plugins/explore/public/helpers/shorten_dotted_string.ts
  src/plugins/explore/public/types/doc_views_types.ts
  yarn.lock
Labels: discover, Skip-Changelog, seasoned-contributor, explore

#9809 [Explore] Update explore plugin to make saved explore objects work correctly
  changelogs/fragments/9809.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/saved_explore.spec.js
  cypress/utils/apps/explore/saved.js
  cypress/utils/index.d.ts
  src/plugins/content_management/public/constants.ts
  src/plugins/explore/public/application/legacy/discover/application/components/data_grid/data_grid_table.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/default_discover_table/default_discover_table.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/default_discover_table/table_header.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/default_discover_table/table_header_column.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/doc_views/context_app.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
  src/plugins/explore/public/application/legacy/discover/application/components/top_nav/open_search_panel.tsx
  src/plugins/explore/public/application/legacy/discover/application/utils/state_management/discover_slice.test.tsx
  src/plugins/explore/public/application/legacy/discover/application/utils/state_management/discover_slice.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/discover_table.tsx
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/get_default_sort.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/get_sort_for_search_source.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/update_search_source.ts
  src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_search.ts
  src/plugins/explore/public/application/legacy/discover/build_services.ts
  src/plugins/explore/public/application/legacy/discover/embeddable/search_embeddable.tsx
  src/plugins/explore/public/application/legacy/discover/embeddable/types.ts
  src/plugins/explore/public/application/legacy/discover/index.ts
  src/plugins/explore/public/application/legacy/discover/mocks.ts
  src/plugins/explore/public/application/legacy/discover/opensearch_dashboards_services.ts
  src/plugins/explore/public/application/legacy/discover/saved_searches/_saved_search.ts
  src/plugins/explore/public/application/legacy/discover/saved_searches/index.ts
  src/plugins/explore/public/application/legacy/discover/saved_searches/saved_searches.ts
  src/plugins/explore/public/application/legacy/discover/saved_searches/types.ts
  src/plugins/explore/public/application/legacy/discover/types.ts
  src/plugins/explore/public/application/legacy/discover/url_generator.ts
  src/plugins/explore/public/index.ts
  src/plugins/explore/public/plugin.ts
  src/plugins/explore/public/saved_explore/_saved_explore.ts
  src/plugins/explore/public/saved_explore/index.ts
  src/plugins/explore/public/saved_explore/saved_explore.ts
  src/plugins/explore/public/saved_explore/types.ts
  src/plugins/explore/public/url_generator.test.ts
  src/plugins/explore/public/url_generator.ts
  src/plugins/explore/server/capabilities_provider.ts
  src/plugins/explore/server/plugin.ts
  src/plugins/explore/server/saved_objects/search.ts
  src/plugins/saved_objects_management/opensearch_dashboards.json
  src/plugins/saved_objects_management/public/lib/in_app_url.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/saved_objects_management/public/register_services.ts
  ts_error_baseline.json
Labels: v3.0.0, all-star-contributor

#9770 Add resource API pattern
  changelogs/fragments/9770.yml
  src/plugins/query_enhancements/server/connections/managers/base_connection_manager.ts
  src/plugins/query_enhancements/server/connections/resource_manager_service.test.ts
  src/plugins/query_enhancements/server/connections/resource_manager_service.ts
  src/plugins/query_enhancements/server/plugin.ts
  src/plugins/query_enhancements/server/routes/index.ts
  src/plugins/query_enhancements/server/routes/resources/index.ts
  src/plugins/query_enhancements/server/routes/resources/routes.test.ts
  src/plugins/query_enhancements/server/routes/resources/routes.ts
  src/plugins/query_enhancements/server/types.ts
  ts_error_baseline.json
Labels: enhancement, discover, first-time-contributor, explore

#9818 Feature: deprecate showInAllNavGroup property
  changelogs/fragments/9818.yml
  src/core/public/chrome/nav_group/nav_group_service.test.ts
  src/core/public/chrome/nav_group/nav_group_service.ts
  src/plugins/home/public/plugin.test.ts
  src/plugins/home/public/plugin.ts
Labels: distinguished-contributor

#9827 [Explore] fix download_csv for explore
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/download_csv.spec.js
  cypress/utils/apps/explore/download_csv.js
Labels: Skip-Changelog, all-star-contributor, explore
