Repository opensearch-project/OpenSearch-Dashboards, pull requests merged in 2025-10, with the labels that each got.

#10611 Discover:Traces feature flag and bug fixes
  .github/workflows/cypress_workflow.yml
  changelogs/fragments/10611.yml
  config/opensearch_dashboards.yml
  package.json
  src/plugins/explore/common/config.ts
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/ppl_resolve_helpers.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/ppl_to_trace_hits.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/trace_detail_tabs.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/trace_detail_tabs.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/trace_view.tsx
  src/plugins/explore/public/application/pages/traces/traces_page.tsx
  src/plugins/explore/public/components/doc_viewer/trace_details_view/trace_details_view.tsx
  src/plugins/explore/public/plugin.ts
Labels: seasoned-contributor

#10613 Fix CI/CD failure: Cannot find module @osd/optimizer/target/cli
  changelogs/fragments/10613.yml
  packages/osd-optimizer/src/worker/run_worker.ts
  scripts/build_opensearch_dashboards_platform_plugins.js
Labels: ci, distinguished-contributor, v3.3.0, OSD

#10608 Trace:Details Handle undefined items in span table
  changelogs/fragments/10608.yml
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.tsx
Labels: repeat-contributor, OSD

#10583 Add Query Snippet Suggestions
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
  cypress/utils/apps/explore/autocomplete.js
  src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
  src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
  src/plugins/data/public/plugin.ts
  src/plugins/data/public/query_snippet_suggestions/ppl/suggestions.test.ts
  src/plugins/data/public/query_snippet_suggestions/ppl/suggestions.ts
  src/plugins/data/public/query_snippet_suggestions/types.ts
  src/plugins/data/public/query_snippet_suggestions/utils.test.ts
  src/plugins/data/public/query_snippet_suggestions/utils.ts
  src/plugins/data/public/services.ts
Labels: distinguished-contributor, OSD

#10621 Fix Column Value Caching for Autocomplete
  changelogs/fragments/10621.yml
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
  src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
Labels: distinguished-contributor, OSD

#10622 Enhance explore modal UI with local storage logic
  changelogs/fragments/10622.yml
  src/plugins/explore/server/index.ts
  src/plugins/home/public/application/components/explore_experience.tsx
  src/plugins/home/public/application/components/home_app.js
Labels: distinguished-contributor, v3.3.0

#10624 chat(feat): mark context provider and chat as experimental
  changelogs/fragments/10624.yml
  src/plugins/chat/README.md
  src/plugins/chat/public/index.ts
  src/plugins/chat/public/plugin.ts
  src/plugins/chat/server/index.ts
  src/plugins/context_provider/README.md
  src/plugins/context_provider/public/index.ts
  src/plugins/context_provider/public/plugin.ts
Labels: distinguished-contributor, v3.3.0, ai

#10597 [explore] clear editor after datset change
  changelogs/fragments/10597.yml
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.test.tsx
  src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.tsx
Labels: distinguished-contributor, OSD

#10595 be able to update console_polling through the UI
  changelogs/fragments/10595.yml
  src/plugins/console/public/application/containers/settings.tsx
Labels: backport 2.x, distinguished-contributor, OSD

#10618 Bumps cypress-request to 3.0.9
  changelogs/fragments/10618.yml
  package.json
  yarn.lock
Labels: cve, repeat-contributor, v3.3.0, backport 3.3

#10629 feat(trace-details): improve timeline loading state with spinner
  changelogs/fragments/10629.yml
  src/plugins/explore/public/components/doc_viewer/trace_details_view/trace_details_view.tsx
Labels: first-time-contributor, OSD

#10582 Fix focus add/remove column
  changelogs/fragments/10582.yml
  src/plugins/explore/public/components/fields_selector/field_list.tsx
Labels: seasoned-contributor, OSD

#10599 Fix Breadcrumb floating issue
  changelogs/fragments/10599.yml
  src/core/public/chrome/ui/header/header.scss
Labels: all-star-contributor, OSD

#10649 Test fix CI group 4 / Cypress group 13+15
  changelogs/fragments/10649.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/inspect.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/recent_queries.spec.js
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/inspect.spec.js
  cypress/utils/apps/explore/recent_queries.js
  src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
Labels: seasoned-contributor, v3.3.0, OSD, backport 3.3

#10660 Allow more use cases for serverless collections
  changelogs/fragments/10660.yml
  src/core/public/index.ts
  src/core/utils/default_nav_groups.ts
  src/core/utils/index.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/use_form_available_use_cases.test.ts
  src/plugins/workspace/public/components/workspace_form/use_form_available_use_cases.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/services/use_case_service.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: seasoned-contributor

#10646 [Backport 2.x] be able to update console_polling through the UI
  changelogs/fragments/10595.yml
  src/plugins/console/public/application/containers/settings.tsx
Labels: failed changeset

#10661 [Explore] add backticks to source for explore
  changelogs/fragments/10661.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/saved_explore.spec.js
  src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts
  src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
  src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts
Labels: distinguished-contributor, OSD, Cypress-test

#10681 TestFix: Table.spec move CI groups
  changelogs/fragments/10681.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/table.spec.js
Labels: seasoned-contributor

#10630 Trace Details:Page header
  changelogs/fragments/10630.yml
  cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces.spec.js
  src/plugins/explore/public/application/pages/traces/trace_details/public/top_nav_buttons.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/top_nav_buttons.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/utils/helper_functions.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/public/utils/helper_functions.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/trace_view.test.tsx
  src/plugins/explore/public/application/pages/traces/trace_details/trace_view.tsx
Labels: seasoned-contributor, Cypress-test
